### ISSUE TITLE
Exception executing query when ibm_db_dbi.paramstyle = 'format' 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ibmdb/python-ibmdb#155]
```
Queries can not be formatted using 'format' paramstyle


>>> import ibm_db_dbi
>>> ibm_db_dbi.paramstyle
'qmark'
>>> ibm_db_dbi.paramstyle = 'format'
>>> conn = ibm_db_dbi.connect("db2")
>>> cursor=conn.cursor()
>>> q = 'SELECT col1,col2 FROM test WHERE col0 = %s'
>>> cursor.execute(q, (1819043,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python2.6/site-packages/ibm_db-2.0.4.1-py2.6-linux-x86_64-SP3.egg/ibm_db_dbi.py", line 1331, in execute
    self._set_cursor_helper()
  File "/usr/local/lib64/python2.6/site-packages/ibm_db-2.0.4.1-py2.6-linux-x86_64-SP3.egg/ibm_db_dbi.py", line 1214, in _set_cursor_helper
    raise self.messages[len(self.messages) - 1]
ibm_db_dbi.ProgrammingError: ibm_db_dbi::ProgrammingError: SQLNumResultCols 
failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected token "=" was 
found following "test WHERE col0".  Expected tokens may include:  
"<interval_qualifier>".  SQLSTATE=42601 SQLCODE=-104


```

Original issue reported on code.google.com by `south.mi...@gmail.com` on 12 Jun 2014 at 3:05

**Comment by kadler** [comment]
From my reading of PEP 249, apilevel, threadsafety, and paramstyle are meant to be read-only from the module. They're not meant to be set by the user. If a database API wants to be able to allow the user to change the parameter style, they need to offer some other way to do that, such as an option on connect() or a method on a Connection object.

From what I've gathered, most other implementers of PEP 249 don't allow changing the parameter style either, so not sure why we would either.

**Comment by aratic** [comment]
swapping from postgres to db2, expected to using the universal dbi from ibm_db_dbi, while found the pyformat no longer exist, question mark worked fine, guess I need to apply a wrapper when binding the statement
