### ISSUE TITLE
SQL0605W should be logged as a warning but not raised up

### ISSUE THREAD

**Issue by mriedem** [ibmdb/python-ibmdb#176]
SQL0605W is an error when trying to create a duplicate index.

The OpenStack Nova project has a database migration that fails with DB2 because there is a UniqueConstraint defined first on a column and an Index is created on the same column in the Table definition:

http://git.openstack.org/cgit/openstack/nova/tree/nova/db/sqlalchemy/api_migrations/migrate_repo/versions/001_cell_mapping.py#n28

We should just handle that error, log it and keep going.

**Comment by mriedem** [comment]
I guess alternatively we could try to handle this in sqlalchemy-migrate's DB2 module, or have some error handling translation/filter in oslo.db:

http://git.openstack.org/cgit/openstack/oslo.db/tree/oslo_db/sqlalchemy/exc_filters.py

**Comment by kadler** [comment]
I don't think this makes sense to handle that error in ibm_db/ibm_db_dbi. These are low level interfaces directly to the database. It would probably make more sense to handle such a "known" error in the SQLAlchemy adapter. You can open an issue here: https://github.com/ibmdb/python-ibmdbsa/issues
