### ISSUE TITLE
Support for django 1.8

### ISSUE THREAD

**Issue by daniloluna** [ibmdb/python-ibmdb#177]
Any milestone for django 1.8 support?

Thanks

**Comment by auvipy** [comment]
1.9 too

**Comment by jospaul1** [comment]
Development for django 1.8   is progressing  ,Expectation is to release it Mid Jan.We have not started 1.9 yet .

**Comment by mjlawrence83** [comment]
Hi, how is progress for Django 1.8 support going? Any update to the release date?

**Comment by jospaul1** [comment]
Work is completed ,we are yet to update the release notes .but the git code
is update .
It is tested in windows ,yet to test in Linux .

You can try it from git  .Official release will happen  shortly .

Regards,
Jose

**Comment by jospaul1** [comment]
Hi All,

https://pypi.python.org/pypi?:action=display&name=ibm_db_django&version=1.0.9

ibm_db_django 1.0.9 is released  ,this support django 1.8 .

Regards,
Jose

**Comment by mjlawrence83** [comment]
Thank you Jose

**Comment by kadler** [comment]
@jospaul1 I don't see the code on GitHub. [CHANGES](https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db_django/CHANGES) still shows 1.0.7 and [__init.py__](https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db_django/ibm_db_django/__init__.py) still shows 1.0.8.

**Comment by jospaul1** [comment]
Version  is  updated in release ,will update the git too .
