### ISSUE TITLE
Add binary support for Python 3.5

### ISSUE THREAD

**Issue by dr-leo** [ibmdb/python-ibmdb#201]
The current src Distribution (v2.0.6) has .pyd files up to python 3.4. 

Binaries for py3.5 are needed. So pls do a new release.

**Comment by ibmdb** [comment]
New release is in our pipeline.

**Comment by dr-leo** [comment]
Hi,

can you already anticipate the date for the release including Windows binary for Python
 3.5?

Please apologize my stubbernness. But my colleagues are working with Python 3.5 on Windows and are blocked by lack of Support for this platform. And our security Guidelines and resource constraints make it cumbersome to install new Software every week.  
 
On a separate note, the IBM_DBSA package does not Support Python3 either, even though there is a PR for this. Moreover, there is a Long Standing bug in IBM_DBSA regarding CAST expressions. Neither seems to have so far prompted any reaction. From a large customer's viewpoint I would very much appreciate better responsiveness and maintenance.

Thanks.
