### ISSUE TITLE
Add support for SSL in ibm-db-django

### ISSUE THREAD

**Issue by Jamstah** [ibmdb/python-ibmdb#202]
I need to be able to connect my django application to a DB2 database that is using SSL security.

**Comment by Jamstah** [comment]
On investigation, there is a workaround here. I'm not sure if its on purpose or not. If you specify a dsn in OPTIONS it gets merged into the kwargs that are given to connect, so you can override the DSN

DATABASES = {
    'default': {
        'ENGINE': 'ibm_db_django',
        'NAME': 'DB',
        'USER': 'application',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '50000',
        'OPTIONS': {
            'dsn': 'DATABASE=DB;HOSTNAME=localhost;PORT=50001;PROTOCOL=TCPIP;SECURITY=SSL;SSLCLIENTKEYSTOREDB=/path/to/db2client.kdb;SSLCLIENTKEYSTASH=/path/to/db2client.sth;'
        }
    }
}

Its a workaround not a solution, but will keep me going for now.

**Comment by Davin-IBM** [comment]
I need this functionality to be supported as well.  +1

**Comment by kadler** [comment]
This issue was moved to ibmdb/python-ibmdb-django#4
