### ISSUE TITLE
Case insensitive queries do not work

### ISSUE THREAD

**Issue by nhardman** [ibmdb/python-ibmdb#211]
Using ibm_db_django 1.0.9.2  I can query a db table using the icontains filter, however it only works if the icontains value is made uppercase first. The first query returns a tuple with two objects, the second query returns an empty tuple. I would expect both queries to give the same result.
See the results of an interactive session below.

Within the ObjectStatus model, object_status_name was defined like so:
object_status_name = models.CharField(unique=True, max_length=255)

python manage.py shell
Python 2.7.5 (default, Feb 11 2014, 07:46:25) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-13)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)

>>> from core.models import *
>>> ObjectStatus.objects.all()
`[<ObjectStatus: Available>, <ObjectStatus: Expired>, <ObjectStatus: Unavailable>]
>>> ObjectStatus.objects.filter(object_status_name__icontains='AVAILABLE')
[<ObjectStatus: Available>, <ObjectStatus: Unavailable>]
>>> ObjectStatus.objects.filter(object_status_name__icontains='available')
[]`
>>>

**Comment by SabaKauser** [comment]
Fixed in github.
