### ISSUE TITLE
"Column information cannot be retrieved" - error after reconnecting to database

### ISSUE THREAD

**Issue by lintonv** [ibmdb/python-ibmdb#212]
**Here is the code Path:**
In Python Flask webserver - 

**STEP 1 -  connect to database, restart docker DB2 container, so check if the connection is active and reconnect**
```
if ibm_db.active(databaseConnection) is False:
    del databaseConnection
    databaseConnection = ibm_db.connect(conn_str, ' ', ' ')
```
            
**STEP 2 -  prepare statement**
```
sql_string = "select * from <table_name>"
stmt = self.ibm_db.prepare(databaseConnection, sql_string)
```

**STEP 3 -  bind parameters**
`ibm_db.bind_param(stmt, 0, "some_test_variable")`

**STEP 4 -  execute DB2 statement**
`ibm_db.execute(stmt)`

**STEP 5 - Try to fetch row**
```
if ibm_db.fetch_row(stmt) is False:
      <use ibm_db.result() to get some results - BUT FAILS BEFORE HERE>
```

Code works always when the connection is NOT reset. As soon as db2 container is restarted (or goes down) and the connection is re-established successfully, trying to fetch_row fails with the exception below. The reconnect, prepare, bind and execute all WORK and complete successfully (at least no errors are seen). But trying to fetch a row raises an exception. 

**Here is the error**
`Exception: Column information cannot be retrieved:`

**Here is the setup:**

- Running db2express in a Docker Container
https://hub.docker.com/r/ibmcom/db2express-c/

- If the container restarts and the connection to DB2 is re-established by calling "ibm_db.connect()", ibm_db.fetch_row(resource_stmt) fails

**Environment**
Name: ibm-db
Version: 2.0.6
Summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS
Home-page: http://pypi.python.org/pypi/ibm_db/
Author: IBM Application Development Team
Author-email: opendev@us.ibm.com
License: Apache License 2.0
Location: /usr/local/lib/python2.7/site-packages

**Comment by lintonv** [comment]
Adding DB2 version as well

 Database server        = DB2/LINUXX8664 10.5.5

**Comment by nleeisme** [comment]
Have you solved this issue?
I have to loop making connection to ibm_db and closure from it,
but it does not work from the 2nd loop.
If you've solved it, how?

**Comment by SabaKauser** [comment]
Can you elaborate more on the reproduction steps.
What I have understood is that you have a script that works well until the docker container is not restarted. But once you restart the docker container and run the script again, it fails while fetching.
