### ISSUE TITLE
Update method signatures for get_select_precolumns() and limit_clause() to include **kwargs

### ISSUE THREAD

**Issue by kartha01** [ibmdb/python-ibmdb#213]
While working with IBM Big SQL and an open source visualization tool called Caravel (http://airbnb.io/caravel/) using SQLAlchemy (1.0.12), we noticed some of the method  signatures under:

/usr/lib/python2.7/site-packages/ibm_db_sa-0.3.2-py2.7.egg/ibm_db_sa/base.py

need to be changed to reflect the latest SQLAlchemy:

def get_select_precolumns(self, select):
to
def get_select_precolumns(self, select, **kwargs):

def limit_clause(self, select):
to
def limit_clause(self, select, **kw):

It would useful to make these changes and create an official release, so users don't have to many make them.

**Comment by kadler** [comment]
Please open an issue under https://github.com/ibmdb/python-ibmdbsa/issues for SQLAlchemy adapter issues.
