### ISSUE TITLE
document how to secure connectivity with ssl

### ISSUE THREAD

**Issue by snowch** [ibmdb/python-ibmdb#218]
Does this library support ssl?  If so, can this be documented?

**Comment by jai11** [comment]
Well said one .. Please provide steps

**Comment by kadler** [comment]
I think this is what you're looking for: http://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.admin.sec.doc/doc/t0053518.html Refer to "CLI/ODBC client applications" section.

**Comment by snowch** [comment]
Thanks, @kadler.
