### ISSUE TITLE
iexact query fails

### ISSUE THREAD

**Issue by ericpershey** [ibmdb/python-ibmdb#219]
Queries don't seem to work with iexact.  The user('pershey') doesn't return when using __iexact. 
Setup:
Python 2.7.5
Django==1.8.9
ibm-db-django==1.0.9.2
ibm-db==2.0.7
Using Documentation from https://docs.djangoproject.com/en/1.8/ref/models/querysets/#iexact
>>> from django.contrib.auth.models import User
>>> User.objects.get(username='pershey')
('get', (), {'username': 'pershey'})
```<User: pershey>```
>>> User.objects.get(username__iexact='pershey')
('get', (), {'username__iexact': 'pershey'})
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/************************************************/virtualenv/lib/python2.7/site-packages/django/db/models/manager.py", line 128, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/************************************************/virtualenv/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: User matching query does not exist.

Interestingly upper casing it seems to work:
>>> User.objects.get(username__iexact='PERSHEY')
('get', (), {'username__iexact': 'PERSHEY'})
```<User: pershey>```

This line might be the source of the problem:
https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db_django/ibm_db_django/operations.py#L283

Below is the output using MySQL
>>> from django.contrib.auth.models import User
>>> User.objects.get(username='pershey')
```<User: pershey>```
>>> User.objects.get(username__iexact='pershey')
```<User: pershey>```

**Comment by IBMAmarPY** [comment]
Hello,
we have not yet received the PMR in RTC. However, I have a fix for the problem and I can push it to git after you have verified.
You could add the following for verification.

ibm_db_django/base.py:
    128 class DatabaseWrapper( BaseDatabaseWrapper ):
    129
    130     """
    131     This is the base class for DB2 backend support for Django. The under lying
    132     wrapper is IBM_DB_DBI (latest version can be downloaded from http://code.google.com/p/ibm-db/ or
    133     http://pypi.python.org/pypi/ibm_db).
    134     """
    135     data_types={}
    136     vendor = 'DB2'
    137     operators = {
    138         "exact":        "= %s",
   -139         "iexact":       "LIKE %s ESCAPE '\\'",
  **+139         "iexact":       "LIKE upper(%s) ESCAPE '\\'",** 

Awaiting your confirmation for furhter action.

**Comment by ericpershey** [comment]
That seems to fix this problem.  I tested it using my provided code and using the ldap authentication module, both worked.  There might be other problems with the other i* queries that you might want to look at.

**Comment by IBMAmarPY** [comment]
The fix for other filters are also added to github.

**Comment by SabaKauser** [comment]
fixed.
