### ISSUE TITLE
Fetching BIGINT value from db2 truncates the value

### ISSUE THREAD

**Issue by lintonv** [ibmdb/python-ibmdb#222]
We have a BIGINT value that is being correctly stored in the IBM DB2 database.  But when it is retrieved, it is always truncated to the first digit.
Example:
3232235520 is correctly written to the database. We use ibm_db.execute
When we use ibm_db.result(stmt, BIGINT_COLUMN), only 3 is returned

**Comment by SabaKauser** [comment]
Thanks for reporting this issue. 
This problem is fixed in git now.

**Comment by lintonv** [comment]
@SabaKauser 
Great fix and good timing. 
Is there anyway you can generate a new python package and put it in the PYPI for 'pip install'

https://pypi.python.org/pypi/ibm_db is still reflecting an older version. Any way to update this?

--Linton

**Comment by SabaKauser** [comment]
Hello Linton,

Release to pypi is a process and there is no way to update the binaries or source code there quickly.
If you want to have the changes reflect in your env, I suggest you download the source code from github and build the source yourself:
cd to folder where you see ibm_db.c
python setup.py build
python setup.py install

Thanks!

**Comment by lintonv** [comment]
@SabaKauser - Thank you. We will do that for now.
