### ISSUE TITLE
ibm_db_django 1.0.9.2 generating invalid sql during migration

### ISSUE THREAD

**Issue by nhardman** [ibmdb/python-ibmdb#227]
My system on RHEL7 has the following installed:
IBM DB2 V10.5 fp6
Django==1.8.15
ibm-db==2.0.7
ibm-db-django==1.0.9.2

I created a django project with 1 app (grumpy) and one user defined model. For the purposes of this ticket I left the database settings to use the default sqllite database. I ran manage.py makemigrations and then manage.py migrate. The output is below:

./manage.py makemigrations
Migrations for 'grumpy':
  0001_initial.py:
    - Create model SourceEnvironment
[root@rhel7 nrh]# ./manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages
  Apply all migrations: admin, contenttypes, grumpy, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying grumpy.0001_initial... OK
  Applying sessions.0001_initial... OK

As a db2inst1 user I created my database 'NRH':
su - db2inst1
Last login: Thu Oct 20 10:32:40 BST 2016
[db2inst1@rhel7 ~]$ db2 create database NRH pagesize 8 k
DB20000I  The CREATE DATABASE command completed successfully.

I edited my setting.py file so the DB2 database is now used:
~~~~
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'ibm_db_django',
        'NAME': 'NRH',
        'USER': 'db2inst1',
        'PASSWORD': '60gcpz3o',
        'HOST': 'localhost',
        'PORT': '50000',
    }
}
~~~~
and I changed the USE_TZ flag to False as this is needed for DB/2.

I then reran the makemigrations (which has no effect as they have already been created) and then the reran migrate, and got the following error:
[root@rhel7 nrh]# ./manage.py makemigrations
No changes detected
[root@rhel7 nrh]# ./manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages
  Apply all migrations: admin, contenttypes, grumpy, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/Django-1.8.15-py2.7.egg/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/Django-1.8.15-py2.7.egg/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/Django-1.8.15-py2.7.egg/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/Django-1.8.15-py2.7.egg/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/Django-1.8.15-py2.7.egg/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/Django-1.8.15-py2.7.egg/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/Django-1.8.15-py2.7.egg/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python2.7/site-packages/Django-1.8.15-py2.7.egg/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python2.7/site-packages/Django-1.8.15-py2.7.egg/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/lib/python2.7/site-packages/ibm_db_django-1.0.9.2-py2.7.egg/ibm_db_django/schemaEditor.py", line 284, in alter_field
    'column': self.quote_name(new_field.column)
  File "/usr/lib/python2.7/site-packages/Django-1.8.15-py2.7.egg/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/Django-1.8.15-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.7/site-packages/Django-1.8.15-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/ibm_db_django-1.0.9.2-py2.7.egg/ibm_db_django/pybase.py", line 170, in execute
    six.reraise(utils.ProgrammingError, utils.ProgrammingError( *tuple( six.PY3 and e.args or ( e._message, ) ) ), sys.exc_info()[2])
  File "/usr/lib/python2.7/site-packages/ibm_db_django-1.0.9.2-py2.7.egg/ibm_db_django/pybase.py", line 160, in execute
    return super( DB2CursorWrapper, self ).execute( operation, parameters )
  File "/usr/lib64/python2.7/site-packages/ibm_db-2.0.7-py2.7-linux-x86_64.egg/ibm_db_dbi.py", line 1336, in execute
    self._execute_helper(parameters)
  File "/usr/lib64/python2.7/site-packages/ibm_db-2.0.7-py2.7-linux-x86_64.egg/ibm_db_dbi.py", line 1248, in _execute_helper
    raise self.messages[len(self.messages) - 1]
django.db.utils.ProgrammingError: Statement Execute Failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0190N  ALTER TABLE "DB2INST1.AUTH_USER" specified attributes for column "EMAIL" that are not compatible with the existing column.  SQLSTATE=42837 SQLCODE=-190

I then edited django/db/backends/utils.py line 64 to print the sql that is generated and reran the migrate. I got the following output:

[root@rhel7 nrh]# ./manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages
  Apply all migrations: admin, contenttypes, grumpy, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying auth.0003_alter_user_email_max_length...
utils[64] ALTER TABLE "AUTH_USER" ALTER COLUMN "EMAIL" DROP DEFAULT

So the ibm_db_django driver is generating a DROP DEFAULT for the Email column in the AUTH_USER table.

Then as the db2inst1 user I listed the table columns and tried the alter directly from the DB/2 shell and got the following:

[db2inst1@rhel7 ~]$ db2 describe table auth_user
~~~~
                                Data type                     Column
Column name                     schema    Data type name      Length     Scale Nulls
------------------------------- --------- ------------------- ---------- ----- ------
ID                              SYSIBM    INTEGER                      4     0 No    
PASSWORD                        SYSIBM    VARCHAR                    128     0 No    
LAST_LOGIN                      SYSIBM    TIMESTAMP                   10     6 No    
IS_SUPERUSER                    SYSIBM    SMALLINT                     2     0 No    
USERNAME                        SYSIBM    VARCHAR                     30     0 No    
FIRST_NAME                      SYSIBM    VARCHAR                     30     0 No    
LAST_NAME                       SYSIBM    VARCHAR                     30     0 No    
EMAIL                           SYSIBM    VARCHAR                     75     0 No    
IS_STAFF                        SYSIBM    SMALLINT                     2     0 No    
IS_ACTIVE                       SYSIBM    SMALLINT                     2     0 No    
DATE_JOINED                     SYSIBM    TIMESTAMP                   10     6 No    

  11 record(s) selected.
~~~~
[db2inst1@rhel7 ~]$ db2 ALTER TABLE "AUTH_USER" ALTER COLUMN "EMAIL" DROP DEFAULT
DB21034E  The command was processed as an SQL statement because it was not a 
valid Command Line Processor command.  During SQL processing it returned:
SQL0190N  ALTER TABLE "DB2INST1.AUTH_USER" specified attributes for column 
"EMAIL" that are not compatible with the existing column.  SQLSTATE=42837

So I conclude that the ibm_db_django driver is generating invalid SQL as this command does not work on the email field.

**Comment by SabaKauser** [comment]
This problem is already fixed in git. You can build the source from github repository codebase and you should be able to continue.

**Comment by nhardman** [comment]
Hi Saba, thanks for letting me know this is fixed that's great news. I'd like to know when is the next official build going to be available? Whilst I can move forward by taking the code from github, I'd really like an official drop with a version number as this needs to be incorporated into our development systems.

**Comment by SabaKauser** [comment]
Hello,
dev is working on it. I will get back to you on this. Need to get the status.

Thanks!

**Comment by nhardman** [comment]
Thanks Saba, this is important to us (and probably a lot of DB/2 / django users) who use django in production servers, because without this fix we cannot easily move to django 1.8 which as the Long Term Support version of django gets all the security updates applied to it.

**Comment by SabaKauser** [comment]
Hello Neil,
I had a check and the team is planning to have the release in 3 weeks time.

Thanks,
Saba.

**Comment by nhardman** [comment]
Brilliant, thanks
