### ISSUE TITLE
Connecting to the DB hangs

### ISSUE THREAD

**Issue by ptchankue** [ibmdb/python-ibmdb#229]
Hi guys,

I am trying to use this library to connect to a DB2 database with django. It just hangs when trying to connect. I tried the same with a jt400 library with Java, and the connection works fine (with same schema, host, port, and user).

Any idea how to fix this issue?

Regards,
Patrick

**Comment by nhardman** [comment]
Your going to need to give a lot more info than that if you're expecting anyone to help you.... How about providing the versions of django and associated components and also providing the database settings from settings.py?

Regards,
Neil

**Comment by ptchankue** [comment]
@nhardman Thank you for replying. I am using Django version 1.10 with Python 2.7
```
'default': {
        'ENGINE'    : 'ibm_db_django',
        'NAME'      : 'MyMD',
        'USER'      : 'mysuer',
        'PASSWORD'  : 'mypasspwrd',
        'HOST'      : 'host.domain.com',
        'PORT'      : '8471',
        'AUTHENTICATION' : 'SERVER',
        'PCONNECT'  : True,
    }
```

I suspect that the DB was set to restrict some connections because the same issue occurs with ibm_db for nodeJS. I am investigating that.

Best regards,
Patrick
