### ISSUE TITLE
django loaddata is too slow

### ISSUE THREAD

**Issue by milind7705** [ibmdb/python-ibmdb#235]
Hello,
I am trying to migrate the data from sqllite to db2. I have used the dumpdata to take the backup from sqlite and using loadata to populate existing db2.
The commands i habe been following are:
manage.py dumpdata --exclude auth.permission --exclude contenttypes --exclude sessions --output db.json

For loading to existing db2:
manage.py loaddata db.json

The data we've to migrate is pretty big, and the parsing utility of loaddata is taking time to formulate the sql statements against the db2. Can you check if the timing can be improved?

Regards,
Milind

**Comment by milind7705** [comment]
Closing without providing any solution.. way to go :100:

**Comment by SabaKauser** [comment]
if you see the problem with latest ibm_db_django, kindly reopen the issue. And if you can provide details on the workload that you have from sqllite and possibly the db.json(if everything permits) for us to reproduce, that would be good.

**Comment by SabaKauser** [comment]
ibm_db_django is moved to separate repository. 
https://github.com/ibmdb/python-ibmdb-django/issues/17 -> track it here
