### ISSUE TITLE
How to call the  get_dbsize_info stored procedure in python?

### ISSUE THREAD

**Issue by bg1szd** [ibmdb/python-ibmdb#236]
Yhe DB2 version is 10.5 and python version is 2.6.6.
The code is as below. It will be used to connect to a DB2 db and get the database size.
It will call the stored procedure of CALL get_dbsize_info(?,?,?,-1) to get the value.
However, how to bind the parameter here? Param_1, Param_2 and Param_3, how to set these value?
Because CALL get_dbsize_info('?','?','?',-1) is invalid here. The question mark could not be in quotation marks.

Import os
import ibm_db
import datetime,time

def get_db_size(db_name):
        db_size = []
        conn = ibm_db.connect(" db2 connection info", "", "")
        if conn:
                 sql = 'CALL get_dbsize_info(?,?,?,?)'
                 stmt = ibm_db.prepare(conn, sql)
                 Param_1 =  //
                 Param_2 =  //
                 Param_3 =  //
                 Param_4 = 0
                 ibm_db.bind_param(stmt, 1, Param_1, ibm_db.SQL_PARAM_OUTPUT)
                 ibm_db.bind_param(stmt, 2, Param_2, ibm_db.SQL_PARAM_OUTPUT)
                 ibm_db.bind_param(stmt, 3, Param_3, ibm_db.SQL_PARAM_OUTPUT)
                 ibm_db.bind_param(stmt, 4, Param_4, ibm_db.SQL_PARAM_INPUT)
                 if ibm_db.execute(stmt):
                        while db_size != False:
                                print db_size
                                #print "Name :", db_size[0]
                                #print "Value :", db_size[1]
                                db_size=ibm_db.fetch_both(stmt)

get_db_size('datebase')

**Comment by kadler** [comment]
If you're calling a procedure, use [ibm_db.callproc](https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbcallproc) or [ibm_db_dbi.callproc](https://www.python.org/dev/peps/pep-0249/#cursor-methods).

Also, for questions about usage and not actual bugs, please direct questions to the Google group: https://groups.google.com/forum/#!forum/ibm_db
