### ISSUE TITLE
BooleanField always returns True for both value 1 and value 0

### ISSUE THREAD

**Issue by fmeoli** [ibmdb/python-ibmdb#249]
The models.NullBooleanField () or models.BooleanField () does not translate correctly the values 0/1 False / True from version 1.8 of Django.
For example, users are shown all as superuser and staff (as if the database were setup to 1 - True) even if the corresponding values in the database are 0 (False).
To solve the problem I had to change the function of get_db_converters in operations.py module of ibm_db_django as follows:
```

    def get_db_converters(self, expression):
        converters =super(DatabaseOperations, self).get_db_converters(expression)
        
        field_type = expression.output_field.get_internal_type()
        if field_type in ( 'BinaryField',  ):
            converters.append(self.convert_binaryfield_value)   
        elif field_type in ['BooleanField', 'NullBooleanField']:
            converters.append(self.convert_booleanfield_value)
        #  else:
        #   converters.append(self.convert_empty_values)
        """Get a list of functions needed to convert field data.

        Some field types on some backends do not provide data in the correct
        format, this is the hook for coverter functions.
        """
        return converters
```
and add convert_booleanfield_value function as follows:

```
    if( djangoVersion[0:2] >= ( 1, 8 ) ):
        def convert_booleanfield_value(self, value, expression, connection, context):
            field = expression.output_field
            field_type = field.get_internal_type()
            if field_type in ( 'BooleanField', 'NullBooleanField' ):
               if value in ( 0, 1 ):
                  return bool( value )
            else:
                return value

```
My enviroments is:
Django==1.8.16
ibm-db==2.0.7
ibm-db-django===1.0.9.2

I'm sorry for my english
Fabio

**Comment by hemlatabhatt** [comment]
Hi Fabio,

i checked the same with a sample test case as : 
class test(models.Model):
    isboo = models.BooleanField(default=0)
    noboo = models.BooleanField(default=1)

    def convert_boolean_value(self,value):
        if value in ( 0, 1 ):
            print("Print the value :",bool(value),value)
            return value 
        else:
            return value
        
    def test(self): 
        a= test()
        output1= self.convert_boolean_value(a.isboo)
        output2= self.convert_boolean_value(a.noboo)

I am not able to re-produce the issue .Can you please share where you are facing the issue by some sample model .

Thanks
Hemlata

**Comment by fmeoli** [comment]
Hi Hemlata,

sorry I did not say the most important thing maybe. The mistake I reported only occurs in the form. You can check it with the Admin site on model "Auth" controlling "is_staff" privilege users:
The list are properly displayed (as in your test) but if you enter details on a "no staff member" the next screen displays the user such as "is staff."

I hope I was clear enough

**Comment by mjlawrence83** [comment]
Hi,

I'm also experiencing this same issue after trying to upgrade to 1.8.17 from 1.7.11. For each django version I'm using the same ibm-db-django version 1.1.0.2.

Any model instance which is supposed to be a booleanField is actually of type Integer

**Comment by SabaKauser** [comment]
this is moved to ibm_db_django

**Comment by hemlatabhatt** [comment]
This issue was moved to ibmdb/python-ibmdb-django#25

**Comment by hemlatabhatt** [comment]
This issue was moved to ibmdb/python-ibmdb-django#26
