### ISSUE TITLE
SQL0668N  Operation not allowed for reason code "7" on migrate

### ISSUE THREAD

**Issue by mjlawrence83** [ibmdb/python-ibmdb#254]
Hi,

I recently dropped a few fields in a model, and created a migration file. This does an ALTER TABLE and DROPs columns etc.

When running migrate, it fails with: SQL0668N  Operation not allowed for reason code "7". According to the following URL, it looks like the table isn't REORGed after the alter: http://www-01.ibm.com/support/docview.wss?uid=swg21674146

Can this fixed?

(using Django v1.7.11, ibm-db 2.0.6, ibm-db-django 1.0.7 - Maybe fixed in a newer version, but I'm still waiting for the next release after 1.1.0.0 in PyPi as #244 stops me from using it - when will this be released?)

**Comment by SabaKauser** [comment]
This issue is already fixed and is available in pypi.
For #244, Let me see if we can have another release any time sooner.

**Comment by mjlawrence83** [comment]
Please do try to get a new release into PyPi, like I said, we cannot use any of your later versions in PyPi as they all have the #244 bug

**Comment by SabaKauser** [comment]
New release is available in pypi. You may use and validate your application/s.
