### ISSUE TITLE
SQLCODE=-1042

### ISSUE THREAD

**Issue by genomics-geek** [ibmdb/python-ibmdb#256]
I ran into this issue and was able to address it when using `ibm_db.connect` directly. 

My connection command is:
```python
ibm_db.connect("DATABASE=BIGSQL;HOSTNAME=mn0204.chop.edu;PORT=32051;PROTOCOL=TCPIP;UID=gonzalezma;PWD=mypasswordhere;AUTHENTICATION=SERVER", "", "")

# <ibm_db.IBM_DBConnection object at 0x10508dd68>
```

However, it requires that I use `AUTHENTICATION=SERVER`. How can I pass this to ibm_db_django?? 

I have tried two ways below (neither seem to work):

```python
DATABASES = {
    'default': {
        'ENGINE': 'ibm_db_django',
        'NAME': 'BIGSQL',
        'USER': 'user',
        'PASSWORD': 'passwordgoeshere',
        'HOST': 'mn0204.chop.edu',
        'PORT': '32051',
        'AUTHENTICATION' : 'SERVER',
    }
}
```

```python
DATABASES = {
    'default': {
        'ENGINE': 'ibm_db_django',
        'NAME': 'BIGSQL',
        'USER': 'user',
        'PASSWORD': 'passwordgoeshere',
        'HOST': 'mn0204.chop.edu',
        'PORT': '32051',
        'OPTIONS': {
                'AUTHENTICATION' : 'SERVER',
        }
    }
}
```

**Comment by Vyshakh18** [comment]
Hi,
Could you try using db2dsdriver.cfg file and mention AUTHENTICATION as SERVER for the database which you are trying to connect?
An entry in db2dsdriver.cfg file for a DB called "sample1" could look like this:

<configuration>
	<dsncollection>
		<dsn alias="sample1" name="sample1" host="100.100.100.100" port="50000"/>
	</dsncollection>
	<databases>
		<database name="sample1" host="100.100.100.100" port="50000">
			<parameter name="USERID" value="user1"/>
			<parameter name="Password" value="pwd1"/>
			<parameter name="AUTHENTICATION" value="SERVER"/>
		</database>
	</databases>
</configuration>

More info on db2dsdriver.cfg can be found here:
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/c0054555.html

For info regarding the location of db2dsdriver.cfg, please follow the below link:
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/r0061058.html

**Comment by Vyshakh18** [comment]
Hi,
Could you try using db2dsdriver.cfg file and mention the value of AUTHENTICATION parameter as SERVER for the DB which you are using?
A screenshot of a sample db2dsdriver.cfg file is attached here:
![capture](https://cloud.githubusercontent.com/assets/20924484/23509414/b3bbc404-ff7b-11e6-8b1e-f1c5cc816080.JPG)
 
For more info regarding db2dsdriver.cfg, please refer to:
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/c0054555.html

For info regarding the location of db2dsdriver.cfg, please follow the below link:
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/r0061058.html
