### ISSUE TITLE
Adding timeout to ibm_db.connect()

### ISSUE THREAD

**Issue by Ron4326** [ibmdb/python-ibmdb#260]
Hi,

I'm connecting to a remote DB2 database and when the server is down, the control never comes out of 
`ibm_db.connect(<remote db connection>)`

I checked for a way to add timeout to this connect method and strangely I couldn't find anything, except 
[this thread](https://groups.google.com/forum/#!topic/ibm_db/x2IO45NN1Js)

But I can't edit the ini files as I'm connecting to a remote server. Also, I can't execute DB queries on those servers, so the above solution doesn't work for me.

All I want is to add a timeout like we do for socket connections
`socket.settimeout(10)`

Thanks,
Ron

**Comment by SabaKauser** [comment]
can you try connecttimeout in db2cli.ini or db2dsdriver.cfg file.
You could also add it in connection string.

https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0021533.html
