### ISSUE TITLE
Data Type "long" Is Not Supported at ibm_db.fetch_row Function

### ISSUE THREAD

**Issue by claudefalbriard** [ibmdb/python-ibmdb#261]
The following sample was executed under Linux RedHat with Python 2.6

**Test 1** 
using ibm_db.fetch_both(stmt) - see value 12103L in column TPS_LOG_ID

`{0: 12103L, 1: datetime.datetime(2017, 3, 24, 10, 31, 49, 167000), 2: u'xyz...xyz', 3: u'permit', 'EVIDENCE': u'xyz...xyz', 'LOG_DATETIME': datetime.datetime(2017, 3, 24, 10, 31, 49, 167000), 'TPS_LOG_ID': 12103L}`

**Test 2**
using fetch_row(stmt) - see value 1 in column TPS_LOG_ID (value in error) 
```
Dic: TPS_LOG_ID = 1
Dic: LOG_DATETIME = 2017-03-24 10:31:49.167000
Dic: EVIDENCE  = xyz...xyz
```

**Comment by SabaKauser** [comment]
Is this still open? Can you please confirm that issue is fixed now.
