### ISSUE TITLE
Separate ibm_db_django in to its own project

### ISSUE THREAD

**Issue by kadler** [ibmdb/python-ibmdb#264]
There are 4 main python projects:

ibm_db
ibm_db_django
ibm_db_sa
ibm_db_alembic

While ibm_db_sa and ibm_db_alembic are in their own repositories, for some reason ibm_db_django is in this repository. I think it would be a good idea to split these projects in to separate repositories.

**Comment by kadler** [comment]
FYI, there's a doc on how to do this while keeping the history: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by SabaKauser** [comment]
Hello Kevin,
This is already there is the backlog. However, we are currently working on new support and hence would be able to take this up sometime later. Although I cannot commit on exact timeline, but this would be looked into as soon as we have some bandwidth.

Thanks!
Saba.

**Comment by hemlatabhatt** [comment]
This issue was moved to ibmdb/python-ibmdb-django#1

**Comment by hemlatabhatt** [comment]
This issue was moved to ibmdb/python-ibmdb-django#2
