### ISSUE TITLE
Exception: [IBM][CLI Driver] SQL30081N  A communication error has been detected. 

### ISSUE THREAD

**Issue by Adam-Dodson** [ibmdb/python-ibmdb#265]
I'm trying to connect to a IBM i5. I try to connect directly with this connection string (sanitized string): 

con = ibm_db.connect("DRIVER={IBM DB2 ODBC DRIVER};DATABASE=SRVRIBM.PRODQA;System=100.100.100.100;PORT=657;PROTOCOL=TCPIP;UID=Login;PWD=Password;", '', '')

I then get this error: 

Exception: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "127.0.0.1".  Communication function detecting the error: "connect".  Protocol specific error code(s): "10061", "*", "*".  SQLSTATE=08001
 SQLCODE=-30081

If I use a "IBM i Access ODBC Driver" that I had setup with the ibm_db library with the following connection string:

con = ibm_db.connect("DRIVER={IBM i Access ODBC Driver};DATABASE=SRVRIBM.PRODQA;System=100.100.100.100;PORT=657;PROTOCOL=TCPIP;UID=User;PWD=Password;", '', '')

I get the following error:

File "<interactive input>", line 1, in <module>
Exception: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968
 SQLCODE=-1598

Further the above connection string where I use the 'IBM i Access ODBC Driver'  with pyodbc, the connection works just fine.

The db2diag.log file produces this in the body:

FUNCTION: DB2 UDB, RAS/PD component, pdLogInternal, probe:120
START   : New Diagnostic Log file
DATA #1 : Build Level, 208 bytes
Instance "" uses "32" bits and DB2 code release "SQL10055"
with level identifier "0606010E".
Informational tokens are "DB2 v10.5.500.107", "s141128", "IP23627", Fix Pack "5".

and 

FUNCTION: DB2 UDB, Connection Manager, sqleuPerformServerActivationCheck, probe:110
MESSAGE : ADM12008C  The product "IBM Data Server Driver For ODBC and CLI" does 
          not have a valid license key installed and the evaluation period has 
          expired. Functions specific to this product are not enabled. If you 
          have licensed this product, ensure the license key is properly 
          installed. You can install the license using the db2licm command. The 
          license file can be obtained from your licensed product CD.

Any suggestions on how to proceed?

All the tutorials I've read about setting up this library have pretty much been a install via "easy-install.py  ibm_db-2.0.7.tar.gz" load the library, put in a connection string & everything is working.

edit: Using Python 3.4

**Comment by kadler** [comment]
Where did you get port 657 from? The default DRDA port on IBM i is 446/448: https://www.ibm.com/support/knowledgecenter/ssw_i5_54/ddm/rbae5ports.htm

FYI, ibm_db does not support connecting through the IBM i Access ODBC driver.

**Comment by Adam-Dodson** [comment]
I got that port via 'netstat' on the i5 & looking at the port information, but, I think I originally just got it from an nmap scan.  I also could connect on the DRDA ports.

I was only giving the pyodbc library using the  IBM i Access ODBC driver as what I did for a sanity check to illustrate that the connection string didn't appear to be at fault.  


I only tried the i Access ODBC  driver because the db2 express-c driver wasn't working after doing the easy-install & to see if that would be an easy way to use the ibm_db library, which, didn't work.

What confused me the most is the output to the db2log, the line with the information:
""DB2 v10.5.500.107", "s141128", "IP23627", Fix Pack "5"."  I was under the assumption that fix pack's didn't apply to the express-c drivers & was kinda wondering if that's the normal reported version.  Is that the version everyone uses with this library out of the box?


I've tried uninstalling i Access for Windows, removed all references to IBM DB2 in the registry & ProgramFiles. unintalled & reintalled the ibm_db library with & without i Access for Windows installed on the machine. All of which has had the same error.

**Comment by kadler** [comment]
The connection string you were using with pyODBC goes through the ODBC driver manager, which looks up the driver to use and forwards requests to it. ibm_db bypasses the driver manager (as a [CLI](https://en.wikipedia.org/wiki/Call_Level_Interface) application)and binds directly to the DB2 Connect driver, so you cannot use any other driver with it.

Regarding the fixpack comment, I'm not a DB2 Express developer, so I can't say for sure, but from what I understand DB2 Express-C does not support applying fixpacks, but instead the installs are periodically updated with the latest fixpack code. So to update Express-C you must uninstall the current version and install the latest instead of just applying a fixpack on top.

**Comment by Adam-Dodson** [comment]
I was under the impression that when I issue the easy_install.py ibm_db2...bz the easy_install script installs the Express-C driver for me, and requires no further setup if you're using a connection string. Currently, when I use the following connection string I'm still receiving the same error.

conn = ibm_db.connect('DRIVER={IBM DB2 ODBC DRIVER};DATABASE=SRVRIBM.PRODQA;System=100.100.100.100;PORT=657;PROTOCOL=TCPIP;UID=user;PWD=password;', "", "") 

Nor does:

conn = ibm_db.connect('DRIVER={IBM DB2 ODBC DRIVER};DATABASE="SRVRIBM.PRODQA";System=100.100.100.100;PORT=657;PROTOCOL=TCPIP;UID=user;PWD=password;', "", "") where the difference is the double quotes around the "SRVRIBM.PRODQA" for the database parameter.

**Comment by kadler** [comment]
Sorry, I missed this message the first time:

> FUNCTION: DB2 UDB, Connection Manager, sqleuPerformServerActivationCheck, probe:110
> MESSAGE : ADM12008C The product "IBM Data Server Driver For ODBC and CLI" does
> not have a valid license key installed and the evaluation period has
> expired. Functions specific to this product are not enabled. If you
> have licensed this product, ensure the license key is properly
> installed. You can install the license using the db2licm command. The
> license file can be obtained from your licensed product CD.

You must purchase a license of DB2 Connect in order to connect to an IBM i system (or a z/OS system). This is not required to connect to Linux, Unix, or Windows DB2 servers.

**Comment by Adam-Dodson** [comment]
The following error was only returned when I was attempting to use the IBM i Access ODBC driver with the ibm_db library.

>FUNCTION: DB2 UDB, Connection Manager, sqleuPerformServerActivationCheck, probe:110
MESSAGE : ADM12008C The product "IBM Data Server Driver For ODBC and CLI" does
not have a valid license key installed and the evaluation period has
expired. Functions specific to this product are not enabled. If you
have licensed this product, ensure the license key is properly
installed. You can install the license using the db2licm command. The
license file can be obtained from your licensed product CD.




Otherwise, when I attempt to use 'IBM DB2 ODBC driver' I simply am given:

[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "127.0.0.1".  Communication function detecting the error: "connect".  Protocol specific error code(s): "10061", "*", "*".  SQLSTATE=08001
 SQLCODE=-30081


As the error code.

We've already established that the IBM i Access driver is not supported by the ibm_db library.

**Comment by kadler** [comment]
Well, I think we're back to using the wrong port. As I said before, 446/448 are the standard ports for DDM/DRDA. Of course, once you connect you'll probably hit the same licensing error above unless you have a DB2 Connect license installed.

**Comment by Adam-Dodson** [comment]
It never much mattered what port I was connecting, it always resulted in the same error. 446 DRDA, ddm, ddm-ssl port.  


[IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "127.0.0.1".  Communication function detecting the error: "connect".  Protocol specific error code(s): "10061", "*", "*".  SQLSTATE=08001
 SQLCODE=-30081

**Comment by kadler** [comment]
Ah. Well, I think we've reached the limits of my DB2 Connect knowledge. Perhaps @SabaKauser knows more.

**Comment by Adam-Dodson** [comment]
Thanks for trying.

**Comment by IBMAmarPY** [comment]
Thanks Kevin.
Adam, your connection from LUW driver (odbc and cli driver) seems to establish connection through loopback. Loopback is for local IP connections. You can see -30081 is reporting IP 127.0.0.1 in error and not 100.100.100.100.

Kindly provide traces to assist more.

you can collect db2 traces as follows:

cd <clidriver install location>/adm
./db2trc on -f trc.dmp
<try your repro>
./db2trc off
./db2trc flw trc.dmp trc.flw
./db2trc fmt trc.dmp trc.fmt
./db2trc fmt -c trc.dmp trc.fmtc
./db2trc fmt -cli trc.dmp trc.cli and provide us all the files except trc.dmp.

**Comment by IBMAmarPY** [comment]
cd /adm ==> cd <CLI driver install location/adm>

**Comment by Adam-Dodson** [comment]
@IBMAmarPY That part confuses me too, I don't have a local install of DB2.  I only have installed as far as DB2 is concerned is what the ibm_db package provides.  I have that binary in clidriver in the bin directory("C:\Python\Lib\site-package\clidriver\bin").  I suppose I should mention I'm developing this on a Windows box, not Linux (if that makes an impact).  At any rate I was able to perform the trace as requested; I've attached the files in a zip.  







[trace_files.zip](https://github.com/ibmdb/python-ibmdb/files/1022238/trace_files.zip)

**Comment by Adam-Dodson** [comment]
Would a trace with an actual connection attempt provide better information for you?

I did one & I can actually see that it contacts our IBM i5,

**Comment by Adam-Dodson** [comment]
Would you like a trace where I actually make an attempt to connect to the server & schema?

**Comment by IBMAmarPY** [comment]
Hi Adam,

The traces does not seem to capture the application flow. Only db2trc processing is captured. Nothing either is captured in cli traces.
Could you please capture traces for the connection and share the same.

-Amar.

**Comment by SabaKauser** [comment]
closing. Please re-open if required.
