### ISSUE TITLE
Django AS/400 Connection Issues

### ISSUE THREAD

**Issue by cchadwick75** [ibmdb/python-ibmdb#266]
I have 2 issues when using the ibm_db_django DATABASES engine settings in my django project.  Here is what my settings looks like.  

DATABASE_ENGINE = 'ibm_db_django'
DATABASES = {
       'default': {
       'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'mydatabase',
     },
     'db2': {
     'ENGINE': 'ibm_db_django',
     'NAME':'****',    
     'USER':'****',
     'PASSWORD': '****',
     'HOST': '****',
     'PORT' : '8471',
     'PCONNECT' : True,
     'OPTIONS':{ 

     },
    }
}

When run the manage.py test on my linux server the program asks if I want to create a test database.  I type no.  Then it asks if I want to use ****(name) as a test db, when I type yes and enter it hangs.  

So if I change the port to 446, i get an error saying I dont have a license for the program.  When I use port 9471 I get this message.  Any help at all would be awesome.

django.db.utils.OperationalError: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "10.1.0.4".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001 SQLCODE=-30081

**Comment by norwinu** [comment]
What version of Django are you using? I don't think DATABASE_ENGINE is relevant anymore. Do you have a DB2 Connect license? I believe one is required in order to connect remotely to DB2.

**Comment by cchadwick75** [comment]
I am using 1.11.1 in Django, I am trying to use it without the DB2 Connect license.  I was trying to connect hopefully using something like pyodbc so we wouldn't have to look deeper into the license.  Thanks very much for responding.

**Comment by norwinu** [comment]
Read the previous issue (#265). kadler from IBM addresses this. Seems like it won't be possible to connect to DB2 for i without a Connect license.

**Comment by cchadwick75** [comment]
Thank you very much for responding, I was looking at this and wasnt sure if it was related.  So you cant access db2 for i using a seperate linux box with an ODBC driver, or IBM_Db unless you have db2 connect.  If thats the case thank you very much and I appreciate the help and i will close this once I get final confirmation.
