### ISSUE TITLE
iSeries ibm_db_django

### ISSUE THREAD

**Issue by cchadwick75** [ibmdb/python-ibmdb#268]
Hello everyone, 

Has anyone else had success connecting to the iSeries using ibm_db_django?  There doesnt appear to be a whole lot of documentation about it.  I am using a django framework and I want to use the ibm_db_django.  Is this even possible?  I once read on a post from 2015 that the iSeries isnt supported by django?  Should I be using a different framework, or a different way to connect to the iSeries. My version of the Django is 1.11.  I have tried changing ports, I know I can connect successfully using an ODBC driver.  Here is what the settings.py looks like for the DATABASES.  Any help would be amazing.  

DATABASES = {
     'default': {
     'ENGINE': 'ibm_db_django',
     'NAME':'NAME',    
     'USER':'myuser',
     'PASSWORD': 'pass',
     'HOST': '0.0.0.0',
     'PORT' : '448',
     'PCONNECT' : True,
     'OPTIONS':{ 
 },
    }
 }

**Comment by SabaKauser** [comment]
Copying Kevin's response from  -> https://groups.google.com/forum/#!topic/ibm_db/G-U6AJuvq1Y


  There is IBM i support within ibm_db and ibm_db_django for IBM i when using DB2 Connect already, I believe. While there appears to be some IBM i-related code in ibm_db_sa, I don't think it is currently functional.

If you want to run your code on IBM i, then we do ship a version of ibm_db and ibm_db_django as part of 5733-OPS. This works on 7.1 and up. We do not ship ibm_db_sa for the above-mentioned reasons. These versions are based on the 2.0.5 release, so they're a little out of date. I do have a goal of merging the two code streams (the IBM i related code is in the "ibmi" branch on GitHub), but they've diverged quite a bit in the interim.

On Wednesday, November 22, 2017 at 9:21:41 PM UTC-6, Nahum Castro wrote:

    There will be support to db2 7.3 on as400 i series  on django, ibm_db and ibm_db_sa?

**Comment by kadler** [comment]
In addition to that, the current ibm_db_django code does not currently support Django 1.11 and the ibm_db_django version provided for IBM i is still only up to Django 1.8 support. If you are not running on IBM i and using the DB2 Connect driver, it may work just fine. It looks like you're running on IBM i though (using host 0.0.0.0, which isn't actually valid for a client). Try this:

```
DATABASES = {
    'default': {
        'ENGINE': 'ibm_db_django',
        'NAME': '*LOCAL',
        'USER': 'user',
        'PASSWORD': 'password',
    }
}
```
