### ISSUE TITLE
opendev email is dead

### ISSUE THREAD

**Issue by pdbossman** [ibmdb/python-ibmdb#269]
Hello,
I attempted to send a note to opendev@us.ibm.com and it got kicked back as not found.

I was looking to ask when support for using this with python in z in USS?

Thank you,
Patrick Bossman

**Comment by SabaKauser** [comment]
Hello Patrick,
You can start a thread here for the problem you are facing.

Can you elaborate more what exactly you are looking for.

**Comment by pdbossman** [comment]
I installed python on UNIX system services on z/OS.  I want to connect
python and db2 z.

It appears to not be a supported installation.

Regards,
Pat

**Comment by SabaKauser** [comment]
python ibm_db driver is supported for installation only on LUW.

**Comment by RockBomber** [comment]
python ibm_db driver works with db2 on z/os in my case.
I had an issue with ibm_db_sa, but I solved it through ugly hack in `ibm_db_sa/ibm_db.py` line 140 in method get_isolation_level `return None` 
Will be official support for z/os in future?

**Comment by SabaKauser** [comment]
remote connectivity is supported. What I meant is installing the driver on z/OS machine.

**Comment by pdbossman** [comment]
Right, I'm saying there is demand for support for install on system z
itself.

**Comment by SabaKauser** [comment]
Hello Patrick,

Could you please share following details:
Customer name
Do you have db2 Connect license?

We use db2 LUW ODBC and CLI Driver internally and this driver is currently not  supported for installation on z/OS. However, Z has their own C driver and I think you could use that installation and try installing IBM Python ibm_db driver.
Please note that we have never supported or ever tested our driver with the installation that I have proposed above and the z ODBC driver development is not owned by us.
