### ISSUE TITLE
callproc input xml Segmentation fault

### ISSUE THREAD

**Issue by cmbc-hongye** [ibmdb/python-ibmdb#277]
major_version = 1
        minor_version = 0
        requested_locale = "en_US"
        xml_input = """<?xml version =\"1.0\" encoding=\"UTF-8\"?>
                <plist version =\"1.0\"><dict><key>MAJOR_VERSION</key><integer>1</integer><key>MINOR_VERSION</key>
                <integer>0</integer><key>REQUESTED_LOCALE</key><string>en_US</string><key>CMD_OPTIONS</key>
                <string>-w \"{0}\" -t 5</string></dict></plist>""".format(explain_time).encode('hex')
        xml_filter = ''
        xml_output = ''
        xml_message = ''

        #adviseProc,major_version,minor_version,xml_output.xml_message = ibm_db.callproc(self.conn, 'SYSPROC.DESIGN_ADVISOR', (1, 0, 'en_US', procPara, 'NULL', '', ''))

return 
bash: line 1: 29024 Segmentation fault      env "PYCHARM_HOSTED"="1" "PYTHONUNBUFFERED"="1" "PYTHONIOENCODING"="UTF-8" "PYTHONPATH"="/root/root/remote-server/check_scripts" "JETBRAINS_REMOTE_RUN"="1" /usr/local/bin/python -u /root/root/remote-server/check_scripts/check_scripts/sqlplan.py -d sample -U db2inst1 -P db2inst1 -I weihoo-bj-2 -p 50000 -v 2017-11-03-10.37.27.291620

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by SabaKauser** [comment]
do you need any assistance with this?
