### ISSUE TITLE
Add support for 2 phase commit transactions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ibmdb/python-ibmdb#28]
```
I would like to have ability to do 2PC commits between two DB2 9LUW using
DB2 as transaction manager.
```

Original issue reported on code.google.com by `kolar.radim` on 25 Jun 2009 at 4:30

**Comment by SabaKauser** [comment]
re-open as needed.

**Comment by christoffkok** [comment]
We'd definitely love and use this feature! Has there be any progress or ideas on this issue? Something we could perhaps look at if to get a solution for 2 phase commits working for us?
