### ISSUE TITLE
When I try to use SQLAlchemy version 1.1.9 or 1.1.15 , Error Can't load plugin: sqlalchemy.dialects:ibm_db_sa hit

### ISSUE THREAD

**Issue by yrayanki** [ibmdb/python-ibmdb#280]
If the SQLAlchemy version is 1.1.9 or greater , I see access to db2 connector fails with Can't load plugin: sqlalchemy.dialects:ibm_db_sa error.

Is their any limitation of ibm_db_sa or ibm_db with higher version of SQLAlchemy > 1.1.9 ?

With SQLAlchemy version <= 1.0.19 , access to db2 works fine without any error.

!pip show SQLAlchemy
Name: SQLAlchemy
Version: 1.1.9
Summary: Database Abstraction Library
Home-page: http://www.sqlalchemy.org
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT License
Location: /gpfs/global_fs01/cluster/ys1-wmlspark-dal09-env4-0001.bluemix.net/user/s2a9-28bca0d06ade56-05b1d10fb12b/.local/lib/python2.7/site-packages
Requires:

!pip show ibm_db_sa
Name: ibm-db-sa
Version: 0.3.3
Summary: SQLAlchemy support for IBM Data Servers
Home-page: http://pypi.python.org/pypi/ibm_db_sa/
Author: IBM Application Development Team
Author-email: opendev@us.ibm.com
License: Apache License 2.0
Location: /gpfs/global_fs01/cluster/ys1-wmlspark-dal09-env4-0001.bluemix.net/user/s2a9-28bca0d06ade56-05b1d10fb12b/.local/lib/python2.7/site-packages
Requires: sqlalchemy

!pip show ibm_db
Name: ibm-db
Version: 2.0.7
Summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS
Home-page: http://pypi.python.org/pypi/ibm_db/
Author: IBM Application Development Team
Author-email: opendev@us.ibm.com
License: Apache License 2.0
Location: /gpfs/global_fs01/cluster/ys1-wmlspark-dal09-env4-0001.bluemix.net/user/s2a9-28bca0d06ade56-05b1d10fb12b/.local/lib/python2.7/site-packages
Requires:

dashdb_input_map= {
'type':'dashdb',
'host':'awh-yp-small03.services.dal.bluemix.net',
'port':'50000',
'username': 'dash105036',
'password': '*****',
'database':'BLUDB',
'tablename': 'TRANSACTIONS_ML'
}
pandasdf4=PandasConnector.load(dashdb_input_map)
print(pandasdf4)

/gpfs/fs01/user/s2a9-28bca0d06ade56-05b1d10fb12b/.local/lib/python2.7/site-packages/sqlalchemy/engine/init.pyc in create_engine(*args, **kwargs)
389
390 def engine_from_config(configuration, prefix='sqlalchemy.', **kwargs):
--> 391 """Create a new Engine instance using a configuration dictionary.
392
393 The dictionary is typically produced from a config file.

/gpfs/fs01/user/s2a9-28bca0d06ade56-05b1d10fb12b/.local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.pyc in create(self, name_or_url, **kwargs)
54 u.query.pop('plugin', None)
55
---> 56 entrypoint = u._get_entrypoint()
57 dialect_cls = entrypoint.get_dialect_cls(u)
58

/gpfs/fs01/user/s2a9-28bca0d06ade56-05b1d10fb12b/.local/lib/python2.7/site-packages/sqlalchemy/engine/url.pyc in _get_entrypoint(self)
137 else:
138 name = self.drivername.replace('+', '.')
--> 139 cls = registry.load(name)
140 # check for legacy dialects that
141 # would return a module with 'dialect' as the

/gpfs/fs01/user/s2a9-28bca0d06ade56-05b1d10fb12b/.local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.pyc in load(self, name)
219
220 def register(self, name, modulepath, objname):
--> 221 def load():
222 mod = compat.import_(modulepath)
223 for token in modulepath.split(".")[1:]:

NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:ibm_db_sa

**Comment by rolweber** [comment]
The entrypoints for the plugin are defined [here in `setup.py`](https://github.com/ibmdb/python-ibmdbsa/blob/master/ibm_db_sa/setup.py#L35). I wonder if this could be an installation problem. Have you tried with Python 3 as well, for comparison?

**Comment by rolweber** [comment]
The paths in the issue description indicate that this is about using SQLAlchemy and ibm_db_sa in Jupyter notebooks on [Data Science Experience](https://datascience.ibm.com/) with an Apache Spark service.

Minimal code for loading the driver:
```python
from sqlalchemy import create_engine
engine = create_engine('ibm_db_sa://', echo=True)
```

**Comment by yrayanki** [comment]
closing the issue as I see with SQLAlchemy version  1.1.9 or greater it is working fine. 
Not very sure what was the root cause earlier.
