### ISSUE TITLE
psycopg2.fetchall() version in ibm_db

### ISSUE THREAD

**Issue by brityboy** [ibmdb/python-ibmdb#282]
Is there a method to execute fetchall() on an ibm_db connection?
Similar to this from psycopg2 http://initd.org/psycopg/docs/cursor.html

Currently, this is what I am using

```
    def query_db(self, query):
        """
        Args:
            query (str): this is the SQL query statement which is being used
            to get data from the database
        Returns:
            results (list): this is the list of result rows where
            each result row is a dictionary that has the keys as the columns
            of the response, and the values as the value of that item
            in the database
        """
        results = []
        stmt = ibm_db.exec_immediate(self.conn, query)
        row_dict = ibm_db.fetch_assoc(stmt)
        results.append(row_dict)
        while row_dict is not False:
            row_dict = ibm_db.fetch_assoc(stmt)
            if row_dict is not False:
                results.append(row_dict)
        return results
```

Which, to me, doesn't look like the most efficient way of doing things, but what I saw from this set of docs
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_9.5.0/com.ibm.db2.luw.apdv.python.doc/doc/t0054388.html

**Comment by SabaKauser** [comment]
Currently, there is no API no fetch all the result set at once. its iterator wise until last record is fetched.

**Comment by brityboy** [comment]
Hi @SabaKauser , thanks for responding. Is this something in the development pipeline?

**Comment by SabaKauser** [comment]
Hello Brian,

Right now, this isn't in the plan.
