### ISSUE TITLE
Data Stored as Numbers Returned as String

### ISSUE THREAD

**Issue by brityboy** [ibmdb/python-ibmdb#283]
This is my dashdb schema. See how the fields are numbers?
![screen shot 2017-12-08 at 11 22 16 am](https://user-images.githubusercontent.com/18532719/33781646-4e4ab17c-dc0a-11e7-89fb-27b38cd38b0a.png)

This is my query result using python ibm_db
![screen shot 2017-12-08 at 11 22 26 am](https://user-images.githubusercontent.com/18532719/33781645-4e2a1d86-dc0a-11e7-8c37-e72507463aeb.png)

See how it gets returned as strings? How is this supposed to be addressed via ibm_db?

**Comment by SabaKauser** [comment]
I tried this:
import ibm_db
import decimal
dsn="database=dbname;hostname=bluemixmachine.bluemix.net;port=portno;uid=uname;pwd=pwd;protocol=tcpip;"
conn=ibm_db.connect(dsn,'','')

if conn:
  try:
    delete = "drop table stockprice"
    result = ibm_db.exec_immediate(conn, delete)
  except:
    pass

  create = "CREATE TABLE STOCKPRICE (id SMALLINT NOT NULL, company VARCHAR(30), stockshare DECIMAL(7,2), stockprice DECFLOAT(16))"
  result = ibm_db.exec_immediate(conn, create)

  insert = "INSERT INTO STOCKPRICE (id, company, stockshare, stockprice) VALUES (10,'saba',100.002, 990.356736488388374888532323)"
  result = ibm_db.exec_immediate(conn, insert)

  query = 'SELECT * FROM STOCKPRICE ORDER BY id ASC'
  stmt = ibm_db.prepare(conn, query)

  ibm_db.execute(stmt)
  data = ibm_db.fetch_both( stmt )
  while ( data ):
    print( "%s : %s : %f : %s\n" % (data[0], data[1], decimal.Decimal(data[2]), data[3]))
    data = ibm_db.fetch_both( stmt )

  ibm_db.close(conn)

ibm_db returns string format for Numeric, decimal and decfloat.

**Comment by SabaKauser** [comment]
Any comments?
