### ISSUE TITLE
Thread-safety clarification

### ISSUE THREAD

**Issue by dsuch** [ibmdb/python-ibmdb#284]
Hello,

I'd like to confirm the situation with regards to multithreading as far as ibm_db goes.

The module's thread safety is set to 'threadsafety = 0', that is, per [PEP-249](https://www.python.org/dev/peps/pep-0249/), threads may not share the module.

I'm not clear in this case if it should be attempted at all to use the library in a multi-threaded program (or a multi-greenlet one but it amounts to the same thing)?

Even if I import the module in each thread separately, CPython will naturally return a reference to the same module object and this will make multiple threads/greenlets share the module which per its spec should not be done.

I'm asking about it because I'd like to add DB2 support to [Zato](https://zato.io/docs/) but with this level of thread safety, I'm not really sure if the library is to be used for anything except for single-threaded programs?

Regards.

**Comment by SabaKauser** [comment]
Let me get back to you on this.

**Comment by SabaKauser** [comment]
Hello Dariusz,

Which module did you try? ibm_db or ibm_db_dbi?
threadsafety=0 is set in ibm_db_dbi. can you confirm.

We do have thread safe blocks for odbc API calls in ibm_db and these were added via https://github.com/ibmdb/python-ibmdb/issues/50.
Is this what you are looking for?

**Comment by dsuch** [comment]
Hi @SabaKauser,

I did not try anything, I was simply trying to clarify the feature set of the library and you are right that I said ibm_db when I meant ibm_db_dbi.

Thus, to confirm it, I am interested in ibm_db_dbi's thread-safety with regards to [PEP-249](https://www.python.org/dev/peps/pep-0249/) which is set to 0 so my understanding is that this library may be used with single-threaded programs only, if I interpret it correctly?

Thanks.

**Comment by SabaKauser** [comment]
Hello Dariusz,

Yes, you are correct. We do not support multi-threading.

Thanks,
Saba.

**Comment by dsuch** [comment]
I see, thanks for the update.
