### ISSUE TITLE
Include license copy

### ISSUE THREAD

**Issue by pokoli** [ibmdb/python-ibmdb#285]
It's a good practice to include the applicable license in the source code and into the source code distributions.

**Comment by hemlatabhatt** [comment]
@pokoli The license file is present in the Source code .TIA

**Comment by pokoli** [comment]
@hemlatabhatt yes, you are right. But the license is not visible on the root directory which may cause confusion. I added a PR that should fix it.

**Comment by SabaKauser** [comment]
I will leave this as it is for now.
