### ISSUE TITLE
Charset issues

### ISSUE THREAD

**Issue by 54346946** [ibmdb/python-ibmdb#291]
My software version:
Python 2.7.8
DB2 V10.5: Database code set is utf-8

I am trying to insert data into DB2 through ibm_db. But I encoutered charset issues. The data arenot correct in DB2 that the words are changed. How can I get the correct result in DB2? Does ibm_db neet to set charset to connect to DB2?

Below is original text. It's non-English words and encode is UTF-8. After saving in DB2, the words are changed.
'Chef de Produits Sénior Hémophilie'

Use UTF-8
'Chef de Produits Sénior Hémophilie' -> 'Chef de Produits SAnior HAmophilie'

Use unicode
'Chef de Produits Sénior Hémophilie'.decode('UTF-8') -> 'Chef de Produits Senior Hemophilie'

**Comment by SabaKauser** [comment]
I tried on linux with a utf-8 database, and I could see correct results.

test snip:

  insert = "INSERT INTO STOCKPRICE (id, company, stockshare, stockprice) VALUES (10,'Hém',100.002, 990.356736488388374888532323)"
  result = ibm_db.exec_immediate(conn, insert)

  query = 'SELECT * FROM STOCKPRICE ORDER BY id ASC'


hotellnx108: home/sakauser/python_samples> python select.py
10 : Hém : 100.000000 : 990.3567364883884

which OS did you try on? and what is the code page, locale set on your client?

**Comment by 54346946** [comment]
It's my fault. Before data passing into ibm_db, there is a module unicodedata will change the character. That is the reason why I cannot save correct data into DB2. I think we can close this ticket . Thanks.
