### ISSUE TITLE
ibm_db Setup script exited with error: command 'powerpc64le-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by frjhong** [ibmdb/python-ibmdb#292]
Hi ,
Did ibm_db-2.0.8a support powerpc64le? We try to install ibm_db on ppc64le , but setup script show 'powerpc64le-linux-gnu-gcc' failed. The installation process is as below , would you give us some suggestion?

root@powerait01:/opt/ibm_db-2.0.8a# uname -a
Linux powerait01 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:26:02 UTC 2017 ppc64le ppc64le ppc64le GNU/Linux

root@powerait01:/opt/ibm_db-2.0.8a# apt-get install python-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-dev is already the newest version (2.7.11-1).
0 upgraded, 0 newly installed, 0 to remove and 99 not upgraded.

root@powerait01:/opt/ibm_db-2.0.8a# easy_install ibm_db
Searching for ibm_db
Reading https://pypi.python.org/simple/ibm_db/
Downloading https://pypi.python.org/packages/f8/6f/5f8186cb31021409235a948be5e29                                                                             d77761ef92747a101360003747c4105/ibm_db-2.0.8.tar.gz#md5=3ec936255ac69d2746433c6d                                                                             68c694d6
Best match: ibm-db 2.0.8
Processing ibm_db-2.0.8.tar.gz
Writing /tmp/easy_install-dc5d2P/ibm_db-2.0.8/setup.cfg
Running ibm_db-2.0.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-dc5d2P/i                                                                             bm_db-2.0.8/egg-dist-tmp-Irdij7
Detected 64-bit Python
Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/driver                                                                             s/odbc_cli/ppc64_odbc_cli.tar.gz
warning: no files found matching 'README'
warning: no files found matching '*' under directory 'ibm_db_dlls'
In file included from clidriver/include/sqlcli.h:983:0,
                 from clidriver/include/sqlcli1.h:45,
                 from ibm_db.h:15,
                 from ibm_db.c:29:
clidriver/include/sqlext.h:2133:1: warning: function declaration isn’t a prototy                                                                             pe [-Wstrict-prototypes]
 RETCODE SQL_API TraceCloseLogFile();            /* Request to close a trace log
 ^
clidriver/include/sqlext.h:2135:1: warning: function declaration isn’t a prototy                                                                             pe [-Wstrict-prototypes]
 DWORD   SQL_API TraceVersion();                 /* Returns trace API version */
 ^
clidriver/include/sqlext.h:2153:1: warning: function declaration isn’t a prototy                                                                             pe [-Wstrict-prototypes]
 DWORD SQL_API   ODBCGetTryWaitValue();          /* In Milliseconds(!) */
 ^
In file included from ibm_db.c:29:0:
ibm_db.h:31:0: warning: "PyObject_CheckBuffer" redefined
 #define PyObject_CheckBuffer  PyObject_CheckReadBuffer
 ^
In file included from /usr/include/python2.7/Python.h:133:0,
                 from ibm_db.c:27:
/usr/include/python2.7/abstract.h:534:0: note: this is the location of the previ                                                                             ous definition
 #define PyObject_CheckBuffer(obj) \
 ^
ibm_db.c: In function ‘_python_ibm_db_free_result_struct’:
ibm_db.c:362:32: warning: unused variable ‘prev_ptr’ [-Wunused-variable]
  param_node *curr_ptr = NULL, *prev_ptr = NULL;
                                ^
ibm_db.c:362:14: warning: unused variable ‘curr_ptr’ [-Wunused-variable]
  param_node *curr_ptr = NULL, *prev_ptr = NULL;
              ^
ibm_db.c: In function ‘_python_ibm_db_execute_helper1’:
ibm_db.c:5945:25: warning: unused variable ‘curr_ptr’ [-Wunused-variable]
  param_node *prev_ptr, *curr_ptr;
                         ^
ibm_db.c:5945:14: warning: unused variable ‘prev_ptr’ [-Wunused-variable]
  param_node *prev_ptr, *curr_ptr;
              ^
In file included from ibm_db.c:29:0:
ibm_db.c: In function ‘ibm_db_callproc’:
ibm_db.h:54:25: warning: comparison between pointer and integer
 #define NIL_P(ptr) (ptr == NULL)
                         ^
ibm_db.c:10710:38: note: in expansion of macro ‘NIL_P’
                                 if( !NIL_P(tmp_curr->ivalue ))
                                      ^
ibm_db.c: In function ‘ibm_db_get_last_serial_value’:
ibm_db.c:10932:19: warning: pointer targets in assignment differ in signedness [                                                                             -Wpointer-sign]
             value = ALLOC_N(char,31);
                   ^
ibm_db.c:10911:19: warning: unused variable ‘return_value’ [-Wunused-variable]
         PyObject *return_value = NULL;
                   ^
ibm_db.c:10909:12: warning: unused variable ‘stmt’ [-Wunused-variable]
  PyObject *stmt = NULL;
            ^
ibm_db.c: In function ‘ibm_db_field_nullable’:
ibm_db.c:7164:1: warning: control reaches end of non-void function [-Wreturn-typ                                                                             e]
 }
 ^
**clidriver/lib/libdb2.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
error: Setup script exited with error: command 'powerpc64le-linux-gnu-gcc' faile                                                                             d with exit status 1**

root@powerait01:/opt/ibm_db-2.0.8a# python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
'>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ibm_db.py", line 10, in <module>
    __bootstrap__()
  File "ibm_db.py", line 9, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
**ImportError: ./ibm_db_dlls\ibm_db.dll: cannot open shared object file: No such file or directory**
'>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
'>>>
root@powerait01:/opt/ibm_db-2.0.8a#

**Comment by SabaKauser** [comment]
As of today, we do not have setup support for linuxppc64le. We have support for LinuxPPC64 BE and LinuxPPC32 BE.

If you would like to have setup support, I can provide you with modified file, however, please note that we have not validated the driver on powerpc64 LE.

**Comment by frjhong** [comment]
Hi , 
Thank you for your explanation. Because We need to use powerpc64 LE arch to connect DB2 , please provide us modified file.

**Comment by SabaKauser** [comment]
I am attaching setup.py file. I could not test it as I do not have a linuxppcle machine currently. 
could you test and let me know if you find any issues with setup.


[setup.zip](https://github.com/ibmdb/python-ibmdb/files/1579288/setup.zip)
you just need to replace the setup.py in ibm_db source and install the driver manually.

cd <path to setup.py>
python setup.py build
python setup.py install

An alternate method than to use modified setup.py is to do following:
install odbc and clidriver for linuxppcle64 and set IBM_DB_HOME to path upto clidriver for the clidriver installation.
python setup.py build
python setup.py install.

I am on vacation until monday and back on tuesday.

**Comment by TonyWedu** [comment]
@SabaKauser 
I am create patch for setup.py, it workable. refer:

--- orig-ibm_db-2.0.8a/setup.py 2017-12-13 11:36:36.000000000 +0800
+++ ibm_db-2.0.8a/setup.py      2017-12-21 22:36:42.354402480 +0800
@@ -5,6 +5,7 @@
 import tarfile
 import zipfile
 import shutil
+import platform
 
 if sys.version_info >= (3, ):
     from urllib import request
@@ -31,6 +32,7 @@
 ibm_db_lib_runtime = ''
 license_agreement = False
 prebuildIbmdbPYD = False
+process_ = ''
     
 if machine_bits == 64:
     is64Bit = True
@@ -102,8 +104,12 @@
         if (_checkOSList(os.uname(),'ppc')):   
             os_ = 'ppc'
             if is64Bit:
-                cliFileName = 'ppc64_odbc_cli.tar.gz'
-                arch_ = 'ppc64'
+                if ('ppc64le' in platform.processor()):
+                    cliFileName = 'ppc64le_odbc_cli.tar.gz'
+                    arch_ = 'ppc64le'
+                else:
+                    cliFileName = 'ppc64_odbc_cli.tar.gz'
+                    arch_ = 'ppc64'
             else:
                 cliFileName = 'ppc32_odbc_cli.tar.gz'
                 arch_ = 'ppc*'

[setup.patch.zip](https://github.com/ibmdb/python-ibmdb/files/1579550/setup.patch.zip)

**Comment by vibkulkarni** [comment]
was this patch checked in ??  I am trying to build https://pypi.python.org/pypi/ibm_db and it fails. I did try with the patch here and it worked fine..

**Comment by SabaKauser** [comment]
Its not checked-in yet.  I shall do it in sometime.

**Comment by SabaKauser** [comment]
Sure. Will do that.

**Comment by jtfogarty** [comment]
@SabaKauser Is this available?  I have a need to connect DB2 from Jupyter.  Thanks

**Comment by vibkulkarni** [comment]
@jtfogarty you can use this PR and try it for ppc64le ,
https://github.com/ibmdb/python-ibmdb/pull/311
