### ISSUE TITLE
insert language special characters

### ISSUE THREAD

**Issue by jframier** [ibmdb/python-ibmdb#295]
Hi
I am trying to insert spécial caractère into a iseries file 
The complete code is below

import sys
import ibm_db_dbi as dbi
conn = dbi.connect()
cursor = conn.cursor()
sql = "INSERT INTO JFR.FILE (CTGENR, CTCODE, CTDSC1) VALUES('T1', 'T1C', 'éÉ') with nc"
print("SQL='{0}'".format(sql))
try:
		stmt = cursor.execute(sql)
except:
		print("ERROR: %s %s %s" % (sys.exc_info()[0], sys.exc_info()[1], sys.exc_info()[2]))
finally:
		conn.close()

ERROR: <class 'ibm_db_dbi.ProgrammingError'>, ibm_db_dbi::ProgrammingError: Token N was not valid. Valid tokens: ALL CS CHG NONE RR RS UR NC. SQLSTATE=42601 SQLCODE=-104, <traceback object at 0x3035bc34>

I am using python3 located in /QOpenSys/QIBM/ProdData/OPS/Python3.4/bin
and the latest PTF on Iseries

Is there a setup on the connection to do for special characters
presently I remove them all 
program code page is 819 and tried Iseries file CCSID(500) and 37

**Comment by kadler** [comment]
So it seems that inline special characters has issues, but I'm not sure why yet. The statement text should get passed through as UTF-8 and converted to Job CCSID, but it gets a warning: `ibm_db_dbi::ProgrammingError: Token WIT was not valid. Valid tokens...` Seems that the statement text is getting corrupted during corruption or something.

Using parameter markers should be good, but it seems that the multi-byte UTF-8 characters (é = c3a9, É = c389) are messing up lengths somewhere:

```
éÉ -> é
éÉab -> éÉ
éÉabc -> éÉa
```

**Comment by jframier** [comment]
Here is the output of the dspjoba
                      Display Job Definition Attributes      
Job:   JFRF           User:   JFR            Number:   163175
                                                             
Device recovery action  . . . . . . . . . . . . . :   *DSCMSG
Time slice end pool . . . . . . . . . . . . . . . :   *NONE  
Print key format  . . . . . . . . . . . . . . . . :   *PRTHDR
Sort sequence . . . . . . . . . . . . . . . . . . :   *HEX   
  Library . . . . . . . . . . . . . . . . . . . . :          
Language identifier . . . . . . . . . . . . . . . :   FRC    
Country or region identifier  . . . . . . . . . . :   CA     
Coded character set identifier  . . . . . . . . . :   37     
Default coded character set identifier  . . . . . :   37     
Character identifier control  . . . . . . . . . . :   *DEVD  
Job message queue maximum size  . . . . . . . . . :   16     
Job message queue full action . . . . . . . . . . :   *NOWRAP
Allow multiple threads  . . . . . . . . . . . . . :   *NO    
Auxiliary storage pool group  . . . . . . . . . . :   *NONE  
Spooled file action . . . . . . . . . . . . . . . :   *KEEP

**Comment by jframier** [comment]
Is it some thing that I need to call IBM service ?

**Comment by jframier** [comment]
wrong button

**Comment by kadler** [comment]
You can open a PMR if you like. Otherwise, I can just deal with it here.

**Comment by jframier** [comment]
Tanks If it is the same I will wait

**Comment by jframier** [comment]
Hi Kevin

 

Any new

Thanks

JF

**Comment by SabaKauser** [comment]
Do we need to keep this open?

**Comment by jframier** [comment]
Hi

 

Yes, please

No response yet but the problem is still there

 

Thanks

**Comment by SabaKauser** [comment]
following up to see if this is fixed . Can some one confirm.

**Comment by jframier** [comment]
no news
I will see if there is a new version
If not I will open a PMR at IBM
Thanks

**Comment by richardschoen** [comment]
Just wanted to add to this. Ran into this issue today with special characters. Just padded the end of the SQL string with ( blanks about 10) and this works now.
