### ISSUE TITLE
ibm_db not downloading the proper db2 odbc_cli driver for ppc64le

### ISSUE THREAD

**Issue by Styx13** [ibmdb/python-ibmdb#296]
There are not test to properly check the ppc64le architecture and download the ppc64le version of the odbc_cli driver.
Instead, it downloads the ppc64 version (big endian instead of little endian) and thus the build does not work.

Please add a test to properly detect ppc64le (little endian) and download the correct odbc_cli driver.

Thanks !

**Comment by kadler** [comment]
Seems like a duplicate of #292

**Comment by Styx13** [comment]
Yes, you are right, sorry I did not do a proper search.

I was able to install the ppc64le version of the odbc_cli driver by just editing the setup.py code and the installation worked.

So far it seems to be working ok from Ubuntu 16.04 running on PPC64LE (and connecting to a DB2 instance running on AIX)
