### ISSUE TITLE
SQL1042C Error on windows ubuntu

### ISSUE THREAD

**Issue by whuey1992** [ibmdb/python-ibmdb#298]
I'm running ubuntu bash on windows 10. I try to run python script which works fine on my mac, but I get SQL1042C Error on windows. I tried changing the DYLD_LIBRARY_PATH with export DYLD_LIBRARY_PATH=~/anaconda2/lib/python2.7/site-packages/ibm_db-2.0.8-py2.7-linux-x86_64.egg/clidriver/lib/icc:$DYLD_LIBRARY_PATH , but no luck. Please help

**Comment by kadler** [comment]
`DYLD_LIBRARY_PATH` is a Mac-specific variable. `LD_LIBRARY_PATH` should be the Linux equivalent. I have no idea whether things will actually work when running in the Windows Subsystem for Linux, however.

**Comment by whuey1992** [comment]
Hey thanks I did not know that, however even changing LD_LIBRARY_PATH I am getting the same issue.

**Comment by SabaKauser** [comment]
is the issue resolved?
if not, can you share db2 traces ?

db2trc on -f trc.dmp
<run app>
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc 

and share trc.flw, trc.fmt and trc.fmtc files.

**Comment by SabaKauser** [comment]
reopen if not resolved.
