### ISSUE TITLE
a licensing problem

### ISSUE THREAD

**Issue by pbandzi** [ibmdb/python-ibmdb#299]
SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968 SQLCODE=-1598

DB2 running on zOS.

where to put license? what license?

**Comment by SabaKauser** [comment]
You would either need a client side license that must be added to license folder of client installation (CLI Driver installation) or use Db2 Connect unlimited edition for system Z server side license that must be applied at the server by running db2connectactivate utility from client.

you can find more details in my blog here:
https://www.ibm.com/developerworks/community/blogs/96960515-2ea1-4391-8170-b0515d08e4da/entry/unlimited_licensing_in_non_java_drivers_using_db2connectactivate_utlility?lang=en

**Comment by SabaKauser** [comment]
I have lost access to our email conversation. Kindly copy the last conversation that you need assistance with.

**Comment by pbandzi** [comment]
Hi Saba,
Thank you for your response and patience with me. 
- The windows is installed on the server. My colleague who has windows is able to connect to DB2 too. On both I installed "python-ibm_db" using "pip" did not care about anything else and it works.
- I have a Mac from which i cannot connect due to license issue 
- When try from linux, it is a docker container running either on my mac -> license issue
- or on my colleague windows PC when running from linux container -> license issue, but when using it directly on windows system (python on windows) it works.
 

Seems no *.lic file is present on windows and no cfgcache directory is there. Is that mean that we are using licensing on server side?
Again sorry to bother you, but no-one here can explain this to me and am totally confused :)

 Directory of C:\Users\Administrator\bender-collector\env\Lib\site-packages\clidriver\license
01/05/2018  10:01 AM    <DIR>          .
01/05/2018  10:01 AM    <DIR>          ..
01/05/2018  10:01 AM            25,936 odbc_notices.rtf
01/05/2018  10:01 AM    <DIR>          Windows
               1 File(s)         25,936 bytes
               3 Dir(s)  21,097,381,888 bytes free
 Directory of C:\Users\Administrator\bender-collector\env\Lib\site-packages\clidriver
01/05/2018  10:01 AM    <DIR>          .
01/05/2018  10:01 AM    <DIR>          ..
01/05/2018  10:01 AM    <DIR>          bin
01/05/2018  10:01 AM    <DIR>          bnd
01/05/2018  10:01 AM    <DIR>          cfg
01/05/2018  10:01 AM    <DIR>          conv
01/05/2018  10:01 AM    <DIR>          db2
01/05/2018  10:01 AM    <DIR>          lib
01/05/2018  10:01 AM    <DIR>          license
01/05/2018  10:01 AM    <DIR>          msg
01/05/2018  10:01 AM                 0 __init__.py
01/05/2018  10:01 AM    <DIR>          __pycache__
               1 File(s)              0 bytes
              11 Dir(s)  21,097,381,888 bytes free
 
thank you,

**Comment by SabaKauser** [comment]
If you were using server based licensing, you should have seen conlic.bin file in your client license directory. Are you sure your python ibm_db driver is using the same C client library that you have listed above?

Even if its docker container, you should be able to connect to host unless the license from your windows machine is activated at a different db2level. i.e if your windows client from where you have activated license to z/OS is say V10.5 and your python driver from docker is using V11.1 C driver(clidriver), you would need to activate the license from V11.1 client again.
Apart from that, I do not see any other problem.

If the issue is still not resolved, I would like to see db2 traces when you attempt connection from your direct windows installation v/s docker.
to collect db2 traces: exe under clidriver/adm
db2trc on -f trc.dmp
<try connection from python driver>
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc.
and share trc.flw trc.fmt and trc.fmtc files.

on a side note, can you also check if you have set IBM_DB_HOME env variable some how.

**Comment by pbandzi** [comment]
Sorry for delay, 
here are logs from linux and windows..

[db2-trace.tar.gz](https://github.com/ibmdb/python-ibmdb/files/1706487/db2-trace.tar.gz)

on linux I see that

trc.fmt:	DB2 Connect license key is not activated on the requested database server. To activate the license key, use db2connectactivate utility.

on windows I am not even sure if that utility was used. After execute my script those trc.dmp was not updated.

I understand that on db2 server someone should use db2connectactivate utility. But I still don't understand how is it that it works on windows.

thank you

**Comment by SabaKauser** [comment]
Hi,
Traces collected on windows are not correct. There is no processing logged for the client.
Linux traces shows you are connecting to DVIEDSNV(mvsadm1.emea.ibm.com/6045 picked from db2dsdriver.cfg located under /usr/local/lib/python3.6/site-packages/clidriver/cfg/db2dsdriver.cfg) and server side license is not activated for it. 
My only guess is that, from windows, you are attempting connection to a different server than what you are attempting via windows. If this is not the case, I still need traces from windows client to investigate this further.
Can you check the db2dsdriver.cfg for your windows client and see which db you are connecting to.

**Comment by SabaKauser** [comment]
Is there anything more that I can assist you with?

**Comment by eagerstudent-sil** [comment]
Hi SabaKauser!

I've encountered the same issue as pbandzi did and I can't seem to solve it by myself. I've followed the directions you gave here and created the traces. Could you please take a look at them and help me with this? Thank you!
[db2trace.zip](https://github.com/ibmdb/python-ibmdb/files/3642129/db2trace.zip)

**Comment by SabaKauser** [comment]
Hello,
From the traces, I see that you are using Db2 on z/OS and to use db2 python driver, you need to have a client side license. The license can be applied at client side which will be a license file to be copied under clidriver/license folder or buy db2connectactivate(Db2 connection unlimited Edition for system z). You can find more information here -> https://www.ibm.com/developerworks/community/blogs/96960515-2ea1-4391-8170-b0515d08e4da/entry/unlimited_licensing_in_non_java_drivers_using_db2connectactivate_utlility?lang=en
