### ISSUE TITLE
I added some code to get stmt and hdbc handles

### ISSUE THREAD

**Issue by asierra01** [ibmdb/python-ibmdb#301]
I created a fork with my changes, I need these handles from python to call directly using ctypes, something like this, I do not close them, just use it.....

         stmt_handle = ibm_db.get_stmt_handle(stmt)
         stmt_hdbc   = ibm_db.get_hdbc_handle(stmt)
        #use stmt_handle below ......
        #may use stmt_hdbc later....

        self.real_size_xml_message = ctypes.c_int(len(self.xml_message))
        clirc = self.test_cli.libcli64.SQLBindParameter(
                                                       stmt_handle,
                                                        7,
                                                        SQL_PARAM_OUTPUT,
                                                        SQL_C_BINARY,
                                                        SQL_BLOB,
                                                        0,
                                                        0,
                                                        byref(self.xml_message),
                                                        len(self.xml_message),
                                                        byref(self.real_size_xml_message))

**Comment by SabaKauser** [comment]
can you share your changes link.

**Comment by asierra01** [comment]
here https://github.com/asierra01/python-ibmdb, I am not requesting a PR, just something I use, can we incorporate this on trunk ? possible....

**Comment by SabaKauser** [comment]
ok. I see that you are returning the address equivalent of the handles. Right now, I do not see the need of it to add to our code base. But I shall ask for PR whenever needed. 

Thank you and keep contributing :)
