### ISSUE TITLE
Install failed ibm_db

### ISSUE THREAD

**Issue by eovolkov** [ibmdb/python-ibmdb#302]
> Collecting ibm-db==2.0.7 (from -r requirements.txt (line 54))
>   Downloading ibm_db-2.0.7.tar.gz (553kB)
>     Complete output from command python setup.py egg_info:
>     Detected 64-bit Python
>     Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-y7z4fg_g/ibm-db/setup.py", line 159, in <module>
>         file_stream = BytesIO(request.urlopen(url).read())
>       File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
>         return opener.open(url, data, timeout)
>       File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
>         response = meth(req, response)
>       File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
>         'http', request, response, code, msg, hdrs)
>       File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
>         return self._call_chain(*args)
>       File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
>         result = func(*args)
>       File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
>         raise HTTPError(req.full_url, code, msg, hdrs, fp)
>     urllib.error.HTTPError: HTTP Error 500: Internal Server Error
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-y7z4fg_g/ibm-db/
> The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1
> 

Looks like there are no any required files in https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli

**Comment by pajachiet** [comment]
We have the same issue here. This seems a regular issue, as can be seen in these issues https://github.com/ibmdb/node-ibm_db/issues/277 & https://github.com/ibmdb/node-ibm_db/issues/156, and the installation procedure of [node-ibm_db](https://github.com/ibmdb/node-ibm_db#important-environment-variables-and-download-essentials)

Does any one know if there is a mirror somewhere else ?

**Comment by SabaKauser** [comment]
That's an IBM site and I believe when you tried downloading, it was having network issues or it might be down. Can you try again and let us know if the problem persists. I shall report it to and get it correct if the problem continues.

**Comment by pajachiet** [comment]
It is working again https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/. 
But the problem is not new, and may appear again. 

We will have to install this driver on many environments in the coming months
Is there a more reliable way to fetch it ?

**Comment by SabaKauser** [comment]
Let me check with site owners. When exactly do you plan to have the installations so that I inform to monitor to make sure the problem does not happen while you use it.

**Comment by pajachiet** [comment]
We are building a continuous integration pipeline, which should be able to
regularly download those drivers.
Otherwise we will build a mirror for our own needs.

Pierre-Alain
06 16 48 57 52

2018-02-19 13:57 GMT+01:00 Saba Kauser <notifications@github.com>:

**Comment by SabaKauser** [comment]
Received response from site owner:

the public.dhe.ibm.com FTP site is redundant and normally there should be no downtime. Unfortunately a network issue caused by a change outside our domain, even if for few hours, did not allow the access to a handful of sites, among them public.dhe.ibm.com.

We apologize for the inconvenience.

**Comment by pajachiet** [comment]
Many thanks for those information and your assistance. It is working fine now. 
We will thrust the FTP site unless we encounter another issue later.
