### ISSUE TITLE
Python Pandas Read Sql with ibm_db and ibm_db_dbi

### ISSUE THREAD

**Issue by daniielamir** [ibmdb/python-ibmdb#305]
am using Pandas Read Sql in Python for executing sql-statements in IBM DB2 and saving the repsonse in pandas dataframes. Now I am trying to execute a sql-statement containing a non ASCII character, a letter from the Swedish alphabet: 'Å' (others are Å, Ä and Ö) but I am getting this error:

"DatabaseError: Execution failed on sql 'SELECT * FROM DATA_CONFIG WHERE TAG_NAME='Å'': ibm_db_dbi::Error: Error occure during processing of statement"

This is my code:

import ibm_db
import ibm_db_dbi
import pandas as pd

def sqlToFrame(sql): # Function for creating pandas dataframes from SQL-statements
    con = ibm_db.connect(connection_string, "", "")
    conn = ibm_db_dbi.Connection(con)
    return pd.read_sql(sql, conn)

df = sqlToFrame("SELECT * FROM DATA_CONFIG WHERE TAG_NAME='Å'")

I've tried executing the statement in the IDE in the IBM DB2 interface which works perfectly fine. Therefore I am figuring that the problem might be connected to how I establish the connection/the DB2 driver pandas uses. I have tried finding a way to set an encoding but can't find anything. How can I solve this? I also know this is possible because another package that builds upon ibm_db accept these characters. The characters are a from the ISO-8859-1 series

**Comment by SabaKauser** [comment]
Hello,
I tried from my windows 10 using Python 3.6(32-bit) using direct ibm_db_dbi interface and can see the correct result fetched.
ibm_db(or ibm_db_dbi) uses IBM CLI Driver(ODBC) internally and as I can see from traces of the driver, the application code page is 1252 which is superset of  ISO 8859-1. You can see from traces that it is c385 in Hex(UTF-80.

  DDM Format: d0 SEND(AR) OBJDSS - Object Data Stream Structure
  LL: 61  CORR: 0001  CHAINED: n  CONT ON ERR: n  SAME CORR FOR NEXT DSS: n  

    NM: SQLSTT - SQL Statement
      LL: 55    CP: 2414   
      DATA:                              (ASCII)          (EBCDIC)
      000000002D73656C 656374202A206672  ....-select * fr .......%........
      6F6D20444154415F 434F4E4649472057  om DATA_CONFIG W ?_.....^.!+.....
      4845524520544147 5F4E414D453D27**C3**  HERE TAG_NAME='. ........^+.(...C
      **85**27FF                             .'.              e..

My sample is this:
import ibm_db
import ibm_db_dbi


conn=ibm_db.connect('database=<dbname>,uid=<username>;pwd=<pwd>;port=<portno>;hostname=<hostname>;protocol=tcpip','','')
con = ibm_db_dbi.Connection(conn)
result1 = ibm_db.exec_immediate(conn,"insert into data_config values('Å','sabakauser')")
cur = con.cursor()
res=cur.execute("select * from DATA_CONFIG WHERE TAG_NAME='Å'")
rs=cur.fetchone()
print(rs)

  
ibm_db.rollback(conn)  

output:
('Å', 'sabakauser') 

So this implies, we do process the character correctly. What I suspect is ibm_db_dbi is receiving something different from pandas layer?

**Comment by daniielamir** [comment]
Hi! Thank you for the answer. As it appears to be this problem only exists in Python 2.7 and not in Python 3. By upgrading my python version I solved the problem.

**Comment by SabaKauser** [comment]
great! closing.
Have a great day :)
