### ISSUE TITLE
connect() stays idle

### ISSUE THREAD

**Issue by agSant01** [ibmdb/python-ibmdb#312]
# Unsuccessful connection attempt

When trying to establish a connection,
```
ibm_db.connect("DATABASE=DB;HOSTNAME=xx.x.x.xx;
             PORT=xxxx;PROTOCOL=TCPIP;UID=xxxx;PWD=xxx;","","")
```
there is no response. Neither an error is prompted or success, also the script stays idle at the connection attemp. 

Also tried,

```
ibm_db.connect("DRIVER={IBM DB2 ODBC DRIVER};DATABASE=DB;HOSTNAME=xx.x.x.xx;
              PORT=xxxx;PROTOCOL=TCPIP;UID=xxxx;PWD=xxx;","","")
```

**Comment by SabaKauser** [comment]
reopen if issue persists.
