### ISSUE TITLE
NameError: name 'arch_' is not defined --- Raspberry Pi with Raspbian

### ISSUE THREAD

**Issue by IrrelevantMagician111** [ibmdb/python-ibmdb#321]
I am getting an error when trying to install ibm_db on Raspberry Pi. I cloned the git repo and ran the setup.py file. This is the output:

Traceback (most recent call last):
  File "setup.py", line 161, in <module>
    easy_cli_path = os.path.join(tmp_path, 'ibm_db-%s.egg' % ("-".join([VERSION, "py"+sys.version.split(" ")[0][0:3]]) if('win32' in sys.platform) else "-".join([VERSION, "py"+sys.version.split(" ")[0][0:3], os_, arch_])), 'clidriver')
NameError: name 'arch_' is not defined

**Comment by SabaKauser** [comment]
we support installations for following OS:
Linuxamd64 
linuxia32
sunamd
sun sparc
linuxx390
windows
mac
LinuxPPC(LE 64 bit, BE 64 and 32 bit)
AIX(64 and 32 bit)

**Comment by cvdantas** [comment]
I have stumbled on the very same problem. Any plans to support RPI in the near future?

**Comment by SabaKauser** [comment]
No plans yet, not in near future. I will add this to bucket-list and see if we can do something.

**Comment by shyamsantoki** [comment]
Any update?

**Comment by amukherjee28** [comment]
In order to support ibm_db on a new platform, in this case Raspberry Pi we will need a clidriver on the same platform which will allow communication with the Database server.

Since currently we do not have clidriver support on Raspberry Pi it will not be feasible to support ibm_db.

Thanks

**Comment by amukherjee28** [comment]
Unfortunately having a CLIDIRVER for Raspberry Pi is currently not part of our Roadmap.
In case we have the support for Raspberry Pi we will happy to include it in the list of supporting platform as part of the documentation.
Closing this issue for now as I cannot commit on any time line on the same.

Thanks.
