### ISSUE TITLE
ibm_db needs specific exceptions

### ISSUE THREAD

**Issue by Tam-Lin** [ibmdb/python-ibmdb#323]
Even if they're generic to ibm_db, a generic try/except statement is considered bad practice.

**Comment by amukherjee28** [comment]
Can we have a bit more explanation on this.
@Tam-Lin can you give an example if possible.

I am not able to understand on what needs to be done for this.

Thanks

**Comment by Tam-Lin** [comment]
Since I opened the defect, it appears that the exceptions being generated by ibm_db and the exception handling has been greatly improved.  So closing.
