### ISSUE TITLE
setup.py can download wrong cli file

### ISSUE THREAD

**Issue by Tam-Lin** [ibmdb/python-ibmdb#326]
Already fixed in pull request #325

There’s a bug in the setup for ibm_db.  Specifically, when you’re trying to install the command line library.  You have function that looks through everything that’s returned from os.uname() to determine which one to download.  That function looks through all the items returned, which includes (sysname,nodename, release, version, machine).  The problem is that when you’re checking to determine which libraries to download for linux, you look at all those fields, and right now, the release string for RHEL zLinux is '3.10.0-862.el7.s390x’, so if you try installing ibm_db on zLinux, it downloads the cli_libraries for the x86 platform and the install fails.  What I’m proposing you do instead is only look at the machine field to determine the architecture.  I don’t have access to all those types of machines to validate that this is the correct solution, but it does work for zLinux.  I’m assuming you have a place you can validate the other platforms.

**Comment by SabaKauser** [comment]
fixed, will be released to pypi shortly.
