### ISSUE TITLE
How to solve the below error 

### ISSUE THREAD

**Issue by venkateshmunagala** [ibmdb/python-ibmdb#327]
C:\Python36\python.exe C:/Users/vmunagal/PycharmProjects/untitled4/venky.py
Traceback (most recent call last):
  File "C:/Users/vmunagal/PycharmProjects/untitled4/venky.py", line 187, in <module>
    ibm_db_conn = ibm_db.connect(conn_str,'','')
 SQLCODE=-1336

**Comment by venkateshmunagala** [comment]
can some please let me know the reason for the above error

**Comment by SabaKauser** [comment]
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.messages.sql.doc/doc/msql01336n.html

closing, re-open if you need further assistance.
