### ISSUE TITLE
Licensing issue on zLinux (and probably other lines)

### ISSUE THREAD

**Issue by Tam-Lin** [ibmdb/python-ibmdb#330]
Running with a fixed ibm_db install, that's pulling in a correct library file.  I'm now getting a missing license error when connecting to a Db2 for z server.  I have a valid db2consv_zs.lic file, and can run the program in question on a Mac, using the same license file.  The license file is located at site-packages/ibm_db-2.0.8-py2.7-linux-s390x.egg/clidriver/license/db2consv_zs.lic.

**Comment by SabaKauser** [comment]
can you collect traces and share. Also run : ldd <ibm_db shared library>
e.g : on my linuxppc it is : ibm_db.cpython-36m-powerpc64-linux-gnu.so located under egg folder.
the libdb2.so file it has dependency on is picked from below path in my case:
  libdb2.so.1 => /home/skauser/validate_V105_linuxppc64_BE/clidriver/lib/libdb2.so.1 (0x00000fffae100000)
and I have the license present under /home/skauser/validate_V105_linuxppc64_BE/clidriver/license/db2consv_zs.lic
and I can connect to the db successfully.

to collect traces:
cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
and share the trc.flw, trc.fmt and trc.fmtc files with us to assist you further.

**Comment by Tam-Lin** [comment]
Attached.  Note that the dump file was trc.dump, not trc.dmp.




[Archive.zip](https://github.com/ibmdb/python-ibmdb/files/2185208/Archive.zip)

**Comment by SabaKauser** [comment]
I can see that although the license is present at clidriver/license, it does not seem to be the correct license. What is the level of your client driver?
cd site-packages/ibm_db-2.0.8-py2.7-linux-s390x.egg/clidriver/bin
./db2level 

I believe its a V11.1 client. And your Mac OS might have a different version client whose license is db2consv_zs.lic. 
You can't use non V11.1 client license on a V11.1 installation. 

PS: the traces from MAC OS seem to be in binary.

**Comment by SabaKauser** [comment]
you can also verify the ProductVersion from the license file itself.
e.g:
In my license file, it is:
ProductName=DB2 Connect Unlim Ed zSeries
ProductVersion=11.1

**Comment by Tam-Lin** [comment]
It's whatever level I get from installing the ibm_db module, so whatever's being pulled from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/.  On Mac, it says it's 

> DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL10055" with level identifier "0606010E".
Informational tokens are "DB2 v10.5.0.5", "special_35187", "DARWIN64105_35187",
and Fix Pack "5".
Product is installed at
"/Users/kdm/src/testmatrix/.direnv/python-2.7.14/lib/python2.7/site-packages/cl
idriver".

On zLinux, it says 

> DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL10055" with level identifier "0606010E".
Informational tokens are "DB2 v10.5.0.5", "s141128", "IP23635", and Fix Pack
"5".
Product is installed at "..".

So it appears to be the same release.  The license file does specify ProductVersion=11.1.

**Comment by Tam-Lin** [comment]
OK, I was able to get a version of the license file for 10.5; things are working on both platforms now.
