### ISSUE TITLE
SQL10007N Message "0" could not be retrieved.

### ISSUE THREAD

**Issue by SzickA** [ibmdb/python-ibmdb#334]
Hello All,

I facing the following issue, after installing/setting everything correctly:

conn = ibm_db.pconnect(dsn,"", "")
Exception: [IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3". SQLCODE=-1042

I using OSX (High Sierra, 10.13.6) with python v3.6

Is there any workaround to solve the problem above? 

Thanks in advance
András

**Comment by SabaKauser** [comment]
Hello Andras,
Have you set DYLD_LIBRARY_PATH and PATH to point to clidriver?
The sqlcode is -1042 i,e SQL1042C but it seem like driver is unable to load correct library for printing message.

**Comment by SzickA** [comment]
Hi @SabaKauser 
Thanks for your answer,

I believe that i set both the DYLD_LIBRARY_PATH and PATH correctly, please see the results:
(Applications/dsdriver is the path where the dashdb driver package installed)

~$ echo $DYLD_LIBRARY_PATH
Applications/dsdriver/lib/icc:Applications/dsdriver/lib/:
~$ echo $PATH
Applications/dsdriver/lib/icc:Applications/dsdriver/lib/:/Applications/dsdriver/bin:/Applications/dsdriver/adm:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/zz00a8/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/zz00a8/lift-cli/:/Users/zz00a8/lift-cli/bin/:/Applications/dsdriver/:/Applications/dsdriver/lib/:/Applications/dsdriver/lib/icc/:/Applications/dsdriver/bin/:/Users/zz00a8/lift-cli/

**Comment by SabaKauser** [comment]
can you set DYLD_LIBRARY_PATH to Applications/dsdriver/lib/icc:Applications/dsdriver/lib/icc as well.

**Comment by SzickA** [comment]
Sorry for my late answer,
As i see both directory  added to DYLD_LIBRARY_PATH, also i disable the integrity protection in the system but the problem still persist

**Comment by SabaKauser** [comment]
Can you collect db2 and cli traces.
to collect traces:
cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files with us to assist you further.

**Comment by SabaKauser** [comment]
you have the traces?

**Comment by shj0180** [comment]
it is also maybe other problem:  telnet fail  or  drive version is not matching
