### ISSUE TITLE
installing with gcc-8.1.1 - large list of str format overflow errors (and a few others)

### ISSUE THREAD

**Issue by grooverdan** [ibmdb/python-ibmdb#340]
<pre>
$ easy_install ibm_db
Searching for ibm_db
Reading https://pypi.python.org/simple/ibm_db/
Downloading https://files.pythonhosted.org/packages/3f/61/389c6decacfed61c2724005b8c2be61f2c699f731b53af13517e5a0e6e98/ibm_db-2.0.9.tar.gz#sha256=72a5b1911125311bfa53dab40cf6684965abf4a548181f4af53dbe7d527f68c6
Best match: ibm-db 2.0.9
Processing ibm_db-2.0.9.tar.gz
Writing /tmp/easy_install-4eeq754l/ibm_db-2.0.9/setup.cfg
Running ibm_db-2.0.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-4eeq754l/ibm_db-2.0.9/egg-dist-tmp-vpy0h_wp
Detected 64-bit Python
Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
warning: no files found matching 'README'
warning: no files found matching '*' under directory 'ibm_db_dlls'
ibm_db.c: In function ‘_python_ibm_db_free_result_struct’:
ibm_db.c:363:32: warning: unused variable ‘prev_ptr’ [-Wunused-variable]
  param_node *curr_ptr = NULL, *prev_ptr = NULL;
                                ^~~~~~~~
ibm_db.c:363:14: warning: unused variable ‘curr_ptr’ [-Wunused-variable]
  param_node *curr_ptr = NULL, *prev_ptr = NULL;
              ^~~~~~~~
ibm_db.c: In function ‘_python_ibm_db_bind_data’:
ibm_db.c:5492:25: warning: comparison of integer expressions of different signedness: ‘SQLINTEGER’ {aka ‘int’} and ‘SQLUINTEGER’ {aka ‘unsigned int’} [-Wsign-compare]
        if (curr->ivalue <= curr->param_size) {
                         ^~
ibm_db.c:5496:25: warning: comparison of integer expressions of different signedness: ‘SQLINTEGER’ {aka ‘int’} and ‘long unsigned int’ [-Wsign-compare]
        if (curr->ivalue <= (curr->param_size * sizeof(SQLWCHAR))) {
                         ^~
ibm_db.c:5508:29: warning: comparison of integer expressions of different signedness: ‘int’ and ‘SQLUINTEGER’ {aka ‘unsigned int’} [-Wsign-compare]
     } else if (param_length <= curr->param_size) {
                             ^~
ibm_db.c:5629:24: warning: comparison of integer expressions of different signedness: ‘SQLINTEGER’ {aka ‘int’} and ‘SQLUINTEGER’ {aka ‘unsigned int’} [-Wsign-compare]
       if (curr->ivalue <= curr->param_size) {
                        ^~
ibm_db.c: In function ‘_python_ibm_db_execute_helper1’:
ibm_db.c:5954:25: warning: unused variable ‘curr_ptr’ [-Wunused-variable]
  param_node *prev_ptr, *curr_ptr;
                         ^~~~~~~~
ibm_db.c:5954:14: warning: unused variable ‘prev_ptr’ [-Wunused-variable]
  param_node *prev_ptr, *curr_ptr;
              ^~~~~~~~
ibm_db.c: In function ‘_ibm_db_chaining_flag’:
ibm_db.c:10225:5: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
     sprintf(err_fmt,"%s\nError %d: %s", err_fmt, (int)errNo, "%s \n");
     ^~~~~~~
ibm_db.c:10231:5: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
     sprintf(err_fmt,"%s\nError %d: %s", err_fmt, (int)errNo, "%s \n");
     ^~~~~~~
In file included from ibm_db.c:29:
ibm_db.c: In function ‘ibm_db_callproc’:
ibm_db.h:54:25: warning: comparison between pointer and integer
 #define NIL_P(ptr) (ptr == NULL)
                         ^~
ibm_db.c:10719:38: note: in expansion of macro ‘NIL_P’
                                 if( !NIL_P(tmp_curr->ivalue ))
                                      ^~~~~
ibm_db.c: In function ‘ibm_db_get_last_serial_value’:
ibm_db.c:10941:19: warning: pointer targets in assignment from ‘char *’ to ‘SQLCHAR *’ {aka ‘unsigned char *’} differ in signedness [-Wpointer-sign]
             value = ALLOC_N(char,31);
                   ^
ibm_db.c:10920:19: warning: unused variable ‘return_value’ [-Wunused-variable]
         PyObject *return_value = NULL;
                   ^~~~~~~~~~~~
ibm_db.c:10918:12: warning: unused variable ‘stmt’ [-Wunused-variable]
  PyObject *stmt = NULL;
            ^~~~
ibm_db.c: In function ‘ibm_db_field_nullable’:
ibm_db.c:7173:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ibm_db.c: In function ‘ibm_db_get_num_result’:
ibm_db.c:6880:44: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1015 [-Wformat-overflow=]
    sprintf(error, "SQLGetDiagField failed: %s",
                                            ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 25 and 1064 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c: In function ‘ibm_db_num_rows’:
ibm_db.c:6818:40: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1019 [-Wformat-overflow=]
    sprintf(error, "SQLRowCount failed: %s",
                                        ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 21 and 1060 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c: In function ‘ibm_db_num_fields’:
ibm_db.c:6744:45: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1014 [-Wformat-overflow=]
    sprintf(error, "SQLNumResultCols failed: %s",
                                             ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 26 and 1065 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c: In function ‘_python_ibm_db_bind_param_helper’:
ibm_db.c:2493:44: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1016 [-Wformat-overflow=]
     sprintf(error, "Describe Param Failed: %s",
                                            ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 24 and 1063 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:2466:44: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1016 [-Wformat-overflow=]
     sprintf(error, "Describe Param Failed: %s",
                                            ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 24 and 1063 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:2440:44: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1016 [-Wformat-overflow=]
     sprintf(error, "Describe Param Failed: %s",
                                            ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 24 and 1063 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:2414:44: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1016 [-Wformat-overflow=]
     sprintf(error, "Describe Param Failed: %s",
                                            ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 24 and 1063 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c: In function ‘_python_ibm_db_prepare_helper’:
ibm_db.c:5174:45: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1013 [-Wformat-overflow=]
   sprintf(error, "Statement Prepare Failed: %s", IBM_DB_G(__python_stmt_err_msg));
                                             ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 27 and 1066 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c: In function ‘ibm_db_result’:
ibm_db.c:7833:60: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 999 [-Wformat-overflow=]
    sprintf(error, "Column information cannot be retrieved: %s",
                                                            ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 41 and 1080 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c: In function ‘ibm_db_fetch_row’:
ibm_db.c:8587:60: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 999 [-Wformat-overflow=]
    sprintf(error, "Column information cannot be retrieved: %s",
                                                            ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 41 and 1080 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c: In function ‘ibm_db_execute_many’:
ibm_db.c:10506:40: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1022 [-Wformat-overflow=]
       sprintf(error, "Binding Error 1: %s",
                                        ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 18 and 1057 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:10546:46: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1018 [-Wformat-overflow=]
         sprintf(error, "Sending data failed: %s", IBM_DB_G(__python_stmt_err_msg));
                                              ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 22 and 1061 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:10586:39: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1019 [-Wformat-overflow=]
   sprintf(error, "SQLRowCount failed: %s",IBM_DB_G(__python_stmt_err_msg));
                                       ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 21 and 1060 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c: In function ‘_python_ibm_db_execute_helper1’:
ibm_db.c:6063:46: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1013 [-Wformat-overflow=]
    sprintf(error, "Statement Execute Failed: %s", IBM_DB_G(__python_stmt_err_msg));
                                              ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 27 and 1066 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:5875:38: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1022 [-Wformat-overflow=]
     sprintf(error, "Binding Error 1: %s",
                                      ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 18 and 1057 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:6042:39: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1022 [-Wformat-overflow=]
      sprintf(error, "Binding Error 3: %s", IBM_DB_G(__python_stmt_err_msg));
                                       ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 18 and 1057 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:5928:40: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1022 [-Wformat-overflow=]
       sprintf(error, "Binding Error 2: %s",
                                        ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 18 and 1057 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:5906:45: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1016 [-Wformat-overflow=]
      sprintf(error, "Describe Param Failed: %s",
                                             ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 24 and 1063 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:5915:39: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1022 [-Wformat-overflow=]
      sprintf(error, "Binding Error 2: %s",
                                       ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 18 and 1057 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:6012:37: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1024 [-Wformat-overflow=]
      sprintf(error, "Binding Error: %s", IBM_DB_G(__python_stmt_err_msg));
                                     ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 16 and 1055 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:6081:45: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1013 [-Wformat-overflow=]
   sprintf(error, "Statement Execute Failed: %s", IBM_DB_G(__python_stmt_err_msg));
                                             ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 27 and 1066 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:6105:42: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1018 [-Wformat-overflow=]
     sprintf(error, "Sending data failed: %s",
                                          ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 22 and 1061 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:6120:41: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1018 [-Wformat-overflow=]
    sprintf(error, "Sending data failed: %s",
                                         ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 22 and 1061 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c: In function ‘_python_ibm_db_bind_fetch_helper’:
ibm_db.c:8162:60: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 999 [-Wformat-overflow=]
    sprintf(error, "Column information cannot be retrieved: %s",
                                                            ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 41 and 1080 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:8172:51: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1008 [-Wformat-overflow=]
    sprintf(error, "Column binding cannot be done: %s",
                                                   ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 32 and 1071 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:8474:43: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1019 [-Wformat-overflow=]
       sprintf(error, "Failed to LOB Data: %s",
                                           ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 21 and 1060 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:8460:50: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1013 [-Wformat-overflow=]
        sprintf(error, "Failed to fetch LOB Data: %s",
                                                  ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 27 and 1066 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ibm_db.c:8266:34: warning: ‘%s’ directive writing up to 1039 bytes into a region of size 1024 [-Wformat-overflow=]
   sprintf(error, "Fetch Failure: %s", IBM_DB_G(__python_stmt_err_msg));
                                  ^~
In file included from /usr/include/stdio.h:862,
                 from /usr/include/python3.6m/Python.h:25,
                 from ibm_db.c:27:
/usr/include/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 16 and 1055 bytes into a destination of size 1039
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>

**Comment by IBMAmarPY** [comment]
Hello Daniel,

From the output, I see all are warnings. Did your build fail? 
We will consider fixing the warnings in next release of driver.

Thanks,
Amar
