### ISSUE TITLE
callproc sometimes returns a DBStatement object not a tuple as documented

### ISSUE THREAD

**Issue by dongryphon** [ibmdb/python-ibmdb#341]
This [branch](https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/ibm_db.c#L10710) returns a tuple if true but a Statement if false:

    if(numOfParam != 0 && tmp_curr != NULL) {
        int paramCount = 1;
        outTuple = PyTuple_New(numOfParam + 1);
        ...
    } else {
        outTuple = (PyObject *)stmt_res;
    }

Also, whatever tabsize you are using makes the code unreadable in GitHub viewer :o

**Comment by SabaKauser** [comment]
Hello Don,

When the call statement does not return anything(no parameters for example), only a statement object is returned. stmt object is used to retrieve the result set of SP and parameters retrieved as tuple.

e.g: stmt, par1, par2 = ibm_db.callproc(conn, 'proc_t', (par1, par2))  -> as tuple
stmt = ibm_db.callproc(conn, 'proc_a' ) --> does not take parameters.

Fixing indentation is pending work, I need to find some time to fix it :)

**Comment by kadler** [comment]
The equivalent could be done by return a tuple of 1, but then you'd have to change any code expecting just one result:

```python
# old code
stmt = ibm_db.callproc(conn, 'proc_a' )

# new code
(stmt,) = ibm_db.callproc(conn, 'proc_a' ) 
```

I suspect that at this point the only thing that can be done is to update the docs :slightly_frowning_face:

**Comment by kadler** [comment]
@SabaKauser as far as the white-space issues go, I have removed all tabs from the code in #315. The code could use a lot more cleanup than that, but it is certainly better than what we have currently. I just rebased the PR so it can now be applied cleanly.

**Comment by SabaKauser** [comment]
@kadler , Yes, I have that pending.

**Comment by SabaKauser** [comment]
I have updated the doc.
