### ISSUE TITLE
BooelanField (SMALLINT) returns integer not boolean

### ISSUE THREAD

**Issue by chsymann89** [ibmdb/python-ibmdb#349]
summary
------------
in the current Version (1.2.0.0) we are facing a problem with BooleanFields due to a bug/a missing feature in ibm-db-django. 
When you read a BooloeanField (through ORM) you receive an integer. 
Where as using ibm-db-django 1.0.7 we receive a boolean instead.

example
-----------
I created a small testscript to illustrate it:

SQL to create the database-field:
```
    CREATE TABLE "DB2_BOOLEANTEST" (
      "ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
      "TEST_FIELD" SMALLINT NOT NULL DEFAULT 1 ); 
    
    ALTER TABLE "DB2_BOOLEANTEST"
      ADD CONSTRAINT "SQL20042016104703" CHECK
        (TEST_FIELD IN (0,1))
      ENFORCED
      ENABLE QUERY OPTIMIZATION;
```

Django test-snippet 
```python
from django.db import models

class BooleanTest(models.Model):
    test_field = models.BooleanField(default=False)

bt_0 = BooleanTest.objects.create(test_field=0)
bt_false = BooleanTest.objects.create(test_field=False)
bt_1 = BooleanTest.objects.create(test_field=1)
bt_true = BooleanTest.objects.create(test_field=True)

print("Check memory-objects:")
print("written: 0, read: {}".format(bt_0.test_field))
print("written: False, read: {}".format(bt_false.test_field))
print("written: 1, read: {}".format(bt_1.test_field))
print("written: True, read: {}".format(bt_true.test_field))

# reload objects from db
bt_0 = BooleanTest.objects.get(id=bt_0.id)
bt_false = BooleanTest.objects.get(id=bt_false.id)
bt_1 = BooleanTest.objects.get(id=bt_1.id)
bt_true = BooleanTest.objects.get(id=bt_true.id)

print("\nCheck objects refreshed from database:")
print("written: 0, read: {}".format(bt_0.test_field))
print("written: False, read: {}".format(bt_false.test_field))
print("written: 1, read: {}".format(bt_1.test_field))
print("written: True, read: {}".format(bt_true.test_field))
```

Here are the different test-results for different test-environments:

```
test-environment
----------------
Django==1.11.13
ibm-db==2.0.8
ibm-db-django==1.2.0.0


script-output
-------------
Check memory-objects:
written: 0, read: 0
written: False, read: False
written: 1, read: 1
written: True, read: True

Check objects refreshed from database:
written: 0, read: 0  # <---- here we got an integer
written: False, read: 0  # <---- here we got an integer
written: 1, read: 1  # <---- here we got an integer
written: True, read: 1  # <---- here we got an integer

........................................................................................

test-environment
----------------
Django==1.6.7
ibm-db==2.0.7
ibm-db-django==1.0.7


script-output
-------------
Check memory-objects:
written: 0, read: 0
written: False, read: False
written: 1, read: 1
written: True, read: True

Check objects refreshed from database:
written: 0, read: False  # <---- here we got a boolean
written: False, read: False  # <---- here we got a boolean
written: 1, read: True  # <---- here we got a boolean
written: True, read: True  # <---- here we got a boolean
```

initial analysis
------------------
When I reviewed the latest changes, I identified this commit, which apparently removed the functionality of casting the database integers back to booleans.

https://github.com/ibmdb/python-ibmdb/commit/c6ca1ed5d168a36cc3c892b0669dbfe3faca27b9#diff-2ffd88dee5332bb4993d9745545ffd63

Interaction with Django
-----------------------------
We have become aware of this error because we use Django Model Forms. 
For the determination of a checked/unchecked checkbox BooleanFields are checked internally with the following method:

From Django==1.11.13 (django.forms.widgets.boolean_check)
```python
def boolean_check(v):
    return not (v is False or v is None or v == ''')
```

This returns True for both 0 and 1. Therefore the checkboxes are always checked. 

conclusion
-------------
Especially regarding the discrepancies with Django, I would consider this a bug. I have already worked on a pull request and would be very happy if you would accept it - it will follow tomorrow.

**Comment by hemlatabhatt** [comment]
@chsymann89 ,thanks for the information, i am looking into the issue.I am moving the issue to the correct repository.Please raise a pull request in the same i.e( https://github.com/ibmdb/python-ibmdb-django )

**Comment by hemlatabhatt** [comment]
This issue was moved to ibmdb/python-ibmdb-django#33

**Comment by kadler** [comment]
@hemlatabhatt This issue should be closed, since it was moved to the other repo

**Comment by SabaKauser** [comment]
@kadler , Hema is no more associated with this project. I am closing this.
