### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by kentcb** [ibmdb/python-ibmdb#352]
Hi,

Feeling pretty stupid here and looking for some help. I have a .NET Core DB2 client running on Linux that successfully connects and queries using the license file. But when I try and use the same with this Python library, I get:

```
Exception: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968 SQLCODE=-1598
```

Output of `db2level` is:

```
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11013" with level identifier "0204010F".
Informational tokens are "DB2 v11.1.3.3", "s1804271300", "DYN1804271300AMD64",
and Fix Pack "3a".
Product is installed at "/home/ec2-user/<<redacted>>/clidriver".
```

My license file includes this:

```
ProductVersion=11.1
```

I've also validated that my environment variables are set correctly:

```
[ec2-user@ip-192-168-12-158 bin]$ echo $IBM_DB_LIB
/home/ec2-user/<<redacted>>/clidriver/lib/
[ec2-user@ip-192-168-12-158 bin]$ echo $IBM_DB_DIR
/home/ec2-user/<<redacted>>/clidriver/
```

Any idea what I'm doing wrong?

**Comment by SabaKauser** [comment]
Hello Kent,
You would need to add the license under "/home/ec2-user/<<redacted>>/clidriver/license.

**Comment by kentcb** [comment]
@SadaKauser That's exactly where it is, though. Like I said, it works perfectly fine with the .NET Core DB2 drivers.

I thought maybe there was a second copy of the drivers being used, so I did a `sudo find / -name <<aDriverFile>>` to track down all copies. There was one under` /usr/local/lib/python2.7/site-packages/ibm_db-2.0.9-py2.7-linux-x86_64.egg/clidriver/`, so I copied a license under ` /usr/local/lib/python2.7/site-packages/ibm_db-2.0.9-py2.7-linux-x86_64.egg/clidriver/license` for good measure. Still didn't work and my environment variables suggest that copy of the drivers isn't being used anyway.

Any other ideas?

**Comment by SabaKauser** [comment]
Hello Kent,
While running, the library path is resolved from LD_LIBRARY_PATH. Hence you can add /home/ec2-user/<<redacted>>/clidriver/lib/ to library path.
Are you connecting to the same database from both .NET and ibm_db?

Please collect db2 traces -
cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files

**Comment by kentcb** [comment]
Ended up getting things working from .NET, so I no longer need the Python driver to work.
