### ISSUE TITLE
Replace IBM_DB/ibm_db/ibm_db.c with Python ctypes

### ISSUE THREAD

**Issue by sasa-tomic** [ibmdb/python-ibmdb#353]
People have so many issues with the usage of the ibm_db module in Python (e.g. https://github.com/ibmdb/python-ibmdb/blob/0468fb51a4f517dc44089cd701c2e514c8202f34/IBM_DB/ibm_db/README.md#issues-with-mac-os-x but some people on Linux also have issues).

The solution for most of these issues is easy: stop using a proprietary loader for the ibm_db*.so (or ibm_db*.dylib) and use the framework provided by Python: ctypes
https://docs.python.org/3/library/ctypes.html

The actual development effort shouldn't be too high, and as a bonus the installation of python-ibmdb will be easier and faster.

**Comment by amukherjee28** [comment]
With the latest release we are now at 3.0.4 and I guess this has been addressed.
@sasa-tomic can you please let me know if we can close this issue.

**Comment by sasa-tomic** [comment]
Seems to me that nothing changed with regard to using a proprietary loader for the `ibm_db*.so`, correct me if I'm wrong.
But that shouldn't stop you from closing the ticket. It's old enough and seems like no one is willing to work on really fixing it.
