### ISSUE TITLE
Setting enableRowsetSupport parameter

### ISSUE THREAD

**Issue by ramazanpolat** [ibmdb/python-ibmdb#356]
[enableRowsetSupport ](https://www.ibm.com/support/knowledgecenter/SSEPEK_11.0.0/java/src/tpc/imjcc_c0052058.html) (for Multi-row FETCH) is avaliable for JDBC and SQLJ.

Is there any way to set this parameter for Python driver.

**Comment by SabaKauser** [comment]
Hello,
Currently you can use execute_many API to insert multiple rows. However, array fetch is not supported.

**Comment by ramazanpolat** [comment]
Using DB2 with python has no advantage over any other databases, unless you use columnar tables(BLU). That only makes sense if tables have millions of rows(probably billions). BLU is already fast but SQL is not enough for a data sientist. We need to bring data to python in order to process. That needs being able to fetch millions of rows as fast as possible. Altohough it is possible to do it in JDBC and ODBC via Multi-row FETCH, Java and .NET languages are not really a good choice for data science. That's why we need multi-row fetch(or array fetch as you call it).

Without multi-row fetch, there is no point to use Python and DB2 together. I've already submitted a service request about this issue(#28568,001,862) but knowing that this is not supported(or implemented) in python driver makes me understand that service request won't help in this situation. The only way to use python and DB2 together is having this feature implemented. If so please let me know, otherwise we will need to move data from DB2 to other solutions.

**Comment by SabaKauser** [comment]
Hello Ramazan,
I am sorry to hear that your service request was not addressed. Unfortunately, the request did not reach us. Github is the recommended forum as the actual development happens through here.

I will evaluate your proposal and let you know the time frame when I will be able to deliver.

Thanks for bringing this up!

**Comment by ramazanpolat** [comment]
> Github is the recommended forum as the actual development happens through here.
That's why I brought this here :)

I appreciate your help. I can issue another SR and make sure the request reach to you if it helps.

**Comment by SabaKauser** [comment]
Hello Ramazan,
The array fetch is just client side functionality and does not reduce network trip to server as the data that is sent by server is always in blocks(query block size). Hence all the performance benefits that you might get would only be the time reduction in processing the data at client side.
Is this your expectation?

**Comment by ramazanpolat** [comment]
Hi,
What I'm looking for is described exactly here [DB2 Continuous block fetch](https://www.ibm.com/support/knowledgecenter/en/SSEPEK_10.0.0/perf/src/tpc/db2z_continuousblockfetch.html) and here [DB2 block fetch](https://www.ibm.com/support/knowledgecenter/SSEPEK_10.0.0/intro/src/tpc/db2z_blockfetch.html)

> You can use block fetch to retrieve a set of rows and transmit them all in one message over the network.
> 
> DB2® uses a block fetch to group the rows that an SQL query retrieves into as large a "block" of rows as can fit in a message buffer, and then transmits the block over the network. By sending multiple rows in a block, DB2 avoids sending a message for every row.

As fas as I understand, there are 2 ways to get multiple rows from server with one network trip and those are **Multi-row FETCH** and **Block-FETCH**. I don't know the difference between them tho.

I've used Multi-row-FETCH with **dbeaver** successfully when I used *enableRowsetSupport* parameter in JDBC driver. With *enableRowsetSupport* set, I can fetch rows realy really fast! Unfortunately same parameter doesn't exist in python drivers.

I hope this clarifies what my expectation is.

**Comment by amukherjee28** [comment]
@ramazanpolat 

With v11.5.4.0 and above the new keyword has been introduced into the IBM data server driver (NON java driver) to perform the similar operation that you have talked about in this case.

BlockForNRows is the keyword that can be used along with the db2cli.ini file or in db2dsdriver.cfg file or in connection string in order to control the Number of rows being fetched from the server in a single fetch request.

Here the documentation link https://www.ibm.com/docs/en/db2/11.5?topic=keywords-blockfornrows

We have the ibm_db default clidriver already updated to v11.5.5.0 which will have the feature implemented.

Please configure the above mentioned keyword in any of the three ways as mentioned above in order to control the Query Fetch.

Let me know if this works for you.

Thanks

**Comment by alexcocia** [comment]
Hi,

We have enabled the BlockForNRows in our ODBC DB2 driver, but found out that it only fetches one row per fetch - block, and the db2cli is not able to provide the full result.
For instance,.. in a 1000 rows query, with the BlockForNRows set to 100, it only returns 10 elements.
Any ideas on the usage of that param? Thanks in advance!
Alex



> @ramazanpolat
> 
> With v11.5.4.0 and above the new keyword has been introduced into the IBM data server driver (NON java driver) to perform the similar operation that you have talked about in this case.
> 
> BlockForNRows is the keyword that can be used along with the db2cli.ini file or in db2dsdriver.cfg file or in connection string in order to control the Number of rows being fetched from the server in a single fetch request.
> 
> Here the documentation link https://www.ibm.com/docs/en/db2/11.5?topic=keywords-blockfornrows
> 
> We have the ibm_db default clidriver already updated to v11.5.5.0 which will have the feature implemented.
> 
> Please configure the above mentioned keyword in any of the three ways as mentioned above in order to control the Query Fetch.
> 
> Let me know if this works for you.
> 
> Thanks

**Comment by bimalkjha** [comment]
@alexcocia If `BlockForNRows` is set, then server sends N rows to client on a fetch request over TCPIP. Client stores those results in a DRDA buffer. SQLFetch() is meant to return only one row at a time. SQLFetch() reads rows from DRDA buffer and returns to application. Client do not go on server to fetch next set of results until all rows from DRDA buffers have been read.
So, BlockForNRows keyword do not affect the behavior of SQLFetch(), but it affects how many rows are returned by Db2 server to Db2 client/driver on a driver request. It only affects the performance of the application not the behavior of SQLFetch(). i.e. [ibm_db.fetch_row](https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbfetch_row)  will always return single row either BLockForNRows is set or not. Check more info about BlockForNRows here: https://www.ibm.com/docs/en/db2/11.5?topic=keywords-blockfornrows
If you want more rows, you need to call fetch in a while loop or use `FETCH FIRST n ROWS ONLY` predicate in SQL to limit number of rows. Check https://github.com/ibmdb/python-ibmdb/blob/master/ibm_db_tests/test_154_AllFetches.py
Thanks.

**Comment by alexcocia** [comment]
Hi @bimalkjha!. Thanks for your response.
The fact is that we saw different number of rows responded from machines with the BlockForNRows parameter and without it. (For the same query, database, etc). Finally tested with the db2cli executeSql straight away, to discard problems with our code
`/usr/lib/db2/clidriver/bin/db2cli execsql -execute -connstring "UID=zzzzz;PWD=sssss;DATABASE=cccc;HOSTNAME=DB2HOST;PORT=6022" -inputsql ./db2_dev_qwyp.sql`

And found that, with BlockForNRows set to 150, it returned 
`FetchAll: 5 rows fetched.`
While for the server with no BlockForNRows set, it returned all 656 elements
`FetchAll: 656 rows fetched.
`
I have tcpdumped the network and seen that all elements in the response are provided to the db2cli, but it only returns 5 elements, which is the same result we have executing from our code.

Am I doing something wrong, or missing some other parameter?
King regards
Alex

**Comment by bimalkjha** [comment]
@alexcocia If FetchAll returns only 5 rows and not 150, then it might be bug with clidriver not with ibm_db. You should open a support case with IBM for clidriver.
If you have cliscript that shows this behavior, please share here. I would be interested to have a look into it. Thanks.

**Comment by bimalkjha** [comment]
[blockfornrows.txt](https://github.com/ibmdb/python-ibmdb/files/14051304/blockfornrows.txt)
@alexcocia Just update the database connection info in this file and path of db2cli.ini file, then execute it using `db2cli < blockfornrows.txt` command. You can see the BLOCKFORNROWS keyword in the connection string output of SQLDriverConnect API. Also, it returns all 100 rows to me despite blockfornrows value is 10.
```
  98, rocket, software
  99, rocket, software
  100, rocket, software
FetchAll: 100 rows fetched.
>
> sqlfreestmt 1 sql_close
```
So, I am not sure why you are getting only 5 rows instead of 656 rows by `FetchAll` api. Thanks.

**Comment by alexcocia** [comment]
> @alexcocia If FetchAll returns only 5 rows and not 656 rows, then it might be bug with clidriver not with ibm_db. You should open a support case with IBM for clidriver. If you can share your `db2_dev_qwyp.sql` script, please share here. I would be interested to have a look into it. Thanks.

It only contains a select clause... No configuration or any other change.
Checking clidriver. We might have to open a case with IBM

Just for completing the info, we have nothing in the db2cli.ini file, our config is stored in the db2dsdriver.cfg. Here is the databaseconfig part of it:

```
 <database name="ccccc" host="DB2HOST" port="6022">
        <parameter name="BlockForNRows" value="150"/> 
        <wlb>
            <parameter name="enableWLB" value="true"/>
            <parameter name="maxTransports" value="-1"/>
        </wlb>
      </database>
```

**Comment by alexcocia** [comment]
Hi Again!

Curious, but I used your blockForNRows file but removing the table creation and pointing to our database, and updating the number used for the BlockForNRows, it still provides different info.

```
writeini common BlockForNRows 1
opt echo on
opt callerror on
system "cat $DB2HOME/clidriver/cfg/db2cli.ini"
sqlallocenv 1
sqlallocconnect 1 1

sqldriverconnect 1 1 "UID=userid;PWD=passwd;DATABASE=database;HOSTNAME=hostname;PORT=6052" -3 255 sql_driver_noprompt
sqlallocstmt 1 1
sqlexecdirect 1 " SELECT DES_INFOALFA, COD_DATADIC FROM D337.TABLEQUERY WHERE COD_COUNTRY='ES' AND COD_ENTITY='0182' AND COD_PERSCON<='000001034' AND COD_PERSCON<='000002034'" -3
fetchall 1

sqlfreestmt 1 sql_close
sqltransact 1 1 sql_rollback
killenv 1
writeini common BlockForNRows
```

When using `BlockForNRows 1`, it returns 
```
  TIT, 6002
  TIT, 6002
  2                           , 6010
FetchAll: 945 rows fetched.
```

But using `BlockForNRows 100`, it returns 
```
  TIT, 6002
  2023-06-30     , 1058
  2                           , 6010
FetchAll: 10 rows fetched.
```

Have not found the solution yet, but will open the case to IBM

**Comment by bimalkjha** [comment]
@alexcocia I would suggest to collect db2traces for above cliscript with `BlockForNRows` value set to 100 that fetches only 10 rows for you. You can collect traces using below commands:
```
db2trc on -f 1.trc
db2cli < blockfornrows.txt
db2trc off
db2trc flw 1.trc 1.flw
db2trc fmt 1.trc 1.fmt
db2trc fmt -cli 1.trc 1.cli
```
Copy the complete output of above commands in a file. zip output file along with all generated 1.* files and share here.
I would also suggest to run below validate command from terminal and save complete output in a file and then add it too in the zip file and share here.
```
db2cli validate -database "dbname:hostname.com:port" -user userid -passwd xxxxx -connect
```
Update connection info in above validate command before running it. Thanks.

**Comment by alexcocia** [comment]
Hi again!.
I'll collect the traces.
Just to tell you that in my mac with the db2cli, I have tested your script and it returns correctly all 100 rows 
The problem might be in having  db2cli pointing to the DB2 for zOS. We are checking it.
Thanks a log

**Comment by alexcocia** [comment]
[TraceForNRows.tar.gz](https://github.com/ibmdb/python-ibmdb/files/14192271/TraceForNRows.tar.gz)

Here you can find the traces. Sorry for the delay....
I had to modify the files removing real hostnames, users, passwds... and so on. 
IBM support reported something about the former MultiFetch feature, but still have no answer for why it is not working with db2cli.

Thanks in advance
