### ISSUE TITLE
self._set_rowcount() in executemany function exception block causes original exception message not to be raised

### ISSUE THREAD

**Issue by gvenzl** [ibmdb/python-ibmdb#363]
If you execute a INSERT statement on a not existing table, [line 1399](https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/ibm_db_dbi.py#L1399) rightfully throws an exception.

Then when going into the exception block and executing `self._set_rowcount()` in [line 1411](https://github.com/ibmdb/python-ibmdb/blob/bd6670b0e0c4c7f1694e0c142fcd47b51df62275/IBM_DB/ibm_db/ibm_db_dbi.py#L1411) causes another exception to be thrown, in [line 1290](https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/ibm_db_dbi.py#L1290) which causes the original exception and error message to be swallowed and not be raised.

I'm not sure why `self._set_rowcount()` is even necessary when an exception occurs, in the first place. Seems like it's clear that an error occurred and that no rowcount can be reliably given.

**Comment by amukherjee28** [comment]
Hi @gvenzl 

Can we close this issue?

**Comment by amukherjee28** [comment]
Hi @gvenzl 

Since the attached issue with this case was closed, I have closed the issue.
Also this was an old issue and many other releases were made since then.

In case the issue still persists feel free to report a new issue.

**Comment by gvenzl** [comment]
Hi @amukherjee28,

The attached issue just mentioned this one but was about something unrelated.
If you read it, you will see.

Yes, the issue still exists, just try to insert in a non-existing table and see what error you get back there, not the one that one would expect.
I put in even the line numbers above where the problem is, sorry, not going to open a new issue instead this one should be reopened where the required analysis and information is already present.
