### ISSUE TITLE
Ensure macOS can find CLI libraries

### ISSUE THREAD

**Issue by kadler** [ibmdb/python-ibmdb#368]
There have been various issues opened related to not being able to load the require libdb2.dylib on macOS, especially when using the downloaded driver. See #276 #333 and possibly #366.

The answer has been: "use `install_name_tool` to fix the runtime load path", but this can and should be fixed rather easily in setup.py: https://stackoverflow.com/a/19147134

**Comment by SabaKauser** [comment]
I have the following that is working to resolve the lib path of clidriver on mac.
index 893b49a..4f6a4c2 100644
--- a/IBM_DB/ibm_db/setup.py
+++ b/IBM_DB/ibm_db/setup.py
@@ -268,3 +268,14 @@ setup( name    = PACKAGE,

 if license_agreement:
     sys.stdout.write(license_agreement)

+if('IBM_DB_HOME' not in os.environ):^M
+    sys.stdout.write("IBM_DB_HOME is not set. Run install_name_tool with")^M
+    os.system("install_name_tool -change libdb2.dylib @loader_path/clidriver/lib/libdb2.dylib build/lib.macosx-10.9-x86_64-3.7/ibm_db.cpython-37m-darwin.so")^M
+else:^M
+    sys.stdout.write("IBM_DB_HOME is set. Run install_name_tool with")^M
+    os.system("install_name_tool -change libdb2.dylib $IBM_DB_HOME/lib/libdb2.dylib build/lib.macosx-10.9-x86_64-3.7/ibm_db.cpython-37m-darwin.so")^M

However, I am finding difficulty in understanding how is name lib.macosx-10.9-x86_64-3.7 constructed. 
The machine where I have these changes has following:
**>>> platform.mac_ver()
('10.13.6', ('', '', ''), 'x86_64')
**
I don't know from where is 10.9 coming.

**Comment by SabaKauser** [comment]
ok. that's for building the driver manually using source. If I install via pip, I have the lib at @loader_path as ibm_db.cpython-37m-darwin.so.

**Comment by SabaKauser** [comment]
@kadler I have the fix for this problem available here.
https://github.com/SabaKauser/python-ibmdb/commit/39a8b4b3230b86d2c899f8fac9d579300692134f

Can you verify that install succeeds now.

**Comment by SabaKauser** [comment]
I have added your suggestion.
https://github.com/SabaKauser/python-ibmdb/commit/1de47f1d9ea70913515e08c8602d6b486ce443c3

**Comment by kadler** [comment]
@SabaKauser why not just make a pull request? Then I could comment on the PR instead of on the individual commits.

**Comment by kadler** [comment]
Other than than the odd tab comment, looks good. If it were me, I'd squash them before merging (or do it at merge time).

**Comment by SabaKauser** [comment]
Fixed in https://github.com/ibmdb/python-ibmdb/pull/377
