### ISSUE TITLE
Not able to call a Native SP with XML data type

### ISSUE THREAD

**Issue by nareshmanoharan** [ibmdb/python-ibmdb#369]
Hi
I have a Native Stored Proc on DB2 zOS that takes in a parameter of data type XML. It is defined as 'IN' parameter. When I try to invoke the stored procedure using ibm_db.callproc() , the python kernel in spyder IDE crashes. I tried with 'try/except' block, it is not entering the except block at all. For other stored procedures with non-XML (CHAR, VARCHAR, INT ) data types, the call is working fine and I am able to get results as expected. I am using a string variable to have the XML payload and using that string variable in the call statement. I also tried with str.encode() function but that also did not help. 

My code looks like this
planno = 12345
xmlpayload = '<xml>xmlvalue<xml>'
stmt,planno,xmlpayload = ibm_db.callproc(conn,'STOREDPROC',(planno,xmlpayload))

I browsed through the tests folder but couldn't find an example of calling a stored procedure with XML data type. Could it be because the string is not getting converted properly into a DB2 acceptable value for XML data types? 

In the c code, i found something called SQL_XML but not sure how I could use that to cast the string into XML data type. 

Any help is really appreciated

Regards
Naresh

**Comment by amukherjee28** [comment]
Hi @nareshmanoharan 

were you able to move forward with this issue. In case there is any progress please comment. We are currently in the version 3.0.4.

Thanks

**Comment by bimalkjha** [comment]
@nareshmanoharan Please confirm if you are still facing this issue using the latest version of ibm_db, else we would like to close it assuming issue no longer exist. Thanks.
