### ISSUE TITLE
ibm_db.callproc and typed-arrays

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb#370]
Can ibm_db.callproc API pass typed-arrays (from module array) as input arguments to SQLPL stored procedures with callproc?

For example: if I have a python array of integers like this:

`   somenumbers = array.array('I', [ 1000 , 200, 3 ] )`

and suppose a stored-procedure :

```
"create or replace type my_int_array as integer array[]; " .

"create or replace someprocedure (input somenumbers my_int_array )..."
```

the question is whether the below should work or not:

`ibm_db.callproc(ibm_db_conn, 'someprocedure', ( somenumbers ) )`

When I try it, the result is:

>  "Exception: Binding error 3" 

from callproc, on both python 2.7.12 and 3.5.3 with ibm_db 2.0.9.

**Comment by kadler** [comment]
The code currently doesn't support array parameters. [This](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/t0060938.html) doc has details about what would be needed to make it work.

**Comment by aratic** [comment]
same issue found, got clue from stackoverflow at https://stackoverflow.com/questions/54482787/call-db2-stored-proc-with-array-parameter-using-ibm-db-dbi-in-python

did thoughed about pass in typed array as @imavo , also failed, and up to the reply, the binding takes more effort than we thought

**Comment by amukherjee28** [comment]
@imavo can we close this?

**Comment by amukherjee28** [comment]
We have currently taken up the enhancement in order to support ARRAY in ibm_db driver.
Once the release with the changes are made this should be supported.

Currently _python_ibm_db_bind_data function does not handle ARRAY datatype passed into it throws error for array data, which is later handled as Bind Error 3 from the ibm_db.c code.

Once we support array this should be working condition when is bind_param can accept array inputs for various data types.

**Comment by praveen-db2** [comment]
@imavo array support is been addressed in latest version. We are not using pythons array module instead we are passing array of values in python list.

Below is commit for those changes, 
https://github.com/ibmdb/python-ibmdb/pull/698/commits/b9daa4746d5d6768756734fd0bb594cede9231d3

You can also refer sample test cases where we used list of values.
