### ISSUE TITLE
builtins.SystemError: <built-in function connect> returned NULL without setting an error

### ISSUE THREAD

**Issue by z06steve** [ibmdb/python-ibmdb#371]
This was working until this week and now get this error.  Windows 10, Python 3.5.4, ibm_db 2.0.9, DB2 v11.1.9.0

**Comment by SabaKauser** [comment]
this problem is not reproducible at will. I had provided a debug build as well earlier but it did not help. After few days, the issue disappeared. I know this sound strange, but that's what was seen earlier.

**Comment by SabaKauser** [comment]
Do you need any more assistance with this?

**Comment by celsken** [comment]
Hi, I also have Windows 10, Python 3.7.2,  and this code was working on Friday, but suddenly not working yesterday.
bss_conn1 = ibm_db_conn = ibm_db.connect(conn_string, "", "")
bss_conn = ibm_db_dbi.Connection(bss_conn1)

SystemError                               Traceback (most recent call last)
<ipython-input-35-2e78542aa74d> in <module>
----> 1 bss_conn1 = ibm_db_conn = ibm_db.connect(conn_string, "", "")
      2 print(bss_conn1)
      3 bss_conn = ibm_db_dbi.Connection(bss_conn1)

SystemError: <built-in function connect> returned NULL without setting an error

Any clues are appreciated!

**Comment by SabaKauser** [comment]
try running in cmd windows with admin privileges.

**Comment by celsken** [comment]
Thanks for the suggestion.  I tried it, but still getting that same error.

**Comment by pTyTb-git** [comment]
I'm facing the same issue on newly created env with python 3.7.6:
"<built-in function connect> returned NULL without setting an error"

- running in cmd windows with admin privileges - does not resolve it.

Has anybody figured out how to fix this issue? I did not find any solution in the Internet. 
Any ideas? Thx

**Comment by mudittripathi** [comment]
getting same issue in Pycharm terminal. However when I run with admin prev in cmd I get this

C:\Users\MuditTripathi\PycharmProjects\CoverageApi\API_UI_App>python test.py
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    conn = ibm_db.connect(database_connection, "", "")
 SQLCODE=-1013M][CLI Driver] SQL1013N  The database alias name or database name " " could not be found.  SQLSTATE=42705

**Comment by amukherjee28** [comment]
Hi,

The error being pointed out is because of the missing or invalid Alias name used in the application while connection with that of the name being used in the configuration/ini file in the driver.

There are few things that you might consider checking :
1. If you are using an alias name in the connection string then please check the name with that used in the db2dsdriver.cfg file or db2cli.ini file in the driver used.
2. In case your connection string is a full connection string then recheck for the values used in the string.

Thanks.
