### ISSUE TITLE
Need db.bind_multiple parameters

### ISSUE THREAD

**Issue by brettforbes** [ibmdb/python-ibmdb#379]
Hi,
I am an IBM business partner using ibm_db and ibm_dbi. they are pretty good libraries, even if the help info is hard to find (test files). However, your architecture leads to a serious problem in all but the toy scenarios you use in your tests.

The idea that you may want to load a lot of data, with only one or two parameters is poorly considered (i.e. the idea behind bind params and your test files is based on toy scenarios). Every single one of my tables is parameter based, so for example I must use 32 bind param statements in a row, just to fill out a single table. My next project will be even more intricate, which means a lot of unnecessary boilerplate, simply to use your library.

Surely, you could have a bind multiple params statement with a list or dict, or something, because the current approach really doesn't use python facilities properly.

Thanks
Brett
brett@cloudaccelerator.co

**Comment by kadler** [comment]
What's wrong with ibm_db_dbi? It does all that for you.

**Comment by amukherjee28** [comment]
hi @brettforbes 

Do you still have this issue. We have release version 3.0.4 now.

Let me know if this issue can be closed.

**Comment by causalmodeller** [comment]
hi, this issue can be closed, thanks

**Comment by amukherjee28** [comment]
Thanks @brettforbes.
