### ISSUE TITLE
Add tags for releases

### ISSUE THREAD

**Issue by kadler** [ibmdb/python-ibmdb#380]
Here's a list of all release commits since 1.0:
- 2.0.9 c6fe669b16185724c2d2c223abf9ca75fd32cb58
- 2.0.8 7c3d45b6692412fb30f3ab28b11bd7009218d8bb
- 2.0.7 7a0951a6825fa67bb365f936f4e7e3b4eb3cd4e0
- 2.0.6 6470f7d30dbf4723f5bf8225191cf19c765f2418
- 2.0.5.1 0d37f2ae26d75a374073b7b444305dc1c7dc00b5
- 2.0.5 afbe05cac81997cce86c4d8ec208dd8881c21d7f
- 2.0.4.1 38572b0298ffed55568047bf4d9b20a157ee9952
- 2.0.4 8c4b6c087157fe049e69a84080023c209db75ed1
- 2.0.3 39176b487d034f8b6453247f077ab52c6cec0179
- 2.0.2 8b82b757efbebbd1f2e2b5b08cc6d74a90ee6aae
- 2.0.1 ba5b76bf60a1c12c78c9f9c3e64d14896a99ed96
- 2.0.0 795c794ec520571a5b7a2521818d43ba8f4999c4
- 1.0.6 48a6184ddfa7930e892543638670f6861402f058
- 1.0.5 5e263976bdec3425635fc5e8d5ee1edadd35e9e8
- 1.0.4 9e5fe8c5a3a0bbcbdd2c787046fe10859bcc95f4
- 1.0.3 05802a008014cfeb7a569bfcf5bda675cf64624c
- 1.0.2 d18d257e8278c7fbdc5eb2db9803795f95b62e7a
- 1.0.1 3366930ade7a0eaff95ae8e01fa2d411a3517446
- 1.0    4ace24363623238e9985ed992e484d0fab346fa4

Found with
```sh
git log --format='%H  %s' -L24,24:IBM_DB/ibm_db/setup.py
```
example commands:
```
git tag 2.0.9   c6fe669b16185724c2d2c223abf9ca75fd32cb58
git tag 2.0.8   7c3d45b6692412fb30f3ab28b11bd7009218d8bb
git tag 2.0.7   7a0951a6825fa67bb365f936f4e7e3b4eb3cd4e0
git tag 2.0.6   6470f7d30dbf4723f5bf8225191cf19c765f2418
git tag 2.0.5.1 0d37f2ae26d75a374073b7b444305dc1c7dc00b5
git tag 2.0.5   afbe05cac81997cce86c4d8ec208dd8881c21d7f
git tag 2.0.4.1 38572b0298ffed55568047bf4d9b20a157ee9952
git tag 2.0.4   8c4b6c087157fe049e69a84080023c209db75ed1
git tag 2.0.3   39176b487d034f8b6453247f077ab52c6cec0179
git tag 2.0.2   8b82b757efbebbd1f2e2b5b08cc6d74a90ee6aae
git tag 2.0.1   ba5b76bf60a1c12c78c9f9c3e64d14896a99ed96
git tag 2.0.0   795c794ec520571a5b7a2521818d43ba8f4999c4
git tag 1.0.6   48a6184ddfa7930e892543638670f6861402f058
git tag 1.0.5   5e263976bdec3425635fc5e8d5ee1edadd35e9e8
git tag 1.0.4   9e5fe8c5a3a0bbcbdd2c787046fe10859bcc95f4
git tag 1.0.3   05802a008014cfeb7a569bfcf5bda675cf64624c
git tag 1.0.2   d18d257e8278c7fbdc5eb2db9803795f95b62e7a
git tag 1.0.1   3366930ade7a0eaff95ae8e01fa2d411a3517446
git tag 1.0     4ace24363623238e9985ed992e484d0fab346fa4

git push --tags
```

**Comment by SabaKauser** [comment]
Added all tags.
