### ISSUE TITLE
Wrong data types with ibm_db.fetch_assoc

### ISSUE THREAD

**Issue by WimCools** [ibmdb/python-ibmdb#387]
I'm using ibm_db 2.0.9 : 
ibm_db.fetch_assoc(statement)
ibm_db.field_type(statement, column)

The fetch_assoc returns a dictionary but columns of type date, decimal and integer are returned as python type str instead of date, decimal, int.
The field_type returns string for db2 date columns.
I need this data types for further formatting.
Is this a setting in the db2cli.ini  ?
How can I return Date and Decimals, floats ?

**Comment by SabaKauser** [comment]
Hello,
fetch_assoc returns a dictionary of column name and column value , it does not return the type.
ibm_db.field_type() is designed to return the type name as string. Having to return type defines would require you to interpret and map these values accordingly. For e.g: if I am returning DATE type as DATE, then your python program should have a way to interpret its value. Comparison is easier if we return string.

**Comment by WimCools** [comment]
I have upgraded ibm_db to 3.0.1.  The fetch_assoc returns a dict with the python types according to the DB2 types.
So my problem is solved.

**Comment by SabaKauser** [comment]
I have not changed anything related to types in 3.0.1 release. I would like to see the output of your test. Can you share it.

**Comment by WimCools** [comment]
This the debug output.
> /home/pomp/reports/db.py(102)fetchRow()
-> row = ibm_db.fetch_assoc(self.stmt)
(Pdb) n
> /home/pomp/reports/db.py(115)fetchRow()
-> return row
(Pdb) p row
{'SUPPLIER_INVOICE_NR': None, 'LEGAL_ENTITY_VAT_NR': None, 'STATUS': 'order', 'SUPPLIER_ID': 561412, 'DESTINATION_COUNTRY': 'SPAIN', 
'CUSTOMER_VAT_NR': 'ES A45401296', 'OLE_ID': 20105, 'DIRECT_DELIVERY': 'Y', 'INVOICE_DATE': None, 'VAT_AMOUNT': None,
 'PICKUP_ADDRESS_ID': 535024, 'CUSTOMER': 'SISTEMPUR, S.A.', 'CUSTOMER_ID': 714380, 'ORDER_CREATION_DATE': datetime.date(2019, 3, 19), 
 'VAT_CODE_IC': None, 'DESTINATION_ID': 740169, 'DEP_ADDRESS_CALL_SIGN': 'PORT VALENCIA', 'OUR_INVOICE_NR': None, 
 'VAT_CODE_PO': '21.000% VAT,SPAIN', 'OLE': 'RAVAGO CHEMICALS SPAIN', 'DATE': datetime.date(2019, 3, 30), 'PO_ORDER_NR': '6307303-01', 
 'DEST_ADDRESS_CALL_SIGN': 'SISTEMPUR, S.A.', 'PO_INCO_TERM': 'CFR', 'SUPPLIER': 'Ravago Chemicals Netherlands BV', 
 'DEPARTURE_COUNTRY': 'SPAIN', 'TOTAL_AMOUNT_W_O_VAT': None, 'CURRENCY': None, 'VAT_CODE_SO': '21.000% VAT,SPAIN', 
 'SO_ORDER_NR': '100041361-01', 'SO_INCO_TERM': 'DDP', 'DATE_INVOICE_CONTROL': None}
