### ISSUE TITLE
Boolean handling in execute_many

### ISSUE THREAD

**Issue by stfj77** [ibmdb/python-ibmdb#388]
I have a table with one column defined as DECIMAL(1,0), the corresponding value in python is of type bool.
When inserting records using execute_many I receive the following error the first time the value is set to True and previous values were set to False:

Error 1: Value parameters array 22 is not homogeneous with previous parameters array

Inserting the records using execute one by one works without problems.
Mapping the bool value in the script to 0/1 also solves the problem.

So somehow the handling of the bool datatype seems not to be correct on lower level.

**Comment by SabaKauser** [comment]
If there is a repro you can share, that would be helpful.

**Comment by stfj77** [comment]
I can only share the following code snippet where df is a pandas dataframe. If it contains a column of type boolean with multiple rows first having the value Fals,  followed by one or more with True, then these records with True values run into the error situation described above.

`
import ibm_db

def insert_dataframe(df, table_name, conn):
    rec_list = tuple([tuple(x) for x in df.replace({pd.np.nan: None}).to_numpy()])

    sql = "INSERT INTO " + table_name + "("
    sql += ",".join(df.columns)
    sql += ") VALUES ("
    sql += '?,' * len(df.columns)
    sql = sql[:-1]
    sql += ")"

    try:

        stmt = ibm_db.prepare(conn, sql)
        return ibm_db.execute_many(stmt, rec_list)

    except:
        log.error("Exception at insert operation" + ibm_db.stmt_errormsg())
        return None
`

**Comment by SabaKauser** [comment]
can you print rec_list and share the output

**Comment by stfj77** [comment]
(('R', None, '201903', False, 0, 18.0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0),
('R', None, '201903', False, 0, 18.0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0),
('R', None, '201903', False, 0, 18.0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0),
('R', None, '201903', True,  0, 18.0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0),
('R', None, '201903', True,  0, 18.0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0))


2019-04-09 10:54:38,491 : ERROR : Exception at insert operation error 
Error 1: Value parameters array 4 is not homogeneous with previous parameters array 

Error 2: Value parameters array 5 is not homogeneous with previous parameters array

**Comment by SabaKauser** [comment]
Thanks.
I have fixed this problem. I will post the fix to git and it will be available in next release.
