### ISSUE TITLE
IBM i support status

### ISSUE THREAD

**Issue by kskuhlman** [ibmdb/python-ibmdb#389]
Please document the state of IBM i support.   Is the IBMi branch being maintained?  Will it be merged at some point?   Is connecting from another platform to the i supported, or just local connections?

Querying a CCSID 37 table on a 7.2 IBM i using the official ibm_db 3.0.1 release from Windows results in the error below.  Expected due to lack of support?  Or bug?:

Traceback (most recent call last):
  File "C:\Programs\Python\Python37-32\lib\site-packages\ibm_db_dbi.py", line 1434, in _fetch_helper
    row = ibm_db.fetch_tuple(self.stmt_handler)
Exception: Column information cannot be retrieved: [IBM][CLI Driver][AS] SQL0332N  Character conversion from the source code page "937" to the target code page SQLCODE=-332 supported.

**Comment by SabaKauser** [comment]
ibmi branch is maintained by Kevin Adler. 
@kadler

**Comment by kadler** [comment]
I have no authority to push to the ibmi branch any longer, so I maintain the IBM i fork [here](https://github.com/kadler/python-ibmdb/tree/ibmi). This is the code we ship as part of the IBM i rpms. It is a longterm goal to merge this code upstream here, but the branches have diverged quite a bit at this point.

@kskuhlman As to the specific question, it appears you are using ibm_db on Windows, which would mean you are using the Db2 Connect (or similar) driver interface underneath which @SabaKauser and her team can help with more than I.

You say that you are querying a CCISD 37 table, but the message would indicate it's actually in 937 (Traditional Chinese EBCDIC). Are you sure the table is in 37? @SabaKauser, is there any way to load other conversion tables?

**Comment by kskuhlman** [comment]
Thanks for the replies.  Yes, I'm certain I'm using CCSID 37 throughout.    Here's session-level info showing the CCSID: 

```C:\>db2 connect to myDb user myId using 'myPwd'
   Database Connection Information

 Database server        = OS/400 7.2.0
 SQL authorization ID   = myId
 Local database alias   = MYDB

C:\>db2 "SELECT a.CHARACTER_IDENTIFIER_CONTROL USER_CCSID, b.CURRENT_NUMERIC_VAL
UE SYSTEM_CCSID FROM qsys2.user_info a, qsys2.SYSTEM_VALUE_INFO b WHERE a.AUTHOR
IZATION_NAME = session_user AND b.SYSTEM_VALUE_NAME = 'QCCSID'"

USER_CCSID SYSTEM_CCSID
---------- --------------------
*SYSVAL                      37

  1 record(s) selected.
```

And here's a Python session show the drop, recreate & query attempt:


```
C:\>python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit
(Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db_dbi as dbi
>>> print(dbi.__version__)
3.0.1
>>> conn = dbi.connect("DATABASE=myDB;HOSTNAME=myHost;PORT=446;PROTOCOL=TCPIP;UID=myID;PWD=myPwd;", "", "")
>>> c = conn.cursor()
>>> c.execute('drop table ibm_db_tst')
True
>>> conn.commit()
True
>>> c.execute('create table ibm_db_tst (col1 int)')
True
>>> c.execute('insert into ibm_db_tst values(2)')
True
>>> c.execute('select col1 from ibm_db_tst')
True
>>> print(c.fetchone())
Traceback (most recent call last):
  File "C:\Users\myID\AppData\Local\Programs\Python\Python37-32\lib\site-packa
ges\ibm_db_dbi.py", line 1434, in _fetch_helper
    row = ibm_db.fetch_tuple(self.stmt_handler)
Exception: Column information cannot be retrieved: [IBM][CLI Driver][AS] SQL0332
N  Character conversion from the source code page "937" to the target code page
 SQLCODE=-332 supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\myID\AppData\Local\Programs\Python\Python37-32\lib\site-packa
ges\ibm_db_dbi.py", line 1460, in fetchone
    row_list = self._fetch_helper(1)
  File "C:\Users\myID\AppData\Local\Programs\Python\Python37-32\lib\site-packa
ges\ibm_db_dbi.py", line 1441, in _fetch_helper
    raise self.messages[len(self.messages) - 1]
ibm_db_dbi.Error: ibm_db_dbi::Error: [IBM][CLI Driver][AS] SQL0332N  Character c
onversion from the source code page "937" to the target code page "1252" is not
 SQLCODE=-332
```

**Comment by kadler** [comment]
That's weird as the table doesn't even have any character data in it. Could be the job CCSID - can you find that?

**Comment by kskuhlman** [comment]
That's what I was showing in the first part of the last update.   The system ccsid is 37 and the user profile doesn't override it so sessions are 37.

I was trying to stay in SQL to be friendly to non-specialists, but just for completeness here's the info from DSPJOB on the Db2 Connect session shown earlier: 
```
                      Display Job Definition Attributes                        
                                                            System:   MYHOST    
Job:   QRWTSRVR       User:   QUSER          Number:   986708                  
...                                                                               
Device recovery action  . . . . . . . . . . . . . :   *MSG                     
Time slice end pool . . . . . . . . . . . . . . . :   *NONE                    
Print key format  . . . . . . . . . . . . . . . . :   *NONE                    
Sort sequence . . . . . . . . . . . . . . . . . . :   *HEX                     
  Library . . . . . . . . . . . . . . . . . . . . :                            
Language identifier . . . . . . . . . . . . . . . :   ENU                      
Country or region identifier  . . . . . . . . . . :   US                       
Coded character set identifier  . . . . . . . . . :   37                       
Default coded character set identifier  . . . . . :   37                       
...
```

**Comment by kadler** [comment]
@kskuhlman Sorry, I glossed right over that. It does look like everything should be 37. Hopefully Saba can find something in the traces.

**Comment by SabaKauser** [comment]
@kskuhlman do you any assistance on this?

**Comment by kskuhlman** [comment]
I have the traces.. is there a secure place I can upload them?  (Since they have confidential data)

**Comment by SabaKauser** [comment]
I think traces are not required.
You earlier had client with 1252 code page and at server it is 937.
From Db2 LUW infocenter, I can see this:
937 is in group D-2(D is double byte group).
1252 is single byte codepage in group S-1.(S is single byte)
Conversion between different groups is not allowed unless its group 'N' and hence you got the error.
Since 1208 is N-1 i.e Neutral,  the connection and conversion with any other code page listed is allowed.

**Comment by kadler** [comment]
@SabaKauser can you link to that documentation?

**Comment by kskuhlman** [comment]
The codepage for the IBM i database is 37, not 937.  

Also note that 37 is pervasive in the IBMi community, so I would expect this to be a common issue.

**Comment by SabaKauser** [comment]
The link to documentation is : https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.admin.nls.doc/doc/r0004565.html

Same is applicable for 37  as it is single bye code page.

**Comment by kskuhlman** [comment]
Sorry, I'm not following.. what I'm seeing is that 937 might be an issue because it's DBCS & my laptop is using a SBCS.  But 37 is also SBCS so what's the connection?

Also, how does what we've discovered help us get closer to a PR?

**Comment by SabaKauser** [comment]
Db2 client drivers support conversions as per the table I shared the link for. 
937 is DBCS and as per the table, it belongs to group D-2(the grouping is to identify which other codepages are valid for conversion and hence, any code-page in group D-2 can be converted to and fro). Likewise, the N-*, N is neutral and code page conversion to and from any other group to any code-page in N group is valid.
Since 937 is D-2 and 1252 is S-1, you see these are different groups and there is no conversion defined for this combination.
However, since 1208 is N-1, 937 <->1208 conversion is valid.
My understanding is that the problem you are facing is with CP 937 and 1252 and that changing codepage to 1208 resolved the problem for you. From the error you posted earlier:
'''ibm_db_dbi.Error: ibm_db_dbi::Error: [IBM][CLI Driver][AS] SQL0332N  Character c
onversion from the **source code page "937" to the target code page "1252"** is not'''

**Comment by kskuhlman** [comment]
Thanks for the reply.  Please read the earlier notes in this issue where we established that it's 37, not 937 as reported by the error text.

**Comment by SabaKauser** [comment]
As per the error message, Db2 ODBC driver is attempting conversion from CP 937 to CP 1252. 
If its 37 codepage, I need to check traces to confirm the codepage returned by server for client connection response and for the select statement.
you can mail traces to : skauser@rocketsoftware.com

**Comment by sgonchigar** [comment]
Is there way to changing the naming convention. where if you don't qualify the schema name, it will pick up from the library list.  in SQL we would set that by using 
sql set option commit=*none, **naming = *SYS,** datfmt=*ISO,timfmt=*ISO, dlyprp=*YES;

**Comment by kadler** [comment]
If you're running _on_ IBM i, the version we ship has that support. I wrote a blog post about it: https://kadler.github.io/2018/09/28/using-system-naming-in-ibm_db.html

**Comment by sgonchigar** [comment]
Thank you!. Would that work if Jupyter Notebook is running on Windows and connected to IBM i using db2 connect? I get error indicating those properties are not defined.

**Comment by kadler** [comment]
No, the code changes that we've made to support them have not been submitted here yet, just in our fork. Of course, Db2 Connect supports those attributes (though they may have different names) so it could be done.

**Comment by amukherjee28** [comment]
Hi @kskuhlman 

Can we close this issue. The resolution was provided as I see.

**Comment by sgonchigar** [comment]
Yes please.

With regards,
Sunil Gonchigar



________________________________
