### ISSUE TITLE
Python ibm_db can't do simple select query

### ISSUE THREAD

**Issue by timswiley** [ibmdb/python-ibmdb#390]
Env: Python 3.7 64bit  Windows Server 2012, DB2 ver 11.1.2,  ibm_db module ver 3.0.1

Issue: ibm_db isn't working pyodbc works fine

Code:
```
   oCon = ibm_db.connect(ConnectString)
   if oCon:
      sSQL = 'Select 1 as X From SYSIBM.SYSDUMMY1'
      oStmt = ibm_db.exec_immediate(oCon,sSQL)   #  Offending line
      print('Yee haw! Finally made it to this line') 
```
The offending line just exits the program immediately like nothing happened without raising an exception. Also i've seen other people report the other issue of after installing and importing the ibm_db about continuous pylint warnings 'ibm_db' has no 'connect' member yet it executes the connect method. Someone may ask why not just use pyodbc. I need to fetch blob/clob columns from DB2 and pyodbc indicates it/the ibm odbc driver does not support those data types yet.

**Comment by SabaKauser** [comment]
@timswiley ,
I need you to collect traces and share with me to understand the problem you are facing.
The statement you are executing should return the result set without any problem. Even in case of errors, ibm_db returns appropriate error message.
Like in my example:
C:\Users\skauser\Python_samples>python fetch_tuple.py

```
import ibm_db

oCon=ibm_db.connect("database=testpy;hostname=x.x.x.x;port=50000;uid=username;pwd=passwd;protocol=tcpip",'','')
if oCon:
    sSQL = 'Select 1 as X From SYSIBM.SYSDUMMY1'
    oStmt = ibm_db.exec_immediate(oCon,sSQL)
    result = ibm_db.fetch_tuple(oStmt)
    while(result):
        print("{}".format(result[0]), end="\n")
        result = ibm_db.fetch_tuple(oStmt)
```
success:
C:\Users\skauser\Python_samples>python fetch_tuple.py
1

Error cases:
Traceback (most recent call last):
  File "fetch_tuple.py", line 6, in <module>
    oStmt = ibm_db.exec_immediate(oCon,sSQL)
 SQLCODE=-204BM][CLI Driver][DB2/NT64] SQL0204N  "SYSIBM1.SYSDUMMY1" is an undefined name.  SQLSTATE=42704

C:\Users\skauser\Python_samples>python fetch_tuple.py
Traceback (most recent call last):
  File "fetch_tuple.py", line 6, in <module>
    oStmt = ibm_db.exec_immediate(oCon,sSQL)
Exception: [IBM][CLI Driver][DB2/NT64] SQL0104N  An unexpected token "SYSIBM" was found following "Select 1 as  From ".  Expected tokens may include:  "FROM".  SQLSTATE=426 SQLCODE=-104

Can you collect traces as :
cd <site-packages-path>/clidriver/bin
db2trc on -f trc.dmp
<run your application>
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli

And share the trc.flw, trc.fmt, trc.fmtc and trc.cli files.

**Comment by SabaKauser** [comment]
awaiting traces.

**Comment by timswiley** [comment]
Sorry for the delay.  I had no idea how fast a response would be.  Thank you!   Ok so the issue only occurs when using the connect method on a  "Cataloged" database where i only have to pass the database name, user, pwd as the parameters.   I tried this first and then i tried the full connect string... except i did not have the ,'','' at the end of the string and it yielded the same exact behavior as the cataloged database connect method.  Which was it returned true but just exited on that offending line.   I can now connect using the long form connect string with the ,'','').

**Comment by SabaKauser** [comment]
Thanks.
Can you post the exact usage of the API that gave the error. Of course with the mask on confidential data as necessary along with traces. traces would capture the db2 CLI processing, but I would also like to see the exact usecase from python ibm_db as well.

**Comment by SabaKauser** [comment]
closing. re-open as required.
