### ISSUE TITLE
execute_many returns only a single row for select statement

### ISSUE THREAD

**Issue by sebastian-hick** [ibmdb/python-ibmdb#392]
Dear Team.

Thanks for providing the Python DB2 API!

**[Question]**

I can execute a select query with parameter markers using the execute_many function. Query execution doesn't throw any exception, but returns only a single row, whereas I would expect several rows.
Is this correct?

**[Details]**

Query

```python
SQL_ORDER_DATA = (
    select
         /***************/
         /* ORDER DATA */
         /***************/
           por.ordernr
         , por.prodart
      from npt.vnppor por
     where 1=1
       and por.ordernr = ?
       and por.prodart = ?
    with ur;
)
```

Code

```python
def testExecuteMany():
    myDbConnection = setupDbConnection()
    sql = SQL_ORDER_DATA
    try:
        preparedStatement = ibm_db.prepare(myDbConnection, sql)
    except Exception as e:
        myLogger.error('Exception caught: %s', e)
    parameters = (('0003256', '1'), ('0003257', '1'))
    myLogger.info('parameters : %s', parameters)
    try:
        ibm_db.execute_many(preparedStatement, parameters)
    except Exception as e:
        myLogger.error('Exception caught: %s', e)
        
    result = []
    howManyRowsRetrieved = 0
    try:
        queryResultRow = ibm_db.fetch_assoc(preparedStatement)
        while(queryResultRow):
            howManyRowsRetrieved += 1
            result.append(queryResultRow)
            queryResultRow = ibm_db.fetch_assoc(preparedStatement)
    except Exception as e:
        myLogger.error('Exception caught: %s', e)
        assert False, 'Query result retrieval failed.'
    myLogger.debug('%d rows retrieved.', howManyRowsRetrieved)
    myLogger.info('result = %s', result)
    disconnectFromDb(myDbConnection)
    return 0
```

Logs

```
pydev debugger: starting (pid: 8680)
2019-04-23 09:27:49,639 - ERROR - START
2019-04-23 09:28:07,740 - INFO - parameters : (('0003256', '1'), ('0003257', '1'))
2019-04-23 09:28:25,593 - INFO - result = [{'ORDERNR': '0003256', 'PRODART': '1'}]
2019-04-23 09:28:33,821 - ERROR - STOP
```

The parameter tuple `parameters` contains **two** tuples - but `fetch_assoc` only retrieves a single row!

Any help would be greatly appreciated!

Thanks and kind regards.

Sebastian

**Comment by SabaKauser** [comment]
Hello Sebastian,
execute_many() is supported only for insert/update/delete.

**Comment by sebastian-hick** [comment]
Hello Saba.

Thanks for Your reply.

:( I read it in the docs, but as the bind operation didn't throw an error message, I thought I better ask.

Are there any plans to enhance the API in order to support multi-row fetches like the above?

Thanks

Sebastian

**Comment by SabaKauser** [comment]
Hello Sebastian,
Currently both server and client does not support this operation. This would be a feature request. I will discuss and get back to you.
By client, I mean Db2 ODBC client and not ibm_db.

**Comment by sebastian-hick** [comment]
Hi Saba.

Thanks. Looking forward to hearing Your discussion results.

I could imagine that OR mappers would benefit from implementing this feature.

**Comment by SabaKauser** [comment]
Sebastian,
would it be possible for you to provide more details on the requirement. 
I will take it forward for discussion and I will be asked for usecases.

**Comment by sebastian-hick** [comment]
Saba,
to my knowledge and experience, OO software systems are typically implemented using an OR mapper in combination with a technical DB key for each business entity. 
If You have to access mutliple objects at once, from a performance point of view it is very slow to issue a single point query for each object. It is much faster, if multiple objects could be retrieved by issuing a single DB call.
This could be done by creating a corresponding dynamic SQL statement with a suitable in clause for example. But that's a solution at the SQL level and thus not so easy to implement.
In my opinion, it would be much more elegant to enhance the ibm_db API  as described above; then, a single stable interface for point / multi-point / range queries would exist.
Does my explanation make sense?
Thanks for Your reply.
Sebastian

**Comment by SabaKauser** [comment]
Thanks Sebastian.

**Comment by amukherjee28** [comment]
Hi @sebastian-hick 

Were you able to move forward with this? Can this issue be closed?

**Comment by amukherjee28** [comment]
@sebastian-hick 
As stated earlier execute_many was created with the aim of supporting insert/update/delete operations and not for select.
For fetching rows there are multiple options available.

Also When I try running the sample code that you provided (my changing the table structure in my own way) I am not able to run the code and get exception before the fetch_assoc statement is reached.

Can you check once if the logic being tried here is the correct approach.

SAMPLE CODE
```
import ibm_db

print("IBM_DB_VERSION : " + str(ibm_db.__version__))
print("=> Creating Connection")

conn = ibm_db.connect(CONNECTION_STRING,"","")

sql = "select C1,C2 from execute_many_example where C1=? and C2=?"
try:
    prepare = ibm_db.prepare(conn,sql)
except:
    print("Error in prepare")
    
parameters = ((1,'arnab'),(1,'rahul'))
print(parameters)

try:
    ibm_db.execute_many(prepare,parameters)
except:
    print("error in execute many")
    
result = []
howManyRowsRetrieved = 0
try:
    queryResultRow = ibm_db.fetch_assoc(prepare)
    while(queryResultRow):
        howManyRowsRetrieved += 1
        result.append(queryResultRow)
        queryResultRow = ibm_db.fetch_assoc(prepare)
except Exception as e:
    print('Exception caught: %s', e)
print('%d rows retrieved.', howManyRowsRetrieved)
print('result = %s', result)
```

TABLE STRUCTURE 
```
=> Fetching data
C1|C2
1|arnab|
1|rahul|
1|basu|
4|urvi|
1|arnab|
1|rahul|
1|basu|
4|urvi|
1|arnab|
1|rahul|
1|basu|
4|urvi|
```

OUTPUT
```
IBM_DB_VERSION : 3.1.1
=> Creating Connection
((1, 'arnab'), (1, 'rahul'))
error in execute many
Exception caught: %s Fetch Failure: [IBM][CLI Driver] CLI0125E  Function sequence error. SQLSTATE=HY010 SQLCODE=-99999
%d rows retrieved. 0
result = %s []
```

Please let me know your opinion on this.

Thanks

**Comment by amukherjee28** [comment]
Closing this issue for now. Please open a new issue if you think the issues persists after testing with the latest version.
