### ISSUE TITLE
move repos to github.com/IBM?

### ISSUE THREAD

**Issue by stevemart** [ibmdb/python-ibmdb#394]
Hi there, I'm an admin for github.com/IBM and am happy to help you move the repos here http://github.com/ibmdb over to github.com/IBM and set up a team that can maintain them. If we do it correctly, we'll redirects will happen automatically.

Let me know if you're interested!

**Comment by SabaKauser** [comment]
Hello Steve,
Could you please email more details on why you think this can be moved to github.com/IBM. Please provide more background on this. You can reach me out at skauser@rocketsoftware.com.

**Comment by stevemart** [comment]
Will do!
