### ISSUE TITLE
cursor.rowcount is wrong on IBM i

### ISSUE THREAD

**Issue by jkyeung** [ibmdb/python-ibmdb#398]
As mentioned by @kadler in #389, the RPMs for IBM i are built from a [fork](https://github.com/kadler/python-ibmdb/tree/ibmi) he maintains. However, issues are disabled there, so I'm reporting this here.

After updating some rows using cursor.execute, cursor.rowcount is not set to the actual number of affected rows, but rather `(actual_rows + 1) * 2**32 - 1`. I imagine this is due to some mix-up with respect to integer size in the C implementation.

**Comment by SabaKauser** [comment]
@jkyeung , I can see correct rows in rowcount for my connection. 
How many number of rows did you update

**Comment by jkyeung** [comment]
I tested with various numbers of rows, from just a single row, to several thousand rows. In all cases, the number given by `rowcount` was exactly the expression I gave above.

**Comment by SabaKauser** [comment]
which driver interface are you using with ibm_db. Is it db2 LUWs db2 clidriver or using PASE CLI(libdb400.*). My result is with db2 LUW clidriver(on linux) against IBM i.

**Comment by jkyeung** [comment]
PASE. That is why I was talking about Kevin Adler's fork.

**Comment by SabaKauser** [comment]
@kadler you might want to take a look.

**Comment by kadler** [comment]
@jkyeung I've enabled issues on my fork. Can you please open an issue there?

**Comment by jkyeung** [comment]
> @jkyeung I've enabled issues on my fork. Can you please open an issue there?

OK, issue created.

**Comment by kadler** [comment]
Issue is https://github.com/kadler/python-ibmdb/issues/3
