### ISSUE TITLE
Unable to import ibm_db library

### ISSUE THREAD

**Issue by dapper-hacker** [ibmdb/python-ibmdb#399]
Hi, I am trying to setup a new project to use python library for IBM Db2 Cloud. However when i try to import ibm_db either from python shell or jupyter notebook, I get this error. 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/7928115/58233673-8c0aee80-7cf1-11e9-888f-66bb76b0e367.png">

There are some workarounds on internet but why is a workaround required?
https://github.com/ibmdb/python-ibmdb/issues/276

**Comment by SabaKauser** [comment]
Hello Vinayak,
Can you try this:
pip uninstall ibm_db
pip install --no-cache-dir ibm_db

**Comment by RohitUttam** [comment]
> Hello Vinayak,
> Can you try this:
> pip uninstall ibm_db
> pip install --no-cache-dir ibm_db

It worked for me!

**Comment by SonicChris** [comment]
I try to switch 3.0.1 to 3.0.0  then it works ok！

**Comment by nearodney** [comment]
Appreciate the suggestion @SabaKauser but this still does not work. Even after Darwin reinstallation of the ibm_db version 3.0.1, and bypassing the pip cache, produces a non-working library. The original issue #276 remains open, despite repeated closure, because the workaround DOES NOT work. There has been no improvement on this issue using pip on the Darwin platform. 
Developer responses and workaround STILL produce an invalid setup on High Sierra (10.13). Invoking python directly via python3.7, python3.6, as well as within anaconda3 envs that use 3.7 all result in the same error output shown by @dapper-hacker.

**Comment by SabaKauser** [comment]
Hello Rodney,
If you see  setup.py line 59, I am using get_python_lib() to locate the site-packages and run install_name_tool on the ibm_db*.so to change the odbc library name for correct path resolution.
However, the get_python_lib() seem to behave strange and return incorrect paths for site-packages. 
I have raised bug in distutils and have not heard from any experts.
for e.g: using anaconda, it returns this path : c:\users\skauser\anaconda\lib\site-packages\users\skauser\anaconda\lib\site-packages
when the expected behavior is to only see c:\users\skauser\anaconda\lib\site-packages. The behavior of get_python_lib() seem to depend on something that I am unaware and I need to hear from experts.

**Comment by rajarshi-d** [comment]
The following command worked for me when I tried to execute the program from my terminal(but failed in PyCharm):
export DYLD_LIBRARY_PATH=/anaconda3/lib/python3.7/site-packages/clidriver/lib:$DYLD_LIBRARY_PATH

For PyCharm, the following needs to be added to the environment variable under Run -> Edit Configurations... 
DYLD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/clidriver/lib:$DYLD_LIBRARY_PATH

**Comment by deeraj2527** [comment]
![image](https://user-images.githubusercontent.com/84575156/199654546-6bff8ede-593e-47f9-88e4-c52cd5f44ea7.png)


i am gettiing this kind of error please help me

**Comment by deeraj2527** [comment]
![image](https://user-images.githubusercontent.com/84575156/199654728-3be494dc-bfae-48c6-ba63-73e7b5f274e7.png)

**Comment by yash4510** [comment]
**I cant install the ibm_db package**
Collecting ibm-db
  Using cached ibm_db-3.1.3.tar.gz (1.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\hp\appdata\local\programs\python\python38\python.exe' 'c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\HP\AppData\Local\Temp\tmpuz1o5hhi'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-install-85cgc500\ibm-db
    Complete output (30 lines):
    Detected 64-bit Python
    Detected platform = win32
    running dist_info
    creating C:\Users\HP\AppData\Local\Temp\pip-modern-metadata-3aqb3nke\ibm_db.egg-info
    writing C:\Users\HP\AppData\Local\Temp\pip-modern-metadata-3aqb3nke\ibm_db.egg-info\PKG-INFO
    writing dependency_links to C:\Users\HP\AppData\Local\Temp\pip-modern-metadata-3aqb3nke\ibm_db.egg-info\dependency_links.txt
    writing top-level names to C:\Users\HP\AppData\Local\Temp\pip-modern-metadata-3aqb3nke\ibm_db.egg-info\top_level.txt
    writing manifest file 'C:\Users\HP\AppData\Local\Temp\pip-modern-metadata-3aqb3nke\ibm_db.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\HP\AppData\Local\Temp\pip-modern-metadata-3aqb3nke\ibm_db.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'config.py'
    adding license file 'LICENSE'
    writing manifest file 'C:\Users\HP\AppData\Local\Temp\pip-modern-metadata-3aqb3nke\ibm_db.egg-info\SOURCES.txt'
    creating 'C:\Users\HP\AppData\Local\Temp\pip-modern-metadata-3aqb3nke\ibm_db-3.1.3.dist-info'

    ****************************************
    You are downloading a package which includes the Python module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the python module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in c:\users\hp\appdata\local\programs\python\python38\Lib\site-packages\clidriver or c:\users\hp\appdata\local\programs\python\python38\Lib\site-packages\ibm_db-3.1.3-py3.8.egg\clidriver.   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
    ****************************************
    OSError: [Errno 9] Bad file descriptor

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 276, in main
        write_json(json_out, pjoin(control_dir, 'output.json'), indent=2)
      File "c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 35, in write_json
        json.dump(obj, f, **kwargs)
    OSError: [Errno 9] Bad file descriptor
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\hp\appdata\local\programs\python\python38\python.exe' 'c:\users\hp\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\HP\AppData\Local\Temp\tmpuz1o5hhi' Check the logs for full command output.

![Uploading image.png…]
