### ISSUE TITLE
import ibm_db throws error

### ISSUE THREAD

**Issue by vibkulkarni** [ibmdb/python-ibmdb#400]
root@95ad77fa75a9:/# pip install --no-cache-dir ibm_db
Collecting ibm_db
  Downloading https://files.pythonhosted.org/packages/98/cb/f77d9bd5f64246074af364cc30e20e3044c533890f3b67d30e89615c2fc5/ibm_db-3.0.1.tar.gz (642kB)
    100% |################################| 645kB 2.0MB/s 
Installing collected packages: ibm-db
  Running setup.py install for ibm-db ... done
Successfully installed ibm-db-3.0.1

root@95ad77fa75a9:/# 
root@95ad77fa75a9:/# python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libibmc++.so.1: cannot open shared object file: No such file or directory
>>>

**Comment by SabaKauser** [comment]
db2 clidriver on Linux on power requires libibmc++.so.1.
You need to set the LD_LIBRARY_PATH to lib location on your machine.
