### ISSUE TITLE
EXECUTE_MANY with MULTI SESSION Issues

### ISSUE THREAD

**Issue by mrrameshch** [ibmdb/python-ibmdb#401]
I am trying to execute EXECUTE_MANY method with multi session and that is giving issues as below

**"[IBM][CLI Driver] SQL0902C  A system error occurred. Subsequent SQL statements cannot be processed. IBM software support reason code: "".  SQLSTATE=58005 SQLCODE=-902"**

If I run with single session it is working fine. To achieve parallelism, I want to run the function that is using EXECUTE_MANY with multiple processes in parallel.

As per DBA, we have latest version of Database and no issues on DataBase side.

Here is the code:-
import ibm_db
import ibm_db_dbi
import multiprocessing

def InsertTuple(con, Tuple1, stmt_insert):
  stmt_insert=idb.prepare(con, sql)
  idb.execute_many(stmt_insert,Tuple1)

p1=Process(target=self.InsertTuple,args=(con,Tuple1,sqlfle))
p2=Process(target=self.InsertTuple,args=(con,Tuple2,sqlfle))
p1.start()
p2.start()
p1.join()
p2.join()

Can any one please suggest how to execute EXECUTE_MANY in parallel sessions??

**Comment by paul-lilley** [comment]
Hi, I think you need each process to open its own connection to the database rather than sharing a single connection (and trust that the underlying drivers deal with connection pooling).  
I have a working parallel insert - I'll simplify the code and post an example

**Comment by paul-lilley** [comment]
`import ibm_db_dbi
import multiprocessing as mp
import logging
import pandas as pd
import sqlalchemy
import datetime
import math

from xxxxxxxxxxxxxxxxxxxx import get_ibmdb_DB2connectionString
from xxxxxxxxxxxxxxxxxxxx import get_credentials_from_netrc


def ibmdb_dbi_insert(con_str: str, sql: str, tuple_of_tuples: tuple) -> bool:
    # use ibmdb_dbi - more pythonic wrapper for ibm_db
    # ibm_db_dbi does not natively support context manager (with ... as)
    try:
        con = ibm_db_dbi.pconnect(con_str, '', '', conn_options=
        {ibm_db_dbi.SQL_ATTR_AUTOCOMMIT:
             ibm_db_dbi.SQL_AUTOCOMMIT_OFF})
    except ibm_db_dbi.Error as e:
        logging.error('Failed to connect to db2 with ibmdb_dbi, no rows '
                      'inserted')
        logging.error(e)
        return False

    cur = con.cursor()

    try:
        # ibm_db_dbi prepares the statement for us
        cur.executemany(sql, tuple_of_tuples)
        con.commit()
        return True
    except ibm_db_dbi.Error as e:
        # automatic rollback as we use autocommit_off above
        logging.error(f'Failed to bulk insert {len(tuple_of_tuples)} rows '
                      f'to db2 with ibmdb_dbi')
        logging.error(e)
        return False
    finally:
        con.close()


if __name__ == '__main__':

    logging.getLogger().setLevel(logging.DEBUG)

    database = 'IVHP02'
    schema = 'APP'
    table_name = 'zap'

    # how many rows should each parallel insert take
    n_rows_per_process = 15  # 20000 seems ideal for our real systems

    # some dummy data
    df = pd.DataFrame([{'col1': x, 'col2': x + 1} for x in range(39)])

    # ensure the table exists, or create it - here I just use sqlalchemy
    username, account, password = \
        get_credentials_from_netrc()  # internal convenience function
    engine = sqlalchemy.create_engine(
        f'ibm_db_sa://{username}:{password}@/{database}')
    # Create Table structure with sqlalchemy
    df[:0].to_sql(name=table_name, schema=schema, con=engine,
                  if_exists='replace', index=False)
    engine.dispose()

    # define your connection string
    con_str = get_ibmdb_DB2connectionString(
        database=database) # internal convenience function

    # build the sql string for the insert
    num_cols = len(df.columns)
    cols = ','.join(list(df.columns))
    qmarks = '?' * num_cols
    placeholders = ','.join([qmarks[i] for i in range(num_cols)])
    sql = f'INSERT INTO {schema}.{table_name} ({cols}) ' \
        f'VALUES ({placeholders})'

    # convert our dummy data to a tuple of tuples
    tuple_of_tuples = tuple(df.itertuples(index=False, name=None))

    # function to split the data into chunks,
    def _chunker(seq, size):
        return (seq[pos:pos + size] for pos in range(0, len(seq), size))

    n_rows = len(tuple_of_tuples)
    threads = []
    logging.debug(f'starting {math.ceil(n_rows / n_rows_per_process) } '
                  f'parallel inserts')
    t1 = datetime.datetime.now()
    for chunk in _chunker(tuple_of_tuples, n_rows_per_process):
        x = mp.Process(target=ibmdb_dbi_insert,
                             args=(con_str, sql, chunk))
        x.start()
        threads.append(x)

    for x in threads:
        x.join()
    logging.debug(f'Done {len(threads)} parallel inserts {n_rows} rows '
                  f'{datetime.datetime.now() -t1}')


`

**Comment by paul-lilley** [comment]
Hope the above helps - I'd welcome any feedback/improvements too.

**Comment by mrrameshch** [comment]
Thank you Paul, Implemented as you suggested and it is working perfectly.

**Comment by mrrameshch** [comment]
Thanks
