### ISSUE TITLE
ibm_db_django with db2 cloud

### ISSUE THREAD

**Issue by stuartgreen456** [ibmdb/python-ibmdb#403]
I'm trying to get Django v2.2 to work on IBM Cloud with a db2 cloud backend.

I can get the django instance to connect to the db2 service but initial 'migrate' fails. 
Some of the django tables are created but we then error due to a permission problem:

`2019-06-20T16:52:06.98+0100 [APP/TASK/b12fc77b/0] ERR CREATE TABLE "DJANGO_MIGRATIONS" ("ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 10 ORDER) NOT NULL PRIMARY KEY, "APP" VARCHAR(255) NOT NULL, "NAME" VARCHAR(255) NOT NULL, "APPLIED" TIMESTAMP DEFAULT '2019-06-20 15:52:06.987408' NOT NULL); (params None)`
`2019-06-20T16:52:07.12+0100 [APP/TASK/b12fc77b/0] ERR (0.137) QUERY = 'CREATE TABLE "DJANGO_MIGRATIONS" ("ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 10 ORDER) NOT NULL PRIMARY KEY, "APP" VARCHAR(255) NOT NULL, "NAME" VARCHAR(255) NOT NULL, "APPLIED" TIMESTAMP DEFAULT \'2019-06-20 15:52:06.987408\' NOT NULL)' - PARAMS = (); args=None`
`2019-06-20T16:52:07.12+0100 [APP/TASK/b12fc77b/0] ERR CREATE TABLE "DJANGO_CONTENT_TYPE" ("ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 10 ORDER) NOT NULL PRIMARY KEY, "NAME" VARCHAR(100) NOT NULL, "APP_LABEL" VARCHAR(100) NOT NULL, "MODEL" VARCHAR(100) NOT NULL); (params None)`
`2019-06-20T16:52:07.26+0100 [APP/TASK/b12fc77b/0] ERR (0.135) QUERY = 'CREATE TABLE "DJANGO_CONTENT_TYPE" ("ID" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 10 ORDER) NOT NULL PRIMARY KEY, "NAME" VARCHAR(100) NOT NULL, "APP_LABEL" VARCHAR(100) NOT NULL, "MODEL" VARCHAR(100) NOT NULL)' - PARAMS = (); args=None`
`2019-06-20T16:52:07.26+0100 [APP/TASK/b12fc77b/0] ERR ALTER TABLE "DJANGO_CONTENT_TYPE" ADD CONSTRAINT "DJANGO_CONTENT_TYPE_APP_LABEL_MODEL_76BD3D3B_UNIQ" UNIQUE ("APP_LABEL", "MODEL"); (params ())`
`2019-06-20T16:52:07.29+0100 [APP/TASK/b12fc77b/0] ERR (0.027) QUERY = 'ALTER TABLE "DJANGO_CONTENT_TYPE" ADD CONSTRAINT "DJANGO_CONTENT_TYPE_APP_LABEL_MODEL_76BD3D3B_UNIQ" UNIQUE ("APP_LABEL", "MODEL")' - PARAMS = (); args=()`
`2019-06-20T16:52:07.30+0100 [APP/TASK/b12fc77b/0] ERR Traceback (most recent call last):`
`2019-06-20T16:52:07.30+0100 [APP/TASK/b12fc77b/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/ibm_db_dbi.py", line 1235, in _set_cursor_helper`
`2019-06-20T16:52:07.30+0100 [APP/TASK/b12fc77b/0] ERR     num_columns = ibm_db.num_fields(self.stmt_handler)`
`2019-06-20T16:52:07.30+0100 [APP/TASK/b12fc77b/0] ERR Exception: SQLNumResultCols failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0551N  The statement failed because the authorization ID does not have the required authorization or privilege to perform the operation.  Authorization ID: "GHRxxxxx".  Operation: "SELECT". Object: "SYSIBMADM.ADMINTABINFO".  SQLSTATE=42501 SQLCODE=-551`

What privileges should I be setting for the db2 user to overcome this error?

**Comment by SabaKauser** [comment]
you can grant select privilege on table to respective user.

e.g: On server from Db2 CLP:
db2 grant select on <table> to user <username>

more info can be found here -> https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0000966.html
