### ISSUE TITLE
Can't connect to a catalogued database due to "GSKit Error: 102" windows 10. conenction works on windows  ODBC  and SPSS

### ISSUE THREAD

**Issue by remeez** [ibmdb/python-ibmdb#404]
trying to connect to a database I've catalogued using DB2 CLI. i've tested the connection using CLI, windows ODBC and SPSS.

connecting to the database with ibm_db using 
import ibm_db as db2
import ibm_db_dbi 
conn1 = db2.connect("dbname","uid","pword")

I get the following error:
SQLCODE=-1109on: [IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "GSKit Error: 102".  SQLSTATE=42724

I've added Gskit bin and library to the system path. 
The error code suggests a kdb issue but i use the same file using SPSS and can query. 
102 - GSK_KEYFILE_IO_ERROR
    I/O error reading keyfile. 
conn2 = ibm_db_dbi.Connection(conn1)

**Comment by SabaKauser** [comment]
Is it the same user from SPSS? Did you check if the user has permissions to read the kdb file?

Since you are using instance-based client(catalogued db), can you try connecting from db2 clp (command line processor).
e.g: db2 connect to <dbname> user <username> using <password>

**Comment by SabaKauser** [comment]
clp:
db2 connect to dbname user username using password

**Comment by remeez** [comment]
I'm able to connect to the database in db2 CLP. I'm using the same user in the CLP, SPSS and python environment. The user has admin privilege and is included in the db2 admins and db2 user groups. 

This is the error logs in the db2diag file when i try to connect. Looks like ibm-db is not able to find/open the ssl file, but the other programs have no issue. 

 2019-07-02-08.18.18.749000-240 I44448F436           LEVEL: Error
PID     : 14384                TID : 14388          PROC : python.exe
INSTANCE: DB2                  NODE : 000
HOSTNAME: LAPTOP-V3KEJJKR
EDUID   : 14388
FUNCTION: DB2 UDB, common communication, sqlccMapSSLErrorToDB2Error, probe:530
MESSAGE : DIA3604E The SSL function "gsk_environment_init" failed with the 
          return code "102" in "sqlccLoadSSLLibrary".

2019-07-02-08.18.18.761000-240 I44886F356           LEVEL: Error
PID     : 14384                TID : 14388          PROC : python.exe
INSTANCE: DB2                  NODE : 000
HOSTNAME: LAPTOP-V3KEJJKR
EDUID   : 14388
FUNCTION: DB2 UDB, common communication, sqlccLoadSSLLibrary, probe:998
MESSAGE : DIA3603E SSL was not setup. Return code = "91".

2019-07-02-08.18.18.772000-240 I45244F528           LEVEL: Severe
PID     : 14384                TID : 14388          PROC : python.exe
INSTANCE: DB2                  NODE : 000
HOSTNAME: LAPTOP-V3KEJJKR
EDUID   : 14388
FUNCTION: DB2 UDB, DRDA Communication Manager, sqljcCommConnect, probe:10
MESSAGE : ZRC=0x8636000A=-2043281398=SQLZ_RC_FNEX, SQLT_SQLJC
          "File Does Not Exist"
          DIA8411C A file "" could not be found.
DATA #1 : String, 11 bytes
CCI Error: 
DATA #2 : unsigned integer, 8 bytes
91

**Comment by remeez** [comment]
I tried using the following connection string to connect to the db.

import ibm_db as db2
import ibm_db_dbi

connection_string = """DATABASE=dbname;
                      HOSTNAME=ip;
                      PORT=port;
                      UID=;
                      PWD=;
                      PROTOCOL=TCPIP;
                      Security=ssl;
                      SSLServerCertificate=ibm-truststore.jks;"""

conn = db2.connect(connection_string, ' ', ' ')

tried using .der, .pem .jks certificate files. 
I'm getting the following error code.

 SQLCODE=-30081n: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "127.0.0.1".  Communication function detecting the error: "connect".  Protocol specific error code(s): "10061", "*", "*".  SQLSTATE=08001

**Comment by SabaKauser** [comment]
ODBC and CLI driver requires user to pass keystore database file. Trust store I believe is used by Java driver.
You can either create a keystore or use the SSLServerCertificate keyword to pass the arm file from server.
e.g:
gsk8capicmd_64 -cert -extract -db "mydbserver.kdb" -pw "myServerPassw0rdpw0" 
       -label "myselfsigned" -target "mydbserver.arm" -format ascii -fips

get mydbserver.arm to client and use this for SSLServerCertificate.

**Comment by remeez** [comment]
I tried .arm and .pem certificates as well. 
I tried using pyodbc instead of ibm_db and same result.

**Comment by SabaKauser** [comment]
Can you collect db2 traces as:

cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files with us to assist you further.

**Comment by remeez** [comment]
Hi Saba,

I've attached the trc files.

**Comment by remeez** [comment]
Hi Saba, 

I've attached the trc files. I tried connecting 3 times using different connection strings. 
[trc.zip](https://github.com/ibmdb/python-ibmdb/files/3362990/trc.zip)

**Comment by remeez** [comment]
I was able to resolve the issue. I originally had gskit version 8.0.14 installed. I upgraded to 8.0.50 and it works without a hitch.
