### ISSUE TITLE
Performance problems converting results set

### ISSUE THREAD

**Issue by jjaquinta** [ibmdb/python-ibmdb#406]
I've been tracing performance problems in our REST api when we query a large chunk of data. I'm finding that the bulk of the time is spent iterating through a result set and extracting the contents.

I've copied the instrumented code below, and the times reported by a typical call. The function which includes the DB2 call (`dbSelectStartOffset`) doesn't take that long (132ms). But the look after it, where we call `ibm_db.fetch_assoc` repeatedly and convert the rows does (31021 ms, factoring out the time for our own conversions). 

We're using version 2.0.9 of the library with Python 2.7.12. (We will be switching to Python 3.5.2 soon.)

Is there a different way we can iterate through the result set that will be faster? Is there a newer version of the library that has improved performance in this area?

Instrumented code:
```
        start_time = int(round(time.time() * 1000))
        SQLStmt, count = self.dbSelectStartOffset(params2, isScoped, getCount)
        end_time = int(round(time.time() * 1000))
        g.extra_headers["X-DBSelect-Elapsed"] = str(end_time - start_time)
        responses = {}
        responses[self.collectionName] = []
        start_time = int(round(time.time() * 1000))
        get_time = 0
        row = ibm_db.fetch_assoc(SQLStmt)
        while row is not False:
            get_start_time = int(round(time.time() * 1000))
            responses_temp = self.getResponses(row)
            responses[self.collectionName].append(responses_temp)
            get_end_time = int(round(time.time() * 1000))
            get_time += (get_end_time - get_start_time)
            row = ibm_db.fetch_assoc(SQLStmt)
        responses["count"] = count
        end_time = int(round(time.time() * 1000))
        g.extra_headers["X-DBExtractDB2-Elapsed"] = str(end_time - start_time)
        g.extra_headers["X-DBExtractConv-Elapsed"] = str(get_time)
```

Output values:
```
< X-DBSelect-Elapsed: 132
< X-DBExtractDB2-Elapsed: 44520
< X-DBExtractConv-Elapsed: 13499
```

**Comment by jjaquinta** [comment]
FWIW: I'm also `jo_grant@us.ibm.com`.

**Comment by jjaquinta** [comment]
Oh, DB2 v11.1.4

**Comment by SabaKauser** [comment]
Hello Jo,
There are fetch_assoc(), fetch_both() and fetch_tuple() and all of this return single row from result set. You can try other APIs to see if there is any performance gain(I doubt though).

**Comment by SabaKauser** [comment]
closing for now.
