### ISSUE TITLE
Error Installing on Mac OS IBM_DB with Anaconda

### ISSUE THREAD

**Issue by PhillipDowney** [ibmdb/python-ibmdb#412]
I get the following error when installing IBM_db python library to anaconda 3.7

Last login: Mon Aug  5 19:22:48 on ttys000
(base) phils-MBP:~ phild$ conda install -c conda-forge ibm_db 
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/phild/anaconda3

  added / updated specs:
    - ibm_db

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.6.16          |           py37_0         148 KB  conda-forge
    conda-4.7.10               |           py37_0         3.0 MB  conda-forge
    ibm_db-3.0.1               |   py37h01d97ff_0        19.8 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        22.9 MB

The following NEW packages will be INSTALLED:

  ibm_db             conda-forge/osx-64::ibm_db-3.0.1-py37h01d97ff_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                         pkgs/main --> conda-forge
  conda                                           pkgs/main --> conda-forge

Proceed ([y]/n)? y

Downloading and Extracting Packages
ibm_db-3.0.1         | 19.8 MB   | ##################################### | 100% 
conda-4.7.10         | 3.0 MB    | ##################################### | 100% 
certifi-2019.6.16    | 148 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: failed

ClobberError: The package 'conda-forge::ibm_db-3.0.1-py37h01d97ff_0' cannot be installed due to a
path collision for 'lib/python3.7/site-packages/tests/__init__.py'.
This path already exists in the target prefix, and it won't be removed by
an uninstall action in this transaction. The path appears to be coming from
the package 'defaults::json5-0.8.4-py_0', which is already installed in the prefix.

ClobberError: The package 'conda-forge::ibm_db-3.0.1-py37h01d97ff_0' cannot be installed due to a
path collision for 'lib/python3.7/site-packages/tests/__pycache__/__init__.cpython-37.pyc'.
This path already exists in the target prefix, and it won't be removed by
an uninstall action in this transaction. The path appears to be coming from
the package 'defaults::json5-0.8.4-py_0', which is already installed in the prefix.

CondaVerificationError: The package for ibm_db located at /Users/phil.downey/anaconda3/pkgs/ibm_db-3.0.1-py37h01d97ff_0
appears to be corrupted. The path 'lib/python3.7/site-packages/clidriver/db2dump/._db2diag.log'
specified in the package manifest cannot be found.

**Comment by PhillipDowney** [comment]
I have since got it to work by updating the lib path names with install_name_tool, reinstalling with pip and updating DYLD path. Was unable to get a clean installation with anyone package.. I think part of the problem is the level of libraries in the default Conda packages. using the anaconda  Conda Forge installation method did not work.

**Comment by SabaKauser** [comment]
@PhillipDowney could you please detail out the steps that resolved the problem for you.
This might be helpful to others who face similar problems.

**Comment by PhillipDowney** [comment]
let me try and retrace my steps, I tried a range of different suggestions. I m not absolutely sure what combination did the job. certainly once I reinstalled it it with pip, I had to then update some Conda packages. I think part of the issue is some of the Latest build of Conda is using packages at different levels to ibm_db. that Said Pip seemed to work better after I tried using Conda Forge. I think someone needs to reach out to anaconda

**Comment by PhillipDowney** [comment]
Ok I have had to go through it all again, Installed Anaconda Jupy 2019 3.7
>used pip install ibm_db and worked through any pre-req installs that were required
> then ran the install_name change tool as per https://github.com/ibmdb/python-ibmdb/issues/333
> then ensure DYLD_LIBARY_PATH is set in my bask profile

**Comment by douglas-hoen** [comment]
I have the same problem. This is not acceptable from IBM.

**Comment by SabaKauser** [comment]
This problem will be fixed in next release shortly. 
Although this problem is hit for ibm_db, you may hit this problem for other packages that has tests folder in its installation package.  This is specific to conda-forge and if you have a prior installation of another package that installed tests folder. And the error is thrown out from conda, a warning could have been better than error exit. I have this fix in next release for users relief.
Sorry for the inconvenience!
