### ISSUE TITLE
ibm_db installation error

### ISSUE THREAD

**Issue by migu-el** [ibmdb/python-ibmdb#414]
I am attempting to conect to Informix ds from python in Raspberry pi 3...the issue occurs when run the pip install ibm_db(or pip3) :

> pi@raspberrypi:~ $ pip install ibm_db
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Collecting ibm_db
>   Using cached https://files.pythonhosted.org/packages/98/cb/f77d9bd5f64246074af364cc30e20e3044c533890f3b67d30e89615c2fc5/ibm_db-3.0.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Detected 32-bit Python
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-d5kkIA/ibm-db/setup.py", line 175, in <module>
>         easy_cli_path = os.path.join(tmp_path, 'ibm_db-%s.egg' % ("-".join([VERSION, "py"+sys.version.split(" ")[0][0:3]]) if('win32' in sys.platform) else "-".join([VERSION, "py"+sys.version.split(" ")[0][0:3], os_, arch_])), 'clidriver')
>     NameError: name 'arch_' is not defined

> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-d5kkIA/ibm-db/
> 
I did install the pyton 3 dev package.

Does anybody have been resolving this issue?

Thanks.

**Comment by SabaKauser** [comment]
@migu-el , raspberry pi is not supported by ibm_db.
