### ISSUE TITLE
IfxPy import issue in Thonny IDE

### ISSUE THREAD

**Issue by migu-el** [ibmdb/python-ibmdb#415]
When i try run a pyton sample in Thonny this error message is showed :

> %Run sample.py
> Traceback (most recent call last):
>   File "/home/pi/pysamples/sample.py", line 1, in <module>
>     import IfxPy
>   File "/usr/lib/python3/dist-packages/thonny/backend.py", line 305, in _custom_import
>     module = self._original_import(*args, **kw)
> ImportError: libifdmr.so: cannot open shared object file: No such file or directory.

But in console mode, the same sample python file run fine...

> pi@raspberrypi:~/pysamples $ python3 sample.py
> --  Record 1 --1-BOYS 4/5, 6/7, 8, 10/12, 14/16, 18, 20
> --  Record 2 --2-BOYS XS, S, M, L, XL, 2XL, 3XL
> --  Record 3 --3-BOYS XS(4-5), S(6-7), M(8), L(10-12), XL(14-16, XXL(18), 10/12H, 14/16H
> --  Record 4 --4-GIRLS 4/5, 6/6X, 7/8, 10/12, 14/16
> --  Record 5 --5-GIRLS 4, 5, 6, 7, 8, 10, 12, 14
> 

I am using Os Rasbian buster  + Python 3x + IfxPy database Driver.

Your help is great appreciated!!!!

**Comment by kadler** [comment]
I suspect this would be more applicable over here: https://github.com/OpenInformix/IfxPy
