### ISSUE TITLE
[IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "GSKit Error: 8".  on windows 10

### ISSUE THREAD

**Issue by reshmigumtya** [ibmdb/python-ibmdb#417]
Python - 3.7
OS- WIN 10
python package
---------------------
ibm_db == 3.0.1
ibm_db_sa == 0.3.4

On win 7 I was able to connect IBM DB but once I upgraded to win 10 I am getting this error:
Exception: [IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "GSKit Error: 8".  SQLSTATE=42724
 SQLCODE=-1109

My code snippet:
        jdbc_url_template = 'ibm_db_sa://%s:%s@%s:%s/%s;Security=SSL'
        self.__url = jdbc_url_template % (username, password,
                                          hostname, port, db_name)
        self.__engine = create_engine( self.__url)
        self.__conn = self.engine.connect()

**Comment by reshmigumtya** [comment]
There was similar issue for node IBM_DB package but it was solved on version ibm_db@2.4.1
https://github.com/ibmdb/node-ibm_db/issues/448

**Comment by SabaKauser** [comment]
If server is enabled for SSL connection, then specifying that port and security=ssl would work using the default certificate present under clidriver/cfg/*.arm file unless sslservercertificate is passed to with the generated server arm file.
Are you connecting to the same database?
Try the alternatives suggested in https://github.com/ibmdb/node-ibm_db/issues/448.
python ibm_db also uses clidriver V11.1 with 3.0.1.

If that does not work, collect the traces and share.
cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files with

**Comment by reshmigumtya** [comment]
yes I am using the same Database. 
And this .arm file is not there in the location:
C:\Users\<username>\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\clidriver\cfg

**Comment by reshmigumtya** [comment]
The following solved the Issue:

1. Changed the version from 3.7.4(32 bit) to 3.7.3(64 bit)
Then I got the below error for 'import ibm_db':
ImportError: DLL load failed: %1 is not a valid Win32 
So downgraded the ibm_db version from 3.0.1 to 2.0.9
And it solved!
