### ISSUE TITLE
execute fonction task 'create tenant' returns "(' 1)Can not commit transaction.',)"

### ISSUE THREAD

**Issue by romatho** [ibmdb/python-ibmdb#419]
I'm working on a automatic script that will create the various spaces to create a tenant DB and then create this DB.  The creation of the spaces goes well but when it is time to create the tenant DB it fails and the row returned is the following "(' 1)Can not commit transaction.',)"  (no exception is generated it just return the row and the Db is not created).
However,  the same sql command lines do work when working with dbaccess.

the code is the following:
```
conn_str = "server=informix;database=sysadmin;hostname=" + database_hostname + ";port=" + database_port + ";protocol=TCPIP;UID=informix;PWD="+ informix_pwd

create_db = "execute function admin('CREATE DBSPACE FROM STORAGEPOOL','"+dblist[i]+"_dbs', '100 MB');"
temp=ibm_db.exec_immediate(ibm_db_conn, create_db)
 print(ibm_db.fetch_tuple(temp))
 create_db = "execute function admin('CREATE SBSPACE FROM STORAGEPOOL','"+dblist[i]+"_sbs', '100 MB');"
temp=ibm_db.exec_immediate(ibm_db_conn, create_db)
 print(ibm_db.fetch_tuple(temp))
create_db = "execute function admin('CREATE BLOBSPACE FROM STORAGEPOOL','"+dblist[i]+"_bls', '100 MB');"
temp=ibm_db.exec_immediate(ibm_db_conn, create_db)
print(ibm_db.fetch_tuple(temp))
 create_db = "EXECUTE FUNCTION task('tenant create', '"+dblist[i]+"',       '{dbspace:\""+dblist[i]+"_dbs\",sbspace:\""+dblist[i]+"_sbs\",blobspace: \""+dblist[i]+"_bls\","
            create_db = create_db +"vpclass:\"tvp_c"+dblist[i]+",num=1\",session_limit_locks: \"2000\",session_limit_memory:\"110MB\",session_limit_tempspace:\"35MB\",session_limit_logspace:\"35MB\","
create_db = create_db +"session_limit_txn_time:\"180\",tenant_limit_memory:\"200MB\",tenant_limit_connections:\"200\",logmode:\"buffered\"}' );"
temp=ibm_db.exec_immediate(ibm_db_conn, create_db)
print(ibm_db.fetch_tuple(temp))
```

Thank you a lot for helping,
Romain Mathonet

**Comment by SabaKauser** [comment]
Hi Romain,
This seem to be looked into by server team.
To confirm, please collect traces.

cd `clidriver install path` under site-packages
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files

**Comment by romatho** [comment]
Here are the files
[trc.tar.gz](https://github.com/ibmdb/python-ibmdb/files/3560120/trc.tar.gz)

**Comment by SabaKauser** [comment]
Hello Romain,

Thanks for the traces,
I can see from the traces that client did send the full statement to server and server responded with SQLCODE '0' --> which is success and client will not generate exceptions for such cases.

traces:
19430	data DB2 UDB DRDA Communication Manager sqljcReceive fnc (3.3.54.3.0.1178)
	pid 99359 tid 139683823191872 cpid -1 node -1 probe 1178
	bytes 488

	RECEIVE BUFFER(AR):

            SQLCARD OBJDSS                   (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  001ED04300010018 2408000000000020   ...C....$......   ..}.............
  0010  2020202049465831 32313030FFFF           IFX12100..    ..............

            RDBUPDRM RPYDSS                  (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  0026D05200020020 2218000611490000   .&.R... "....I..  ..}.............
  0010  00162110E2E8E2C1 C4D4C9D540404040   ..!.........@@@@  ....SYSADMIN    
  0020  404040404040                        @@@@@@                  

            RSLSETRM RPYDSS                  (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  0058D05200020052 2219000611490000   .X.R...R"....I..  ..}.............
  0010  0048213900442113 E2E8E2C1C4D4C9D5   .H!9.D!.........  ........SYSADMIN
  0020  4040404040404040 4040D5E4D3D3C9C4   @@@@@@@@@@......            NULLID
  0030  4040404040404040 40404040E2E8E2E2   @@@@@@@@@@@@....              SYSS
  0040  C8F5F0F040404040 4040404040405359   ....@@@@@@@@@@SY  H500          ..
  0050  534C564C30310005                    SLVL01..          .<.<....

            SQLCARD OBJDSS                   (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  001ED05300020018 2408000000000020   ...S....$......   ..}.............
  0010  2020202049465831 32313030FFFF           IFX12100..    ..............

            SQLRSLRD OBJDSS                  (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  0026D05300020020 240E010000000000   .&.S... $.......  ..}.............
  0010  0000000E73716C5F 6375727368353030   ....sql_cursh500  ......%^........
  0020  633500000000                        c5....            ......

            OPNQRYRM RPYDSS                  (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  0031D0520002002B 2205000611490000   .1.R...+"....I..  ..}.............
  0010  0006210224170005 211FF10005215001   ..!.$...!....!P.  ..........1...&.
  0020  000C215B00000000 000000000005214B   ..![..........!K  ...$............
  0030  F1                                  .                 1

            SQLCINRD OBJDSS                  (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  0036D05300020030 240BFF0100000000   .6.S...0$.......  ..}.............
  0010  0000080000000000 00C9010333000000   ............3...  .........I......
  0020  0000000000000100 0000000000000000   ................  ................
  0030  00000000FFFF                        ......            ......

            QRYDSC OBJDSS                    (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  001FD05300020019 241A0676D0350800   ...S....$..v.5..  ..}.........}...
  0010  0971E0540001D000 010671F0E00000     .q.T......q....   ..\...}....0\..

            QRYDTA OBJDSS                    (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  002DD05300020027 241BFF0000001E20   .-.S...'$......   ..}.............
  0010  312943616E206E6F 7420636F6D6D6974   1)Can not commit  .../>.>?...?__..
  0020  207472616E736163 74696F6E2E          transaction.     .../>./...?>.

            ENDQRYRM RPYDSS                  (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  0026D05200020020 220B000611490004   .&.R... "....I..  ..}.............
  0010  00162110E2E8E2C1 C4D4C9D540404040   ..!.........@@@@  ....SYSADMIN    
  0020  404040404040                        @@@@@@                  

            SQLCARD OBJDSS                   (ASCII)           (EBCDIC)
         0 1 2 3 4 5 6 7  8 9 A B C D E F   0123456789ABCDEF  0123456789ABCDEF
  0000  001ED00300020018 2408006400000030   ........$..d...0  ..}.............
  0010  3230303049465831 32313030FFFF       2000IFX12100..    ..............

  DDM Format: d0 RECV(AR) OBJDSS - Object Data Stream Structure
  LL: 30  CORR: 0001  CHAINED: y  CONT ON ERR: n  SAME CORR FOR NEXT DSS: n  

    NM: SQLCARD - SQL Communications Area Reply Data
      LL: 24    CP: 2408   
      * SQLCAGRP: Not Null (00)
      * SQLCODE:
        DECIMAL:     0     (if byte-reversed: 0) 
        HEXADECIMAL: 00000000 (if byte-reversed: 00000000)
      * SQLSTATE: 2020202020
      * SQLERRPROC:
        ASCII: IFX12100
        EBCDIC: ........
      * SQLCAXGRP: Null (ff)
      * SQLDIAGGRP: Not Null (00)
        DATA:                              (ASCII)          (EBCDIC)

  DDM Format: d0 RECV(AR) RPYDSS - Reply Data Stream Structure
  LL: 38  CORR: 0002  CHAINED: y  CONT ON ERR: n  SAME CORR FOR NEXT DSS: y  

    NM: RDBUPDRM - RDB Update Reply Message
      LL: 32    CP: 2218   
      NM: SVRCOD - Severity Code
        LL: 6    CP: 1149   
        Information Only Severity Code (0000)
      NM: RDBNAM - Relational Database Name
        LL: 22    CP: 2110   
        ASCII: ........@@@@@@@@@@
        EBCDIC: SYSADMIN          

  DDM Format: d0 RECV(AR) RPYDSS - Reply Data Stream Structure
  LL: 88  CORR: 0002  CHAINED: y  CONT ON ERR: n  SAME CORR FOR NEXT DSS: y  

    NM: RSLSETRM - RDB Result Set Reply Message
      LL: 82    CP: 2219   
      NM: SVRCOD - Severity Code
        LL: 6    CP: 1149   
        Information Only Severity Code (0000)
      NM: PKGSNLST - RDB Pkg Name, Const Tkn & Sec
        LL: 72    CP: 2139   
        DATA:                              (ASCII)          (EBCDIC)
        00442113E2E8E2C1 C4D4C9D540404040  .D!.........@@@@ ....SYSADMIN    
        404040404040D5E4 D3D3C9C440404040  @@@@@@......@@@@       NULLID    
        4040404040404040 E2E8E2E2C8F5F0F0  @@@@@@@@........         SYSSH500
        4040404040404040 40405359534C564C  @@@@@@@@@@SYSLVL           ...<.<
        30310005                           01..             ....

  DDM Format: d0 RECV(AR) OBJDSS - Object Data Stream Structure
  LL: 30  CORR: 0002  CHAINED: y  CONT ON ERR: n  SAME CORR FOR NEXT DSS: y  

    NM: SQLCARD - SQL Communications Area Reply Data
      LL: 24    CP: 2408   
      * SQLCAGRP: Not Null (00)
      * SQLCODE:
        DECIMAL:     0     (if byte-reversed: 0) 
        HEXADECIMAL: 00000000 (if byte-reversed: 00000000)
      * SQLSTATE: 2020202020
      * SQLERRPROC:
        ASCII: IFX12100
        EBCDIC: ........
      * SQLCAXGRP: Null (ff)
      * SQLDIAGGRP: Not Null (00)
        DATA:                              (ASCII)          (EBCDIC)

  DDM Format: d0 RECV(AR) OBJDSS - Object Data Stream Structure
  LL: 38  CORR: 0002  CHAINED: y  CONT ON ERR: n  SAME CORR FOR NEXT DSS: y  

    NM: SQLRSLRD - SQL Result Set Reply Data
      LL: 32    CP: 240E   
      DATA:                              (ASCII)          (EBCDIC)
      0100000000000000 000E73716C5F6375  ..........sql_cu ............%^..
      7273683530306335 00000000          rsh500c5....     ............

  DDM Format: d0 RECV(AR) RPYDSS - Reply Data Stream Structure
  LL: 49  CORR: 0002  CHAINED: y  CONT ON ERR: n  SAME CORR FOR NEXT DSS: y  

    NM: OPNQRYRM - Open Query Complete
      LL: 43    CP: 2205   
      NM: SVRCOD - Severity Code
        LL: 6    CP: 1149   
        Information Only Severity Code (0000)
      NM: QRYPRCTYP - Query Protocol Type
        LL: 6    CP: 2102   
        CODE POINT DATA: 2417
        NAME: LMTBLKPRC - Limited Block Query Protocol
      NM: SQLCSRHLD - Hold Cursor Position
        LL: 5    CP: 211F   
        BOOLEAN: ????
      NM: QRYATTUPD - Query Attribute for Updatability
        LL: 5    CP: 2150   
        The cursor is read-only
      NM: QRYINSID - Query Instance Identifier
        LL: 12    CP: 215B   
        DATA: 0000000000000000 
      NM: DYNDTAFMT - Dynamic Data Format
        LL: 5    CP: 214B   
        BOOLEAN: ????

  DDM Format: d0 RECV(AR) OBJDSS - Object Data Stream Structure
  LL: 54  CORR: 0002  CHAINED: y  CONT ON ERR: n  SAME CORR FOR NEXT DSS: y  

    NM: SQLCINRD - SQL Result Set Col Info Rpy Data
      LL: 48    CP: 240B   
      DATA:                              (ASCII)          (EBCDIC)
      FF01000000000000 08000000000000C9  ................ ...............I
      0103330000000000 0000000001000000  ..3............. ................
      0000000000000000 0000FFFF          ............     ............

  DDM Format: d0 RECV(AR) OBJDSS - Object Data Stream Structure
  LL: 31  CORR: 0002  CHAINED: y  CONT ON ERR: n  SAME CORR FOR NEXT DSS: y  

    NM: QRYDSC - Query Answer Set Description
      LL: 25    CP: 241A   
       N-GDA Len: 06 Type: 76 ID: D0
          Var[00] Type: 0X35 Len: 0X0800
      Footer: Length: 15
      DATA:                              (ASCII)          (EBCDIC)
      0971E0540001D000 010671F0E00000    .q.T......q....  ..\...}....0\..

  DDM Format: d0 RECV(AR) OBJDSS - Object Data Stream Structure
  LL: 45  CORR: 0002  CHAINED: y  CONT ON ERR: n  SAME CORR FOR NEXT DSS: y  

    NM: QRYDTA - Query Answer Set Data
      LL: 39    CP: 241B   
      DATA:                              (ASCII)          (EBCDIC)
      FF0000001E203129 43616E206E6F7420  ..... 1)Can not  ........./>.>?..
      636F6D6D69742074 72616E7361637469  commit transacti .?__...../>./...
      6F6E2E                             on.              ?>.

  DDM Format: d0 RECV(AR) RPYDSS - Reply Data Stream Structure
  LL: 38  CORR: 0002  CHAINED: y  CONT ON ERR: n  SAME CORR FOR NEXT DSS: y  

    NM: ENDQRYRM - End of Query
      LL: 32    CP: 220B   
      NM: SVRCOD - Severity Code
        LL: 6    CP: 1149   
        Warning Severity Code (0X0004)
      NM: RDBNAM - Relational Database Name
        LL: 22    CP: 2110   
        ASCII: ........@@@@@@@@@@
        EBCDIC: SYSADMIN          

  DDM Format: d0 RECV(AR) OBJDSS - Object Data Stream Structure
  LL: 30  CORR: 0002  CHAINED: n  CONT ON ERR: n  SAME CORR FOR NEXT DSS: n  

    NM: SQLCARD - SQL Communications Area Reply Data
      LL: 24    CP: 2408   
      * SQLCAGRP: Not Null (00)
      * SQLCODE:
        DECIMAL:     100     (if byte-reversed: 1677721600) 
        HEXADECIMAL: 00000064 (if byte-reversed: 64000000)
      * SQLSTATE: 3032303030
      * SQLERRPROC:
        ASCII: IFX12100
        EBCDIC: ........
      * SQLCAXGRP: Null (ff)
      * SQLDIAGGRP: Not Null (00)
        DATA:                              (ASCII)          (EBCDIC)

Please check with server team to get further assistance on this.
