### ISSUE TITLE
ibm_db.connect has not installed

### ISSUE THREAD

**Issue by P3t3rT1j** [ibmdb/python-ibmdb#420]
hi, 
i installed ibm_db using pip and during the installation i haven't any problem, the issue came when i tried to use ibm_db.connect api, it show me "undefined variable from import: connect" error. 

I'm using windows 7 (64 bits), python version 3.7.4, eclipse 2019-06 with pyDev plugin

Your help is great appreciated!

**Comment by SabaKauser** [comment]
can you show provide the following:
1.you current working directory from where you are running ibm_db.
2.The directory listing.
3.And the sample API use case that you used for connection.

**Comment by P3t3rT1j** [comment]
1. Current working directory

C:\PythonProject\ejemplos

29/08/2019  05:52 p.m.    <DIR>          .
29/08/2019  05:52 p.m.    <DIR>          ..
29/08/2019  05:51 p.m.               379 .project
29/08/2019  05:51 p.m.               439 .pydevproject
05/09/2019  06:59 p.m.             1,655 pruebas.py
               3 archivos          2,473 bytes
---------------------- -------
2. pip list

Package                Version
astroid                2.2.5
autopep8               1.4.4
colorama               0.4.1
Django                 2.2.5
future                 0.17.1
ibm-db                 3.0.1
ibm-db-django          1.1.1.2
importlib-metadata     0.20
isort                  4.3.21
jaydebeapi             1.1.2
jedi                   0.14.1
lazy-object-proxy      1.4.2
mccabe                 0.6.1
more-itertools         7.2.0
parso                  0.5.1
pip                    19.2.3
pluggy                 0.12.0
pycodestyle            2.5.0
pydocstyle             4.0.1
pyflakes               2.1.1
pylint                 2.3.1
python-jsonrpc-server  0.2.0
python-language-server 0.28.3
pytz                   2019.2
rope                   0.14.0
setuptools             41.2.0
six                    1.12.0
snowballstemmer        1.9.0
sqlparse               0.3.0
typed-ast              1.4.0
wrapt                  1.11.2
yapf                   0.28.0
zipp                   0.6.0

---------------------- -------
3. sample
   C:\PythonProject\ejemplos\prueba.py
    hostname = "test"
    database = "xxx.xxx.xxx.xxx"
    port = 6000
    user = "user"
    passwd = "passwd"
    conn = ibm_db.connect("DATABASE=%s;HOSTNAME=%s;PORT=%s;PROTOCOL=TCPIP;UID=%s;PWD=%s" % (database, hostname, port, user, passwd), "",    "")

**Comment by SabaKauser** [comment]
Hello,
I think your cwd has a file named ibm_db.py and import has loaded that module. And since this does not contain connect method, it is complaining of the same.

**Comment by P3t3rT1j** [comment]
Hi, 

the only file with the name ibm_db.py that i found is in the dir C:\Users\user1\AppData\Local\Programs\Python\Python37-32\Lib\site-packages

if i remove it the import fail

**Comment by SabaKauser** [comment]
can you do this:
python -v
import ibm_db 
and check the path from where ibm_db is imported. It should be the one loaded from ibm_db.pyd.

**Comment by P3t3rT1j** [comment]
this it the path from where ibm_db is imported

# extension module 'ibm_db' loaded from 'C:\\Users\\TIJUANA\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\ibm_db_dlls\\ibm_db.dll'
# extension module 'ibm_db' executed from 'C:\\Users\\TIJUANA\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\ibm_db_dlls\\ibm_db.dll'
import 'ibm_db' # <_frozen_importlib_external.ExtensionFileLoader object at 0x002F4970>
import 'ibm_db' # <_frozen_importlib_external.SourceFileLoader object at 0x002F48F0>
# destroy ibm_db

**Comment by SabaKauser** [comment]
This seem to be problem with eclipse.

https://stackoverflow.com/questions/2112715/how-do-i-fix-pydev-undefined-variable-from-import-errors

Can you try setting undefined imports to warning and see if the problem goes away.
The python ibm_db is imported from correct location and APIs should work.

**Comment by SabaKauser** [comment]
closing for now. reopen if you need more assistance.
