### ISSUE TITLE
WRKSTNNAME Error on 2019 MacBook Pro - no issue on Late 2013 MBP

### ISSUE THREAD

**Issue by gfcannon12** [ibmdb/python-ibmdb#422]
I get the following error when trying to connect to db2 using the ibm_db python package.

```
[IBM][CLI Driver] SQL4917N  Element "SQLE_CLIENT_INFO_WRKSTNNAME" 
in the option array is not valid. SQLCODE=-4917
```

This problem is specific to my new machine (2019 MacBook Pro).  I set up this machine from a Time Machine backup of my old machine (Late 2013 MacBook Pro).  The exact same code is able to connect to the database without error on my old machine.  The new machine can connect to the database using the SQLDeveloper program but not python.

The error persists when trying different databases on different servers.  I am trying to connect to the Db2 Warehouse on Cloud service.

Environment:

- 2019 MacBook Pro
- macOS v. 10.14.6
- python v. 3.6.8 (also tried 3.7.4)
- ibm_db v. 3.0.1
- conda environment (also tried non-conda python)

I've tried:

- Uninstall / reinstall ibm_db with pip (regular and sudo, --no-cache-dir)
- Download clidriver to different directory and set IBM_DB_HOME env var

I get the error when executing the connect method:

```
import ibm_db
conn = ibm_db.connect(DSN, "", "")
```

At this point, I expect python to connect to the database, but I get the following error:

```
[IBM][CLI Driver] SQL4917N  Element "SQLE_CLIENT_INFO_WRKSTNNAME" 
in the option array is not valid. SQLCODE=-4917
```

db2level command

```
~/anaconda3/envs/ibm/lib/python3.6/site-packages/clidriver/bin/db2level
```
db2level output

```
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL10055" with level identifier "0606010E".
Informational tokens are "DB2 v10.5.0.5", "special_35187", "DARWIN64105_35187",
and Fix Pack "5".
Product is installed at
"~/anaconda3/envs/ibm/lib/python3.6/site-packages/clidriver".
```

**Comment by SabaKauser** [comment]
Please collect traces :

cd `clidriver install path`
cd adm
db2trc on -l 2m
<repro>
db2trc dump trc.dmp
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files

**Comment by gfcannon12** [comment]
The ClientWrkStnName value had an invalid character. This resulted from the conflict of Mac ComputerName between my old Mac and new Mac on the same network. Ex. Gray's MacBook Pro -> Gray's MacBook Pro (2). The issue is resolved by changing ComputerName and HostName on the new computer from the terminal.

```
scutil --set ComputerName "graymac"
scutil --set HostName "graymac"
```
