### ISSUE TITLE
ibm_db on iseries i/5

### ISSUE THREAD

**Issue by kgiampa** [ibmdb/python-ibmdb#426]
Is there a driver for ibm iseries i / 5 for python?
When will ibm_db be developed for db2 ibm iseries.
I use pyodbc which relies on the "ibm client access" driver.

Best Regards

**Comment by SabaKauser** [comment]
You can report here -> https://github.com/kadler/python-ibmdb/issues
there is a python driver for ibmi maintained by Kevin.

**Comment by kadler** [comment]
As Saba mentioned, the IBM i OSS team maintains a fork of ibm_db with IBM i support and we ship it via YUM.

We also have the IBM i Access ODBC driver available in PASE for use with PyODBC on IBM i. You can get the driver here: http://ibm.biz/ibmi-odbc-download

**Comment by kgiampa** [comment]
I was looking for a driver that works outside the pase environment, for windows and linux. but the only one I found is pypyodbc but in linux it doesn't work because there is no installation for Iseries access for linux with its odbc.

**Comment by kadler** [comment]
I'm not sure what you mean. We have the IBM i Access ODBC driver available for both Windows and Linux (and now PASE). The link I sent above has the downloads for all 3 there. We have some more documentation getting things set up here: https://github.com/IBM/ibmi-oss-examples/blob/master/odbc/odbc.md

**Comment by kgiampa** [comment]
I think I understand,  I have to use the odbc that provides iseries client solution and not the old iseries access client.
thanks
