### ISSUE TITLE
Error attempting to write dataframe to table and specifying replace

### ISSUE THREAD

**Issue by marc-mclean1** [ibmdb/python-ibmdb#428]
I have tried the following engine strings:
```
from sqlalchemy import create_engine
#e = create_engine("db2+ibm_db://user:pass@host[:port]/database")
#e = create_engine("ibm_db_sa://user:pass@host[:port]/database")
```
retrieving data from table into dataframe is no problem:
```
import pandas as pd
dff = pd.read_sql("select * from model_output_1 limit 10", con=e)
```
writing data from a dataframe to a table is no problem in append mode:
````
dff.to_sql(name="model_output_4", con=e, schema=schema, if_exists="append", index=False)
````
as soon as I switch the if_exists parameter to "replace", I get the following error:
````
dff.to_sql(name="model_output_4", con=e, schema=schema, if_exists="replace", index=False)
````

TypeError                                 Traceback (most recent call last)
<ipython-input-77-668f45f8c530> in <module>()
----> 1 dff.to_sql(name='model_output_4', con=e, schema='DASH5294', if_exists='replace', index=False)

/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py in to_sql(self, name, con, schema, if_exists, index, index_label, chunksize, dtype, method)
   2529         sql.to_sql(self, name, con, schema=schema, if_exists=if_exists,
   2530                    index=index, index_label=index_label, chunksize=chunksize,
-> 2531                    dtype=dtype, method=method)
   2532 
   2533     def to_pickle(self, path, compression='infer',

/opt/conda/lib/python3.6/site-packages/pandas/io/sql.py in to_sql(frame, name, con, schema, if_exists, index, index_label, chunksize, dtype, method)
    458     pandas_sql.to_sql(frame, name, if_exists=if_exists, index=index,
    459                       index_label=index_label, schema=schema,
--> 460                       chunksize=chunksize, dtype=dtype, method=method)
    461 
    462 

/opt/conda/lib/python3.6/site-packages/pandas/io/sql.py in to_sql(self, frame, name, if_exists, index, index_label, schema, chunksize, dtype, method)
   1171                          if_exists=if_exists, index_label=index_label,
   1172                          schema=schema, dtype=dtype)
-> 1173         table.create()
   1174         table.insert(chunksize, method=method)
   1175         if (not name.isdigit() and not name.islower()):

/opt/conda/lib/python3.6/site-packages/pandas/io/sql.py in create(self)
    575                     "Table '{name}' already exists.".format(name=self.name))
    576             elif self.if_exists == 'replace':
--> 577                 self.pd_sql.drop_table(self.name, self.schema)
    578                 self._execute_create()
    579             elif self.if_exists == 'append':

/opt/conda/lib/python3.6/site-packages/pandas/io/sql.py in drop_table(self, table_name, schema)
   1220         schema = schema or self.meta.schema
   1221         if self.has_table(table_name, schema):
-> 1222             self.meta.reflect(only=[table_name], schema=schema)
   1223             self.get_table(table_name, schema).drop()
   1224             self.meta.clear()

/opt/conda/lib/python3.6/site-packages/sqlalchemy/sql/schema.py in reflect(self, bind, schema, views, only, extend_existing, autoload_replace, resolve_fks, **dialect_kwargs)
   4197 
   4198             available = util.OrderedSet(
-> 4199                 bind.engine.table_names(schema, connection=conn)
   4200             )
   4201             if views:

/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/base.py in table_names(self, schema, connection)
   2241             if not schema:
   2242                 schema = self.dialect.default_schema_name
-> 2243             return self.dialect.get_table_names(conn, schema)
   2244 
   2245     def has_table(self, table_name, schema=None):

/opt/conda/lib/python3.6/site-packages/ibm_db_sa/base.py in get_table_names(self, connection, schema, **kw)
    721 
    722     def get_table_names(self, connection, schema=None, **kw):
--> 723         return self._reflector.get_table_names(connection, schema=schema, **kw)
    724 
    725     def get_view_names(self, connection, schema=None, **kw):

<string> in get_table_names(self, connection, schema, **kw)

/opt/conda/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py in cache(fn, self, con, *args, **kw)
     41     info_cache = kw.get("info_cache", None)
     42     if info_cache is None:
---> 43         return fn(self, con, *args, **kw)
     44     key = (
     45         fn.__name__,

/opt/conda/lib/python3.6/site-packages/ibm_db_sa/reflection.py in get_table_names(self, connection, schema, **kw)
    208                     where(systbl.c.tabschema == current_schema).\
    209                     order_by(systbl.c.tabname)
--> 210         return [self.normalize_name(r[0]) for r in connection.execute(query)]
    211 
    212     @reflection.cache

/opt/conda/lib/python3.6/site-packages/ibm_db_sa/reflection.py in <listcomp>(.0)
    208                     where(systbl.c.tabschema == current_schema).\
    209                     order_by(systbl.c.tabname)
--> 210         return [self.normalize_name(r[0]) for r in connection.execute(query)]
    211 
    212     @reflection.cache

TypeError: expected bytes, str found

**Comment by SabaKauser** [comment]
can you open this here -> https://github.com/ibmdb/python-ibmdbsa

**Comment by kadler** [comment]
@SabaKauser Why not transfer this yourself: https://help.github.com/en/articles/transferring-an-issue-to-another-repository

**Comment by SabaKauser** [comment]
Thanks Kevin, Done already.
