### ISSUE TITLE
TIMESTAMP values with hours=24 cause exceptions

### ISSUE THREAD

**Issue by mjhilt** [ibmdb/python-ibmdb#429]
DB2 allows hour values in the range of 0-24 for some reason:
https://www.ibm.com/support/knowledgecenter/SSCJDQ/com.ibm.swg.im.dashdb.sql.ref.doc/doc/r0008474.html

The driver is somehow able to create python datetime objects with hours=24 in python 2.7.
In Python 3.6, the driver thows an exception when pulling a single column with this issue:
`ValueError:` hour must be in 0..23`

When pulling multiple columns where one column has this issue the driver causes the process to seg fault.

My environment is Ubuntu 18.04, Python 3.6.8, ibm-db 3.0.1

**Comment by kadler** [comment]
From the link given above:
> Using the value 24 when representing hours in a time value might result in errors or unexpected data. To avoid this issue, use 00 instead of 24.

Based on that, I suspect the solution is to have the Python interface switch 24 to 0 before converting to a datetime object.

**Comment by mjhilt** [comment]
[patch.txt](https://github.com/ibmdb/python-ibmdb/files/3683016/patch.txt)

**Comment by SabaKauser** [comment]
@mjhilt,
I tried this on python 3.7.2 and it worked without your patch:
>>> stmt = ibm_db.exec_immediate(conn, "insert into timetest values('00:00:24')")
>>> res = ibm_db.exec_immediate(conn,"select * from timetest")
>>> print(res)
<ibm_db.IBM_DBStatement object at 0x00000164FF635098>
>>> row=ibm_db.fetch_tuple(res)
>>> print(row)
(datetime.time(9, 42, 23),)
>>> row=ibm_db.fetch_tuple(res)
>>> print(row)
(datetime.time(0, 0, 24),)
>>> row=ibm_db.fetch_tuple(res)
>>> print(row)
(datetime.time(0, 0, 24),)

The data in db2 is:
db2 "select * from timetest"

COL1
--------
09:42:23
00:00:24
00:00:24

  3 record(s) selected.

Am I missing something in reproducing the problem?

**Comment by mjhilt** [comment]
24 should be in the hour value. Those look like they are seconds?

**Comment by SabaKauser** [comment]
My bad. Thanks! 
I will include this fix  in next release.

**Comment by SabaKauser** [comment]
Fix merged to master.
