### ISSUE TITLE
if a sp has an OUT blob parameter...doesnt work...

### ISSUE THREAD

**Issue by asierra01** [ibmdb/python-ibmdb#434]
I found a serious bug....
``
CREATE OR REPLACE PROCEDURE SP_TEST_OUT_PARAM_BLOB(OUT P1 BLOB(100))

SPECIFIC SP_TEST_OUT_PARAM_BLOB
LANGUAGE SQL
DYNAMIC RESULT SETS 0 
BEGIN
    SET P1 = BLOB('1234567801234567890');
END
``

If use the python code below doesn't work...it returns the out parameter blob as '1234', this is incorrect, It never returns '1234567801234567890' the correct value, I took a deep look at the code, and found out how to fix this issue, I also added a test case.

``
p1 = bytes('1234', 'utf8')

params = (p1,)
stmt, blob = ibm_db.callproc(self.conn, "SP_TEST_OUT_PARAM_BLOB", params)
ibm_db.free_result(stmt)
print("blob '%s' type %s" % (blob, type(blob)))
``
I wrote the code here (https://github.com/asierra01/python-ibmdb)
the most important line [5690] ibm_db.c
paramValuePtr = (SQLPOINTER)curr->svalue;//this fix the issue

**Comment by SabaKauser** [comment]
I haven't tried this yet. I shall try it out and share my feedback.

Thanks

**Comment by imavo** [comment]
This is easy to recreate. I'm not sure about the proposed fix (as regards the v3.0.1 baseline). The code at ibm_db_callproc() after running the execute_helper() has a switch statement that chooses different paths according to the datatype of the output parameter. That switch statement currently lacks any clause for SQL_BLOB (and related binary types), so the `default:` clause runs, which seems unsuitable. Would be useful for have a testcase for returning eacd if SQL_BLOB, or SQL_LONGVARBINARY, SQL_VARBINARY datatypes as OUT parameters from stored procedures.

**Comment by SabaKauser** [comment]
this is fixed in new release 3.0.2.
Thanks for your contribution!
