### ISSUE TITLE
pip3 install ibm_db halted when downloading macos64_odbc_cli.tar.gz

### ISSUE THREAD

**Issue by lechie** [ibmdb/python-ibmdb#435]
`
pip3 --no-cache-dir install -vvv ibm_db
`

...(running sth.)...

`
Running command python setup.py egg_info
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz
`

It's halted here without progress bar ,but I can download the  macos64_odbc_cli.tar.gz file from the brower successfully.
I tried pip3 install ibm_db==3.0.1, but halted too.

macOS catalina version: 10.15.1 
python version: 3.7.4
pip3 version: 19.1.1

**Comment by SabaKauser** [comment]
are you able to install or the problem continues

**Comment by lechie** [comment]
> are you able to install or the problem continues

it costs a very long time to continue.

**Comment by SabaKauser** [comment]
driver uses https for download. I have installed multiple times on mac os and never faced the problem. 
what happens if you use curl and download? is it quick?

**Comment by lechie** [comment]
it's halted for a long time too, I believe what you said. 
May be because of the internet, curl is also slow, but download in chrome is very fast.

```
% curl https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz >> a.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 19.1M    0 65536    0     0   1069      0  5:13:04  0:01:01  5:12:03  1544
```
