### ISSUE TITLE
install ibm_db without internet connection fails

### ISSUE THREAD

**Issue by qsecofr** [ibmdb/python-ibmdb#436]
Hello,

when trying to install the package without an internet connection I run into an error since the setup insists on downloading linuxx64_odbc_cli.tar.gz. Maybe setup can respect options like --find-links.

greetings

Alexander

**Comment by kadler** [comment]
You may want to consult [this part](https://github.com/ibmdb/python-ibmdb#envvar) of the readme Admittedly, it could be better, but you can download one of the installation packages that setup.py downloads and extract it manually, then set `IBM_DB_HOME` to point at that directory.

Also, I don't understand your point about `--find-links`.

**Comment by kadler** [comment]
eg.
```sh
tar -xzf linuxx64_odbc_cli.tar.gz
export IBM_DB_HOME=$PWD/clidriver
pip install ibm_db
```

**Comment by qsecofr** [comment]
To my understanding with --find-links you tell pip to only look in the given folder for packages, not only.

Thing is, we have to download everything move it to the server and install it without internet connection.

I found that trick with IBM_DB_HOME, but I guess I have to alter setup.py to remove tha part about downloading linuxx64_odbc_cli.tar.gz.
