### ISSUE TITLE
Z/os license and anaconda

### ISSUE THREAD

**Issue by itaraday** [ibmdb/python-ibmdb#438]
Hello.

I've used ibm-db to connect with ODBC before and can connect to my data source using data studio.
the license was told to use is enterprise edition ProductVersion=10.5 which others have used to successfully connect to the source DB.

looking at db2 level I see 

Informational tokens are "DB2 v11.1.3031.295", "s1804271300",
"DYN1804271300WIN64", and Fix Pack "3a".

I've put the db2consv_ee.lic file under 
{anaconda}\envs\{env}\Lib\site-packages\clidriver\license

whenever I try to connect though

import ibm_db
con = "DATABASE={};HOSTNAME={};PORT={};PROTOCOL=TCPIP;UID={};PWD={};".format(
db,
host,
port,
user,
pw
)
conn = ibm_db.connect(con, "", "")

SQLCODE=-1598on: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968

using a Windows machine and Python 3.6

**Comment by SabaKauser** [comment]
Hi,
You need to have a license file for V11.1 level. V10.5 license file is not valid for client at v11.1 level.

**Comment by SabaKauser** [comment]
reopen if you need more assistance.
