### ISSUE TITLE
Q: how to applying license file for accessing DB2 for z/OS and any hint for Python2.7 ? 

### ISSUE THREAD

**Issue by tkang007** [ibmdb/python-ibmdb#441]
Hi, 
I have two questions when using ibm_db python package on CentOs 7.5 system for development.

First question:
IBM_DB_HOME and LD_LIBRARY_PATH env var setting does not work properly for Python 2.7, but worked with Python 3.6 as document.

When using with Python 2.7, it still download and install the default IBM product during pip ibm_db installation.
When import ibm_db, it load default installed libdb2.so.1 instead of separated licensed installs and failed with these exception when connecting.

ibm_db_dbi.connect(connstr) 
[IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968 SQLCODE=-1598

ibm_db.connect(connstr,'','')
[IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968 SQLCODE=-1598

Loaded shared library with Python 2.7 (lsof | grep db)
python    18664       vagrant  mem       REG    8,1  36882530 102220979 /usr/lib64/python2.7/site-packages/clidriver/lib/libdb2.so.1
python    18664       vagrant  mem       REG    8,1    384048 102220969 /usr/lib64/python2.7/site-packages/ibm_db.so

Loaded shared library with Python 3.6  
python3   18772       vagrant  mem       REG    8,1  38348272 102133362 /ibmcli/odbc_cli/clidriver/lib/libdb2.so.1
python3   18772       vagrant  mem       REG    8,1    429432   6897046 /usr/local/lib64/python3.6/site-packages/ibm_db.cpython-36m-x86_64-linux-gnu.so

Is there any option to avoid this case for Python 2.7 for existing app regression testing ?

The default downloaded product does not work with our license file even though copying the license file on the installed location. 
I have to install separately for licensed product even though installed thing is very similar.

Second question:
As the doc, copying the license file (db2consv_zs.lic) to license directory, it does not work when connecting with same license issue.  
Workaround is copying nodelock file to the license directory, which generated on the DB2 Client installation.

Is there any hint how to applying license file on clidriver environment without using other DB2 client installation ?

Thanks,
Taewon

**Comment by SabaKauser** [comment]
Hi Taewon,

1. IBM_DB_HOME is only for installation and as you said LD_LIBRARY_PATH is for runtime. I am not aware of any reason why the env var setting won't work unless pip has something special like picking from cache. 
So you can set the env var, and try this:
pip install ibm_db --no-cache-dir

2. Coming to LD_LIBRARY_PATH, try 1 , set the library path again(make sure you have not added the default path) and test.
after you have set the library path, ldd on ibm_db.so should point to the explicit path set. 

3. License is client version specific. Hence if the client you installed on your own is at a version different than the one in default copy(auto-installed by ibm_db), you connection will fail with license error. Either you need to have a client license at default level(for Linux ,its V11.1) or use your client with correct license for connection.
Can you share the db2level of both client levels?

**Comment by tkang007** [comment]
Hi SabaKauser,

Thanks a lot for your response very quickly.
As my testing, I can conclude Python2.7 library binding issue might be related with python 2/3 version difference for handling LD_LIBRARY_PATH.  
In Python2.7, user supplied LD_LIBRARY_PATH was not ahead of Python itself library path. 
In Python3.6, user supplied LD_LIBRARY_PATH was ahead of Python itself library path.
With Python2.7, PYTHONPATH and LD_PRELOAD was not valid, not availbe to ahead of Python itself.

Even though I set IBM_DB_HOME (and  IBM_DB_LIB, IBM_DB_DIR), pip download the default ibm cli product and install on the site-packages/clidriver directory.  This also can be improved.

As a workround for Python2.7 and separately installed clidriver having z/OS licensing.
```
$ find /usr -name clidriver -type d 2>/dev/null | grep site-packages | sudo xargs rm -rf
```

I am still struggle on client side licensing issue as only get a  license file, db2consv_zs.lic.
But, it is not work, only work with nodelock file by using db2licm (but, db2licm not include clidriver).

**Comment by SabaKauser** [comment]
Please help me with db2level of your default (i.e clidriver from python 2.7) and manually installed copy of clidriver. The db2level exe is under bin folder.

**Comment by SabaKauser** [comment]
Also, did you try --no-cache-dir from python 2.7 via pip?
Another thing you can try is rename the clidriver under 2.7 site-packages, set LD_LIBRARY_PATH to your own copy of driver and retry connection.

**Comment by tkang007** [comment]
Hi SabaKauser,

Please reference below information to check db2level and why IBM_DB_HOME does not execlude clidriver installation at site-packages.


"C:\projectg\atssql\3rdparty\DB2_RTC_11.5_Linux_x86-64.tar.gz"



DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11050" with level identifier "0601010F".
Informational tokens are "DB2 v11.5.0.0", "s1906101300", "DYN1906101300AMD64",
and Fix Pack "0".
Product is installed at "/ibmcli/odbc_cli/clidriver".


-bash-4.2# uname -a
Linux centos76b 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

-bash-4.2# pip --version
pip 19.3.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)

-bash-4.2# env | grep IBM
IBM_DB_HOME=/ibmcli/odbc_cli/clidriver
-bash-4.2# env | grep LD
LD_LIBRARY_PATH=/ibmcli/odbc_cli/clidriver/lib

-bash-4.2# db2level
-bash: db2level: command not found
-bash-4.2# export PATH=$PATH:$IBM_DB_HOME/bin
-bash-4.2# $IBM_DB_HOME/bin/db2level
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11050" with level identifier "0601010F".
Informational tokens are "DB2 v11.5.0.0", "s1906101300", "DYN1906101300AMD64",
and Fix Pack "0".
Product is installed at "/ibmcli/odbc_cli/clidriver".

-bash-4.2# pip2 install ibm_db --no-cache-dir
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting ibm_db
  Downloading https://files.pythonhosted.org/packages/98/cb/f77d9bd5f64246074af364cc30e20e3044c533890f3b67d30e89615c2fc5/ibm_db-3.0.1.tar.gz (642kB)
     |████████████████████████████████| 645kB 4.8MB/s
ERROR: Files/directories not found in /tmp/pip-install-nqGKI6/ibm-db/pip-egg-info


-bash-4.2# pip2 install ibm_db
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing ./.cache/pip/wheels/10/3f/74/c274ef3f7afab9b16fbfbd7814eccc229992a91151a13d91c9/ibm_db-3.0.1-cp27-cp27mu-linux_x86_64.whl
Installing collected packages: ibm-db
Successfully installed ibm-db-3.0.1

-bash-4.2# find /usr -name clidriver | grep site-packages
/usr/lib64/python2.7/site-packages/clidriver
/usr/local/lib64/python3.6/site-packages/clidriver
-bash-4.2# ls -al /usr/lib64/python2.7/site-packages/clidriver
total 12
drwxr-xr-x. 11 root root  158 Nov 17 12:38 .
drwxr-xr-x. 38 root root 4096 Nov 17 12:38 ..
drwxr-xr-x.  2 root root  152 Nov 17 12:38 bin
drwxr-xr-x.  2 root root  122 Nov 17 12:38 bnd
drwxr-xr-x.  2 root root  116 Nov 17 12:38 cfg
drwxr-xr-x.  2 root root   24 Nov 17 12:38 cfgcache
drwxr-xr-x.  4 root root   27 Nov 17 12:38 conv
drwxr-xr-x.  2 root root  202 Nov 17 12:38 include
-rw-r--r--.  1 root root    0 Nov 17 12:38 __init__.py
-rw-r--r--.  1 root root  139 Nov 17 12:38 __init__.pyc
drwxr-xr-x.  3 root root  179 Nov 17 12:38 lib
drwxr-xr-x.  3 root root   65 Nov 17 12:38 license
drwxr-xr-x.  3 root root   28 Nov 17 12:38 msg


-bash-4.2# python db2testa.py
LD_LIBRARY_PATH=/ibmcli/odbc_cli/clidriver/lib

ibm_db_dbi connection based on connectin string:
ibm_db_dbi::ProgrammingError: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968 SQLCODE=-1598

ibm_db connection based on connectin string:
[IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968 SQLCODE=-1598

-bash-4.2# find /usr -name clidriver | grep site-packages | xargs rm -rf
-bash-4.2# ls -al /usr/lib64/python2.7/site-packages/clidriver
ls: cannot access /usr/lib64/python2.7/site-packages/clidriver: No such file or directory

-bash-4.2# python db2testa.py
LD_LIBRARY_PATH=/ibmcli/odbc_cli/clidriver/lib

ibm_db_dbi connection based on connectin string:
[(2, u'GL'), (2, u'CP'), (2, u'CL')]

ibm_db connection based on connectin string:
2, GL
2, CP
2, CL

ibm_db_dbi connection based on ibm_db connection:
[(2, u'GL'), (2, u'CP'), (2, u'CL')]

-bash-4.2# ls $IBM_DB_HOME
adm  bin  bnd  cfg  cfgcache  conv  db2dump  lib  license  msg  Readme.txt

-bash-4.2# ls $IBM_DB_HOME/lib
icc  libdb2clixml4c.so  libdb2clixml4c.so.1  libdb2o.so  libdb2o.so.1  libdb2.so  libdb2.so.1  libDB2xml4c.so  libDB2xml4c.so.58  libDB2xml4c.so.58.0

-bash-4.2# ls $IBM_DB_HOME/license
nodelock  odbc_notices.txt  odbc_REDIST.txt  UNIX

Thanks.

**Comment by SabaKauser** [comment]
ok. I can see your installation attempt is picking from cache.
Please clear your cache : ./.cache/pip
And retry.

**Comment by tkang007** [comment]
Yes. you are right. 
It was done after 'rm -rf ~/.cache/pip' as 'pip2  install --no-cache-dir' was not worked.
Thanks SabaKauser!
