### ISSUE TITLE
Installing CLI driver for ibm_db package installation

### ISSUE THREAD

**Issue by rkatcosmos** [ibmdb/python-ibmdb#442]
I am trying to install imb_db package and since I am installing on my corporate computer I think the CLI driver installation attempt is not executing properly.

This is the error I am getting when installing the ibm_db.

```
C:\Users\i0000964\Downloads>pip install -v ibm_db-3.0.1.tar.gz
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Processing c:\users\i0000964\downloads\ibm_db-3.0.1.tar.gz
  Running setup.py (path:C:\Temp\pip-o3sj9f6p-build\setup.py) egg_info for package from file:///C:/Users/i0000964/Downloads/ibm_db-3.0.1.tar.gz
    Running command python setup.py egg_info
    Detected 64-bit Python
    Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip
```
I have not included all the lines of the result. But as I am suspecting that the error is due to lack of permission to download and install the cli driver from web. I am able to overcome this by downloading this independently using the browser. 

What I am not sure of is how to proceed with the installation of the CLI driver.

What all should I do with the downloaded zip file? I feel that I need change/alter some ENVIRONMENT PATH or something. 

Please help me with this.

I am running Python 3.6.0 on a Win10 pc.

**Comment by rkatcosmos** [comment]
> I am trying to install imb_db package and since I am installing on my corporate computer I think the CLI driver installation attempt is not executing properly.
> 
> This is the error I am getting when installing the ibm_db.
> 
> ```
> C:\Users\i0000964\Downloads>pip install -v ibm_db-3.0.1.tar.gz
> Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
> Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
> Processing c:\users\i0000964\downloads\ibm_db-3.0.1.tar.gz
>   Running setup.py (path:C:\Temp\pip-o3sj9f6p-build\setup.py) egg_info for package from file:///C:/Users/i0000964/Downloads/ibm_db-3.0.1.tar.gz
>     Running command python setup.py egg_info
>     Detected 64-bit Python
>     Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip
> ```
> 
> I have not included all the lines of the result. But as I am suspecting that the error is due to lack of permission to download and install the cli driver from web. I am able to overcome this by downloading this independently using the browser.
> 
> What I am not sure of is how to proceed with the installation of the CLI driver.
> 
> What all should I do with the downloaded zip file? I feel that I need change/alter some ENVIRONMENT PATH or something.
> 
> Please help me with this.
> 
> I am running Python 3.6.0 on a Win10 pc.

Will this be the right thing to do?
https://github.com/ibmdb/node-ibm_db/issues/222#issuecomment-435075158

**Comment by rkatcosmos** [comment]
Will this be the right thing to do?
https://github.com/ibmdb/node-ibm_db/issues/222#issuecomment-435075158

**Comment by SabaKauser** [comment]
Please refer https://github.com/ibmdb/python-ibmdb#inst.
If you need more assistance, drop a message.

**Comment by rkatcosmos** [comment]
Ha! Thanks for pointing out at the right point @SabaKauser. Since I was using a corporate system, the automatic download was restricted. And I was able to figure it out only by using the `-v` option in pip installation. It has now started working. Thanks for the help. I might seek more assistance in the coming future, given the installation has gone quite comfortably.

Thanks a lot.

**Comment by SabaKauser** [comment]
anytime! Thank you.
