### ISSUE TITLE
Can't connect to DB2

### ISSUE THREAD

**Issue by byrdman062** [ibmdb/python-ibmdb#443]
I get the following error:

 SQLCODE=-30081][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "10.50.40.21".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001

I am trying the following:

import ibm_db
ibm_db.connect("DATABASE=NEON_DSN;HOSTNAME=PRODESA;PORT=1200;PROTOCOL=TCPIP;UID=userid; PWD=password;", "", "")

The DSN is a DataDirect Shadow Client 7.3 and is mapped on my machine.

I can connect using R and the following code:
library (RODBC) #import the RODBC library
dsn.name <- "NEON_DSN"
con1 <- odbcConnect(dsn=dsn.name,uid="username")

**Comment by SabaKauser** [comment]
Hi,
Is this hostname valid "PRODESA?
The problem is not with DSN Name but with the host. At 10.50.40.21, port 1200, your db2 server does not seem to be listening. Can you login to server and see if its started and listening at 1200 DRDA port.

**Comment by byrdman062** [comment]
I think so. Here is a screenshot of the connection. Again it works for both R and Access.

![image](https://user-images.githubusercontent.com/57776859/68952820-325a1d00-0786-11ea-86d4-161e9ce89ba2.png)

I am reaching out to the owners to follow up on your second question.

**Comment by SabaKauser** [comment]
From Access, are you using the Db2 ODBC driver for connection. If so, please collect db2 traces. I need db2 traces for both the working case(Access or R driver) and non-working case(python driver).
The db2traces can be collected as:
cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files with us to assist you further.

**Comment by SabaKauser** [comment]
re-open when you have the needed data.
Thanks

**Comment by sricharan44** [comment]
I am also facing this same issue.I am trying to connect to a public DB2 instance only.
