### ISSUE TITLE
Bad behaviour of UTF-16 decoding

### ISSUE THREAD

**Issue by theophilechevalier** [ibmdb/python-ibmdb#447]
Hi,

I ran into problems when decoding some `UTF-16` encoded strings, and I'm curious about the way [strings are decoded in the package](https://github.com/ibmdb/python-ibmdb/blob/78993f2e941383c2d9187bf0a626bb0fce3b0892/IBM_DB/ibm_db/ibm_db.c#L1417-L1439), especially in `getSQLWCharAsPyUnicodeObject`.

From my understanding, there is no `BOM` support in the above function. According to [Python documentation](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_DecodeUTF16):
_"If *byteorder is zero, and the first two bytes of the input data are a byte order mark (BOM),
the decoder switches to this byte order and the BOM is not copied into the resulting Unicode string.
If *byteorder is -1 or 1, any byte order mark is copied to the output (where it will result in either a \ufeff or a \ufffe character)."_

Looking at the function definition in `CPython` [code](https://github.com/python/cpython/blob/master/Objects/unicodeobject.c#L5787), it seems that any eventual `BOM` is simply ignored if `*byteorder` is not zero.

According to [getSQLWCharAsPyUnicodeObject at line 1431](https://github.com/ibmdb/python-ibmdb/blob/78993f2e941383c2d9187bf0a626bb0fce3b0892/IBM_DB/ibm_db/ibm_db.c#L1431), the `byteorder` is set depending on the user's machine.

In my case, I have to decode big endian-encoded strings on a little endian machine, so it fails.

The database server is either big or little endian, so in my opinion the information of byteorder to -1 or 1 for decoding should come from it, and not from the macro `is_bigendian`.

Clause D98 of conformance (section 3.10) of the Unicode standard states, _"The UTF-16 encoding scheme may or may not begin with a BOM. However, when there is no BOM, and in the absence of a higher-level protocol, the byte order of the UTF-16 encoding scheme is big-endian."_.

As a quick dirty workaround for my usecase and maximum tolerance, I'd write something like
```C
u = PyUnicode_DecodeUTF16((char *)sqlwcharData, sqlwcharBytesLen, "strict", NULL);
if (PyErr_Occurred()){
    if (PyErr_ExceptionMatches(PyExc_UnicodeDecodeError)){
        PyErr_Clear();
        int bo = 1;
        u = PyUnicode_DecodeUTF16((char *)sqlwcharData, sqlwcharBytesLen, "strict", &bo);
    }
}
return u;
```

In this case, if *bo is `NULL`, CPython will check for a BOM, or convert it as little endian otherwise. In case of failure, we try as bigendian. This way it's working either for strings with or without BOM, `UTF-16-LE` or `UTF-16-BE`.

Any help appreciated !

**Comment by SabaKauser** [comment]
Hi,
I am on vacation and back on Dec 2nd. I will look into this after I am back.

**Comment by amukherjee28** [comment]
Closing this issue. In the new release 3.1.1 Unicode character issue has been fixed. Please check with the latest version.
In case the issue persists please open a new issue.
