### ISSUE TITLE
Travis CI: docker pull ibmcom/db2express-c fails

### ISSUE THREAD

**Issue by cclauss** [ibmdb/python-ibmdb#449]
https://travis-ci.org/ibmdb/python-ibmdb/jobs/614147866#L216 fails because there is no such Docker image https://hub.docker.com/search?q=ibmcom%2Fdb2

**Comment by SabaKauser** [comment]
Hi,
I am on vacation and back on 2nd Dec. I will respond to your message after I am back.

**Comment by imavo** [comment]
This issue should be closed, because it does not directly relate to ibm_db.

IBM corporation decides what it puts on dockerhub and when to remove such images, and any prerequisites such as customer identification. 

None of that is relevant for ibm_db directly.
