### ISSUE TITLE
Travis CI: Migration needed from travis-ci.org --> travis-ci.com

### ISSUE THREAD

**Issue by cclauss** [ibmdb/python-ibmdb#450]
https://travis-ci.org/ibmdb/python-ibmdb -->
https://travis-ci.com/ibmdb/python-ibmdb so that tests are associated with pull requests.

**Comment by kadler** [comment]
@SabaKauser can you please move this over? See https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/ for more info.

**Comment by SabaKauser** [comment]
@kadler @cclauss ,I do not seem to have authority to move using my login. We have an admin login and I have requested him to either give me  necessary access or move.

**Comment by SabaKauser** [comment]
Its moved now. There was some temporary bug that travis team has now fixed and I can see the repository under travis-ci.com
