### ISSUE TITLE
python  :  ImportError: dlopen failed: "/data/data/org.teammate.teammate/files/app/ibm_db_dlls/ibm_db.dll" has bad ELF magic

### ISSUE THREAD

**Issue by kulvir244** [ibmdb/python-ibmdb#454]
i am trying to use ibm-db in my python-android app. i am getting below error when app runs on android phone:-
python  :  ImportError: dlopen failed: "/data/data/org.teammate.teammate/files/app/ibm_db_dlls/ibm_db.dll" has bad ELF magic

**Comment by kulvir244** [comment]
please help to find a solution for this, i am trying to solve it from days.

**Comment by SabaKauser** [comment]
Hi, we do not officially support ibm_db on android.
