### ISSUE TITLE
Segmentation Fault with Large Date Time

### ISSUE THREAD

**Issue by ProgrammingByPermutation** [ibmdb/python-ibmdb#457]
When I retrieve a row from the database with the following information:

Identifier | Key | Start Time | Stop Time
----------|-----|--------------|------------|
1111|MY_KEY|11/26/2019 4:16:18 PM |12/30/9999 12:00:00 AM

I consistently get a crash in Python where the process exits with the following: 
Windows: -1073741819 (0xC0000005)
Linux: Segmentation fault (core dumped)

The table definition is the following:

Identifier | Key | Start Time | Stop Time
----------|-----|--------------|------------|
INTEGER|VARCHAR(50)|TIMESTAMP|TIMESTAMP

There are a lot of other rows in the database, anything without this date time (12/30/9999 12:00:00 AM) I am able to query without receiving a segmentation fault. It is only this date time that fails. Using Toad Data Point, I am able to pull this row successfully.

**Comment by SabaKauser** [comment]
I would like to know how you inserted the values 
12/30/9999 12:00:00 AM into the db2 database so that I can reproduce.

**Comment by SabaKauser** [comment]
Any information that you can share for my question earlier.
