### ISSUE TITLE
Current release on conda-forge don't work for SSL connection

### ISSUE THREAD

**Issue by haobibo** [ibmdb/python-ibmdb#459]
![image](https://user-images.githubusercontent.com/1597350/71811854-ae028700-30b0-11ea-8afb-6d7d94bc1c54.png)

**Comment by SabaKauser** [comment]
Hi,
The code is same and SSL connection works. I need traces for both working and failing case to narrow down the problem.
Collect them as:
cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files

The clidirver is usually installed under site-packages unless you have set IBM_DB_HOME.

**Comment by haobibo** [comment]
@SabaKauser  Thank you for your quick reply.

For the conda package installed from the `conda-forge` channel:  https://anaconda.org/conda-forge/ibm_db/files  (<--- you can also download a copy with this URL:  https://anaconda.org/conda-forge/ibm_db/3.0.1/download/linux-64/ibm_db-3.0.1-py36h516909a_1.tar.bz2)

After unzipped (same with the `conda install -c conda-forge ibm_db`) and cd into `clidriver`:
 - there is no folder named `adm`
 - when running `./bin/db2trc on -f trc.dmp`, it reported `error while loading shared libraries: libdb2.so.1: cannot open shared object file: No such file or directory`

I think this might be a specific error for conda pkg, since the one installed by pip works well.

**Comment by SabaKauser** [comment]
can you set DYLD_LIBRARY_PATH to point to clidriver/lib location and retry.

**Comment by haobibo** [comment]
[db2cli_dmp.zip](https://github.com/ibmdb/python-ibmdb/files/4030534/db2cli_dmp.zip)

**Comment by SabaKauser** [comment]
Hi,
From the traces, I can see that Key manager initialization via GSKKM_Init is failing. I also see that you do not seem to have sufficient permissions to write as logged in user to db2diag.log.

3853	entry DB2 UDB oper system services sqloopenp cei (1.3.15.845.2)
	pid 7697 tid 139970381801280 cpid -1 node -1

	bytes 120

	Data1 	(PD_TYPE_FILE_NAME,72) File name:
	/opt/anaconda3/lib/python3.7/site-packages/clidriver/db2dump/db2diag.log
	Data2 	(PD_TYPE_SQO_FILE_OPEN_OPTIONS,4) SQO Open File Options:
SQLO_CRTREV, SQLO_WRITEONLY, SQLO_SHAREREAD, SQLO_NO_FLUSH_ON_CLOSE, SQLO_EXPLOCK, SQLO_NO_THREAD_LEVEL_FILE_LOCK, SQLO_USE_RESERVED_HANDLE_IF_NEEDED, SQLO_NO_UNSAFE_LINK
	Data3 	(PD_TYPE_HEXINT,4) Hex integer:
	0x000001B6
	Data4 	(PD_TYPE_PTR,8) Pointer:
	0x0000000000000000

3854	mbt DB2 UDB oper system services sqloopenp cei (6.3.15.845.2.32769)
	pid 7697 tid 139970381801280 cpid -1 node -1

	Marker:PD_SQO_OPEN_WRITE_FOR_SHARED_LOCK 
	Description: The file mode is being switch to read/write in order to lock the file 

3855	exit DB2 UDB oper system services sqloopenp cei (2.3.15.845.2)
	pid 7697 tid 139970381801280 cpid -1 node -1
	codepath = 5:7:15:27:30

	rc = 0x870F0011 = -2029060079 = SQLO_PATH
	bytes 16
	
db2diag -rc 0x870F0011

Input ZRC string '0x870F0011' parsed as 0x870F0011 (-2029060079).

ZRC value to map: 0x870F0011 (-2029060079)
        V7 Equivalent ZRC value: 0xFFFFF611 (-2543)

ZRC class :
        Global Processing Error (Class Index: 7)
Component:
        SQLO ; oper system services (Component Index: 15)
Reason Code:
        17 (0x0011)

Identifer:
        SQLO_PATH
        SQLO_PATH_NOT_FOUND
Identifer (without component):
        SQLZ_RC_PATH

Description:
        an invalid path

Associated information:
        Sqlcode -902
SQL0902C  A system error occurred. Subsequent SQL statements cannot be
processed. IBM software support reason code: "".

        Number of sqlca tokens : 1
        Diaglog message number: 8514

It complains that /opt/anaconda3/lib/python3.7/site-packages/clidriver/db2dump/db2diag.log is invalid or does not exist.

Do you have necessary privileges to /opt/ananconda3/*/clidriver/* ?		

If you can share the traces from working case, I can possibly forward the traces to IBM gskit team for their support on this case.

I tried SSL connection from ibm_db through my anaconda installation and its working fine.

**Comment by SabaKauser** [comment]
Are you able to make any progress? If not, can you share the working trace?

**Comment by haobibo** [comment]
Turned out to be a permission issue. The folder which including this package was set to read-only for the user - we found the package will write something in that folder.

As a suggestion, it will be better for this package to assume the folder containing it is not write-able. Temp files/configurations could be written to the user's home folder or TEMP folders.
