### ISSUE TITLE
import of ibm_db failed

### ISSUE THREAD

**Issue by meiras** [ibmdb/python-ibmdb#460]
Using python 3.7. I can install ibm_db but cannot import.

If it helps, I see libdb2.dylib
Troubleshooting steps from 2015/2016 for the same error have not resolved the issue.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-fe3bb08c8a05> in <module>
----> 1 import ibm_db

ImportError: dlopen(/Users/meiras/anaconda3/lib/python3.7/site-packages/ibm_db.cpython-37m-darwin.so, 2): Library not loaded: libdb2.dylib
  Referenced from: /Users/meiras/anaconda3/lib/python3.7/site-packages/ibm_db.cpython-37m-darwin.so
  Reason: image not found

**Comment by SabaKauser** [comment]
try this:
pip install --no-cache-dir ibm_db
If the problem is still not resolved,  share the path to clidriver/lib/libdb2.dylib

**Comment by SabaKauser** [comment]
or try : pip install --no-binary "ibm_db" ibm_db

**Comment by SabaKauser** [comment]
is your problem solved?

**Comment by brunomuriel** [comment]
Look at this, it worked for me https://github.com/ibmdb/python-ibmdb/tree/master/IBM_DB/ibm_db#issues-with-mac-os-x

**Comment by SabaKauser** [comment]
can this be closed?

**Comment by meiras** [comment]
It still isn't working. Same error.

**Comment by SabaKauser** [comment]
neither of the below worked?
pip install --no-cache-dir ibm_db
or
pip install --no-binary "ibm_db" ibm_db

**Comment by GraceYxx** [comment]
Hi Guys

I have encountered the same issue with Meiras, and I have tried two ways provided by SabaKauser, but both didn't work,

**Comment by SabaKauser** [comment]
This issue is fixed in ibm_db 3.0.2. Which version are you using?

**Comment by GraceYxx** [comment]
> This issue is fixed in ibm_db 3.0.2. Which version are you using?
Hi  SabaKauser 

I am using the "IBM Db2 on Cloud", and not very sure what is it's version. Should I download the " IBM Data Server Driver "?
A lot of people mentioned it on some websites. 

Regards 
Thx
