### ISSUE TITLE
Cloning IBM_DB Connection Object for Parallel connections

### ISSUE THREAD

**Issue by mrrameshch** [ibmdb/python-ibmdb#464]
Hi,

I created a connection object using IBM_DB Connect method. As we need to have separate connection objects to establish multi sessions to IBM DB2 , I am trying to create the new objects by copying/cloning the object that created earlier instead of calling IBM_DB connection method multiple times.

Created Connection object as - 
conn=ibm_db.connect(DBDsn,"","")

Then to create new objects, I am using deepcopy method using the copy module as below - 
**import copy as cp
con2 = cp.deepcopy(conn)**

When I try to run that script, it is failing with error as below -
    **con1 = cp.deepcopy(con)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle ibm_db.IBM_DBConnection objects**_**

Can some one suggest how to clone/copy an IBM_DB Connection object??

**Comment by SabaKauser** [comment]
we have ibm_db.pconnect() for persistent connections. see if that helps

**Comment by mrrameshch** [comment]
Giving same issues with IBM_DB.PCONNECT as well...

**Comment by SabaKauser** [comment]
What I meant is, pconnect API allows you to re-use connection objects. 
I am not sure if you can deepcopy or pickle the connection objects, I think there is more needed to achieve this, as far as I can see from other examples of deepcopy on extension objects. I am afraid we do not have that support in the driver.  May be try posting in python forums to see if others have done it.

**Comment by mrrameshch** [comment]
Thank you for your quick response....

Just one more question, is there any way in IBM_DB driver to check a particular PCONNECT object is in use at a particular moment?

I am thinking of creating a pool of PCONNECT objects so the scripts can use what ever available (PCONNECT object that is not in use) for updating in DB2...

If I don't have that functionality, more than one script may try to use same connection object and may fail.

**Comment by SabaKauser** [comment]
There is no such option, however, there is api to check if connection to db is active on a connection handle. 
ibm_db.active() might help in this case.
pconnect() maintains connection pool and returns active connection handle on a db/user/password combination unless you are doing something different with your own pool logic.

**Comment by SabaKauser** [comment]
do you need any more assistance on this?

**Comment by mrrameshch** [comment]
I am still working on this issue, can we keep it open for few more days??

**Comment by SabaKauser** [comment]
sure!

**Comment by SabaKauser** [comment]
please feel free to re-open
