### ISSUE TITLE
The database alias name or database name "" could not be found.

### ISSUE THREAD

**Issue by Trapican** [ibmdb/python-ibmdb#465]
Hi!

First of all, thanks for creating the package! We're currently stuck on getting the package to work (the last stage). We've managed to install it in a container and import the package, but when we connect it does not seem to properly pass the database name to the CLI Driver:

>>> ibm_db.connect('database=XXXX;hostname=XXXX;protocol=sockets;uid=XXXX;pwd=XXXX','','')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception: [IBM][CLI Driver] SQL1013N  The database alias name or database name "" could not be found.  SQLSTATE=42705 SQLCODE=-1013

Any ideas? Been stuck on this one for a while! ;-)

Jim

EDIT: Just to make sure. Instead of the database being XXXX, the text between quotes is actually empty ("")

**Comment by SabaKauser** [comment]
Hi,Thanks for using the driver.
the connection string is:
"database=dbname;hostname=machinename;port=portwheredb2islistening;protocol=tcpip;uid=username;pwd=password"

The connection samples are available here->https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbconnect

**Comment by SabaKauser** [comment]
Are you able to get past the error?

**Comment by SabaKauser** [comment]
I need to know if you are able to get through the connection.
