### ISSUE TITLE
CONNECT TO DB2 USING PYTHON

### ISSUE THREAD

**Issue by srinivasnadimpalli0818** [ibmdb/python-ibmdb#471]
Hello All,

I need a quick help.
I need to connect to DB2 database from python.
**i am getting error as AN attempt to connect to the database server failed because of a licensing problem**
As of now steps i have followed :
1: installed ibm_db using pip install ibm_db
2:python in linux environment and it is a 64 bit
3: As of now i am connecting to **db2 database remotely**

Should i install any other packages/driver on db2 client side?

Could any one please help me to this issue

**Comment by kadler** [comment]
https://github.com/ibmdb/python-ibmdb#-license-requirements-for-connecting-to-databases

**Comment by coolhost1252** [comment]
Hello All,

I need a quick help.
I need to connect to DB2 database from python.
i am getting error as AN attempt to connect to the database server failed because of a licensing problem
I need quick with clear solution

**Comment by SabaKauser** [comment]
Hi,
 If you have client side license file, just copy it under .../ibm_db/installer/clidriver/license folder.
You can get information on Db2 Connect license types here -> https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.qb.server.doc/doc/r0006748.html
and Check for db2con*. 

if you do not have a license and need to purchase one,, contact IBM support:
http://www-05.ibm.com/support/operations/zz/en/selectcountrylang.html

**Comment by coolhost1252** [comment]
thanks for the update 

still am facing same problem licences issue .

can you please recommend how to install ibm db and path setup ..
while export the libpath getting bash is not found and path is not available

please suggest

**Comment by SabaKauser** [comment]
the ibm_db installation by default will also install the clidriver under site-packages of your python.
To connect to z/OS, you need to have a license. The license file name is db2consv_zs.lic and ,ust be copied under <site-packages>/clidriver/license folder. Do you need have his license? or you want to purchase one?
The other type of license if server side license and you need to purchase db2connectactivate utility that will install the license at server for you.
 for bash error, you need to set the correct path to bash. On my machine it is under /bin/bash.

**Comment by coolhost1252** [comment]
thanks for help and supporting.
But am unable to locate clidriver/ license  folder please help on this

**Comment by SabaKauser** [comment]
how did you install ibm_db and is IBM_DB_HOME set in your machine

**Comment by SabaKauser** [comment]
I am waiting on this.

**Comment by coolhost1252** [comment]
its working now for me , i copied the db2 license ,
Thanks for your help and support.

**Comment by SabaKauser** [comment]
Thanks, 
closing
