### ISSUE TITLE
SQLCODE=-332 error 

### ISSUE THREAD

**Issue by rgopalan1** [ibmdb/python-ibmdb#473]
Hi,

I am trying to use the ibm_db package to connect to IBM DB2 server. I am able to connect to DB2, but when I try to execute the Stored Procedure I am getting the following error "SQLCODE=-332". I am not able to get detailed errors as well. Please help to resolve the issue.

Thanks,
Ramanujan

**Comment by IBMAmarPY** [comment]
Hi,
can you use ibm_db.stmt_errormsg() API and check the full error message.

**Comment by rgopalan1** [comment]
Hi,

Following is the code 
    try:
        ibm_db.execute(stmt)
        cols = ibm_db.num_fields(stmt)
        print(str(cols))
        for i in range(0, cols):
            field_name.append(ibm_db.field_name(stmt, i))
        print(field_name)
    except:
        print("SQLSTATE = {}".format(ibm_db.stmt_errormsg()))

Still I am getting only SQLCODE only.

**Comment by SabaKauser** [comment]
Hi,
Can you share traces.
cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files with us to assist you further.

collecting traces on MAC:
cd `clidriver install path`
cd adm
db2trc on -l 2m
<repro>
db2trc dump trc.dmp
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files

**Comment by rgopalan1** [comment]
Fixed the issue. By set the db2codepage at the client.
