### ISSUE TITLE
ascii codec error if column name contains Ñ

### ISSUE THREAD

**Issue by carlos-merida** [ibmdb/python-ibmdb#476]
> I was able to reproduce this. This seems to be a bug in QSQCLI handling of statement text coming in as UTF-8. It converts the text from UTF-8 to job CCSID, but uses the UTF-8 length instead of the converted length since it assumes a one-to-one byte mapping, which is not always the case with UTF-8.
> 
> You can work around this by padding the end with blanks for each extra byte of UTF-8 data.
> 
> ```python
> import os
> import subprocess
> import ibm_db_dbi
> 
> # Set job to CCSID 284 (Spanish)
> proc = subprocess.run(['getjobid', '-s', str(os.getpid())], stdout=subprocess.PIPE)   
> jobname = proc.stdout.decode().rstrip()
> proc = subprocess.run(['system', 'CHGJOB {} CCSID(284)'.format(jobname)], stdout=subprocess.PIPE)
> 
> 
> conn = ibm_db_dbi.connect()
> cur = conn.cursor()
> cur.execute('create table birthday(aÑo decimal(4,0))    ')
> 
> query = 'select aÑo from birthday'
> try:
>     cur.execute(query)
>     print('"{}" succeeded'.format(query))
> except ibm_db_dbi.ProgrammingError as e:
>     print('"{}" failed'.format(query))
>     print(e)
> 
> try:
>     query = query + ' '
>     cur.execute(query)
>     print('"{}" succeeded'.format(query))
> except ibm_db_dbi.ProgrammingError as e:
>     print('"{}" failed'.format(query))
>     print(e)
> ```
> 
> This gives me:
> 
> ```
> "select aÑo from birthday" failed
> ibm_db_dbi::ProgrammingError: BIRTHDA in KADLER type *FILE not found. SQLSTATE=42704 SQLCODE=-204
> "select aÑo from birthday " succeeded
> ```

How can I change the CCSID???

I try your code:

```
# Set job to CCSID 284 (Spanish)
proc = subprocess.run(['getjobid', '-s', str(os.getpid())], stdout=subprocess.PIPE)   
jobname = proc.stdout.decode().rstrip()
proc = subprocess.run(['system', 'CHGJOB {} CCSID(284)'.format(jobname)], stdout=subprocess.PIPE)
```

but I get error in first line:

FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

I'm trying in Anaconda enviroment in Windows.

Regards.

_Originally posted by @carlos-merida in https://github.com/ibmdb/python-ibmdb/issues/439#issuecomment-590585728_

**Comment by carlos-merida** [comment]
I still waiting a solution for this problem:

`df = pd.read_sql(query, con)`

This is the error:

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_dbi.py in __get_description(self)
   1035                 column_desc.append(ibm_db.field_name(self.stmt_handler,
-> 1036                                                           column_index))
   1037                 type = ibm_db.field_type(self.stmt_handler, column_index)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 1: ordinal not in range(128)

Client info:

DRIVER_NAME: string(10) "DB2CLI.DLL"
DRIVER_VER: string(10) "11.01.0303"
DATA_SOURCE_NAME: string(9) "ASMAYORAL"
DRIVER_ODBC_VER: string(5) "03.51"
ODBC_VER: string(10) "03.01.0000"
ODBC_SQL_CONFORMANCE: string(8) "EXTENDED"
APPL_CODEPAGE: int(1252)
CONN_CODEPAGE: int(1208)

Server Info:

Db2 database server name                 : AS
Database name                            : ASMAYORAL
Db2 instance name                        : ASMAYORAL
Database codepage used                   : 284

Remember, I'm connect from Anaconda in Windows to AS400 DB2 (ibm i).

Regards.

**Comment by theophilechevalier** [comment]
This is directly linked to #447 
@SabaKauser would you take a look? I'm willing to make a PR if you don't have enough bandwidth.

**Comment by SabaKauser** [comment]
@theophilechevalier , if you can make a PR, that would be great.

**Comment by bimalkjha** [comment]
@theophilechevalier Are you still facing this issue? We saw you have closed PR 478. Thanks.

**Comment by amukherjee28** [comment]
@theophilechevalier 
Do we have an update on this??

**Comment by amukherjee28** [comment]
Closing this issue. In the new release 3.1.1 Unicode character issue has been fixed. Please check with the latest version.
In case the issue persists please open a new issue.

**Comment by crisrivlop** [comment]
Hi i know this thread is already closed but i found an easy solution for this issue:
``` python
import ibm_db_dbi
Import ibm_db as db2

conn = ibm_db_dbi.connect()
query = 'select aÑo from birthday'
db2.exec_immediate(conn.conn_handler,query)
```
