### ISSUE TITLE
Support for db2 on zOS 

### ISSUE THREAD

**Issue by josiptolusic** [ibmdb/python-ibmdb#477]
Hi, are there plans for supporting db2 on zOS for IBM_db driver ?

**Comment by SabaKauser** [comment]
Hi, we support connection to z/OS using ibm_db driver. Is this what you meant?

**Comment by josiptolusic** [comment]
Hi Saba, I've been having issuses with installing this pacakge on AIX platform. The error I've recieved while trying to instal package is: Not a known platform for python ibm_db. So I've assumed that It's not supported.

**Comment by SabaKauser** [comment]
@josiptolusic , we support installation on aix. Can you provide the full error log, aix version. B.T.W, your issue title says 'z/OS'.

**Comment by josiptolusic** [comment]
Hi Saba, This is my whole output:
>python setup.py
Detected 64-bit Python
Not a known platform for python ibm_db

**Comment by SabaKauser** [comment]
can you give 'uname -a ' and 'oslevel' output. Also the python version you are using. 'python -V'
