### ISSUE TITLE
ibm_db_commit does't release GIL

### ISSUE THREAD

**Issue by Hogglo** [ibmdb/python-ibmdb#481]
In `ibm_db_commit()`, `SQLEndTran()` should be wrapped in `Py_BEGIN_ALLOW_THREADS` and `Py_END_ALLOW_THREADS` to allow the committing thread to release the Global Interpreter Lock (GIL). Db2 commits can potentially take a non-zero amount of time which can significantly impact commit's parallelism.

**Comment by SabaKauser** [comment]
Hello Zach,
Would you be opening a PR for this?

**Comment by SabaKauser** [comment]
@Hogglo  yes, please open.
