### ISSUE TITLE
Hi, does anyone know how to escape semicolon in the password?

### ISSUE THREAD

**Issue by cyuankai** [ibmdb/python-ibmdb#484]
I have one generated password, and it contains semicolon like ****;*****, which will cause the connect function always return, wrong password. 

I tried to use \, \", ", {} to escape it, but on use.

Please help and share your comments.

Thanks.

**Comment by SabaKauser** [comment]
I don't think ; is a valid character for Db2 connection password from clidriver. From infocenter :
https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.swg.im.dbclient.install.doc/doc/c0060749.html

```
Password rules for drivers and CLPPlus

Starting in Version 10.1 Fix Pack 2, the ODBC, CLI, .NET data provider, and the CLPPlus interface support password values containing the ASCII code range of 0x20 to 0x7E.
Support for this range of characters is subject to the following limitations:

    The ; character, ASCII code 0x3b, is not supported for use in passwords.
```

**Comment by cyuankai** [comment]
Thanks for answering.
