### ISSUE TITLE
Travis CI tests are failing

### ISSUE THREAD

**Issue by cclauss** [ibmdb/python-ibmdb#485]
https://travis-ci.org/ibmdb/python-ibmdb/builds

**Comment by imavo** [comment]
Why is this an issue with python ibm_db ?

**Comment by cclauss** [comment]
These Continuous Integration tests should tell us if the software should be trusted and  `ibmdb/python-ibmdb` has failed them for the past 10 months.

**Comment by imavo** [comment]
The tests have `docker pull ibmcom/db2express-c` , which has been withdrawn by IBM and replaced by the Db2 community edition,  so that part of the test script valid ?

**Comment by cclauss** [comment]
https://github.com/ibmdb/python-ibmdb/pull/488/files#diff-354f30a63fb0907d4ad57269548329e3R18 ?

**Comment by imavo** [comment]
What about the line `docker run --name db2  -p 50000:50000 -e DB2INST1_PASSWORD=password -e LICENSE=accept -d ibmcom/db2express-c db2start` which still mentions express-c ?
