### ISSUE TITLE
Secure connection to DB2 On ZOS

### ISSUE THREAD

**Issue by abhishek0102** [ibmdb/python-ibmdb#486]
Do we have properly documented steps for establishing secure connection using certificates (JKS or base64).

one which we have need to give more clear picture.

**Comment by SabaKauser** [comment]
Can you refer this
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.admin.sec.doc/doc/t0053518.html

python driver does not have anything more than the configuration settings needed by the underlying clidriver to establish secure connection to.
If that link does not help, let me know and I can guide your further.

**Comment by abhishek0102** [comment]
I have gone thru this link before.. couple of question.
1.  Do we need db2 client to be installed or IBM_DB will be sufficien.
2.  We need GSK8 only for KDB and STH generation  ?
3. can we install GSK8 on some other system and converts CA certs to CMS format  and use it ?

thanks alot for your help with this.

**Comment by SabaKauser** [comment]
>>>Do we need db2 client to be installed or IBM_DB will be sufficien.
If you did not set IBM_DB_HOME while installing ibm_db via pip, you do not need to have db2 client as the ibm_db driver installs it automatically under site-packages

>>>We need GSK8 only for KDB and STH generation ?
just pass the server certificate in sslservercertificate keyword in connection string, along with security=SSL. the db2 clidriver generates the kdb internally

>>>can we install GSK8 on some other system and converts CA certs to CMS format and use it ?
The client expects certificate in .arm format.

**Comment by abhishek0102** [comment]
We need GSK8 only for KDB and STH generation ?

just pass the server certificate in sslservercertificate keyword in connection string, along with security=SSL. the db2 clidriver generates the kdb internally

I have certificates in below format, can i pass this as sslservercertificate ?
Base64 (PKCS #8)
Base64 (OpenSSL)
DER
PKCS #7
Java Keystore (JKS)

**Comment by abhishek0102** [comment]
python code:-

print connection_details
tc_conn = ibm_db.connect(connection_details, "", "",)
print tc_conn

output:-

DATABASE=XXXXXX;HOSTNAME=XXXX.aaa.com;PORT=portno;PROTOCOL=TCPIP;UID=user;PWD=pwd;SSLServerCertificate=certificate.cer;SECURITY=ssl
Traceback (most recent call last):
  File Conn.py", line 27, in <module>
    tc_conn = ibm_db.connect(connection_details, "", "",)
Exception: [IBM][CLI Driver] CLI0157E  Error opening a file. SQLSTATE=HY507 SQLCODE=-99999

NON SSL connection working fine without certificates.

**Comment by SabaKauser** [comment]
give the full path to certificate.cer in SSLServerCertificate

**Comment by abhishek0102** [comment]
Yes, i have given full path only..

**Comment by SabaKauser** [comment]
In your example, its the relative path.

**Comment by SabaKauser** [comment]
can you pass the full path where you have the certificate.cer file and retry

**Comment by abhishek0102** [comment]
for comp privacy purpose i removed full path... I am using full path only..

**Comment by abhishek0102** [comment]
after correcting path- below is new error.
Traceback (most recent call last):
  File "C:/Conn.py", line 27, in <module>
    tc_conn = ibm_db.connect(connection_details, "", "",)
 SQLCODE=-30081

**Comment by SabaKauser** [comment]
your server is not reachable. check the ip address or host name passed to hostname parameter and the port number for SSL connection the server is configured to listen to.

**Comment by abhishek0102** [comment]
DATABASE=DB2BSEC1;HOSTNAME=DB2BSEC1.fmr.com;PORT=8900;PROTOCOL=TCPIP;UID=WSPDBA1;PWD=********;SSLClientKeystoredb=/home/a486637/key.kdb;SSLClientKeystash=/home/a486637/key.sth;SECURITY=ssl
Traceback (most recent call last):
  File "conn.py", line 32, in <module>
    tc_conn = ibm_db.connect(connection_details, "", "",)
Exception: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001 SQLCODE=-30081


We see below as database log-
DSNL511I  D*** DSNLIENO TCP/IP CONVERSATION FAILED  073      
           TO LOCATION ::***************                        
           IPADDR=::********* PORT=******
           SOCKET=RECV RETURN CODE=1121 REASON CODE=77A9733D

Question - How do we run SSL trace here ?
same user name and password work for db2connect unsercured connection.
i have ran db2trc.. i pretty much get same information over there...

**Comment by abhishek0102** [comment]
same certificate works fine for java connection - JKS version

**Comment by SabaKauser** [comment]
Hi,
The error 414 states this:
GSKit: 414

This return code indicates that an incorrectly formatted certificate was received from the partner in an SSL relationship.
This error can be returned in these scenarios:

    You are using self-signed certificates and the certificate is missing.
    The certificate that is being used is from a local certificate authority that does not have the Basic Constraints extension active. 

To run SSL trace:
1) export GSK_TRACE_FILE=/home/a486637/gsknobuffer.log
2)export GSKTRACE_NOBUFFERING=YES 
2) Run the repro 
3) you should be able to see gsknobuffer.log

**Comment by SabaKauser** [comment]
any update on this?

**Comment by bimalkjha** [comment]
@abhishek0102 When you reported this issue, only certificate file with .arm extension was accepted by SSLServerCertificate keyword. The latest clidriver which get installed with ibm_db supports all formats of certificate file with SSLServerCertificate keyword. So, this issue should be fixed now. Please reopen the issue if you are still facing any connectivity issue. Thanks.

**Comment by abhishek0102** [comment]
Hi
