### ISSUE TITLE
Supports IAM authentication for Db2 on IBM Cloud

### ISSUE THREAD

**Issue by shawnzhu** [ibmdb/python-ibmdb#487]
## Background

For those Db2 provisioned on IBM Cloud, it supports IAM authentication besides user/password. see [Identity and access management (IAM) on IBM Cloud - Db2 warehouse on Cloud](https://www.ibm.com/support/knowledgecenter/en/SS6NHC/com.ibm.swg.im.dashdb.security.doc/doc/iam.html):

> The following methods can be used for IAM authentication:
> * Access token
> * API Key
> * IBMid/password

## Expected result

It should allow setting API key in the connection string like:

```Python
conn_str = 'DATABASE={};HOSTNAME={};PORT={};PROTOCOL=TCPIP;SecurityTransportMode=SSL;APIKEY={};' \
    .format(
        'BLUDB',
        'db-hostname',
        50001,
        apikey
    )
conn_handler = ibm_db.connect(conn_str, '', '')
```

It should be able to connect to Db2 server w/ valid API Key

## Actual result

When running python code that connecting to Db2 using API Key, I got:

```
Exception: [IBM][CLI Driver] SQL30082N  Security processing failed with reason "17" ("UNSUPPORTED FUNCTION").  SQLSTATE=08001 SQLCODE=-30082
```

Which indicates that it misses user or password.

**Comment by SabaKauser** [comment]
I don't think its saying "user id or password". Reason code 17 says "authentication type not supported".
You need to set Security=SSL and Authentication=GSSplugin.
SecurityTransportmode is a db2dsrdriver.cfg keyword.
Security is connection string equivalent.

security -> https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/r0054667.html
Authentication -> https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.swg.im.dbclient.config.doc/doc/r0054601.html

Try and let me know your results.

**Comment by shawnzhu** [comment]
Given:

```Python
import ibm_db
import ibm_db_dbi

conn_str = 'DATABASE={};HOSTNAME={};PORT={};PROTOCOL=TCPIP;Security=SSL;Authentication=GSSplugin;APIKEY={};' \
    .format(
        'BLUDB',
        'db-hostname',
        50001,
        os.environ['IBMCLOUD_APIKEY']
    )

conn_handler = ibm_db.connect(conn_str, '', '')
conn = ibm_db_dbi.Connection(conn_handler)
```

I've got the same error message:

```
Exception: [IBM][CLI Driver] SQL30082N  Security processing failed with reason "17" ("UNSUPPORTED FUNCTION").  SQLSTATE=08001 SQLCODE=-30082
```

**Comment by SabaKauser** [comment]
Is it possible for you to collect db2 traces.
cd `clidriver install path`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files

**Comment by shawnzhu** [comment]
@SabaKauser I didn't use db2cli at all nor `db2trc`. would you please provide more information about how to get these tool and a working example?

A simple question is, does API key authentication ever supported by this package at all?

**Comment by SabaKauser** [comment]
@shawnzhu , yes , API key is supported by driver for Db2 on cloud. The driver will be available under <python's site-packages location>/clidriver . Will it be possible for you cd to this directory?

**Comment by shawnzhu** [comment]
@SabaKauser I've provided asked files from https://github.com/ibmdb/python-ibmdb/issues/487#issuecomment-604304666 to https://gist.github.com/shawnzhu/d41ab982d1ea1306f4b29d9d547b4504

**Comment by SabaKauser** [comment]
Hi, 
I see you have uploaded only flw file. I need all files, 
trc.flw, trc.fmt, trc,cli and trc.fmtc

**Comment by shawnzhu** [comment]
@SabaKauser I've updated the gist with 4 required files.

**Comment by shawnzhu** [comment]
I've noticed that the clidriver was trying to locate this file: `/root/.local/share/virtualenvs/kzhu-ZXUKUG7_/lib/python3.8/site-packages/clidriver/security64/plugin/IBM/client/IBMIAMauth.so`. see line 38774 from `try.fmt`:

> 3940	data DB2 UDB bsu security findPluginPath fnc (3.3.92.236.0.250)
	pid 568 tid 139720562440000 cpid -1 node -1 probe 250
	bytes 133
>
>	Data1 	(PD_TYPE_STRING,125) String:
	/root/.local/share/virtualenvs/kzhu-ZXUKUG7_/lib/python3.8/site-packages/clidriver/security64/plugin/IBM/client/IBMIAMauth.so

> 3941	entry DB2 Common OSSe ossPathTest cei (1.1.3.156.2)
	pid 568 tid 139720562440000

I could not find this file after installing python package `ibm-db`.

**Comment by shawnzhu** [comment]
@SabaKauser I can confirm that file is missing from upstream cli_driver package at `https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz` so this is really not a problem of this package. do you know if there's any channel to get this fix delivered to the ODBC driver package?

**Comment by SabaKauser** [comment]
great! thanks for the analysis.  . I will check from ODBC driver side and I will get back to you on this.

**Comment by data-henrik** [comment]
What is the status?

**Comment by shawnzhu** [comment]
@data-henrik the current status in my side is https://github.com/ibmdb/python-ibmdb/issues/487#issuecomment-608095608

**Comment by torsstei** [comment]
@SabaKauser Any news?

**Comment by SabaKauser** [comment]
I have worked with the site owner and got the package with the IAM lib uploaded. Please re-install ibm_db driver for it to install this clidriver image freshly.

**Comment by data-henrik** [comment]
@SabaKauser I can confirm that I can connect to Db2 on Cloud using an APIKEY. I used the panda-based example here: https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbexec_immediate

BTW: Please change the snippet to `import pandas as pd` for the pd reference later on.

**Comment by SabaKauser** [comment]
@data-henrik , thanks. Changes done to document. I assume this can be closed. Please confirm.

**Comment by data-henrik** [comment]
ok from my side, but I didn't open the defect. :)

**Comment by SabaKauser** [comment]
@shawnzhu until you say ok, I will keep this open :)

**Comment by data-henrik** [comment]
The following works as Cloud Function when using the updated driver:
```
import ibm_db
import pandas as pd
import ibm_db_dbi as dbi
import json,sys,os
import requests,base64

def db2test(iamKey):
    connstr="DATABASE=BLUDB;Authentication=GSSplugin;HOSTNAME=db2oncloud-server-uri;PORT=50001;PROTOCOL=TCPIP;SECURITY=SSL;APIKEY="+iamKey+';'
    conn1 = dbi.connect(connstr)
    df = pd.read_sql("select count(*) from syscat.tables", conn1)
    return df.to_json(orient='split')    

def main(args):

    # use iam key if passed in, personal iam key otherwise
    iamKey = args.get("IAM_KEY") or os.environ.get('__OW_IAM_NAMESPACE_API_KEY')
    db=json.loads(db2test(iamKey))

    return { **args, **db}
```

**Comment by shawnzhu** [comment]
I can verify it works with IAM authentication when using `ibm-db==3.0.1`.

and I can see `IBMIAMAuth.so` is here:

```
$ /usr/local/lib/python3.8/site-packages/clidriver# ls security64/plugin/IBM/client/
IBMIAMauth.so  IBMkrb5.so  IBMkrb5.so.1
```

@SabaKauser @data-henrik Thank you!
