### ISSUE TITLE
 ibm_db.callproc returns None if OUT parameter is SMALLINT and the value is zero

### ISSUE THREAD

**Issue by hachi0727** [ibmdb/python-ibmdb#489]
[Problem summary]
We are using IIAS 1.0.16(db2_main_prod s1902271200) or IIAS 1.0.21 (db2_main_prod
s2002071700).
When we execute a stored procedure that returns zero as OUT parameter with ibm_db.callproc API, the return value is handled as None (not zero).

[bluadmin@node0101-fab - Db2wh TEST]$ python --version
Python 2.7.13

[bluadmin@node0101-fab - Db2wh TEST]$ pip show ibm_db | grep Version
:
Version: 2.0.8

[bluadmin@node0101-fab - Db2wh TEST]$ db2 -td@ -vf test.ddl
CREATE OR REPLACE PROCEDURE TEST379(
     IN IN1   BIGINT
    ,IN IN2   INTEGER
    ,OUT O_RETURN SMALLINT
 )
BEGIN
   DECLARE C_RET_OK        SMALLINT   CONSTANT 0;
   DECLARE C_RET_EXCEPT      SMALLINT   CONSTANT -1;
SET O_RETURN = C_RET_OK;
RETURN;
END

DB20000I  The SQL command completed successfully.

[bluadmin@node0101-fab - Db2wh TEST]$ cat test.py
import os
import sys
import ibm_db
v_conn = ibm_db.connect("BLUDB", "bluadmin", "xxxxxxxx")
if v_conn:
  v_stmt, v_id, v_aa, v_ret  = ibm_db.callproc(v_conn, "TEST379",(1,1,99))

  if v_ret is not None:
     print(v_ret) 
  else:
     print("v_ret is None")
ibm_db.close(v_conn)

[bluadmin@node0101-fab - Db2wh TS003482379]$ python test.py
v_ret is None

This issue does not occur if we use BIGINT instead of SMALLINT.

[bluadmin@node0101-fab - Db2wh TS003482379]$ db2 -td@ -vf test.ddl
CREATE OR REPLACE PROCEDURE TEST379(
     IN IN1   BIGINT
    ,IN IN2   INTEGER
    ,OUT O_RETURN BIGINT
 )
BEGIN
   DECLARE C_RET_OK        SMALLINT   CONSTANT 0;
   DECLARE C_RET_EXCEPT      SMALLINT   CONSTANT -1;
SET O_RETURN = C_RET_OK;
RETURN;
END

DB20000I  The SQL command completed successfully.

[bluadmin@node0101-fab - Db2wh TS003482379]$ python test.py
0

Is this a known issue or known limitation?
When is it fixed?

**Comment by hachi0727** [comment]
Could you please take a look at this issue?

**Comment by SabaKauser** [comment]
Hi, I am able to reproduce the problem.
I have a fix and it will go in next release.

**Comment by SabaKauser** [comment]
I will push to git master. If you are on linux, you can try building yourself. 
just download the package, cd to directory  until you see ibm_db.c and issue:
pip install .  (note the dot).

if you want the fix in any other way, let me know.

Thanks!
