### ISSUE TITLE
Exception message differs on python3

### ISSUE THREAD

**Issue by kotofos** [ibmdb/python-ibmdb#497]
Hi,
during migration to python3 of the project where we use ibmdb I found that exception message changed. This change was caught by our autotests.
After some digging found the reason: `repr(Exception('msg'))` produces a different result on python3.

```
>>> repr(Exception('msg'))
# python2: "Exception('msg',)"
# python3: "Exception('msg')"
```

issue is in the _get_exception function. See https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/ibm_db_dbi.py#L369

Code to reproduce: 
```
from ibm_db_dbi import _get_exception

res = _get_exception(Exception('test'))

print(res)
# python2 output: ibm_db_dbi::Error: test
# python3 output: ibm_db_dbi::Error: Exception('test')
```

Expected behavior:
same message as in python2 `ibm_db_dbi::Error: test`

**Comment by SabaKauser** [comment]
@kotofos I see you closed the PR. Any reason?

**Comment by kotofos** [comment]
I reopened it right away to change branch.
