### ISSUE TITLE
execute_many() does not check correctly for errors, throws CLI0126E.

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb#499]
ibm_db.execute_many does not check correctly for errors, throws CLI0126E.

When a multi-row insert runs with ibm_db_execute_many,
any data exception (for example CLI0111E etc. ) is not
reported, but  CLI0126E is reported instead.

The only way you can see what is really wrong is to examine a CLI trace.

See example  code below which recreates the symptom with deliberate bad data.
Found using ibm_db version 3.0.1 and odbc/cli driver.

The ibm_db.execute does not show this symptom, because it checks for SQL_ERROR etc following the SQLExecute() call.

The code in ibm_db.c for ibm_db.execute_many does not correctly
check for errors following the SQLExecute() call. 

Example code below
-------------------------------------------
```
import sys
import ibm_db

def fetch(stmt):
    result=[]
    row=ibm_db.fetch_tuple(stmt)
    while row:
        result.append(row)
        row=ibm_db.fetch_tuple(stmt)
    return result

    
connection=ibm_db.connect("DATABASE=sample;HOSTNAME=localhost;PORT=50100;PROTOCOL=TCPIP;UID=xxxxx;PWD=xxxxxxxxxxxx", "", "")

TABLES = fetch(ibm_db.exec_immediate(connection, "select TABNAME from syscat.tables where tabname='CLI0126E' and tabschema = current user"))
if not TABLES:
    create_ddl="CREATE TABLE CLI0126E \
        (\
            offer_id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\
            position_id int NOT NULL,\
            title VARCHAR(5000) NOT NULL,\
            type VARCHAR(5000),\
            quantity decimal(10, 3) NOT NULL,\
            price_btc decimal(10, 8) NOT NULL,\
            city VARCHAR(5000),\
            country VARCHAR(500)\
        )"
    try:
        ibm_db.exec_immediate(connection, create_ddl)
        print("Created table CLI0126E - OK")
    except:
        print("Failed to create the target table")
        print(ibm_db.stmt_errormsg())
        sys.exit(1)
    
      
insert_statement = "INSERT INTO CLI0126E (position_id, title, type, quantity, price_btc, city, country)\
VALUES (?, ?, ?, ?, ?, ?, ?)"
    
stmt = ibm_db.prepare(connection, insert_statement)

# deliberately use wrong size decimal values to trigger CLI0111E (hidden by execute_many()).
# 
parms1= (15628, 'Витебск (Беларусь)', '', 99999999.0, 0.0067762, 'Витебск', 'Belarus')
parms2= (15629, 'Витебск (Беларусь)', '', 1999999.0, 0.0067762, 'Витебск', 'Belarus')
parms=( parms1 , parms2)
try:
    ibm_db.execute_many(stmt, parms)
    print(str(ibm_db.num_rows(stmt)) +" - Rows inserted successfully")
except:
    print("Failed to insert multiple-rows with ibm_db.execute_many()")
    print(ibm_db.stmt_errormsg())
    print("Number of rows inserted: "+ str(ibm_db.num_rows(stmt)) + " - Expected: 2")
    sys.exit(1)

ibm_db.close(connection)
```

**Comment by SabaKauser** [comment]
@imavo I haven't had enough time to reproduce the problem you are facing. I will let you know once I have made some analysis with it.
Thanks!

**Comment by SabaKauser** [comment]
@imavo thanks for the repro. I have fixed the problem and it now correctly reports the error.
Failed to insert multiple-rows with ibm_db.execute_many()
[IBM][CLI Driver] CLI0111E  Numeric value out of range. SQLSTATE=22003 SQLCODE=-99999
Number of rows inserted: 1 - Expected: 2

I will push the code and might add a testcase as well.

**Comment by imavo** [comment]
Thank you I look forward to seeing the new code and the testcase.
