### ISSUE TITLE
Not able to connect DB2 using python

### ISSUE THREAD

**Issue by Sushmita-24** [ibmdb/python-ibmdb#500]
DB = "DATABASE=" + config.get('BMS', 'DATABASE') + ";HOSTNAME=" + config.get('BMS', 'HOSTNAME') +";PORT=" + config.get('BMS', 'PORT') + ";PROTOCOL=TCPIP;UID=" + config.get('BMS', 'UID') + ";PWD=" + config.get('BMS','PWD') + ";"
conn = ibm_db.connect(DB, "", "")
conn1 = ibm_db_dbi.Connection(conn)

this is giving error:
    conn = ibm_db.connect(DB, "", "")
 SQLCODE=-1598

**Comment by imavo** [comment]
This is a frequently asked question. This is not a problem of ibm_db or python.
Instead it is a licence file issue.
SQLCODE=-1598  , also known as SQL1598N
You cannot connect to Db2-for-Z/OS   or  Db2-for-i   **via the IBM CLI driver** *unless* you have a licence file , or unless you connect via a Db2-Connect gatweay.
The action you must take depends on whether you are connecting to AS/400 (Db2 for i-series), or Db2-for-Z/OS but you don' mention this in your question.

**Comment by Sushmita-24** [comment]
I am connecting for Z/OS

**Comment by imavo** [comment]
Ask your Z/OS DBA team if there is a Db2-connect-gateway you can use (that means you don't need a licence file). Otherwise get a license file and deploy it according to IBM's instructions. This has nothing to do with python. 
This issue #500 should be closed.

**Comment by Sushmita-24** [comment]
Thanks alot.
