### ISSUE TITLE
travis_ci 'build fail' due to bad test_InsertRetrieveDateTimeTypeColumn.py

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb#501]
Currently the tests on python ibm_db are failing on **travis_ci**
resulting in a **_'build fail'_** status.

The reason is that **test_InsertRetrieveDateTimeTypeColumn.py**
has a mistake on the line :
`if (server.DBMS_NAME == 'DB2/NT64'):`

Evidently this part of the test is written to operate only on Microsoft-Windows.

The travis_ci tests happen in a linux docker container, so the test fails
because the expected results require that the above test returns true.

A limited workaround is to use instead:
`if (server.DBMS_NAME == 'DB2/NT64' or server.DBMS_NAME == 'DB2/LINUXX8664'):
`
But if the tests must complete on **AIX** or **z/Linux** or other flavours of Unix then a different solution is required, although it is unclear why this part of the test is conditional.

**Comment by kadler** [comment]
I suspect that the test is applicable to _all_ Db2 _LUW_ servers, so just check if `server.DBMS_NAME.startswith('DB2/')`

**Comment by imavo** [comment]
Not sure what gets reported for the DBMS_NAME for  Db2-for-Z/os  and Db2-for-i  ,

**Comment by kadler** [comment]
See https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/testfunctions.py#L89-L96
