### ISSUE TITLE
Connection time out

### ISSUE THREAD

**Issue by jaydipdangariya** [ibmdb/python-ibmdb#503]
Hi Team,

We need your input regarding connection pool

1) What is the optimal size of connection poot to get best performance?
2) What is the pool.setConnectTimeout() parameter it ie minute or second or millisecond?
3) What is the optimal value we can set in setConnectTimeout() function parameter?

Please provide your input

**Comment by imavo** [comment]
1. Currently the ibm_db (at v3.0.1) keeps persistent connections in an internal dictionary object.  Your python code does not directly set the size, this happens indirectly as more persistent connections are requested that cannot be satisfied from those already allocated by the module.

2. The unit is SECONDS (refer to the IBM [documentation](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0021533.html) for details of the parameter)

3. Depends on the path between python and your Db2-server and how busy/resource-rich is your Db2-server. The more complex the path, and least well provisioned Db2-server, or more-busy the Db2-server,  the longer you should allow. This is something that you measure in your own environment. However, if an end-user is (indirectly) waiting for a reply then shorter timeouts give the illusion of more being responsive.

**Comment by jaydipdangariya** [comment]
Thank you for your quick reply

Bassically, 
We are using node js application to connect db2 database and we are using connection pool 
We pool.setMaxPoolSize(25); So, is this optimal pool size?
And if we are not set any connection time out unit then what is default value?

Thank You,

**Comment by imavo** [comment]
Why are you asking about node.js module on the python ibm_db issues page?
