### ISSUE TITLE
Linux CLI driver was gone

### ISSUE THREAD

**Issue by killuazhu** [ibmdb/python-ibmdb#504]
Having trouble to pip install ibm-db on Linux platform

Getting 500 error when pip was trying to download <https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz>

Look into the driver directory, the linux driver was gone...

![image](https://user-images.githubusercontent.com/63790/80225812-99271080-8619-11ea-822e-985252eafa12.png)

Please help fix this, this is blocking the proper installation of db2 linux driver.

**Comment by killuazhu** [comment]
Hmm... this might be a timing issue, now the linux driver appears again.. can we make the driver update less intrusive?

**Comment by imavo** [comment]
Why do you think this is an issue for python ibm_db module?

**Comment by killuazhu** [comment]
ibm_db can't be installed properly if its dependency was not available. Based on the [code](https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/setup.py#L192) below, it's trying to download the driver from public.dhe.ibm.com

> url = 'https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/' + cliFileName

I don't know who manages the upstream site public.dhe.ibm.com and where to report issue. From ibm_db user's perspective, this repo seems to be the most appropriate place to report.

**Comment by imavo** [comment]
Tempoary website operational issues on external IBM websites are outside the scope of this python ibm_db module purview.   Just retry.

**Comment by SabaKauser** [comment]
reference #505
