### ISSUE TITLE
Question - 32bit IBM DB2 drivers with 64bit Python 3.6

### ISSUE THREAD

**Issue by daqieq** [ibmdb/python-ibmdb#506]
Hi team,

Just looking to see if this package (ibm-db) can work with our enterprise 'base' environment that uses the 32bit IBM DB2 windows drivers (e.g. db2cli.dll instead of db2cli64.dll).

Is it possible "out of the box" by changing an installation parameter? Or would we need to change the source code (e.g. [Line 52 of ibm_db.c](https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/ibm_db.c#L52)) and recompile?

Thanks!

**Comment by kadler** [comment]
You can't use 32-bit drivers with a 64-bit applications (ie. Python).
