### ISSUE TITLE
SQL commands in SQLRPGLE programs causing ibm_db.connect to fail for new connections

### ISSUE THREAD

**Issue by edmundpf** [ibmdb/python-ibmdb#507]
This is a strange issue that I've come across:

I'm calling SQLRPGLE programs using the iToolkit library, for some reason when I call a program that has SQL statements like select, insert, etc. the connection is somehow being locked and other users intermittently cannot connect and the ibm_db.connect method fails and returns None. I'm not sure if anyone had a similar issue and I realize the issue comes from calling a different library but the stack trace fails in this method, any help would be greatly appreciated!

Thanks in advance

**Comment by kadler** [comment]
Are you running on IBM i? If so, you may want to open an issue at [my repo](https://github.com/kadler/python-ibmdb/) as I maintain the IBM i fork. Alternatively, due to the interaction with itoolkit, you could open an issue over at https://github.com/IBM/python-itoolkit which I also maintain.

**Comment by edmundpf** [comment]
> Are you running on IBM i? If so, you may want to open an issue at [my repo](https://github.com/kadler/python-ibmdb/) as I maintain the IBM i fork. Alternatively, due to the interaction with itoolkit, you could open an issue over at https://github.com/IBM/python-itoolkit which I also maintain.

Yes I'm running on the IBMi, I'll open an issue there thank you
