### ISSUE TITLE
Getting error while trying to import ibm_db.

### ISSUE THREAD

**Issue by engineerpassion** [ibmdb/python-ibmdb#510]
Getting the following error while trying to import the library:

```
    import ibm_db
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ibm_db.cpython-36m-darwin.so, 2): Library not loaded: libdb2.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ibm_db.cpython-36m-darwin.so
  Reason: image not found
```

The fix suggested here https://github.com/ibmdb/python-ibmdb/tree/master/IBM_DB/ibm_db#issues-with-mac-os-x is also not working for me.

**Comment by SabaKauser** [comment]
did you try setting DYLD_LIBRARY_PATH?
Also can you give me output of :
otool -L  /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ibm_db.cpython-36m-darwin.so

**Comment by engineerpassion** [comment]
@SabaKauser I was able to resolve the issue by adding the following in my environment:

export DYLD_LIBRARY_PATH="/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/clidriver/lib"

I've seen many people facing this issue, can this be taken care of while installing the library itself?

**Comment by SabaKauser** [comment]
@engineerpassion I have delivered a fix to master just now. It should be available in next release.
Thanks! closing.
