### ISSUE TITLE
Secure connection to DB2 warehouse on cloud (SSL)

### ISSUE THREAD

**Issue by reddibhatini** [ibmdb/python-ibmdb#511]
This is in linux.
I got the server certificate from webconsol of db2 warehouse on cloud.

Can someone please help me in connecting to db2 using ssl.

conn=ibm_db.connect("DATABASE=dbname;HOSTNAME=hostname;PROTOCOL=TCPIP;UID=username;PWD=password;SSLServerCehostnrtificate=/location/to/DigiCertGlobalRootCA.crt;SECURITY=SSL;", "", "")

Error:
[FAILED]: [IBM][CLI Driver] SQL0902C  A system error occurred. Subsequent SQL statements cannot be processed. IBM software support reason code: "".  SQLSTATE=58005

**Comment by SabaKauser** [comment]
Hi,
How did you install ibm_db? Did you set IBM_DB_HOME environment variable before installing?

**Comment by imavo** [comment]
Is there a typo in your connection string?  Instead of `SSLServerCehostnrtificate=` please try **SSLServerCertificate=** .

**Comment by SabaKauser** [comment]
Is this resolved?

**Comment by imavo** [comment]
Last time that I tried to connect with SSL/TLS with ibm_db and clidriver, to Db2-on-cloud, it worked correctly for me. I assume the user who created the question made a configuration mistake.  (There should be no difference connecting to Db2-on-premises,  Db2-on-cloud,  and Db2-warehouse-on-cloud __as regards SSL/TLS__ client side configuration, other than connectivity details).

**Comment by SabaKauser** [comment]
Closing. re-open if required.

**Comment by SahooAshis** [comment]
> Last time that I tried to connect with SSL/TLS with ibm_db and clidriver, to Db2-on-cloud, it worked correctly for me. I assume the user who created the question made a configuration mistake. (There should be no difference connecting to Db2-on-premises, Db2-on-cloud, and Db2-warehouse-on-cloud **as regards SSL/TLS** client side configuration, other than connectivity details).

Hi Can you please let me know step by step how to connect to IBM DB2 on cloud?
