### ISSUE TITLE
Image files in ibm_db_tests/

### ISSUE THREAD

**Issue by davidmmooney** [ibmdb/python-ibmdb#512]
Some of the unit tests (000, 045, 048) rely on the existence of external files (`pic1.jpg`, `spook.png`) that get stored and retrieved from a database. These files used to exist in the` tests/` directory, but were removed as part of c6fe669.

These missing files cause unit tests 000, 045, and 048 to fail when run locally. They run cleanly in the CI pipeline because `.travis.yaml` summons them into existence.
```yaml
# These were deleted from git, but required by the tests
# we just create dummy files of the size expected
- truncate -s 10291 ibm_db_tests/spook.png
- truncate -s 15398 ibm_db_tests/pic1.jpg
```
I would like to submit a PR to fix this so the unit test will run clean locally. I can do this by

* Re-adding the pic1.jpg and spook.png files to the codebase, or
* Moving the creating of the files from `.travis.yaml` into `tests.py`.

Do you have a preference for how I should do it? Can you share some insight into why the files were removed in the first place?

**Comment by SabaKauser** [comment]
Hello David, the files were removed as part of some code scan activity when these were part of IBM Db2 Connect packaging. I think we can add these files back as we no more package python driver with Db2 connect, but I will have this confirmed from legal perspective.
Thanks!

**Comment by davidmmooney** [comment]
I've submitted #514, with the original image files in place.

**Comment by kadler** [comment]
Personally, I think the tests should be re-written to not require files anyway. The tests could generate random bytes in memory.

**Comment by SabaKauser** [comment]
@davidmmooney I confirmed that we cannot have these data files added back.
