### ISSUE TITLE
Unable to install ibm_db, tried several ways

### ISSUE THREAD

**Issue by abachurin** [ibmdb/python-ibmdb#517]
I have MAC OS Catalina 10.15.4. I have Python 3.8 and initially thought the problem is this is too new. So i installed 3.6.5 as well. Still get the same error when i try to do
pip3 install ibm_db
I get:
ERROR: Command errored out with exit status 1: /Users/aleksej/PycharmProjects/sql/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = ... et cetera.
I googled the Error type and tried to use Homebrew, as it seems to work for other stuff in this situation. Here i get a simpler error:
Error: No available formula with the name "ibm_db"
So, what should i do? I am trying to pass a short IBM course on SQL on Coursera. IOt is supposed i should have no problem installing ibm_bd library.

**Comment by SabaKauser** [comment]
ibm_db is not available for installation from package manager. Its available for install from pypi( i.e pip) or build from the source(using setup.py).
Can you provide the full log of install.

**Comment by abachurin** [comment]
First python version check:
(venv) aleksej@AB sql % python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
now, just to check, i try:
pip3 install numpy - all fine, numpy installed.
now i try:
pip3 install ibm_db
get the aforementioned error with the log attached
[ibmdb_log.txt](https://github.com/ibmdb/python-ibmdb/files/4721542/ibmdb_log.txt)

**Comment by abachurin** [comment]
Ok, if anybody encounters this - i solved the issue. The root of the problem and the solution is described in the first answer:
https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa
