### ISSUE TITLE
Bug when using aggregation and 'case..when..' in select clause

### ISSUE THREAD

**Issue by wenxiaofoo** [ibmdb/python-ibmdb#518]
When I am operating the following query (say, query1):
```
select sum(case when column = 'Basic' then 1 else 0 end) as #basic,
       sum(case when column = 'CAA' then 1 else 0 end) as #caa
from table
```
My python script returns:
   _#BASIC   #CAA
       0               0_
where it should return (using db2 command line):
_#BASIC      #CAA       
----------- -----------
         43          18_

My python script is running normally on other query, so I think this is a bug from the driver.
If the query is written in this way (say query2):
```
select #basic, #caa
from (select count(column) as #basic
from table M where  club = 'Basic') as M,
(select count(column) as #caa
from table M where  club = 'CAA') as N
```
it has the same problem with query1.
If the query is written in this way (say query3):
```
select M.basic as #Basic, N.caa as #CAA
from (select count(*) as basic from table m where column= 'Basic' group by column) as M,
(select count(*) as caa from table n where column = 'CAA' group by column) as N
```
it returns 0 tuples.
Both query2 and query3 return correct answer when performing in db2 command line directly.

**Comment by SabaKauser** [comment]
python ibm_db driver does not parse or process the input DML but passes as is to server for processing. And the results are provided back to the application as received from server.
Although this is out of scope of python driver, I can still take a look at the traces to confirm the data returned by server in failing case. 
I also need traces for success case (command line for same query). 
Trace on one query is sufficient.

to collect traces:
Linux/Unix/Windows:
cd `clidriver install path, found under site-packages of ibm_db install location`
cd adm
db2trc on -f trc.dmp
`run your application`
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli

Mac:
cd `clidriver install path`
cd adm
db2trc on -l 2m
<repro>
db2trc dump trc.dmp
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share the trc.flw, trc.fmt, trc.fmtc and trc.cli files

**Comment by SabaKauser** [comment]
Have you been able to collect traces?
