### ISSUE TITLE
Without the IBM Data Server Driver, but odbc cli will be ERROR

### ISSUE THREAD

**Issue by IvanaXu** [ibmdb/python-ibmdb#520]
```
Uses the IBM Data Server Driver for ODBC and CLI APIs to connect to IBM DB2 and Informix.
```

I have a machine with the IBM Data Server Driver, odbc cli and ibm_db 3.0.1;

I have to copy the environment into a not internet machine, but without the IBM Data Server Driver

*ERROR:** import ibm_db succcessful,but ibm_db.connection("","","") wait for a long time*

**Comment by imavo** [comment]
You can download the clidriver for your platform+bitness , copy the downloaded file to the offline machine, install clidriver to a suitable directory. Then in the same shell session set (and export if linux/unix) IBM_DB_HOME variable as described on the README page of this python-ibmdb component, and then install the ibm_db module while that variable is set.  The ibm_db module will then use your offline installed clidriver.

**Comment by imavo** [comment]
@IvanaXu , if you are able to load and run the ibm_db module with a pre-installed clidriver, please can you close this issue.

**Comment by IvanaXu** [comment]
Nice
