### ISSUE TITLE
CLI0109E String data right truncation when calling EXPLAIN_FROM_SECTION procedure

### ISSUE THREAD

**Issue by czz829** [ibmdb/python-ibmdb#526]
I'm calling explain_from_section via callproc and passing in input parameter executable_id (varchar32 for bit data) as hex string, but hit CLI0109E error. I get executable_id from mon_get_pkg_cache_stmt by selecting its hex format.  It's something like 
0100000001000000978007000000000000000000020020200624140016285192, I then add 0x as hex prefix to pass in to the procedure. 

I also tried passing in as byte array (calling bytes.fromhex()), it didn't throw any error, but the procedure didn't work either as no explain information was populated into the explain tables.

What is the correct way to pass in procedure parameter as varchar32 for bit data?

Thanks for the help.

**Comment by SabaKauser** [comment]
Hi,
I have this example and it works just fine for me.
result = ibm_db.exec_immediate(conn, """CREATE PROCEDURE out_blob(IN P1 varchar(32) for  bit data,OUT P2 varchar(32) for bit data)
LANGUAGE SQL
DYNAMIC RESULT SETS 0
BEGIN
SET P2 = P1;
END""")

stmt, blob1, blob2 = ibm_db.callproc(conn, 'out_blob', (b'123456',b'0'))

if stmt is not None:
    print("Values of bound parameters _after_ CALL:")
    print("  1: %s\t 2: %s \n" % (blob1, blob2))


output:
Values of bound parameters _after_ CALL:
  1: 123456      2: 123456

**Comment by czz829** [comment]
Thanks for spending time on this, Sabakauser. I tried your procedure and realized there's flaw in my code to fetch back result set from callproc. After correcting it, I'm able to call my procedure as expected.
