### ISSUE TITLE
[IBM][CLI Driver] SQL1531N error

### ISSUE THREAD

**Issue by kakkarg** [ibmdb/python-ibmdb#528]
Hi,

Tried a few things to get ibm_db working with Python 3.8 but still can't.
I have Db2 11.5 running on Windows 10 Pro. 

When I set IBM_DB_HOME=C:\Program Files\IBM\SQLLIB\clidriver, it gives this error while installing:

Collecting ibm_db
  Using cached ibm_db-3.0.2.tar.gz (718 kB)
ERROR: No .egg-info directory found in C:\Users\Gagan\AppData\Local\Temp\pip-pip-egg-info-tenryi_9

And when I don't use IBM_DB_HOME installation works fine but getting this erorr while connecting:

Exception: [IBM][CLI Driver] SQL1531N  The connection failed because the name specified with the DSN connection string keyword could not be found in either the db2dsdriver.cfg configuration file or the db2cli.ini configuration file.  Data source name specified in  SQLCODE=-1531 string: "SAMPLE".

And I don't think there is any issue with db2cli.ini as I do have SAMPLE alias there.

Thanks.
Gagan

**Comment by imavo** [comment]
Looks like a configuration matter.

If you have any of these already installed locally on Win10:
- a Db2 *server* product (this includes its own full client locally)
- or the IBM Db2 Data Server Client (full client) 
- or the IBM Db2 Runtime Client 
then set IBM_DB_HOME to "C:\Program Files\IBM\SQLLIB"  (not to the clidriver subdirectory), before you install ibm_db module.  If you installed the IBM product to a different location, then change the value of IBM_DB_HOME accordingly.

The clidriver directory is only for the tiny footprint (zero gui, and zero install ) ODBC and CLI driver. Other Db2 client packages (i.e. the runtime client, and the full client) do not have that clidriver folder and neither does the Db2-server package.

Both options work fine for me with Win10 and ibm_db 3.0.2 and Python 3.8 (i.e. using either the clidriver, or using the Db2 v11.5 local Db2-server ).

For some years IBM has been using the `db2dsdriver.cfg` file to configure DSNs and databases, instead of using db2cli.ini.  `db2dsdriver.cfg` is an XML file. You can either use command-lines to edit it (with the db2cli.exe tool, as per the documentation in knowledge center), or you can use a text editor if you understand how to edit XML. The db2cli.exe tool also lets you validate the XML file, and additionally lets you verify the database-connection without needing python or other tools - the Db2 documentation has all the details.

**Comment by kakkarg** [comment]
Thank you for your reply @imavo 

I set IBM_DB_HOME=C:\Program Files\IBM\SQLLIB\ and installed ibm_db....now I get this...
I think I will try to use: db2dsdriver.cfg

Traceback (most recent call last):
  File "d:/Documents/VS workspace new/python/db2test1.py", line 1, in <module>
    import ibm_db
  File "C:\Users\Gagan\AppData\Local\Programs\Python\Python38\lib\site-packages\ibm_db.py", line 7, in <module>
    os.add_dll_directory(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'clidriver', 'bin'))
  File "C:\Users\Gagan\AppData\Local\Programs\Python\Python38\lib\os.py", line 1109, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Gagan\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\clidriver\\bin'

**Comment by kakkarg** [comment]
setup db2dsdriver.cfg still same error....

Exception: [IBM][CLI Driver] SQL1531N  The connection failed because the name specified with the DSN connection string keyword could not 
be found in either the db2dsdriver.cfg configuration file or the db2cli.ini configuration file.  Data source name specified in the connec SQLCODE=-1531SAMPLE".

**Comment by kakkarg** [comment]
and here is db2cli validate output:


D:\Documents\VS workspace new\python>db2cli validate -dsn sample

===============================================================================
Client information for the current copy (copy name: DB2COPY1):
===============================================================================

Client Package Type       : IBM DB2 Enterprise Server Edition
Client Version (level/bit): DB2 v11.5.0.1077 (s1906101300/64-bit)
Client Platform           : NT 64BIT
Install/Instance Path     : C:\PROGRA~1\IBM\SQLLIB

Common App Data Path      : C:\ProgramData\IBM\DB2\DB2COPY1
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : <Common App Data Path>\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : <Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : <Common App Data Path>\DB2\db2diag.log

===============================================================================
List of all IBM Data Server client packages on the current workstation:
===============================================================================

Copyname      Version Package Language Installed-Location
-------------------------------------------------------------------------------
DB2COPY1[C,D] 11.5.00 UNKNOWN EN       C:\Program Files\IBM\SQLLIB
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Success: The schema validation completed successfully without any errors.

===============================================================================
db2cli.ini validation for data source name "sample":
===============================================================================

[ Keywords used for the connection ]

Keyword                   Value
---------------------------------------------------------------------------
DBALIAS                   SAMPLE
DATABASE                  SAMPLE
PROTOCOL                  TCPIP
PORT                      50000
PWD                       *********
UID                       Gagan

===============================================================================
db2dsdriver.cfg validation for data source name "sample":
===============================================================================

[ Parameters used for the connection ]

Keywords                  Valid For     Value
---------------------------------------------------------------------------
HOSTNAME                  CLI,.NET,ESQL LOCALHOST
COMMPROTOCOL              CLI,ESQL      IPC
IPCINSTANCE               CLI,.NET,ESQL db2

===============================================================================
The validation is completed.
===============================================================================

**Comment by kakkarg** [comment]
Finally some progress....it's working OK while running from command prompt but not while running the same file in VS Code...

PS D:\Documents\VS workspace new> & python "d:/Documents/VS workspace new/python/db2test1.py"
Traceback (most recent call last):
  File "d:/Documents/VS workspace new/python/db2test1.py", line 1, in <module>
    import ibm_db
  File "C:\Users\Gagan\AppData\Local\Programs\Python\Python38\lib\site-packages\ibm_db.py", line 7, in <module>
    os.add_dll_directory(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'clidriver', 'bin'))
  File "C:\Users\Gagan\AppData\Local\Programs\Python\Python38\lib\os.py", line 1109, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Gagan\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\clidriver\\bin'
PS D:\Documents\VS workspace new>
