### ISSUE TITLE
CLI to Db2 for z/OS: What's the best way to connect with both a userID/pwd & Certificate?

### ISSUE THREAD

**Issue by neoEvol** [ibmdb/python-ibmdb#530]
I'm trying to validate via the CLI prior to using with python app.

i need to connect via AT-TLS using both an userID/pwd & certificate.  I have a .kdb that includes a cert and CA chain.

Whats the preferred method to connect this way?

Thanks

**Comment by SabaKauser** [comment]
Hi,
You can use SSLClientKeystoredb and  SSLClientKeystash or the SSLClientKeystoreDBPassword keyword in the connection string for UserID/pwd.
For certificate, you can use authentication=certificate, set SSLClientKeystoredb  and SSLClientLabel.

https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.5.0/com.ibm.db2.luw.admin.sec.doc/doc/t0053518.html

**Comment by SabaKauser** [comment]
Also, instead of creating your own keydb, I suggest using SSLServerCertificate keyword as driver takes care of creating the keydb internally.
From Db2 V10.5 FP5 onwards, if the client is being installed on a separate computer and uses TLS to communicate with servers, ignore numbers two and three of the Procedure section. GSK also does not need to be installed for CLI, .NET, and open source drivers. You can pass the TLS Certificate to these client drivers using the SSLServerCertificate keyword in the CLI connection string, db2cli.ini file, or db2dsdriver.cfg file. The client driver will create an internal key database and add the certificate to it. You do not need to modify any environment variable.

**Comment by neoEvol** [comment]
i need to connect with a combination of both userID/ pwd AND cert/CA.

im currently using  SSLClientKeystoredb and SSLClientKeystash with my userID & password.  here's the error when i try:

db2cli validate -dsn db2_sec -connect

"
[FAILED]: [IBM][CLI Driver] CLI0219E  Certificate-based authentication failed because the DB2 client or data server driver was configured to use certificate-based authentication, but a password was also specified with the connection. SQLSTATE=HY000
"

how can i connect with **BOTH**  userId/pwd & cert/CA?

**Comment by imavo** [comment]
Certificate-authentication is mutually exclusive with userid+password authentication. You use one or the other but you cannot use both for the same connection.   Verify the type of certificate you have. A certificate for the target subsystem identifies what you are connecting-to and needs userid/password authentication.  A user-certificate identifies __you__ , and requires certificate authentication.

**Comment by neoEvol** [comment]
Ok, I submit: I will try to access secure database without user password. Lets not use SSLServerCertificate for now, please.


I see in my validation no password is being sent in ( I commented it out in my .ini file for this alias).

Here is sanitized version of my .cfg for the secure alias:

   <database name="DB2z" host="DB2z.mno-silly.com" port="2082">                
	<parameter name="ClientApplicationName" value="myProgToData_db2cli"/>
        <parameter name="SecurityTransportMode" value="SSL"/>
	<parameter name="Authentication" value="CERTIFICATE"/>
	<parameter name="SSLClientLabel" value="myCertAlias_current"/>    
        <parameter name="SSLClientKeystash" value="C:\a\b\certName.sth"/>
        <parameter name="SSLClientKeystoredb" value=" C:\a\b\certName.kdb"/>
	<wlb>
	      <parameter name="enableWLB" value="true" />
	      <parameter name="maxTransports" value="40"/>
	</wlb>


Im getting this error when I validate -connect

[FAILED]: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "420", "*", "*".  SQLSTATE=08001


What do you think?

**Comment by imavo** [comment]
Troubleshooting is best done by people at your site. Talk with local experts.
You can lookup (in the Db2 Knowledge Centre online) and various technotes the meaning of SQL30081N.
But in brief, when using SSL / TLS, the protocol specific error codes are return codes from GSKit.
So you can search 'Gskit return codes" online, and you find that 420 means "The partner closed the socket before the protocol completed.".
This can have different causes, but something is wrong with either the certificate or the setup (you must connect to the port dedicated for TLS/ssl for the target subsyste, you must not use the unencrypted port ). Verify every detail. Assume nothing. Before attempting validate -connect, use the plain validate without connect to ensure that syntactically the xml in db2dsdriver.cfg is perfect.
If anyone else at the site has a working configuration for TLS/ssl to the same subsystem, compare the working configuration with the failing one.

**Comment by neoEvol** [comment]
@imavo , thank you for all the support.  i got with local person in my shop and they helped with my cert implementation.


'luck favors the prepared mind'
