### ISSUE TITLE
Support lacking for Docker

### ISSUE THREAD

**Issue by jack0lantern** [ibmdb/python-ibmdb#531]
Does the python driver for DB2 work on docker? Yes it does, but here are a few issues I ran into that I feel are unnecessary hoops to jump through to make it work.

I'm using the python:3.7-slim image, which runs a minimal Ubuntu OS.

I expected to just be able to include`ibm_db==3.0.2` in `requirements.txt` and it would magically work.

First problem, the ibm_db driver can't find `gcc`. No biggie, I just added `RUN apt-get update && apt-get install -y gcc` to my Dockerfile and solved that one. It would be cool if that installation was done automatically, but otherwise I think this should at least be documented somewhere. 

Second problem, after successfully deploying the logs show me this error: `ImportError: libxml2.so.2: cannot open shared object file: No such file or directory`

This one baffled me for a while but it turns out libxml2 is yet another dependency package so I add on to my previous Dockerfile line like this: `RUN apt-get update && apt-get install -y gcc libxml2`

Again, this should be automatically done or documented somewhere.

**Comment by SabaKauser** [comment]
Hello,

We have documentation in README here -> https://github.com/ibmdb/python-ibmdb/blob/master/README.md#-installation

I am not sure what made you miss the readme.

Thanks for reporting the libxml2 dependency. Its actually not a direct dependency of ibm_db, but an implicit dependency of Db2 clidriver. I have added it to README now.
