### ISSUE TITLE
IBMi remote connection examples do not work

### ISSUE THREAD

**Issue by kpassey1** [ibmdb/python-ibmdb#532]
When starting a remote IBMi connection the QZDASOINIT job on the IBMi just sits there and nothing happens - unless you kill it then the python job just crashes.

**Comment by kadler** [comment]
If you are getting a QZDASOINIT job, then you are not using ibm_db. The [version](https://github.com/kadler/python-ibmdb/tree/ibmi) that we ship via yum and runs _on IBM i_ runs in a QSQSRVR job while the version that runs remotely uses Db2 Connect, which uses DRDA and run in a QRWTSRVR job.

QZDASOINIT jobs service ODBC and JDBC connections, which ibm_db is neither.

**Comment by kpassey1** [comment]
So are you saying all the examples relate to running a connection from an IBMi. Which looks like this..
 appier (1.20.2)         
 ibm-db (2.0.5.12)       
 itoolkit (1.6.1)        
 numpy (1.15.4)          

I’ve run this from my mac with the following installed
kevinpassey@Kevins-MacBook-Pro ~ % pip list
Package       Version
------------- -------
asgiref       3.2.10
Django        3.0.8
ibm-db        3.0.2
ibm-db-django 1.1.1.2
ibm-db-sa     0.3.5
pip           20.1.1
PTable        0.9.2
pyodbc        4.0.30
pypyodbc      1.3.4
pytz          2020.1
setuptools    41.2.0
SQLAlchemy    1.3.18
sqlparse      0.3.1

So are you saying that I need db2 connect if I want to run this from Eclipse on my mac or PC.

I have two IBMi instances so I’ll test a remote connection from one to the other.

**Comment by bimalkjha** [comment]
@kpassey1 Please install ibm_db version 3.0.3 which should fix this problem. Let us know if you are still facing this issue. Thanks.

**Comment by amukherjee28** [comment]
Hi @kpassey1 

Can this be closed. were you able to move ahead with the issue.

**Comment by kpassey1** [comment]
Yes close this please

Thanks
Kevin Passey
***@***.***
+44(0)8450 604123

**Comment by amukherjee28** [comment]
Thanks a lot @kpassey1 . Closing the issue.
