### ISSUE TITLE
DB2 SSL connection error

### ISSUE THREAD

**Issue by robertwitte** [ibmdb/python-ibmdb#533]
Hi,

I'm trying to create an SSL connection to a DB2 11 instance. And get the following error when trying to make a connection.

Exception: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001 SQLCODE=-30081

From what I can find on google this is related to GSKit and certificates but I have not been able to fix it.

Configured the connection string for ssl connection; added SSLServerCertificate argument with .arm file that I received from the DBA, SECURITY=ssl, protocol=tcpip, correct port for ssl

I'm using:
Python 3.7.7
ibm-db 3.0.2

Also tried to connect in a docker container (baseimage python 3.7, install dependencies and ibm_db as per README in this repo), and got the same error.

Using a DB client from Pycharm IDE I **am** able to connect with SSL to the same database.

Advise or suggestions are very welcome at this point, I'm stuck for quite some time now.
Thanks in advance!

**Comment by imavo** [comment]
414 Incorrectly formatted certificate is received from the partner.
Something is wrong with the arm file.
Is the Db2 v11 running on Z/OS? Give details.

**Comment by robertwitte** [comment]
Wow... I should have spotted that before.
You are right. It was indeed an incorrectly formatted arm file. 

I was using the server's SSL certificate where I should have used the root CA.

Thanks for the quick response!
