### ISSUE TITLE
AttributeError: module 'ibm_db_dbi' has no attribute 'Connection'

### ISSUE THREAD

**Issue by Sushmita-24** [ibmdb/python-ibmdb#536]
DB=''
conn = ibm_db.connect(DB, "", "")
conn1 = ibm_db_dbi.Connection(conn)

This code was working fine before I upgraded Pycharm from 2019.2.2 to 2020.2.2, I again degraded to 2019.2.2 but still facing the same error.

conn1 = ibm_db_dbi.Connection(conn)
AttributeError: module 'ibm_db_dbi' has no attribute 'Connection'

**Comment by SabaKauser** [comment]
can you check if your working directory has any python file named ibm_db_dbi.py?

**Comment by Sushmita-24** [comment]
No I don't have any file with name ibm_db_dbi.py

**Comment by amukherjee28** [comment]
Hi @Sushmita-24 

In case of proper installation of the ibm_db driver (example pip install ibm_db), the following files should be installed under the site-packages.

```
-rw-r--r--  1 amukherjee abp   9623 Sep 15 11:27 README.md
-rw-r--r--  1 amukherjee abp   9164 Sep 15 11:27 LICENSE
-rw-r--r--  1 amukherjee abp  15042 Sep 15 11:27 CHANGES.md
-rw-r--r--  1 amukherjee abp   1433 Sep 15 11:27 config.py.sample
-rw-r--r--  1 amukherjee abp    431 Sep 15 11:27 ibm_db.py
-rw-r--r--  1 amukherjee abp  63290 Sep 15 11:27 ibm_db_dbi.py
-rw-r--r--  1 amukherjee abp   2239 Sep 15 11:27 tests.py
-rw-r--r--  1 amukherjee abp   7231 Sep 15 11:27 testfunctions.py
drwxr-xr-x  2 amukherjee abp   4096 Sep 15 11:27 EGG-INFO
drwxr-xr-x  3 amukherjee abp   4096 Sep 15 11:27 certs
drwxr-xr-x 14 amukherjee abp   4096 Sep 15 11:27 clidriver
drwxr-xr-x  3 amukherjee abp  12288 Sep 15 11:27 ibm_db_tests
```

Only the clidriver folder is an optional in case you have set IBM_DB_HOME path, then in such cases clidriver download would be skipped.

Once the installation is good, you should be able to import ibm_db_dbi into your application code and use all of the API available with IBM_DB_DBI.

Please check after proper installation.

Let me know if this works for you.
