### ISSUE TITLE
Trace to View Passed Keyword Values

### ISSUE THREAD

**Issue by neoEvol** [ibmdb/python-ibmdb#537]
When i used the db2cli -validate command, i can see the keywords and their values i defined in the .cfg appear in the terminal.

Is there  a trace i can generate that will give me the full list of keywords passed (explicitly defined or otherwise, aka default) when i connect to db2 for z/OS?

I'm currently using this:

Trace = 1
TraceComm = 1
TraceStmtOnly = 1
TraceFileName=C:\Users...
TraceFlush = 1

and for example i can't see where the value i define for maxTransports.

can i capture all of these in a trace and ship to a separate file?

Thanks

**Comment by imavo** [comment]
Your question concerns the details of how CLI driver operates, and so your question is not specific to python ibm_db. It may be wiser to seek alternative support channels for non-python matters, such as opening a support ticket with IBM directly if you have a specific symptom.

This forum is more suitable for issues within python ibm_db itself, as distinct from how clidriver operates. 

To view how python ibm_db uses CLI, you can read the source-code of `ibm_db.c` on github. 

To view what happens inside clidriver (which is not part of python or python ibm_db, although python ibm_db uses a CLI driver to access Db2 databases), the source code is proprietary to IBM, although the `db2trc` tool exposes many aspects of clidriver operations. 

You can format the output of `db2trc` in different ways.  The output is more suitable for those with access to source code, nevertheless can be read by anyone with a basic knowledge of CLI and is useful for problem solving.

Settings that control only client side behaviours may not be passed to the Db2-server. 

Client side tracing is at ODBC/CLI level (such as what you show in `db2cli.ini` style keyword=value pairs), or at `db2trc` level.

Refer to the Db2 Knowledge Centre [online](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.admin.cmd.doc/doc/r0002027.html) for details of `db2trc` command. Apart from those traces, network level tracing via lower level tools (e.g. wireshark or similar) is available for those with suitable skills.

**Comment by SabaKauser** [comment]
you can run db2trc to identify set of keywords.
db2trc on -f trc.dmp
<run your application>
db2trc off

db2trc fmt -cli trc.dmp trc.cli

trc.cli will generate cli trace and you can see most of the keywords (except WLB and ACR) in SQLDriverConnectW() logging.

You can as well run :
db2cli validate -dsn <dsnname> 
above command will pick keywords from db2cli.ini and db2dsdriver.cfg

If your intention is to see other attributes set by ibm_db, then you need to analyze CLI traces.

Thanks,
Saba.

**Comment by amukherjee28** [comment]
All explanation pertaining to the issue was provided. Hence closing on this issue.
In case there are more question/queries please feel free to open a new issue.

Thanks.
