### ISSUE TITLE
August 6th update to clidriver breaks compatibility with CentOS 6 / Redhat 6 

### ISSUE THREAD

**Issue by brki** [ibmdb/python-ibmdb#541]
Installation of ibm-db succeeds on CentOS 6, but when trying to run `import ibm_db`, it fails with an error complaining about an incompatible glibc library. It needs version 2.14, but the available version on CentOS 6 / Redhat 6 is 2.12.

I had an older version of the clidriver directory available.  I copied it into the site-packages directory, replacing the one that was downloaded and installed during the installation of ibm-db.  After that I was able to successfully `import ibm_db`.

It seems to me the problem is caused by the clidriver compressed file, which was updated on August 6th, 2020:  https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz.

I use this ibm-db package in a Jenkins build.  A build on August 5th succeeded, and builds after August 6th fail.

**Comment by bimalkjha** [comment]
@brki What is your python version? Yes we updated linuxx64_odbc_cli.tar.gz. to Db2 V11.5.4.0 version which is built on CentOS 7.5/Redhat 8 and compiled using gcc (GCC) 8.3.1. Previous linuxx64_odbc_cli.tar.gz was of Db2 V11.1.4.5 and compiled using Intel 16 compiler.
I have installed ibm_db on RHEL 7.5 and my python version 2.7.5. It is working fine and we are able to import ibm_db. Probably the older OS and libraries of the system is causing problem. Please share the output of below commands after installing ibm_db:
```
ldd ..../python2.7/site-packages/ibm_db.so
ldd ...../python2.7/site-packages/clidriver/lib/libdb2.so.1
```

**Comment by bimalkjha** [comment]
Also, share the result of `g++ --version`. For me:
$ /usr/lib64> ls -l libstd*
lrwxrwxrwx. 1 root root     19 May  1  2018 libstdc++.so.6 -> libstdc++.so.6.0.19
-rwxr-xr-x. 1 root root 991616 Jan 20  2018 libstdc++.so.6.0.19
$ /usr/lib64> objdump -t libstdc++.so.6.0.19 | grep -i ___cxa_throw_bad_array_new_length
$ /usr/lib64> g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
thanks.

**Comment by bimalkjha** [comment]
$ /usr/lib64> ls -l libc.so*
-rw-r--r--. 1 root root 253 Feb  5  2018 libc.so
lrwxrwxrwx. 1 root root  12 May  1  2018 libc.so.6 -> **libc-2.17.so**

**Comment by brki** [comment]
Hi @bimalkjha ,

I think it's really a problem that's limited to CentOS 6 / Redhat 6 (with their older glib).

More info about my environment:
OS: CentOS 6.10
Python 3.6.9 (from Software Collections)


Output from ldd (note: I don't have site-packages/ibm_db.so, but rather site-packages/ibm_db.cpython-36m-x86_64-linux-gnu.so):

```
(.venv) [root@c9f3ae0969aa bin]# ldd /workflow/airflow_home/.venv/lib/python3.6/site-packages/ibm_db.cpython-36m-x86_64-linux-gnu.so
/workflow/airflow_home/.venv/lib/python3.6/site-packages/ibm_db.cpython-36m-x86_64-linux-gnu.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /workflow/airflow_home/.venv/lib/python3.6/site-packages/clidriver/lib/libdb2.so.1)
/workflow/airflow_home/.venv/lib/python3.6/site-packages/ibm_db.cpython-36m-x86_64-linux-gnu.so: /lib64/libgcc_s.so.1: version `GCC_4.8.0' not found (required by /workflow/airflow_home/.venv/lib/python3.6/site-packages/clidriver/lib/libdb2.so.1)
        linux-vdso.so.1 =>  (0x00007ffc567b5000)
        libdb2.so.1 => /workflow/airflow_home/.venv/lib/python3.6/site-packages/clidriver/lib/libdb2.so.1 (0x00007f9f45dd8000)
        libpython3.6m.so.rh-python36-1.0 => /opt/rh/rh-python36/root/usr/lib64/libpython3.6m.so.rh-python36-1.0 (0x00007f9f458fd000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9f456e0000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9f4534c000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f9f45115000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f9f44f11000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f9f44d09000)
        libpam.so.0 => /lib64/libpam.so.0 (0x00007f9f44afb000)
        libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007f9f447a8000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f9f444a2000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f9f4421e000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9f44008000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f9f43e05000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9f482de000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f9f43c02000)
        libaudit.so.1 => /lib64/libaudit.so.1 (0x00007f9f439de000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f9f437c8000)


(.venv) [root@c9f3ae0969aa bin]# ldd /workflow/airflow_home/.venv/lib/python3.6/site-packages/clidriver/lib/libdb2.so.1
/workflow/airflow_home/.venv/lib/python3.6/site-packages/clidriver/lib/libdb2.so.1: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /workflow/airflow_home/.venv/lib/python3.6/site-packages/clidriver/lib/libdb2.so.1)
/workflow/airflow_home/.venv/lib/python3.6/site-packages/clidriver/lib/libdb2.so.1: /lib64/libgcc_s.so.1: version `GCC_4.8.0' not found (required by /workflow/airflow_home/.venv/lib/python3.6/site-packages/clidriver/lib/libdb2.so.1)
        linux-vdso.so.1 =>  (0x00007ffd587e6000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fb603cd2000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb603ace000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb6038b1000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fb6036a9000)
        libpam.so.0 => /lib64/libpam.so.0 (0x00007fb60349b000)
        libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007fb603148000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fb602e42000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb602bbe000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb6029a8000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb602614000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007fb602411000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb6061f2000)
        libaudit.so.1 => /lib64/libaudit.so.1 (0x00007fb6021ed000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fb601fd7000)
```

g++ info:
```
(.venv) [root@c9f3ae0969aa bin]# g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

other info:
```
(.venv) [root@c9f3ae0969aa bin]# ls -l /usr/lib64/libstd*
lrwxrwxrwx 1 root root     19 Aug  4  2018 /usr/lib64/libstdc++.so.6 -> libstdc++.so.6.0.13
-rwxr-xr-x 1 root root 987096 Jun 19  2018 /usr/lib64/libstdc++.so.6.0.13

(.venv) [root@c9f3ae0969aa bin]# ls -l /lib64/libc.so*
lrwxrwxrwx 1 root root 12 Aug 13 08:33 /lib64/libc.so.6 -> libc-2.12.so
```

**Comment by bimalkjha** [comment]
@brki Please update GCC in your system. New installation of ibm_db requires gcc version >=8.4 should be installed in your system.
The problem is happening due to presence of old libc.so.6 and libgcc_s.so.1 in your system. Thanks.

**Comment by kadler** [comment]
libc.so.6 is **not** provided by GCC, but GLIBC and there's no way that RHEL 6 is getting an update for that.

If you're dropping support for RHEL 6 then you should just state _that_.

**Comment by bimalkjha** [comment]
@kadler I have refreshed clidriver few minute back. Please uninstall the existing ibm_db and have a new install.
If you still see problem with new install, then set environment variable as below and retry.
```
export LD_LIBRARY_PATH=/workflow/airflow_home/.venv/lib/python3.6/site-packages/clidriver/lib:$LD_LIBRARY_PATH
python test.py
```
Thanks.

**Comment by kadler** [comment]
@bimalkjha @SabaKauser 

FYI the latest data server driver at https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz contains 32-bit versions of libgcc_s.so.1, libc.so.6, and libstdc++.so.6.0.25. First of all, this is a 64-bit package and so the 32-bit binaries are less than useless.

Second of all, these files all come from the GNU project and are licensed under various GPL licenses (some LGPL, some GPL3). I could not find in the tar file any license files for them, nor their source code or a statement on where to retrieve the source code. This is a violation of the license of these projects and you'll want to get that corrected ASAP.

**Comment by SabaKauser** [comment]
@kadler  Bimal @bimalkjha  is working on this.

**Comment by brki** [comment]
@bimalkjha Thanks for looking into it!

The new version doesn't work for me, with or without an LD_LIBRARY_PATH modification.

```
$ python
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /someplace/.venv/lib/python3.6/site-packages/clidriver/lib/libdb2.so.1)
```

```
$ export LD_LIBRARY_PATH=/someplace/.venv/lib/python3.6/site-packages/clidriver/lib;$LD_LIBRARY_PATH
$  python
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /someplace/.venv/lib/python3.6/site-packages/clidriver/lib/libdb2.so.1)
```

For me personally, it's not a big deal.  I can work around it by copying the old version of clidriver into place.  Perhaps you could simply make the old version of the clidriver available someplace, and add a note to the README for people using CentOS / Redhat 6?  Or do an OS version check in setup.py, and download the old version if it's running on CentOS / Redhat 6?

Redhat 6 is reaching it's end-of-life in a few months.  I don't want to lose any sleep over this issue, nor cause you to. ;)

**Comment by bimalkjha** [comment]
> @bimalkjha @SabaKauser
> 
> FYI the latest data server driver at https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz contains 32-bit versions of libgcc_s.so.1, libc.so.6, and libstdc++.so.6.0.25. First of all, this is a 64-bit package and so the 32-bit binaries are less than useless.
> 
> Second of all, these files all come from the GNU project and are licensed under various GPL licenses (some LGPL, some GPL3). I could not find in the tar file any license files for them, nor their source code or a statement on where to retrieve the source code. This is a violation of the license of these projects and you'll want to get that corrected ASAP.

@kadler I have removed all three libraries and uploaded clidriver again. I tried to add 64bit version of libc.so.6, but it was causing another set of serious problems. So, there is no option other than removing it and installing latest version of this library on older OS. Thanks.

**Comment by bimalkjha** [comment]
@brki I have added 3 gcc libs and then told you to verify. But, by mistake 32bit libs were copied and @kadler reported the problem. So, we removed those libraries and hence problem still stays.
As of now, there is only two solution that I could see:
1. Download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64/linuxx64_odbc_cli.tar.gz , untar it, `export IBM_DB_HOME=<full path of clidriver>` and then install ibm_db.
2. Install GCC_4.8.0 and GLIBC_2.14 or higher version in your system.
Thanks.
