### ISSUE TITLE
ibm_db fails to connect when db2 is remote

### ISSUE THREAD

**Issue by nadir-syed** [ibmdb/python-ibmdb#542]
I can connect to db2 database when I run python script on SAME host (IBM I) where db2 is.
conn = ibm_db.pconnect("host", "userid", "pwd")
Here after successful connection, anyway to get db2 server details? so I could try them for remote connection.

But fails to connect to same database from other box. Trying default port & protocol as I don't know what values to try with.
connection = ibm_db.pconnect("DATABASE=host;HOSTNAME=host;UID=userid;PWD=pwd;", "", "")

Exception: [IBM][CLI Driver] SQL30081N  A communication error has been detected.
Communication protocol being used: "TCP/IP".  Communication API being used: "SO
CKETS".  Location where the error was detected: "host.ip".  Communication
function detecting the error: "connect".  Protocol specific error code(s): "1006
SQLCODE=-30081SQLSTATE=08001

I installed latest ibm_db 3.0.2 from pypi and have python 3.7.3.

**Comment by SabaKauser** [comment]
Hi,
Have you started the db2 server instance at correct port number?
do this in server machine:
db2 get dbm cfg | grep -i svcename

svcename should be seen updated with the port number. The make sure that server instance is listening at that port. If not, do a 'db2start'.
Come back at client machine, and use that port number in connection string along with existing parameters.
connection = ibm_db.pconnect("DATABASE=dbname;HOSTNAME=host;UID=userid;PWD=pwd;port=portno", "", "")

**Comment by SabaKauser** [comment]
also at server machine:
db2set DB2COMM=tcpip

**Comment by imavo** [comment]
Your question mentions IBM I.  Do you mean i-series (formerly AS/400) ?

Your symptom suggests that a firewall is blacking the specified Db2-port.

That firewall can be on your local workstation, or on the target host, or anywhere along the path.

If you are using Microsoft-Windows, it's software Firewall can be configured to open the port.

If you are running any anti-virus software on your client, it may also have a software firewall that needs to be configured to open the port.

If you are connecting to i-series , it is wise to use the odbc driver option that is available via the `IBM i access` product, because if you try to use the default driver (clidriver) that installs by default with Python ibm_db module then it will need a Db2-connect license file before it will connect to i-series.  You can avoid that need for a license file by using the odbc driver that is available with the `IBM i access` product.

If you are connecting to i-series from Microsoft Windows, Macos or Linux/Unix - y

**Comment by nadir-syed** [comment]
> Hi,
> Have you started the db2 server instance at correct port number?
> do this in server machine:
> db2 get dbm cfg | grep -i svcename
> 
> svcename should be seen updated with the port number. The make sure that server instance is listening at that port. If not, do a 'db2start'.
> Come back at client machine, and use that port number in connection string along with existing parameters.
> connection = ibm_db.pconnect("DATABASE=dbname;HOSTNAME=host;UID=userid;PWD=pwd;port=portno", "", "")

$ db2 get dbm cfg | grep -i svcename
db2: cannot execute

db2 is on IBM I (i series box) and I am trying to access from my windows computer

**Comment by nadir-syed** [comment]
> Your question mentions IBM I. Do you mean i-series (formerly AS/400) ?
> 
> Your symptom suggests that a firewall is blocking the specified Db2-port.
> 
> That firewall can be on your local workstation, or on the target host, or anywhere along the path.
> 
> If you are using Microsoft-Windows, it's software Firewall can be configured to open the port.
> 
> If you are running any anti-virus software on your client, it may also have a software firewall that needs to be configured to open the port.
> 
> If you are connecting to i-series , it is wise to use the odbc driver option that is available via the `IBM i access` product, because if you try to use the default driver (clidriver) that installs by default with Python ibm_db module then it will need a Db2-connect license file before it will connect to i-series. You can avoid that need for a license file by using the odbc driver that is available with the `IBM i access` product.

Yes db2 is on IBM I (i series box) and I am trying to access it from my windows computer

You are right, when I tried port 446 with DRDA protocol - I get license error. IBM I admins don't know where to find license on IBM website
Exception: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database ser
 SQLCODE=-1598ause of a licensing problem.  SQLSTATE=42968

Yes I have 'IBM i access' on my computer. Could you share steps on How to find and use it's odbc driver with python ibm_db?

**Comment by kadler** [comment]
The IBM i Access ODBC driver cannot be used with ibm_db, but you can use it with [pyodbc](https://github.com/mkleehammer/pyodbc)

**Comment by imavo** [comment]
Understand that remote CLI/ODBC access  to i-series (when using a driver supplied by IBM) is __NOT FREE__.

You either pay via your purchased product `IBM i access` (the least cost option, but python ibm_db needs to redirect via pyodbc as mentioned by @kadler ) , 


__OR__ you pay (for a single user) a license for Db2-connect personal license (the license file is available from passport-advantage after purchase and you copy the file to the clidriver/license subdirectory on your Windows workstation) 


__OR__ (for multiple users that need CLI/ODBC access concurrently ) pay for an expensive Db2-connect gateway product that lets multiple workstations see the databases on the i-series (and/or z/os)  as if they were local databases (this can directly work with clidriver that comes with Python ibm_db) and this is the highest cost option (but also the most flexible). 



If the company already has many i-series and/or Z/OS installations then most likely there is already at least one Db2-connect gateway installed, so talk with people at the site and find out what's available and which options make the best commercial and operational sense at your site.

**Comment by ramazanpolat** [comment]
@imavo I wanted to download DB2 Connect from passport advantage it shows 30 products, none of them is labeled as "Connect".

All of them fall under these categories:
* IBM Data Server Driver for ODBC and CLI
* IBM Data Server Runtime Client
* IBM Data Server Driver Package

Which one should I use?

*Thanks in advance*

**Comment by bimalkjha** [comment]
@ramazanpolat You need to download "•	IBM Data Server Driver Package" and apply db2connect license. Thanks.

**Comment by amukherjee28** [comment]
Hi @ramazanpolat 

I hope you were able to move forward with this issue.
Do you have any update on this case.

**Comment by ramazanpolat** [comment]
> Hi @ramazanpolat
> 
> I hope you were able to move forward with this issue.
> Do you have any update on this case.

Thank you. I don't have any other issue about this.

**Comment by amukherjee28** [comment]
Thanks for the confirmation. Will close the issue.
