### ISSUE TITLE
pypi serves the wrong file under certain conditions

### ISSUE THREAD

**Issue by joshred83** [ibmdb/python-ibmdb#545]
When manually downloading the ibm_db package from PyPi it seems to check the user agent before serving the file. 

If the user is coming from internet explorer, it will serve them a tar.tar file instead of a tar.gz file.

**Comment by amukherjee28** [comment]
Hi @joshred83 

Do you still have this issue?

**Comment by amukherjee28** [comment]
Please check the latest packages. In case you still the issue please open a new issue. Closing on this issue.
