### ISSUE TITLE
Difference in binaries for the same version.

### ISSUE THREAD

**Issue by sxnguyen** [ibmdb/python-ibmdb#546]
Hello,
We observed something strange.  We have containers that use the `ibm-db` library.  We include the `ibm-db==3.0.1` in our `requirements.txt` file. Both containers return the same version when we check using `pip show ibm_db`
```
bash-4.2$ pip show ibm_db
Name: ibm-db
Version: 3.0.1
Summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS
Home-page: http://pypi.python.org/pypi/ibm_db/
Author: IBM Application Development Team
Author-email: opendev@us.ibm.com
License: Apache License 2.0
Location: /usr/local/lib64/python3.6/site-packages
Requires:
Required-by:
```

 
However, the `db2level` cmd from the container that built late last year (Dec 2019) would show
```
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11014" with level identifier "0205010F".
Informational tokens are "**DB2 v11.1.4.5**", "special_39510",
"DYN1911120100AMD64_39510", and Fix Pack "5".
Product is installed at "..".
```
and the `db2level` cmd from the container that build this year would show
```
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11054" with level identifier "0605010F".
Informational tokens are "**DB2 v11.5.4.0**", "s2006161200", "DYN2006161200AMD64",
and Fix Pack "0".
Product is installed at "..".
```

We also notice the difference in sizes for binaries between this two containers.

Is this normal?
Thanks,
Scott

**Comment by sxnguyen** [comment]
Thank you @imavo

**Comment by sxnguyen** [comment]
@imavo : I hope you can help us here.  
1. We tried to use the odbc_cli version `11.1.4.5`, so we download the `v11.1.4fp5_linuxx64_odbc_cli.tar.gz`, extracted, and set the `IBM_DB_HOME` and `LD_LIBRARY_PATH`.  However, when I run `pip install ibm_db==3.0.1`, I would get
```
[root@ac9c64016b66 bin]# pip install ibm_db==3.0.1
Collecting ibm_db==3.0.1
  Downloading ibm_db-3.0.1.tar.gz (642 kB)
     |################################| 642 kB 709 kB/s
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-ch9joz8r
[root@ac9c64016b66 bin]# pip install ibm_db
Collecting ibm_db
  Downloading ibm_db-3.0.2.tar.gz (718 kB)
     |################################| 718 kB 801 kB/s
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-a8tew4vh
```

2. If I download the cli driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/, extract it, and set the `IBM_DB_HOME` and `LD_LIBRARY_PATH`, then the `pip install ibm_db` would work.  However, we don't want to use `11.5.4.0`.

Would you know where to get the correct odbc_cli version `11.1.4.5`?
Thanks,
Scott

**Comment by SabaKauser** [comment]
Hello Scott @sxnguyen 
You can download the v11.4.5 odbc and cli driver from this location:
https://www.ibm.com/support/fixcentral/swg/doSelectFixes?options.selectedFixes=DSClients-linuxx64-odbc_cli-11.1.4.5-FP005&continue=1

I think you need to be registered with fixcentral to download the driver. Please try and let me know.

**Comment by SabaKauser** [comment]
another thing to note is, please uninstall the ibm_db and do a fresh installation after setting IBM_DB_HOME.
e.g: 
pip uninstall ibm_db
export IBM_DB_HOME=/work/skauser/python/clidriver
pip install ibm_db

**Comment by sxnguyen** [comment]
@SabaKauser : Thank you for replying.  We download the same file
![image](https://user-images.githubusercontent.com/15933777/91329328-e3adca80-e77c-11ea-9096-c9c29b647a4e.png)
- Extract it to /opt/ibm/
- db2 level
```
[root@c7d83c3a144e bin]# ./db2level
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11014" with level identifier "0205010F".
Informational tokens are "DB2 v11.1.4.5", "s1911120100", "DYN1911120100AMD64",
and Fix Pack "5".
Product is installed at "/opt/ibm/clidriver".
```
- Environment variable
```
[root@c7d83c3a144e bin]# env |grep IBM
IBM_JAVA_OPTIONS=-XX:+UseContainerSupport
IBM_DB_HOME=/opt/ibm/clidriver
IBM_CLI_DRIVER_NAME=v11.1.4fp5_linuxx64_odbc_cli.tar
[root@c7d83c3a144e bin]# env |grep LD
LD_LIBRARY_PATH=/opt/ibm/clidriver/lib
OLDPWD=/opt/ibm/clidriver
```
- ibm_db not installed
```
[root@c7d83c3a144e bin]# pip show ibm_db
WARNING: Package(s) not found: ibm_db
```

- Installing ibm-db
```
[root@c7d83c3a144e bin]# pip install ibm_db==3.0.1
Collecting ibm_db==3.0.1
  Using cached ibm_db-3.0.1.tar.gz (642 kB)
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-whgmc_bl
```

**Comment by imavo** [comment]
Are you running this in a container?   
Would you share the Dockerfile ? ( so we can recreate the image and reproduce the problem)
Why using v3.0.1 instead of v3.0.2 of ibm_db ?
please confirm environment variables are exported to subshells, not only defined for current session.

**Comment by bimalkjha** [comment]
@sxnguyen What is the exact issue you are facing. Yes, we have updated the clidriver used by open source drivers recently at latest level. It has dependency on GCC version >=8.4.0. So, if you install latest version of gcc, issue should get fixed.
If you want older version of clidriver, you can download it from here: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64/linuxx64_odbc_cli.tar.gz
Thanks.

**Comment by bimalkjha** [comment]
> Hello Scott @sxnguyen
> You can download the v11.4.5 odbc and cli driver from this location:
> https://www.ibm.com/support/fixcentral/swg/doSelectFixes?options.selectedFixes=DSClients-linuxx64-odbc_cli-11.1.4.5-FP005&continue=1
> 
> I think you need to be registered with fixcentral to download the driver. Please try and let me know.

This version of clidriver do not support SSL connection. It has a bug. Use: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64/linuxx64_odbc_cli.tar.gz

**Comment by sxnguyen** [comment]
@imavo : I'll try to recreate w/ a sample container and send you the DockerFile.  We're using our internal container and cannot be shared.
@bimalkjha : The reason we want to go this way is that we want to control the cli client version as we've seen incompatibility issues between the latest cli client driver (11.5.4.0) with Db2 servers.
Can you kindly provide us with a central location where we can pick the specific version of cli driver? [This](https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64/) does not tell us the specific version.
Thanks,
Scott

**Comment by SabaKauser** [comment]
From Scott via email:
Hello Bimal,
I downloaded this package you mention, it has version 11.1.4.5 and it worked fine with our build. 

So the issue is with python ibm_db installation is resolved.

**Comment by guija** [comment]
@SabaKauser we also faced an issue regarding this. We build a project relying on `ibm-db` one year ago (This resulted in clidriver db2 version `11.1`. Rebuilding the project now results in db2 version `11.5`.

Our project connects do DB2 on ZOS so a license is required. Since the license (`db2consv_zs.lic`) is bound to a specific product version:
```
ProductName=DB2 Connect Unlim Ed zSeries
ProductID=1411
ProductVersion=11.1
```
our scripts failed with the following error:

> SQL1598N An attempt to connect to the database server failed because of a licensing problem. SQLSTATE=42968 SQLCODE=-1598

So replacing the `clidriver` version as you suggested worked. I comment this to document it for others having the same problem. 

However I don't think that ready release should change their dependencies. Not being reproduceable can lead to lots of problems. Can't you choose a fixed versions of the `clidriver`?
