### ISSUE TITLE
ibm_db callproc without parameters

### ISSUE THREAD

**Issue by yashasvi1992** [ibmdb/python-ibmdb#550]
How can I execute the stored procedures which don't have any parameters with ibm_db.callproc. Should I have to pass 'None' for parameters? or simply ignore the parameters option?

**Comment by imavo** [comment]
With ibm_db v3.0.2 you can pass an empty tuple as the parameters when the stored procedure has no input-parameters and no output-parameters. 


`stmt = call ibm_db.callproc('some_procname', ())`

If you specify `None` instead of an empty tuple(), you may get `Exception: Param is not a tuple`.

**Comment by AWADHAMBIKA** [comment]
Hi Yashasvi(@yashasvi1992 ),
Does the above resolve your query? If yes, kindly close the issue else let us know if you need any further help.

**Comment by amukherjee28** [comment]
Closing on this issue. Explanation provided.
