### ISSUE TITLE
Error installing ibm_db on Raspberry PI OS Version August 2020

### ISSUE THREAD

**Issue by dkuzdas** [ibmdb/python-ibmdb#552]
I have been working on a project that uploads production data to a IBM DB2 database from a Raspberry Pi 4 – 4gb device
When I try to install the itoolkit  – get the error shown below:
Any ideas – thoughts
Let me know 
Thanks  - Dan

Try to install using sudo pip install ibm_db
Get the following error:

pi@raspberrypi:~ $ sudo pip install ibm_db
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ibm_db
  Using cached https://files.pythonhosted.org/packages/6f/4e/48bf113d4f14b20a5008ea9f7784654041d8f7730c1081b370f569d80c93/ibm_db-3.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Detected 32-bit Python
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gDpkFf/ibm-db/setup.py", line 197, in <module>
        easy_cli_path = os.path.join(tmp_path, 'ibm_db-%s.egg' % ("-".join([VERSION, "py"+sys.version.split(" ")[0][0:3]]) if('win32' in sys.platform) else "-".join([VERSION, "py"+sys.version.split(" ")[0][0:3], os_, arch_])), 'clidriver')
    NameError: name 'arch_' is not defined
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-gDpkFf/ibm-db/

**Comment by amukherjee28** [comment]
Hi @dkuzdas ,

We have a list of supported Operating System for ibm_db as pointed out in the support document.
[https://github.com/ibmdb/python-ibmdb/blob/master/README.md]

From the error it looks to be issue with OS Support while installing.

Can you please help me with the Operating System Information from Raspberry Pi namely the OS name and the OS Bit in which you are trying to install ibm_db.

Thanks.

**Comment by dkuzdas** [comment]
OS is https://www.raspberrypi.org/downloads/raspberry-pi-os/
Release Notes: http://downloads.raspberrypi.org/raspios_armhf/release_notes.txt
Raspberry Pi OS (32-bit) with desktop
Image with desktop based on Debian Buster
Version:August 2020
Release date:2020-08-20
Kernel version:5.4
Size:1133 MB

**Comment by amukherjee28** [comment]
Hi @dkuzdas 

Thank you for the information provided.
Python driver(ibm_db) has dependency on the clidriver which is platform specific and is required to make the connection with the db2 database.
Unfortunately we do not have a clidriver available for Raspberry pi and hence we dont support the python driver on the same.

Please refer to this readme for the list of supported platforms on which we currently support.
[https://github.com/ibmdb/python-ibmdb/blob/master/README.md]

Because of the same the pip installs fails to install as it fails the OS check requirement.

Thanks.

**Comment by bimalkjha** [comment]
Raspberry PI is not a supported platform for IBM Db2 Clients. Only x86 and x64 architectures are supported not ARM architecture. So, IBM Open Source drivers are also not supported on ARM64 platform: https://docs.microsoft.com/en-us/answers/questions/10614/what-is-the-difference-between-x64-and-arm64.html#:~:text=The%20ARM%20architecture%20is%20typically,that%20supports%2064%2Dbit%20processing.&text=For%20example%20the%20Microsoft%20HoloLens%202%20uses%20an%20ARM64%20processor.
