### ISSUE TITLE
Does ibm-db run on z/OS Unix System Services ?

### ISSUE THREAD

**Issue by dwitkows** [ibmdb/python-ibmdb#554]
I have Python 3.7 installed in USS, and attempting to install the IBM-db 3.0.2 package from pypi, it throws the following messages:

    Detected 64-bit Python
    Not a known platform for python ibm_db.

If not, is there an intention for that?  And if so, any idea when it might be available?

**Comment by amukherjee28** [comment]
Hi,

We currently support z-linux (linux390x64), 64 bit which is also a supported platform as part of the readme as well.
[](https://github.com/ibmdb/python-ibmdb/blob/master/README.md)

s390x | s390x64_odbc_cli.tar.gz | Yes | V11.5.4
  | s390 | s390_odbc_cli.tar.gz | Yes | V11.1

Could you help me with the error message that you get while running pip install.

Also could you please also give us the following details from the platform you are running into.
1. osname
2. hardware of the platform (you can provide me the output of uname -a command)

Thanks.

**Comment by dwitkows** [comment]
Hi, thanks for the quick response.

I have attached the full output from pip.  You can find the error messages at the end.

The operating system is z/OS SP7.2.3.  On that is running Unix System Services (aka z/OS UNIX).

The hardware is an IBM SystemZ 8561 mainframe.

Here is the output from uname -a:
OS/390 ESAJ 26.00 04 8561

Dave

**Comment by imavo** [comment]
Z/OS USS is different from zLinux. 
ibm_db does not currently support Z/OS USS, neither is clidriver available for USS afaik.

**Comment by dwitkows** [comment]
Any idea when it will support z/OS USS ?

**Comment by SabaKauser** [comment]
z/OS USS is work in progress. We have a branch zODBC_support that is to enable ibm_db on z/OS using z ODBC driver.

Thanks!

**Comment by dwitkows** [comment]
Can you provide download and setup information for ibm_db on z/OS using z ODBC driver?

**Comment by bimalkjha** [comment]
@dwitkows You need to setup zODBC first on z/OS. For that you can refer [this doc](https://github.com/ibmdb/node-ibm_db#configure-odbc-driver-on-zos).  Then run below commands:
```
git clone https://github.com/ibmdb/python-ibmdb.git -b zODBC_support
cd python-ibmdb/IBM_DB/ibm_db
python setup.py build
python setup.py install
```

@SabaKauser Do we need to set IBM_DB_HOME environment variable too? Please correct above info if required. Also, do we have any documentation updated in zODBC_support branch for z/OS installation like we have for node.js driver?

@AWADHAMBIKA please update. Thanks.

**Comment by AWADHAMBIKA** [comment]
We have updated the documentation for z/OS at below link. Kindly refer to the same and check the steps. Please let us know if you face any issues.
https://github.com/ibmdb/python-ibmdb/blob/zODBC_support/install.md

**Comment by AWADHAMBIKA** [comment]
@dwitkows latest driver release i.e. 3.0.3 officially supports z/OS and has been released. Have you tried with the latest release?
Kindly follow the standard driver installation instructions in README file and validate if your issue is resolved.
If yes, please confirm and close this issue.
