### ISSUE TITLE
SystemError: <built-in function connect> returned NULL without setting an error

### ISSUE THREAD

**Issue by infoakash** [ibmdb/python-ibmdb#556]
I'm trying to connect to db2 with ibmdb library.
Using python 3.7.6 and ibm_db==3.0.1

import ibm_db
conn_str = 'database=;hostname=.cua.com.au;port=;protocol=tcpip;uid=;pwd='
#removed the details from conn_str

db2Conn = ibm_db.connect(conn_str, '', '')

while executing the connect this runs into a error :
SystemError: <built-in function connect> returned NULL without setting an error

**Comment by imavo** [comment]
Please use the version 3.0.2 of the ibm_db , and retry.  You also need to tell us which Db2-server platform you try to reach (is it Db2 on Z/OS,  Db2 for i-series,  or Db2 for Linux/Unix/Windows) as different software driver for Db2 might be necessary if accessing Db2-for-i-series.    You should also describe your workstation environment, is it MS-Windows or Linux etc, and how it is configured for python (virtual env etc?), and whether you have verified that this workstation can connect to the same database with the same credentials *outside* of python (for example, at the shell command line etc).

**Comment by infoakash** [comment]
It's DB2 Z/OS I'm trying to connect to. Using Windows 10.  

Upgraded to ibm_db 3.0.2 as well. 
Still getting the same error.

**Comment by infoakash** [comment]
@SabaKauser is this something you can help with?

I read a couple of forums on this issue no plausible resolution is posted anywhere.

**Comment by infoakash** [comment]
Hi @amukherjee28 ,

1.All what I am in the console is : 
Traceback (most recent call last):
  File "<input>", line 1, in <module>
SystemError: <built-in function connect> returned NULL without setting an error

2. I am using the IBM Data Server Driver for ODBC and CLI (Windows AMD64 and Intel EM64T) Version 11.5.4 available at 
https://epwt-www.mybluemix.net/software/support/trial/cst/programwebsite.wss?siteId=849&h=null&p=null

And I have got the DB2 connect license file placed in the license folder inside clidriver.

**Comment by imavo** [comment]
Have you verified that in a cmd.exe window on Win10, that you are able to use the `db2cli.exe` (which is part of the clidriver) to connect to the Db2-for-Z/OS database successfully at the command line?  
The idea is to prove that the clidriver can connect with the same credentials to the same database , regardless of python. This is often the way to find underlying errors and omissions in the  configuration.

Once you get a successful connection using `db2cli.exe validate -dsn YOURDSN -connect -user XXX -password YYY `, it means that your Win10 configuration for clidriver is all good, and your python ibm_db will then connect.


To help with this, You can  configure the plain xml text file called `db2dsdriver.cfg` file (in the clidriver\cfg directory , whose path is shown via `pip show ibm_db` ) with all the details of your Db2-for-Z/OS data-source (as instructed via the links on the Db2-documentation  page here:

https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.swg.im.dbclient.config.doc/doc/c0054555.html

If that is too difficult for you , you can also run a CLI trace, with the `db2trc` command (detailed in the Db2 Knowledge centre) with these command lines:


cd clidriver install path, found with `pip show ibm_db` in Location: field of its output.
cd clidriver\bin
db2trc on -f trc.dmp
--> now run your application
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share these files  trc.flw, trc.fmt, trc.fmtc and trc.cli files

**Comment by imavo** [comment]
I see that other users reported this symptom in environments where they do NOT have local-administrator privilege,  and others in corporate environment where the Windows workstation has specific ACLs that restrict the behaviour in some way.

So three additional suggestions:

1. You might want to try if different workstations / different users are impacted .
2. You might want to see if the behaviour changes if you run your python script in a cmd window that has elevated privileged (running as local admin, for example).
3. You also might want to run the python debugger on your script `python -m pdb YOUR_SCRIPT.py` and report its output.

**Comment by amukherjee28** [comment]
closing on this issue.

**Comment by Earammak** [comment]
@alessandroToninelli Can you please share the details that are mentioned from the issue template.
You can also refer the similar issues: #783, #714, #692
