### ISSUE TITLE
Supported DB2 Drivers?

### ISSUE THREAD

**Issue by ram-ibm** [ibmdb/python-ibmdb#557]
#1 I used the driver recommended here on a Linux server "linuxx64_odbc_cli.tar.gz" and realized that I need C libraries and seemingly gcc installed. db2cli command would not work without the C libraries.

#2 Since I cannot trivially install the C libraries on my customer machine, I downloaded the latest ODBC/CLI driver from FixCentral "v11.1.4fp5_linuxx64_odbc_cli.tar.gz". I was able to run db2cli successfully without C libraries. Unfortunately ibm_db wants an "include" sub-directory that does not exist for this driver (discovered this after much searching and realizing that pip install with -vvv shows the include directory missing).

#3 On my laptop I have a vm image running which includes a DB2 server. ibm_db installed fine and ran successfully BUT I noticed that there is no IBM_DB_HOME environment variable. So the ibm_db is clearly using some other way to detect that DB2 is available and useable on that box.

Question: How can I pursue option#2 please? It does not have the C library requirements, I can install trivially by unzipping and setting environments variables, and it contains the install steps clearly documented. What is this "include" directory dependency - how can I work around it please?

**Comment by imavo** [comment]
Which linux distro and cpu-architecture?  Is it x64, or zLinux or some other architecture?   If you are using something like alpine then more than one required package will be omitted by default.

The "linuxx64_odbc_cli.tar.gz" ( also known as clidriver)  __does__ need you to have libxml2 installed for db2cli to be able to validate xml files like db2dsdriver.cfg (at the very least).  You can install libxml2 with yum or apt or whatever package manager you use. But once that is installed, clidriver will work as long as the cpu-architecture is supported (i.e as long as ibm_db does not need to be compiled from source).  Many distros have this already installed, but it can be absent in minimalist distros or in containers, hence the readme file of the ibm-db module mentions this requirement.

You do not need to have the gcc installed unless your CPU architecture does not have a prebuilt image for ibm_db and clidriver. When there's no prebuilt image, the ibm_db must be compiled from source code and then you need the "include" directory of a Db2-client as well as the matching "lib" directory.    The "include" directory for the Db2-client is __NOT__ present in the clidriver package by design. (clidriver is the *minimal footprint driver*, the smallest one, not intended for development or compiling from source code). The "include" directory is present in the full Db2-client (also known as the fat client because it is significantly larger than either clidriver or the RuntimeClient , as it has all required tools for development and administration and operation).

For the #3 question, the ibm_db setup also looks for IBM_DB_DIR or IBM_DB_HOME or IBM_DB_LIB . A standard `db2profile` file of a Db2-LUW db2-instance will always set IBM_DB_DIR and IBM_DB_LIB environment variables once dotted into the current session.  Hence the python ibm_db setup should find these  That is the reason the python ibm_db setup works without IBM_DB_HOME defined, it uses one of the other two and knows that it does not then need to install clidriver as it uses the Db2-instance own local client instead, in that case.

**Comment by ram-ibm** [comment]
Thanks much for the detailed reply! I am providing details of errors since someone else might hit similar issues.

Here is what customer was facing:
```
$ pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org ibm_db --proxy=http://<proxy details>
Collecting ibm_db 
  Downloading https://files.pythonhosted.org/packages/6f/4e/48bf113d4f14b20a5008ea9f7784654041d8f7730c1081b370f569d80c93/ibm_db-3.0.2.tar.gz (718kB) 
    98% |&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#338;| 706kB 25.0MB/s eta 0:00:0    99% |&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;| 716kB 22.9MB/s eta 0:00:0    100% |&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;&#226;–&#710;| 727kB 23.2MB/s 
No files/directories in /tmp/pip-build-kFPXFm/ibm-db/pip-egg-info (from PKG-INFO)
```

I retried on a server that I had access to (yeah still on python2) - using the fixpack ODBC/CLI driver:
```
$ pip install ibm_db --proxy=<proxy details>
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting ibm_db
  Using cached ibm_db-3.0.2.tar.gz (718 kB)
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-x2dDr6
```

Naively I updated setuptools and pip and continued getting the error. then when installing with -vvv I noticed this:
```
...lots of messages
    Running setup.py (path:/tmp/pip-install-PlGHqS/ibm-db/setup.py) egg_info for package ibm-db
    Created temporary directory: /tmp/pip-pip-egg-info-3Mf7Ot
    Running command python setup.py egg_info
    /tmp/pip-install-PlGHqS/ibm-db/setup.py:258: UserWarning: Detected usage of IBM Data Server Driver package. Ensure you have downloaded 64-bit package of IBM_Data_Server_Driver and retry the ibm_db module install

      warnings.warn(notifyString)
    Detected 64-bit Python
     /home/python/odbc_cli/clidriver/include folder not found. Check if you have set the IBM_DB_HOME environment variable's value correctly
```

Then I switched back to using the recommended driver (which has the include sub-directory) and was able to install the package, but ran into problems when I tried to use the package:
```
$ python                                            
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/python/clidriver/lib/libdb2.so.1)
```

Now switching back to the ODBC_CLI driver (downloaded from FixCentral), I was able to import ibm_db:
```
$ python
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import ibm_db
```

Will run more tests actually trying to use the package. So I was able to install the package using the recommended CLI driver, but actually use the package successfully using the ODBC_CLI driver.

FYI - Here is my CPU architecture details:
```
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                5
On-line CPU(s) list:   0-4
Thread(s) per core:    1
Core(s) per socket:    5
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
Stepping:              4
CPU MHz:               2793.269
BogoMIPS:              5586.53
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-4
```

**Comment by ram-ibm** [comment]
I got my hands on one more server I could test the steps out on - really hoping to use the odbc_cli driver both for install and execution. Please let me know if there is any details I could provide on the re-create?

**Comment by bimalkjha** [comment]
@ram-ibm Please check this comment for more info: https://github.com/ibmdb/node-ibm_db/issues/713#issuecomment-712657253
Thanks.

**Comment by ram-ibm** [comment]
@bimalkjha - there seems to be a dependency on the "include" directory *only* during install time. We installed the recommended CLI driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz got ibm_db installed and then switched to using ODBC/CLI driver successfully. The one that can be downloaded as per this link:

https://www.ibm.com/support/pages/db2-odbc-cli-driver-download-and-installation-information#%5B%3Ch2%3E%5DDownload%5B%3C%2Fh2%3E%5D

**Comment by bimalkjha** [comment]
@ram-ibm `include` dir contains header files which is required to compile the native code of ibm_db during install time. The odbc libraries are also compiled using same header files. If you change the odbc library post install, the ibm_db binary and odbc binary files may get compiled with different versions of header file and may cause some problem during runtime. It depends on how much is changed between header files and what functionality is being used at runtime. So, normally it works, but there can be error or other crashes at anytime during the program execution. So, its not recommended to change the version and level of odbc/cli driver during installation and post installation. If versions are same, then no issues and it should work. Thanks.
