### ISSUE TITLE
ibm_db.conn_errormsg() returning only SQLCODE

### ISSUE THREAD

**Issue by vfandino** [ibmdb/python-ibmdb#558]
ibm_db.conn_errormsg() returns only a portion of the error message when a connection fails

**Comment by vfandino** [comment]
ibm_db.conn_errormsg().replace('\r', '') will fix the issue

**Comment by AWADHAMBIKA** [comment]
Hi @vfandino,
So your issue is resolved? Can you please close this else let us know if you need any further help?
