### ISSUE TITLE
Can't connect to IBM AS400 Database

### ISSUE THREAD

**Issue by thiagodma** [ibmdb/python-ibmdb#560]
I'm trying to connect to an IBM AS400 database using ibm_db but without success. Here's my code:

```
import ibm_db

conn_str = "DRIVER={IBM i Access ODBC Driver};DATABASE=db;HOSTNAME=host;PORT=port;PROTOCOL=TCPIP;UID=uid;PWD=pwd;"

conn = ibm_db.connect(conn_str, "", "")
```

It seems that no matter what I do to the connection string I always get the error:

> Exception: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "xxx.xx.xx.xxx".  Communication function detecting the error: "recv".  Protocol specific error code(s): "*", "*", "0".  SQLSTATE=08001 SQLCODE=-30081

I've changed the host's IP on the exception.

System:

Red Hat 4.8.5-39
Python 3.6.8
ibm_db version: 3.0.2

**Comment by amukherjee28** [comment]
Hi,

I would suggest you to please have a look at this issue and try out the resolution provided.

[](https://github.com/ibmdb/python-ibmdb/issues/555)

Thanks.

**Comment by thiagodma** [comment]
Hi @amukherjee28 . Maybe you forgot to add a link?

**Comment by thiagodma** [comment]
Are you sure this is the correct link?

**Comment by imavo** [comment]
Look up issue 555 which is now closed
https://github.com/ibmdb/python-ibmdb/issues/555

**Comment by thiagodma** [comment]
Thank you @imavo. Using pyodbc + IBM i Access Driver worked!
