### ISSUE TITLE
Connection Issue from Azure

### ISSUE THREAD

**Issue by neoEvol** [ibmdb/python-ibmdb#561]
Hello,

I’m working with a developer who is setting up SSL connection to db2 for z/OS from a .Net application running in an azure windows VM.

Here’s the console message when attempting to validate via the db2cli ( db2cli validate -dsn alias-name -connect) command:

[FAILED]: [IBM][CLI Driver] SQL1531N  The connection failed because the name specified with the DSN connection string keyword could not be found in either the db2dsdriver.cfg configuration file or the db2cli.ini configuration file.  Data source name specified in the connection string: "alias-name".

[IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968

Without the “-connect’ her validation is successful.  But the -connect throws the above error.

I had her run a trace level 1 and here is a (sanatized) snip of trace from the above error:

[ Process: 5176, Thread: 3892 ]
[ Date & Time:               10/13/2020 13:43:26.622531 ]
[ Product:                   QDB2/NT64 DB2 v11.5.4000.1449 ]
[ Level Identifier:          0605010F ]
[ CLI Driver Version:        10.01.0000 ]
[ Informational Tokens:      "DB2 v11.5.4000.1449",…,”Fixpack 0" ]
[ Install Path:              C:\...\ODBC Drivers\clidriver ]
[ Current Installation Name: Error obtaining installation name ( zrc = -2029059760 ) ]
[ db2cli.ini Location2:      C:\...\db2cli.ini ]
[ db2dsdriver.cfg Location:  C:\...db2dsdriver.cfg ]
[ CLI Driver Type:           IBM Data Server Driver For ODBC and CLI ]
[ Hostname:                  (…).com ]

I’m thinking I need to resolve the ( zrc = -2029059760 ) error, but I’m having trouble finding documentation on that.

Can you please help?

Thanks,

**Comment by imavo** [comment]
Is the Db2-connect license key file (as purchased by the customer) already placed into the license subdirectory of the clidriver location and made readable by all?

The `db2dsdriver.cfg` DSN name must exactly match the DSN used in the python connection string.

**Comment by neoEvol** [comment]
we resolved this item: DSN had been correct the entire time.  prob was Db2 connect version on client was newer than server.  client side went back to version of server and works A-OK.
This is resolved.
Thanks for your prompt response as always
