### ISSUE TITLE
can't connect to IBM DB2 using Anaconda Python 2020.07 Python 3.8.3

### ISSUE THREAD

**Issue by ankhnesmerira** [ibmdb/python-ibmdb#563]
ibm_db / ibm_dbi package for python 3.8 doesn't work for Python 3.8.3. we have to unintall and revert back to 3.7.6

**Comment by amukherjee28** [comment]
Hi,

Just wanted to check on few things.
1. Are you using conda install to install the package ibm_db or you are using python from Anaconda distribution and then using pip to install pacakge.
2. Can you please provide the error log in case you have it.

Thanks.

**Comment by imavo** [comment]
It seems that the currently available ibm_db 3.0.2 package on conda-forge  
will fail to `conda install` on  conda 2020.07 which initially comes with python 3.8.3.

The solver may report `UnsatisfiableError:` with specifications:
`ibm_db -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']`

I don't know who maintains the conda-forge packages...

The workaround below resulted in a successful connection via ibm_db for me,  other workarounds may be available. The `conda update -all` yields python 3.8.5 at todays date (19/Oktober/2020).

```
conda update -all
(for MS-Windows:  conda install m2-patch )
conda skeleton pypi ibm-db
conda-build ibm-db
conda install --use-local ibm-db

```

**Comment by ankhnesmerira** [comment]
The recent Anaconda Python version 2020.07 is a Python 3.8.3 version.
As shown below, ibm_db does support 3.8.0a, but not anything higher than 3.8. Hope it helps.

![can't install ibmdb](https://user-images.githubusercontent.com/28076602/96836469-99dd1a00-1477-11eb-9a1c-26edf08289d4.png)

**Comment by AntonioBlago** [comment]
> 
> 
> It seems that the currently available ibm_db 3.0.2 package on conda-forge
> will fail to `conda install` on conda 2020.07 which initially comes with python 3.8.3.
> 
> The solver may report `UnsatisfiableError:` with specifications:
> `ibm_db -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']`
> 
> I don't know who maintains the conda-forge packages...
> 
> The workaround below resulted in a successful connection via ibm_db for me, other workarounds may be available. The `conda update -all` yields python 3.8.5 at todays date (19/Oktober/2020).
> 
> ```
> conda update -all
> (for MS-Windows:  conda install m2-patch )
> conda skeleton pypi ibm-db
> conda-build ibm-db
> conda install --use-local ibm-db
> ```

I tried this approach, but it failed when i installed  conda-build ibm-db 

![grafik](https://user-images.githubusercontent.com/44394836/100430779-8553f900-3097-11eb-90ef-7a9b228e292e.png)

**Comment by amukherjee28** [comment]
Hi @ankhnesmerira

The ibm_db version is already on 3.0.4 now.
Can we close on this issue in case you are able to move forward with this.

**Comment by ankhnesmerira** [comment]
Sure. I found a way around it. Thanks.

**Comment by amukherjee28** [comment]
Thanks @ankhnesmerira . Closing this issue.
