### ISSUE TITLE
Head function crashing in Watson studio Jupyter Notebook with Python 3.7

### ISSUE THREAD

**Issue by rvandiessen** [ibmdb/python-ibmdb#564]
Connection to DB2 database running as managed service in Ibm Cloud is working. Both DB2 instance and Watson Studio running in the same region (Frankfurt). But the ida_df_2.head() below fails.
===
ida_df_2 = IdaDataFrame(idadb_ca1a28bd91894ba4829b8f5d2c9107a6, 'TEST.SHORTTEST')
ida_df_2.head()

# You can close the database connection with the following code. Please keep the comment line with the @hidden_cell tag,
# because the close function displays parts of the credentials.
# @hidden_cell
# idadb_ca1a28bd91894ba4829b8f5d2c9107a6.close()
# To learn more about the ibmdby package, please read the documentation: http://pythonhosted.org/ibmdbpy/
===
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-a873e5776128> in <module>
      1 ida_df_2 = IdaDataFrame(idadb_ca1a28bd91894ba4829b8f5d2c9107a6, 'TEST.SHORTTEST')
----> 2 ida_df_2.head()
      3 
      4 # You can close the database connection with the following code. Please keep the comment line with the @hidden_cell tag,
      5 # because the close function displays parts of the credentials.

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/ibmdbpy/internals.py in wrapper(self, *args, **kwds)
     55                 self.internal_state.viewstack.append("(" + self.internal_state.get_state() + ")")
     56             try:
---> 57                 result = function(self, *args, **kwds)
     58             except:
     59                 raise

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/ibmdbpy/frame.py in head(self, nrow, sort)
   1068                     if sort:
   1069                         column = self.columns[0]
-> 1070                         if self._get_numerical_columns():
   1071                             column = self._get_numerical_columns()[0]
   1072                         order = " ORDER BY \"" + column + "\" ASC"

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/ibmdbpy/frame.py in _get_numerical_columns(self)
   2248         num = ['SMALLINT', 'INTEGER', 'BIGINT', 'REAL',
   2249                             'DOUBLE', 'FLOAT', 'DECIMAL', 'NUMERIC']
-> 2250         return list(self.dtypes.loc[self.dtypes['TYPENAME'].isin(num)].index)
   2251 
   2252     def _get_categorical_columns(self):

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/lazy/lazy.py in __get__(self, inst, inst_cls)
     26             name = '_%s%s' % (inst_cls.__name__, name)
     27 
---> 28         value = self.__func(inst)
     29         inst.__dict__[name] = value
     30         return value

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/ibmdbpy/internals.py in wrapper(self, *args, **kwds)
     65             self.internal_state._create_view()
     66             try:
---> 67                 result = function(self, *args, **kwds)
     68             except:
     69                 raise

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/ibmdbpy/frame.py in dtypes(self)
    293         """
    294         #import pdb ; pdb.set_trace()
--> 295         return self._get_columns_dtypes()
    296 
    297     @lazy

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/ibmdbpy/frame.py in _get_columns_dtypes(self)
   2142         data.columns = [x.upper() for x in data.columns]
   2143         data.set_index(keys='COLNAME', inplace=True)
-> 2144         del data.index.name
   2145         return data
   2146 

AttributeError: can't delete attribute

**Comment by imavo** [comment]
Your question is about `ibmdbpy`, but this github issue page is for a __different__ component - the  python `ibm_db` module.

According to the `ibmdbpy`  page on pypi,  `ibmdbpy` , At today's date is compatible with python3 up to version 3.6 (this may change in the future): 

See https://pypi.org/project/ibmdbpy/

You are trying to use `ibmdbpy` with Python 3.7.

Maybe you need to ask this question on the issues page of `ibmdbpy`  which is at 
https://github.com/ibmdbanalytics/ibmdbpy

**Comment by rvandiessen** [comment]
Thanks for the reply and sorry for posting on the wrong repository
