### ISSUE TITLE
Docker error when installing ibm_db via pip. 

### ISSUE THREAD

**Issue by FernandoDurier** [ibmdb/python-ibmdb#565]
Hello, I'm having several issues trying to use this lib to connect to an IBM DB2 for Z/OS I have.
Here is my Dockerfile:
```
FROM python:3.6
WORKDIR /app
COPY . /app
ENV IBM_DB_HOME ./db2_license/license/clidriver
ENV LD_LIBRARY_PATH ./db2_license/license/clidriver/lib
ENV PATH $PATH:$IBM_DB_HOME/bin
RUN pip install -r requirements.txt
CMD ["python","app.py"]
```

And here is the error I'm getting:
```
Step 7/8 : RUN pip install -r requirements.txt
 ---> Running in 037c59c2ff52
Collecting ibm_db
  Downloading ibm_db-3.0.2.tar.gz (718 kB)
ERROR: No .egg-info directory found in /tmp/pip-pip-egg-info-g4xtnc3_
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```

And when I'm trying without the IBM_DB_HOME, I got licensing issues in the connection.

**Comment by FernandoDurier** [comment]
Hello!!
I have good news!!
I did it here. In the end I had to uncompress the license tar.gz file. Then correctly set the required env vars. In the end here 
I've used the linuxx64_odbc_cli.tar.gz
How the Dockerfile is set up:
```
FROM python:3.7
WORKDIR /app
COPY . /app
RUN pip install --upgrade setuptools pip
ENV IBM_DB_HOME /app/db2_license/licenses/clidriver
ENV LD_LIBRARY_PATH /app/db2_license/licenses/clidriver/lib:$LD_LIBRARY_PATH
RUN pip install -r requirements.txt
CMD ["python","app.py"]
```

**Comment by usertamil** [comment]
Hello !! I heard linuxx64_odbc_cli.tar.gz is not required.  Lack of wheeling should be the root cause. 
Hopefully you agree there is value in distributing a wheel for ease of use for those of us with restricted environments.

**Comment by bimalkjha** [comment]
@usertamil please check my comment on issue #573 . Thanks.
