### ISSUE TITLE
Deploy error - External link restriction error

### ISSUE THREAD

**Issue by usertamil** [ibmdb/python-ibmdb#573]
I really like this package. Since we have restriction to external Links, i tried with IBM_DB_Path. But getting an error : Is this due to caching ? 

ERROR: Files/directories not found in /tmp/pip-install-uwxucagc/ibm-db/pip-egg-info
Running pip install failed. You need to include all dependencies in the vendor directory.
**ERROR** Could not install vendored pip packages: could not run pip: exit status 1

Is the driver mandatory for using IBM_DB package ? 
Hopefully you agree there is value in distributing a wheel for ease of use for those of us with restricted environments. ?

**Comment by bimalkjha** [comment]
@usertamil For restricted environment, download clidriver based on your Operating System and platform form this link: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/
Untar/unzip the file which will give you clidriver directory. Then set system environment variable `IBM_DB_HOME` pointing to full/path/of/clidriver/directory. Then use `pip install ibm_db`. It'll be installed without downloading the clidriver as it is already downloaded and pointed by IBM_DB_HOME. Yes, clidriver or some db2 client/server must be installed in the system to use ibm_db. Thanks.
