### ISSUE TITLE
ibm_DB 3.0.2 stuck in collecting

### ISSUE THREAD

**Issue by DgitalTrex** [ibmdb/python-ibmdb#584]
It's just stuck here...

`C:\WINDOWS\system32>pip3 install ibm_db`
`Collecting ibm_db`
`Using cached ibm_db-3.0.2.tar.gz (718 kB)`

**Comment by SabaKauser** [comment]
Can you try: pip install ibm_db --no-cache-dir

**Comment by DgitalTrex** [comment]
Hi, it worked. Requirement already satisfied: ibm_db in c:\python39\lib\site-packages (3.0.2)

But now an import ibm_db says module not found. I go to site-packages folder and I see ibm_db_dbi, but no ibm_db? Am I missing something

**Comment by SabaKauser** [comment]
Hello,
We currently do not support python 3.9. The latest supported version is python 3.8.
https://github.com/ibmdb/python-ibmdb#-pre-requisites

Please try with python 3.8.

Thanks!

**Comment by amukherjee28** [comment]
Hi @DgitalTrex 

Can we close on with this issue?

**Comment by DgitalTrex** [comment]
Yes please. I apologize for leaving this open for awhile I didn't notice

**Comment by amukherjee28** [comment]
Thanks @DgitalTrex
