### ISSUE TITLE
db2 resource limitation error while using ibm-db.

### ISSUE THREAD

**Issue by zohebhussain** [ibmdb/python-ibmdb#587]
Hello all,

I have a generic question (not an issue). I am trying to run a big query with (lot of join conditions connecting 15-20 tables). Do we have any limitations in ibm_db while running big queries ? The query has been running in our production environment for more than 15 years. I am able to run the query in a in-home .Net tool. However, while running it using ibm-db in pycharm I keep getting sqlcode -905 resource limitation error. Is there anything I am missing with ibm-db usage ? 

Any insight will be helpful. Thank you for the help.

**Comment by imavo** [comment]
seems to be a cross posted question 
https://stackoverflow.com/questions/65459614/db2-resource-limitation-error-while-using-ibm-db

**Comment by zohebhussain** [comment]
Thank you very much for your response. It was indeed a resource issue. The server was configured to allocate based on the auth ID. I had the resources bumped.
