### ISSUE TITLE
python3-ibm_db vs pip install ibm-db on ibm i

### ISSUE THREAD

**Issue by pgrimard** [ibmdb/python-ibmdb#592]
I've been having trouble installing the latest version of ibm-db on an IBM i.  When I first setup my IBM i to use open source packages, I did so through the open source package manager in IBM Access Client Solutions, which I now know is just yum and can also be accessed from an SSH client.

The ibm-db package installed comes from the rpm python3-ibm_db installed through yum and is currently at version 2.0.5.12.

![image](https://user-images.githubusercontent.com/162011/104773655-655dbf00-5743-11eb-8936-73b6f5a072ca.png)

When I try to install the latest version of ibm-db in a Python virtual environment using pip, it fails with an error about limits.h no such file or directory.

![image](https://user-images.githubusercontent.com/162011/104774108-15332c80-5744-11eb-8ba8-da942010e575.png)

Does the IBM i support the latest version of ibm-db installed via pip, or is it better to install the rpm via yum?  If the latter is the preferred solution, is 2.0.5.12 the most recent version?  It seems that this version is about 5 years old.

My IBM i is running V7R2.

Thanks

**Comment by jkyeung** [comment]
PASE is a lot like a Unix, but is different enough that most packages which need compilation are best built by the folks at IBM (chiefly Kevin Adler). Sometimes you'll get lucky with pip compiling something on its own, but for the most part, if there is an RPM for PASE, that's the one to use.

So yeah, yum-installed 2.0.5.12 is the most recent version, and is the recommended way to use ibm-db from PASE. yum only knows how to install to the system Python, so the prevailing strategy is to use `--system-site-packages` in any of your virtual environments that need an RPM package. Pure-Python packages are of course pip-installable into a venv.

You can sidestep the ibm-db issue entirely by using pyodbc. This leverages the fact that IBM now has an ODBC driver for PASE which is equivalent to the ones for mainstream platforms.

**Comment by pgrimard** [comment]
Continuing the conversation in StackOverflow.
