### ISSUE TITLE
Unable to connect  on Windows 10 [SQL1042C]

### ISSUE THREAD

**Issue by franpss** [ibmdb/python-ibmdb#593]
Hi, I have been trying for several days to connect to a db2 database without success. I've tried different combinations of versions of Python + ibm_db. Even I formatted my computer because it was suggested that this many installations on Python versions may have broken some register.
The weirdest thing is that my coworker, in the same computer model and same conditions as me (Python in a virtual environment, same ibm_db version and the same script used for testing connection) was able to connect without any problem. In my personal computer I had no problem connecting, also using this configurations (and other factors that were suggested too that may be causing the problem, like my internet connection).
I have also tried setting environment variables without success but this seems unnecessary comparing to my coworker and my personal computer.

Any help will be appreciated. This is the error I get with all the different configurations. Actually I have Python 3.8.7 and ibm_db 3.0.2
```
Traceback (most recent call last):
  File "db2.py", line 10, in <module>
    conn=ibm_db.connect(arg1, "", "")
 SQLCODE=-1042M][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004
```

**Comment by amukherjee28** [comment]
Hi,

I would like to ask for few more information regarding the setup/machine.

This error is likely to be caused because of the multiple installation of db2 found on the machine and hence the gskit libraries might be picked up from more that one path.

Are you using the default driver that comes with python ibm_db driver or are your using any different driver by setting the IBM_DB_HOME path.

In case there are multiple installations, can you trying setting the icc64 path of the driver used into PATH environment variable and try running the sample program again.
set PATH=<driver_path>/bin/icc64;%PATH%

Just check if you can set this variable and your application works.

Thanks.

**Comment by franpss** [comment]
> Hi,
> 
> I would like to ask for few more information regarding the setup/machine.
> 
> This error is likely to be caused because of the multiple installation of db2 found on the machine and hence the gskit libraries might be picked up from more that one path.
> 
> Are you using the default driver that comes with python ibm_db driver or are your using any different driver by setting the IBM_DB_HOME path.
> 
> In case there are multiple installations, can you trying setting the icc64 path of the driver used into PATH environment variable and try running the sample program again.
> set PATH=<driver_path>/bin/icc64;%PATH%
> 
> Just check if you can set this variable and your application works.
> 
> Thanks.

Hi, thanks a lot for your response.
Before resetting my computer there was suggested the problem related to the IBM_DB_HOME path, so I setted it without sucess.
Now, my pc is factory reset and deleted everything, and there's only one version of Python (3.8.7). I tried the script before installing anything else but the same error happened

**Comment by Lalitpruthi** [comment]
Hi All,

I am also facing the same above state error..

did you able to resolve it ?

**Comment by franpss** [comment]
@Lalitpruthi Hi, unfortunately I have not been able to solve it yet.

**Comment by imavo** [comment]
If using clidriver,  then in the python site-packages folder on Microsoft-Windows , you will find sub-folders:  ...\clidriver\bin\amd64.VC12.CRT\ 

In ...\clidriver\bin\amd64.VC12.CRT\ are two DLL files.

Copy these files  into a folder that is already on your PATH environment variable when python runs.

Then retry.

**Comment by bimalkjha** [comment]
@franpss Let us know if you are still unable to use ibm_db after following the steps shared by amukherjee28 and imavo . Closing the issue as of now. Thanks.
