### ISSUE TITLE
The command was not processed because the database manager failed to load the following DLL: "gsk8ssl.dll".  SQLSTATE=42724

### ISSUE THREAD

**Issue by nickallenjr** [ibmdb/python-ibmdb#595]
Thanks team for creating this package!

I have an issue which I can't seem to get past. I tried looking through all seemingly related issues for the answer, but had no luck. I am trying to connect to a database using this syntax:

`import os`
`import ibm_db`
`conn_str = "database=<db name>;hostname=<host>;port=<port>;protocol=tcpip;security=ssl;uid=<user>;pwd=<password>"`
`ibm_db_conn = ibm_db.connect(conn_str,'','')`

This is the full trace:

`$ python app.py
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    ibm_db_conn = ibm_db.connect(conn_str,'','')
 SQLCODE=-1109M][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "gsk8ssl.dll".  SQLSTATE=42724
`

I am able to connect through a DB client called DBeaver just fine although I am passing in some extra "params" there such as "sslConnnection, sslTrustStoreLocation, & sslTrustStorePassword". I don't see a option to pass things like that to ibm_db in the api docs. 

Also I am using a JDBC Driver in DBeaver, which could also be part of what I'm missing too.

Please help!!!

**Comment by imavo** [comment]
The jdbc driver is written in java , and that is not used in any way by the python ibm_db module.
Instead python ibm_db uses a CLI driver ( no java code).


Your question does not indicate __which__  CLI driver you are using.  You can use different kinds of CLI driver supplied by IBM, or you can use a third party driver.  

If you did not specifically set IBM_DB_HOME environment variable  ___before__ installing python ibm_db module then you will get the db2cli  driver.  This is a tiny footprint CLI driver (minimal function),  but it __does__ support SSL(TLS)  connections as long as it is correctly configured by you.

That means it's `.../clidriver/bin/icc64` directory must to be on the PATH when python runs, and your connection-string has to be correct. You can find the full path to clidriver via `pip show ibm_db` , it will be under the "Location" directory shown in the result.  

If you want to use a trust store (which is optional)  then you must create and populate a new truststore for CLI (you cannot re-use the java truststore), and reference the truststore and its password in the connection string and indicate which (of possibly) several certificates present in the keystore should be used.  This is configuration and the Db2 Knowledge Centre explains it all , so you have to have the ability to read, comprehend and follow instructions.

But if you only have a single certificate, then you can use a connection attribute `SSLServerCertificate=fully_qualified_path_to_certificate_file;`   (and then you do not need a pre-created truststore ).  Alternatively you can specify this parameter in the db2dsdriver.cfg file  and/or the db2cli.ini for the DSN and database.

Spend the time studying the relevant pages (there are many) in the Db2 Knowledge Centre . Your question has nothing to do with python per se, and everything to do with CLI configuration of a Db2 CLI driver.

**Comment by nickallenjr** [comment]
Thanks for the quick response. I will spend some time reading to understand what I am missing. Since it is not related to this package I will close this issue. Thanks again!
