### ISSUE TITLE
SQLCODE=-1042M][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004

### ISSUE THREAD

**Issue by BenjaminTorresAbarca** [ibmdb/python-ibmdb#599]
Hi,

I am having a problem running the library ibm-db, I had been using this library in other computer but I got a new one and I can not use it.
I also install the library in 3 computers and it run normal but in the new computer is impossible.

Problem:
SQLCODE=-1042M][CLI Driver] SQL1042C  An unexpected system error occurred.  SQLSTATE=58004

I am using windows 10.
I have been trying to use python 3.7.6, 3.8.7 and 3.9.1.
I have been trying to use ibm-db 2.0.8a, 3.0.2 and 3.0.3.

I tried to install visual studio tools c++ 14.0 2015 because I remembered that It was a requirement.

I also restored the computer because I thought that It happened for a configuration and It is the same I just install python and ubm-db.

The differences between my partner' computers and mine is the processor
It works on:
Inter core i5 7th generation
Inter core i5 8th generation
Inter core i7 8th generation

It doesn't work on:
Intel core i7 10th generation.

![evidence](https://user-images.githubusercontent.com/48972481/107110505-005f2b80-680e-11eb-8418-d76f8d232318.PNG)

**Comment by imavo** [comment]
You may be experiencing a known defect that affects some Microsoft Windows configurations.

Use `pip show ibm_db` to find the "Location:" of your site-packages directory.

Suppose for example, that directory is c:\python\lib\site-packages 

Your installation directory will be different, but try to  understand the idea.

Then modify your PATH environment variable to append the following directory to the PATH:

`c:\python\lib\site-packages\clidriver\bin\amd64.VC12.CRT`

(that is, your site-packages path with **\clidriver\bin\amd64.VC12.CRT**  appended to it )

After modifying the PATH, you can retry the python ibm_db database connection.

If you do not have permission to modify the PATH, you can also copy the contents (2 .DLL files) of that amd64.VC12.CRT directory , into another directory that you know will be already on the PATH when python runs.

If you are encrypting your database connections with SSL/TLS, you sometimes also need to add a second directory to the PATH (  ... **site-packages\clidriver\bin\icc64** ) .

**Comment by BenjaminTorresAbarca** [comment]
Now it is working fine, thank you so much!!

**Comment by amukherjee28** [comment]
Thanks @imavo for the explanation.

That was really a detailed explanation of the work around that needs to be done in some distribution of windows.

Thanks.

**Comment by kingsley-3z3nw4k4** [comment]
Experienced same issue 3 years later; solved by applying @imavo's suggestions. Thanks!

**Comment by essancv** [comment]
Hi, I was working fine with ibm-db library and python 3.10 in a Windows 11 system, but, after updating to python 3.13 I'm experiencing the SQL1042C error again. All the recomendations to solve the problem were allready applied so i don´t know what to do now , any suggestion? Thanks
