### ISSUE TITLE
Unable to Connect to database

### ISSUE THREAD

**Issue by waleedqk** [ibmdb/python-ibmdb#600]
I installed the latest `ibm_db` package on a z OS machine using `IBM Open Enterprise SDK for Python 3.9`.

I was able to install the package successfully following the instructions provided and then tried to connect to a local database via the following code:

## Test Code

```
from __future__ import print_function
import os, sys
import ibm_db

def test_local_connect():

    dsn_uid = '********'
    dsn_pwd = '********'
    dsn_database = 'DSN=DB2C'

    try:
        conn = ibm_db.connect(dsn_database, dsn_uid, dsn_pwd)
        print ("Connected to database: ", dsn_database, "as user: ", dsn_uid,)

    except Exception as e:
        print ("Unable to connect: ", ibm_db.conn_errormsg() )
        print ("Error: ", e )


if __name__ == '__main__':

    test_local_connect()
```

## Resulting Output 

Running this code I get the output:

```
Unable to connect:
Error:
```

As can be seen from the output, no message is printed relating to what the error might be when attempting to make the connection.

We tried connecting to the database using a C program to ensure that the database was indeed present and that the ODBC driver related parameters were set correctly. That program was able to connect to the database without any issues.

**Comment by imavo** [comment]
Is USS installed? Is zODBC installed and configured?

**Comment by AWADHAMBIKA** [comment]
Additionally, can you also try with "conn = ibm_db.connect('', '', '')" instead of "conn = ibm_db.connect(dsn_database, dsn_uid, dsn_pwd)"

**Comment by waleedqk** [comment]
Yes, bot USS and zODBC are installed and configured. 

I updated the code from my example above to conn = ibm_db.connect('', '', '') and still got the same output.

**Comment by amukherjee28** [comment]
I just tried the above example in my environment.

PIP LIST
--------------

 pip3 list
Package      Version
------------ -------
cffi         1.14.0
cryptography 2.8
ebcdic       1.1.1
**ibm-db       3.0.3**
numpy        1.18.2
pip          20.1.1
pycparser    2.20
setuptools   46.4.0
six          1.15.0
zos-util     1.0.0


SAMPLE CODE
---------------------

from __future__ import print_function
import os, sys
import ibm_db

def test_local_connect():
    try:
        conn = ibm_db.connect('','','')
        print ("Connected to database: ")

    except Exception as e:
        print ("Unable to connect: ", ibm_db.conn_errormsg() )
        print ("Error: ", e )


if __name__ == '__main__':

    test_local_connect()


OUTPUT SEEN
---------------------

python3 test_connect.py
Connected to database:


I am able to connect without hitting any error.

Please check if you have the following environment variables configured as mentioned in the zODBC documentation.

export STEPLIB=RSQA.DSNC10.SDSNLOAD
export STEPLIB=RSQA.DSNC10.SDSNLOD2:$STEPLIB
export STEPLIB=<SSID>.SDSNEXIT:$STEPLIB
export DSNAOINI=$HOME/odbc.ini
export IBM_DB_HOME='RSQA.DSNC10'

Please have a look once if something is missing as part of the prerequisite in the below mentioned doc link:

https://github.com/ibmdb/python-ibmdb/blob/master/install.md

**Comment by AWADHAMBIKA** [comment]
Please add below as part of your ODBC configuration for additional logs:
APPLTRACE=1
DIAGTRACE=1
DIAGTRACE_NO_WRAP=0
APPLTRACEFILENAME="DD:APPLTRC"

e.g.
[COMMON]
MVSDEFAULTSSID=$SUBSYSTEM
CONNECTTYPE=2
APPLTRACE=1
DIAGTRACE=1
DIAGTRACE_NO_WRAP=0
APPLTRACEFILENAME="DD:APPLTRC"
CURRENTAPPENSCH=UNICODE
FLOAT=IEEE

**Comment by AWADHAMBIKA** [comment]
Alternatively, you can create a shell script with below content and use it to run your test program:
`#!/bin/sh

export _BPXK_JOBLOG=STDERR
export FILEPREFIX=${1:-}

export IBM_DB_HOME='XX.XXXX'
export SUBSYSTEM=XXXX
export STEPLIB=$SUBSYSTEM.SDSNEXIT:$IBM_DB_HOME.SDSNLOD2:$IBM_DB_HOME.SDSNLOAD

export DSNAOINI="$HOME/ODBC_${HOSTNAME}_${SUBSYSTEM}_CAF"
touch $DSNAOINI
chtag -t -c 1047 $DSNAOINI
cat <<EOF >$DSNAOINI
[COMMON]
MVSDEFAULTSSID=$SUBSYSTEM
CONNECTTYPE=2
APPLTRACE=1
DIAGTRACE=1
DIAGTRACE_NO_WRAP=0
APPLTRACEFILENAME="DD:APPLTRC"
CURRENTAPPENSCH=UNICODE
FLOAT=IEEE
[$SUBSYSTEM]
MVSATTACHTYPE=RRSAF
PLANNAME=DSNACLI
[$HOSTNAME$SUBSYSTEM]
AUTOCOMMIT=1
EOF
chtag -b $DSNAOINI # we have to tag as binary, so that ODBC can read it, since python's program ccsid is ascii

python3 odbc_test.py`

**Comment by waleedqk** [comment]
Tried to run with the following files:

### Python Test

```
from __future__ import print_function
import os, sys
import ibm_db

SCRIPT_DIR, SCRIPT_NAME = os.path.split(os.path.abspath(__file__))
PARENT_DIR = os.path.dirname(SCRIPT_DIR)
filename = __file__

def test_local_connect():

    dsn_uid = '********'
    dsn_pwd = '********'
    dsn_database = 'DSN=DB2C'

    try:
        # conn = ibm_db.connect(dsn_database, dsn_uid, dsn_pwd)
        conn = ibm_db.connect('', '', '')
        print ("Connected to database: ", dsn_database, "as user: ", dsn_uid,)

    except Exception as e:
        print ("Unable to connect: ", ibm_db.conn_errormsg() )
        print ("Error: ", e )


if __name__ == '__main__':
    print("Running {}".format(SCRIPT_NAME))

    test_local_connect()
```

### Config File

Parameters set in the ini file and set to binary via `chtag -b`

```
[COMMON]
MVSDEFAULTSSID=DB2C
CONNECTTYPE=2
APPLTRACE=1
APPLTRACEFILENAME="~/trace.log"
MULTICONTEXT=1
CURRENTAPPENSCH=ASCII
FLOAT=IEEE
THREADSAFE=1
APPLTRACE=1
DIAGTRACE=1
DIAGTRACE_NO_WRAP=0
[DB2C]
PLANNAME=DSNACLI
MVSATTACHTYPE=RRSAF
```

### Script to Run

Shell script to set and run the python code:

```
unset PYTHONHOME

export _BPXK_JOBLOG=STDERR
export _BPXK_AUTOCVT='ON'
export _CEE_RUNOPTS='FILETAG(AUTOCVT,AUTOTAG) POSIX(ON) XPLINK(ON)'
export _TAG_REDIR_ERR='TXT'
export _TAG_REDIR_IN='TXT'
export _TAG_REDIR_OUT='TXT'

export IBM_DB_HOME=SHARE.******.*****
export STEPLIB=$IBM_DB_HOME.SDSNLOAD
export STEPLIB=$IBM_DB_HOME.SDSNLOD2:$STEPLIB
export STEPLIB=$IBM_DB_HOME.SDSNEXIT:$STEPLIB

export DSNAOINI="~/odbc.ini"

export PATH="${PYTHON_DIR}/bin:${PATH}"
export LIBPATH="${PYTHON_DIR}/lib:${LIBPATH}"
alias python3="${PYTHON_DIR}/bin/python3"

rm -rf venv && python3 -m venv  venv --system-site-packages

source ./venv/bin/activate

python -m pip install ibm-db

python db2_test_conn.py
```

I get the same output. 

The contents of the `~/trace.log`file remain empty.

**Comment by AWADHAMBIKA** [comment]
As discussed, please verify the SubSystem being used and update the same in your .INI file and let us know if the issue is resolved.

**Comment by waleedqk** [comment]
By setting the STEPLIB with the SubSystem and setting the appropriate name+location for the DSNAOINI file I was able to connect to the database successfully. 

```bash
export IBM_DB_HOME='XX.XXXX'
export SUBSYSTEM=XXXX
export STEPLIB=$SUBSYSTEM.SDSNEXIT:$IBM_DB_HOME.SDSNLOD2:$IBM_DB_HOME.SDSNLOAD

export DSNAOINI="$HOME/ODBC_${HOSTNAME}_${SUBSYSTEM}_CAF"
```
