### ISSUE TITLE
Latest Updates does not list 3.0.3

### ISSUE THREAD

**Issue by pdbossman** [ibmdb/python-ibmdb#602]
The "latest updates" section mentions June 2020, and not the recent updates.

**Comment by AWADHAMBIKA** [comment]
Hi Patrick,
I can see 3.0.3 in the latest release section i.e. https://github.com/ibmdb/python-ibmdb/releases and even on the home page.

Are you referring to the same place or somewhere else? Kindly let us know.

**Comment by bimalkjha** [comment]
@pdbossman We also observed this issue about release of version 3.0.3 and fixed it on github page. The latest code on git has fixed this issue and it will be corrected in next release. Thanks.
