### ISSUE TITLE
IBM Data Virtualization SSL Connection in IBM_DB

### ISSUE THREAD

**Issue by bachhaniaman** [ibmdb/python-ibmdb#603]
Hello Team,

Unable to make a SSL connection with CP4D DV.

 conn=ibm_db.connect("DATABASE=bigsql;HOSTNAME=123.45.5.2;PORT=30839;PROTOCOL=TCPIP;UID=admin;PWD=<>;SSL=true;SSLServerCertificate=E:\certificate.pem;",'','')
    connState = ibm_db.active(conn)
    connpd = ibm_db_dbi.Connection(conn)

SQLCODE=-30081t established sucessfully [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".

**Comment by bimalkjha** [comment]
@bachhaniaman What is the output of db2level command? Let us know if you are using your own db2 client pointed out by IBM_DB_HOME environment variable or not.
Communication error indicates that either the PORT values is not an SSL port or SSL port is not activated on server. Please verify the SSL port and use it. Also, share the complete output of "db2 get dbm cfg" command from bigsql server which will have details about SSL and TCPIP port is set or not. Thanks.
