### ISSUE TITLE
ibm_db.execute_many with prepared statement and values as tuple-of-tuples does not seem to work with only a single parameter

### ISSUE THREAD

**Issue by sebschlue** [ibmdb/python-ibmdb#619]
If there is a table like

```
ibm_db.exec_immediate(ibm_db2_con, 'CREATE TABLE "TEST" ("ID" INTEGER NOT NULL, "C1" VARCHAR(8192)) IN "USERSPACE1"')
```

and a bulk update like

```
update_statement = 'UPDATE "TEST" SET "C1" = ? WHERE "ID" = ?'
update_prepared_statement = ibm_db.prepare(ibm_db2_con, update_statement)
ibm_db.execute_many(update_prepared_statement, tuple([tuple(x) for x in df.values]))
```

where df is a Pandas Dataframe containing the rows "C1" and "ID"

and given that `tuple([tuple(x) for x in df.values])` creates the necessary tuple-of-tuples containing values

then this works fine without problems.

What does NOT work is the following:

```
delete_statement = 'DELETE FROM "TEST" WHERE "ID" = ?'
delete_prepared_statement = ibm_db.prepare(ibm_db2_con, delete_statement)
ibm_db.execute_many(delete_prepared_statement, tuple([tuple(x) for x in df.values]))
```

In this case, there is only one parameter and the Dataframe df contains column "ID" only.

This leads to error

```
Error 10: Binding Error 1:  
Error 11: [IBM][CLI Driver] CLI0125E  Function sequence error. SQLSTATE=HY010 SQLCODE=-99999
```

Surprisingly, what DOES work is the following:

```
delete_statement = 'DELETE FROM "TEST" WHERE "ID" = ? AND "C1" = ?'
delete_prepared_statement = ibm_db.prepare(ibm_db2_con, delete_statement)
ibm_db.execute_many(delete_prepared_statement, tuple([tuple(x) for x in df.values]))
```
In this case, there are two parameters and the Dataframe df contains columns "ID" and "C1".

In theory, the tuple-of-tuples data-structure works just as well if there is only one row.

If printed to the console it would look like something similar to:

```
((1,), (2,), (3,), (4,), (5,), (6,), (7,), (8,), (9,), (10,))
```

So, at the moment, this looks like a bug to me.

Is this a known thing?

Is some special treatment necessary if there is only one parameter?

**Comment by sebschlue** [comment]
What's even weirder is that it DOES work even with a single parameter if

```
tuple(df.itertuples(index=False, name=None))
```

is used instead of

```
tuple([tuple(x) for x in df.values])
```

although in theory both should be interchangeable.

Or shouldn't they? I am totally confused now. Maybe somebody can shed some light into this issue :)

**Comment by imavo** [comment]
could you give a standalone minimal complete example, that i can just run to demonstrate the issue?

**Comment by bimalkjha** [comment]
@sebschlue You need to modify your query and use IN instead of = as: `delete_statement = 'DELETE FROM "TEST" WHERE "ID" IN ?'` . Let us know the result. Thanks.

**Comment by amukherjee28** [comment]
@sebschlue Do you any update on this after updating the query as suggested in the above response.
