### ISSUE TITLE
Validation Fails on Connect with  SQL1598N...SQLSTATE=42968

### ISSUE THREAD

**Issue by neoEvol** [ibmdb/python-ibmdb#623]
My issue appears nearly identical to https://github.com/ibmdb/python-ibmdb/issues/516:
I'm using ibm_db python to to db2 for z/OS on an ubuntu 18.04 - everything works fine using .cfg and .ini files.

I need to build out new machine using ubuntu 20.04.  I'm using newer version (ibm-db,3.0.4) and i've copied over the .cfg and .ini from first machine.  i do validation in sequence:
./db2cli validate  <- success
./db2cli validate -dsn <myDSN>  <- success, everything looks in line
./db2cli validate -dsn <myDSN> -connect   <- console message:
[FAILED]: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968

when i look in the trace, its like the connection is killed before its made.

I'm not using db2Connect.  i'm trying to hit db2 for z/os alias endpoint as i can with the 18.04 and my local windows machine.

Is there any easy thing that came out of the 516 issue that i can try before sending off a trace to you?

what do you think?

Thanks a bunch

**Comment by neoEvol** [comment]
oh ya - the 18.04 version is using py3.7 and my 20.04 is using py3.8.  i see that should be an issue, but i wanted to point that out as well.
ty

**Comment by bimalkjha** [comment]
@neoEvol Probably you miss to copy the `license/db2con*.lic` file from your 18.04 to 20.04 machine. SQL1598N says, your new system do not have this license file. Thanks.

**Comment by neoEvol** [comment]
Thanks so much - where do you get this from?  i don't believe i adjusted any license file last time.  i certainly didnt on my windows machine and i can connect both secure and unsecure just fine.

What do you think?

**Comment by bimalkjha** [comment]
@neoEvol Do you mean you do not see `license\db2con*.lic` file on 18.04 system and willing to get it? We can get db2connect license file from IBM Support. IBM employees need to send an email to connomon@us.ibm.com to get it. Thanks.

**Comment by neoEvol** [comment]
@bimalkjha here is that dir when i compare:


![version_compare](https://user-images.githubusercontent.com/67710721/115564745-c1763900-a286-11eb-8042-3ca398a912fd.jpg)

i will do what i need to do to make this work correctly.  I need to ask - what changed?  why do i need this special file now?  i thought if the server was setup to accept this traffic, then client just needs db2cli (along with credentials, of course).

I'm trying to understand why my old setup works and the new one doesn't.  i'm sure i never implemented a special license file before - not on linux or windows.  i can connect both unsecurely and securely with those setups, no probs works great.  with this new version, im getting yelled at about a license.  We have direct contacts at db2 for z/OS, but im just curious what changed, and why do i need a special license file now?

Thanks again for your patience.

Best,

**Comment by neoEvol** [comment]
Hello,
I'm working with internal team on acquiring license file.  I will update when that works.
I'm still scratching my head how this worked before with previous versions but not now with the current one...

**Comment by SabaKauser** [comment]
Hi @neoEvol 
CLI license is version based. Hence, if your earlier installation had clidriver at level V11.1, and hence the license at this level, it will not work with new installation as it comes with V11.5 version and you will need a license from this level.

**Comment by neoEvol** [comment]
Hey @SabaKauser , thanks for the response.
I get what you're saying, but i've built out 4 stand-alone vms using ibm_db, and never had to adjust a .lic file, but now with this one i do.  it's ok, i'm working with internal team at the moment, and i believe we'll get through with the license file.

That said, can you please provide doc on how to manage this file?  is the correct location for in `...clidriver/license/db2con*.lic`?

**Comment by neoEvol** [comment]
@SabaKauser 

Here’s why I’m still scrathcing my head – we’re apparently using db2 connect unlimited for system z, with the server license option, I just found the doc here:
https://www.ibm.com/docs/en/db2/11.5?topic=drivers-validating-data-server-driver-package-windows-installation

‘If you are using Db2 Connect Unlimited Edition for z/OS®, you can use a server-based license key. This one step prevents the need for client-based license keys. For details, see the topic about activating the license key for Db2 Connect Unlimited Edition for System z®. ’

I’m sure this is why I haven't had to deal with a license file before.

What do you think?

**Comment by imavo** [comment]
@neoEvol - 

licenses (for IBM supplied drivers) for CLI access to Z/os or i-series  can be :

(1) client-based (i.e the license file is on the workstation running the cli app e.g. python ibm_db ), 
 or 

(2)  Z/os subsystem based (if the subsystem has had db2connectactivate configured, and in this case no client side license file is needed),  or 

(3) handled via a Db2-connect-gateway (in which case no client side license is needed).

So there are two different ways to avoid client side licensing.

**Comment by neoEvol** [comment]
we had to update license file on server, and now i can connect =)

thanks for all you do!!
