### ISSUE TITLE
Dependent module libdb2.a(shr_64.o) could not be loaded

### ISSUE THREAD

**Issue by brittomoses** [ibmdb/python-ibmdb#624]
Running from IBM i, On importing IBM_DB getting this error,
![screenshot](https://user-images.githubusercontent.com/17372625/115461596-985a9780-a1f7-11eb-82de-893ba6e0fe7e.png)

**Comment by imavo** [comment]
Looks like AIX.  The LIBPATH environment variable needs to include the directory that contains libdb2.a.

We cannot tell from the question whether the clidriver is being used or a pre-existing Db2-client is being used.

If it is a pre-existing Db2-client, with a db2profile, normally the shell session (or shell startup script) would dot in the correct db2profile which would set all required environment variables, before running any program (like python) that tries to use Db2.

**Comment by brittomoses** [comment]
@amukherjee28 @imavo It is from IBM i not AIX

@imavo It is not a pre-existing Db2 Client, How do I check if clidriver is used?

**Comment by imavo** [comment]
Did you already have a Db2-client installed before installing python ibm_db ?   

Did you set the IBM_DB_HOME environment to the pre-existing db2-client directory, before installing ibm_db?   

Are there any db2 directories on your PATH ? 

If the answer to all three questions is NO, then it may be using clidriver, and `pip3 show ibm_db` will show the site_packages directory location name, under which is 'clidriver/lib/' which should have all required libdb2* files. 

You can put the fully-qualified-path of the clidriver/lib directory on the LIBPATH before running python.

**Comment by brittomoses** [comment]
Added the clidriver to the LIBPATH, getting this error now
Traceback (most recent call last):                                                                                               
  File "<stdin>", line 1, in <module>                                                                                            
ImportError:    0509-022 Cannot load module /QOpenSys/pkgs/lib/python3.6/site-packages/clidriver/lib/libdb2.a(shr_64.o).         
        0509-150   Dependent module libcfg.a(shr_64.o) could not be loaded.                                                      
        0509-022 Cannot load module libcfg.a(shr_64.o).                                                                          
        0509-026 System error: A file or directory in the path name does not exist.                                              
        0509-022 Cannot load module /QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db.so.                                        
        0509-150   Dependent module /QOpenSys/pkgs/lib/python3.6/site-packages/clidriver/lib/libdb2.a(shr_64.o) could not be loaded.

**Comment by amukherjee28** [comment]
Mean while @kadler can you take a look at this once.

**Comment by kadler** [comment]
If you want to run ibm_db on IBM i, I suggest using our pre-build rpms: `yum install python3-ibm_db` or installing from our fork: https://github.com/kadler/python-ibmdb

**Comment by bimalkjha** [comment]
@brittomoses It seems libcfg package is missing from your system. Probably you need to install aix-fileset-upgrade-aix-7_1-bos.rte.libcfg package: https://www.rapid7.com/db/vulnerabilities/aix-7_1-u847683/
If still facing issue, then please share complete output of `ldd /QOpenSys/pkgs/lib/python3.6/site-packages/clidriver/lib/libdb2.a` command. Probably you need to install xlc16 in your system by following this doc: https://www.ibm.com/support/pages/ibm-xl-cc-runtime-aix-161#DNLD
Thanks.

**Comment by brittomoses** [comment]
@Kadler I'm trying to use Django with that, with yum it installs the older package which gives out the error AttributeError: module 'ibm_db_dbi' has no attribute 'BOOLEAN'

@bimalkjha It is IBM i system not AIX, wont be able to install that PTF and not able to use ldd.

**Comment by amukherjee28** [comment]
Hi @brittomoses 

The BOOLEAN error on Django you are facing is from the latest django version 1.4.0.0 which requires boolean support from ibm_db to allow the migrations to happen. This fix has gone in the regular ibm_db latest release 3.0.4.

However on i-series when you are installing the ibm_db using the yum install command the boolean fix in that package might not be present and hence the error.

My suggestion to you would be to install ibm_db_django using the following set of commands

pip install django==2.0
pip install ibm_db_django==1.2.0.0

This combination should allow you to move forward with django migrations.

**Comment by kadler** [comment]
@bimalkjha there is no libcfg.a on IBM i.

@brittomoses we have started work on an IBM i-specific Django adapter at https://github.com/IBM/django-ibmi using the IBM i Access ODBC driver. That is probably your best bet in the long term.

**Comment by brittomoses** [comment]
@amukherjee28 Installed the old versions, that did not give the Boolean error but gives me django.db.utils.InterfaceError: IBM i does not support DSN keywords 'HOSTNAME' error. I think i'll have to use just ibm_db and connect to database instead of connecting through django.

@kadler Sound good, do you know when this would be available?

**Comment by amukherjee28** [comment]
Hi @brittomoses yes the current django adaptor is not supported for IBM i. You have to go with ibm_db connections for now and wait the django adaptor to come up on IBM i.

@kadler thank you for your help and providing us with the necessary information.

**Comment by brittomoses** [comment]
Thanks everyone for the help

**Comment by amukherjee28** [comment]
Can we close this issue then?

**Comment by brittomoses** [comment]
@amukherjee28 yes, you can close this. Thanks.
