### ISSUE TITLE
ascii codec error if column name a chinese name

### ISSUE THREAD

**Issue by enjoyenzi** [ibmdb/python-ibmdb#628]
I ran into a problem when I used ibm_db_dbi. The data returned normally, but the column names did not

db2codepage  is  GBK
`
import ibm_db_dbi

link = "DATABASE=aaa;PORT=50000;PROTOCOL=TCPIP;PWD=aaa;UID=aaa;HOSTNAME=11.111.1.111"

con = ibm_db_dbi.connect(link,'','')

cur = con.cursor()

cur.execute("with a as( select '中文' a ,1 b from sysibm.dual ) select a,b from a")

columns1 = cur.description

rows1 = cur.fetchall()

cur.execute("with a as( select '中文' a ,1 b from sysibm.dual ) select a,b 中文列名  from a")

rows2 = cur.fetchall()

columns2 = cur.description

cur.close()
con.close()
`

error：
  columns2 = cur.description
  File "c:\program files\python37\lib\site-packages\ibm_db_dbi.py", line 1124, in __get_description
    raise self.messages[len(self.messages) - 1]
Error: ibm_db_dbi::Error: UnicodeDecodeError('ascii', b'\xd6\xd0\xce\xc4\xc1\xd0\xc3\xfb', 0, 1, 'ordinal not in range(128)')

I checked the source code and try to get column name from ibm_db.field_name(cur.stmt_handle,1)
the same error occur

and then i found ibm_db.h file code,  I guess error occur because of 
`
(7142row)  return StringOBJ_FromASCII((char*)stmt_res->column_info[col].name);
`
I don't know C language

**I want to know how to extract the column name from the cur.stmt handle**
thanks

**Comment by amukherjee28** [comment]
Hi, We are looking into this.

Will get back with more details.

Thanks

**Comment by amukherjee28** [comment]
Hi @enjoyenzi 

We have analyzed the issue.

Unicode support needs to be added and we will try and add this support in the next release.

**Comment by enjoyenzi** [comment]
> 
> 
> Hi @enjoyenzi
> 
> We have analyzed the issue.
> 
> Unicode support needs to be added and we will try and add this support in the next release.

thank you very much

**Comment by kyokonishito** [comment]
Hi @amukherjee28 

I have same issue with column names  having Japanese characters.
When do we get the next release including the fix of this issue? Thanks!

**Comment by amukherjee28** [comment]
@kyokonishito @enjoyenzi 
Can you please if the issue has been resolved in the latest release.

**Comment by enjoyenzi** [comment]
get jumbled in 3.1.1
