### ISSUE TITLE
ibm_db and ibm_db_dbi Python Package compatability for z/OS Unix System Services?

### ISSUE THREAD

**Issue by dperrau** [ibmdb/python-ibmdb#629]
Today we are able to access data contained within Db2 for z/OS using Windows Python and connecting with ibm_db via Db2 DDF, since it's c/c++ code is pre-compiled into executables in Windows distributions.

However to replicate this process leveraging Python for z/OS and in USS, it ends with error messages "the C/C++ feature of z/OS is not enabled."

**My Question:** understanding that there is **No** c++ compiler installed on z/OS, is there a way (or a plan) to get the Python Packages ibm_db and ibm_db_dbi implemented for use in z/OS Unix System Services?

Thanks, Dave

**Comment by bimalkjha** [comment]
@dperrau We provide precompiled binary only for Windows platform. Rest all platforms including z/OS, must have c++ compiler to install ibm_db or ibm_db_dbi package. Thanks.

**Comment by dperrau** [comment]
> 
> 
> @dperrau We provide precompiled binary only for Windows platform. Rest all platforms including z/OS, must have c++ compiler to install ibm_db or ibm_db_dbi package. Thanks.

Thanks bimalkjha for the information -- 2 follow-up questions for some more details, so that I can better explain the situation to others:

1) What are the reason(s) that there is no binary for z/OS?  (any technical or financial concerns?) 
2) If a precompiled binary for z/OS would be considered for development, would that development activity come from the IBM Db2 Lab team in San Jose or somewhere else?

**Comment by amukherjee28** [comment]
Hi @dperrau 

Let me help you with your queries.

1. For non windows we rely on the compilation at run time to generate binaries. The main reason being the diversity of the platforms that is being supported. Having precompiled binaries for all of these platforms is very difficult to maintain and hence we provide pre-compiled binaries only for windows.
2. In case we decide to have pre-compiled binary for ZOS,  it would be done from our end only as we maintain the release of this driver.

I hope I am able to provide the necessary input to your queries.

Thanks

**Comment by amukherjee28** [comment]
Hi @dperrau 

Were we able to provide a proper response to your queries. In case you have any more question please feel free to comment else can we close on this issue.

Thanks

**Comment by dperrau** [comment]
> Hi @dperrau
> 
> Were we able to provide a proper response to your queries. In case you have any more question please feel free to comment else can we close on this issue.
> 
> Thanks

Thanks everyone for their thorough replies to my inquiries.  Feel free to close this issue.
Dave
