### ISSUE TITLE
Sev-1 Critical: Python IBM DB Takes ~3 - 5 minutes to connect to server (Production DB2 Server)

### ISSUE THREAD

**Issue by mgfos207** [ibmdb/python-ibmdb#630]
When attempting to connect to a db2 instance the connection takes up to 5 minutes to connect using the ibm_db api. Not getting the same behavior with other db2 instances just this one in particular.

**Comment by amukherjee28** [comment]
Hi @mgfos207 

What kind of instance are you connecting to could you please provide some details on the same.

Could you please also explain when you say "other db2 instances".

Thanks

**Comment by mgfos207** [comment]
Hello @amukherjee28 we are using an ibm cloud db2 instance. The name of the instance that is taking a while to connect to is Db2-FantasyFootballProd (Enterprise), while another db2 instance Db2-FantasyFootballDev (Standard) connects within a few seconds.

**Comment by amukherjee28** [comment]
Hi,

Looks like we need to take a look into the TCPIP trace and check the time stamp from the trace to understand what's causing the delay in connection to the server instance.

Can you please perform the following steps with each connection and send me back the trace files after running the connection with both the server instances.

STEPS TO FOLLOW

1. Set the PATH to adm folder of the clidriver
export PATH=<path_to_clidirver>/adm:$PATH

2. START the trace
```
db2trc on -perfcount -t
```

3. Once the trace is started run the application to connect to one of the server instance.

4. NOW stop the trace and collect the trace files.
```
db2trc dmp perf.dmp
db2trc off
db2trc perffmt perf.dmp perf.out

Please perform the above steps with both the server instances and send me the two perf.out files captured.

This will help us to under stand what's causing the delay in connection.

Thanks.

**Comment by mgfos207** [comment]
@amukherjee28 I'm not available to get db2trc to work on my docker container. Is it possible that we can jump on a call I'm available via slack.

**Comment by amukherjee28** [comment]
PMR CLOSED hence closing the issue.
