### ISSUE TITLE
Failed to Connect to Db2 database on Cloud using Python.

### ISSUE THREAD

**Issue by Talha-Javed965** [ibmdb/python-ibmdb#633]
I am using python version 3.9.4. When I import ibm_db on my jupyter notebook it gives me error message
"ModuleNotFoundError     Traceback (most recent call last)
<ipython-input-7-fe3bb08c8a05> in <module>
----> 1 import ibm_db
ModuleNotFoundError: No module named 'ibm_db'"

I have tried to install ibm_db using " pip install ibm_db    "  but not able to get successful installation

Please guide me what issue could be and how to resolve it!

Thanks

**Comment by imavo** [comment]
please edit your question to give more details about the version of the jupyter and ipython components (or show the text output of `pip freeze` ).  Also detail the operating-system build and version and name. Also if you are using anaconda please give its version.

**Comment by amukherjee28** [comment]
Hi @Talha-Javed965 

Do you still the issue?
In case can you please provide the details in the previous comment.

**Comment by amukherjee28** [comment]
Please open a new issue in case you still have the issue. Closing this issue for now.
