### ISSUE TITLE
Issues installing ibm_db with python3 for use with Django

### ISSUE THREAD

**Issue by jsiebrand** [ibmdb/python-ibmdb#635]
Install of ibm_db, requires Python.h.

This requires python3-devel to be installed 

yum install python3-devel -y

The User install with pip, usr/lib/python3.6/site-packages requires that the /usr/lib/python3.6/site-packages be 777 so that the file README.md could be copied in.

Error returned:

error: could not create '/usr/lib/python3.6/site-packages/README.md': Permission denied

**Comment by imavo** [comment]
please mention your distro, and your distro version.

It is important to ensure that you always have the most recent version of pip before using pip for any installation. Use `pip install --upgrade pip`  , and then retry.

**Comment by amukherjee28** [comment]
Since we are getting lot of issues being reported on this, I have updated the readme to have a documentation on how to handle this particular installation issue.

Please refer to the Readme.md documentation :

https://github.com/ibmdb/python-ibmdb#KnownIssues

**Comment by amukherjee28** [comment]
Hi @jsiebrand 

Did the above resolution work for you or do you still have any issues?
Please let us know.
