### ISSUE TITLE
error: could not create '/usr/lpp/python39/lib/python3.9/site-packages/README.md': EDC5141I Read-only file system.

### ISSUE THREAD

**Issue by RabasMa1** [ibmdb/python-ibmdb#636]
Hi,

the install tries to copy README.md to site-packages instead of $HOME/.local/lib//site-packages.
and fails because site-packages is READ-ONLY.
what can I do?

byte-compiling /home/txxxxxx/.local/lib/python3.9/site-packages/ibm_db_tests/test_warn.py to test_warn.cpython-39.pyc
    running install_data
    copying ./README.md -> /usr/lpp/python39/lib/python3.9/site-packages
    error: could not create '/usr/lpp/python39/lib/python3.9/site-packages/README.md': EDC5141I Read-only file system.
    Running setup.py install for ibm-db ... error
ERROR: Command errored out with exit status 1: /usr/lpp/python39/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.
argv[0] = '"'"'/TN01/tmp/pip-install-j3iq8ro1/ibm-db_6caaf4f526bb4db7bf787587b29b0d44/setup.py'"'"'; __file__='"'"'/TN01/tmp/pip-install-j3iq8ro1/ibm-db_6caaf4f526bb4db7bf787587b29b0d44/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /TN01/tmp/pip-record-o93sck63/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/txxxxx/.local/include/python3.9/ibm-db Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/txxxxxx/.local/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 825, in install

(.local) /home/txxx ==> python --version
Python 3.9.0
(.local) /home/txxx ==> pip3 --version
pip 21.1.2 from /home/txxx/.local/lib/python3.9/site-packages/pip (python 3.9)
platform is z/OS 2.4
ibm_db is 3.0.4

**Comment by imavo** [comment]
What was the exact full command-line you used to install ibm_db?
Suggestion:   `pip3 install --user  ibm_db`

**Comment by amukherjee28** [comment]
The installation tries to copy all required files into pip site-packages folder in case of normal installation
```pip install ibm_db```

However in case of local user specific installation files get copied into a local site-packages.

The expectation here is to have proper access to these folders.

**Comment by amukherjee28** [comment]
Hi @RabasMa1

Did the above explanation work for you or do you still have any more queries?
