### ISSUE TITLE
Offline installation of ibm_db on linux

### ISSUE THREAD

**Issue by edwardrana** [ibmdb/python-ibmdb#638]
Following the directions to install without downloading the linuxx64_odbc_cli.tar.gz file. I'm in a corporate environment where I do not have internet access on the dev servers.

I placed the drivers in /opt/clidriver
Set up the env variables:
IBM_DB_HOME=/opt/clidriver
LD_LIBRARY_PATH=/opt/clidriver/lib

used pip install ibm_db
and the package builds.

But cannot import ibm_db in python
ImportError : /opt/middleware/anaconda_python/3/6/10/lib/python3.6/site-packages/ibm_db.cpython-36m-x86_64-linux-gnu.so: undefined symbol: SQLGetFunctions

Any suggestions on this offline install?

**Comment by amukherjee28** [comment]
Are you using Anaconda distribution of python?
In case can you mention the mention the python version.

Also are you using any virtual environment while running the python programs ?

Another concern is if your environment do not have internet access how is pip install working ?

**Comment by edwardrana** [comment]
In our corporate environment we are using anaconda python, with python version 3.6.10
No virtual environment. I'm calling python directly using the install path of /opt/middleware/anaconda_python/3.6.10/bin
We use jfrog Artifactory which acts like a proxy to pipy.org. Any pip install requests passes through this proxy for purposes of capturing any external downloads.

**Comment by imavo** [comment]
pip will install dependencies without detailed checking of version compatibilities, which can result in symptoms like yours .  Please mention the version of your `conda` and your distro-name-and-version,

**Comment by amukherjee28** [comment]
Hi @edwardrana 

Please let us know if this can be closed. Are you still facing the issue?
