### ISSUE TITLE
Minor mistake in the example in README

### ISSUE THREAD

**Issue by karl-otto** [ibmdb/python-ibmdb#641]
Hello,
I tried to follow your [example](https://github.com/ibmdb/python-ibmdb/blob/master/README.md) and recognizes two mistakes around „Tables API“.

1.  Schema name

    The schema is set to `db2admin` (`conn.tables('DB2ADMIN', '%')`) and the result should contain the user's table.
    
    But the connection is done as user `db2inst1` and the table is created without specifying a schema. Thus, the table is created in the schema of the user (in this case `db2inst1`).

    Suggested syntax:
    ```sql
    conn.tables('DB2INST1', '%')
    ```

2.  Placement of the example to show access to Tables API

    When one follows along the procedure an empty result is returned. Contrary to the shown output for `db2admin.mytable`. This is because the table is created in the step after.

    Thus, it would be helpful placing this statement later in the procedure (Suggestion: after inserting values).

3.  [_Suggestion_] Add a new function call for dropping `mytable`, so one can redo the example without an error (`mytable` already exists). Best location would be at the end, just before termination of the connection.

    ```sql
    # Drop table "mytable" using ibm_db
    drop = 'DROP TABLE mytable'
    stmt_delete = ibm_db.exec_immediate(ibm_db_conn, drop)
    # <empty>
    ```

Kind regards from Germany

**Comment by amukherjee28** [comment]
Hi @karl-otto 

Thanks for the suggestion and the observation.

Will take a look into the example and make necessary changes in order to make the user experience better.

**Comment by amukherjee28** [comment]
Suggestion modified to readme file.
