### ISSUE TITLE
Segmentation Fault: 11 when use ibm_db.connect() to connect DB2 on IBM Cloud

### ISSUE THREAD

**Issue by alanzyt311** [ibmdb/python-ibmdb#644]
Hi @amukherjee28 , I create a new issue and we could continue here.

Here's my trace file. Could you help and have a look on it? The issue is Segmentation Fault: 11 with MAC OS.
[trc.zip](https://github.com/ibmdb/python-ibmdb/files/6860511/trc.zip)

You mentioned that

> I did go through the trace files and what I see that at the connection level itself your application is crashing and not moving forward.

So any suggestion on handling this crashing problem? Thx.

**Comment by amukherjee28** [comment]
@alanzyt311 

From the trace the connection string used is :

SQLDriverConnectW( hDbc=0:1, hwnd=0:0, szConnStrIn="DRIVER={IBM DB2 ODBC DRIVER};**DATABASE=BLUDB;HOSTNAME=6f299df0-4db1-4b58-92d3-95eeb7b0ec3c.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud;PORT=31257;PROTOCOL=TCPIP;UID=0097acec;PWD=****************;"**, cbConnStrIn=197, szConnStrOut=<NULL pointer>, cbConnStrOutMax=0, pcbConnStrOut=<NULL pointer>, fDriverCompletion=SQL_DRIVER_NOPROMPT )
    ---> Time elapsed - -8.081421E+008 seconds

Can you try using the SSL connection string to connect to IBM Db2 on cloud.

In the connection string you need to change the following
DATABASE=BLUDB;HOSTNAME=6f299df0-4db1-4b58-92d3-95eeb7b0ec3c.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud;PORT=<USE SSL PORT>;PROTOCOL=TCPIP;UID=0097acec;PWD=****************;SECURITY=SSL";

Can you try this once.

**Comment by alanzyt311** [comment]
Now it works for the SSL connection by using your conn string! 

Thx a lot for your kindness and generous help! :-)

**Comment by amukherjee28** [comment]
That's great. :-)

Also let me know you mac OS version and python version so that I can keep a note of the issue you faced initially.

Thanks.

**Comment by alanzyt311** [comment]
Sure. 

- Mac Version: MAC OS X 10.15.2
- Python Version: 3.8

**Comment by alanzyt311** [comment]
SSL connection also works for my Windows. I'll close this issue. Thx again.
