### ISSUE TITLE
Symbol not found: _SQLAllocHandle when using ibm_db

### ISSUE THREAD

**Issue by alanzyt311** [ibmdb/python-ibmdb#645]
I am using ibm_db to connect Db2 on Cloud, and then I got the following error msg:

`Traceback (most recent call last):
  File "ibm_db2.py", line 13, in <module>
    import ibm_db`
`ImportError: dlopen(/Users/ltz/software/forge3/envs/pyflask38/lib/python3.8/site-packages/ibm_db.cpython-38-darwin.so, 2): Symbol not found: _SQLAllocHandle
  Referenced from: /Users/ltz/software/forge3/envs/pyflask38/lib/python3.8/site-packages/ibm_db.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/ltz/software/forge3/envs/pyflask38/lib/python3.8/site-packages/ibm_db.cpython-38-darwin.so`

What should I do to handle this issue? I cannot find the exact same situation on the Internet. Any help will be appreciated!

**Comment by amukherjee28** [comment]
can you explain your application code a bit, like which statement is causing this issue.

Can you put an example of your code.

**Comment by alanzyt311** [comment]
Sry about that. I forgot to put the code. Please refer to the following:

`app = Flask(__name__)`

`app.config['SQLALCHEMY_DATABASE_URI'] = 'db2+ibm_db://{}:{}@{}:{}/{}?SECURITY=SSL'.format(config.DB2['USER'],config.DB2['PASSWD'],config.DB2['HOST'],config.DB2['PORT'], config.DB2['DB'])`

`SQLAlchemy().init_app(app)`

I guess it was `SQLAlchemy().init_app(app)` that cause this error because it is used to connect DB.

**Comment by amukherjee28** [comment]
Hi,

Sorry for the delayed response.
In case you are still facing this issue can you get me a few more details regarding on what you have trying to do here.

I understand that you are using a flask app to connect to db2 database. Can you provide a bit more details on the environment.As par my knowledge you are using MAC OS with python 3.8

Can you also brief on the sqlalchemy version along with ibm_db version and in case you are using ibm_db_sa can you also mention that version as well.

Also by any chance can you check if the same application is working in windows.

Thanks

**Comment by amukherjee28** [comment]
Could you please provide an update on this case.

Thanks

**Comment by alanzyt311** [comment]
Hi @amukherjee28, sry for the late update. Actually, it turns out to work well later after creating a new Conda environment and re-install ibm_db package. 

So I may close this issue. Thx for your help!
