### ISSUE TITLE
Getting a typeerror during the installation by conda.

### ISSUE THREAD

**Issue by woebsz** [ibmdb/python-ibmdb#651]
TypeError('not all arguments converted during string formatting')

**Comment by amukherjee28** [comment]
Hi,

Can you provide a bit more details on the issue.

1. What kind of platform are you running the conda install.
2. Version of the conda and python used.
3. Complete error seen during the installation.

Thanks.

**Comment by amukherjee28** [comment]
Is there any update on this issue. Do you still have to issue or you were able to move forward with the issue.
In case the issue persists please let me know the details above.
