### ISSUE TITLE
ibm_db_dbi  object has no .execute() attribute

### ISSUE THREAD

**Issue by GeneGeneGitHub** [ibmdb/python-ibmdb#652]
import ibm_db_dbi
connectstring = 'DATABASE=xxx;HOSTNAME=localhost;PORT=50000;PROTOCOL=TCPIP;UID=xxx;PWD=xxx;'
conn = ibm_db_dbi.connect(connectstring,'','')
curr  = conn.cursor
cSQL = "SELECT * FROM TEST"
curr.execute(cSQL)
rows = curr.fetchall()
print(len(rows))

Connection is made but the curr.execute() statement throws the error:

AttributeError: 'function' object has no attribute 'execute’

Any ideas?  I’m running python 3.8.2, and installed the ibm_db package via 'pip install **ibm_db'**

**Comment by imavo** [comment]
Try this:

```
import ibm_db
import ibm_db_dbi
connectstring = 'DATABASE=xxx;HOSTNAME=localhost;PORT=50000;PROTOCOL=TCPIP;UID=xxx;PWD=xxx;'

db_conn = ibm_db.connect(connectstring,"","")

curr = ibm_db_dbi.Connection(db_conn).cursor()

cSQL = "SELECT * FROM TEST"
curr.execute(cSQL)
rows = curr.fetchall()
print(len(rows))
```

**Comment by GeneGeneGitHub** [comment]
Thanks.

I must've done it right, using cursor(), 500x in the past. Bleary-eyed from staring at code too long I guess.

**Comment by amukherjee28** [comment]
This issue was resolved hence closing the case,
