### ISSUE TITLE
pip install ibm_db with error in ibm_db setup command: use_2to3 is invalid.

### ISSUE THREAD

**Issue by focabr** [ibmdb/python-ibmdb#655]
Python 3.9.6
ibm_db 3.0.4
pip 21.2.4
setuptools 58.0.4

Problem from pip install ibm_db.

**Workaround:** setuptools==56.0.0

ERROR:
<pre>
    Running setup.py install for ibm-db: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-td7jf43y/ibm-db_5610859d2bb34e94b09cb4533e3868a3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-td7jf43y/ibm-db_5610859d2bb34e94b09cb4533e3868a3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cn2swwqk/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/ibm-db
         cwd: /tmp/pip-install-td7jf43y/ibm-db_5610859d2bb34e94b09cb4533e3868a3/
    Complete output (5 lines):
    Detected 64-bit Python
    /tmp/pip-install-td7jf43y/ibm-db_5610859d2bb34e94b09cb4533e3868a3/setup.py:304: UserWarning: Detected usage of IBM Data Server Driver package. Ensure you have downloaded 64-bit package of IBM_Data_Server_Driver and retry the ibm_db module install
    
      warnings.warn(notifyString)
    error in ibm_db setup command: use_2to3 is invalid.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-td7jf43y/ibm-db_5610859d2bb34e94b09cb4533e3868a3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-td7jf43y/ibm-db_5610859d2bb34e94b09cb4533e3868a3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cn2swwqk/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/ibm-db Check the logs for full command output.
</pre>

**Comment by focabr** [comment]
It looks like setuptools>=58 breaks support for use_2to3:

https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0

**Comment by jaraco** [comment]
Confirming that the merged change addressed the issue:

```
$ pip-run 'git+https://github.com/ibmdb/python-ibmdb#subdirectory=IBM_DB/ibm_db'
Collecting git+https://github.com/ibmdb/python-ibmdb#subdirectory=IBM_DB/ibm_db
  Cloning https://github.com/ibmdb/python-ibmdb to /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-82lusgpm
  Running command git clone -q https://github.com/ibmdb/python-ibmdb /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-82lusgpm
  Resolved https://github.com/ibmdb/python-ibmdb to commit 9b39a7548bb073c10441e675cd47be1df8940650
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: ibm-db
  Building wheel for ibm-db (PEP 517) ... done
  Created wheel for ibm-db: filename=ibm_db-3.0.4-cp310-cp310-macosx_10_15_universal2.whl size=32499059 sha256=5c4e5284f8bea4956c0e07cacbefd02574f9c243cf2466d58c76ef331ce159a2
  Stored in directory: /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-ephem-wheel-cache-yo4dgcoy/wheels/e3/7b/37/3f0a39623d4a4e5c1f362ec574665d3c139bfa489f30b52027
Successfully built ibm-db
Installing collected packages: ibm-db
Successfully installed ibm-db-3.0.4
Python 3.10.0rc1 (v3.10.0rc1:cc115e5bf6, Aug  2 2021, 17:54:14) [Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D
```

All that's needed is to cut a new release with the workaround.

**Comment by jaraco** [comment]
@amukherjee28 In the PR, you reported that you're still encountering the issue. I should note that the fix will only work for pip installs. Anyone using `setup.py install` or `easy_install` (both deprecated) will need to manually downgrade Setuptools.
