### ISSUE TITLE
I'm having an install issue with ibm_db - keep getting Error msg

### ISSUE THREAD

**Issue by JPow** [ibmdb/python-ibmdb#658]
Trying to install any ibm-db I get the same error message.
I've tried pip install ibm-db
pip install ibm_db
!pip install ibm_db_sa 

This is the error msg:

Building wheels for collected packages: ibm-db
  Building wheel for ibm-db (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Applications/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/km/x_cb0wn5249ddhfzzt066kg40000gn/T/pip-install-l57r2ypj/ibm-db_9dc78b18aac84ab3845432f0ece70ae1/setup.py'"'"'; __file__='"'"'/private/var/folders/km/x_cb0wn5249ddhfzzt066kg40000gn/T/pip-install-l57r2ypj/ibm-db_9dc78b18aac84ab3845432f0ece70ae1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/km/x_cb0wn5249ddhfzzt066kg40000gn/T/pip-wheel-j_co3son
       cwd: /private/var/folders/km/x_cb0wn5249ddhfzzt066kg40000gn/T/pip-install-l57r2ypj/ibm-db_9dc78b18aac84ab3845432f0ece70ae1/

**Comment by amukherjee28** [comment]
@JPow 

From the error message it looks like you are trying installation on MAC OS. Could you provide a few more details.

1. python version use. Are you using python from anaconda distribution?
2. Is this the complete error log. If not can you provide the complete error log seen during installation.
3. Do you have sufficient permission on the folders where the installation occurs?
4. version of pip (pip --version)

**Comment by JPow** [comment]
@amukherjee28 
1. Anaconda confirmed with Python 3. Also tried conda install with same result.  
2. That was just a snippet - Entire log is now attached
3. This is all locally hosted on my Mac - is there a security setting i should change?
4.  21.0.1  (i took this from !pip list) 
[error log ibm_db_sa.txt](https://github.com/ibmdb/python-ibmdb/files/7217886/error.log.ibm_db_sa.txt)

**Comment by amukherjee28** [comment]
Hi @JPow 

For installing IBM_DB on mac we require C compiler gcc to compile the code and then install the dependency.

From the error log I see the following

```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

Looks like some dependency is failing while compilation.

I looked up on the internet and have the following link
https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa

Can you try the resolution provided in the above link and try the installation once more.

**Comment by JPow** [comment]
@amukherjee28 that worked! Thank you for the guidance. I needed to install xcode via Terminal. Then the ibm_db api can subsequently be successfully installed on Mac OS.  Thanks so much!  I had actually searched and posted on slackoverflow but was unsuccessful.

xcode-select --install
