### ISSUE TITLE
Dependency issue with ibm-db-django=1.5.0.0 and Django 3.2.7

### ISSUE THREAD

**Issue by juliushacker** [ibmdb/python-ibmdb#659]
Hello everyone,

Today I’ve tried to upgrade our existing Django 3.1 / ibm-db-django 1.4.0.0 installation to the newest Releases – Django 3.2.7 and ibm-db-django 1.5.0.0
As my installation resides behind a proxy, I’m downloading the wheels / sources from pypi.org and installing it via “pip install .\ibm_db_django-1.5.0.0.tar.gz .\Django-3.2.7-py3-none-any.whl"

This gives me the following error message:

ERROR: Cannot install django 3.2.7 (from C:\XXXXXXXXX\Django-3.2.7-py3-none-any.whl) and ibm-db-django==1.5.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested django 3.2.7 (from C:\XXXXXXXXX\Django-3.2.7-py3-none-any.whl)
    ibm-db-django 1.5.0.0 depends on django==3.2

The  python environment is an actual Python 3.9.7 on Windows.

Is there a specific reason for ibm-db-django depending on exactly Django 3.2 and not including Django bugfix releases?
As the Django release process ( https://docs.djangoproject.com/en/3.2/internals/release-process/ ) says that the bugfix releases are 100% compatible I would have excepted a dependency like django>=3.2.0, <3.3.0

Regards
Julius

**Comment by praveen-db2** [comment]
Hi Julius,

ibm-db-django 1.5.0.0 support upto django 3.2 version.
anything above that is not yet supported. 
I see you are trying Django 3.2.7

Thanks
Praveen

**Comment by juliushacker** [comment]
Hi Praveen,

Thanks for your information on that issue!

Just to clarify my point a little bit:
3.2.7 is a patch release. The Django docs define a patch release as being 100% backward compatible to previous patch releases. Consequently, 3.2.7 is compatible to 3.2.
As a consequence I strongly suspect that ibm-db-django also works with 3.2.7 and following patch releases.

Regards
Julius

**Comment by praveen-db2** [comment]
Hi Julius,

Yes ibm-db-django should work with 3.2.7, but in setup file we didnt specify to work above django 3.2. Looks liek its blocking installation above Django 3.2.

For time being you can download ibm_db_django thru github and install the same by modifying setup file.
We are also planning to release next support in year end. 

We will check if we can release intermediate version in between with fix in setup file or we include in major version.

Thanks
Praveen

**Comment by praveen-db2** [comment]
Hi Julius, 

This is been addressed in ibm-db-django 1.5.1.0

Refer commit: https://github.com/ibmdb/python-ibmdb-django/commit/f379aff2fa378b1c14f579ed9d80994a119ef954#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7

Thanks
Praveen
