### ISSUE TITLE
ibm_db 3.1.0 fails to pip install with python 3.8.10 linux

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb#672]
my environment:

ubuntu 20.04.2 x64
python version 3.8.10
pip version 21.2.4
setuptools version 58.2.0

After creating the venv, and activiating the venv, and ensuring its pip version is latest, I run this command:

pip install ibm_db

This fails with:

    ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/tmpquqn65ej/output.json'

The full text:

(venv1)$ pip install ibm_db
Collecting ibm_db
  Using cached ibm_db-3.1.0.tar.gz (797 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/tmpr7np75f9/output.json'

Note that it makes no difference to the symptom whether IBM_DB_HOME variable is exported first or not.
Also , it makes no difference if the pip version is older at 20.0.2.

Details below:

```
user3@myhostname:~$ python -m venv /home/user3/venv2


user3@myhostname:~$ source venv2/bin/activate
(venv2) user3@myhostname:~$ python -V
Python 3.8.10


(venv2) user3@myhostname:~$ python -m pip install --upgrade pip 
Collecting pip 
  Using cached pip-21.2.4-py3-none-any.whl (1.6 MB) 
Installing collected packages: pip 
  Attempting uninstall: pip 
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-21.2.4



(venv2) user3@myhostname:~$ python -m pip install --upgrade setuptools
Requirement already satisfied: setuptools in ./venv2/lib/python3.8/site-packages (44.0.0)
Collecting setuptools
  Using cached setuptools-58.2.0-py3-none-any.whl (946 kB) 
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 44.0.0
    Uninstalling setuptools-44.0.0:
      Successfully uninstalled setuptools-44.0.0
Successfully installed setuptools-58.2.0



(venv2) user3@myhostname:~$ pip install ibm_db
Collecting ibm_db
  Using cached ibm_db-3.1.0.tar.gz (797 kB) 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/tmp3a0pt79x/output.json'
```

**Comment by amukherjee28** [comment]
@imavo 

After upgrading the setuptools pip install worked fine for me.
I did not use venv though.

Can you try the normal installation and check once without the virtual environment, meanwhile I will check with the venv command.

Thanks

**Comment by imavo** [comment]
Accidental close, reopened .  See previous update.

**Comment by amukherjee28** [comment]
So this means this has nothing to do with the 3.1.0 version. Its even coming for the old version as well.

You are trying this in linux machine right.

**Comment by amukherjee28** [comment]
I tried in exact similar setup

python : 3.8.2
Linux RHEL8.0 machine

I have no issues installing

```
amukherjee@waldevdbcttst02:/work/amukherjee/PYTHON_IBM_DB> pip3 install --upgrade setuptools
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/41/f4/a7ca4859317232b1efb64a826b8d2d7299bb77fb60bdb08e2bd1d61cf80d/setuptools-58.2.0-py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 41.2.0
    Uninstalling setuptools-41.2.0:
      Successfully uninstalled setuptools-41.2.0
Successfully installed setuptools-58.2.0
WARNING: You are using pip version 19.2.3, however version 21.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
amukherjee@waldevdbcttst02:/work/amukherjee/PYTHON_IBM_DB> pip3 install ibm_db
Collecting ibm_db
  Using cached https://files.pythonhosted.org/packages/d0/b7/4b133397dbaa5f7046f95b59a784d8030f43a1228aee371affeb4f4b6a6c/ibm_db-3.1.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: ibm-db
  Building wheel for ibm-db (PEP 517) ... done
  Created wheel for ibm-db: filename=ibm_db-3.1.0-cp38-cp38-linux_x86_64.whl size=41036398 sha256=28ed6b7b399f970eca1da372d2364300a011006323c10e36ad2d6c8fdb676161
  Stored in directory: /home/amukherjee/.cache/pip/wheels/d9/fa/4d/7db40a5016d103abc6094c26d20257a336f1c15f11ed89d803
Successfully built ibm-db
Installing collected packages: ibm-db
Successfully installed ibm-db-3.1.0
WARNING: You are using pip version 19.2.3, however version 21.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
amukherjee@waldevdbcttst02:/work/amukherjee/PYTHON_IBM_DB> python3
Python 3.8.2 (default, May 12 2020, 04:45:08)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> print(ibm_db.__version__)
3.1.0
>>>
```

**Comment by imavo** [comment]
It is a physical box (ubuntu 20.04) not a VM , but I will check. However, as I noted, other packages install OK with pip, it's just ibm_db that gives trouble. Give me some time to check , and to check on RHEL8.

**Comment by lampwins** [comment]
@imavo did you find anything else out? Facing this with 3.8 on rhel.

**Comment by rmonicovia** [comment]
+1, still having problem on Windows (10), pip 22.0.4 and python 3.9.10

**Comment by cadentb** [comment]
I have this problem with apache airflow via a docker container. Airflow uses debian10 and python 3.7 I think. I've tried upgrading pip and still no dice

**Comment by lke27** [comment]
I faced this issue yesterday, it is because the download link is dead as mentioned here [https://github.com/ibmdb/python-ibmdb/issues/758](url) once it's fixed the error is gone.

**Comment by qa-aleksejs-fomins** [comment]
@Ike27 The link you have provided does not point to anything :(

**Comment by lke27** [comment]
@qa-aleksejs-fomins The issue is #758

**Comment by bimalkjha** [comment]
@qa-aleksejs-fomins The link is down again. Working with IBM to make it up. It should be up in couple of hours. Thanks.
