### ISSUE TITLE
Unable to Connect - Extra Spaces after the Database Name

### ISSUE THREAD

**Issue by prevailings** [ibmdb/python-ibmdb#673]
**Environment:**
Windows 10 1909
Python: 3.8.10
ibm_db.__version__: 3.1.0
clidriver: ntx64_odbc_cli
(https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip)

**Code**
```
# Private information has been replaced with ***, which is actually correct
conn_str = 'hostname=***;port=***;database=D;uid=***;pwd=***'
try:
    ibm_db_conn = ibm_db.connect(conn_str, '', '')
    conn = ibm_db_dbi.Connection(ibm_db_conn)
except Exception as e:
    print(e)
```

**Discription**
I tried to use python connect to the DB2 database on remote server(sys: IBM AIX 7).
Error "SQLCODE=-30081" was reported. 

When I debug the code, info as below:
```
[IBM][CLI Driver] SQL30061N  The database alias or database name "D                 " was not found at the remote node.  SQLSTATE=08004
SQLCODE=-30061
```
I am wondering where the spaces after the name of database(name is D) comes from? How to solve the problem?

**Comment by bimalkjha** [comment]
@prevailings The space is the error message for database is normal as space padding is done by the driver, but it does not mean the database name with space is used for connection. The main issue is, ibm_db is unable to find the database 'D' on the remote server. Run `db2 get db directory` on remote server and verify the database name. We can see, you are using `database=D;` in connection string, but error say, database 'D' does not exist on remote host and port combination. Thanks.

**Comment by prevailings** [comment]
@bimalkjha I solved this problem by changing a PC which support the CharSet.
I checked the CharSet in CMD by the command "chcp", and found the previous PC do not surpport the remote database.
Thanks.
