### ISSUE TITLE
SQL Persist command is giving an Error in IBM Watson studio Jupyter Notebook

### ISSUE THREAD

**Issue by ehab-wahhab** [ibmdb/python-ibmdb#674]
##When I run below commands on Jupyter Notebook on IBM Watson Studio I get an error. I'm unable to continue my Lab on edx.

import pandas
chicago_socioeconomic_data = pandas.read_csv('https://data.cityofchicago.org/resource/jcxq-k9xf.csv')
%sql PERSIST chicago_socioeconomic_data

 * ibm_db_sa://gkj44478:***@0c77d6f2-5da9-48a9-81f8-86b520b87518.bs2io90l08kqb1od8lcg.databases.appdomain.cloud:31198/bludb
(ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: Statement Execute Failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected token "END-OF-STATEMENT" was found following "o_socioeconomic_data".  Expected tokens may include:  "JOIN <joined_table>".  SQLSTATE=42601 SQLCODE=-104
[SQL: PERSIST chicago_socioeconomic_data]
(Background on this error at: http://sqlalche.me/e/f405)

**Comment by bimalkjha** [comment]
Closing the issue as error seems due to use of invalid SQL and there is no issue with ibm_db driver. There is no response from user since 25days, so closing it. Let us if issue still exist. Thanks.
