### ISSUE TITLE
IBM_DB issue when docker build is installing package.

### ISSUE THREAD

**Issue by jsalcedoa** [ibmdb/python-ibmdb#676]
Hi,

I'm having issues deploying some critical fixes to production environment because I'm getting an error while docker build command is running and installing ibm_db package. I'm not sure what happened because the deployment script that I'm using has been working for over a year.

I'm not very knowledgeable in dev ops but there is no body in my team or project who can help me.

This is the screenshot of my console before the error occurs:

<img width="1310" alt="Screen Shot 2021-10-12 at 12 58 08 PM" src="https://user-images.githubusercontent.com/29698309/137133058-bf7d9d18-f8d4-4b32-b652-fbf4091f9f1c.png">

This is the screenshot of my console after the error occurs:

![image (1)](https://user-images.githubusercontent.com/29698309/137133199-1468df3c-c9d7-42f5-b03f-e474fafcbdc9.png)

I believe this is the docker configuration file that is getting executed:

<img width="696" alt="Screen Shot 2021-10-12 at 1 01 15 PM" src="https://user-images.githubusercontent.com/29698309/137133295-428481b4-4f08-4352-9d96-f3fbfb24fcfa.png">

And this is the package.json file from my back end which contains the ibm_db dependency:

<img width="1398" alt="Screen Shot 2021-10-12 at 1 03 52 PM" src="https://user-images.githubusercontent.com/29698309/137133426-5ab1c645-795a-4472-9b51-e9fd8d4383a8.png">

<img width="1403" alt="Screen Shot 2021-10-12 at 1 04 04 PM" src="https://user-images.githubusercontent.com/29698309/137133454-4762f671-8de8-4409-bcf0-bc781ff04d11.png">

Note: I had installed ibm_db version 2.7 when the error happened so I updated the version to 2.8 to see if this would fix the error but it didn't.

**Comment by amukherjee28** [comment]
Looks to me this is with respect to installation of node ibm_db rather than python ibm_db.
Could you please confirm once.
