### ISSUE TITLE
Getting error "SQLCODE=-1042ect: [IBM][CLI Driver] SQL1042C An unexpected system error occurred. SQLSTATE=58004"

### ISSUE THREAD

**Issue by Prateekibm** [ibmdb/python-ibmdb#680]
Hello,

I am trying to connect to database="BLUDB",host name="85dbf01d-0df0-49e3-a51a-31d46b9ff6bb.bpe60pbd01oinge4psd0.databases.appdomain.cloud" using Python.
I am facing an error "SQLCODE=-1042on: [IBM][CLI Driver] SQL1042C An unexpected system error occurred. SQLSTATE=58004", while connecting to above host. However my colleague is able to successfully connect from her machine by running same code. Could you provide help on the error?

**Comment by amukherjee28** [comment]
Please check #599 

Similar issue was reported before. We had this issue with few distribution of windows.

**Comment by Prateekibm** [comment]
After appending clidriver to path variable,I am getting error "Failed to load dll".I have followed the steps to append exact bin path as mentioned in the #599 case.

**Comment by imavo** [comment]
@Prateekibm - please supply the requested trace files per the above instructions by  @amukherjee28

**Comment by amukherjee28** [comment]
For the failed to load DLL error please check the documentation once as well.
https://github.com/ibmdb/python-ibmdb/blob/master/README.md#inst

You might have to add the following
```
import os
os.add_dll_directory('path to clidriver installation until bin')

e.g:
os.add_dll_directory('C:\Program Files\IBM\CLIDRIVER\\bin')
```
