### ISSUE TITLE
ERROR: Could not build wheels for ibm-db, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by wbgibby** [ibmdb/python-ibmdb#682]
Trying to install ibm_db model in a red-hat linux image 
FROM registry.access.redhat.com/ubi8/ubi-init:latest

I get 

  ERROR: Failed building wheel for ibm-db
Failed to build ibm-db
ERROR: Could not build wheels for ibm-db, which is required to install pyproject.toml-based projects

I ran the steps from https://github.com/ibmdb/python-ibmdb/issues/627
pip install --upgrade pip  
sudo dnf install python3-devel 
pip install ibm_db

and I get
[root@5d6f4f59e988 scripts]# pip install ibm_db
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal'

steps to recreate
Run this docker file
[Dockerfile.txt](https://github.com/ibmdb/python-ibmdb/files/7383162/Dockerfile.txt)

I get this error message

[error.txt](https://github.com/ibmdb/python-ibmdb/files/7383177/error.txt)

**Comment by wbgibby** [comment]
You can close this Apparently I needed to add 
RUN dnf install -y gcc to the docker file.
And that worked.

**Comment by amukherjee28** [comment]
Hi Went through the dockerfile and error file attached.

Not sure why pip install is failing to build the ibm_db.
Can you please check if gcc is installed in the docker image?

**Comment by amukherjee28** [comment]
So gcc was indeed missing in the docker image.
Corrected docker file.
[Dockerfile.txt](https://github.com/ibmdb/python-ibmdb/files/7383220/Dockerfile.txt)

Closing the issue.
Thanks for the update.
