### ISSUE TITLE
installing ibm_db on windows

### ISSUE THREAD

**Issue by ds-sabmlt** [ibmdb/python-ibmdb#685]

**Comment by ds-sabmlt** [comment]
hi 
Im try to offline install ibm_db on windows 10.
python3.9.7
i have below error in import ibm_db:
ImportError: DLL load failed while importing ibm_db: The specified module could not be found.

**Comment by imavo** [comment]
What command(s) , did you use to install the ibm_db module, show the exact command-line and the output.
It is unclear what you mean "in offline way".
Which version of the ibm_db module did you install?

**Comment by bimalkjha** [comment]
@ds-sabmlt I think offline way means installing db2 client in your system and you are installing ibm_db after setting IBM_DB_HOME? If yes, then you need to add full path of clidriver/bin & clidriver/lib directory in PATH and LIB system environment variables. If you are still facing issue, please let us know. Thanks.
