### ISSUE TITLE
ImportError: CEE3512S An HFS load of module /mypath/python/lib/python3.9/site-packages/ibm_db.so failed. The system return code was 0000000111; the reason code was 00000004. 

### ISSUE THREAD

**Issue by MRabast** [ibmdb/python-ibmdb#686]
Hi,
How can I solve this ? What have I done wrong ?

(python) MYUSERID@ZOSHOST:/home/myUserid ==> pip3 install ibm-db -v

Using pip 21.3.1 from /WWW/opera/python/lib/python3.9/site-packages/pip (python 3.9)
Looking in indexes: https://mycache/repository/public-lib-python-pypi/simple
Collecting ibm-db
  Using cached ibm_db-3.1.0-cp39-cp39-os390_27_00_8561.whl
Installing collected packages: ibm-db
Successfully installed ibm-db-3.1.0
 

(python) MYUSERID@ZOSHOST:/home/myUserid ==> pip3 list -v
Package            Version   Location                                      Installer
------------------ --------- --------------------------------------------- ---------
ibm-db             3.1.0     /WWW/opera/python/lib/python3.9/site-packages pip
pip                21.3.1    /WWW/opera/python/lib/python3.9/site-packages pip
setuptools         58.3.0    /WWW/opera/python/lib/python3.9/site-packages pip
zoautil-py         1.1.1     /WWW/opera/python/lib/python3.9/site-packages

(python) MYUSERID@ZOSHOST:/home/myUserid ==>
(python) MYUSERID@ZOSHOST:/home/myUserid ==> python
Python 3.9.0 (heads/pyz_dev-3.9:49e97075d0, Nov 25 2020, 15:20:41) on zos
Type "help", "copyright", "credits" or "license" for more information.
 
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  
ImportError: CEE3512S An HFS load of module /mypath/python/lib/python3.9/site-packages/ibm_db.so failed. The system return code was 0000000111; the reason code was 00000004.    

Thanks for help.

**Comment by amukherjee28** [comment]
Hi @MRabast 

From the logs it looks like you are trying to install ibm_db driver in a ZOS machine,

The error in question depends on how the ZOS machine setup was done in order to run python applications.

First off all let me ask you if you have configured all of the pre-requisites as mentioned in the documentation
https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/NOTES.md

Also what are the parameters set in your odbc.ini file.

**Comment by MRabast** [comment]
found that in the Docu: remove the tag

MyUserId@host ==> ls -alT /mypath/python/lib/python3.9/site-packages/ibm_db.so
t ISO8859-1   T=on  -rwxr-xr-x+  1 user group     417792 Nov  2 12:37 /mypath/python/lib/python3.9/site-packages/ibm_db.so
MyUserId@host ==> chtag -r /mypath/python/lib/python3.9/site-packages/ibm_db.so

**Comment by amukherjee28** [comment]
I guess doing the above did not resolve the issue.
In this regard we will require a few more information from you.

Could you provide the details all the PATH variable that was set in order use the Z/ODBC driver to work with the ibm_db.

Also have a look into this link
https://www.ibm.com/docs/en/python-zos/3.9?topic=troubleshooting

Move to the section ```Issues building and installing PyPI packages```. Just check if your chtag was done properly.

**Comment by bimalkjha** [comment]
@MRabast Are you still facing this issue after following the documentation link shared above? Thanks.
