### ISSUE TITLE
 SQL1042C  An unexpected system error occurred.  SQLSTATE=58004

### ISSUE THREAD

**Issue by EemeIi** [ibmdb/python-ibmdb#687]
I'm unable to get ibm-db working on my Windows 10 machine. As a minimal example, if I run the following:
```
import ibm_db

if __name__ == "__main__":
    dsn = 'database=pydev;hostname=host.test.com;port=portno;protocol=tcpip;uid=db2inst1;pwd=secret'
    ibm_db_conn = ibm_db.connect(dsn, "", "")
```

I get the following error:  `SQL1042C  An unexpected system error occurred.  SQLSTATE=58004`, while the expected response would be `SQLCODE=-1337on: [IBM][CLI Driver] SQL1337N  The service "portno" was not found.` as the connection string is nonsense. I get the same error with any proper connection string I have tested as well. I am using the following conda environment:
```
name: db_test
channels:
  - defaults
dependencies:
  - python=3.6.9
  - pip==19.3.1
  - pip:
    - ibm-db==3.1.0
```

I am suspecting some kind of issue with my ODBC driver, but resintalling ibm-db has not been helpful. As a curiosity, the package works fine on my WSL (Windows subsystem for Linux).

Any suggestions on what I should try?

**Comment by imavo** [comment]
please check if the suggestion in this link helps, take great care that you understand the details and get the paths correct  https://github.com/ibmdb/python-ibmdb/issues/599

**Comment by EemeIi** [comment]
That works, thanks a lot! Not sure how I managed to miss that thread.

**Comment by Vishnu-Suriyan** [comment]
HI sir, I am also facing issue. I even tried the adding PATH variable. But Its not working. Pls tell me way a to send the following files 

trc.flw
trc.fmt
trc.fmtc
trc.cli
