### ISSUE TITLE
ibm_db python symbol not found error after Monterey

### ISSUE THREAD

**Issue by TomBigelow1986** [ibmdb/python-ibmdb#691]
I am getting the following error in my conda environment

import ibm_db
E   ImportError: dlopen(/opt/miniconda3/envs/graphtest/lib/python3.9/site-packages/ibm_db.cpython-39-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
E     Referenced from: /opt/miniconda3/envs/graphtest/lib/python3.9/site-packages/clidriver/lib/libdb2.dylib
E     Expected in: /usr/lib/libstdc++.6.dylib

I was not having issues even after upgrading to Monterey until after I rebuilt my conda environment.

I am following the issue related to ibm_db & python & monterey:
https://github.com/ibmdb/python-ibmdb/issues/648

Things I have tried:
1) install the latest XCODE to get g++ and gcc in order to get a new version of “libstdc++.6.dylib” as mentioned in the last thread by @bimalkjha . It is still referencing the same /usr/lib/libstdc++.6.dylib (created/modified a month ago) from before installing XCODE. The /usr/lib/libstdc++.6.dylib apparently goes no where as when I execute the shortcut from /usr/lib/libstdc++.6.dylib, it says:
"The operation can’t be completed because the original item for “libstdc++.6.dylib” can’t be found"

I currently have a conda environment variable setup; DYLD_LIBRARY_PATH=/opt/miniconda3/envs/graphtest/lib/python3.9/site-packages/clidriver/lib

**Comment by bimalkjha** [comment]
@TomBigelow1986 [This page](https://stackoverflow.com/questions/50694822/xcode-10-ios-12-does-not-contain-libstdc6-0-9) has documented the root cause of the issue with solution.
If you run `ls -l /usr/lib/libstdc++*`, you can see libstdc++.6.dylib is soft link of libstdc++.6.0.9.dylib but this library does not exist.
Root cause is, XCode 10 has removed it. So, either install older version of xcode or copy libstdc++.6.0.9.dylib under /usr/lib. Thanks.

**Comment by TomBigelow1986** [comment]
Thanks for the reply @bimalkjha 

Yes I see now that libstdc++.6.dylib is linking to a file that does not exist. The solution you linked said to copy that library over into xcode's usr/lib which I did, but im not sure what XCode has to do with that broken link in the OS's usr/lib. I only installed xcode to get the latest gcc and g++ which I was hoping (somehow) would provide a new version of that library. If I put put the library into the usr/lib of XCode, is there another step required to make it look there instead because based on that stack trace, clidriver/lib/libdb2.dylib is driving the: "Expected in: /usr/lib/libstdc++.6.dylib"

Do I have to instead copy that file into the protected OS directory usr/lib since that is where the error message says its expecting to find it? If so, I have to disable a bunch of security apparently.

**Comment by bimalkjha** [comment]
@TomBigelow1986 The latest xcode has removed /usr/lib/libstdc++.6.0.9.dylib, so you just need to copy `libstdc++.6.0.9.dylib` under `/usr/lib` directory and your application should work fine,. Nothing else. Thanks.

**Comment by danws2020** [comment]
What is the plan to address this? libstdc++ was deprecated in Xcode 8... removed in Xcode 10... and the current version is 13.1. We can't tell customers they have to some file into a protected folder.

**Comment by TomBigelow1986** [comment]
To expand on what @danws2020 is saying:

The solution you suggest is to put that missing library into usr/lib; however, it is a protected OS folder and would require us to boot into recovery mode, turn off system integrity protection, put the file in, put SIP back on, and boot back into normal mode. It would probably work, but there has to be a better solution that doesn't require users to find this thread, obtain a copy of that library, and then follow those instructions and compromise security to get it into that folder. It will likely also get clobbered in the next OS update.

Also, we are not creating applications within XCode which require that library, which I believe is what the original SO solution you linked is addressing. @bimalkjha Can you suggest a better way forward? Can the driver be updated with a fix? We now have other team members experiencing the same problem.

**Comment by tn-m** [comment]
I'm facing on the same with the **MacOS Big Sur**.
It seems like Apple prohibited to write on system volume, and I cannot copy the `libstdc++.6.dylib` to `/usr/lib`.
Any workarounds?

**Comment by amukherjee28** [comment]
@tn-m Could you try using sudo as MacOS does not allow operations into the /usr directory without root privilege.
Use sudo before the copy command and when prompted from password provide your password.

This should work when copying the library into /usr/lib directory.

**Comment by tn-m** [comment]
@amukherjee28 Thank you for the reply.
I tried with `sudo` but still getting an error.

```
sudo cp /usr/local/Cellar/gcc/11.2.0_2/lib/gcc/11/libstdc++.6.dylib /usr/lib/
Password:
cp: /usr/lib/libstdc++.6.dylib: Read-only file system
```

**Comment by amukherjee28** [comment]
@tn-m looks like this is more than just permission issue.

I did find a work around in the internet. If you could give it a try and check.
https://www.dev2qa.com/how-to-fix-read-only-file-system-error-when-run-mkdir-command-on-macos/

You might give a try for the solution 1 in the above link.

Meanwhile we will also investigate a bit more on this based on the previous comments in the issue.

**Comment by marcosbrazz** [comment]
While there is no definitive solution, I tried the following workaround and it worked:

1. Copy the file libstdc++.6.dylib from site-packages/clidriver/lib from a virtual env created before the Monterey upgrade to site-packages/clidriver/lib of a new virtual env.
2. Export the variable DYLD_LIBRARY_PATH=/path/to/clidriver/lib

**Comment by arlon-nlo** [comment]
I have the same issue since i've updated to OSX Monterey. I'm unable to fix this with the workarounds suggested above:
- Installing an older version of Xcode (< 10) is not possible on a Monterey
- Installing gcc via Homebrew did not work 
- Setting the environment variables DYLD_LIBRARY_PATH or LD_LIBRARY_PATH is not working. I can set them, but during runtime the dlopen module keeps expecting the .dylib file in in /usr/lib. This also doen't work when I set these variables in a Python script or when I'm adding them to the .bashrc file.
- Copying files to the root disk (/usr/lib) has been made virtually impossible since Big Sur and certainly not recommended. 

@TomBigelow1986 did you find a working solution yet?

**Comment by amukherjee28** [comment]
We have updated the fixed clidriver with proper linking of the library.
Please clean up the previous installation and install again.

This should resolve the issue.

Also with this fix there is no additional requirement for setting the DYLD_LIBRARY_PATH as well

**Comment by daniloas80** [comment]
I had the same issue and in my case, I solved it out exporting the lib using these two lines below in my terminal:

export IBM_DB_HOME=/usr/local/lib/python3.10/site-packages/clidriver _<here is my path, you should use yours>_
export DYLD_LIBRARY_PATH=$IBM_DB_HOME/lib:$DYLD_LIBRARY_PATH

I'm using MacOS. It may working in Linux and might have similar solution for Windows users as well.
