### ISSUE TITLE
SystemError: <built-in function connect> returned NULL without setting an error

### ISSUE THREAD

**Issue by Gabikakenobi** [ibmdb/python-ibmdb#692]
Dear ibm_db project team!

I had a perfectly working setup with ibm_db using jupyter lab in anaconda environment querying a DB2 Z/Os database on a daily basis.
A few days ago I started getting this error without updating or changing any settings/versions on any tools used (only Windows was updated on a regular basis ). Code used to connect is also unchanged:

Connection failed. Check VPN and credentials.
Traceback (most recent call last):
  File "<ipython-input-1-ed367e0199c2>", line 17, in <module>
    con_db2 = db.connect("DATABASE=dbname;HOSTNAME=address;PORT=1234;PROTOCOL=TCPIP;UID="+UID+";PWD="+PWD+";", "", "")
SystemError: <built-in function connect> returned NULL without setting an error

using python 3.8

jupyter lab version 3.0.14

anaconda version info:

Name: conda
Version: 4.10.3
Summary: OS-agnostic, system-level binary package manager.
Home-page: https://github.com/conda/conda
Author: Anaconda, Inc.
Author-email: conda@continuum.io
License: BSD-3-Clause
Location: c:\users\kissgabe\anaconda3\lib\site-packages

ibm_db version info:

Name: ibm-db
Version: 3.0.4
Summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS
Home-page: http://pypi.python.org/pypi/ibm_db/
License: Apache License 2.0
Location: c:\users\kissgabe\anaconda3\lib\site-packages

DB2 driver version info

DB21085I  Instance "DB2" uses "64" bits and DB2 code release "SQL10010" with
level identifier "0201010E".
Informational tokens are "DB2 v10.1.0.872", "s120403", "NTX64101", and Fix Pack
"0".
Product is installed at "C:\PROGRA~1\IBM\SQLLIB" with DB2 Copy Name "DB2COPY1".

Current Windows build:

Edition	Windows 10 Enterprise
Version	21H1
Installed on	‎9/‎30/‎2020
OS build	19043.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

**edit***
forgot original code(connection string info removed for security purposes):
----------------------------------------------------------------------------
import ibm_db as db
import pandas as pd
import ibm_db_dbi as dbi
import traceback
import getpass
import matplotlib.pyplot as plt

try:    
    UID
except NameError:
    UID = 'None'
    if UID == 'None' :
        UID = input('CPPS TSO USER ID =')
        prompt = 'Password for '+UID+': '
        PWD = getpass.getpass(prompt=prompt, stream=None)
try:
    con_db2 = db.connect("DATABASE=dbase;HOSTNAME=hostaddress;PORT=123;PROTOCOL=TCPIP;UID="+UID+";PWD="+PWD+";", "", "")
    conn_db2 = dbi.Connection(con_db2)
    print('Connected')
except:
    print('Connection failed. Check VPN and credentials.')
    print(traceback.format_exc())

**Comment by bimalkjha** [comment]
@Gabikakenobi This issue is fix by setting environment variables as posted on similar issue [here](https://github.com/ibmdb/python-ibmdb/issues/694#issuecomment-976446573). Please verify and confirm. Thanks.

**Comment by Gabikakenobi** [comment]
Nevermind.

On my Windows 10 OS I reset the IBM_DB_HOME environmental variable to "C:\Program Files\IBM\SQLLIB\clidriver" and changed access clearance to target folder to admin level and now I can connect again.

Thx for all comments people. Have a great weekend.
