### ISSUE TITLE
Support for trusted contexts

### ISSUE THREAD

**Issue by VictorLFandino** [ibmdb/python-ibmdb#693]
Does the ibm_db driver support trusted contexts by using connection string keywords?

Thank you very much

**Comment by bimalkjha** [comment]
@VictorLFandino Yes, ibm_db driver supports all features supported by IBM Data Server Driver for ODBC and CLI. Details about trusted connection support in Db2 is documented [here](https://www.ibm.com/docs/en/db2/11.5?topic=security-using-trusted-contexts-trusted-connections). Make sure, server is configured to support trusted context.

For ibm_db, to enable trusted context, you need to pass `Trusted_Connection=Yes;` in connection string. Then when you want to switch to trusted userid, use `ibmdb.set_option()` to set the attribute [SQL_ATTR_TRUSTED_CONTEXT_USERID](https://www.ibm.com/docs/en/db2/11.5?topic=attributes-connection-list#r0006816__trusted_context_userid). Also, you need to set option [SQL_ATTR_TRUSTED_CONTEXT_PASSWORD](https://www.ibm.com/docs/en/db2/11.5?topic=attributes-connection-list#r0006816__trusted_context_password) if the database server requires a password when switching users on a trusted connection. Then you can execute queries. Any operation after these set_option() will be executed by new userid. Thanks.

**Comment by VictorLFandino** [comment]
Thank you @bimalkjha
