### ISSUE TITLE
Python 3.8 - Symbol not found

### ISSUE THREAD

**Issue by ManeshKN** [ibmdb/python-ibmdb#696]
Hi,

I am using PyCharm 2021.2.3 (CE) and Python 3.8 as interpretator. When i am trying to import ibm_db I am getting the below error-

ImportError: dlopen(/venv/lib/python3.8/site-packages/ibm_db.cpython-37m-darwin.so, 2): Symbol not found: ___cxa_throw_bad_array_new_length Referenced from: /venv/lib/python3.8/site-packages/clidriver/lib/libdb2.dylib Expected in: /usr/lib/libstdc++.6.dylib in /venv/lib/python3.8/site-packages/clidriver/lib/libdb2.dylib

I tried uninstalling/installing ibm_db and ibm_db_sa few times and nothing helped. Not sure how to go around it. I referred to a similar issue on github but again not sure how to go about it. I am new to this and trying a little hard with these kind of issues.

Is there a known fix for this? Can somebody provide step by step guidance?

Thanks,

**Comment by ktsuench** [comment]
This looks like a dup of issue #691

**Comment by ManeshKN** [comment]
Thanks @ktsuench. I installed gcc through home-brew and was able to get to libstdc++6.dylib but Mac is not allowing me to copy the file to /usr/lib and I don't want to experiment with disabling the security configuration as well. Any other alternative you came across?

**Comment by ManeshKN** [comment]
I was able to finally solve this. Below is what I did-
1. Installed home-brew by following this link - [https://osxdaily.com/2018/03/07/how-install-homebrew-mac-os/]
2. Installed gcc through home-brew by simply running the command **brew install gcc** from my Mac terminal
3. After the gcc installation, you should be able to see the libstdc++.6.dylib file at /usr/local/Cellar/gcc/11.2.0_3/lib/gcc/11
4. Run **export DYLD_LIBRARY_PATH=/usr/local/Cellar/gcc/11.2.0_3/lib/gcc/11:${DYLD_LIBRARY_PATH}** from your MAC terminal. Here you basically are letting the system know where to find the libstdc++.6.dylib

**Comment by amukherjee28** [comment]
We have updated the fixed clidriver with proper linking of the library.
Please clean up the previous installation and install again.

This should resolve the issue.

Also with this fix there is no additional requirement for setting the DYLD_LIBRARY_PATH as well
