### ISSUE TITLE
SQLCODE=-1013M][CLI Driver] SQL1013N  The database alias name or database name "" could not be found.  SQLSTATE=42705

### ISSUE THREAD

**Issue by ak19952711** [ibmdb/python-ibmdb#699]
conn = db.connect("DATABASE=fvtclddb;HOSTNAME=n000a273.cloud.icds.ibm.com;PORT=50602;PROTOCOL=SOCKETS;Security=SSL;UID=***;PWD=***;SECURITY=SSL;SSLClientKeyStoreDB=C:/Security/RDC_PP;SSLClientKeyStoreDBPassword=***;","","")

**Comment by imavo** [comment]
It is telling you that the database called fvtclddb does not exist at the db2-instance on hostname n000a273.cloud.icds.ibm.com that is listening on port 50602.  Some typo ?
