### ISSUE TITLE
SQLCODE=-204ver][DB2/LINUXX8664] SQL0204N  "DB2ADMIN.TEST" ê?ò????′?¨ò?μ???3??￡  SQLSTATE=42704

### ISSUE THREAD

**Issue by kxmatjob** [ibmdb/python-ibmdb#700]
when i select a not exist table, 
print(ibm_db.stmt_errormsg()), show mistaken code, SQLCODE=-204ver][DB2/LINUXX8664] SQL0204N  "DB2ADMIN.TEST" ê?ò????′?¨ò?μ???3??￡  SQLSTATE=42704

so i try encode gbk, but the result is:
print(ibm_db.stmt_errormsg().encode('utf-8').encode('gbk',errors='ignore'))
SQLCODE=-204][CLI Driver][DB2/LINUXX8664] SQL0204N  "DB2ADMIN.TEST" 脢脟脪禄赂枚脦麓露篓脪氓碌脛脙没鲁脝隆拢  SQLSTATE=42704

my database set: 
    db2set DB2TERRITORY=CN
    db2set DB2COUNTRY=86
    db2set DB2CODEPAGE=1386

thanks.

**Comment by imavo** [comment]
What is the operating-system where python is running? 
What is the python version?
What is the version of the ibm_db module?

**Comment by kxmatjob** [comment]
win7 x64python 3.6.8 x86ibm_db3.1.0,  nt32_odbc_clidb2 server V10.1发自我的华为手机

**Comment by imavo** [comment]
On the Windows-7 x64 where python runs,  which Db2-driver are you using with python?
Specifically, before installing the ibm_db module, was environment-variable IBM_DB_HOME set , pointing to a pre-existing Db2-client installation?  (your message mentions nt32_odbc_clidb2 server V10.1 but you do not explain exactly why you use that old version, and you did not explain how you are certain it is the version that pyton really uses).


Also, on that Windows-7 x64 machine where python is running, is the environment variable DB2CODEPAGE set  before python runs,  and if so , to which vlue?  

Also, on your Db2-server, which appears to run on Llinx, what is the text output of the `db2level` command? We need to know this to determine the best client-side driver version that should be installed on the Windows-7 x64 client.

**Comment by kxmatjob** [comment]
I connect linux db2 used ibm_db-3.1.0,
db2 client version v10.5,
db2 server version v10.1,
i have't new vesion license :)

Here are the details:

---------------------------------
----client win7 x64:
---------------------------------
environment-variable:
IBM_DB_HOME
D:\Program Files (x86)\python\Lib\site-packages\ibm_db-3.1.0-py3.6.egg\clidriver

C:\Program Files (x86)\IBM\SQLLIB\BIN>db2level
DB21085I 此实例或安装（适用的实例名："DB2INST1"）使用 "32" 位和级别标识为
"0602010E" 的 DB2 代码发行版 "SQL10051"。
参考标记为 "DB2 v10.5.100.64"、"special_31160" 和 "IP23520_31160"，修订包为
"1"。
产品使用 DB2 副本名 "DB2COPY1" 安装在 "C:\PROGRA~2\IBM\SQLLIB" 中。

C:\Program Files (x86)\IBM\SQLLIB\BIN>db2set -all
[e] DB2INCLUDE=C:\Program Files (x86)\IBM\SQLLIB\include
[e] DB2PATH=C:\Program Files (x86)\IBM\SQLLIB
[i] DB2TERRITORY=CN
[i] DB2INSTPROF=C:\ProgramData\IBM\DB2\DB2COPY1
[i] DB2COUNTRY=86
[i] DB2COMM=TCPIP
[i] DB2CODEPAGE=1386
[i] DB2_PARALLEL_IO=*
[i] DB2AUTOSTART=YES
[g] DB2_COMPATIBILITY_VECTOR=MYS
[g] DB2_EXTSECURITY=NO
[g] DB2_COMMON_APP_DATA_PATH=C:\ProgramData
[g] DB2SYSTEM=CS20
[g] DB2PATH=C:\Program Files (x86)\IBM\SQLLIB
[g] DB2INSTDEF=DB2INST1
[g] DB2ADMINSERVER=DB2DAS00


---------------------------------
----server linux redhat:
---------------------------------
***@***.*** ~]$ db2level
DB21085I Instance "db2inst1" uses "64" bits and DB2 code release "SQL10010"
with level identifier "0201010E".
Informational tokens are "DB2 v10.1.0.0", "s120403", "LINUXAMD64101", and Fix
Pack "0".
Product is installed at "/opt/ibm/db2/V10.1".

***@***.*** ~]$ db2set -all
[i] DB2TERRITORY=CN
[i] DB2COUNTRY=86
[i] DB2COMM=TCPIP
[i] DB2CODEPAGE=1386
[i] DB2_PARALLEL_IO=*
[i] DB2AUTOSTART=YES
[g] DB2FCMCOMM=TCPIP6
[g] DB2SYSTEM=localhost.localdomain
[g] DB2INSTDEF=db2inst1



At 2021-12-14 17:22:37, "imavo" ***@***.***> wrote:

On the Windows-7 x64 where python runs, which Db2-driver are you using with python?
Specifically, before installing the ibm_db module, was environment-variable IBM_DB_HOME set , pointing to a pre-existing Db2-client installation? (your message mentions nt32_odbc_clidb2 server V10.1 but you do not explain exactly why you use that old version, and you did not explain how you are certain it is the version that pyton really uses).

Also, on that Windows-7 x64 machine where python is running, is the environment variable DB2CODEPAGE set before python runs, and if so , to which vlue?

Also, on your Db2-server, which appears to run on Llinx, what is the text output of the db2level command? We need to know this to determine the best client-side driver version that should be installed on the Windows-7 x64 client.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by imavo** [comment]
Db2-registry variables (those visible with the `db2set` command) are different from Microsoft-Windows environment variables. The question I asked was, in your cmd.exe session, before you run python, is the environment variable called DB2CODEPAGE set, and to which value.  Use the command `echo %DB2CODEPAGE%` before running python, and report the result.

It is not enough to show the current value of IBM_DB_HOME variable. The question I asked was whether this variable was already set BEFORE you installed module ibm_db. If the value was correctly set before installing module ibm_db then clidriver would not have been installed. But your answer *suggests* (but does not explicitly confirm) that clidriver is installed. If clidriver is installed then its version is most likely the v11.5 version that arrives by default with version 3.1.0 of module ibm_db. I suspect that the v11.5 clidriver is somehow conflicting with the local Db2-v10.5 server.  


If you have access to a different clean workstation that does not have any pre-existing Db2 product, then on that workstation , check if you can recreate the symptom.

**Comment by kxmatjob** [comment]
thanks for your help :)1.echo %DB2CODEPAGE% in cmd.exe show %DB2CODEPAGE%.2.i not set IBM_DB_HOME before install ibm_db,now i detete it.3.the same error return in other db2 server，DB2 v11.1.3.3 and DB2 v11.5.6.04.At last,i try set Microsoft-Windows environment variable: DB2CODEPAGE 1386. however it return the same result.发自我的华为手机-------- 原始邮件 --------发件人： imavo ***@***.***>日期： 2021年12月15日周三 19:39收件人： ibmdb/python-ibmdb ***@***.***>抄送： kxmatjob ***@***.***>, Author ***@***.***>主    题： Re: [ibmdb/python-ibmdb] SQLCODE=-204ver][DB2/LINUXX8664] SQL0204N  "DB2ADMIN.TEST" ê?ò????′?¨ò?μ???3??￡  SQLSTATE=42704 (Issue #700)
Db2-registry variables (those visible with the db2set command) are different from Microsoft-Windows environment variables. The question I asked was, in your cmd.exe session, before you run python, is the environment variable called DB2CODEPAGE set, and to which value.  Use the command echo %DB2CODEPAGE% before running python, and report the result.
It is not enough to show the current value of IBM_DB_HOME variable. The question I asked was whether this variable was already set BEFORE you installed module ibm_db. If the value was correctly set before installing module ibm_db then clidriver would not have been installed. But your answer suggests (but does not explicitly confirm) that clidriver is installed. If clidriver is installed then its version is most likely the v11.5 version that arrives by default with version 3.1.0 of module ibm_db. I suspect that the v11.5 clidriver is somehow conflicting with the local Db2-v10.5 server.
If you have access to a different clean workstation that does not have any pre-existing Db2 product, then on that workstation , check if you can recreate the symptom.

**Comment by amukherjee28** [comment]
@kxmatjob 

We have made some changes in the latest release of ibm_db with respect to unicode character encoding.
Could you try install ibm_db version 3.1.1 (the latest version available) and check if the issue still remains.

I am attaching a sample code of different error message. Could you run the same and send me the output of the program.

```
import ibm_db

conn_str = "CONNECTION STRING"

print("=> Creating the connection")
try:
    connection = ibm_db.connect(conn_str,"","")
    print("=> Connected to Server ... SUCCESSFULL")
except:
    print("=> Connection to server .... FAILED")
    print("Error Description = ")
    print(ibm_db.conn_errormsg())
    print("SQLSTATE = " + ibm_db.conn_error())
    exit(0)

print("=> Error during CREATE TABLE SYNTAX")

create = "create table test_tab_error (C1 innt, C2 VARCHAR(30))"

try:
    rc = ibm_db.exec_immediate(connection,create)
    print("=> Table Created")
except:
    print("=> Error creating Table")
    print("MESSAGE : " + ibm_db.stmt_errormsg())
    print("SQLSTATE : " + ibm_db.stmt_error())

create = "create tabl test_tab_error (C1 int, C2 VARCHAR(30))"

try:
    rc = ibm_db.exec_immediate(connection,create)
    print("=> Table Created")
except:
    print("=> Error creating Table")
    print("MESSAGE : " + ibm_db.stmt_errormsg())
    print("SQLSTATE : " + ibm_db.stmt_error())

create = "create table test_tab_error (C1 int, C1 VARCHAR(30))"

try:
    rc = ibm_db.exec_immediate(connection,create)
    print("=> Table Created")
except:
    print("=> Error creating Table")
    print("MESSAGE : " + ibm_db.stmt_errormsg())
    print("SQLSTATE : " + ibm_db.stmt_error())

create = "create table test_tab_error (C1 int, C2 VARCHAR(30))"

try:
    rc = ibm_db.exec_immediate(connection,create)
    print("=> Table Created")
except:
    print("=> Error creating Table")
    print("MESSAGE : " + ibm_db.stmt_errormsg())
    print("SQLSTATE : " + ibm_db.stmt_error())

insert = "insert into test_tab_error values(ab,1)"

try:
    rc = ibm_db.exec_immediate(connection,insert)
    print("=> Inserted Successfully")
except:
    print("=> Error Inserting Data")
    print("MESSAGE : " + ibm_db.stmt_errormsg())
    print("SQLSTATE : " + ibm_db.stmt_error())

insert = "insert into test_tab_error values(1,'abcdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')"

try:
    rc = ibm_db.exec_immediate(connection,insert)
    print("=> Inserted Successfully")
except:
    print("=> Error Inserting Data")
    print("MESSAGE : " + ibm_db.stmt_errormsg())
    print("SQLSTATE : " + ibm_db.stmt_error())

insert = "insert into test_tab_error values(1,'acbd',2)"

try:
    rc = ibm_db.exec_immediate(connection,insert)
    print("=> Inserted Successfully")
except:
    print("=> Error Inserting Data")
    print("MESSAGE : " + ibm_db.stmt_errormsg())
    print("SQLSTATE : " + ibm_db.stmt_error())

insert = "insert into test_tab_error value(1,'acbd')"

try:
    rc = ibm_db.exec_immediate(connection,insert)
    print("=> Inserted Successfully")
except:
    print("=> Error Inserting Data")
    print("MESSAGE : " + ibm_db.stmt_errormsg())
    print("SQLSTATE : " + ibm_db.stmt_error())

insert = "insert into test_tab_error(c3,c4) values(1,'acbd')"

try:
    rc = ibm_db.exec_immediate(connection,insert)
    print("=> Inserted Successfully")
except:
    print("=> Error Inserting Data")
    print("MESSAGE : " + ibm_db.stmt_errormsg())
    print("SQLSTATE : " + ibm_db.stmt_error())

insert = "select * fro test_tab_error"

try:
    rc = ibm_db.exec_immediate(connection,insert)
    print("=> selected Successfully")
except:
    print("=> Error Fetching Data")
    print("MESSAGE : " + ibm_db.stmt_errormsg())
    print("SQLSTATE : " + ibm_db.stmt_error())

insert = "select C1,C1 from test_tab_error"

try:
    rc = ibm_db.exec_immediate(connection,insert)
    print("=> selected Successfully")
except:
    print("=> Error Fetching Data")
    print("MESSAGE : " + ibm_db.stmt_errormsg())
    print("SQLSTATE : " + ibm_db.stmt_error())
```

Also as matter of fact with windows we have a know issue where the error message is corrupted when displayed.
#468 
We are trying to fix the issue in the next release.

Thanks

**Comment by kxmatjob** [comment]
thanks, here is the test result.


=> ibm_db.__version__ 3.1.1
=> Creating the connection
=> Connected to Server ... SUCCESSFULL
=> Error creating Table
MESSAGE :
SQLSTATE :
=> Error creating Table
MESSAGE : [IBM][CLI Driver][DB2/NT] SQL0104N  ÔÚ "create tabl " ºóÃæÕÒµ½Òì³£±ê¼Ç "test_tab_error"¡£Ô¤ÆÚ±ê¼Ç SQLCODE=-104pace>"¡£  SQLSTATE=42601
SQLSTATE : 42601
=> Error creating Table
 SQLCODE=-612M][CLI Driver][DB2/NT] SQL0612N  "C1" ÊÇÒ»¸öÖØ¸´µÄÃû³Æ¡£  SQLSTATE=42711
SQLSTATE : 42711
=> Table Created
=> Error Inserting Data
MESSAGE :
SQLSTATE :
=> Error Inserting Data
MESSAGE : [IBM][CLI Driver][DB2/NT] SQL0433N  Öµ "abcdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa SQLCODE=-433SQLSTATE=22001
SQLSTATE : 22001
=> Error Inserting Data
 SQLCODE=-117M][CLI Driver][DB2/NT] SQL0117N  ¸³ÖµÊýÄ¿ÓëÖ¸¶¨µÄ»òÒþº¬µÄÁÐÊý»ò±äÁ¿Êý²»Ò»Ñù¡£  SQLSTATE=42802 
SQLSTATE : 21S01
=> Error Inserting Data
MESSAGE : [IBM][CLI Driver][DB2/NT] SQL0104N  ÔÚ "into test_tab_error" ºóÃæÕÒµ½Òì³£±ê¼Ç "value"¡£Ô¤ÆÚ±ê¼Ç¿É SQLCODE=-104ES"¡£  SQLSTATE=42601
SQLSTATE : 42601
=> Error Inserting Data
 SQLCODE=-206M][CLI Driver][DB2/NT] SQL0206N  "C3" ÔÚÊ¹ÓÃËüµÄÉÏÏÂÎÄÖÐÎÞÐ§¡£  SQLSTATE=42703
SQLSTATE : 42S22
=> Error Fetching Data
MESSAGE : [IBM][CLI Driver][DB2/NT] SQL0104N  ÔÚ "select * " ºóÃæÕÒµ½Òì³£±ê¼Ç "fro"¡£Ô¤ÆÚ±ê¼Ç¿ÉÄÜ°üÀ¨£º"FRO SQLCODE=-104E=42601
SQLSTATE : 42601
=> selected Successfully

**Comment by kxmatjob** [comment]
Thanks, this is the souce code and test result. I used encode() for get a simplified chinese.




# -*- coding: utf-8 -*-
import ibm_db
.....
insert ="select C1,C1 from db2admin.test_tab_errorxxx"
try:
    rc = ibm_db.exec_immediate(connection,insert)
    print("=> selected Successfully")
except:
    print("=> Error Fetching Data")
    print("MESSAGE : "+ ibm_db.stmt_errormsg())
    print("MESSAGE : "+ ibm_db.stmt_errormsg().encode('utf-8',errors='ignore').decode('gbk',errors='ignore'))
    print("MESSAGE : "+ ibm_db.stmt_errormsg().encode('gbk',errors='ignore').decode('gbk',errors='ignore'))
    print("SQLSTATE : "+ ibm_db.stmt_error())




=> Error Fetching Data SQLCODE=-204M][CLI Driver][DB2/NT] SQL0204N "DB2ADMIN.TEST_TAB_ERRORXXX" ÊÇÒ»¸öÎ´¶¨ÒåµÄÃû³Æ¡£ SQLSTATE=42704 MESSAGE : [IBM][CLI Driver][DB2/NT] SQL0204N "DB2ADMIN.TEST_TAB_ERRORXXX" 脢脟脪禄赂枚脦麓露篓脪氓碌脛脙没鲁脝隆拢 SQLST SQLCODE=-204 SQLCODE=-204M][CLI Driver][DB2/NT] SQL0204N "DB2ADMIN.TEST_TAB_ERRORXXX" ¨ SQLSTATE=42704 SQLSTATE : 42S02

**Comment by amukherjee28** [comment]
New release 3.1.2 fixed the issue.

**Comment by kxmatjob** [comment]
The same output I update release 3.1.2, so what i should do ?

`MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0204N  "DB2INST1.TEST_TAB_ERROR" ÊÇÒ»¸öÎ´¶¨ÒåµÄÃû³Æ¡£  SQLSTATE=42704  SQLCODE=-204
MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0204N  "DB2INST1.TEST_TAB_ERROR" 脢脟脪禄赂枚脦麓露篓脪氓碌脛脙没鲁脝隆拢  SQLSTATE=42704  SQLCODE=-204
MESSAGE : [IBM][CLI Driver][DB2/LINUXX8664] SQL0204N  "DB2INST1.TEST_TAB_ERROR" ¨  SQLSTATE=42704  SQLCODE=-204
SQLSTATE : 42S02`
