### ISSUE TITLE
[IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3". SQLCODE=-1042

### ISSUE THREAD

**Issue by lzx4627** [ibmdb/python-ibmdb#704]
I tried to connect to db2 using python3.6, but I encountered this problem
`[IBM][CLI Driver] SQL10007N Message "0" could not be retrieved.  Reason code: "3". SQLCODE=-1042`

And my DYLD_LIBRARY_PATH environment variable configuration is as follows：
`echo $DYLD_LIBRARY_PATH`

`/opt/das/app/api/sqlodbc/packages/ibm_db-3.1.0/clidriver/lib:/opt/das/app/api/sqlodbc/packages/ibm_db-3.1.0/clidriver/lib/icc`

**Comment by imavo** [comment]
This message usually results from environment variables that are not set, which the clidriver needs to be able to operate.  In this case the clidriver is trying to get an error message from its message file but cannot find its message files.

You may also need the clidriver bin directory on the PATH environment variable .

What is the operating-system (name, version, bitness) that runs python?

Are you running the python at the shell (command line), or in some tool such as a notebook or gui or interactive python? Please give details.

What is the output of `pip show ibm_db | grep Location` ?

**Comment by lzx4627** [comment]
I have solved it.
I added `clidriver/lib` to `/etc/ld.so.conf.d`

**Comment by lampwins** [comment]
@lzx4627 can you provide more detail on what you did to resolve this? `/etc/ld.so.conf.d` is a directory, so are you saying you copied all of `clidriver/lib` there?

**Comment by bimalkjha** [comment]
@lampwins The SQL10007N error mostly comes due to missing `clidriver/msg` directory or some file under it, which points out that installation of clidriver is not proper or an incorrect version is being used.
If `msg` files are there and we do not see any issue, then we need to look on other causes. The fix that lzx4627 has used is to add the absolute path of `clidriver\lib` directory in file `/etc/ld.so.conf.d`. If have this file in the system then you need to add a line in this file at end. Thanks.

**Comment by ksaket1998** [comment]
@bimalkjha can you please explain the process to resolve this in steps. I could not find /etc/ld.so.conf.d in my system.
I'm using windows 10, I have a python script which I use to connect to DB2 using ibm_db module in python. It works fine when I connect using script, but when I convert it to exe using pyinstaller, it gives this error [IBM][CLI Driver] SQL10007N Message "0" could not be retrieved. Reason code: "6". SQLCODE=-1042

**Comment by ksaket1998** [comment]
Hi @bimalkjha, I do not see clidriver/lib/icc in the folder, do you mean `clidriver\bin\icc64\c\icc\icclib` ?

**Comment by bimalkjha** [comment]
@ksaket1998 Yes, icc64 is correct.
You need to update your script as below:
```
import os
clidriver_lib_path = 'C:\\Users\\..l\\anaconda3\\Lib\\site-packages\\clidriver\\lib'
clidriver_bin_path = 'C:\\Users\\..l\\anaconda3\\Lib\\site-packages\\clidriver\\bin'
clidriver_lib_icc_path = 'C:\\Users\\..l\\anaconda3\\Lib\\site-packages\\clidriver\\lib\\icc64'
if not os.path.isdir(clidriver_bin_path):
    print("Invalid clidriver PATH: " + clidriver_bin_path)
    os._exit(0)

current_lib = os.environ.get('LIB', '')
new_lib = f"{clidriver_bin_path};{clidriver_lib_path};{clidriver_lib_icc_path};{current_lib}"
os.environ['LIB'] = new_lib
os.add_dll_directory(new_lib)
import ibm_db
```
Thanks.
