### ISSUE TITLE
name 'arch_' is not defined for installing in container python images 

### ISSUE THREAD

**Issue by Netozs** [ibmdb/python-ibmdb#708]
I receive this error when I try to build an image from this Dockerfile below, succesfully built it before on Windows, now on Mac (Monterey) I get an error, I've also tried different images for python.
Dockerfile:
```
FROM registry.access.redhat.com/ubi8/python-39
WORKDIR /app
ADD . /app
COPY requirements.txt /app
RUN pip3 install -r requirements.txt

CMD [ "uwsgi" ,"uwsgi.ini" ]
```
Error: 
```
 => ERROR [6/6] RUN pip3 install -r requirements.txt                                                                                                            7.3s
------                                                                                                                                                               
 > [6/6] RUN pip3 install -r requirements.txt:                                                                                                                       
#10 0.468 Collecting ibm_db                                                                                                                                          
#10 0.666   Downloading ibm_db-3.1.0.tar.gz (797 kB)                                                                                                                 
#10 1.063   Installing build dependencies: started                                                                                                                   
#10 2.999   Installing build dependencies: finished with status 'done'                                                                                               
#10 3.002   Getting requirements to build wheel: started
#10 3.087   Getting requirements to build wheel: finished with status 'error'
#10 3.087   ERROR: Command errored out with exit status 1:
#10 3.087    command: /opt/app-root/bin/python3 /opt/app-root/lib64/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp06_kg5bu
#10 3.087        cwd: /tmp/pip-install-rwoj3veg/ibm-db_b2c9abe44c464a7b89f4510367b11bc0
#10 3.087   Complete output (17 lines):
#10 3.087   Detected 64-bit Python
#10 3.087   Traceback (most recent call last):
#10 3.087     File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#10 3.087       main()
#10 3.087     File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#10 3.087       json_out['return_val'] = hook(**hook_input['kwargs'])
#10 3.087     File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
#10 3.087       return hook(config_settings)
#10 3.087     File "/tmp/pip-build-env-b86vv374/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
#10 3.087       return self._get_build_requires(
#10 3.087     File "/tmp/pip-build-env-b86vv374/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
#10 3.087       self.run_setup()
#10 3.087     File "/tmp/pip-build-env-b86vv374/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
#10 3.087       exec(compile(code, __file__, 'exec'), locals())
#10 3.087     File "setup.py", line 230, in <module>
#10 3.087       easy_cli_path = os.path.join(tmp_path, 'ibm_db-%s.egg' % ("-".join([VERSION, "py"+sys.version.split(" ")[0][0:3]]) if('win32' in sys.platform) else "-".join([VERSION, "py"+sys.version.split(" ")[0][0:3], os_, arch_])), 'clidriver')
#10 3.087   NameError: name 'arch_' is not defined
```

**Comment by amukherjee28** [comment]
@Netozs 

Let me check this in the same docker image and come back. Looks like some of the dependencies are getting missed in the docker image and hence the installation is failing.

But I have one query to ask here.
Could you please let me know what kind of hardware the MAC OS is running on. Is it running on intel chip or the new Apple M1 chip.

Currently on MAC OS we are only supporting the x86_64 architecture (64 bit). Looks like the docker image is different from this and hence the error.

**Comment by Netozs** [comment]
Yeah, I think it's because of the M1 chip, are you planing on making it available for this in the future?

**Comment by amukherjee28** [comment]
I though so. We are on getting solution for M1. We are working on the new Hardware and its is under progress. Once completed we will have some update on this.

**Comment by bimalkjha** [comment]
@Netozs Install x64 version of python on M1 chip system and then install ibm_db. You can install this python: https://www.python.org/ftp/python/3.9.10/python-3.9.10-macosx10.9.pkg and verify. Thanks.

**Comment by amukherjee28** [comment]
Please check my last comment on the issue https://github.com/ibmdb/python-ibmdb/issues/712

You need to install the intel python instead of the basic ARM64 python.
Update your docker script to install from the link provided above.

**Comment by bimalkjha** [comment]
Above commit has pushed fix for this issue and it would be available with next release of ibm_db. Thanks.

**Comment by GilbertoAristizabalEmpire** [comment]
I'm getting the same issue trying to use Python 3.10.4 on Mac (v12 -Monterey) M1 chip. Any support for it?

**Comment by bimalkjha** [comment]
@GilbertoAristizabalEmpire You need to install x64 version of Python. Please check this comment: https://github.com/ibmdb/python-ibmdb/issues/708#issuecomment-1064273728

**Comment by rychrr** [comment]
> Please check my last comment on the issue #712
> 
> You need to install the intel python instead of the basic ARM64 python. Update your docker script to install from the link provided above.

Hi, Thanks for the support,  I've been following the thread, I am having similar issue setting up on docker, can you guide me on how to install the basic ARM64 python from the link.

**Comment by bimalkjha** [comment]
@rychrr ibm_db do not work with basic ARM64 python and you need to use `intel-only` version of python like https://www.python.org/ftp/python/3.9.13/python-3.9.13-macosx10.9.pkg . If you install this python and update environment variables to use this python (at list python -v should show x64 bit version instead of arm64), ibm_db works fine. Thanks.

**Comment by rychrr** [comment]
Thanks 

> @rychrr ibm_db do not work with basic ARM64 python and you need to use `intel-only` version of python like https://www.python.org/ftp/python/3.9.13/python-3.9.13-macosx10.9.pkg . If you install this python and update environment variables to use this python (at list python -v should show x64 bit version instead of arm64), ibm_db works fine. Thanks.

Thank you,
