### ISSUE TITLE
Can't connect to remote database in db2rc Tool due to "GSKit Error: 102" windows 10 but I can connect by cli and QMF 

### ISSUE THREAD

**Issue by mpasiani** [ibmdb/python-ibmdb#711]
trying to connect to a database I've catalogued using DB2 CL it is working from prompt and in the QMF too but I got error in to the **db2rc** tool. Could someone please help me?

**The error :** 
Connect failed
COM.ibm.db2.jdbc.DB2Exception: [IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "GSKit Error: 102".  SQLSTATE=42724

**CLI is working fine :**
C:\MAP\GCS_SSL\SSL>  db2cli validate -dsn database -connect -user xxxxx-passwd blablabla
------------------------------------------------------------------------------
Client information for the current copy (copy name: DB2COPY1):
------------------------------------------------------------------------------
Client Package Type       : IBM Data Server Client
Client Version (level/bit): DB2 v10.5.1000.898 (s180615/64-bit)
Client Platform           : NT 64BIT
Install/Instance Path     : C:\PROGRA~1\IBM\SQLLIB
Common App Data Path      : C:\ProgramData\IBM\DB2\DB2COPY1
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path *    : <Common App Data Path>\DB2\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : <Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : <Common App Data Path>\DB2\db2diag.log

* - Warning: db2dsdriver.cfg configuration file is found at the location which
will be deprecated soon. It is recommended to move this file to the location:
"C:\ProgramData\IBM\DB2\DB2COPY1\cfg\".

------------------------------------------------------------------------------
List of all IBM Data Server client packages on the current workstation:
------------------------------------------------------------------------------
Copyname Version Package Language Installed-Location

------------------------------------------------------------------------------
db2dsdriver.cfg schema validation for the entire file:
------------------------------------------------------------------------------
Success: The schema validation completed successfully without any errors.

------------------------------------------------------------------------------
db2cli.ini validation for data source name "database":
------------------------------------------------------------------------------
[ Keywords used for the connection ]
Keyword                   Value
------------------------------------------------------------------------------
DATABASE                  database
PROTOCOL                  TCPIP
HOSTNAME                  server.az.dal.cpc.ibm.com
SERVICENAME               3703
SECURITY                  SSL
SSLCLIENTKEYSTOREDB       C:\MAP\GCS_SSL\SSL\CloudClient.kdb
SSLCLIENTKEYSTASH         C:\MAP\GCS_SSL\SSL\CloudClient.sth

------------------------------------------------------------------------------
db2dsdriver.cfg validation for data source name "database":
------------------------------------------------------------------------------
[ Parameters used for the connection ]
Keywords                  Valid For     Value
---------------------------------------------------------------------------
SSLCLIENTKEYSTASH         CLI,.NET,ESQL C:\MAP\GCS_SSL\SSL\CloudClient.sth
SSLCLIENTKEYSTOREDB       CLI,.NET,ESQL C:\MAP\GCS_SSL\SSL\CloudClient.kdb
SECURITYTRANSPORTMODE     CLI,.NET      SSL

------------------------------------------------------------------------------
Connection attempt for data source name "database":
------------------------------------------------------------------------------
[SUCCESS]
------------------------------------------------------------------------------
The validation is completed.
------------------------------------------------------------------------------

**Comment by bimalkjha** [comment]
@mpasiani You need to contact IBM Support for **db2rc** tool. We do not look into `db2rc` tool related issues. Thanks.
