### ISSUE TITLE
SystemError: <built-in function connect> returned NULL without setting an error (Windows 10)

### ISSUE THREAD

**Issue by liudikang** [ibmdb/python-ibmdb#714]
# Env
* OS: Windows 10 Pro 64 bit (19043.1466) 
* Enable UTF 8  language support
# Exception Code
python exception location
```
ibm_db.connect("DATABASE=dbname;HOSTNAME=host;PORT=50000;PROTOCOL=TCPIP;UID=db2inst1;PWD=pwd;", "", "")
```

I found the exception code through visual studio as follows
```
// _python_ibm_db_connect_helper
rc = SQLAllocHandle(SQL_HANDLE_ENV, SQL_NULL_HANDLE, &(conn_res->henv));
// rc return SQL_ERROR
if (rc != SQL_SUCCESS) {
    _python_ibm_db_check_sql_errors( conn_res->henv, SQL_HANDLE_ENV, rc,
                    1, NULL, -1, 1);
  break;
}
```
and in function `_python_ibm_db_check_sql_errors` ,`SQLGetDiagRec`  return `SQL_INVALID_HANDLE`
# Solution
When I tried turning off UTF-8 support in windows `Region Settings`, everything back to normal  

So does clidriver not work properly when windows is turned on utf-8 support?

**Comment by bimalkjha** [comment]
@liudikang clidriver supports UTF-8 encoding, but you need to set system environment variable DB2CODEPAGE=1208 to inform clidriver about it. Thanks.

**Comment by liudikang** [comment]
> @liudikang clidriver supports UTF-8 encoding, but you need to set system environment variable DB2CODEPAGE=1208 to inform clidriver about it. Thanks.

that's work for me, thanks

**Comment by hegaolovepython** [comment]
> @liudikang clidriver supports UTF-8 encoding, but you need to set system environment variable DB2CODEPAGE=1208 to inform clidriver about it. Thanks.

this answers save my life. many thanks.

**Comment by e-nurtin** [comment]
Thanks this helped a lot.
