### ISSUE TITLE
Issue using ibm_db in lambda - No module named 'ibm_db'.

### ISSUE THREAD

**Issue by astro44** [ibmdb/python-ibmdb#716]
Ran the pip install and collected all artifacts, FROM amazonlinux:1, in  /usr/local/lib....site-packages/
primarily included clidriver folder and other ibm prefixed files. (*runs great in EC2 instance)
__README.txt,          ibm_db_dbi.py,  __pycache__,       clidriver,      testfunctions.py,_
_ibm_db.cpython-37m-x86_64-linux-gnu.so,         tests.py_

Added to lambda layer...then in the lambda:

os.environ['IBM_DB_HOME'] to clidriver path
os.environ['LD_LIBRARY_PATH'] to  local '.'

`import ibm_db`

When running I still get No module named 'ibm_db'.

any ideas?
thanks in advance.

**Comment by amukherjee28** [comment]
@astro44 

No module found error is due to installation not done properly or some setup steps missed during configuration.

Please follow all steps to configure Python and configure site-packages in lambda and check.

Also with respect to environment path setting

IBM_DB_HOME should point to the clidriver path and LD_LIBRARY_PATH should point to clidriver/lib path in order to point proper libraries.

**Comment by astro44** [comment]
@amukherjee28  thank you for the fast response.  on the docker container it seems to work great... here is the docker file used:
`FROM amazonlinux:1
WORKDIR /
RUN yum update -y
# Install Python 3.7
RUN yum install gcc gcc-c++  openssl-devel bzip2-devel libffi-develD libffi-devel wget tar -y
RUN yum -y install zlib zlib-devel
RUN yum groupinstall "Development Tools" -y
RUN yum install python-devel -y
RUN wget https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz
RUN tar -xzvf Python-3.7.9.tgz
WORKDIR /Python-3.7.9
RUN ./configure --enable-optimizations
RUN make install
# Install Python packages
RUN mkdir /packages
RUN yum update -y

RUN pip3.7 install --upgrade pip
RUN pip3.7 install ibm_db

RUN mkdir -p /packages/ibm_db
RUN cp -r /usr/local/lib/python3.7/site-packages/ibm* /packages/ibm_db
RUN cp -r /usr/local/lib/python3.7/site-packages/clidriver /packages/ibm_db
RUN cp -r /usr/local/lib/python3.7/site-packages/certs /packages/ibm_db
RUN cd /packages/ibm_db`
- Then zips it up... zip -r ibm_db2-0.0.1.zip .* *
and use that as the lambda layer...  (*there are no files in lib64)... could there be another step needed for Lambda to see the layer?  
Thanks again,
-r

**Comment by astro44** [comment]
@amukherjee28 you can close this ticket out... its working as expected... the issue was that the lambda layer was NOT zipped under the expected "python" directory.  
once all files where under that directory it worked.
