### ISSUE TITLE
Run without admin privileges

### ISSUE THREAD

**Issue by xxjlee** [ibmdb/python-ibmdb#717]
ibmdb 3.1.1, Python 3.7.3, Windows 10.
I need to run the code without admin access, is this possible?
I cannot get it to work unless I start program with admin.
Thanks for any advice.
John

**Comment by amukherjee28** [comment]
@xxjlee 
Could you please explain a bit on what exactly you need to run without admin.
When you say run the code do you mean running python application using ibm_db driver?
Also please do mention on how the driver was installed. If the installation was done using ADMIN account/privilege then the working is expected to have admin rights for using the binaries.
Thanks

**Comment by xxjlee** [comment]
Hi,
  Yes when I run the python app using ibm_db driver, I need to start cmd window with Run as Administrator.  I only have one account on this laptop so all I did is issue pip install ibm_db from normal window (not administrator) I think.  I can try to uninstall and then try reinstalling making sure it is not using admin window.
Will try that. Thanks.
John

**Comment by xxjlee** [comment]
I uninstalled and reinstalled in cmd window with no admin privilege.  Cannot run python code unless I start
cmd with Admin.  This is going to present problem for us as we cannot run with admin privileges in prod.
pip install ibm_db
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting ibm_db
  Using cached ibm_db-3.1.1-py3-none-any.whl
Installing collected packages: ibm-db
Successfully installed ibm-db-3.1.1

**Comment by amukherjee28** [comment]
@xxjlee 

There are few things that we have to check in here.

1. What is the error you are getting when running from normal command prompt. Can you please put the error you are getting when running normally.
2. How was the python installed. Pip installation has dependency on the site-packages folders which is part of the python installation. So we need to be sure that the installation happened normally and any user has access to use the site-packages folder. This is purely from the installation point of view in windows operating system.

Can you please check on the above points.

**Comment by xxjlee** [comment]
Hi,
  Issue resolved. There was DB2 connect installed on my laptop.  I uninstalled that and it seems to be working now without admin access. Thanks.
  John
