### ISSUE TITLE
SSL Connection to DB2 throws error - [Error: [IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "".  SQLSTATE=42724

### ISSUE THREAD

**Issue by TheHun89** [ibmdb/python-ibmdb#718]
I have a **Windows** machine and am trying to connect to my company **DB2** database using **SSL**.  I am using the same ibm_db library _in Node and Python and am getting the same error_.  
**ibm_db 3.1.1  
Python 3.9.1**
VS Code 1.63.4
OS Windows 10 x64

Connection:

`ibm_db.connect("SslServerCertificate=C:\\Users\\xxxxxx\\DEV\\python-hello-world\\cacerts;SECURITY=SSL;DATABASE=xxxxxxx;HOSTNAME=xxxxxxxxxx.xxx.xxxxx.com;PORT=xxxxx;UID=xxxxxx;PROTOCOL=TCPIP;PWD=xxxxxxx;", '','')`

Error: 

`'[IBM][CLI Driver] SQL1109N  The command was not processed because the database manager failed to load the following DLL: "".  SQLSTATE=42724\r SQLCODE=-1109'`

How can I resolve this so that I can connect to the DB2 database?

**Comment by amukherjee28** [comment]
@TheHun89 

In the recent Windows machine we have seen that there has been some issue in loading GSKIT libraries responsible for secured (ssl) connections.

Let me point out two things for your ssl connection to work assuming all details provided in the connection string is correct.

1. For the SSLServerCertificate keyword please use the complete path to the certificate File.
2. Set the following PATH ```set PATH=<clidriver_folder_path>\bin\amd64.VC12.CRT;%PATH%```

Sometime libraries are loaded properly and hence we need to specify the path contanining msvc*.dll to load properly.

This should allow loading of the libraries and allow SSL connections.

**Comment by TheHun89** [comment]
@amukherjee28 

First thank you very much for the quick reply!
The path you mention with the \bin\amd64.VC12.CRT exists in the node modules for the Node project I have.  I added this to my system PATH as well as the Python one:
```
C:\Users\xxxxx\DEV\Docs\xx\2. Nodejs\hello world api\node_modules\ibm_db\installer\clidriver\bin\amd64.VC12.CRT
C:\Users\xxxxxx\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\clidriver\bin\x86.VC12.CRT
```

It still throws the same error:

`'[IBM][CLI Driver] SQL1109N The command was not processed because the database manager failed to load the following DLL: "". SQLSTATE=42724\r SQLCODE=-1109'`

I am using VS Code and closed and opened it after adding to my PATH.  Would I need to restart my machine?  

The name of the cert I'm using is 'cacerts' and it doesn't have an extension.  Does this matter?  I saw someone mention that it may need to have an .arm extension.

Is there anything I need to do to install this GSKit?

Please let me know if you need any more information or screenshots.  Again I really appreciate the help as I'm running out of ideas to troubleshoot the issue.

**Comment by bimalkjha** [comment]
@TheHun89 Could you please check with the person who gave you this `cacerts` file that what kind of certificate it is and why it do not have any extension? Normally, client certificate file generated from Db2 server system have .arm, .pem, .cert extensions.
Please check your `C:\Users\xxxxx\DEV\Docs\xx\2. Nodejs\hello world api\node_modules\ibm_db\installer\clidriver\db2dump` directory and share the `db2diag.log` file if it has post the error.
If you are able to reproduce the problem using simple node.js test program, then edit the file `ibm_db\installer\testODBCConnection.sh` file; comment line number 29 and uncomment line no 32. Modify line no 32 to run your node test program; save the file. Now, run this script file to run node.js test program. It will generate few db2 trace files name 1.*. zip all the generated files and share with us. Thanks.

**Comment by bimalkjha** [comment]
Try adding `C:\Users\xxxxxx\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\clidriver\bin;C:\Users\xxxxxx\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\clidriver\lib;C:\Users\xxxxxx\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\clidriver\bin\icc64` to LIB and PATH system environment variable. Then open a fresh command prompt, run your test program and share the result. Thanks.

**Comment by TheHun89** [comment]
@bimalkjha 

Thank you for the reply!

Also just fyi - a colleague of mine is getting the same exact error message on a Windows machine as well when he tries connecting to DB2.  He also mentioned he is not able to connect to an Oracle database using ibm_db.

The cacerts has a file type of 'File'.  I will inquire more information about it.

I followed the instructions for modifying and running the testODBCConnection.sh It gave me this message:
"Trace could not allocate the necessary IPC resources.  Please retry using a smaller buffer size."
It generated files 1.cli, 1.flw, 1.fmt, 1.fmtc and 1.trc but they are all empty.


I checked the below file after running npm start but there is a single line 'db2diag.log'
C:\Users\xxxxx\DEV\Docs\KT\2. Nodejs\hello world api\node_modules\ibm_db\installer\clidriver\db2\db2diag.txt


After adding these 4 to my PATH and LIB system variables I still get the same error when I run the python program:
C:\Users\xxxxx\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\clidriver\lib
C:\Users\xxxxx\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\clidriver\bin
C:\Users\xxxxx\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\clidriver\bin\icc
C:\Users\xxxxx\AppData\Local\Programs\Python\Python39-32\Lib\site-packages\clidriver\bin\x86.VC12.CRT

`'[IBM][CLI Driver] SQL1109N The command was not processed because the database manager failed to load the following DLL: "". SQLSTATE=42724\r SQLCODE=-1109'`

**Comment by bimalkjha** [comment]
@TheHun89 using `ibm_db` we can connect to only Db2 family of servers and not Oracle server. There should be different node driver for Oracle.
The `cacerts` file may not be generated correctly. Please tell to generate the certificate using gskit command `gsk8capicmd_64 -cert -extract -db "mydbserver.kdb" -pw "myServerPassw0rdpw0" -label "myselfsigned" -target "mydbserver.arm" -format ascii -fips` as documented under section 1.c. of Procedure on this page: https://www.ibm.com/docs/en/db2/10.5?topic=de-configuring-secure-sockets-layer-ssl-support-db2-instance
Also, I hope that Db2 server is configured properly to accept SSL connection as per above link.

Just noticed, you are adding x86 directories in env vars. Are you using 32bit Windows? Can you try installing ibm_db on an ntx64 system and try the connection? Thanks.

**Comment by bimalkjha** [comment]
In initial post you have mentioned OS as `OS Windows 10 x64`. Then you need to add `clidriver\bin\icc64` and `clidriver\bin\amd64.VC12.CRT` directories in PATH and LIB. Please clarify about os bit, share output of db2level and complete output of `npm install ibm_db` command. thanks.

**Comment by TheHun89** [comment]
@bimalkjha 

I will have to check with the DBA on Monday regarding the cert.  The server is set up to accept SSL as I can connect via Toad.

It looks like I have the 32 bit version of Python installed.  Should I uninstall it and install the matching OS 64 bit?  Would that cause an issue?
<img width="437" alt="db2level" src="https://user-images.githubusercontent.com/30477607/151614682-55c7b461-5d9e-484b-9c8a-869b0cf4dfdb.PNG">
<img width="524" alt="pythonV" src="https://user-images.githubusercontent.com/30477607/151614684-8e687f2f-4fe6-4b0b-9e2f-ab20df9e19cc.PNG">
<img width="301" alt="systemInfo" src="https://user-images.githubusercontent.com/30477607/151614932-76f8b176-bc39-46b8-ad83-8d9b4a572f19.PNG">



Do you just mean the output in the _console_ when I run the `npm i ibm_db` and `db2level `commands?  or the actual contents of the folder?

**Comment by bimalkjha** [comment]
@TheHun89 I mean output in the console.
Also, install x64 version of python and node.js. First let us check the connection issue with node.js and then we'll check the python issue. Thanks.

**Comment by TheHun89** [comment]
@bimalkjha 

I have x64 nodejs installed.  What do you need me to provide to check the connection for nodejs?  Do you want me to zip up and send the ibm_db folder from node_modules?

**Comment by bimalkjha** [comment]
@TheHun89 Your db2level output is not showing the python dir or node_modules path, but you have a version of db2 installed locally which is causing issue with the clidriver that comes with ibm_db and hence error. 
Set the system env var `IBM_DB_HOME` to the `C:\Program Files\SQLLIB` directory and then have a fresh installation of ibm_db. If IBM_DB_HOME is set, ibm_db will not download the clidriver but use the one pointed out by IBM_DB_HOME environment variable. Please try it and share the result. Thanks.

**Comment by bimalkjha** [comment]
> @bimalkjha
> 
> I have x64 nodejs installed. What do you need me to provide to check the connection for nodejs? Do you want me to zip up and send the ibm_db folder from node_modules?

We want to redirect the output of `npm install ibm_db` in a file like `npm i ibm_db > install.out` and share the install.out file. Or, page the complete output from console here.
Please set IBM_DB_HOME, then install and then try connection. It seems the copy of gskit in your system which got installed with SQLLIB under program files/ibm/gsk8 is causing confusion with the icc lib of clidriver. Thanks.

**Comment by TheHun89** [comment]
@bimalkjha 

I set IBM_DB_HOME to C:\Program Files\SQLLIB and did a fresh install of ibm_db with node and python and am still getting the same error message.

<img width="462" alt="python_install_ibm_db" src="https://user-images.githubusercontent.com/30477607/151619108-00fa89f4-06e3-43c2-95d5-f8b18a3d65ee.PNG">
<img width="444" alt="node_install_ibm_db" src="https://user-images.githubusercontent.com/30477607/151619166-647958d0-d318-40ef-934b-613f92c0b8b9.PNG">
<img width="232" alt="ibm_db_home- sys variable" src="https://user-images.githubusercontent.com/30477607/151619200-14065367-60c6-4469-9467-efb59d864b02.PNG">

**Comment by TheHun89** [comment]
@bimalkjha 

Not sure if this is helpful but the DB2INSTANCE system var is set to DB2_01

**Comment by TheHun89** [comment]
actually I think it might be working now - let me build a query and I will respond if I can confirm it's successful or not

**Comment by TheHun89** [comment]
@bimalkjha  @amukherjee28 

I confirmed it is now working!  I think setting the IBM_DB_HOME to C:\Program Files\SQLLIB and doing a fresh install of ibm_db with node and python did the trick.  I think additionally I needed to close down all cmd and VS Code windows.  

Thank you very much for the fast replies and for your help resolving this issue!!!

**Comment by MrsMystique** [comment]
THANK YoU guys so mach) i thought im gonna die with this errors with db and clidraver) now its working
