### ISSUE TITLE
Unable to install ibm-db 3.0.2 for Python 3.7.5

### ISSUE THREAD

**Issue by amitkumar41** [ibmdb/python-ibmdb#721]
OS: Ubuntu 18.04
Python version: 3.7.5
ibm-db: 3.0.2

pip install of ibm-db fails with error:

`(venv) root@hegemony1:~/qp/query-processor-dev/python-components# python --version
Python 3.7.5
(venv) root@hegemony1:~/qp/query-processor-dev/python-components# pip install ibm-db==3.0.2
Collecting ibm-db==3.0.2
  Using cached ibm_db-3.0.2.tar.gz (718 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Detected 64-bit Python
      Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
      error in ibm_db setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by amukherjee28** [comment]
This error is in par with the latest setuptools changes in the new version.
We have already released new version and the latest version right now is 3.1.1.

Please try installing the new version or if you want to continue with the particular version of 3.0.2 then downgrade the setuptools to the older version.

Thanks

**Comment by amitkumar41** [comment]
thanks, changing to 3.1.1 worked
