### ISSUE TITLE
pip install erroring

### ISSUE THREAD

**Issue by baarongit** [ibmdb/python-ibmdb#722]
Hey,

We have tried pip install commands on the ibm-db module for multiple versions over multiple versions of python. We tried on several machines and in docker with the same error.

This had been working for several years until today.

Any help would be appreciated.

    urllib.error.HTTPError: HTTP Error 500: Internal Server Error
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/54/8a/54857a841cbd485d68f9852dfc16d27b069987a65ade38bb9288471ae98b/ibm_db-2.0.7.tar.gz#sha256=3db1dab4f5ea2efa37b3e8cdda0f19e60a37c716f56a12455dd40e8dad56e64f (from https://pypi.org/simple/ibm-db/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement ibm-db==2.0.7 (from versions: 0.2.0, 0.2.6, 0.2.7, 0.2.9, 0.2.9.1, 0.3.0, 0.4.0, 0.4.1, 0.6.0, 0.7.0, 0.7.2, 0.7.2.1, 0.7.2.5, 0.8.0, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.4.1, 2.0.5, 2.0.5.1, 2.0.6.1, 2.0.7, 2.0.8a0, 2.0.8, 2.0.9, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.1.0, 3.1.1)
ERROR: No matching distribution found for ibm-db==2.0.7
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

**Comment by telnoratti** [comment]
Also seeing this issue. It seems that https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz is returning a 500 error.

**Comment by sachinshinde1391** [comment]
Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
is resulting in
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by zenflow** [comment]
Does anyone have a contact at IBM to get this file back on their server?

**Comment by baarongit** [comment]
The file has been restored!
