### ISSUE TITLE
Using ibm_db with Python 3.9

### ISSUE THREAD

**Issue by Lenyas66** [ibmdb/python-ibmdb#723]
I was able to install ibm_db in my Pycharms using local artifactory, but still all ibm_db functions appear to be unavailable.

![ibm_db installation](https://user-images.githubusercontent.com/99292434/153076421-3a5b66e6-9181-4316-b7e7-5be8c3a4b28f.PNG)
![ibm_db functions are not available](https://user-images.githubusercontent.com/99292434/153076440-44677170-854d-435e-96ab-f18b15cef50e.PNG)

I am trying to install also ibm_db_py3, but getting the following error:

Collecting ibm_db_py3
  Downloading https://us-artifactory.prudential.com/artifactory/api/pypi/pypi-virtual/packages/packages/94/d7/24b23fb482acc581c2c5ec025a304f6ade2e8ef08e23b7561148ff2f21a4/ibm_db_py3-2.0.5
.tar.gz (155 kB)
     |████████████████████████████████| 155 kB ...
  Preparing metadata (setup.py) ... done
ERROR: No .egg-info directory found in C:\Users\X250864\AppData\Local\Temp\pip-pip-egg-info-bb9thtgq

Looks like similar issue was already brought up (https://github.com/actions/setup-python/issues/165), but the solutions don't appear to be working for me.
Would appreciate some help.

Thanks,

Leonid

**Comment by amukherjee28** [comment]
@Lenyas66 

I did the same in window with python3.9 and things worked fine for me.
Firstly let me talk about the installation.

Currently directly installation through Pycharm is not supported and hence its suggested to install the ibm_db driver using the command prompt interface.

Once the installation is successful you can use the ```import ibm_db``` into pycharm programs and use all of the supported API's.

In the example code shown in the picture I can see from line number 30. I hope you are using the import statement before using the API.

Thanks

**Comment by Lenyas66** [comment]
@amukherjee28 

Thank you for your reply.

I did installation thru PyCharm, but used our company's artifactory.

PS C:\Users\X250864\PycharmProjects\Sylvan> pip install ibm_db
Looking in indexes: https://X250864:****@us-artifactory.prudential.com/artifactory/api/pypi/pypi-virtual/simple
Requirement already satisfied: ibm_db in c:\users\x250864\pycharmprojects\pythonproject\venv\lib\site-packages (3.1.1)

![ibm_db Pycharm installation](https://user-images.githubusercontent.com/99292434/153289457-2bfc9976-8438-40df-8560-b23ae3a985eb.PNG)

I do use `import ibm_db` before calling the functions.

If you saying that it should be done separately, could you tell me, which command I should be using and where it needs to be installed? 

I did install the driver separately as well. Do I need to uninstall it in Pycharms then? 
Also, I have IBM_DB_HOME set to the following directory, where I had the driver installed.

C:\Program Files\IBM\SQLLIB
![IBM driver installation](https://user-images.githubusercontent.com/99292434/153290106-92fba4a1-5e0d-4ef0-bb47-c2188875f7e8.PNG)

**Comment by amukherjee28** [comment]
@Lenyas66 From the data received I do not see any issues with respect to the way things are implemented.

There are few things we need to check in this case.
1. The python version used for installing the package and version used for running the application should be same. Can you please check on this once.
2. Did you try restarting the pycharm after installing the driver.
3. Any particular reason you are using separate repository for installing the ibm_db instead of the actual pypi site.

**Comment by Lenyas66** [comment]
Please see the answers below in blue.

I suspect, that it could be PyCharm environment issue rather than the
driver itself.

Could you please answer the question about environment variable (s) though
and local installation outside of PyCharm?

Thanks,

Leonid

**Comment by amukherjee28** [comment]
@Lenyas66 

I do not think setting IBM_DB_HOME has any impact when you are using pycharm. As in the screen shot I do see clidriver in the site-packages folder.
Also the error message is more of not being able to read ibm_db.py file which loads ibm_db libraries.

Not sure why that loading is failing.

Because when the site-packages folder of pycharm contains the necessary files and folders it should be able to load.

Can you send across the ibm_db.py file that you have in the site-packages folder and also check if the folder ibm_db_dll contains a readable ibm_db.dll file.

**Comment by Lenyas66** [comment]
Sure. Will do it later after I connect to work.

Thanks,

Leonid

**Comment by Lenyas66** [comment]
Please see below.

ibm_db.py

`import os
import sys
if 'clidriver' not in os.environ['PATH']:
    os.environ['PATH'] = os.environ['PATH'] + ";" + os.path.join(os.path.abspath(os.path.dirname(__file__)), 'clidriver', 'bin')
if sys.version_info >= (3,8,):
    if 'IBM_DB_HOME' not in os.environ:
        os.add_dll_directory(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'clidriver', 'bin'))
    else:
        ibm_db_home = os.environ['IBM_DB_HOME'].strip('"')
        os.add_dll_directory(os.path.join(ibm_db_home, 'bin'))
def __bootstrap__():
   global __bootstrap__, __loader__, __file__
   import sys, pkg_resources, imp
   __file__ = pkg_resources.resource_filename(__name__,'ibm_db_dlls\ibm_db.dll')
   __loader__ = None; del __bootstrap__, __loader__
   imp.load_dynamic(__name__,__file__)
__bootstrap__()`

DLL location 

![image](https://user-images.githubusercontent.com/99292434/153429273-d0efbe62-cdaf-473d-ad64-0fbfddf45cac.png)

**Comment by Lenyas66** [comment]
I didn't mean to close it, as it is still unresolved.

**Comment by Lenyas66** [comment]
I think, I got to the bottom of it.

Somehow, it doesn't interpret the functions correctly, but it runs successfully!

Not sure, where bug is: in Pycharm or the driver, but at least I am able to make it work. :-)

![image](https://user-images.githubusercontent.com/99292434/153523552-18860718-131a-438a-b415-5d341956d586.png)
