### ISSUE TITLE
Missing 3.1.1 tag

### ISSUE THREAD

**Issue by vegraux** [ibmdb/python-ibmdb#724]
I can find ibm-db 3.1.1 on [pypi](https://pypi.org/project/ibm-db/), but I can't find any reference to it on this remote. Could you push the tag/ missing commits to this remote?

**Comment by amukherjee28** [comment]
@vegraux thanks for pointing it out. Will tag the missing release in the ibmdb site as well.

**Comment by vegraux** [comment]
We can still not see the tag @amukherjee28.

**Comment by bimalkjha** [comment]
@vegraux You can see the tag now. Thanks.
