### ISSUE TITLE
Python3.8 DB2 - Symbol not found

### ISSUE THREAD

**Issue by BigNerd** [ibmdb/python-ibmdb#726]
After installing ibm-db-3.1.1 into a python 3.8 environment on macOS 11.6 using pip (ibm_db-3.1.1-cp38-cp38-macosx_11_0_x86_64.whl)

I get this error message when trying to connect to DB2:

ImportError: dlopen(.../ibm_db.cpython-38-darwin.so, 2): Symbol not found: _SQLAllocHandle

**Comment by amukherjee28** [comment]
can you check this issue once
https://github.com/ibmdb/python-ibmdb/issues/696

**Comment by BigNerd** [comment]
> 

In that issue #696 it is said "We have updated the fixed clidriver with proper linking of the library.
Please clean up the previous installation and install again."

I did install freshly, so I currently do not see how this could help me, unfortunately.

**Comment by bimalkjha** [comment]
@BigNerd Please share the complete output of below commands:
```
echo $PATH
echo $DYLD_LIBRARY_PATH
echo $IBM_DB_HOME
cd ....python3.8/site-packages/clidriver/bin
./db2level
ls -l /usr/lib/libstdc++*
otool -L ibm_db.cpython-38-darwin.so
python -c 'import ibm_db'
```
Thanks.

**Comment by BigNerd** [comment]
Thanks, I have executed the above commands (in a Python 3.10 environment which gives the same error as with Python 3.9 and Python 3.8 as mentioned above).

`
echo $PATH
/Users/my_user/my_project/venv/bin:/usr/local/opt/openjdk@8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

echo $DYLD_LIBRARY_PATH

(empty)

 echo $IBM_DB_HOME
 
 (empty)
 
 cd /Users/my_user/my_project/venv/lib/python3.10/site-packages/clidriver/bin
  ./db2level 
zsh: exec format error: ./db2level


 ls -l /usr/lib/libstdc++*
lrwxr-xr-x  1 root  wheel  21 Jan  1  2020 /usr/lib/libstdc++.6.dylib -> libstdc++.6.0.9.dylib
lrwxr-xr-x  1 root  wheel  17 Jan  1  2020 /usr/lib/libstdc++.dylib -> libstdc++.6.dylib

otool -L ibm_db.cpython-38-darwin.so
error: /Library/Developer/CommandLineTools/usr/bin/otool-classic: can't open file: ibm_db.cpython-38-darwin.so (No such file or directory)

python -c 'import ibm_db'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/my_user/my_project/venv/lib/python3.10/site-packages/ibm_db.cpython-310-darwin.so, 2): Symbol not found: _SQLAllocHandle
  Referenced from: /Users/my_user/my_project/venv/lib/python3.10/site-packages/ibm_db.cpython-310-darwin.so
  Expected in: flat namespace
 in /Users/my_user/my_project/venv/lib/python3.10/site-packages/ibm_db.cpython-310-darwin.so
`

**Comment by bimalkjha** [comment]
@BigNerd Below error should be the root cause:
```
cd /Users/my_user/my_project/venv/lib/python3.10/site-packages/clidriver/bin
./db2level
zsh: exec format error: ./db2level
```
Why ./db2level is not working for you? It should work if right clidriver is downloaded and installed. Please share output of below commands:
```
cd /Users/my_user/my_project/venv/lib/python3.10/site-packages/clidriver/bin
ls
db2level
file db2level
uname
uname -m
```
Thanks.

**Comment by BigNerd** [comment]
Hi @bimalkjha here is the output of the commands you suggest, hth
```
(venv) my_prompt % ls
db2cli          db2diag         db2drdat        db2dsdcfgfill   db2ldcfg        db2lddrg        db2level        db2support      db2trc
(venv) my_prompt % ./db2level
zsh: exec format error: ./db2level
(venv) my_prompt % file db2level
db2level: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=ff9dbabe556d7e1757f6cc94cb747f9ca795f23f, not stripped
(venv) my_prompt % uname
Darwin
(venv) my_prompt % uname -m
x86_64
```
