### ISSUE TITLE
kernel process dies because of deprecated support for extra string quotes in traitlets 5

### ISSUE THREAD

**Issue by parodayco** [ibmdb/python-ibmdb#728]
My python kernel dies every time I run `ibm_db.connect()` or `ibm_db_dbi.connect()`. Here is the console output:
```
Error 08:48:19: Disposing session as kernel process died ExitCode: undefined, Reason: /usr/local/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/usr/local/lib/python3.9/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'b13bc39e-6f5f-4a5e-b875-93a86653eb31' instead of 'b"b13bc39e-6f5f-4a5e-b875-93a86653eb31"'.
  warn(

Info 08:48:19: Dispose Kernel process
Error 08:48:19: Raw kernel process exited code: undefined
```
Downgrading traitlets creates issues because 5.0+ is required by ipykernel and ipython in my environment.

MacOS 12.2.1
Python 3.9.10

Please let me know if there is any modification I can test so ibm_db works with trailets>5.

**Comment by amukherjee28** [comment]
@parodayco 
I could not recreate the issue. Could you provide the sample code that causes the issue in your system.

I tried running sample programs from the MAC machine with python 3.10.1 with following installed
```
 pip3 list
Package          Version
---------------- -------
html-testRunner  1.2.1
ibm-db           3.1.1
ipython-genutils 0.2.0
Jinja2           3.0.3
MarkupSafe       2.0.1
pip              21.2.4
setuptools       58.1.0
traitlets        5.0.5
```

Everything seemed to work fine for me.

**Comment by parodayco** [comment]
@amukherjee28 While creating an MRE for you, I discovered the kernel failure only occurs when I'm using VS Code in either 'interactive' mode or a Jupyter notebook. My code runs fine in the terminal and in Jupyterlab. In all cases, I'm using the same python environment and packages. Weird

**Comment by parodayco** [comment]
https://github.com/microsoft/vscode-python/issues/18678
