### ISSUE TITLE
No support for TLS with - both client and server certificates (authentication=certificate)

### ISSUE THREAD

**Issue by op123singh** [ibmdb/python-ibmdb#729]
Hi,
I can connect python-ibmdb on Windows  with Db2 zOS server with TLS/SSL with server certificate.
But when I try to connect to  both client and server certificates (authentication=certificate) the connection fails.

Exception: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "9.30.179.1".  Communication fun SQLCODE=-30081 the error: "connect".  Protocol specific error code(s): "10061", "*", "*".  SQLSTATE=08001

FYI :
conn_str="authentication=certificate;DATABASE=DSNR3;HOSTNAME=9.30.179.1;PORT=51690;PROTOCOL=TCPIP;SECURITY=SSL;SSLClientKeyStoreDB=C:\work\samples\SSL\odbc\server_client_both\zosclientdb.kdb;SSLClientKeyStash=C:\work\samples\SSL\odbc\server_client_both\zosclientdb.sth;SSLClientLabel=clientcert;"

**Comment by amukherjee28** [comment]
@op123singh 
For the SSL handshake with authentication=Certificate can you tell me the db2 driver version you are using?
Are you using the default clidriver that comes with the python ibm_db installation or are you using any particular version of your own and configured via IBM_DB_HOME env variable.
We have a issue with certificate authentication currently in open state and hence that may be the problem.
Please let me know the driver version and then I can check.

**Comment by op123singh** [comment]
DB21085I  This instance or install (instance name, where applicable: "DB2")
uses "64" bits and DB2 code release "SQL11055" with level identifier
"0606010F".
Informational tokens are "DB2 v11.5.5000.1587", "s2011011400",
"DYN2011011400WIN64", and Fix Pack "0".
Product is installed at "C:\IBM\SQLLIB" with DB2 Copy Name "DB2COPY1".

And just to let u know that ODBC applications can connect with authentication=Certificate  for the same install

**Comment by op123singh** [comment]
Name: ibm-db
Version: 3.1.1
Summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS
Home-page: http://pypi.python.org/pypi/ibm_db/
Author: IBM Application Development Team
Author-email: opendev@us.ibm.com
License: Apache License 2.0
Location: c:\nonibm\python3.9\lib\site-packages\ibm_db-3.1.1-py3.9.egg
Requires:
Required-by: ibm-db-django, ibm-db-sa

Python 3.9.4

**Comment by amukherjee28** [comment]
I have tested the authentication=certificate with ibm_db version 3.1.1 with clidriver v1155 same as yours and it works fine for me. No issues in the connection and execution.

Please make sure your connection string details provided above are proper and working.

ODBC application connecting with authentication=certificate is not enough as ODBC driver works within the ZOS machine and the connection attempt will be different when remote connection is made to the ZOS server having the server certificate.

Please make sure that the remote connection to the same server via clidriver works and all configurations are proper.

Example Output

```
 python3 SSL_certificate1.py
IBM_DB_VERSION : 3.1.1
=> Creating Connection
Connection String : database=DB;hostname=HOSTNAME;port=SSL_PORT;protocol=TCPIP;SECURITY=SSL;AUTHENTICATION=CERTIFICATE;SSLCLientKeyStoredb=ZOS_SSL/file.kdb;sslclientkeystash=ZOS_SSL/file.sth;SSLCLIENTLABEL=clientSSL
=> creating Tables
=> RUNNING : create TABLE test1 (c1 int)
<ibm_db.IBM_DBStatement object at 0x7fb668d0a100>
=> Dropping Table
=> RUNNING : Drop  TABLE test1
<ibm_db.IBM_DBStatement object at 0x7fb668d0a170>
```

```
Exception: [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "9.30.179.1". Communication fun SQLCODE=-30081 the error: "connect". Protocol specific error code(s): "10061", "", "". SQLSTATE=08001
```
The above error shows communication error when remote connection is attempted.

I will not be able to help you as to what config on the ZOS side needs to be done to enable authentication=certificate connections.

You may also try a remote connection to the same connection string via the clidriver and check if the same works.
Let me know if you need help to test connection using CLIDRIVER.

Thanks

**Comment by bimalkjha** [comment]
@op123singh You are getting SQL30081N error with Protocol specific error code: 10061. As per details of [SQL30081N doc](https://www.ibm.com/docs/en/db2/11.5?topic=messages-sql28000-sql33999#sql30081n), 10061 means - ECONNREFUSED i.e. connection request is rejected by server.
One of the reason could be the server is not setup properly for `Certificate` authentication or label is incorrect. We need to generate client certificate and add to the server keydb too for certificate authentication.
To verify the connection string and server setup, you can try db2cli command as below:
```
db2cli execsql -connstring "Authentication=Certificate;DATABASE=DSNR3;HOSTNAME=9.30.179.1;PORT=51690;PROTOCOL=TCPIP;SECURITY=SSL;SSLClientKeyStoreDB=C:\work\samples\SSL\odbc\server_client_both\zosclientdb.kdb;SSLClientKeyStash=C:\work\samples\SSL\odbc\server_client_both\zosclientdb.sth;SSLClientLabel=clientcert"
```
Also,  you can put these info in db2dsdriver.cfg file and use the `db2cli validate -connect` command to verify connection. If db2cli is able to connect to server, ibm_db will also work. Thanks.

**Comment by amukherjee28** [comment]
@op123singh can we have an update on this. Does the explanation provided resolves the issue.

Thanks

**Comment by amukherjee28** [comment]
Do we have an understanding on this after the explanation was provided?

**Comment by op123singh** [comment]
yes, I tried on distributed (windows ) it works now. We can close the issue.
