### ISSUE TITLE
import error of ibm_db on M1

### ISSUE THREAD

**Issue by niju3063** [ibmdb/python-ibmdb#730]
[import ibm_db

ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ibm_db.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_SQLAllocHandle']()

does any solution exists for above query

**Comment by bimalkjha** [comment]
@niju3063 Its a duplicate of closed issue #726 . Please check that for solution. Thanks.
