### ISSUE TITLE
In Wiki file APIs.md at line 857

### ISSUE THREAD

**Issue by frcode** [ibmdb/python-ibmdb#731]
conn1 =
ibm_db.connect('DATABASE=database;HOSTNAME=hostname;PORT=port;PROTOCOL=TCPIP;UID=username;PWD=password')

should be

conn1 = dbi.connect('DATABASE=database;HOSTNAME=hostname;PORT=port;PROTOCOL=TCPIP;UID=username;PWD=password')

**Comment by amukherjee28** [comment]
Issue fix via commit https://github.com/ibmdb/python-ibmdb/wiki/APIs/dd27c3b5e4d7fb8436ebe6860f94844ad54b96e3

Thanks.
