### ISSUE TITLE
import ibm_db

### ISSUE THREAD

**Issue by niju3063** [ibmdb/python-ibmdb#732]
[dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ibm_db.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_SQLAllocHandle']()

any solution to this?

**Comment by niju3063** [comment]
!pip install --force-reinstall ibm_db==3.1.0 ibm_db_sa==0.3.3
!pip uninstall sqlalchemy==1.4 -y && pip install sqlalchemy==1.3.24
 !pip install ipython-sql

even after installing these unable to import ibm_db.

kindly suggest'

**Comment by niju3063** [comment]
python setup.py
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by bimalkjha** [comment]
@niju3063 It is an M1 Chip system or x64 system? Either case, you need to install x64 version of python on M1 chip system too and then install ibm_db. You can install this python and check: https://www.python.org/ftp/python/3.9.10/python-3.9.10-macosx10.9.pkg 
Similar issue was reported by 3-4 closed issues. Please check closed issue for details. Thanks.

**Comment by niju3063** [comment]
thanks. reinstalled python3.10.3 and performed above steps. it worked . thanks

**Comment by bimalkjha** [comment]
Added this info here: https://github.com/ibmdb/python-ibmdb#pre-requisites
