### ISSUE TITLE
python ds driver install is failing on RHEL 7.9 on Intel x86_64

### ISSUE THREAD

**Issue by Anshu-Garg** [ibmdb/python-ibmdb#735]
**- Operating System Name:** RHEL 7.9
**- db2level output from clidriver if in use:** 
 
__From /home/db2inst1/dsdriver/bin/db2level__
DB21085I  This instance or install (instance name, where applicable: "*") uses 
"64" bits and DB2 code release "SQL11056" with level identifier "0607010F".
Informational tokens are "DB2 v11.5.6.0", "s2106111000", "DYN2106111000AMD64", 
and Fix Pack "0".
Product is installed at "/opt/ibm/db2/V11.5".

**- Target Db2 Server Version:** 

DB21085I  This instance or install (instance name, where applicable: 
"db2inst1") uses "64" bits and DB2 code release "SQL11056" with level 
identifier "0607010F".
Informational tokens are "DB2 v11.5.6.0", "special_13320", 
"DYN2112150824AMD64_13320", and Fix Pack "0".
Product is installed at "/opt/ibm/db2/V11.5".
 
**- Python Version: 2.7**

Python 2.7.5
 
- ibm_db version: 
 
Does not exist. Our understanding from steps in knowledge center and in Git is ... it becomes available once python driver is installed successfully

 
**- For non-Windows, output of below commands:**
  uname
  uname -m

[db2inst1@cps-rack-79-vm-147 bin]$ uname
Linux
[db2inst1@cps-rack-79-vm-147 bin]$ uname -a
Linux cps-rack-79-vm-147 3.10.0-1160.53.1.el7.x86_64 #1 SMP Thu Dec 16 10:19:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**- Value of below environment variables if set:**
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

export IBM_DB_HOME=/home/db2inst1/dsdriver
LD_LIBRARY_PATH=/home/db2inst1/sqllib/lib64:/home/db2inst1/sqllib/lib64/gskit:/home/db2inst1/sqllib/lib32
PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/db2inst1/.local/bin:/home/db2inst1/bin:/home/db2inst1/sqllib/bin:/home/db2inst1/sqllib/adm:/home/db2inst1/sqllib/misc:/home/db2inst1/sqllib/pd:/home/db2inst1/sqllib/gskit/bin:/home/db2inst1/sqllib/db2tss/bin

- Test script to reproduce the problem. **NA**
 
**- For installation related issue, complete output of `pip install ibm_db` command.**
Command output is in attached text file
[pythondriver.txt](https://github.com/ibmdb/python-ibmdb/files/8364550/pythondriver.txt)

**Steps to Reproduce:**

1. Deployed DB1 11.5.6 std edition
2. Followed steps 1-4 from https://www.ibm.com/docs/en/db2/11.5?topic=dsd-installing-data-server-driver-package-software-linux-unix-operating-systems
3. follow step 6.d from https://www.ibm.com/docs/en/db2/11.5?topic=dsd-installing-data-server-driver-package-software-linux-unix-operating-systems

**Comment by imavo** [comment]
Please study the section "Some common issues" on the readme page, because your symptom is a common symptom.
https://github.com/ibmdb/python-ibmdb


before installing ibm_db, add python-dev package to your RHEL, because it is that development
   package that supplies file "Python.h" and the gcc (build) step is failing because that file Python.h is missing.
   "...Python.h: No such file or directory"

upgrade your pip version before installing ibm_db with a command similar to :
   python -m pip install --upgrade pip
   
At some point the support for python 2.7 will be dropped.

**Comment by Anshu-Garg** [comment]
@imavo we do not have option to use python3 
Our OS images only use and provide python2.7

However one question .. if we build above drivers on a VM where we have python3 and let's say we are able to build. Can we zip the built drivers/ouput and use on python 2.7.5 environment ?

Bottom line is our VM will only have python2.7 or now.

**Comment by amukherjee28** [comment]
@Anshu-Garg As explained in the above comment you need to install the python-dev packages for python2 as well in order to have the missing dependencies.
Issue from the log
```
creating build/temp.linux-x86_64-2.7
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/db2inst1/dsdriver/include -I/usr/include/python2.7 -c ibm_db.c -o build/temp.linux-x86_64-2.7/ibm_db.o
  ibm_db.c:27:20: fatal error: Python.h: No such file or directory
   #include <Python.h>
                      ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
```

As you can see in the above error the python.h header is missing which can be installed via ```yum install python-dev```

Once the above is installed successfully please try and install the ibm_db python package again.

**Comment by Anshu-Garg** [comment]
Hi @amukherjee28 I understand you mean python-devel

When Installed that I get a success message but I still do not see expected files as per documentation https://www.ibm.com/docs/en/db2/11.5?topic=dsd-installing-data-server-driver-package-software-linux-unix-operating-systems

I was expecting .egg files as mentioned here

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/14204924/160462399-25da2b4a-9a3e-4600-a43a-d564a4b7c9e7.png">

```
[db2inst1@cps-rack-79-vm-147 dsdriver]$ pip install ibm_db
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting ibm_db
  Using cached ibm_db-3.1.1.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: ibm-db
  Building wheel for ibm-db (PEP 517) ... done
  Created wheel for ibm-db: filename=ibm_db-3.1.1-cp27-cp27mu-linux_x86_64.whl size=423138 sha256=4f3a0c4493fe718d6bf9412a3d4009121aa59981b90bf963a32bb05b21a93b72
  Stored in directory: /myinst/.cache/pip/wheels/6c/2f/f7/3b6e2a3008f20f5daf4b0c344de6dcca0af70e2e04265d3918
Successfully built ibm-db
Installing collected packages: ibm-db
Successfully installed ibm-db-3.1.1
```

Where are the packages installed according to this output ? We want to build it once and use on different Db2 VMs
Can I zip that "output" and use on any other DB2 11.5.6 install without having to build again ?
What should I do to set ds driver location in different db2 install VMs once db2 is installed and we extract drive there ?

**Comment by amukherjee28** [comment]
@Anshu-Garg 

All the pip installed related file will be present in the site-packages folder of the pip installed location.
In order to find the location of the site-packages folder location you can run the following command and check

```python -m site```

Example output
```
 python -m site
sys.path = [
    '/usr/local/lib/python2.7/dist-packages',
    '/usr/lib/python2.7',
    '/usr/lib/python2.7/plat-x86_64-linux-gnu',
    '/usr/lib/python2.7/lib-tk',
    '/usr/lib/python2.7/lib-old',
    '/usr/lib/python2.7/lib-dynload',
    '/usr/lib/python2.7/dist-packages',
]
USER_BASE: '/home/amukherjee/.local' (exists)
USER_SITE: '/home/amukherjee/.local/lib/python2.7/site-packages' (doesn't exist)
ENABLE_USER_SITE: True
```

This is the folder where all pip install related files and folders will be present. Please check this location for you ibm_db related files and folders.

Also one more point to be noted here is, since you are installing using the python package manager pip you might not find the .egg files as all the dependencies during pip installation are taken care by the package manager and end result are the files required to run.
However if you install using the setup.py file from the code will end up having the .egg files inside which all of the dependencies shall be present.
Let me know if this explains the query.

Thanks

**Comment by Anshu-Garg** [comment]
Hi Arnab,

Can we get on a call/WebEx. It will be far quicker and I can explain use case and take guidance from you what is best way for us to build driver for use case. Please let me know your availability today.

-Thanks & Regards,
Anshu Garg
Product Transformation Centre, India

Phone: 8800096760
E-mail: ***@***.******@***.***>

On 29-Mar-2022, at 10:43 AM, arnab mukherjee ***@***.******@***.***>> wrote:

This Message Is From an External Sender
This message came from outside your organization.


@Anshu-Garg<https://github.com/Anshu-Garg>

All the pip installed related file will be present in the site-packages folder of the pip installed location.
In order to find the location of the site-packages folder location you can run the following command and check

python -m site

Example output

 python -m site
sys.path = [
    '/usr/local/lib/python2.7/dist-packages',
    '/usr/lib/python2.7',
    '/usr/lib/python2.7/plat-x86_64-linux-gnu',
    '/usr/lib/python2.7/lib-tk',
    '/usr/lib/python2.7/lib-old',
    '/usr/lib/python2.7/lib-dynload',
    '/usr/lib/python2.7/dist-packages',
]
USER_BASE: '/home/amukherjee/.local' (exists)
USER_SITE: '/home/amukherjee/.local/lib/python2.7/site-packages' (doesn't exist)
ENABLE_USER_SITE: True


This is the folder where all pip install related files and folders will be present. Please check this location for you ibm_db related files and folders.

Also one more point to be noted here is, since you are installing using the python package manager pip you might not find the .egg files as all the dependencies during pip installation are taken care by the package manager and end result are the files required to run.
However if you install using the setup.py file from the code will end up having the .egg files inside which all of the dependencies shall be present.
Let me know if this explains the query.

Thanks

**Comment by amukherjee28** [comment]
Hi,

Yes that sounds good to be me.

You can schedule a webex call between 12 Noon to 2PM IST today itself. We can sort out the issues in the call.

Thanks.

----------------------------------------------------------------------
Arnab Mukherjee
QA Engineer
Rocket Software India Development, Bangalore
+91-7760288775
***@***.***

________________________________

**Comment by Anshu-Garg** [comment]
Great!

Can you please join  https://ibm.webex.com/meet/anshugarg at 12:40 PM today.

-Thanks & Regards,
Anshu Garg
Product Transformation Centre, India

Phone: 8800096760
E-mail: ***@***.******@***.***>

On 29-Mar-2022, at 11:16 AM, arnab mukherjee ***@***.******@***.***>> wrote:

This Message Is From an External Sender
This message came from outside your organization.

Hi,

Yes that sounds good to be me.

You can schedule a webex call between 12 Noon to 2PM IST today itself. We can sort out the issues in the call.

Thanks.

----------------------------------------------------------------------
Arnab Mukherjee
QA Engineer
Rocket Software India Development, Bangalore
+91-7760288775
***@***.***

________________________________

**Comment by amukherjee28** [comment]
Hi,

This works for me. Will join the meeting link at 12 40. I shall send you a meeting invite with the link as well.

Thanks.

----------------------------------------------------------------------
Arnab Mukherjee
QA Engineer
Rocket Software India Development, Bangalore
+91-7760288775
***@***.***

________________________________

**Comment by amukherjee28** [comment]
The issue was resolved and resolution was provided. Hence closing the issue.
