### ISSUE TITLE
Error when connecting on with SSL on MAC (interrupted by signal 6: SIGABRT)

### ISSUE THREAD

**Issue by Matheus-Rangel** [ibmdb/python-ibmdb#748]
I have two differents databases that i am able to access, the one that does not require SSL i can run the script without any issues, but the other with SSL the error is thrown. 

- Operating System Name: MacOS Intel
- db2level output from clidriver if in use:
- Target Db2 Server Version: DB2 ON CLOUD
- Python Version:3.8
- ibm_db version:3.1.1
- For non-Windows, output of below commands:
  uname
 Darwin
  uname -m
x86_64
- Value of below environment variables if set:
  IBM_DB_HOME:
PATH:/Users/matheusrangel/opt/anaconda3/bin:/Users/matheusrangel/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/matheusrangel/Library/Python/3.8/bin:/Users/matheusrangel/.local/bin:/Users/matheusrangel/openshift-client-mac-4.10.6
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

The script that i used to test.
```python

import os
import ibm_db

def get_connection():
    database = os.environ.get('DATABASE')
    hostname = os.environ.get('HOSTNAME')
    port = os.environ.get('DBPORT')
    protocol = os.environ.get('PROTOCOL')
    uid = os.environ.get('UID_') if os.environ.get(
        'UID_') else os.environ.get('UID')
    pwd = os.environ.get('PASS')
    connect_string = "DATABASE={};HOSTNAME={};PORT={};PROTOCOL={};UID={};PWD={};SECURITY=ssl"
    return connect_string.format(database, hostname, port, protocol, uid, pwd)


if __name__ == '__main__':
    print('test connection')
    conn = ibm_db.connect(get_connection(), '', '')
```

**Comment by Matheus-Rangel** [comment]
In fact there is no need to set any environment variable, just having the SECURITY=ssl option is enough to throw the error.

**Comment by Matheus-Rangel** [comment]
I checked /usr/lib directory and i have the libstdc++.6.dylib there as well that might be causing the error. The problem is renaming the file on that location requires a lot of workarounds on macOS Monterey, any other solution?

**Comment by amukherjee28** [comment]
@Matheus-Rangel 

With respect to the error, I think the libstdc++ is not causing the issue.
With respect to libstdc++ the error that we have seen is either
```
ImportError: dlopen(/Library/Python/3.8/site-packages/ibm_db.cpython-38-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: /Library/Python/3.8/site-packages/clidriver/lib/libdb2.dylib
  Expected in: /usr/lib/libstdc++.6.dylib
```

or the other error would be
```
python(2472,0x201366600) malloc: *** error for object 0x7ffb559e3800: pointer being freed was not allocated python(2472,0x201366600) malloc: *** set a breakpoint in malloc_error_break to debug
```

However looking into older issue #697 looks like this is the root cause of the issue.

The new version of MAC OS Monterey has removed the library libstdc++ dependency and hence that is causing the issue in some cases.
We are working on this to check how can it be handled in some cases. I will update on this at the earliest.

**Comment by amukherjee28** [comment]
@Matheus-Rangel Also from the update while looking into the environment variable section I do see an issue.

You do not have IBM_DB_HOME path set that is OK. However can you set the value of DYLD_LIBRARY_PATH to the clidriver/lib path from the site-packages directory where the clidriver is downloaded.

Usually I for SSL connection the path to the clidriver/lib is needed to be set.

can you set ```export DYLD_LIBRARY_PATH=<path to clidriver>/lib:$DYLD_LIBRARY_PATH```

**Comment by Matheus-Rangel** [comment]
Yes the actually the error is 
`python(2472,0x201366600) malloc: *** error for object 0x7ffb559e3800: pointer being freed was not allocated `
I tried with the DYLD_LIBRARY_PATH as well before opening the issue and the same error is thrown.

**Comment by bimalkjha** [comment]
@Matheus-Rangel Please check the file `/usr/local/lib/gcc/8/libgcc_s.1.dylib` exist in your system or not. libdb2.dylib need this library. If it is not present, then install it using below commands and then try:
```
$ brew tap homebrew/versions
$ brew install homebrew/versions/gcc8
$ ls /usr/local/lib/gcc/8/libgcc_s.1.dylib
```
Thanks.

**Comment by Matheus-Rangel** [comment]
Now it's working, thanks guys.
