### ISSUE TITLE
Unable to import ibm_db

### ISSUE THREAD

**Issue by chesterpoon8** [ibmdb/python-ibmdb#749]
- Operating System Name: Mac OS Monterey 12.0.1
- Python Version: 3.9.12
- ibm_db version: 3.1.1

run into this error when attempting to import ibm_db

>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ibm_db.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_SQLAllocHandle'

I've seen similar errors for other issues listed here, like [#688](https://github.com/ibmdb/python-ibmdb/issues/688), but the solutions did not work for me and hours of googling have not been fruitful. I do not have homebrew python

Any help appreciated. thanks

**Comment by dwt** [comment]
Same issue for me. :-(

```shell
$ uname -a
Darwin Seneca.fritz.box 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
```

**Comment by rahulkalluri** [comment]
Same here

```
$ uname -a
Darwin Rahuls-MacBook-Air.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
```

**Comment by bimalkjha** [comment]
@chesterpoon8 @dwt @rahulkalluri ibm_db do not work with arm64 version of python on MacOS. Install x64 version of python on M1 chip system and then install ibm_db. You can install this python: https://www.python.org/ftp/python/3.9.10/python-3.9.10-macosx10.9.pkg and verify. You can see this comment [here](https://github.com/ibmdb/python-ibmdb/issues/712#issuecomment-1064821174)Thanks.

**Comment by chesterpoon8** [comment]
Thank you @bimalkjha !  This fixed it for me.

**Comment by rahulkalluri** [comment]
Actually this didn't work for me. 

I installed the x64 version of Homebrew and then Python through Homebrew. This was on a fresh Monterey install on a Macbook Air M1. 

I'm going to give this a whirl again this weekend just to be sure but I didn't have success 2 weeks ago.

**Comment by jonathanherdt** [comment]
There is also an M1-specific part of the Readme that might help, see here: https://github.com/ibmdb/python-ibmdb#pre-requisites

**Comment by dwt** [comment]
Any reason you cannot make ibmdb support Apple Silicon / ARM chips natively? Having to skip to rosetta for an installation might work, but is quite a chore on all of your users. :-/

**Comment by dwt** [comment]
@bimalkjha it seems that arm64 is not supported by the c library that IBM is releasing? If that is the case, It would really help to spell this out more plainly at https://github.com/ibmdb/python-ibmdb#pre-requisites

**Comment by dwt** [comment]
Ideally with a link to their bug that tracks when they compile it for arm too.
