### ISSUE TITLE
ibm_db.connect() stuck

### ISSUE THREAD

**Issue by dsos** [ibmdb/python-ibmdb#752]
anaconda3.2022.05(python 3.9.12)
pip install ibm_db(version 3.11)

code like below:
def get_ssh_tunnel():
    server = SSHTunnelForwarder(
            ssh_address_or_host=('SSH SERVER', 22),
            ssh_username='USER',
            ssh_password='PASS',
            remote_bind_address=('DB2 SERVER', 50000),
            local_bind_address=('127.0.0.1', 50000)
            )
    server.start() 
    return server

def get_db_conn(sshserver):
    dbip = sshserver.local_bind_host
    dbport = sshserver.local_bind_port
    conn_str = f'DATABASE=XX;HOSTNAME={dbip};PORT={dbport};PROTOCOL=TCPIP;UID=XX;PWD=XX;'
    ibm_db_conn = ibm_db.connect(conn_str,'','')
    return ibm_db_dbi.Connection(ibm_db_conn)
if __name__ == "__main__":
    sshserver = get_ssh_tunnel()
    conn = get_db_conn(sshserver)
    select="select * from XXX"
    cur = conn.cursor()
    print(cur.description)
    cur.execute(select)
    row=cur.fetchall()
    print(row)
    conn.close()

(base) D:\project\python>python -v simpledb.py
import 'pkg_resources' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83AC31CA0>
# d:\anaconda3\lib\__pycache__\imp.cpython-39.pyc matches d:\anaconda3\lib\imp.py
# code object from 'd:\\anaconda3\\lib\\__pycache__\\imp.cpython-39.pyc'
import 'imp' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83A9A1EB0>
# extension module 'ibm_db' loaded from 'd:\\anaconda3\\lib\\site-packages\\ibm_db_dlls\\ibm_db.dll'
# extension module 'ibm_db' executed from 'd:\\anaconda3\\lib\\site-packages\\ibm_db_dlls\\ibm_db.dll'
import 'ibm_db' # <_frozen_importlib_external.ExtensionFileLoader object at 0x000001F83AA5BFA0>
# destroy ibm_db
import 'ibm_db' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83AC31550>
# d:\anaconda3\lib\site-packages\__pycache__\ibm_db_dbi.cpython-39.pyc matches d:\anaconda3\lib\site-packages\ibm_db_dbi.py
# code object from 'd:\\anaconda3\\lib\\site-packages\\__pycache__\\ibm_db_dbi.cpython-39.pyc'
# d:\anaconda3\lib\__pycache__\decimal.cpython-39.pyc matches d:\anaconda3\lib\decimal.py
...
# code object from 'd:\\anaconda3\\lib\\site-packages\\paramiko\\__pycache__\\client.cpython-39.pyc'
# d:\anaconda3\lib\site-packages\paramiko\__pycache__\agent.cpython-39.pyc matches d:\anaconda3\lib\site-packages\paramiko\agent.py
# code object from 'd:\\anaconda3\\lib\\site-packages\\paramiko\\__pycache__\\agent.cpython-39.pyc'
import 'paramiko.agent' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D59F700>
# d:\anaconda3\lib\site-packages\paramiko\__pycache__\hostkeys.cpython-39.pyc matches d:\anaconda3\lib\site-packages\paramiko\hostkeys.py
# code object from 'd:\\anaconda3\\lib\\site-packages\\paramiko\\__pycache__\\hostkeys.cpython-39.pyc'
import 'paramiko.hostkeys' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D59FD60>
import 'paramiko.client' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83CFDB5B0>
# d:\anaconda3\lib\site-packages\paramiko\__pycache__\sftp_server.cpython-39.pyc matches d:\anaconda3\lib\site-packages\paramiko\sftp_server.py
# code object from 'd:\\anaconda3\\lib\\site-packages\\paramiko\\__pycache__\\sftp_server.cpython-39.pyc'
# d:\anaconda3\lib\site-packages\paramiko\__pycache__\sftp_si.cpython-39.pyc matches d:\anaconda3\lib\site-packages\paramiko\sftp_si.py
# code object from 'd:\\anaconda3\\lib\\site-packages\\paramiko\\__pycache__\\sftp_si.cpython-39.pyc'
import 'paramiko.sftp_si' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D5B3580>
# d:\anaconda3\lib\site-packages\paramiko\__pycache__\sftp_handle.cpython-39.pyc matches d:\anaconda3\lib\site-packages\paramiko\sftp_handle.py
# code object from 'd:\\anaconda3\\lib\\site-packages\\paramiko\\__pycache__\\sftp_handle.cpython-39.pyc'
import 'paramiko.sftp_handle' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D5B3C70>
import 'paramiko.sftp_server' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D59F550>
# d:\anaconda3\lib\site-packages\paramiko\__pycache__\proxy.cpython-39.pyc matches d:\anaconda3\lib\site-packages\paramiko\proxy.py
# code object from 'd:\\anaconda3\\lib\\site-packages\\paramiko\\__pycache__\\proxy.cpython-39.pyc'
import 'paramiko.proxy' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D5B3E80>
import 'paramiko' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D013220>
# d:\anaconda3\lib\__pycache__\socketserver.cpython-39.pyc matches d:\anaconda3\lib\socketserver.py
# code object from 'd:\\anaconda3\\lib\\__pycache__\\socketserver.cpython-39.pyc'
import 'socketserver' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D0139A0>
import 'sshtunnel' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83CFCD820>
# d:\anaconda3\lib\site-packages\paramiko\__pycache__\win_pageant.cpython-39.pyc matches d:\anaconda3\lib\site-packages\paramiko\win_pageant.py
# code object from 'd:\\anaconda3\\lib\\site-packages\\paramiko\\__pycache__\\win_pageant.cpython-39.pyc'
# d:\anaconda3\lib\ctypes\__pycache__\__init__.cpython-39.pyc matches d:\anaconda3\lib\ctypes\__init__.py
# code object from 'd:\\anaconda3\\lib\\ctypes\\__pycache__\\__init__.cpython-39.pyc'
# extension module '_ctypes' loaded from 'd:\\anaconda3\\DLLs\\_ctypes.pyd'
# extension module '_ctypes' executed from 'd:\\anaconda3\\DLLs\\_ctypes.pyd'
import '_ctypes' # <_frozen_importlib_external.ExtensionFileLoader object at 0x000001F83D5E3490>
# d:\anaconda3\lib\ctypes\__pycache__\_endian.cpython-39.pyc matches d:\anaconda3\lib\ctypes\_endian.py
# code object from 'd:\\anaconda3\\lib\\ctypes\\__pycache__\\_endian.cpython-39.pyc'
import 'ctypes._endian' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D5E39A0>
import 'ctypes' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D5CF7F0>
# d:\anaconda3\lib\ctypes\__pycache__\wintypes.cpython-39.pyc matches d:\anaconda3\lib\ctypes\wintypes.py
# code object from 'd:\\anaconda3\\lib\\ctypes\\__pycache__\\wintypes.cpython-39.pyc'
import 'ctypes.wintypes' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D5CF880>
# d:\anaconda3\lib\site-packages\paramiko\__pycache__\_winapi.cpython-39.pyc matches d:\anaconda3\lib\site-packages\paramiko\_winapi.py
# code object from 'd:\\anaconda3\\lib\\site-packages\\paramiko\\__pycache__\\_winapi.cpython-39.pyc'
import 'paramiko._winapi' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D5CFB80>
import 'paramiko.win_pageant' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D5CF1C0>
# d:\anaconda3\lib\encodings\__pycache__\idna.cpython-39.pyc matches d:\anaconda3\lib\encodings\idna.py
# code object from 'd:\\anaconda3\\lib\\encodings\\__pycache__\\idna.cpython-39.pyc'
# d:\anaconda3\lib\__pycache__\stringprep.cpython-39.pyc matches d:\anaconda3\lib\stringprep.py
# code object from 'd:\\anaconda3\\lib\\__pycache__\\stringprep.cpython-39.pyc'
# extension module 'unicodedata' loaded from 'd:\\anaconda3\\DLLs\\unicodedata.pyd'
# extension module 'unicodedata' executed from 'd:\\anaconda3\\DLLs\\unicodedata.pyd'
import 'unicodedata' # <_frozen_importlib_external.ExtensionFileLoader object at 0x000001F83D628C40>
import 'stringprep' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D628400>
import 'encodings.idna' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D5E3F70>
# d:\anaconda3\lib\encodings\__pycache__\utf_16_le.cpython-39.pyc matches d:\anaconda3\lib\encodings\utf_16_le.py
# code object from 'd:\\anaconda3\\lib\\encodings\\__pycache__\\utf_16_le.cpython-39.pyc'
import 'encodings.utf_16_le' # <_frozen_importlib_external.SourceFileLoader object at 0x000001F83D653100>

thanks for reply

**Comment by amukherjee28** [comment]
This looks to be on windows with anaconda python.

Can you please mention the method used to install the ibm_db driver.
Did you install using ```conda install ibm_db -c conda-forge``` command or any other way to install.

**Comment by dsos** [comment]
> 

I tried "pip install" off-line and on_line as homepage tells,
and then "pip uninstall",delete all files and env set,
conda install ibm_db -c conda-forge
same error

**Comment by amukherjee28** [comment]
Could you try directly with the SSH connection string connecting VIA ibm_db.

Also check if all parameters pertaining to the SSH connection are correct including the SSH port. Usually SSH connections are struck when there is a wrong connection parameter passed.

I am not sure if SSHTunnel is behaving in a different manner in this case.

The best way to check is to try the SSH connection directly and check if that works.

**Comment by dsos** [comment]
ok,I'll try it later.

thanks

**Comment by amukherjee28** [comment]
@dsos SSH connection string will have the SSH connection details with almost the same details like a normal connection string however you have to provide the SSH configured port and certificate if any.

**Comment by Earammak** [comment]
@dsos Can we have an update on this. I hope the above update provided resolves the issue.

**Comment by dsos** [comment]
@Earammak sorry like before even after updated

**Comment by bimalkjha** [comment]
@dsos It looks issue with SSHTunnelForwarder() which seems not communicating well with remote SSH server or SSH service on remote system is not forwarding the request to target Db2 server.
Using your test program, we collected db2 trace and found that there is no issue at client side as we can print the connection string and see what connection string is used. From db2trace, we saw that ibm_db has sent the request to host 127.0.0.1:50000 and it is waiting for response. Since, ibm_db is not getting any response back, so it is waiting at TCP/IP layer.
Probably,  you should enable some logging at SSH Server for SSH and see the communication. It looks some configuration issue with SSH Tunneling. ibm_db is just regarding the connection string, sent request on the passed host,port and waiting for response. Thanks.

**Comment by bimalkjha** [comment]
@dsos After google, I came to know that SSHTunnelForwarder() works as proxy for a web server. Db2 server is not a web server. For a webserver to communicate, you just need the hostname and port number, but for Db2 server, we need to pass database name too. For proxy servers, there is no mechanism to pass the database from ssh tunnel to db2 server. 
The essence is Db2 server is different from web server and you can not communicate to a Db2 server using ssh tunneling. Thanks.

**Comment by dsos** [comment]
> 

thanks very much
