### ISSUE TITLE
install release 3.1.2 failed

### ISSUE THREAD

**Issue by kxmatjob** [ibmdb/python-ibmdb#757]
- **For installation release 3.1.2 issue.**
  D:\Program Files (x86)\Python\Lib\site-packages\ibm_db-3.1.2>python setup.py install
  Detected 32-bit Python
  Db2 installation detected ...
  Traceback (most recent call last):
    File "setup.py", line 118, in <module>
      _getinstalledDb2Path()
    File "setup.py", line 91, in _getinstalledDb2Path
      path = temp[1].strip()
  IndexError: list index out of range

**I change the setup.py like this, install success.**
```
def _getinstalledDb2Path():
        .......
        #temp = output.split("Product is installed at")
        temp = output.split("安装在")
```

**the install code print:**
```
  Db2 installation detected ...
  DB21085I  此实例或安装（适用的实例名："DB2"）使用 "64" 位和级别标识为 "0606010E"
  
  的 DB2 代码发行版 "SQL10055"。
  
  参考标记为 "DB2 v10.5.500.107"、"s141128" 和 "IP23628"，修订包为 "5"。
  
  产品使用 DB2 副本名 "DB2COPY1" 安装在 "C:\PROGRA~1\IBM\SQLLIB" 中。
```

**----other infomation:**
- Operating System Name:Windows 10
- db2level output from clidriver if in use:DB2 v10.5.500.107
- Target Db2 Server Version:DB2 v10.5.500.107
- Python Version:3.6.8
- ibm_db version:3.1.2
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:C:\Program Files (x86)\ibm\gsk8\lib;C:\PROGRA\~1\IBM\SQLLIB\BIN;
  LIB:C:\PROGRA~1\IBM\SQLLIB\LIB

**Comment by amukherjee28** [comment]
This is an issue with the new feature support where we parse english language db2level output to find the install path and set IBM_DB_HOME accordingly.
However since the locale is different the approach fails.

So for now may I ask you to install the last version.

pip install ibm_db==3.1.1 till we fix the issue.

**Comment by bimalkjha** [comment]
Fix has been delivered using commit https://github.com/ibmdb/python-ibmdb/commit/cec149f3912eedbfc2d0e88c3a6e08f89670b5b6 and it would be part of next release. Thanks.
