### ISSUE TITLE
release level error

### ISSUE THREAD

**Issue by analyserdmz** [ibmdb/python-ibmdb#759]
- Operating System Name:
Windows 10
- db2level output from clidriver if in use:
SQLCODE=-5048  [IBM][CLI Driver] SQL5048N  The release level of the database client is not supported by the release level of the database server.
- Target Db2 Server Version:
7.2
- Python Version:
Tried with 2.7 and 3.10.5 (Both 32 and 64 bit)
- ibm_db version:
ibm-db==3.1.1

```
import ibm_db

connectionSettings = [
    {
        "dbtype": "DB2",
        "hostname": "DBSERVERHOSTNAME",
        "database": "DBNAME",
        "username": "DBUSER",
        "password": "DBPASS",
        "port": 50000,
        "protocol": "TCPIP"
    }
]

def connectToDB2(hostname, database, username, password, port, protocol):
    try:
        ibm_db.connect("DATABASE=BSS_CDRS;HOSTNAME={};PORT={};PROTOCOL={};UID={};PWD={};".format(hostname, port, protocol, username, password), "", "")
    except:     
        print("no connection: ", ibm_db.conn_errormsg())
    else:
        print("Connected to the database.")

for conn in connectionSettings:
    connectToDB2(conn["hostname"], conn["database"], conn["username"], conn["password"], conn["port"], conn["protocol"])
```

I keep getting the error described above and I wanted to ask if this is a normal behavior or not. And if yes, which ibm_db version do I need to install and use to be compatible with my version of DB2 Server?

Thank you.

**Comment by imavo** [comment]
Yes the error message you see is expected, and documented, and deliberate.

Typically the IBM supplied cli drivers operate OK only with 2 major Db2-versions lower than the cli driver version.  So that means a version 9.1 would be the highest client version that in theory would work with Db2 v7.x servers.  The currently shipping clidriver version (which by default gets installed with python) is v11.5 and that cannot operate with a v7.x Db2-server, which is the reason for your error symptom.


While you might be lucky enough to find an installable Db2-driver at version 7.x, or version 8.x or version 9.1, you may find that these will give errors installing on modern operating systems, and even if you do get them installed you might find that Python 3.x might fail to operate correctly with those antique versions.  

Adjust your expectations perhaps?

**Comment by analyserdmz** [comment]
Can't really do anything to kind of "upgrade" things. My work environment is way too old with TB of data and I am forced to use such old versions of DB2 Server. Unfortunately. In fact, I have a Db2-driver that old, and I am using it by calling the db2cmd utilities. The problem is I needed a custom solution in Python...

**Comment by imavo** [comment]
Find a v9.1 driver then, uninstall the current clidriver driver (manually) , and try installing the v9.1 driver . Most of the likely installation-time errors might have workarounds with competent troubleshooting.  Very few sites may be trying to access a v7.x Db2-LUW server with today's python versions, which means you are likely to be on your own with the integration efforts (but you may succeed, or be able to workaround some problems).   Of course, if you have a large enough budget, you can pay people to develop solutions...

**Comment by analyserdmz** [comment]
> @analyserdmz I assume the target Db2 Server version 7.2 is an LUW server and not AS400 server. In that case, you can download the db2 v9.1.11 client installer from [here](https://www.ibm.com/support/fixcentral/swg/selectFixes?source=dbluesearch&product=ibm%2FInformation+Management%2FIBM+Data+Server+Client+Packages&release=9.1.*&platform=Windows+64-bit,+x86&searchtype=fix&fixids=*client*FP011&function=fixId&parent=ibm/Information%20Management). Install it, and set system environment variable IBM_DB_HOME to full_path_of_install_directory_of_db2_client. Then uninstall the existing ibm_db and go for fresh installation. When environment variable IBM_DB_HOME is set and pointing to a db2 client/server installation, ibm_db do not download the latest clidriver from ibm hosted website and use the existing one. It should fix your problem. Thanks.

@bimalkjha thank you, I have followed the suggested workaround, I had signs of success but at the end I failed again. The good news is that the Db2 installation now is detected indeed! I am pasting the pip install log.

```
C:\Users\kkar>pip install ibm_db
Collecting ibm_db
  Using cached ibm_db-3.1.2.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Detected 64-bit Python
      Db2 installation detected ...
      Traceback (most recent call last):
        File "C:\Users\kkar\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\kkar\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\kkar\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\kkar\AppData\Local\Temp\pip-build-env-crrxzem1\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\kkar\AppData\Local\Temp\pip-build-env-crrxzem1\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "C:\Users\kkar\AppData\Local\Temp\pip-build-env-crrxzem1\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 118, in <module>
          _getinstalledDb2Path()
        File "setup.py", line 91, in _getinstalledDb2Path
          path = temp[1].strip()
      IndexError: list index out of range
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the 'C:\Users\kkar\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

C:\Users\kkar>
```

**Comment by bimalkjha** [comment]
@analyserdmz Use `pip install 'ibm-db==3.1.1'`. This issue may be due to use of latest ibm_db version 3.1.2. Thanks.

**Comment by analyserdmz** [comment]
Thanks again @bimalkjha ... you helped me to make a lot of steps forward. But strange things are happening. Have you seen that before?
![strange](https://user-images.githubusercontent.com/61113942/174761396-f551dc6a-c0e0-4981-8d07-262c86d71e0b.png)

**Comment by bimalkjha** [comment]
@analyserdmz You have set incorrect path for IBM_DB_HOME. It should be `C:\Program Files\IBM\SQLLIB` only. Correct the environment variable value and reinstall ibm_db==3.1.1. It should work. Thanks.

**Comment by bimalkjha** [comment]
Use 64bit version of python only. No need to use 32bit version.

**Comment by analyserdmz** [comment]
@bimalkjha I did. To be honest, I have double checked for the following steps.

- Uninstalled all Python installations
- Installed Python 3.10.5 x64
- Added Python to PATH
- Corrected the system variable IBM_DB_HOME
- Installed (pip install) ibm_db==3.1.1 with success

But when I try to run the script with the ibm_db module imported, I get **ImportError: DLL load failed while importing ibm_db: %1 is not a valid Win32 application.**

**Comment by Earammak** [comment]
@analyserdmz , Is the issue still exists for you?

**Comment by bimalkjha** [comment]
@analyserdmz If you are getting error `ibm_db: %1 is not a valid Win32 application`, it means ibm_db is not installed correctly and there was some installation error. Please share the complete output of `pip install 'ibm_db==3.1.1'` here along with test program output. Once you uninstall the existing ibm_db, make sure there is no ibm_db specific dirs under site_packages directory including clidriver. If it is there, delete it manually before reinstalling ibm_db.
After installation, check that `site-packages/ibm_db_dlls/ibm_db.dll` file exists.
Thanks.

**Comment by bimalkjha** [comment]
Fix delivered using commit https://github.com/ibmdb/python-ibmdb/commit/cec149f3912eedbfc2d0e88c3a6e08f89670b5b6 and it should be part of next release. Thanks.
