### ISSUE TITLE
version 3.1.2 fails to install on Debian Gnu/Linux

### ISSUE THREAD

**Issue by cdcadman** [ibmdb/python-ibmdb#761]
- Operating System Name: Debian Gnu/Linux
- db2level output from clidriver if in use: N/A
- Target Db2 Server Version: N/A
- Python Version: 3.9.13
- ibm_db version: 3.1.2
- For non-Windows, output of below commands:
  uname
Linux
  uname -m
x86_64
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Collecting ibm-db
  Downloading ibm_db-3.1.2.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 16.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/tmp81z8lgmj/output.json'

Steps to Reproduce:

1. Run 'pip install ibm_db'

**Comment by Earammak** [comment]
@cdcadman  Try unsetting IBM_DB_HOME, if it already set. Then run 'pip install ibm-db'.

**Comment by cdcadman** [comment]
@earammak IBM_DB_HOME was not set.

**Comment by cdcadman** [comment]
@Earammak yes, it was a problem with the system environment.  I ran pip with -vvv and discovered that gcc is missing.  After installing it, I was able to install ibm-db version 3.1.2.
This problem arose when I was trying to deploy an Azure function that had ibm-db as a dependency.  I will figure out how to install gcc before running pip during the deployment.
