### ISSUE TITLE
SERIOUS: Missing Packages -- Failed to install on all machines.

### ISSUE THREAD

**Issue by edumorlom** [ibmdb/python-ibmdb#765]
I am trying to install ibm_db on python using pip but I keep getting the following error. I have tried on different machines and on Docker containers. Running Mac and Linux. The files are missing.

All of the installation files are missing: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/

https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz is throwing 500.

I cannot install Python or node ibm_db

```
 ✗ pip3 install ibm_db       
Collecting ibm_db
  Using cached ibm_db-3.1.2.tar.gz (1.1 MB)
  Installing build dependencies ... done


  Getting requirements to build wheel ... done

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/var/folders/km/c5kjtfhx0j17qjhm1zdgkx8w0000gn/T/tmpzu36vqpn/output.json'
```

Logs:
[pip.log](https://github.com/ibmdb/python-ibmdb/files/9035763/pip.log)
[node.log](https://github.com/ibmdb/python-ibmdb/files/9035764/node.log)

**Comment by bimalkjha** [comment]
@edumorlom Use `pip3 install 'ibm_db==3.1.1'`. Thanks.

**Comment by edumorlom** [comment]
> @edumorlom Use `pip3 install 'ibm_db==3.1.1'`. Thanks.

this doesn't work either

**Comment by bimalkjha** [comment]
@edumorlom The same problem was reported by issue #761 and it is fixed by installing previous version. This error is specific to latest version. In older version of ibm_db this issue does not exist.
If you still see the issue, clean the cache and then try. It should work. Thanks.

**Comment by bimalkjha** [comment]
Ok. Problem is with the link https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz which is not available now. Checking with IBM about it. Once available, will update. Thanks.

**Comment by data-henrik** [comment]
the links seem to be available - I succeeded building

**Comment by edumorlom** [comment]
The issue seems to be fixed. The link now works.

https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz

Thank you!
