### ISSUE TITLE
Offline installation of ibm_db==3.1.2 failed

### ISSUE THREAD

**Issue by LuizSilvaDBA** [ibmdb/python-ibmdb#766]
I'm trying to install ibm_db==3.1.2 in a Windows server without internet access, so I set IBM_DB_HOME to the installation path of the DB2 Data Server client (11.5.7)

- Operating System Name: Windows Server 2022 Standard
- db2level output from clidriver if in use:
DB21085I  This instance or install (instance name, where applicable: "DB2")
uses "64" bits and DB2 code release "SQL11057" with level identifier
"0608010F".
Informational tokens are "DB2 v11.5.7000.1973", "s2111221000",
"DYN2111221000WIN64", and Fix Pack "0".
Product is installed at "D:\Program Files\IBM\SQLLIB" with DB2 Copy Name
"DB2COPY1".
- Target Db2 Server Version: n/a
- Python Version: 3.9.13
- ibm_db version: 3.1.2
- Value of below environment variables if set:
  IBM_DB_HOME:D:\Program Files\IBM\SQLLIB
  PATH:D:\Python_environments\test_python_39\venv\Scripts;C:\Program Files\Python39\Scripts\;C:\Program Files\Python39\;C:\Program Files\Eclipse Adoptium\JDK 11 x64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\PowerShell\7\;C:\Program Files\Git\cmd;C:\Program Files\Python\;C:\Program Files\Python\Scripts\;D:\Program Files\IBM\SQLLIB\BIN;D:\Program Files\IBM\SQLLIB\FUNCTION;C:\Users\luiz\AppData\Local\Microsoft\WindowsApps;
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: ;D:\Program Files\IBM\SQLLIB\LIB

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.
(Test Python 3.9.13) D:\Python_environments\test_python_39\venv>python -m pip install ibm_db==3.1.2 --no-index --find-links=file:D:\temp --log=log.txt
Looking in links: file:///D:\temp
Processing D:\temp\ibm_db-3.1.2.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error

  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing backend dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Steps to Reproduce:

It seems that the Db2 path is not being properly parsed from the "db2level" command. In setup.py, I've added the following to **setup.py** troubleshoot:
def _getinstalledDb2Path():
    status,output = subprocess.getstatusoutput('db2level')
    if(status == 0):
        _printOnly("Db2 installation detected ... ")
        temp = output.split("Product is installed at")
        path = temp[1].strip()
        path = path[0:-1]
        path = path.replace('"','')
        **print(f'Luiz - path extracted from "db2level": <{path}>')**
        
In the log generated:

2022-07-06T13:42:07,063   Luiz - path extracted from "db2level": <D:\Program Files\IBM\SQLLIB with DB2 Copy Name

2022-07-06T13:42:07,064   DB2COPY1>

**Comment by bimalkjha** [comment]
Fix has been delivered using commit https://github.com/ibmdb/python-ibmdb/commit/cec149f3912eedbfc2d0e88c3a6e08f89670b5b6 and it would be part of next release. Thanks.
