### ISSUE TITLE
Error: [IBM][CLI Driver] SQL1109N The specified DLL "GSKit Error: 202" could not be loaded. SQLSTATE=42724

### ISSUE THREAD

**Issue by Gabikakenobi** [ibmdb/python-ibmdb#767]
Hi Team!

Already attempted fixes described in issue #395 and #263 but error persists.
Attached trace file on request of Bimal for checking.

- Operating System Name: Win 10
- db2level output from clidriver if in use: DB2 v10.1.0.872 (64 bit)
- Target Db2 Server Version: Db2v 12.1.0
- Python Version: 3.9.5
- ibm_db version: 3.1.2
- Value of below environment variables if set:
  IBM_DB_HOME: C:\PROGRA~1\IBM\SQLLIB
  PATH: C:\PROGRA~1\IBM\SQLLIB\BIN
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: not set

- Test script to reproduce the problem. 
import ibm_db as db
import pandas as pd
import ibm_db_dbi as dbi
import traceback
import getpass
import matplotlib.pyplot as plt

try:    
   UID
except NameError:
    UID = 'None'
    if UID == 'None' :
        UID = input('EPLMVSA USER ID =')
        prompt = 'Password for '+UID+': '
        PWD = getpass.getpass(prompt=prompt, stream=None)

con_db2 = db.connect("DATABASE=databaseHOSTNAME=host;PORT=port;Security=SSL;SslServerCertificate=C:\Certificates\certificate.arm;PROTOCOL=TCPIP;UID=uid;PWD=pwd;", "", "")
conn_db2 = dbi.Connection(con_db2)
print('Connected')

Steps to Reproduce:

1.    ####run script with UID + pwd and con
nection parameters
2. get gskit 202 error

[dumpee2.txt](https://github.com/ibmdb/python-ibmdb/files/9061617/dumpee2.txt)

**Comment by imavo** [comment]
This 202 response code from IBM GsKit means "Unable to open the key file or the Microsoft Certificate Store. The path was specified incorrectly, or the file permissions did not allow the file to be opened, or the file format is incorrect. "
So, most likely this has nothing to do with ibm_db module, and cause by incorrect configuration. Verify that the path and the file C:\certificates\certificate.arm  actually exists, and that the userid/account that runs python has read permission to the directory and to the file.

**Comment by Gabikakenobi** [comment]
Hi imavo. Ty for commenting. Answer is yes to both points. (file exists and the account has admin level permission.

**Comment by bimalkjha** [comment]
@Gabikakenobi The db2 client version 10.1 does not support `SSLServerCertificate` keyword. It was added in Db2 V10.5.5.
So, if you want to use 10.1 client, then you need to create keystoredb using gskit command and add certificate to it. Then pass the keydbname and stashfile/keydbpasswd in connection string.
If you want to use the clidriver that comes with ibm_db, then remove setting of IBM_DB_HOME so that ibm_db will download own clidriver, but you need to correct PATH and LIB system environment variables to use the ibm_db\clidriver instead of C:\Program Files\IBM\SQLLIB. Thanks.

**Comment by Gabikakenobi** [comment]
Hi All,

Turns out the solution was incorrect certificate used from the certificate chain. Once the root CA was used, the CLI driver could make the connection with above connection string! (after update to 11.5).
