### ISSUE TITLE
OSError: [Errno 2] No such file or directory: 'output.json'

### ISSUE THREAD

**Issue by CarlosSchneider** [ibmdb/python-ibmdb#770]
I can't install python module ibm-db on openSUSE Docker Image

- Error:
```text
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/tmpab3re416/output.json'
```

- Operating System Name:

```text
sh-4.4# cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.4"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.4"
PRETTY_NAME="openSUSE Leap 15.4"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.4"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
```
- db2level output from clidriver if in use:

```text
sh-4.4# echo -e "IBM_DB_HOME=${IBM_DB_HOME}\nLD_LIBRARY_PATH=${LD_LIBRARY_PATH}\nDYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}\nLIB=${LIB}\nPATH=${PATH}"
IBM_DB_HOME=/opt/db2/clidriver
LD_LIBRARY_PATH=/opt/db2/clidriver/lib
DYLD_LIBRARY_PATH=
LIB=
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

sh-4.4# $IBM_DB_HOME/bin/db2level
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11056" with level identifier "0607010F".
Informational tokens are "DB2 v11.5.6.0", "special_13806",
"DYN2201171140AMD64_13806", and Fix Pack "0".
Product is installed at "/opt/db2/clidriver".
```

- python Version:

```text
sh-4.4# python3.10 --version
Python 3.10.5
sh-4.4# pip3 --version
pip 22.1.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)
sh-4.4# pip3 list
Package    Version
---------- -------
pip        22.1.2
setuptools 63.2.0
```

- Test script to reproduce the problem.

```text
docker run -it opensuse/leap sh

zypper install -y python310 python310-devel pam libxml2 gcc gcc-c++ curl tar gzip
python3.10 -m ensurepip --upgrade
pip3 install --upgrade pip
pip3 install --upgrade setuptools
curl -o /tmp/linuxx64_odbc_cli.tar.gz https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
mkdir /opt/db2
tar -xzvf /tmp/linuxx64_odbc_cli.tar.gz -C /opt/db2/
export IBM_DB_HOME=/opt/db2/clidriver
export LD_LIBRARY_PATH=/opt/db2/clidriver/lib
pip3 install ibm-db

sh-4.4# pip3 install ibm-db
Collecting ibm-db
  Downloading ibm_db-3.1.2.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 456.7 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/tmpqh1ppftb/output.json'
```

**Comment by giggzy** [comment]
Seeing the same issue on MacOS

**Comment by eonu** [comment]
I'm also running into this when I try to install `ibm-db` (tried various versions) on Ubuntu and Debian 10 after having set `IBM_DB_HOME` to use a driver that I manually installed. 

Seems to work fine if you unset `IBM_DB_HOME`, but this means that you can't specify a manually installed driver, and that it will always auto-install its own ODBC CLI driver in `site-packages`.

**Comment by Earammak** [comment]
@CarlosSchneider, Can you please share the log for " pip3 install ibm_db -v "

**Comment by eonu** [comment]
@Earammak in my case it seems to be that there is no `include` directory at `IBM_DB_HOME` according to `pip install ibm-db -v`.

```
Db2 installation found but the installed Db2 directory does not contain include directory.
  For IBM_DB installation it is important to have the include directory in the installed Db2 folder, as it is required for ibm_db compilation.
  Progessing with download of clidriver along with the installation.
   /home/db2inst1/sqllib/include folder not found. Check if you have set the IBM_DB_HOME environment variable's value correctly
```

I have set up a client instance `db2inst1` using the `db2icrt` script and also ran `. /home/db2inst1/sqllib/db2profile` to set up the correct environment variables including `IBM_DB_HOME=/home/db2inst1/sqllib`, but it does seem that there is no `include` directory.

I am using an installation of the IBM Data Server Runtime Client, **not** the ODBC and CLI driver. I was also only able to complete the setup using `db2_install` rather than `db2setup`, as I only have command-line access (no GUI).

Do you know if `ibm_db` works with IBM Data Server Runtime Client? For my purposes I will not be able to use the ODBC and CLI driver.

**Comment by CarlosSchneider** [comment]
Have a new version of PIP.

<details>
  <summary>Result of 'pip3 install ibm_db -v'</summary>
  
```txt
sh-4.4#
sh-4.4# pip3 install ibm_db -v
Using pip 22.2.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)
Collecting ibm_db
  Using cached ibm_db-3.1.2.tar.gz (1.1 MB)
  Running command pip subprocess to install build dependencies
  Collecting setuptools
    Using cached setuptools-63.2.0-py3-none-any.whl (1.2 MB)
  Installing collected packages: setuptools
  Successfully installed setuptools-63.2.0
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  <string>:393: UserWarning: Detected usage of IBM Data Server Driver package. Ensure you have downloaded 64-bit package of IBM_Data_Server_Driver and retry the ibm_db module install

  Detected 64-bit Python

  No Gcc installation detected.
  Please install gcc and continue with the installation of the ibm_db.
  Getting requirements to build wheel ... done
ERROR: Could not install packages due to an OSError.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 68, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/usr/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/usr/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/usr/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/usr/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 685, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 172, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 328, in _call_hook
    data = compat.read_json(pjoin(td, 'output.json'))
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/compat.py", line 16, in read_json
    with open(path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp3c0vd90p/output.json'
sh-4.4#

```  


</details>

**Comment by Earammak** [comment]
@CarlosSchneider , Check gcc installed or not. 
This is the error it is pointing here:
  No Gcc installation detected.
  Please install gcc and continue with the installation of the ibm_db.
  Getting requirements to build wheel ... done
ERROR: Could not install packages due to an OSError.

**Comment by CarlosSchneider** [comment]
sh-4.4# gcc --version
gcc (SUSE Linux) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

sh-4.4#

**Comment by Isabela192** [comment]
I'm also getting the same error:
`ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory:  output.json`

My system specs:
MacOS Monterey v 12.4
Apple M1

I also checked my gcc:
` gcc --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.5.0
Thread model: posix`

I already installed cmake as well, couldn't get around this error

**Comment by bimalkjha** [comment]
> @Earammak in my case it seems to be that there is no `include` directory at `IBM_DB_HOME` according to `pip install ibm-db -v`.
> 
> ```
> Db2 installation found but the installed Db2 directory does not contain include directory.
>   For IBM_DB installation it is important to have the include directory in the installed Db2 folder, as it is required for ibm_db compilation.
>   Progessing with download of clidriver along with the installation.
>    /home/db2inst1/sqllib/include folder not found. Check if you have set the IBM_DB_HOME environment variable's value correctly
> ```
> 
> I have set up a client instance `db2inst1` using the `db2icrt` script and also ran `. /home/db2inst1/sqllib/db2profile` to set up the correct environment variables including `IBM_DB_HOME=/home/db2inst1/sqllib`, but it does seem that there is no `include` directory.
> 
> I am using an installation of the IBM Data Server Runtime Client, **not** the ODBC and CLI driver. I was also only able to complete the setup using `db2_install` rather than `db2setup`, as I only have command-line access (no GUI).
> 
> Do you know if `ibm_db` works with IBM Data Server Runtime Client? For my purposes I will not be able to use the ODBC and CLI driver.

@eonu If you are using IBM_DB_HOME environment variable, the directory pointed by IBM_DB_HOME must have `include` directory as header files from include directory are getting used to compile native code of ibm_db during installation.
Only `IBM Data Server Driver Pakcage`, `IBM Data Server Client` or `IBM Db2 Server` install can be used with ibm_db. If you are downloading any other installer and want to use with ibm_db, it is not supported. Not even the clidriver or RTCL downloaded from Fix Central or Passport Advantage. Hope it clarifies. Thanks.

**Comment by bimalkjha** [comment]
@CarlosSchneider @Isabela192 @giggzy It seem, this code [setup.py:103](https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/setup.py#L103) is unable to get the result from `which gcc` command and returning command status as non zero i.e. error. Hence, ibm_db thinks there is no gcc in the system and call `sys.exit()` at [setup.py:59](https://github.com/ibmdb/python-ibmdb/blob/master/IBM_DB/ibm_db/setup.py#L59). Could you please check why `which gcc` command is not working during the installation of `ibm_db` with pip3? Thanks.

**Comment by eonu** [comment]
> > @Earammak in my case it seems to be that there is no `include` directory at `IBM_DB_HOME` according to `pip install ibm-db -v`.
> > ```
> > Db2 installation found but the installed Db2 directory does not contain include directory.
> >   For IBM_DB installation it is important to have the include directory in the installed Db2 folder, as it is required for ibm_db compilation.
> >   Progessing with download of clidriver along with the installation.
> >    /home/db2inst1/sqllib/include folder not found. Check if you have set the IBM_DB_HOME environment variable's value correctly
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have set up a client instance `db2inst1` using the `db2icrt` script and also ran `. /home/db2inst1/sqllib/db2profile` to set up the correct environment variables including `IBM_DB_HOME=/home/db2inst1/sqllib`, but it does seem that there is no `include` directory.
> > I am using an installation of the IBM Data Server Runtime Client, **not** the ODBC and CLI driver. I was also only able to complete the setup using `db2_install` rather than `db2setup`, as I only have command-line access (no GUI).
> > Do you know if `ibm_db` works with IBM Data Server Runtime Client? For my purposes I will not be able to use the ODBC and CLI driver.
> 
> @eonu If you are using IBM_DB_HOME environment variable, the directory pointed by IBM_DB_HOME must have `include` directory as header files from include directory are getting used to compile native code of ibm_db during installation. Only `IBM Data Server Driver Pakcage`, `IBM Data Server Client` or `IBM Db2 Server` install can be used with ibm_db. If you are downloading any other installer and want to use with ibm_db, it is not supported. Not even the clidriver or RTCL downloaded from Fix Central or Passport Advantage. Hope it clarifies. Thanks.

Thanks for the response @bimalkjha, I was not aware of this.

I had previously also been trying to get the `IBM Data Server Driver for ODBC and CLI` working with `ibm_db_sa` using `IBM_DB_HOME` and was not able to. I am not sure how involved you are with `ibm_db_sa`, but basically I believe in SQLAlchemy when you use `ibm_db_sa` as the driver name in [`create_engine`](https://docs.sqlalchemy.org/en/14/core/engines.html#database-urls), it tries to use the drivers installed by `ibm_db` in `site-packages`, or `IBM_DB_HOME` if it is set. This fails for the `clidriver` as you say, but instead if you specify `ibm_db_sa+pyodbc` and make sure you have a `/etc/odbcinst.ini` pointing to `lib/libdb2.so` from `clidriver`, it actually works for `IBM Data Server Driver for ODBC and CLI`.

For some reason I am not able to do the same for `IBM Data Server Runtime Client` by pointing to `lib64/libdb2.so` in `/etc/odbcinst.ini`.

I appreciate that this is quite unrelated to @CarlosSchneider's original issue, so I may create a separate issue perhaps in `ibm_db_sa`, but would appreciate it if you had any ideas.

**Comment by bimalkjha** [comment]
@eonu In case of `pyodbc` where `odbcinst.ini` is used, `pyodbc` uses `Microsoft ODBC header files` installed in the system to compiler native code. Since, Microsoft odbc headers are already in the system, you just need to tell MS ODBC that use the `libdb2.so` as driver using `odbcinst.ini`. So, it works using clidriver as `pyodbc` do not need IBM ODBC driver headers but it uses Microsoft ODBC Driver headers.
`ibm_db` uses `IBM ODBC Driver header files` and do not use Microsoft ODBC driver headers. Hence, we need a `Db2 client/server` with `include` directory.
If you want clidriver for use with ibm_db and you want to set its location using `IBM_DB_HOME`, then download a platform specific `clidriver` from `https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/` or from `https://github.com/ibmdb/db2drivers/raw/main/clidriver/`. `clidriver` from these locations comes with `include` directory and it will work with `ibm_db` without any issue. `ibm_db` downloads this clidriver only when `IBM_DB_HOME` is **not** set. Hope it clarifies. Thanks.

**Comment by Isabela192** [comment]
I checked the logs and there is no mention of gcc but at the EOF I found this:

```
2022-07-30T18:26:02,734   Running command Getting requirements to build wheel
2022-07-30T18:26:02,845   Detected 64-bit Python
2022-07-30T18:26:02,845   Arm64 architecture is not supported. Please install x64 version of python and then install ibm_db
```

My question now is: our team uses asdf as a python manager since that we use diferente versions of python for the projects. Is there a known way to install another version of Python on mac M1? Or this package will get a matching version for Macarchiteture?

**Comment by bimalkjha** [comment]
@Isabela192 Just google about "How to install multiple versions of python on macos", you'll multiple solutions.
I would suggest to download and install `64bit intel-only installer` of python as https://www.python.org/ftp/python/3.9.13/python-3.9.13-macosx10.9.pkg . Set environment variables to use this python during installation of ibm_db. Thanks.

**Comment by CarlosSchneider** [comment]
@bimalkjha 
Thank you very much, I identified that the package 'which' is prerequisite for installation of the ibm-db module, was resolved with command:
```bach
zypper -y install which
pip3 install ibm-db
```
