### ISSUE TITLE
ibm-db 3.1.2 install failed for UnicodeDecodeError

### ISSUE THREAD

**Issue by beruhan** [ibmdb/python-ibmdb#772]
- Operating System Name: ubuntu18.04 docker
- Python Version: 3.6.9
- ibm_db version: 3.1.2

ibm-db 3.1.2 install failed for UnicodeDecodeError，install process as follows:

![image](https://user-images.githubusercontent.com/7598892/180490399-2e76db31-50ae-4c21-ace3-efc5bb950952.png)

**Comment by imavo** [comment]
Can you please include your Dockerfile, to show which packages you added to the container, you can get this symptom when there are missing packages.

**Comment by beruhan** [comment]
before install the package,I set the local LANG:`update-locale LANG=zh_CN.UTF-8 LC_ALL=zh_CN.UTF-8`

**Comment by bimalkjha** [comment]
@beruhan Fix for this issue has been pushed on github and should be part of next release. Thanks.
