### ISSUE TITLE
How Do I get the field types in the database?

### ISSUE THREAD

**Issue by kxmatjob** [ibmdb/python-ibmdb#773]
Use the ibm_db.field_type() return str or integer, i want the description string to be varchar / character / integer / bigint /smallint / timestamp.

**Comment by Earammak** [comment]
@kxmatjob, Kindly refer the **API wiki page** : https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbfield_type

**Comment by kxmatjob** [comment]
CREATE TABLE TEST_TAB(C4 VARCHAR (30), C5 CHARACTER (10));

```
strsql = "SELECT * FROM TEST_TAB"
stmt = ibm_db.exec_immediate(conn, strsql)
num_f = ibm_db.num_fields(stmt)
for i in range(num_f):
    print(ibm_db.field_type(stmt, i))
```
There is no distinction between **char** and **varchar**
```
string
string
```

**Comment by Earammak** [comment]
@kxmatjob , The functionality of ibm_db.field_type ( ) is to return data type of the indicated column in a result set.
   To find the distinction between char and varchar, we can see by printing the values for that table.

Here is the sample example:
`import ibm_db
conn_str="Connection details"
connection = ibm_db.connect(conn_str,"","")
drop = "drop table TEST_TAB"
rc = ibm_db.exec_immediate(connection,drop)

create = "CREATE TABLE TEST_TAB(C4 VARCHAR (10), C5 CHAR (10))"
rc = ibm_db.exec_immediate(connection,create)

insert = "insert into TEST_TAB values( 'abcd1234' , 'abcd')"
rc = ibm_db.exec_immediate(connection,insert)

select = "SELECT * FROM TEST_TAB"
stmt = ibm_db.exec_immediate(connection, select)
row = ibm_db.fetch_tuple(stmt)
while ( row ):
    for i in row:
        print("ABC"+i+"XYZ")
    row = ibm_db.fetch_tuple(stmt)
num_f = ibm_db.num_fields(stmt)
for i in range(num_f):
    print(str(ibm_db.field_type(stmt, i)))`

And Result : 
ABCabcd1234XYZ
ABCabcd            XYZ
string
string

**Comment by kxmatjob** [comment]
```
insert into TEST_TAB values( 'abcd1234' , 'abcd1234')
insert into TEST_TAB values( 'abcd1234  ' , 'abcd1234')
```
How to distinguish the types of C4 and C5？

**Comment by bimalkjha** [comment]
@kxmatjob In python, the only data type is 'string'. We do not have 'varstring' data type in python. Could you please answer what data type you want to see in python for varchar?
If your application has need to distinguish between char and varchar column type, then describe the table, save the column type from describe output and process your logic accordingly. Based on retrieve result, you can not distinguish between the char and varchar. You need to get the describe info for the table from server and then do processing. Thanks.
