### ISSUE TITLE
Bug Report: 3.1.3 -- On Windows 10 -- Install works, but import fails:  can't find site-packages\\clidriv er\\bin

### ISSUE THREAD

**Issue by readytheory** [ibmdb/python-ibmdb#777]
- Operating System Name:  Windows 10.0.19043
- db2level output from clidriver if in use: N/A
- Target Db2 Server Version: N/A
- Python Version: 3.9.9 and 3.10.4
- ibm_db version: 3.13
- For non-Windows, output of below commands:
  uname  N/A
  uname -m  N/A
- Value of below environment variables if set:
  IBM_DB_HOME: (not set)
  PATH: /c/Users/a152280/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/a152280/bin:/c/Program Files (x86)/MKS Toolkit/mksnt:/c/PROGRA~2/MKSTOO~1/bin64:/c/PROGRA~2/MKSTOO~1/bin:/c/PROGRA~2/MKSTOO~1/bin/X11:/c/PROGRA~2/MKSTOO~1/mksnt:/c/IBM/InformationServer11_7/jdk32/jre/bin:/c/IBM/InformationServer11_7/jdk32/jre/bin/j9vm:/c/IBM/InformationServer11_7/ASBNode/lib/cpp:/c/IBM/InformationServer11_7/ASBNode/apps/proxy/cpp/vc60/MT_dll/bin:/c/apps/IBM/WebSphere MQ/java/lib:/c/apps/IBM/WebSphere MQ/java/lib64:/c/Program Files (x86)/RSA SecurID Token Common:/c/Program Files/RSA SecurID Token Common:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Program Files (x86)/Verint/Playback:/c/Program Files (x86)/Pulse Secure/VC142.CRT/X64:/c/Program Files (x86)/Pulse Secure/VC142.CRT/X86:/c/PROGRA~2/IBM/SQLLIB/BIN:/c/PROGRA~2/IBM/SQLLIB/FUNCTION:/c/Program Files (x86)/Webex/Plugins:/c/apps/IBM/WebSphere MQ/bin64:/c/apps/IBM/WebSphere MQ/bin:/c/apps/IBM/WebSphere MQ/tools/c/samples/bin:/c/Program Files/Perforce:/c/Program Files/Perforce/DVCS:/c/Program Files/nodejs:/c/apps/gradle-4.4.1/bin:/c/Program Files (x86)/Extra!:/c/Program Files/Docker/Docker/resources/bin:/c/ProgramData/DockerDesktop/version-bin:/c/Program Files/Amazon/AWSCLIV2:/c/Program Files/PuTTY:/c/PROGRA~1/IBM/SQLLIB/BIN:/c/PROGRA~1/IBM/SQLLIB/FUNCTION:/cmd:/c/VSCode/bin:/c/Users/a152280/AppData/Local/Programs/Python/Launcher:/c/Users/a152280/AppData/Local/Microsoft/WindowsApps:/c/bin:/c/bin/oracle:/usr/bin/vendor_perl:/usr/bin/core_perl
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: N/A

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

python -m venv .venv
. .venv/Scripts/activate
pip install ibm_db
python
\>\>\> import ibm_db

ibm_db 3.1.3 is installed by pip but "imoprt ibm_db" results in 
The system cannot find the path specified... venv\\lib\\site-packages\\clidriver\\bin'

And from inside the site-packages folder

$ find . -name '*clidr*'

Gets no results.

I am able to import and use 3.1.2

**Comment by Earammak** [comment]
@readytheory  Looks like in your machine both 3.9 and 3.10 python installed available.
 Try to run with python3 instead of python and see. 
If you check for python --version and python3 --version commands, python3 will have latest python version.
It will work with python3.

**Comment by readytheory** [comment]
@Earammak, thanks for checking.

I always  work inside a virtual environment so "python3" isn't defined.  In a venv (at least on the Windows machine I am using now)  `python3` says `command not found`.  But I tried using both 3.10.4 and 3.9.9, they work with several other versions  of ibm_db.  

On my work machine I saw that same failure with 3.10.4 and 3.9.9, but **on my  home machine,also windows, I can't replicate the problem** with either 3.10.4 or 3.9.10.    At work there are a couple variables I can think of, I'll try to check today to see if  I can find relevant difference.  In particular I didn't pay attention to what version of pip was in use, and I we have a internal pypi server that might have something cached that setup tools uses -- I  don't know if that's even a theoretical  possibility though.

But on the problem machine, which I looked in /c/venv/X/Lib/site-packages/, there was no folder "clidriver", whereas on my  home machine I do see the folder is created.

**Comment by readytheory** [comment]
@Earammak I saw a lot of checking is added to setup.py in [this commit](https://github.com/ibmdb/python-ibmdb/commit/cec149f3912eedbfc2d0e88c3a6e08f89670b5b6)

On my machine we do have a bunch of db2 stuff set up and in particular "db2level" is installed.  The `_getinstalledDb2Path():` is therefore skipping the download, but that results in failed installation.  

I do have these files:
```
$ ls -l /c/Program Files/ibm/SQLLIB/clidriver/bin/
total 1016
-rwxr-xr-x 1 a152280 1049089 459400 May  3  2018 IBMLDAPauthclient.dll*
-rwxr-xr-x 1 a152280 1049089 575112 May  3  2018 IBMLDAPauthclient64.dll*
```

When I run setup.py:
```
$python setup.py 
Detected 64-bit Python
Db2 installation detected ... 
Setting IBM_DB_HOME=C:\PROGRA~2\IBM\SQLLIB and skipping the clidriver download for the installation
c:\py\python-ibmdb\IBM_DB\ibm_db\setup.py:425: UserWarning: Detected usage of IBM Data Server Driver package. Ensure you have downloaded 64-bit package of IBM_Data_Server_Driver and retry the ibm_db module install
 . . . . 
```
I'm not sure what I would download and where I would put it, if that message is relevant.

**Comment by readytheory** [comment]
@Earammak based on your comment in another windows 10 thread, I ran this:
`export IBM_DB_HOME=/c/Program\ Files/ibm/SQLLIB`

And after that, import works.  Am testing that it works okay thereafter.  Something odd -- although `pip list` says it is 3.1.3, running `ibm_db.__version__` in python says 3.1.2

**Comment by danmaxis** [comment]
I had this same issue and after many tries, using this solution below worked for me.

https://github.com/ibmdb/python-ibmdb/issues/456#issuecomment-1039546019

#456 

These lines before import ibm_db :
```
import os
os.add_dll_directory("C:\\<clidriver path>\\bin")
```




Now I'm able to run Django 4 in python 3.11 connecting to DB2 in a windows environment.

**Comment by Earammak** [comment]
@readytheory In the new release the issue has been fixed. Please check with latest version 3.1.4. Thanks

**Comment by readytheory** [comment]
Not going to reopen, but not solved.  I think it is because of how my office configures DB2 installation on workstations; I have same symptom -- can `pip install ibm_db` successfully but `import ibm_db` gives clidriver exception.  Workaround: in a throwaway virtual environment, install version 3.1.0 .  Install ibm_db 3.1.4 (for example) in your intended virtual environment.  Using windows explorer, copy  lib/site-libraries/clidriver folder to the intended virtual environment site-libraries.
