### ISSUE TITLE
Error Installing ibm_db on Win10

### ISSUE THREAD

**Issue by bobgeorge1st** [ibmdb/python-ibmdb#779]
- Operating System Name: Win 10 Enterprise
- db2level output from clidriver if in use:  

DB21085I  Diese Instanz oder Installation (Instanzname, sofern zutreffend:
"DB2") verwendet "32" Bit und DB2-Codefreigabe "SQL11014" mit Aktualitõts-ID
"0205010F".
Informationstokens: "DB2 v11.1.4040.491", "s1811091400", "DYN1811091400WIN32"
und FixPak "4".
Produkt ist in "C:\PROGRA~2\IBM\SQLLIB" mit DB2-Kopienamen "DB2COPY1"
installiert.

- Target Db2 Server Version:
- Python Version: 3.8.5
- ibm_db version: 3.1.3
- For non-Windows, output of below commands:
  uname
  uname -m
- Value of below environment variables if set:
  IBM_DB_HOME:  C:\PROGRA~2\IBM\SQLLIB\clidriver
  PATH: C:\PROGRA~2\IBM\SQLLIB\BIN;C:\PROGRA~2\IBM\SQLLIB\FUNCTION;C:\PROGRA~1\IBM\SQLLIB\BIN;C:\PROGRA~1\IBM\SQLLIB\FUNCTION
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:" ;C:\PROGRA~1\IBM\SQLLIB\LIB;C:\PROGRA~2\IBM\SQLLIB\LIB

C:\Users\*****>pip install ibm_db
Looking in indexes: https://*******/artifactory/api/pypi/ext-pypi/simple/
Collecting ibm_db
  Using cached https://*****/artifactory/api/pypi/ext-pypi/packages/packages/8e/03/.../ibm_db-3.1.3.tar.gz (1.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Detected 32-bit Python
      Db2 installation detected ...
      Traceback (most recent call last):
        File "c:\python385-32\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "c:\python385-32\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\python385-32\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-kxos87qm\overlay\Lib\site-packages\setuptools\build_meta.py", line 337, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-kxos87qm\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in _get_build_requires
          self.run_setup()
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-kxos87qm\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in run_setup
          exec(code, locals())
        File "<string>", line 129, in <module>
        File "<string>", line 91, in _getinstalledDb2Path
      IndexError: list index out of range
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Steps to Reproduce:

1. pip install ibm_db

**Comment by bimalkjha** [comment]
@bobgeorge1st It seems you have set an incorrect value of environment variable IBM_DB_HOME as C:\PROGRA2\IBM\SQLLIB\clidriver. It should be `C:\Program Files\IBM\SQLLIB` only. Please correct the value of IBM_DB_HOME and install using a new command prompt. Thanks.

**Comment by bimalkjha** [comment]
@bobgeorge1st Please share complete output of `db2level` command too. Thanks.

**Comment by bobgeorge1st** [comment]
> @bobgeorge1st It seems you have set an incorrect value of environment variable IBM_DB_HOME as C:\PROGRA2\IBM\SQLLIB\clidriver. It should be `C:\Program Files\IBM\SQLLIB` only. Please correct the value of IBM_DB_HOME and install using a new command prompt. Thanks.

Thanks, but that doesn't solve the problem

**Comment by bobgeorge1st** [comment]
> @bobgeorge1st Please share complete output of `db2level` command too. Thanks.

Added to first post.
