### ISSUE TITLE
Running into error - Exception: [IBM][CLI Driver] SQL30081N A communication error has been detected

### ISSUE THREAD

**Issue by harshit-sh** [ibmdb/python-ibmdb#782]
Hi, a client is running into an error when using ssl certificate to connect to IBM DB2 Warehouse on Cloud Pak for Data instance.

`
Error: [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "SSL". Communication API being used: "SOCKETS". Location where the error was detected: "". Communication function detecting the error: "sqlccSSLSocketSetup". Protocol specific error code(s): "414", "*", "*". SQLSTATE=08001 SQLCODE=-30081
`

* `ibm_db` version - `3.1.1`
* DB2 version - `11.5.7.0-cn4`

I have referred to the links below and they are pointing to incompatible versions of GSKit as the cause of the issue -
* https://stackoverflow.com/questions/53609339/error-when-connecting-to-db2-with-ibm-db-with-ssl
* https://github.com/ibmdb/node-ibm_db/issues/762

Needed further guidance here. Thanks!

cc @bimalkjha

**Comment by bimalkjha** [comment]
@harshit-sh Incompatible version issue comes if client system already has another installation of a db2 client/server. So, PATH environment variable will point to different odbc library and not the one inside ibm_db.
If there is clidriver under site_packages, PATH and LIB system environment variable need to be updated to use this clidriver.
We need below information to understand the user's environment properly:
- Operating System Name:
- db2level output:
- Target Db2 Server Version:
- Python Version:
- ibm_db version:
- For non-Windows, output of below commands:
  uname
  uname -m
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- cd to site_packages/clidriver/bin from command line and run command ".\db2cli validate". We need complete output of this validate command.

**Comment by harshit-sh** [comment]
Thanks @bimalkjha. Let me check and get back with the details.

**Comment by harshit-sh** [comment]
Here's the output of the `./db2cli validate` command -

```
===============================================================================
Client information for the current copy:
===============================================================================

Client Package Type       : IBM Data Server Driver For ODBC and CLI
Client Version (level/bit): DB2 v11.5.6.0 (special_13806/64-bit)
Client Platform           : Linux/X8664
Install/Instance Path     : ..
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : ../cfg/db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : ../cfg/db2cli.ini
db2diag.log Path          : db2diag.log

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file 
db2dsdriver.cfg. The file is searched at "../cfg/db2dsdriver.cfg".

===============================================================================
The validation is completed.
===============================================================================
```

The client DB2 version is `11.5.6`. As I mentioned earlier, the DB2 version of the DB2 warehouse instance is `11.5.7`. Is this mismatch leading to the error?

**Comment by harshit-sh** [comment]
Closing since updating the `IBM_DB_HOME` path to v11.5.7 would fix the issue.
