### ISSUE TITLE
UTF8 Smiles got corrupted on insert

### ISSUE THREAD

**Issue by gudim** [ibmdb/python-ibmdb#785]
- Operating System Name: **Windows 10 with UTF8 as system default codepage**
- db2level output from clidriver if in use: **not in use**
- Target Db2 Server Version: **11.5 on the cloud**
- Python Version: **3.9**
- ibm_db version: **3.1**

- Test script to reproduce the problem.
# example 1 (using tuples)
import os
import ibm_db

org_tuple=[]

conn_str_stg = f"HOSTNAME=<host>;PORT=<port>;DATABASE=<dbname>;UID={dbuser_stg};PWD={dbpswd_stg};Security=SSL"       
conn_stg = ibm_db.pconnect(conn_str_stg, "", "")
sql_insert = "INSERT INTO UAT.TEST (NAME) VALUES(?)"
stmt_stg = ibm_db.prepare(conn_stg, sql_insert)
org_tuple.insert(0, ('JAJA 😂',))
print(tuple(org_tuple))
ibm_db.execute_many(stmt_stg, tuple(org_tuple))
ibm_db.commit(conn_stg)

# example 2 using prepare
import os
import ibm_db

conn_str_stg = f"HOSTNAME={dbhost_stg};PORT=31481;DATABASE=BLUDB;UID={dbuser_stg};PWD={dbpswd_stg};Security=SSL"       
conn_stg = ibm_db.pconnect(conn_str_stg, "", "")
value = 'JAJA 😂'
sql = "INSERT INTO UAT.TEST(NAME) VALUES (?)"
stmt = ibm_db.prepare(conn_stg, sql)
ibm_db.bind_param(stmt, 1, value)
ibm_db.execute(stmt)
ibm_db.commit(conn_stg)

# comments
In both cases ORIGINAL value got corrupted on insert

HEX of good value is   4A414A4120F09F9882
HEX of BAD value after insert  4A414A4120EDA0BD

Meanwhile when I am doing insert from dbeaver
on the same machine it's working as expected
 INSERT INTO UAT.TEST values('JAJA 😂')
![utf8_smile_corrupted](https://user-images.githubusercontent.com/4955527/186705739-a2db1ac9-94aa-4aa3-b71c-21651f989505.jpg)

**Comment by Earammak** [comment]
@gudim , Please share the trace file.

db2trc on -f trc.dmp
now run your application
db2trc off
db2trc flw trc.dmp trc.flw
db2trc fmt trc.dmp trc.fmt
db2trc fmt -c trc.dmp trc.fmtc
db2trc fmt -cli trc.dmp trc.cli
and share these files trc.flw, trc.fmt, trc.fmtc and trc.cli files

**Comment by gudim** [comment]
I did tried and the dmp file is empty.

Any way I did found that this issue is not reproduced on the other hosts so considering it's my local issue most likely related to the fact that I did enable the ust-8 betta support on windows.  I did try to on/off this feature but it's still behaves same way, but this is the only diff from other host where I've tried to run.  Any way I think you may close the call, except you may want to find out the root caue and need more information from me.  Thank you!

**Comment by gudim** [comment]
And finally been able to get the dmp and rest of the files an fixed the issue by adding DB2CODEPAGE=1208 in to windows system variables.

Thank you! and sorry for trouble!
