### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files\\Python310\\lib\\site-packages\\clidriver\\bin'

### ISSUE THREAD

**Issue by KM04021987** [ibmdb/python-ibmdb#790]
- Operating System Name: Windows 11
- db2level output from clidriver if in use: 
- Target Db2 Server Version:
- Python Version: Python 3.10.7
- ibm_db version: ibm-db     3.1.3
- For non-Windows, output of below commands:
  uname
  uname -m
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH: C:\Program Files\Python310, C:\Program Files\Python310\Scripts, C:\Program Files\IBM\Cloud\bin
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.
installation is successful.
C:\WINDOWS\system32>pip show ibm-db
Name: ibm-db
Version: 3.1.3
Summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS
Home-page: http://pypi.python.org/pypi/ibm_db/
Author: IBM Application Development Team
Author-email: praveen.narayanappa1@ibm.com
License: Apache License 2.0
Location: c:\program files\python310\lib\site-packages
Requires:
Required-by:

Steps to Reproduce:

1. I am trying to connect IBM-DB from my python code using "python weeklybatch.py" command. I am seeing below issue.
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Batch-onemonthsdrywaste\weeklybatch.py", line 1, in <module>
    import ibm_db
  File "C:\Program Files\Python310\lib\site-packages\ibm_db.py", line 7, in <module>
    os.add_dll_directory(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'clidriver', 'bin'))
  File "C:\Program Files\Python310\lib\os.py", line 1117, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files\\Python310\\lib\\site-packages\\clidriver\\bin'

2.

**Comment by Earammak** [comment]
@KM04021987 Can you please share the db2level output.

**Comment by KM04021987** [comment]
C:\WINDOWS\system32>db2level
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11050" with level identifier "0601010F".
Informational tokens are "DB2 v11.5.0.1077", "s1906101300",
"DYN1906101300WIN64", and Fix Pack "0".
Product is installed at "C:\PROGRA~1\IBM\IBMDAT~1" with DB2 Copy Name
"IBMDBCL1".

**Comment by KM04021987** [comment]
C:\WINDOWS\system32>db2cli validate

===============================================================================
Client information for the current copy (copy name: IBMDBCL1):
===============================================================================

Client Package Type       : IBM Data Server Driver Package
Client Version (level/bit): DB2 v11.5.0.1077 (s1906101300/64-bit)
Client Platform           : NT 64BIT
Install/Instance Path     : C:\PROGRA~1\IBM\IBMDAT~1

Common App Data Path      : C:\ProgramData\IBM\DB2\IBMDBCL1
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : <Common App Data Path>\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : <Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : <Common App Data Path>\db2diag.log

===============================================================================
List of all IBM Data Server client packages on the current workstation:
===============================================================================

Copyname Version Package Language Installed-Location
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------

Warning: Unable to retrieve information on various IBM Data Server Client
Packages on the current workstation. Continuing with remaining validation
process.

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Success: The schema validation completed successfully without any errors.

===============================================================================
The validation is completed.
===============================================================================



C:\WINDOWS\system32>echo %PATH%
C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Program Files\Java\jdk-17.0.2\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\IBM\IBM DATA SERVER DRIVER\bin;C:\Program Files\nodejs\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\krish\AppData\Local\Microsoft\WindowsApps;C:\Users\krish\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\IBM\Cloud\bin;C:\Users\krish\AppData\Roaming\npm;C:\Program Files\heroku\bin


Yes. When i am running the python script from admin command prompt, then also i am seeing the issue. Please see below:
C:\Users\krish\Desktop\Batch-onemonthsdrywaste>python weeklybatch.py
Traceback (most recent call last):
  File "C:\Users\krish\Desktop\Batch-onemonthsdrywaste\weeklybatch.py", line 1, in <module>
    import ibm_db
  File "C:\Program Files\Python310\lib\site-packages\ibm_db.py", line 7, in <module>
    os.add_dll_directory(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'clidriver', 'bin'))
  File "C:\Program Files\Python310\lib\os.py", line 1117, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files\\Python310\\lib\\site-packages\\clidriver\\bin'



The path 'C:\Program Files\Python310\lib\site-packages\clidriver\bin' does not exist. I can see till C:\Program Files\Python310\lib\site-packages in my windows system. I cannot see clidriver folder inside site-packages folder.



I am not sure about the last question. When i search clidriver in my windows system, i think it is inside "C:\ProgramData\IBM\DB2". Because i can see one folder "IBMDBCL1" inside C:\ProgramData\IBM\DB2.

Please let me know if you need more info.

**Comment by Earammak** [comment]
@KM04021987, If ibm_db installed in machine, db2cli validate output should show the List of all IBM Data Server client packages on the current workstation.
 I'm not sure why it is not displaying from db2cli validate command, if ibm_db is already installed in your machine.
Here is the db2cli validate command output for my machine:

>db2cli validate

===============================================================================
Client information for the current copy (copy name: IBMDBCL1):
===============================================================================

Client Package Type       : IBM Data Server Driver Package
Client Version (level/bit): DB2 v11.5.8000.182 (s2205081300/64-bit)
Client Platform           : NT 64BIT
Install/Instance Path     : C:\DSDRIVER

Common App Data Path      : C:\ProgramData\IBM\DB2\IBMDBCL1
DB2DSDRIVER_CFG_PATH value: <not-set>
db2dsdriver.cfg Path      : <Common App Data Path>\cfg\db2dsdriver.cfg
DB2CLIINIPATH value       : <not-set>
db2cli.ini Path           : <Common App Data Path>\cfg\db2cli.ini
db2diag.log Path          : <Common App Data Path>\db2diag.log

===============================================================================
List of all IBM Data Server client packages on the current workstation:
===============================================================================

Copyname    Version Package Language Installed-Location
-------------------------------------------------------------------------------
DB2COPY1[D] 11.5.8000 UNKNOWN EN       C:\SQLLIB
IBMDBCL1[C] 11.5.8000 DSD     ALL_LANG C:\DSDRIVER
-------------------------------------------------------------------------------
 DSD: IBM Data Server Driver Package
-------------------------------------------------------------------------------

===============================================================================
db2dsdriver.cfg schema validation for the entire file:
===============================================================================

Note: The validation utility could not find the configuration file
db2dsdriver.cfg. The file is searched at
"C:\ProgramData\IBM\DB2\IBMDBCL1\cfg\db2dsdriver.cfg".

===============================================================================
The validation is completed.
===============================================================================

**Comment by Earammak** [comment]
@KM04021987 Hope you are able to find the right path for clidriver. Please update if you are facing the issue.
Thanks,

**Comment by LokeshViswa** [comment]
Hi, I am also getting the same error as mentioned in the description but I am unable to understand the steps mentioned in the comments. Please respond the solution step by step

**Comment by bimalkjha** [comment]
@LokeshViswa This issue comes when your system already have a db2 client/server installed before installing ibm_db. You can get the install directory of db2 client/server installed in your system by running `db2level` command from command prompt/terminal. In that case, you need to set a system level environment variable IBM_DB_HOME=full_path_of_db2_install_dir. Then install ibm_db. It should work.
For example, if your system has dsdriver installed as `C:\DSDRIVER` on windows, `set IBM_DB_HOME=C:\DSDRIVER` and then install ibm_db.
For non-windows, use export command. Suppose dsdriver is installed as `\home\user\sqllib`, then run `export IBM_DB_HOME=\home\user\sqllib` and then install ibm_db. 
As you can see, the steps are Operating system dependent, so if still your issue is not resolved, open a new issue with all the details as requested in new issue template. Then we can assist further. Thanks.
