### ISSUE TITLE
Can't connect to Db2 using SqlAlchemy in PyCharm and Python 3.9 x86

### ISSUE THREAD

**Issue by rahulkalluri** [ibmdb/python-ibmdb#791]
[Error log gist](https://gist.github.com/rahulkalluri/9d0e1998c26340a09a9b10c3649fd458)

Software:

    System Software Overview:

      System Version: macOS 12.6 (21G115)
      Kernel Version: Darwin 21.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Rahul’s MacBook Pro
      User Name: Rahul Kalluri (rahulkalluri)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 52 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Chip: Apple M1 Pro
      Total Number of Cores: 8 (6 performance and 2 efficiency)
      Memory: 16 GB
      System Firmware Version: 7459.141.1
      OS Loader Version: 7459.141.1
      Serial Number (system): KQN9WH6Y35
      Hardware UUID: F53CF502-F864-5EE4-A5BE-7B9DCC88AC57
      Provisioning UDID: 00006000-001214C02E91801E
      Activation Lock Status: Disabled

Steps to produce error: 

1. Install x86 version of Homebrew (I mainly followed [this guide](https://ibm.ent.box.com/notes/988770801740?s=tjk6q2azrb1pmp5s5s0xyfk4cg5pdmil))
2. Ensure terminal is constantly in x86 mode by running `arch -x86_64 zsh`
3. Install Apple Silicon version of PyCharm 
4. Verify Python version and Ibm_DB package are installed and working in PyCharm. I have not used any form of virtual environments, this is the base system interpreter. 
```
rahulkalluri@Rahuls-MacBook-Pro travel-expense % python3 -c "import ibm_db; print(ibm_db.__version__)"
3.1.3
rahulkalluri@Rahuls-MacBook-Pro travel-expense % which python3
/usr/bin/python3
rahulkalluri@Rahuls-MacBook-Pro travel-expense % python3 --version
Python 3.9.6
```
5. Connect to Db2 server using the following function 
```
def get_epm_connection(environment: str, creds: dict) -> (Engine, sqlalchemy.engine.Connection):
    """
    Connects to the EPM space then creates an engine and connection to that space
    :param creds: credentials from yaml file
    :param environment: pick one of the following options: staging, preprod, prod
    :return: an sqlalchemy engine and that engine's connection
    """
    env_creds = get_db2_credentials(creds=creds, environment=environment)
    sqla_url_f = f"db2+ibm_db://{env_creds['username']}:{env_creds['password']}@" \
                 f"{env_creds['hostname']}:{env_creds['port']}/{env_creds['database']};" \
                 f"{env_creds['ssl']};{env_creds['trustpass']};{env_creds['truststore']};"
    engine = sqlalchemy.create_engine(sqla_url_f, pool_size=10, max_overflow=20)
    conn = engine.connect()
    return engine, conn
```
6. Function fails during the `conn = engine.connect()` line. 
Error code in IDE: `Process finished with exit code 134 (interrupted by signal 6: SIGABRT)`

**Comment by bimalkjha** [comment]
@rahulkalluri Are you able to connect to Db2 using ibm_db directly and without SqlAlchemy? If yes, then you should open this issue in sqlalchemy repo.
Anyway, you can run below commands from terminal and see if issue get resolved:
```
$ brew tap homebrew/versions
$ brew install homebrew/versions/gcc8
$ export DYLD_LIBRARY_PATH=/usr/local/lib/gcc/8:$DYLD_LIBRARY_PATH
```
If issue do not get resolved, then:

sudo cp /usr/local/lib/gcc/8/libstdc++.6.dylib /usr/lib/libstdc++.6.0.9.dylib
reinstall ibm_db@latest
mv ..../site_packages/clidriver/lib/libstdc++.6.dylib  ..../site_packages/clidriver/lib/old_libstdc++.6.dylib
cp /usr/local/lib/gcc/8/libstdc++.6.dylib  ..../site_packages/clidriver/lib/libstdc++.6.dylib
```
Thanks.

**Comment by rahulkalluri** [comment]
Hi @bimalkjha, I cannot connect to an IBM DB at the moment using the original methods. I am also troubleshooting that but no connection as of right now. 

Running your code produces some deprecation errors. 
```
rahulkalluri@Rahuls-MacBook-Pro ~ % brew tap homebrew/versions

Error: homebrew/versions was deprecated. This tap is now empty and all its contents were either deleted or migrated.
rahulkalluri@Rahuls-MacBook-Pro ~ % brew install homebrew/versions/gcc8

Error: homebrew/versions was deprecated. This tap is now empty and all its contents were either deleted or migrated.
```
I can confirm that I already have a DYLD_LIBRARY_PATH in my environment: 
`DYLD_LIBRARY_PATH=/usr/local/lib/python3.9/site-packages/clidriver/lib:$DYLD_LIBRARY_PATH`


Additionally, I get a file not found when running the copy file command:
`rahulkalluri@Rahuls-MacBook-Pro travel-expense % sudo cp /usr/local/lib/gcc/8/libstdc++.6.dylib /usr/lib/libstdc++.6.0.9.dylib
Password:
cp: /usr/local/lib/gcc/8/libstdc++.6.dylib: No such file or directory`

**Comment by bimalkjha** [comment]
@rahulkalluri Please share output of `uname -a` command. If your system has `arm64` architecture then you need to install `intel only` version of python in your system for ibm_db to work. ibm_db do not work with arm64 version of python which is default python for M1 Chip system.
For `brew` error, run below commands:
```
brew tap homebrew/homebrew-core
brew update
brew search gcc@8
brew install gcc@8
ls /usr/local/lib/gcc
```
Please share output of `brew search gcc` and `ls /usr/local/lib/gcc` commands too. Thanks.

**Comment by rahulkalluri** [comment]
```
rahulkalluri@Rahuls-MacBook-Pro ~ % uname -a
Darwin Rahuls-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
```

I can confirm installing the x86 version of Python through Homebrew. The error log I posted indicated that Python is running in x86 mode. 
```
rahulkalluri@Rahuls-MacBook-Pro ~ % brew search gcc@8
==> Formulae
gcc@8 ✔      gcc          gcc@5        gcc@9        gcc@7        gcc@6
rahulkalluri@Rahuls-MacBook-Pro ~ % ls /usr/local/lib/gcc
8

**Comment by bimalkjha** [comment]
@rahulkalluri Are you able to connect to Db2 after installation of gcc8? Please update. Thanks.
