### ISSUE TITLE
Bug Report - BIGINT datatype with negative numbers having 19 digits cannot be retrieved from database when using ibm_db API

### ISSUE THREAD

**Issue by realaka** [ibmdb/python-ibmdb#792]
- Operating System Name:
- db2level output from clidriver if in use:
- Target Db2 Server Version:
- Python Version:
- ibm_db version:
- For non-Windows, output of below commands:
  uname
  uname -m
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

1.
2.

F:\aka\dev\pycharm>py
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> con = ibm_db.connect('DATABASE=AKA_TST5;UID=aka;PWD=secret','','')
>>> _ = ibm_db.exec_immediate(con, "create table aka.t1 (n bigint)")
>>> _ = ibm_db.exec_immediate(con, "create table aka.t2 (n bigint)")
>>> ibm_db.commit(con)
True
>>> _ = ibm_db.exec_immediate(con, "insert into aka.t1 (n) values (-999999999999999999)")
>>> ibm_db.commit(con)
True
>>> qry = ibm_db.exec_immediate(con, "select n as N from aka.t1")
>>> ibm_db.fetch_row(qry)
True
>>> v = ibm_db.result(qry,"N")
>>> print(v)
-999999999999999999
>>> print(type(v))
<class 'str'>
>>> ins = ibm_db.prepare(con, "insert into aka.t2 (n) values (?)")
>>> ibm_db.bind_param(ins, 1, v)
True
>>> ibm_db.execute(ins)
True
>>>
>>>
>>>
>>> _ = ibm_db.exec_immediate(con, "delete from aka.t1")
>>> ibm_db.commit(con)
True
>>> _ = ibm_db.exec_immediate(con, "insert into aka.t1 (n) values (-1000000000000000000)")
>>> ibm_db.commit(con)
True
>>> qry = ibm_db.exec_immediate(con, "select n as N from aka.t1")
>>> ibm_db.fetch_row(qry)
True
>>> v = ibm_db.result(qry,"N")
>>> print(v)
-100000000000000000
>>> print(type(v))
<class 'str'>
>>> ins = ibm_db.prepare(con, "insert into aka.t2 (n) values (?)")
>>> ibm_db.bind_param(ins, 1, v)
True
>>> ibm_db.execute(ins)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception: Statement Execute Failed: [IBM][CLI Driver] CLI0112E  Error in assignment. SQLSTATE=22005 SQLCODE=-99999
>>> exit()

F:\aka\dev\pycharm>db2level
DB21085I  This instance or install (instance name, where applicable: "DB2")
uses "64" bits and DB2 code release "SQL11057" with level identifier
"0608010F".
Informational tokens are "DB2 v11.5.7000.1973", "s2111221000",
"DYN2111221000WIN64", and Fix Pack "0".
Product is installed at "C:\bin\IBM\SQLLIB" with DB2 Copy Name "DB2COPY1".

F:\aka\dev\pycharm>ver

Microsoft Windows [Version 10.0.19044.2006]

F:\aka\dev\pycharm>py -m pip install ibm_db
Requirement already satisfied: ibm_db in c:\bin\python310\lib\site-packages (3.1.3)

F:\aka\dev\pycharm>

**Comment by imavo** [comment]
please show the output of `pip show ibm_db`  (we need to know its version).

**Comment by realaka** [comment]
F:\aka\dev\pycharm>py -m pip show ibm_db
Name: ibm-db
Version: 3.1.3
Summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS
Home-page: http://pypi.python.org/pypi/ibm_db/
Author: IBM Application Development Team
Author-email: praveen.narayanappa1@ibm.com
License: Apache License 2.0
Location: c:\bin\python310\lib\site-packages
Requires:
Required-by:

F:\aka\dev\pycharm>

**Comment by realaka** [comment]
I was looking to find a workaround for the problem but then I imagined that it's much worse...

```
>>> _ = ibm_db.exec_immediate(con, "insert into aka.t1 (n) values (9223372036854775807)")
>>> _ = ibm_db.exec_immediate(con, "insert into aka.t1 (n) values (1)")
>>> _ = ibm_db.exec_immediate(con, "insert into aka.t1 (n) values (0)")
>>> _ = ibm_db.exec_immediate(con, "insert into aka.t1 (n) values (-1)")
>>> _ = ibm_db.exec_immediate(con, "insert into aka.t1 (n) values (-999999999999999999)")
>>> _ = ibm_db.exec_immediate(con, "insert into aka.t1 (n) values (-1000000000000000000)")
>>> _ = ibm_db.exec_immediate(con, "insert into aka.t1 (n) values (-9223372036854775808)")
>>> qry = ibm_db.exec_immediate(con, "select n as N from aka.t1")
>>> while ibm_db.fetch_row(qry):
...    v = ibm_db.result(qry,"N")
...    print(bytes(v, encoding='ascii'))
...
b'9223372036854775807'
b'1'
b'0'
b'-1'
b'-999999999999999999'
b'-100000000000000000\x00'
b'-922337203685477580\x00'
>>>

```

It's not only that the \x00 byte leads to the SQL error but also the last digit from the value is gone!
And wouldn't it be more consistent to give back an integer rather than a string?

**Comment by imavo** [comment]
The symptom is reproducible on MS-Windows, but not on Linux x64

**Comment by imavo** [comment]
Note also that a workaround exists, which is to not use ibm_db.result() but instead use one of the other alternatives e.g. ibm_db.fetch_both() .
