### ISSUE TITLE
How to build from source on Windows-10 with Visual-Studio community edition?

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb#793]
- Operating System Name: Windows 10 Pro x64
- db2level output from clidriver if in use: v11.5.6000.7091
- Target Db2 Server Version: v11.4
- Python Version: 3.10.6
- ibm_db version: 3.1.3
- For non-Windows, output of below commands:
  uname
  uname -m
- Value of below environment variables if set:
  IBM_DB_HOME:  (not set)
  PATH:(includes clidriver\bin)
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: not relevant on MS-Windows.

- Test script to reproduce the problem.: none needed, this is a BUILD question
- 
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

Is there a document that describes the steps needed to compile ibm_db from source code on Microsoft-windows x64 with Visual-Studio Community, and then install it so that it can be debugged?

I am assuming that I can do the build/install using the Visual Studio Community edition.

I build manually often on linux x64 with `python setup.py build` and `python setup.py install`. But although these same steps appear to run successfully on Microsoft Windows, but I do not get any ibm_db.dll created and consequently python fails to load ibm_db. 

(For pre-built images) When I run `pip install --no-cache-dir ibm_db` it creates the site-packages\ibm-db-dlls directory and puts ibm_db.dll in there. But this does not happen when I build/install manually with my toolchain. I get a file ibm_db.cp310-win_amd64.pyd in a subdirectory of site-packages whose directory name is ibm_db_x.y.z-py3.10-win-amd64.egg (where x.y.z is the version of ibm_db).

I must be using incorrect steps.

Hence the request for the prereqs and steps needed to build/install ibm_db from source on Windows-10 with MSVC.

environment: MS-Windows 10 x64 , MSVC 2017 Community Edition, Python 3.10.6 x64, setuptools 65.4.0

**Comment by bimalkjha** [comment]
@imavo Any info is pending from out side or we can close this one? Thanks.

**Comment by imavo** [comment]
The request is not answered. 
I asked for instructions for building ibm_db from source-code using microsoft build tools or Misual-Studio community-edition.

But I do not yet see an answere here.

I reported that the supposedly documented method (python setup.py build,  followed by python setup-py install), I do not get any ibm_db.dll created (although no errors are generated, but lots of compilation warnings).

**Comment by Earammak** [comment]
@imavo   If you installed through "python setup.py install", dll will not be created.
This ibm_db.dll will be created only when you have a prebuilt binaries for windows[ we can see it from setup.py code]

**Comment by imavo** [comment]
@Earammak  hence my question, where are the  instructions for building ibm_db.dll from souce code on Microsoft Windows, using the Microsoft compiler?

**Comment by Earammak** [comment]
@imavo We will be generating of binaries for all the supported python versions both 32-bit and 64-bit during the release process. Yes, they are depending on Microsoft compiler. 

Thanks

**Comment by imavo** [comment]
@Earammak  
I'm fully aware that Microsoft C is required for python ibm_db on Windows, and also that pre-built binaries are available.

But I am not interested in pre-built binaries, because I want to compile from source-code, and for this I am asking for the instructions for compiling from source on Microsoft-Windows to be made public.

Is there some reason this is not documented?  
I don't know how I could make this question any more clear!

**Comment by Earammak** [comment]
@imavo If you want to know about compile process, purpose of pre-built binaries. We can have a webex/call on this.
              I can explain you the current procedure we follow interms of release.
              Please let me know your availability to discuss on this. 
             Thanks

**Comment by imavo** [comment]
@Earammak  I understand all about the general  compile process for 'c' on Windows/Linux etc, and understand the purpose of pre-built binaries, and I am well used to developing in 'c' at the command-line /scripting etc.  

Presumably you also understand that some people will want to change the code of ibm_db privately, ( i.e. not via forking on github) for experimental reasons, and therefore need to build it from source code in their own offline environments.

The only thing we need is to write down the command lines needed, because the old methods for building 'c' extensions to python (i.e. `python setup.py build...` etc ) do not result in a DLL on Microsoft-Windows, as I mentioned above. If that is only a temporary situation pending some further changes then that can also be described.

I don't know how to contact you as direct messages are not available on github.

**Comment by Earammak** [comment]
@imavo We can connect via Webex, I think. Please share meeting invitation to me and will join from here.

**Comment by Earammak** [comment]
@imavo, As part of ibm_db release process we will be copying the binaries that are generated under build/lib directory to ibm_db directory. Rename the pyd in the format as below:
               ibm_db<bit value>_py<pythonversion>
              e.g: ibm_db32_py27

This will be done for all the supported python version.

If you want to create dll a from the source code.
Follow the below steps:
1. copy .pyd file from lib directory and keep under ibm_db directory.
2. Rename the .pyd [the file under ibm_db ] is of the format as mentioned above.
3. Run python setup.py build/install 

After install of ibm_db, you should be able to see ibm_db_dll under site-packages.

Thanks

**Comment by Earammak** [comment]
@imavo I hope you have tried above mentioned update. Do you expect any info from our side?

Thanks

**Comment by imavo** [comment]
I have been away , this explains the delayed response.

Please clarify your instructions.

The most helpful documentation would be to explain the required steps in words, and then give a fully worked example, starting with downloading the snapshot python-ibmdb-master.zip from github on to a windows workstation that already has Python installed and on the PATH, and already has the Microsoft `cl.exe` and `link.exe` present on the PATH.


Please explain if there are any dependencies on the exact version of the Microsoft compiler or any specific dependency on the c-library versions/build.  Should the c-libraries be the same ones used to build the installed Python itself, or does it matter?

When downloading and unzipping an ibm_db snapshot from github (python-ibmdb-master.zip), initially there is no pyd file present in that zipfile .  So it appears necessary to first run `python setup.py build` to cause a pyd file to be created. If that is true, the instructions should state it.

After `python setup.py build` created a pyd file, the full filename for me was:

\python-ibmdb-master\IBM_DB\ibm_db\build\lib.win-amd64-cpython-38\ibm_db.cp38-win_amd64.pyd


Your instruction is unclear for the renamed pyd file. 
You write "e.g ibm_db32_py27".   
A single example is insufficient without some additional explanatory text. 
Should the renamed pyd file not have any file-extension?  
What should be the full filename if the current installed Python version is 64-bit version 3.8 ?


What is the expected output (after copy + rename of the pyd file) of the `python setup.py build` ?
Should I expect lots of warnings "check.warn(importable)" ?

In which directory under site-packages should I expect to find the ibm_db.dll ?
In my case after `python setup.py install` , I see a directory created at:
c:\python\lib\site-packages\ibm_db-3.1.4-py3.8-win-amd64.egg  
but this directory does not contain any ibm_db.dll.

**Comment by Earammak** [comment]
@imavo 

Please explain if there are any dependencies on the exact version of the Microsoft compiler or any specific dependency on the c-library versions/build. Should the c-libraries be the same ones used to build the installed Python itself, or does it matter?
 -> I don't think we do have any other dependencies here.

Pre-built binaries we add during the release process, and they are available from pypi source distribution. 
When we install a package from pypi, we will be able to see the ibm_db_dll file under site-package.
This ibm_db_dll will created, when a prebuilt pyd exists.
In github as we don't have pre-built pyd, ibm_db_dll will not created and genated pyd will get copied to site-packages after "python setup.py install" command.

If you want to generate the ibm_db.dll from github repository, find the below steps.

When you run "python setup.py build " command , .pyd file will be created under build\lib.win-amd64-cpython-310 .

C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db>**python setup.py build**
C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db\build\lib.win-amd64-cpython-310>dir
09-01-2023  09:59    <DIR>          .
09-01-2023  09:59    <DIR>          ..
09-01-2023  09:57    <DIR>          certs
04-01-2023  14:09             2,640 ibmdb_tests.py
09-01-2023  09:59           117,760 **ibm_db.cp310-win_amd64.pyd**
04-01-2023  14:09            65,253 ibm_db_dbi.py
09-01-2023  09:57    <DIR>          ibm_db_tests
04-01-2023  14:09             7,403 testfunctions.py
               4 File(s)        193,056 bytes
               4 Dir(s)  343,644,549,120 bytes free

Now copy ibm_db.cp310-win_amd64.pyd to ibm_db directory.
C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db\build\lib.win-amd64-cpython-310>**copy ibm_db.cp310-win_amd64.pyd C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db**
        1 file(s) copied.

C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db>dir

09-01-2023  10:47    <DIR>          .
09-01-2023  10:47    <DIR>          ..
04-01-2023  14:09               214 .gitignore
09-01-2023  09:59    <DIR>          build
04-01-2023  14:09    <DIR>          certs
04-01-2023  14:09            18,879 CHANGES.md
04-01-2023  10:50             1,489 config.py
04-01-2023  14:09             1,463 config.py.sample
09-01-2023  09:59    <DIR>          dist
04-01-2023  14:09             2,640 ibmdb_tests.py
04-01-2023  14:09           480,036 ibm_db.c
09-01-2023  09:59           117,760 ibm_db.cp310-win_amd64.pyd
09-01-2023  09:59    <DIR>          ibm_db.egg-info
04-01-2023  14:09            15,277 ibm_db.h
04-01-2023  14:09            65,253 ibm_db_dbi.py
04-01-2023  14:12    <DIR>          ibm_db_tests
04-01-2023  14:09             9,219 LICENSE
04-01-2023  14:09               271 MANIFEST.in
04-01-2023  14:09             2,651 NOTES.md
04-01-2023  14:09                84 pyproject.toml
04-01-2023  14:09             9,680 README.md
04-01-2023  14:09             2,410 run_all_tests
04-01-2023  14:09             1,217 run_individual_tests
04-01-2023  14:09            23,900 setup.py
04-01-2023  14:09             7,403 testfunctions.py
04-01-2023  14:15    <DIR>          __pycache__
              18 File(s)        759,846 bytes
               8 Dir(s)  343,628,554,240 bytes free

C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db>
**Rename file format is:** ibm_db<32-bit or 64-bit os>_py<python version>.pyd
Ex : If you are using python 3.8 on 64-bit, the pyd file will be : ibm_db64_py38.pyd 

C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db>**rename ibm_db.cp310-win_amd64.pyd ibm_db64_py310.pyd**

C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db>dir
09-01-2023  10:48    <DIR>          .
09-01-2023  10:48    <DIR>          ..
04-01-2023  14:09               214 .gitignore
09-01-2023  09:59    <DIR>          build
04-01-2023  14:09    <DIR>          certs
04-01-2023  14:09            18,879 CHANGES.md
04-01-2023  10:50             1,489 config.py
04-01-2023  14:09             1,463 config.py.sample
09-01-2023  09:59    <DIR>          dist
04-01-2023  14:09             2,640 ibmdb_tests.py
04-01-2023  14:09           480,036 ibm_db.c
09-01-2023  09:59    <DIR>          ibm_db.egg-info
04-01-2023  14:09            15,277 ibm_db.h
09-01-2023  09:59           117,760 ibm_db64_py310.pyd
04-01-2023  14:09            65,253 ibm_db_dbi.py
04-01-2023  14:12    <DIR>          ibm_db_tests
04-01-2023  14:09             9,219 LICENSE
04-01-2023  14:09               271 MANIFEST.in
04-01-2023  14:09             2,651 NOTES.md
04-01-2023  14:09                84 pyproject.toml
04-01-2023  14:09             9,680 README.md
04-01-2023  14:09             2,410 run_all_tests
04-01-2023  14:09             1,217 run_individual_tests
04-01-2023  14:09            23,900 setup.py
04-01-2023  14:09             7,403 testfunctions.py
04-01-2023  14:15    <DIR>          __pycache__
              18 File(s)        759,846 bytes
               8 Dir(s)  343,626,006,528 bytes free

C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db>
After copy and rename, run python setup.py build
C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db>**python setup.py build**
[Note: If you get the error as "file ibm_db.py (for module ibm_db) not found", on run of python setup.py build. you can add ibm_db.py in ibm_db directory]

Run "python setpu.py install", will be able to generate ibm_db_dlls under the site-packages path.
C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db>python setup.py install 
C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db>
C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db>cd c:\program files\python310\lib\site-packages\ibm_db-3.1.4-py3.10.egg
c:\Program Files\Python310\Lib\site-packages\ibm_db-3.1.4-py3.10.egg>dir
09-01-2023  10:59    <DIR>          .
09-01-2023  10:59    <DIR>          ..
09-01-2023  10:59    <DIR>          certs
09-01-2023  10:59            18,879 CHANGES.md
09-01-2023  10:59             1,463 config.py.sample
09-01-2023  10:59    <DIR>          EGG-INFO
09-01-2023  10:59             2,640 ibmdb_tests.py
09-01-2023  10:59                 2 ibm_db.py
09-01-2023  10:59            65,253 ibm_db_dbi.py
09-01-2023  10:59    <DIR>          ibm_db_dlls       
09-01-2023  10:59    <DIR>          ibm_db_tests
09-01-2023  10:59             9,219 LICENSE
09-01-2023  10:59             9,680 README.md
09-01-2023  10:59             7,403 testfunctions.py
09-01-2023  10:59    <DIR>          __pycache__
               8 File(s)        114,539 bytes
               7 Dir(s)  343,634,948,096 bytes free
			   
c:\Program Files\Python310\Lib\site-packages\ibm_db-3.1.4-py3.10.egg>cd ibm_db_dlls

c:\Program Files\Python310\Lib\site-packages\ibm_db-3.1.4-py3.10.egg\ibm_db_dlls>dir
09-01-2023  10:59    <DIR>          .
09-01-2023  10:59    <DIR>          ..
09-01-2023  10:59           117,760 ibm_db.dll   <----- This is where dll is created
09-01-2023  10:59                 0 __init__.py
09-01-2023  10:59    <DIR>          __pycache__
               2 File(s)        117,760 bytes
               3 Dir(s)  343,633,899,520 bytes free

What is the expected output (after copy + rename of the pyd file) of the python setup.py build ?
Should I expect lots of warnings "check.warn(importable)" ?
 ->We expect ibm_db_dll will be created after run of "python setup.py install"
 ->We don't have to expect any warnings here.

**Comment by imavo** [comment]
You write:

> _After copy and rename, run python setup.py build
> C:\Tasks\test\python-ibmdb\IBM_DB\ibm_db>python setup.py build
> [Note: If you get the error as "file ibm_db.py (for module ibm_db) not found", on run of python setup.py build. you can add ibm_db.py in ibm_db directory]_

Yes, after copying and renaming the pyd file, and then running `python setup.py build` , I got an error as follows:

```
c:\Users\user1\Documents\python-ibmdb-master\IBM_DB\ibm_db>python setup.py build
Detected 64-bit Python
Detected platform = win32
Traceback (most recent call last):
  File "setup.py", line 374, in <module>
    _setWinEnv("PATH", "clidriver")
  File "setup.py", line 200, in _setWinEnv
    pyFile = open('ibm_db.py', 'r+')
FileNotFoundError: [Errno 2] No such file or directory: 'ibm_db.py'

```

you write that I must now copy ibm_db.py into the ibm_db directory, but you do not state where I should find the ibm_db.py file. 

Keep in mind that on the ms-windows machine, the ibm_db module has not been previously installed or built, so there is nothing in the site-packages directory at this time .  

Can you please revisit the instructions, to explain more clearly how to resolve the file not found for ibm_db.py if the machine performing the build has never had ibm_db installed on it previously or built on it.

**Comment by imavo** [comment]
@Earammak 

OK I get the DLL created now.

It would not be possible to guess that a zero length file needs to be created as part of the steps!

Now I begin to understand why this stuff is not formally documented, currently i would describe the process as messy and unfit for purpose.

I do hope that it is only a temporary situation while the project evolves. because in previous years no such nonsense was needed to build ibm_db from soruce-code on MS-Windows, only `pyyhon setup.py build` and `python setup.py install`.  

I hope that python ibm_db can get back to that build simplicity at some point without needing any hacking or file renaming or zero-length-files.

But for the moment I have at least one way to build on MS-Windows , even if it that method is messy. I can also revert to plain cl/link command-lines and scripted batch files .

You can close this ticket.
