### ISSUE TITLE
need support for SQL_ATTR_XML_DECLARATION

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb#796]
**Is your feature request related to a problem? Please describe.**

To allow the python programmer to control how the Db2-driver performs serialisation of XML columns/returned-parameters the python ibm_db module needs to support attribute `SQL_ATTR_XML_DECLARATION`.  This is for Db2-LUW at least.  At present, when an XML column, or XML output-parameter-from-a-stored-procedure gets serialised, the default behaviour of the IBM drivers is to prefix a byte-order-mark (example \ufeff) and an XML declaration (fo rexample: <?xml version="1.0" encoding="UTF-16" ?> ), and this can cause truncation of the retrieved payload.

**Describe the solution you'd like**

in module `ibm_db.c`  inside the function `INIT_ibm_db()`, the following line is necessary:

`  PyModule_AddIntConstant(m, "SQL_ATTR_XML_DECLARATION", SQL_ATTR_XML_DECLARATION);`

**Describe alternatives you've considered**

While in theory the addition of an equivalent option to either db2cli.ini or db2dsdriver.cfg should be possible, in practice this is awkward, frustrates the zero-config approach that present software-trends advocate. 
Additionally it is possible for programmers to add code to cope with both the BOM (byte order marker) and the XML-declatation (if the payload lacks that), but this is hostile to programmers perhaps.

**Additional context**

In the existing testcase file, `ibm_db_tests/test_52949_TestSPIntVarcharXml.py`, there is a disabled test for an XML output parameter from a storec procedure.  However, the call to run this test (self.text_xml()) is commented-out without any explanation. Consequently there is no current test case for XML output parameters, this seems careless.  By adding support for this new attribute (as suggested above) then simple adjustments to this testcase file will allow the test for XML output parameters to be re-instated, at least for DB2-LUW.  For example:

` options = {ibm_db.SQL_ATTR_XML_DECLARATION : 0}
   conn = ibm_db.connect(config.database, config.user, config.password, options)
`
followed by invoking the renamed testcase that is currently commented-out:

`    self.xtest_xml(conn) `

and adjusting the  expectation line:
`#__LUW_EXPECTED__
#ProcessXML: <example>This is an example</example>`

**Comment by Earammak** [comment]
@imavo, As part of new release we have given a support for this. Thanks
