### ISSUE TITLE
Exception: [IBM][CLI Driver] SQL10013N  The specified library "GSKit Error: 207" could not be loaded.  SQLSTATE=42724 SQLCODE=-10013

### ISSUE THREAD

**Issue by erland-ramadhan** [ibmdb/python-ibmdb#800]
First of all, I know that this issue has been resolved in #650 and #670. Still, it doesn't satisfy me since the given solution is not working on my MBP. I can connect to IBM DB2 Database through IBM Watson Studio or Google Colab but for some reason it is more comfortable to run jupyter notebook locally through my MBP.

Here are the details of the system.
- OS: macOS Big Sur 11.7
- Python Version: 3.9.12 (I use Conda environment installed from Intel OneAPI Base Toolkit)
- ibm_db version: 3.1.1 (installed through conda install -c conda-forge)
- the used clidriver comes from the installation of ibm_db through conda install

The error is always generated whether I use jupyter-notebook or python console. You can see it in the attached image.
<img width="1106" alt="Python_Console_Error" src="https://user-images.githubusercontent.com/48809651/198777961-aa8c5de2-ab86-41b3-b6a9-0426b349138a.png">

<img width="1144" alt="Jupyter_Notebook_Error" src="https://user-images.githubusercontent.com/48809651/198778173-89c856cf-c84d-43c2-ba55-b7d278d7d5ab.png">

**Comment by bimalkjha** [comment]
As per https://www.ibm.com/docs/en/spectrum-protect/8.1.9?topic=codes-global-security-kit-return, GSKit Error 207 means : 0x000000cf 207 GSK_ERROR_FIPS_NOT_SUPPORTED This installation of GSKit does not support FIPS mode of operation.

It indicates about issue with certificate file. Another reason may be that your system already has some older version of GSKit installed at "C:\Program Files\ibm\gsk8". If it is there, then it might be old. Better to rename this directory and then try. Thanks.
