### ISSUE TITLE
Failed to start the Kernel.  C:\Users\TECHNIFI\AppData\Roaming\Python\Python310\site-packages\traitlets\traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.   warn( C:\Users\TECHNIFI\AppData\Roaming\Python\Python310\site-packages\traitlets\traitlets.py:2366: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '8b1a2d2e-4eb2-4339-888d-8d1dc655bf9f' instead of 'b"8b1a2d2e-4eb2-4339-888d-8d1dc655bf9f"'.   warn( Bad address (C:\projects\libzmq\src\epoll.cpp:100).  View Jupyter [log](command:jupyter.viewOutput) for further details.

### ISSUE THREAD

**Issue by YasirSohailGujjar** [ibmdb/python-ibmdb#801]
- Operating System Name:
- db2level output from clidriver if in use:
- Target Db2 Server Version:
- Python Version:
- ibm_db version:
- For non-Windows, output of below commands:
  uname
  uname -m
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

1.
2.

**Comment by YasirSohailGujjar** [comment]
When I run pandas or any other library, my kernel is not working. Please to resolve this issue. I have windows 11 pro

**Comment by Earammak** [comment]
@YasirSohailGujjar Please provide the steps to reproduce the issue. And also share the information mentioned in issue template.
