### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified:

### ISSUE THREAD

**Issue by LuizSilvaDBA** [ibmdb/python-ibmdb#803]
- Operating System Name: Windows 2022
- db2level output from clidriver if in use:
```
(DBA tools) d:\Python_environments\dba_tools\venv>D:\temp\ntx64_odbc_cli\clidriver\bin\db2level
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11056" with level identifier "0607010F".
Informational tokens are "DB2 v11.5.6000.7091", "special_13806",
"DYN2201171140WIN64_13806", and Fix Pack "0".
Product is installed at "D:\temp\ntx64_odbc_cli\clidriver" with DB2 Copy Name
"IBM Data Server Driver For ODBC and CLI".
```
- Target Db2 Server Version: N/A
- Python Version:  3.9.13
- ibm_db version: 3.1.3

- Value of below environment variables if set:
  IBM_DB_HOME: D:\temp\ntx64_odbc_cli\clidriver
  PATH: d:\Python_environments\dba_tools\venv\Scripts;C:\Program Files\Python39\Scripts\;C:\Program Files\Python39\;C:\Program Files\Eclipse Adoptium\JDK 11 x64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\Git\cmd;C:\Program Files\Python\;C:\Program Files\Python\Scripts\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\PuTTY\;C:\Program Files\PowerShell\7\;D:\Program Files\IBM\SQLLIB\BIN;D:\Program Files\IBM\SQLLIB\FUNCTION;C:\Program Files\Microsoft VS Code\bin;C:\Users\adminldsilva\AppData\Local\Microsoft\WindowsApps;
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: D:\temp\ntx64_odbc_cli\clidriver

- Test script to reproduce the problem.

Steps to Reproduce:

1. In order to install ibm_db on a server without connectivity, I set the variable IBM_DB_HOME to D:\temp\ntx64_odbc_cli\clidriver\ I could successfully install ibm_db==3.1.3. Within the same CMD session, I tested "import ibm_db" and that worked well:
```
(DBA tools) d:\Python_environments\dba_tools\venv>python -m pip install --no-index --find-links=file:D:\temp\python_libraries\ ibm_db -v --log="log_ibm_db.txt"
Using pip 22.0.4 from d:\Python_environments\dba_tools\venv\lib\site-packages\pip (python 3.9)
Looking in links: file:///D:\temp\python_libraries\
Collecting ibm_db
  Using cached ibm_db-3.1.3-py3-none-any.whl
Installing collected packages: ibm_db
Successfully installed ibm_db-3.1.3

(DBA tools) d:\Python_environments\dba_tools\venv>python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> quit()
```

2. When I try to "import ibm_db" in a different CMD session where IBM_DB_HOME is not set, I get this error:
```
d:\Python_environments\dba_tools\venv>echo %IBM_DB_HOME%
%IBM_DB_HOME%

d:\Python_environments\dba_tools\venv>Scripts\activate

(DBA tools) d:\Python_environments\dba_tools\venv>python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Python_environments\dba_tools\venv\lib\site-packages\ibm_db.py", line 7, in <module>
    os.add_dll_directory(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'clidriver', 'bin'))
  File "C:\Program Files\Python39\lib\os.py", line 1111, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'd:\\Python_environments\\dba_tools\\venv\\lib\\site-packages\\clidriver\\bin'
>>> quit()
```
3. If I set the variable IBM_DB_HOME to the same location I used during the installation time, import works again:
```
(DBA tools) d:\Python_environments\dba_tools\venv>python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> quit()

(DBA tools) d:\Python_environments\dba_tools\venv>pip list
Package    Version
---------- -------
ibm-db     3.1.3
pip        22.0.4
setuptools 65.5.0

(DBA tools) d:\Python_environments\dba_tools\venv>python -V
Python 3.9.13
```

I checked d:\Python_environments\dba_tools\venv\lib\site-packages\ and the directory "clidriver" was not not copied there:
```
(DBA tools) d:\Python_environments\dba_tools\venv>dir d:\Python_environments\dba_tools\venv\lib\site-packages
 Volume in drive D is SysData
 Volume Serial Number is 02F4-05FE
 Directory of d:\Python_environments\dba_tools\venv\lib\site-packages

11/04/2022  04:46 PM    <DIR>          .
11/04/2022  04:41 PM    <DIR>          ..
11/04/2022  04:46 PM    <DIR>          certs
11/04/2022  04:44 PM               151 distutils-precedence.pth
11/04/2022  04:46 PM    <DIR>          ibm_db-3.1.3.dist-info
11/04/2022  04:46 PM               806 ibm_db.py
11/04/2022  04:46 PM            65,253 ibm_db_dbi.py
11/04/2022  04:46 PM    <DIR>          ibm_db_dlls
11/04/2022  04:46 PM    <DIR>          ibm_db_tests
11/04/2022  04:41 PM    <DIR>          pip
11/04/2022  04:42 PM    <DIR>          pip-22.0.4.dist-info
11/04/2022  04:44 PM    <DIR>          pkg_resources
11/04/2022  04:46 PM    <DIR>          Python_environments
11/04/2022  04:44 PM    <DIR>          setuptools
11/04/2022  04:44 PM    <DIR>          setuptools-65.5.0.dist-info
11/04/2022  04:46 PM             7,403 testfunctions.py
11/04/2022  04:46 PM             2,640 tests.py
11/04/2022  04:44 PM    <DIR>          _distutils_hack
11/04/2022  04:46 PM    <DIR>          __pycache__
               5 File(s)         76,253 bytes
              14 Dir(s)  14,109,302,784 bytes free

(DBA tools) d:\Python_environments\dba_tools\venv>
```

**Comment by imavo** [comment]
In any cmd session, when you have BOTH the IBM_DB_HOME variable undefined, AND the PATH and LIB variable values NOT-containing the clidriver\bin  and clidriver\lib respectively, then you will be unable to import ibm_db. 

 So choose which way you want to work. 
 
 With manual installation of clidriver, either make IBM_DB_HOME value persistent between cmd sessions, or make relevant changes to the PATH and LIB values to include clidriver\bin and clidriver\lib and have these values persist beteween cmd sessions.

**Comment by LuizSilvaDBA** [comment]
Wasn't IBM_DB_HOME supposed to be used during installation time only?
It seems also that something changed from 3.1.2 as the clidriver directory is not copied to the site-packages

**Comment by imavo** [comment]
When the ibm_db setup.py installs clidriver automatically, it places it into the site-packages location.

When installing clidriver manually, you are free to identify the site-packages directory and unpack the clidriver into that location. Additionally, the python ibm_db setup.py never changed the location of a manually installed driver (remember, other drivers are also usable, not only clidriver, but the full data-server-driver, or the i access odbc driver, and other drivers from non-ibm suppliers).

Yes, the readme file still mentions IBM_DB_HOME only in relation to automatically installing clidriver, but the readme file also mentions the need to adust PATH and LIB values (etc).

**Comment by LuizSilvaDBA** [comment]
"_When the ibm_db setup.py installs clidriver automatically, it places it into the site-packages location.
When installing clidriver manually, you are free to identify the site-packages directory and unpack the clidriver into that location_" 

For consistency sake, wouldn't make sense to have the same behaviour (copying the clidriver to site-packages) in both situations?  

The reason for that is that I would like to have a comparable installation process, either at my personal workstation or at stepping stone server that has no or limited access to the internet.

I'm fine to manually copy the clidriver if that solves the problem. I was just not sure whether or not that could break something later on (based on what's in the readme file and my limited knowledge on setuptools).

**Comment by imavo** [comment]
As multiple different CLI  providers are allowed to be used, it would seem to me to be a mistake (or even impossible ) for setup.py to be copying drivers around the file system.  

It seems cleaner to "use whatever is there already (i.e per IBM_DB_HOME) , or when IBM_DB_HOME is undefined then download and put clidriver into site-packages, OR  use the different approach below.

You are also free to set a different variable IBM_DB_INSTALLER_URL, to point to your own (offline) location from which to install clidriver. So why not experiment with that approach?

**Comment by Earammak** [comment]
@LuizSilvaDBA 
Since you have set IBM_DB_HOME to D:\temp\ntx64_odbc_cli\clidriver, when you install ibm_db clidriver will not be downloaded and it will pick from IBM_DB_HOME path.
And also, when you set clidriver path to PATH, clidriver will not be downloaded and that path will set to IBM_DB_HOME.

The clidriver will not be available under site-packages in both the above-mentioned cases.

When you open different command prompt, the same environment variables will not be available. 
import ibm_db is trying pick the clidriver from site-packages, because we set environment variable during install of ibm_db, clidriver will not be there under site-packages.

Please refer to "https://www.askpython.com/python/environment-variables-in-python " on How to Environment variable in Python.

Thanks

**Comment by mobile-safari** [comment]
https://romeo-idealism.github.io/Zs9yhlJcd2QDvmkjYESBgwRCOVcA4Z9PRwDLIHe61RhQp/



The solution is in sight
