### ISSUE TITLE
Follow up question for Issue #811

### ISSUE THREAD

**Issue by gngrossi** [ibmdb/python-ibmdb#815]
How do I determine if our xlc.cfg options below were used during the compile?
thanks

options = -qarch=13,-qoptimize=2

**Comment by Earammak** [comment]
@gngrossi I have not done these .cfg setting to compile. I'm not sure how you set these settings to compile. Thanks

**Comment by gngrossi** [comment]
The default config file is /usr/lpp/cbclib/xlc/etc/xlc.cfg
I copied it to my home directory and added the options statement.  
Also used the env variable for the install.  export XL_CONFIG="$HOME/c/xlc.cfg"

Here is the common section of the xlc.cfg:
* common definitions
DEFLT:        cppcomp           = /usr/lpp/cbclib/xlc/exe/ccndrvr
              ccomp             = /usr/lpp/cbclib/xlc/exe/ccndrvr
              ipacomp           = /usr/lpp/cbclib/xlc/exe/ccndrvr
              ipa               = /bin/c89
              as                = /bin/c89
              ld_c              = /bin/c89
              ld_cpp            = /bin/cxx
              xlC               = /usr/lpp/cbclib/xlc/bin/xlc
              xlCcopt           = -D_XOPEN_SOURCE
              sysobj            = sys1.sceeobj:sys1.sceecpp
              syslib            = sys1.sceelkex:sys1.sceelked:sys1.sccnobj:sys1.csslib
              syslib_x          = sys1.sceebnd2:sys1.sccnobj:sys1.csslib
              exportlist_c      = NONE
              exportlist_cpp    = sys1.sceelib(c128n):sys1.sclbsid(iostream,complex)
              exportlist_c_x    = sys1.sceelib(celhs003,celhs001)
              exportlist_cpp_x  = sys1.sceelib(celhs003,celhs001,celhscpp,c128):sys1.sclbsid(iostream,complex)
              exportlist_c_64   = sys1.sceelib(celqs003)
              exportlist_cpp_64 = sys1.sceelib(celqs003,celqscpp,c64):sys1.sclbsid(iosx64)
              steplib           = sys1.sccncmp
              options           = -qarch=13,-qoptimize=2,-I/global/zopentools/pyz/usr/lpp/IBM/cyp/v3r10/pyz/include/python3.10,-L/global/zopentools/pyz/usr/lpp/IBM/cyp/v3r10/pyz/lib

**Comment by Earammak** [comment]
@gngrossi May i know the purpose of keeping this config into xlc.cfg ? Anything specific to driver we can help you, for zos configuration you can contact to zos team.

**Comment by bimalkjha** [comment]
@gngrossi Check the install command output in detail and find the xlc command used to compile ibm_db.c file along with ODBC headers. You can see the applied options there. Thanks.

**Comment by bimalkjha** [comment]
Install ibm_db using "pip3 install ibm_db --verbose" command to see the detailed output. Look for xlc command as below that would show all of the options used:
/bin/xlc -DNDEBUG -O3 -qarch=13 -qoptimize=2 -qlanglvl=extc99 -q64 -Wc,DLL -D_XOPEN_SOURCE_EXTENDED -D_UNIX03_THREADS -D_POSIX_THREADS -D_OPEN_SYS_FILE_EXT -qexportall -qascii -qstrict -qnocsect -Wa,asa,goff -Wa,xplink -qgonumber -qenum=int -I/u/@02858/tmp/pip-install-6tuix_kp/ibm-db_7671a777c01448f8a7e2e95430076e13/sdsnc.h -I/usr/lpp/IBM/cyp/v3r10/pyz/include/python3.10 -c ibm_db.c -o build/temp.os390-27.00-8561-cpython-310/ibm_db.o

**Comment by gngrossi** [comment]
I ran  pip3 uninstall ibm_db --verbose

bash-5.1$ pip3 install ibm_db --verbose
Using pip 22.3.1 from /global/zopentools/pyz/usr/lpp/IBM/cyp/v3r10/pyz/lib/python3.10/site-packages/pip (python 3.10)
Collecting ibm_db
  Using cached ibm_db-3.1.4-cp310-cp310-os390_27_00_8561.whl
Installing collected packages: ibm_db
Successfully installed ibm_db-3.1.4

What do I need to remove to be able to recompile?

# ibm_db packages
/global/zopentools/pyz/usr/lpp/IBM/cyp/v3r10/pyz/lib/python3.10/site-packages/
ibm_db-3.1.4.dist-info
ibm_db.cpython-310.so
ibm_db_dbi.py
ibm_db_dlls
ibm_db_tests
ibmdb_tests.py

thanks

**Comment by bimalkjha** [comment]
@gngrossi As per pip [documentation](https://pip.pypa.io/en/stable/topics/caching/#disabling-caching), you need to use `--no-cache-dir` option to avoid installation from cache. So, use `pip3 install ibm_db --no-cache-dir --verbose` command. Thanks.

**Comment by gngrossi** [comment]
The command line seems to be overriding the options from xlc.cfg
options           = -qarch=13,-qoptimize=2,-I/global/zopentools/pyz/usr/lpp/IBM/cyp/v3r10/pyz/include/python3.10,-L/global/zopentools/pyz/usr/lpp/IBM/cyp/v3r10/pyz/lib

After uninstalling and running pip3 install ibm_db --no-cache-dir --verbose

  /bin/xlc -DNDEBUG -O3 -qarch=10 -qlanglvl=extc99 -q64 -Wc,DLL -D_XOPEN_SOURCE_EXTENDED -D_UNIX03_THREADS -D_POSIX_THREADS -D_OPEN_SYS_FILE_EXT -qexportall -qascii -qstrict -qnocsect -Wa,asa,goff -Wa,xplink -qgonumber -qenum=int -I/u/@02858/tmp/pip-install-2rw8ghmk/ibm-db_dbc9a5d8d45a4437931aad02289e3f63/sdsnc.h -I/global/zopentools/pyz/usr/lpp/IBM/cyp/v3r10/pyz/include/python3.10 -c ibm_db.c -o build/temp.os390-27.00-8561-3.10/ibm_db.o
  WARNING CCN3236 /usr/include/unistd.h:1169  Macro name _POSIX_THREADS has been redefined.
  WARNING CCN3068 ./ibm_db.c:5889  Operation between types "unsigned short*" and "char*" is not allowed.
  WARNING CCN3068 ./ibm_db.c:5895  Operation between types "unsigned short*" and "char*" is not allowed.
  WARNING CCN3068 ./ibm_db.c:5902  Operation between types "unsigned short*" and "char*" is not allowed.

  /bin/xlc build/temp.os390-27.00-8561-3.10/ibm_db.o /u/@02858/tmp/pip-install-2rw8ghmk/ibm-db_dbc9a5d8d45a4437931aad02289e3f63/libdsnao64c.x -L. -L. -o build/lib.os390-27.00-8561-3.10/ibm_db.cpython-310.so -Wl,dll /global/zopentools/pyz/usr/lpp/IBM/cyp/v3r10/pyz/lib/python3.10/config-3.10/libpython3.10.x -q64

  installing to build/bdist.os390-27.00-8561/wheel
  running install
  running install_lib
  creating build/bdist.os390-27.00-8561
  creating build/bdist.os390-27.00-8561/wheel

thanks

**Comment by bimalkjha** [comment]
@gngrossi ibm_db executes setup.py file for compilation. If you check setup.py, it calls setuptools.command.install() to compile the code using various options. It is inbuild module of python and you can find it as `site_packages/setuptools/command/install.py`. Under command directory, you can grep for xlc and see what options it is using during compilation.
If command line is overriding options from xlc.cfg, then it should be install.py which is overriding. That means, it gets overridden by python itself.
@rharriszzz Could you please comment on this issue? Thanks.

**Comment by bimalkjha** [comment]
@gngrossi We have provided all info as we can. Can we close the issue now? Thanks.

**Comment by gngrossi** [comment]
In the future, I would suggest install.py not use arch/optimize so the defaults would be in effect unless overridden by xlc.cfg.
If nothing else can be done, this issue can be closed.
thanks
