### ISSUE TITLE
Malloc Error when using db2_engine.connect() 

### ISSUE THREAD

**Issue by j-mon** [ibmdb/python-ibmdb#820]
- Operating System Name: MacOS Ventura
- db2level output from clidriver if in use:
- Target Db2 Server Version:
- Python Version: 3.9.16
- ibm_db version: 3.1.4
- For non-Windows, output of below commands:
  unam: Darwin
  uname -m: arm64
- Value of below environment variables if set:
  IBM_DB_HOME: None 
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: None

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Python Path: /Users/jeffreymonsalve/Desktop/code/modernity-backend/venv/bin/python

Steps to Reproduce:

1. Install 
2.
![Screenshot 2023-01-12 at 10 10 02 AM](https://user-images.githubusercontent.com/26562506/212103499-16433913-52e7-4bbb-8eed-46c115ee4a90.png)

**Comment by moria58** [comment]
Hi @j-mon 
I'm having the same error and I'm stuck.
If so, could you please tell me how you solved it?

**Comment by bimalkjha** [comment]
@moria58 Follow instructions as commented here: https://github.com/ibmdb/python-ibmdb/issues/786#issuecomment-1238536308
