### ISSUE TITLE
Installation Issue: Mac OS Monterey - Requirements to build wheel

### ISSUE THREAD

**Issue by think-jschaefer** [ibmdb/python-ibmdb#821]
I am encountering an installation error.

- Operating System Name: MacOS Monterey 12.6
- db2level output from clidriver if in use: N/A
- Target Db2 Server Version: N/A
- Python Version: 3.9.6
- ibm_db version: N/A
- For non-Windows, output of below commands:
  uname
`Darwin`
  uname -m
`x86_64`
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- For installation related issue, complete output of `pip install ibm_db` command.

`(venv) jackschaefer_ibm@Jacks-MBP apache_superset % pip install ibm_db
Collecting ibm_db
  Using cached ibm_db-3.1.4.tar.gz (1.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Detected 64-bit Python
      Detected platform = darwin, uname = x86_64
      Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz
       Downloading DSDriver from url =  https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz
      Pre-requisite check [gcc] : Passed
      
      No Python.h header file detected.
      Please install python-devel or python3-devel as instructed in "https://github.com/ibmdb/python-ibmdb/blob/master/README.md#KnownIssues" and continue with the installation
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

The above output directs me to a known issues page. However, I am not seeing material about installing python-devel or python3-devel.

Thank you.

**Comment by Earammak** [comment]
@think-jschaefer, From the log it says that you need to install python3-devel or python-devel. May be python is not installed properly in your machine. Please re-install python and install ibm_db in verbose mode.

Thanks

**Comment by think-jschaefer** [comment]
@Earammak is there a specific package for python3-devel or python-devel? I do not know what you are referring to. I am not seeing anything under Pip. Thank you.

Python has been running well on my machine - I am currently running a Flask App with no issues. I suppose I can try reinstalling it.

**Comment by think-jschaefer** [comment]
Issue fixed! Fully installing Xcode solved the issue. Previosly, I only had Xcode command lines tools installed. But the full installation of Xcode was necessary.

This makes sense, as a Python.h header file is related to a C++ lang. Xcode provides dev tools for C++.
