### ISSUE TITLE
V3.1.0 -  "result with an error set" returned by columns() function  on z/OS system

### ISSUE THREAD

**Issue by pjfarleyiii** [ibmdb/python-ibmdb#822]
- Operating System Name:  z/OS V2.4
- db2level output from clidriver if in use: N/A
- Target Db2 Server Version: z/OS DB2 V12 (DSNC10)
- Python Version: 3.9.2
- ibm_db version: 3.1.0
- pip3 list showing version:  
```
> pip3 list
Package            Version
------------------ ---------
. . . . (other entries in list)
ibm-db             3.1.0
```
- For non-Windows, output of below commands:
  uname   OS/390
  uname -m 3906
- Value of below environment variables if set:
  IBM_DB_HOME:   IBM_DB_HOME=DSNC10
  PATH: /usr/lpp/IBM/cvg/go/bin:/usr/lpp/IBM/cyp/v3r9/pyz/bin:/usr/lpp/IBM/zoautil/bin:/usr/lpp/db2c10/jdbc/bin:/bin:/z/bin:.:/usr/lpp/java/J8.0_64/bin:/usr/lpp/zLiberty/V8R5/wlp/bin:/z/z02446/bin:/z/rocket/tools/bin:/usr/lpp/ported/bin:/usr/lpp/IBM/cnj/v16r0/IBM/node-latest-os390-s390x/bin:/usr/lpp/IBM/cnj/v16r0/njsc/bin:/global/node/bin
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:
LD_LIBRARY_PATH=/usr/lpp/db2c10/jdbc/lib
- Test script to reproduce the problem.
```
home_dir> python3
Python 3.9.2 (heads/pyz_dev-3.9:91bcbd3bc6, Apr 15 2021, 02:47:09) on zos
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> conn = ibm_db.connect("","","")
>>> print(ibm_db.columns(conn,None,"%","SYSCOLUMNS"))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in function columns> returned a result with an error set
>>>
```

Steps to Reproduce:

1. Connect to DB2
2. print column names using ibm_db.columns function for any known DB2 table name

Additional comments:
This is happening on the IBM zXplore z/OS system.  I do not have admin access to that system so I cannot provide any admin-only answers, but I wish to know if this issue has been resolved in a later version of the ibm_db python package so that I can request the admins at zXplore to upgrade to a corrected version.

Possibly related is that the field_name() function also consistently fails on this system.  Below is an output from a more complete script showing the error set returned from the columns() function and the error always returned from the field_name() function.

[db_fetch_name_err.py.txt](https://github.com/ibmdb/python-ibmdb/files/10477019/db_fetch_name_err.py.txt)

```
> python3 db_fetch_name_err.py
Test start field_name
Connection done
columns failed:
{DB2 FOR OS/390}{ODBC DRIVER}{DSN12015}
 DSNT408I SQLCODE = -805, ERROR:  PACKAGE NAME DALLASC..DSNCLIMS.1B6FA18B1B634B-
          60 NOT FOUND IN PLAN DSNACLI. REASON 03
 DSNT418I SQLSTATE   = 51002 SQLSTATE RETURN CODE
 DSNT415I SQLERRP    = DSNXEPM SQL PROCEDURE DETECTING ERROR
 DSNT416I SQLERRD    = -251  0  0  -1  0  0 SQL DIAGNOSTIC INFORMATION
 DSNT416I SQLERRD    = X'FFFFFF05'  X'00000000'  X'00000000'  X'FFFFFFFF'
          X'00000000'  X'00000000' SQL DIAGNOSTIC INFORMATION
  ERRLOC=5:10:2 SQLCODE=-805

exec_immediate done
first fetch done
row 1 returned 3 columns: Traceback (most recent call last):
  File "/z/z02446/db_fetch_name_err.py", line 41, in <module>
    colname = ibm_db.field_name(stmt, _i)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 0: ordinal not in range(128)
```

**Comment by Earammak** [comment]
@pjfarleyiii Can you please check with the latest ibm_db[3.1.4] instead of 3.1.0.

**Comment by pjfarleyiii** [comment]
@Earammak, no, I am sorry I cannot try with latest 3.1.4, as I have no authority to install or replace software on the IBM Zxplore z/OS system.  I can ASK the admins there to replace 3.1.0 with 3.1.4, but I cannot do it myself.  Also they do not have venv installed, so I cannot even set up a private virtual environment in which to try 3.1.4, even if they allowed normal users enough disk quota to set up a virtual environment (they do not).  It is a "learning" system, not a real development system.

Can you tell me if errors like the ones I described above are resolved in 3.1.4?  That MIGHT be sufficient reason for the admins on the system to agree to an upgrade, though I won't hold my breath waiting for them to actually do it.  System-level changes seem to take quite a while to accomplish there.

**Comment by Earammak** [comment]
@pjfarleyiii, It is working in my environment using latest version of ibm_db [3.1.4].
Kindly ask your admin to install latest version of ibm_db [ 3.1.4].
The following is the working output for reference:

bash-4.3$ python3
Python 3.9.5 (heads/pyz_dev-3.9:7cc8dd352f, Nov  2 2021, 05:50:11) on zos
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db
>>> conn=ibm_db.connect(" ",' ',' ')
>>> print(ibm_db.columns(conn,None,"%","SYSCOLUMNS"))
<ibm_db.IBM_DBStatement object at 0x5008909CE0>
>>>
>>> ibm_db.__version__
'3.1.4'
>>>


Thanks

**Comment by pjfarleyiii** [comment]
I will do that.  Thank you for the confirmation that 3.1.4 fixes the issue.  I will close this issue.
