### ISSUE TITLE
Symbol not found: ___cxa_throw_bad_array_new_length

### ISSUE THREAD

**Issue by BigNerd** [ibmdb/python-ibmdb#824]
When installing ibm_db==3.1.3 into a python3.7 virtual environment on macOS BigSur 11.6 Intel Core i7
the setup.py included in ibm_db-3.1.3.tar.gz in turn downloads https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz
and the latter has been modified on 2023-02-01 (seemingly without creating a new version of ibm_db).

It seems this is the reason for now getting an error message which did not occur in previous installations of the same ibm_db==3.1.3 before 2023-02-01.

The error message happens when executing the following code

`import ibm_db`

The error message is this:

`ImportError: dlopen(/Users/my_user/my_project/venv/lib/python3.7/site-packages/ibm_db.cpython-37m-darwin.so, 2): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: /Users/my_user/my_project/venv/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib
  Expected in: /usr/lib/libstdc++.6.dylib`

The same error occurs when installing the latest release ibm_db==3.1.4.

**Comment by Earammak** [comment]
@BigNerd You need to Uninstall and reinstall ibm_db after deleting site_packages\clidriver directory. Please refer to #804 
Thanks

**Comment by BigNerd** [comment]
@Earammak thank you for taking care. I did the following but it produced the same error again:

1. deleted my complete local pip cache at /Users/my_user/Library/Caches/pip
2. created and activated a fresh python 3.7 virtual environment
3. pip install ibm-db==3.1.4

Looking in indexes: https://pypi.org/simple
Collecting ibm_db
  Downloading ibm_db-3.1.4.tar.gz (1.4 MB)
  ━━━━━━━━━━━━ 1.4/1.4 MB 13.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: ibm_db
  Building wheel for ibm_db (pyproject.toml) ... done
  Created wheel for ibm_db: filename=ibm_db-3.1.4-cp37-cp37m-macosx_11_0_x86_64.whl size=33037542 sha256=47dd6caff9566633d3be85d11562bbfd4490fa620d0358f23ad2ca6c652f5e67
  Stored in directory: /Users/my_user/Library/Caches/pip/wheels/b8/f6/b9/4721575c570737ed498fbb6f5d62d4eda39990dcd4ef1e8c6e
Successfully built ibm_db
Installing collected packages: ibm_db
Successfully installed ibm_db-3.1.4

4. python -c 'import ibm_db'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/my_user/my_project/venv/lib/python3.7/site-packages/ibm_db.cpython-37m-darwin.so, 2): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: /Users/my_user/my_project/venv/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib
  Expected in: /usr/lib/libstdc++.6.dylib
 in /Users/my_user/my_project/venv/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib

**Comment by Earammak** [comment]
@BigNerd Have you tried referring to similar issue [ex: #786, #774]? 

Thanks

**Comment by BigNerd** [comment]
@Earammak thank you for your patience. I have looked at the two issues you have mentioned, but admittedly it is not easy for me to derive the solution from them. What I have tried now is the sequence of commands suggested in https://github.com/ibmdb/python-ibmdb/issues/774#issuecomment-1239791989. Hope this sheds some light on it.

Please note I have an old environment on my machine where everything still works as desired. This old environment has been installed some time ago. Any new environment I am installing shows the mentioned problem, though.

If I execute the following in the old working environment I am getting this:
```
site-packages % otool -L ibm_db.cpython-37-darwin.so                                                                           
error: /Library/Developer/CommandLineTools/usr/bin/otool-classic: can't open file: ibm_db.cpython-37-darwin.so (No such file or directory)

site-packages % otool -L clidriver/lib/libdb2.dylib        
clidriver/lib/libdb2.dylib:
        libdb2.dylib (compatibility version 0.0.0, current version 0.0.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
        @loader_path/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
        @loader_path/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

If I execute the following in the new non-working environment I am getting this:

```
site-packages % otool otool -L ibm_db.cpython-37-darwin.so
error: /Library/Developer/CommandLineTools/usr/bin/otool-classic: can't open file: otool (No such file or directory)
error: /Library/Developer/CommandLineTools/usr/bin/otool-classic: can't open file: ibm_db.cpython-37-darwin.so (No such file or directory)

site-packages % otool -L clidriver/lib/libdb2.dylib       
clidriver/lib/libdb2.dylib:
        libdb2.dylib (compatibility version 0.0.0, current version 0.0.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/local/lib/gcc/8/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
        /usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

So there is a difference between the two in that for two of the .dylib files the path is displayed differently. In the old and working it is starting with **@loader_path** whereas in the new non-working it is starting with **/usr/local/lib/gcc/8**.

**Comment by Earammak** [comment]
@BigNerd From your shared output, why ibm_db.cpython-37-darwin.so not there in both cases?
                  Please share the below commands output also:
                 cd /Users/my_user/my_project/venv/lib/python3.7/site-packages
                 ls 
                 echo $DYLD_LIBRARY_PATH
                 echo $PATH
                 ls /usr/local/lib/gcc
                 db2level
Thanks

**Comment by BigNerd** [comment]
@Earammak I can now see that ibm_db.cpython-37-darwin.so is not found because in my site-packages directory the file is named slightly differently (an extra letter 'm' after 37):

otool -L ibm_db.cpython-37**m**-darwin.so 
```
ibm_db.cpython-37m-darwin.so:
        @loader_path/clidriver/lib/libdb2.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
```

**Comment by bimalkjha** [comment]
@BigNerd We have added @loader_path in library and updated macos64_odbc_cli.tar.gz. Please run below commands from terminal and verify:
```
rm -rf /Users/my_user/my_project/venv/lib/python3.7/site-packages/clidriver
pip uninstall ibm_db
pip install ibm-db==3.1.4 --no-cache-dir
```
Must use `--no-cache-dir` option with pip to avoid cache. If still you see issue, then share output of below commands:
```
ls /usr/local/lib/gcc/
ls -l /usr/lib/libstdc++.6.dylib
db2level
```
Thanks.

**Comment by BigNerd** [comment]
@Earammak please make sure you have seen my previous comment, adding more information in this comment now.

As the difference between the working and the non-working environment is in the references from `clidriver/lib/libdb2.dylib` to `libstdc++.6.dylib` and to `libgcc_s.1.dylib`, I have checked the following:

```
site-packages % ls /usr/local/lib/gcc/8/libstdc++.6.dylib
ls: /usr/local/lib/gcc/8/libstdc++.6.dylib: No such file or directory
```
```
site-packages % ls /usr/local/lib/gcc/11/libstdc++.6.dylib
/usr/local/lib/gcc/11/libstdc++.6.dylib
```

Can you guess or even explain how this kind of state has arisen on a system like mine? Is it rooted in the installation procedure of ibm_db or is it due to my general enviroment not adhering to assumed standards?

Naively, I should think, ibm_db would be less error prone if it brought all required dylib files with it and kept all its references local to them rather than pointing into the wider environment of the machine where it in these cases does not hit the targets for some odd reason.

**Comment by BigNerd** [comment]
@bimalkjha thanks a lot for fixing my problem by updating https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz.

Now it works again!

**Comment by jamsden** [comment]
I cannot get ibm_db working on an M1 MacBook Pro running macOS 13.4. I think the issue is that I don't have the correct version of gcc.  What version of gcc do I need for what architecture? Version 11 for x86_64? If so, how is that installed on an M1 mac?

`brew install gcc@11`

Works, but installs: in /opt/homebrew/bin, not /usr/local/bin and:
```
/opt/homebrew/bin/gcc-11 --version
gcc-11 (Homebrew GCC 11.4.0) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Is this OK? Or do I have the wrong gcc installed in the wrong place?

Do I need Applications/dsdriver from v11.5.8_macos_dscriver.dmg from [IBM FixCentral](https://www.ibm.com/support/fixcentral/swg/downloadFixes?parent=ibm%7EInformation%20Management&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=11.5.*&platform=All&function=fixId&fixids=DSClients-115-macos-RECOMMENDED&includeRequisites=1&includeSupersedes=0&downloadMethod=http&login=true)? Or does installing ibm_db take care of installing the correct drivers in the virtual environment?

I am using Python 3.9.13 which is  Mach-O 64-bit executable x86_64. Is that correct? 

If I get the right gcc with the right python in my virtual environment, then pip install ibm_db, do I still need to set the DYLD_LIBRARY_PATH?

**Comment by bimalkjha** [comment]
@jamsden Better to open a new issue with all details as this issue is closed.

> Do I need Applications/dsdriver from v11.5.8_macos_dscriver.dmg from [IBM FixCentral](https://www.ibm.com/support/fixcentral/swg/downloadFixes?parent=ibm%7EInformation%20Management&product=ibm/Information+Management/IBM+Data+Server+Client+Packages&release=11.5.*&platform=All&function=fixId&fixids=DSClients-115-macos-RECOMMENDED&includeRequisites=1&includeSupersedes=0&downloadMethod=http&login=true)? Or does installing ibm_db take care of installing the correct drivers in the virtual environment?

Answer: installing ibm_db take care of  installing the correct drivers in the virtual environment. ibm_db downloads `site_packages/clidriver` automatically during install time.

>  I am using Python 3.9.13 which is Mach-O 64-bit executable x86_64. Is that correct?

Answer: The error message in the output says you have installed arm64 version of python not x86_64. Please read the output of importError. 
If you have installed x86_64 python, please share the location.

> If I get the right gcc with the right python in my virtual environment, then pip install ibm_db, do I still need to set the DYLD_LIBRARY_PATH

Answer: No.

Please follow the installation steps as documented [here](https://github.com/ibmdb/python-ibmdb/issues/835#issuecomment-1503772903) and share output of below commands. gcc@11 is also fine. ibm_db works with gcc>=8.4.3.
```
gcc -v   => Output should have x86_64
python --version   or python3 --version
file `which python` or file `which python3`   => Output should have x86_64
cd site_packages/clidriver/lib
otool -L libdb2.dylib
full path of libstdc++.6.dylib in your system from gcc installed dir like /usr/local/Homebrew/Cellar/gcc@12/12.3.0/lib/gcc/12/libstdc++.6.dylib
```
Thanks.

**Comment by idb-db-needs-jesus** [comment]
Can't believe in this day and age this issue still persists
