### ISSUE TITLE
incorrect install / incorrect assumptions

### ISSUE THREAD

**Issue by klaasbrant** [ibmdb/python-ibmdb#825]
- Operating System Name: WIN 11
- db2level output from clidriver if in use:

C:\Program Files\IBM\IBM DATA SERVER DRIVER\bin>db2level  <====
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11050" with level identifier "0601010F".
Informational tokens are "DB2 v11.5.0.1077", "s1906101300",
"DYN1906101300WIN64", and Fix Pack "0".
Product is installed at "C:\PROGRA~1\IBM\IBMDAT~1" with DB2 Copy Name
"IBMDBCL1".

- Target Db2 Server Version:  db2 linux 11.5
- Python Version: 3.11.1 virtual environment <===
- Value of below environment variables if set:
  IBM_DB_HOME: NOT SET!
  PATH:

PATH=D:\Python\db2mon_old\venv\Scripts;C:\Program Files\ibm\gsk8\lib64;C:\Program Files\ibm\gsk8\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Calibre2\;C:\PROGRA~1\IBM\IBMDAT~1\BIN;C:\Program Files (x86)\Lua\5.1;C:\Program Files (x86)\Lua\5.1\clibs;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\PDFtk\bin\;C:\Program Files\Microsoft OLE DB Provider for DB2\system;C:\Program Files\nodejs\;C:\Users\kbran\AppData\Local\Microsoft\WindowsApps;C:\Users\kbran\AppData\Local\GitHubDesktop\bin;C:\Users\kbran\.dotnet\tools;C:\Users\kbran\AppData\Roaming\npm;c:\hugo\bin;C:\Program Files (x86)\SPFLite2;C:\Program Files\dotnet\;C:\Program Files\usbipd-win\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\AOMEI\AOMEI Backupper 6.4.0;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Docker\Docker\resources\bin;C:\Users\kbran\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\kbran\AppData\Local\Programs\Python\Python311\;C:\Users\kbran\scoop\shims;D:\zos\Hercprt\FishLib

- Test script to reproduce the problem.

 Any use of the python ibm_db module fails

- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

(venv) D:\Python\db2mon_old>set IBM_DB_HOME=   <== make sure it is not set
(venv) D:\Python\db2mon_old>pip install ibm_db
Collecting ibm_db
  Using cached ibm_db-3.1.4.tar.gz (1.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: ibm_db
  Building wheel for ibm_db (pyproject.toml) ... done
  Created wheel for ibm_db: filename=ibm_db-3.1.4-py3-none-any.whl size=329659 sha256=f573466e587390faa0567c641e81a79e97c6518d50f5e2d903d63b33d57f9107
  Stored in directory: c:\users\kbran\appdata\local\pip\cache\wheels\13\59\9e\b4ce7cb280c4fa6ad284bd69d5fb74607277954dcfee700509
Successfully built ibm_db
Installing collected packages: ibm_db
Successfully installed ibm_db-3.1.4

When using in application:
import ibm_db
  File "D:\Python\db2mon_old\venv\Lib\site-packages\ibm_db.py", line 7, in <module>
    os.add_dll_directory(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'clidriver', 'bin'))
  File "<frozen os>", line 1119, in add_dll_directory
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\Python\\db2mon_old\\venv\\Lib\\site-packages\\clidriver\\bin'

I have data server driver installed (see above) but during pip install IBM_DB_HOME was NOT set, yet it did not install the driver in the site packages.

I can bypass the problem by doing:
set IBM_DB_HOME="C:\Program Files\IBM\IBM DATA SERVER DRIVER"  <== double quotes importent!!
and then the application runs fine.

So, pip install forget to install the driver even if host var is not set.
BUT that brings me to a bigger problem.  I think the driver should ALWAYS be included in the site package directory and always be used from there. This is the whole point of a virtual environment, so you never depend on anything outside the virtual environment.
For example, let's say I continue with my "bypass" and I develop and test the application. If I am ready to deploy in a docker container then let's assume the pip install works correctly and includes the clidriver. Then I might deploy in production a different driver which could respond differently and make the application fail.

The python ecosystem (including virtual env) says that if I say pip instal xyz=1.0.0 then I get version 1.0.0 of xyz and nor maybe something different because of a hostvar or the install procedure is inventive and figures out there is something else out there it starts to use.

I strongly suggest the install follows the python rules.

**Comment by Earammak** [comment]
_@klaasbrant, Yes, it is an incorrect assumption that IBM_DB_HOME will set automatically while installing ibm_db.
  When <clidriver path> is set to PATH in a machine, then we have to set manually IBM_DB_HOME path to the same <clidiver path>. then install ibm_db driver.
You will not get FileNotFoundError when IBM_DB_HOME is set to <clidriver path> before running "import ibm_db".

We have added this update in Readme.md file.

Thanks

**Comment by bimalkjha** [comment]
@klaasbrant Updated doc with prerequisite to set IBM_DB_HOME if a db2 client is already installed in the system and PATH is set, i.e. if db2level works. Also, this message will come when installing with -v option. I think this should be fine. Hence, closing the issue now. Thanks.
