### ISSUE TITLE
Unable to connect:  [IBM][CLI Driver] SQL1336N  The remote host "ea286ace-86c7-4d5b-8580-3fbfa46b1c66.bs2io90l08kqb1od8lcg.databases.ap" was not found.  SQLSTATE=08001 SQLCODE=-1336

### ISSUE THREAD

**Issue by ugeer** [ibmdb/python-ibmdb#826]
- Operating System Name:
- db2level output from clidriver if in use:
- Target Db2 Server Version:
- Python Version:
- ibm_db version:
- For non-Windows, output of below commands:
  uname
  uname -m
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

1.
2.

**Comment by Earammak** [comment]
@ugeer Can you please share the above information?
Thanks

**Comment by bimalkjha** [comment]
@ugeer It really does not exist. Are you able to ping ea286ace-86c7-4d5b-8580-3fbfa46b1c66.bs2io90l08kqb1od8lcg.databases.ap? Try using the ip address of this host in connection string.
```
C:\Users\bjha>ping ea286ace-86c7-4d5b-8580-3fbfa46b1c66.bs2io90l08kqb1od8lcg.databases.ap
Ping request could not find host ea286ace-86c7-4d5b-8580-3fbfa46b1c66.bs2io90l08kqb1od8lcg.databases.ap. Please check the name and try again.

C:\Users\bjha>
```
If you face issue using IP Address also, then provide all the info in the issue template as requested by earammak.
Thanks.

**Comment by bimalkjha** [comment]
Closing the issue due to lack of response. We can reopen it if you are still facing the issue and share more info here. Thanks.

**Comment by epetecof** [comment]
Hello bimalkjha, saw this on Google and I'm having the same issue. The thing here is that on connection ibm_db is cutting the hostname. It was a bigger string ea286ace-86c7-4d5b-8580-3fbfa46b1c66.bs2io90l08kqb1od8lcg.databases.ap... but for some reason it is not going through the connect method.

**Comment by bimalkjha** [comment]
@epetecof Ping your host and get the IP address. Now use the IP Address in connection string instead of hostname.
Can you share the uncut hostname in full so that I can check if we really have some code to strip it? Thanks.

**Comment by ibmbendev** [comment]
i am having this issue right now, is this already closed?

**Comment by Earammak** [comment]
@ibmbendev , Please share the other details that are mentioned in the issue template and what is the issue you are facing.
