### ISSUE TITLE
M1 / ARM64 Support

### ISSUE THREAD

**Issue by dwt** [ibmdb/python-ibmdb#827]
I'm waiting for ARM Support for DB2-Drivers and thus this python package.

**Describe the solution you'd like**
I understand that this is an upstream problem, however I want a place on this bug tracker to track this issue and to subscribe to, so I get notified once this has materialized and is integrated

**Describe alternatives you've considered**
Searching for closed bugs and looking at all of them do determine what the status is, or looking at pypi packages to see if one with my architecture is already released or looking at change notes.

None of this workarounds give me the ability to a) get status updates and notifications once the change is released or b) allow other people to also subscribe to this notification.

Therefore I request to keep this ticket open, till arm64 support is released and integrated.

**Comment by bimalkjha** [comment]
@dwt ibm_db can not support ARM64 architecture unless IBM Db2 Driver support arm64. For that support, a request with IBM already opened as https://ibm-data-and-ai.ideas.ibm.com/ideas/DB2CON-I-92 . Please open this link and vote/comment their.
ARM64 support is not an issue with ibm_db but with the underlying db2 driver named IBM Data Sever Driver Package or dsdriver/clidiver.
Probably you have not went through the similar closed issue #739 and this comment: https://github.com/ibmdb/python-ibmdb/issues/739#issuecomment-1088696792
Thanks.

**Comment by dwt** [comment]
@bimalkjha yes, I did. I am requesting to have a ticket here, to track when this is released and integrated and released in the python packages that are built form this repo.

My reasoning is, that I am interested in the python package, and therefore land here, so this ticket is the best place to document the current state and where the right ticket and project to request this feature is, as well as get notified when the python package is finally released with a arm variant on pypi.

Does that make sense?

**Comment by dwt** [comment]
(Also: one doesn't need an IBM-ID to subscribe here, and this is the perfect place to direct people to the IBM Page - if they actually want to create an IBM-ID to also subscribe there).

I suspect that many folks don't really care though, and just want to know when the python package is integrated - hence this ticket.

**Comment by bimalkjha** [comment]
**Steps to install ibm_db on arm64 architecture - M1/M2 Chip System** - https://github.com/ibmdb/python-ibmdb/issues/835#issuecomment-1503772903

**Comment by avaz** [comment]
@bimalkjha it seems that driver with support for Mac ARM is already available as per this link: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/v12.1.0/macarm64_odbc_cli.tar.gz

Any idea when this project will add support to it?

**Comment by bimalkjha** [comment]
Hi @avaz , @Earammak is working to provide support for arm64. She should share estimate if any. Thanks.

**Comment by Earammak** [comment]
@avaz , I'm working on it.  I will give support for this in few days. Thanks.

**Comment by bimalkjha** [comment]
@avaz We have released ibm_db@3.2.4 with ARM64 support. Try it and let us know. thanks.

**Comment by pavelzw** [comment]
is it already supposed to be released? 

i don't see it here: https://pypi.org/project/ibm-db/#history
<img width="1185" alt="image" src="https://github.com/user-attachments/assets/902d9356-1fa4-4d7c-8b38-76aa7e813d34" />

**Comment by dwt** [comment]
I see it now on pypi.

**Comment by pavelzw** [comment]
It seems like the source distribution is missing (was available in 3.2.3). Could we get that as well?

**Comment by bimalkjha** [comment]
@pavelzw We can not update source distribution in 3.2.4 release as it was uploaded before and deleted from pypi. Some issue happened during release. But, in next release, it will definitely be available. We are planning to have next release very soon. Thanks.

**Comment by bimalkjha** [comment]
@dwt @avaz @pavelzw We have released `ibm_db v3.2.5` with native installation support for MacOS Silicon Chip system and no need to use the emulated environment with x86_64 python on M1 chip system. Please install latest version of ibm_db and verify. Thanks.

**Comment by pavelzw** [comment]
looks good but in general, though i would suggest you take a look into compiling libdb2.so using clang instead of gcc as this would make installation on macOS much easier since the clang stdlib is already bundled on macos and you don't need to manually install gcc on your system. xref https://github.com/ibmdb/python-ibmdb/issues?q=sort:updated-desc+is:issue+clang+is:closed, https://github.com/ibmdb/db2drivers/issues/3

**Comment by bimalkjha** [comment]
@pavelzw libdb2.dylib for MacOS ARM64 is compiled using clang compiler only and we need not to have gcc. Also, we have released wheel images which do not require compilation. I'll remove check for gcc on macarm64 and update docs. Thanks.

**Comment by avaz** [comment]
> @dwt @avaz @pavelzw We have released `ibm_db v3.2.5` with native installation support for MacOS Silicon Chip system and no need to use the emulated environment with x86_64 python on M1 chip system. Please install latest version of ibm_db and verify. Thanks.

@bimalkjha I'm getting the error below while trying to install `ibm-db==3.2.5` on a docker image based on image `python:3.11-slim` using `python-poetry` tool. Version `3.2.4` does install successfully using the same setup. This is why I'm asking here first before reporting anywhere else. Do you think that maybe be a problem with version `3.2.5`?

```
6.930   ChefBuildError
6.930 
6.930   Backend subprocess exited when trying to invoke get_requires_for_build_wheel
6.930   
6.930   Detected 64-bit Python
6.930   Detected platform = linux, uname = aarch64
6.930   Traceback (most recent call last):
6.930     File "/opt/poetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
6.930       main()
6.930     File "/opt/poetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
6.930       json_out["return_val"] = hook(**hook_input["kwargs"])
6.930                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6.930     File "/opt/poetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
6.930       return hook(config_settings)
6.930              ^^^^^^^^^^^^^^^^^^^^^
6.930     File "/tmp/tmpbcgv0h5v/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
6.930       return self._get_build_requires(config_settings, requirements=[])
6.930              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6.930     File "/tmp/tmpbcgv0h5v/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
6.930       self.run_setup()
6.930     File "/tmp/tmpbcgv0h5v/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in run_setup
6.930       exec(code, locals())
6.930     File "<string>", line 371, in <module>
6.930   NameError: name 'arch_' is not defined
6.930   
6.930 
6.930   at /opt/poetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
6.934       160│ 
6.934       161│                 error = ChefBuildError("\n\n".join(message_parts))
6.934       162│ 
6.934       163│             if error is not None:
6.934     → 164│                 raise error from None
6.934       165│ 
6.935       166│             return path
6.935       167│ 
6.935       168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
6.935 
6.935 Note: This error originates from the build backend, and is likely not a problem with poetry but with ibm-db (3.2.5) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "ibm-db (==3.2.5)"'.
```

**Comment by rishacha** [comment]
I can't get this to run on my system. I get a segmentation fault error ! @bimalkjha 

```sh
python            
Python 3.11.11 (main, Dec  3 2024, 17:20:40) [Clang 16.0.0 (clang-1600.0.26.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_db                                                                                     
>>> conn_str = "DATABASE=bludb;HOSTNAME=54a2f15b-5c0f-46df-8954-7e38e612c2bd.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud;PORT=32459;PROTOCOL=TCPIP;UID=<username>;PWD=<password>;SECURITY=SSL;"
>>> ibm_db_conn = ibm_db.connect(conn_str,None,None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception: [IBM][CLI Driver] SQL30082N  Security processing failed with reason "24" ("USERNAME AND/OR PASSWORD INVALID").  SQLSTATE=08001 SQLCODE=-30082
>>> conn_str = "DATABASE=bludb;HOSTNAME=54a2f15b-5c0f-46df-8954-7e38e612c2bd.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud;PORT=32459;PROTOCOL=TCPIP;UID=<username>;PWD=<password>;"
>>> ibm_db_conn = ibm_db.connect(conn_str,None,None)                                                  
zsh: segmentation fault  python
```

**Comment by rishacha** [comment]
Solved by @bimalkjha . It was an issue with the connection string
