### ISSUE TITLE
ibm_db.execute_many returns bind error with numpy.int64 values

### ISSUE THREAD

**Issue by gregor-mm** [ibmdb/python-ibmdb#828]
ibm_db.execute_many returns bind error with numpy.int64 values

- Operating System Name: Linux
- Target Db2 Server Version: 11.5
- Python Version: 3.10
- ibm_db version: 3.1.4
- Linux x86_64

Steps to Reproduce:

```
ibm_db.exec_immediate(conn, "drop table ibm_db_tmp if exists")
ibm_db.exec_immediate(conn, "create table ibm_db_tmp(I bigint, J bigint)")

df_tiny = pandas.DataFrame([ [1,2],[4,5]], columns=list("IJ") )

tuple_of_tuples = tuple([tuple(x) for x in df_tiny.values]) # this will cause bind error
#tuple_of_tuples = ((1, 2), (4, 5))    # this works

sql = "INSERT INTO ibm_db_tmp(I,J) VALUES(?,?)"
stmt = ibm_db.prepare(conn, sql)
print(tuple_of_tuples)
print(type(tuple_of_tuples[0][0]))   # <class 'numpy.int64'> causes error
ibm_db.execute_many(stmt, tuple_of_tuples)
```
returns error
```
Exception                                 Traceback (most recent call last)
/tmp/1000690000/ipykernel_234/2652429900.py in <module>
     14 print(tuple_of_tuples)
     15 print(type(tuple_of_tuples[0][0]))   # <class 'numpy.int64'> causes error
---> 16 ibm_db.execute_many(stmt, tuple_of_tuples)
     17 # Exception: Error 1: Binding Error 1:
     18 # Error 2: [IBM][CLI Driver] CLI0125E  Function sequence error. SQLSTATE=HY010 SQLCODE=-99999

Exception: Error 1: Binding Error 1: 
Error 2: Binding Error 1: 
Error 3: [IBM][CLI Driver] CLI0125E  Function sequence error. SQLSTATE=HY010 SQLCODE=-99999
```

The data type of the columns in the target table doesn't matter. Got the same error with target type float or int.

When using float values in the dataframe the type in the tuple is `numpy.float64` and the insert works fine.
```
df_tiny = pandas.DataFrame([ [1.0,2.0],[4.0,5.0]], columns=list("IJ") ).  # insert will work
```

**Comment by imavo** [comment]
easy to recreate, also happens with python 3.9.5 and pandas 1.5.3

The immediate cause of the SQLBindParameter failure  is that ibm_db incorrectly sets fCType=SQL_C_TYPE_DATE for fSQLType=SQL_BIGINT  which is an invalid combination, thus produces CLI0125E.
 
When the dataframe values are integers, PyTuple_GET_ITEM()  returns PYTHON_DECIMAL for some reason, which may be an issue in itself.
 
  Two observations here:
  
  (1) PYTHON_DECIMAL values are not expected to be SQL_BIGINT datatypes in
      the _python_ibm_db_bind_data, instead it expects only SQL_DECIMAL,SQL_DECFLOAT.
      But SQLDescribeParm returns SQL_BIGINT in this case (of the example code in the
      issue).  This is the reason why float values in the dataframe work but integers
      fail with CLI0125E.
      
  (2) when the SQLBindParameter fails, ibm_db.c code fails to retrieve and display the 
      more helpful diagnostic message "CLI0102E  Invalid conversion" which happens
      because the code incorrectly gives fCType=SQL_C_TYPE_DATE for the SQLBindParameter
      due to (1). The more helpful error message is visible in a CLI trace however.
