### ISSUE TITLE
Bug Report: Import throws error - Symbol not found

### ISSUE THREAD

**Issue by thomasnicoletibm** [ibmdb/python-ibmdb#829]
Installing ibm_db works fine, but running ibm_db throws the error below. 
The installation guide refers to the clidriver, but I have not found any applicable to me (macOs without existing driver): 
"If you have to use your own URL for clidriver ..."
"If you are using python 3.8 or 3.9 on windows ..."
"if you wish to use an existing installation of clidriver or install the clidriver manually and use it ..."

Apologies if I missed something. I assume this is a bug in missing setup guideline, or a bug in implementation. This might duplicate issue #777 but it was not the same error afaik, and it was reported as fixed in latest build.

**Error**
```
ImportError: dlopen(/opt/anaconda3/envs/dtu/lib/python3.9/site-packages/ibm_db.cpython-39-darwin.so, 0x0002): Symbol not found: (___cxa_throw_bad_array_new_length)
  Referenced from: '/opt/anaconda3/envs/dtu/lib/python3.9/site-packages/clidriver/lib/libdb2.dylib'
  Expected in: '/usr/lib/libstdc++.6.dylib'
```

- Operating System Name: MacOs
- db2level output from clidriver if in use: Unknown
- Target Db2 Server Version: Unknown
- Python Version: 3.9.12
- ibm_db version: 3.1.0
- For non-Windows, output of below commands: 
  uname: Darwin
  uname -m: x86_64
- Value of below environment variables if set: 
  IBM_DB_HOME: Unknown
  PATH: Unknown
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: Unknown

- Test script to reproduce the problem.
`import ibm_db`

Steps to Reproduce:
Install conda, then run
`conda create --name testenv`
`conda activate testenv`

Install ibm_db
`pip install ibm_db`
run the following in a .py or .ipynb file
`import ibm_db`

**Comment by bimalkjha** [comment]
@thomasnicoletibm First, you have not shared all the information asked in issue template. We do not see any info regarding gcc version. /usr/lib/libstdc++.6.dylib is a gcc library and if you install gcc, this issue should go. Having gcc in the system is a pre-requirement for ibm_db on MacOS. Please install gcc version 8 using brew and verify the issue. Thanks.

**Comment by bimalkjha** [comment]
@thomasnicoletibm I hope your issue got resolved by installing gcc8. Else, please share the requested info. Thanks.

**Comment by thomasnicoletibm** [comment]
Thank you for your fast reply, and sorry for not getting back to you. 

Installing gcc version 8 fixed the problem. Thank you very much for the insight.

For new users however, I dont find the error message informative, or and I do not find it very clear that gcc is a requirement from the ibm_db github. 

On github ` https://github.com/ibmdb/python-ibmdb` it says:

_"You might need zlib, openssl, pip installations if not already available in your setup."_ 

This makes users assume that zlib and openssl are the only dependencies.

The github also states:

_MAC OS: Db2 V11.5.4 clidriver is built with GCC version 8.4.0 and hence you may need to upgrade to this version if you face problems due to old version of the GCC compiler in your environment while loading the ibm_db library._

This makes gcc a possible dependency, but it may help users to state it clearly in a "Requirements" section that a proper gcc version is a requirement, or show it in the error message when not having an appropriate.


Thank you again, you can close this if you like (or I will). But as it was not clear for me or other IBM employees I have asked, I assume it may be worth fixing if possible. I.E. Update the error message to hint installing/updating gcc, or updating the github with a clear Dependency / Requirements section: GCC version 8.

**Comment by bimalkjha** [comment]
@thomasnicoletibm Thanks for your feedback. We'll update the ibm_db documentation to highlight this dependency. Thank you.
