### ISSUE TITLE
randomly occurring error "X parameters bound but Y required".

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb#837]
- Operating System Name: any o/s
- db2level output from clidriver if in use: any version
- Target Db2 Server Version: any platform/version
- Python Version: any version
- ibm_db version: 3.1.4 or any previous version
- For non-Windows, output of below commands:
  uname (symptom can happen on any platform)
  uname -m
- Value of below environment variables if set:
  IBM_DB_HOME: (not relevant)
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: (not relevant).

- Test script to reproduce the problem. 
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

1. None provided, as this diagnosis is from code inspection of ibm_db.c, after the  symptom reported as part of #830 by @bestadam133

2. The detail of the bug report is below.

The ibm_db.c function `_python_ibm_db_execute_helper1` declares and tests an unitialised variable:
`SQLSMALLINT num;` which is supposed to get initialised by the subsequent call to `SQLNumParams()`.

However, in some circumstances, the CLI can return `SQL_ERROR` from the `SQLNumParams()` API, and when that happens, the value of the `num` variable remains unchanged, so it will have a random value.

In addition to the use of an unitialised variable, ibm_db.c fails to check the exit-code from `SQLNumParams()` here, so the consequence is that the subsequent comparison of the value of the `num` variable will randomly lead to the symptom `"%d params bound not matching %d required"`. This masks the real problem i.e. failure to check the exit-code from the `SQLNumParams` API and use of an uninitalised variable in comparisons.

It seems wise to ensure that all automatic variables get initialised.

My suggestion is to change the code of `_python_ibm_db_execute_helper1` in two ways , first is to initialise the "num" automatic variable to zero, and secondly to check the exit-code from the `SQLNumParams()` API and respond appropriately.

**Comment by bestadam133** [comment]
Thanks for creating this for me @imavo - it was annoying but not enough to do the research and all for creating the bug ticket since I found a workaround. I can add that I ran into it originally running on AWS Lambda, installing imbdb as a layer. The inserted rows were always the same (~200 rows, all columns strings/varchar), as well as the database tables were all exactly the same. 

Looks like you found root cause though, so you probably won't need anything else from me.

**Comment by Earammak** [comment]
@imavo Can you please share the sample program here to reproduce the problem? 

Thanks

**Comment by imavo** [comment]
@Earammak Do you really need it? The defect seems obvious to me. The example give by @bestadam133 in issue 830 will help you.

In the snippet below by @bestadam133  the database-table ddl is not relevant ( i.e. any schema, any table to match the 6 columns of data), as is the number of rows to be inserted, as any sample data will do as long as it matches the database-column type.  The example is deliberately contrived to ensure that the fault gets exposed, so while obvious workaround is possible (insert_sql=None, before the prepare), the fault nevertheless needs correcting as it can happen whenever SQLNumParms returns SQL_ERROR.


```
    for db in databases:
        conn = ibm_db.connect(f"DATABASE={db};HOSTNAME=...rest of connection string", "", "")
        ibm_db.exec_immediate(conn, f"DELETE FROM {schema}.{tablename}")
        insert_sql = f"""
            INSERT INTO {schema}.{tablename}
                (col1,col2,col3,col4,col5,col6)
            VALUES (?,?,?,?,?,?)
        """
        insert_stmt = ibm_db.prepare(conn, insert_sql, {ibm_db.SQL_ATTR_CURSOR_TYPE: ibm_db.SQL_CURSOR_STATIC})
        for rec in data:
            try:
                ibm_db.bind_param(insert_stmt, 1, rec[0], ibm_db.SQL_PARAM_INPUT)
                ibm_db.bind_param(insert_stmt, 2, rec[1], ibm_db.SQL_PARAM_INPUT)
                ibm_db.bind_param(insert_stmt, 3, rec[2], ibm_db.SQL_PARAM_INPUT)
                ibm_db.bind_param(insert_stmt, 4, rec[3], ibm_db.SQL_PARAM_INPUT)
                ibm_db.bind_param(insert_stmt, 5, rec[4], ibm_db.SQL_PARAM_INPUT)
                ibm_db.bind_param(insert_stmt, 6, rec[5], ibm_db.SQL_PARAM_INPUT)
                ibm_db.execute(insert_stmt)
            except Exception as e:
                print(f"A SQL error occurred: \n{ibm_db.stmt_errormsg()}")
                raise e
        
        ibm_db.free_result(insert_stmt)
        ibm_db.close(conn)

```

**Comment by Earammak** [comment]
@imavo The sample given by @bestadam133 is mentioned as rough code. it is not included complete problematic code.
              If you can share the problematic test file will be easy for me to reproduce the error.

**Comment by imavo** [comment]
@Earammak see below

```
import ibm_db
import sys 

#  Before running this script, create the following table in your database
# drop table if exists bind_test
# create table bind_test(col1 char(1) not null, col2 char(1) not null, col3 char(2) not null, col4 char(1) not null, col5 char(3) not null, col6 char(1) not null);
# ALSO adjust the connection-string details for your environment.
#
# This script when run on ibm_db 3.1.4 may throw exception "Exception: 6 params bound not matching -23020 required" (or other large random number).
# Code defect: ibm_db.c function _python_ibm_db_execute_helper1 declares and tests an unitialised variable:
# SQLSMALLINT num; which is supposed to get initialised by the subsequent call to SQLNumParams(), but if SQLNumnParams() returns SQL_ERROR you get the symptom.
#
# It may happen occasionally, just increase the number of loops (for i in range(10) --> for i in range(100) to increase the chances of getting the error
# Note: this is avoided by the workaround of `insert_stmt=None` before the prepare, but that is a separate matter.


schema="..."  # connecting userid
auth_id=schema
token="..."   # e.g. your password
tablename="bind_test_char"
databases=["..."]   # one database is enough


data = [ 
         [ 'a', 'b', 'c', 'd', 'e','f'],
         [ 'g', 'h', 'i', 'j', 'k','l'],
         [ 'm', 'n', 'o', 'p', '1','s'],
         [ 't', 'u', 'v', 'w', 'y','z'],
         [ 'a', 'a', 'a', 'a', 'a','a'],
         [ 'z', 'z', 'z', 'z', 'z','z'],
         [ '0', '0', '0', '0', '0','0'],
         [ '9', '9', '9', '9', '9','9'],
         [ '<', '<', '<', '<', '<','<'],
         [ '!', '!', '!', '!', '!','!']
      ]   
   

# the insert_statement does not change inside the loops
insert_sql = f"INSERT INTO {schema}.{tablename} ( col1 , col2 , col3 , col4 , col5, col6 ) VALUES (? ,? ,? ,? ,? ,?)"


for i in range(10):
    for db in databases:
        print(f"Database {db} Iteration {i} starting...\n")
        conn = ibm_db.connect( db, auth_id, token )
        if not conn:
            print(f"\nDatabase {db} Iteration {i} Error failed to connect to database: {ibm_db.conn_errormsg()}\n")
            sys.exit(1)
    
        ibm_db.autocommit(conn, ibm_db.SQL_AUTOCOMMIT_ON)
        ibm_db.exec_immediate(conn, f"DELETE FROM {schema}.{tablename}")
    
        insert_stmt = ibm_db.prepare(conn, insert_sql, {ibm_db.SQL_ATTR_CURSOR_TYPE: ibm_db.SQL_CURSOR_STATIC})
    
        for rec in data:
            try:
                ibm_db.bind_param(insert_stmt, 1, rec[0], ibm_db.SQL_PARAM_INPUT)
                ibm_db.bind_param(insert_stmt, 2, rec[1], ibm_db.SQL_PARAM_INPUT)
                ibm_db.bind_param(insert_stmt, 3, rec[2], ibm_db.SQL_PARAM_INPUT)
                ibm_db.bind_param(insert_stmt, 4, rec[3], ibm_db.SQL_PARAM_INPUT)
                ibm_db.bind_param(insert_stmt, 5, rec[4], ibm_db.SQL_PARAM_INPUT)
                ibm_db.bind_param(insert_stmt, 6, rec[5], ibm_db.SQL_PARAM_INPUT)
                ibm_db.execute(insert_stmt)
            except Exception as e:
                print(f"Database {db} Iteration {i}\n{ibm_db.stmt_errormsg()}")
                raise e
        try:
            ibm_db.free_result(insert_stmt)
            ibm_db.close(conn)
        except Exception as x:
            print(f"Database {db} Iteration {i} exception\n")
            raise x


sys.exit(0)
```
