### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by immortalvirgil** [ibmdb/python-ibmdb#840]
import ibm_db
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ibm_db.cpython-39-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: <855AE640-1BCF-3A61-A65E-58F5490BFF43> /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/clidriver/lib/libdb2.dylib
  Expected in:     <C473C61C-2FFF-3171-BD7A-1C0A3B03B3B6> /usr/lib/libstdc++.6.dylib

Anyone could help me,i am a bit out of patience, before yesterday i use python3.8 it report error as below, then i tried all the way to solve include runnning command by
install_name_tool -change libdb2.dylib /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/clidriver/lib/libdb2.dylib /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ibm_db.cpython-38-darwin.so
 export DYLD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/clidriver/lib
it doesn't work, then i tried to switch to python 3.9 environment and works well. After i upgrade ibm_db package then it report the same error as above again

**Comment by Earammak** [comment]
@immortalvirgil Please uninstall and reinstall ibm_db after deleting site_packages\clidriver directory. Thanks

**Comment by immortalvirgil** [comment]
> @immortalvirgil Please uninstall and reinstall ibm_db after deleting site_packages\clidriver directory. Thanks

not work,sorry

**Comment by immortalvirgil** [comment]
@Earammak not work sorry

**Comment by bimalkjha** [comment]
@immortalvirgil Please provide all info requested in issue template to give you the right solution. 
This issue comes due to missing gcc library. You need to add /usr/local/lib/gcc/8 to your DYLD_LIBRARY_PATH. Please check similar issues #829, #831 and #804 which are closed now. It is a duplicate issue whose solution is already in closed issues. Thanks.

**Comment by immortalvirgil** [comment]
is DYLD_LIBRARY_PATH should be libdb2.dylib's path?

**Comment by bimalkjha** [comment]
@immortalvirgil DYLD_LIBRARY_PATH should have both gcc/12 and clidriver/lib like `export DYLD_LIBRARY_PATH=/usr/local/lib/gcc/8:{ABSOLUTE PATH TO site_packages}/clidriver/lib:$DYLD_LIBRARY_PATH`
```
Your MacOS has arm64 processor or x64 processor? 
```
Run below commands on terminal and verify the output as below:
```
gcc -v   => Output must have x86_64
python --version   or python3 --version
file `which python` or file `which python3`   => Output must have x86_64
pip uninstall ibm_db
pip install ibm_db
export DYLD_LIBRARY_PATH=/usr/local/lib/gcc/8:{ABSOLUTE PATH TO site_packages}/clidriver/lib:$DYLD_LIBRARY_PATH
import ibm_db
```
Thanks.

**Comment by immortalvirgil** [comment]
intel i7 processor.
i do tried your way, but still not work

**Comment by immortalvirgil** [comment]
@bimalkjha set up gcc@8 works but i have failed download many times, my version wasn't the correct version, i really thank you and wish you will have a good weekend.
