### ISSUE TITLE
Bug Report: binding array of strings of timestamps/dates/times  with null element causes segfault

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb#841]
- Operating System Name: linux x64
- db2level output from clidriver if in use: 11.5.8.0
- Target Db2 Server Version: 11.5.8.0
- Python Version: 3.9.5
- ibm_db version: 3.1.4
- For non-Windows, output of below commands:
  uname (not relevant)
  uname -m (not relevant)
- Value of below environment variables if set:
  IBM_DB_HOME: (not relevant)
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: (not relevant)

- Test script to reproduce the problem (see below)
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

First the description of the problem, followed by a code snippet to recreate the symptom.

1. Db2 allows NULL in columns of type date, time, timestamp. But python ibm_db causes a segfault during array-binding for the column types if the array (for SQL_PARAM_INPUT type) has null elements.

ibm_db allows NULL elements for other python-types in arrays during binding, for example PYTHON_UNICODE, PYTHON_STRING, PYTHON_DECIMAL.

Code inspection of `ibm_db.c` shows that the relevant branches of the main case statement in function ` _python_ibm_db_bind_data` for each of those python-types `PYTHON_TIMESTAMP`, `PYTHON_TIME`, `PYTHON_DATE`, it has neither allocated nor initialised `bind_indicator_array`. However, it still passes the (unallocated) address of `bind_parameter_array` to `SQLBindParameter()` when the bind_data is a `PYTHON_LIST`, resulting in the segfault.

The code example below shows `PYTHON_TIMESTAMP`, but you can recreate the same symptom with `PYTHON_DATE` and `PYTHON_TIME` as the same coding problem exists for these python-types.

2. create a target table in your database with this DDL `drop table if exists bind_test_timestamp;
create table bind_test_timestamp ( col1 timestamp   , col2 timestamp   );  `

3.  Adjust the code snippet below for your database name and credentials and run it. If it succeeds then 10 rows get inserted into the table, and the second column has some null values, which the first column has no nulls.

```
import ibm_db
import sys 


schema="..."  # the schema-name for the table db2 (typically your userid)
token="..."   # the password for your authid
tablename="bind_test_timestamp"
authid=schema # the account used to connect to the database (typically same as your userid)
databases_list=["your_database_name"]


timestamp_array1 = [b'1981-07-08 10:42:34.000010', b'1982-07-08 10:42:34.000010', b'1983-07-08 10:42:34.000010', b'1984-07-08 10:42:34.000010', b'1985-07-08 10:42:34.000010', b'1986-07-08 10:42:34.000010', b'1987-07-08 10:42:34.000010', b'1988-07-08 10:42:34.000010', b'1989-07-08 10:42:34.000010', b'1990-07-08 10:42:34.000010']

# there are some null elements '' in this array deliberately.

timestamp_array2 = [b'1981-07-08 10:42:34.000010','' , b'1983-07-08 10:42:34.000010','' , b'1985-07-08 10:42:34.000010','' , b'1987-07-08 10:42:34.000010','' , b'1989-07-08 10:42:34.000010','' ]

array_length=len(timestamp_array1)


# the insert statement does not change so initialise it outside the loop(s)
insert_sql = f"INSERT INTO {schema}.{tablename} ( col1 , col2 ) VALUES (? ,?)"


for i in range(1):
    for db in databases_list:
        print(f"Database {db} Iteration {i}\n")
        conn = ibm_db.connect( db, authid, token )
        if not conn:
            print(f"Error failed to connect to database {db} :{ibm_db.conn_errormsg()}\n")
            sys.exit(1)
            
        ibm_db.autocommit(conn, ibm_db.SQL_AUTOCOMMIT_ON)
        spare_hstmt = ibm_db.exec_immediate(conn, f"DELETE FROM {schema}.{tablename}")
        ibm_db.free_result(spare_hstmt)
        spare_hstmt=None
    
        insert_stmt=None
        insert_stmt = ibm_db.prepare(conn, insert_sql, {ibm_db.SQL_ATTR_CURSOR_TYPE: ibm_db.SQL_CURSOR_STATIC})
    
        # set statement-attributes for array-binding, and number of elements in arrays
        mybool=False
        mybool = ibm_db.set_option(insert_stmt, {ibm_db.SQL_ATTR_PARAM_BIND_TYPE : ibm_db.SQL_PARAM_BIND_BY_COLUMN}, 0)
        if not mybool:
            print(f"Database {db} Iteration {i} ,Failed to set array columnwise binding option: {ibm_db.stmt_errormsg()}\n")            
            sys.exit(1)

        mybool=False
        mybool=ibm_db.set_option(insert_stmt, {ibm_db.SQL_ATTR_PARAMSET_SIZE : array_length}, 0)
        if not mybool:
            print(f"Database {db} Iteration {i} , Failed to set array length: {ibm_db.stmt_errormsg()}\n")
            sys.exit(1)
                
        try:
            mybool=False
            mybool=ibm_db.execute(insert_stmt, ( timestamp_array1, timestamp_array2))
                
        except Exception as e:
            print(f"Database {db} Iteration {i}: \n{ibm_db.stmt_errormsg()}")
            raise e

        ibm_db.free_result(insert_stmt)
        ibm_db.close(conn)
        conn=None


sys.exit(0)
```

**Comment by Earammak** [comment]
@imavo, I tried your sample program and when i use Unicode timestamp format instead of string timestamp format [ the one you tried in your sample program]. With your given input we could see the segmentation fault for me.

When i tried with Unicode timestamp format to the same input values. I'm getting the below error.
Arrays:
timestamp_array1 = ['1981-07-08 10:41:32.000010', '1982-07-08 10:42:34.000010', '1983-07-08 10:42:34.000010', '1984-07-08 10:42:34.000010', '1985-07-08 1    0:42:34.000010', '1986-07-08 10:42:34.000010', '1987-07-08 10:42:34.000010', '1988-07-08 10:42:34.000010', '1989-07-08 10:42:34.000010', '1990-07-08 10:4    2:34.000010']
timestamp_array2 = ['1981-07-08 10:42:34.000010' ,'', '1983-07-08 10:42:34.000010','' , '1985-07-08 10:42:34.000010','' , '1987-07-08 10:42:34.000010',''     , '1989-07-08 10:42:34.000010','' ]
Exception: Statement Execute Failed: [IBM][CLI Driver] CLI0113E  SQLSTATE 22007: An invalid datetime format was detected; that is, an invalid string representation or value was specified. SQLSTATE=22007 SQLCODE=-99999

And observed other scenario, when i have all array values containing null values, null values gets inserted into the table.
It is working fine, without any errors. and i can see the data in a corresponding table as well.
Inputs used:
array1 ===> ['1985-07-08 10:42:34.000010', '1985-07-08 10:42:34.000010']
arry2 ====> ['', '']

Inserted tables:
COL1                       COL2
-------------------------- --------------------------
1985-07-08-10.42.34.000010 -
1985-07-08-10.42.34.000010 -

When I try to use combination null and timestamp input values for an array, will be getting invalid date format error.
Looks like from above error, it is saying that representing null values of type timestamp is not the right input.

I'm looking into this. If you have any info in adding null timestamp values, please share with me.

Thanks

**Comment by imavo** [comment]
Timestamp columns in Db2 can be nullable. Are you questioning that? What other information can you need?

Separately, I meant to use ISO formatted strings for the timestamps, as they are the most common with Db2, like this:

timestamp_array1 = ['1981-07-08-10.42.34.000010',
                    '1982-07-08-10.42.34.000010',
                    '1983-07-08-10.42.34.000010', 
                    '1984-07-08-10.42.34.000010', 
                    '1985-07-08-10.42.34.000010', 
                    '1986-07-08-10.42.34.000010', 
                    '1987-07-08-10.42.34.000010', 
                    '1988-07-08-10.42.34.000010', 
                    '1989-07-08-10.42.34.000010', 
                    '1990-07-08-10.42.34.000010']

timestamp_array2 = ['1981-07-08-10.42.34.000010' 
                     '',
                    '1983-07-08-10.42.34.000010',
                    '' , 
                    '1985-07-08-10.42.34.000010',
                    '' , 
                    '1987-07-08-10.42.34.000010',
                    '' , 
                    '1989-07-08-10.42.34.000010',
                    '' ]



The problem symptom remains the same because as I wrote previously, the ibm_db.c code uses an unallocated variable for the bind indicator array for this specific case.

I understand that the SQLBindParameter will operate properly when the programmer properly allocates and initialises the bind indicator array ( i.e. uses SQL_NULL_DATA for the relevant array entry when the length of the corresponding item extracted from the length is zero).  This is an elementary error with a simple fix I think.

**Comment by imavo** [comment]
you are correct, my example shows arrays of strings (of representations of timestamps), it does not show an array of timestamps.

So my remarks about the code in _ibm_db_bind_data for PYTHON_TIMESTAMP are not relevant for PYTHON_STRING or PYTHON_UNICODE objects (although a separate testcase is needed for the former, as the code is still incorrect as regards using an unallocated variable for the bind_indicator_array). So that should be a different issue.


But for this current testcase, It appears that there is a flaw somewhere , as has to be possible to insert a null into a nullable field by some means,  including being able to bind an array  with a mix of not-null and null elements.  I cannot find as yet any documentation that mentions a restriction by CLI for that detail. Need to investigate further.

**Comment by imavo** [comment]
It seems the essential requirement when binding arrays is that each element has exactly the same length. That's not possible if representing NULL as the empty string '' while other elements in the same array are not-null strings. It's also the reason why using '' for all array entries will insert the null into the column.

**Comment by Earammak** [comment]
@imavo, Thank you for sharing the update. 
Can you please share the document where it says all the elements in a binding array uses the same length.

Thanks

**Comment by imavo** [comment]
@Earammak   Refer to the urllink in my previous update.

In the section describing "ParameterValuePtr" where it says "If SQLParamOptions() is called to specify multiple values for the parameter, then ParameterValuePtr is a pointer to a input buffer array of BufferLength bytes."
This I interpret to mean that the array comprises at leas 'n' entries, each of length BufferLength, where 'n' is the value given for SQL_ATTR_PARAMSET_SIZE.

Similarly in the section for the "BufferLength" paramter the text begins with "For character and binary data, BufferLength specifies the length of the ParameterValuePtr buffer (if is treated as a single element) or the length of each element in the ParameterValuePtr array (if the application calls SQLParamOptions() to specify multiple values for each parameter).", which again I interpret to mean that each element in the array has this length (for character and binary input data).
