### ISSUE TITLE
Import ibm_db issue

### ISSUE THREAD

**Issue by sabint54** [ibmdb/python-ibmdb#844]
I am currently having an issue importing ibm_db using python. 

`ImportError: dlopen(/usr/local/lib/python3.11/site-packages/ibm_db.cpython-311-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: <855AE640-1BCF-3A61-A65E-58F5490BFF43> /usr/local/lib/python3.11/site-packages/clidriver/lib/libdb2.dylib
  Expected in:     <31679759-38DC-357A-95C2-542EA70F295F> /usr/lib/libstdc++.6.dylib`

I have the following versions in my computer
`gcc version 12.2.0 using brew install gcc
python version 3.11.2`

I have also tried setting the DYLD_LIBRARY_PATH using:
`export DYLD_LIBRARY_PATH = /usr/local/Cellar/gcc/12.2.0/lib/gcc/12:$DYLD_LIBRARY_PATH"` as well as 
`export DYLD_LIBRARY_PATH=/usr/local/lib/python3.5/site-packages/clidriver/lib:$DYLD_LIBRARY_PATH` [Github Link](https://github.com/ibmdb/python-ibmdb/tree/master/IBM_DB/ibm_db#issues-with-mac-os-x)

but still getting the same error. 

Any suggestions would be appreciated. Thank you

**Comment by Earammak** [comment]
@sabint54 Please check similar issues that are already closed one.[#844, #831, #829, and #804]. Thanks
