### ISSUE TITLE
Enable pandas.to_sql

### ISSUE THREAD

**Issue by pst2154** [ibmdb/python-ibmdb#847]
The method pd.to_sql does not seem to work

**Comment by imavo** [comment]
It works for me. Please fill in all the answers to the questions on the bug template, then somone can help you.
Saysing "does not work" tells us nothing. You need to give all the environment details, all the versions, and some sample code that shows the problem.

**Comment by imavo** [comment]
What is your version of the three modules:  ibm_db, pip, pandas?

What operating-system (linux , unix) bu which distro and which version?


Have you verified which schema contains that table "sqlite_master"? (Db2 is telling you that the "ADMIN" schema has no such table).  Have you either set the current schema special register in a Db2 attribute, or used it as a connection property?

**Comment by bimalkjha** [comment]
@pst2154 Please provide details asked in above post by imavo? Let us know otherwise so that we can close it. Thanks.
