### ISSUE TITLE
Calling SYSPROC.ADMIN_INFO_SYSPARM throws: CLI0150E  Driver not capable. SQLSTATE=HYC00 SQLCODE=-99999 

### ISSUE THREAD

**Issue by c-muncan** [ibmdb/python-ibmdb#848]
- Operating System Name: Win10
- Target Db2 Server Version: V12R1M510
- Python Version: 3.11
- ibm_db version: 3.1.4
- Value of below environment variables if set:
IBM_DB_HOME=C:\Program Files\IBM\SQLLIB
Path=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Personal Communications\;C:\Program Files (x86)\IBM\Trace Facility\;C:\Lotus\Notes;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\Program Files (x86)\Riverbed\Steelhead Mobile\;C:\PROGRA~1\IBM\SQLLIB\BIN;C:\PROGRA~1\IBM\SQLLIB\FUNCTION;C:\Program Files\PuTTY\;C:\Users\a463\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\a463\AppData\Local\Programs\Python\Python311\;C:\Users\a463\AppData\Local\Programs\Python\Launcher\;C:\Users\a463\AppData\Local\Microsoft\WindowsApps;C:\Users\a463\AppData\Local\Programs\Git\cmd;C:\Users\a463\AppData\Local\Programs\Microsoft VS Code\bin

LIB=;C:\PROGRA~1\IBM\SQLLIB\LIB

Steps to Reproduce:

When I attempt to run ADMIN_INFO_SYSPARM via ibm_db.callproc, I get 

```
    stmt1, db2_member, retcode = ibm_db.callproc(conn, "SYSPROC.ADMIN_INFO_SYSPARM", spParms)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Describe Param Failed: [IBM][CLI Driver] CLI0150E  Driver not capable. SQLSTATE=HYC00 SQLCODE=-99999
```

The code used to generate the error:

```python

import ibm_db
import datetime
import sys
import getpass

user = getpass.getuser()
pswd = getpass.getpass()

if len(sys.argv) > 1:
  conn=ibm_db.connect(sys.argv[1],user,pswd)
else:
   conn=ibm_db.connect('ssid',user,pswd)

if not conn:
  print ("Can't connect! Aborting process.")
  exit(-99)

stmt1 =''
db2_member=None
retcode=0
spParms = (db2_member, retcode)
stmt1, db2_member, retcode = ibm_db.callproc(conn, "SYSPROC.ADMIN_INFO_SYSPARM", spParms)

if (stmt1):
  # result set available

  row = ibm_db.fetch_assoc(stmt1)
  while row:
      print(row["TEXT"])
      row = ibm_db.fetch_assoc(stmt1)

ibm_db.commit(conn)
ibm_db.close(conn)
```

**Comment by imavo** [comment]
Please retry with the third parameter to the stored procedure.
```
message='-'
spParms = (db2_member, retcode, message)
stmt1, db2_member, retcode, message = ibm_db.callproc(conn, "SYSPROC.ADMIN_INFO_SYSPARM", spParms)
```

If that does not change the symptom, please take a CLI trace and attach the formatted result to this ticket, by running these commands in a cmd window (or db2cmd.exe window if you are using the IBM Db2 Server client):

```
db2trc on -f  trace.dmp
run your python script until it fails (in this cmd/db2cmd window)
db2trc off
db2trc fmt -cli trace.dmp   trace.fmtcli
```

The resulting file trace.fmtcli is a text file, hopefully short , so you can copy its contents into this ticket or attach the file.

**Comment by c-muncan** [comment]
thank you @imavo that was the problem.  I was not calling the stored proc with the 3rd parameter.

I am now doing this and it is working properly

```python
stmt1 =''
db2_member=None
retcode=0
message ='-'
spParms = (db2_member, retcode, message)
stmt1, db2_member, retcode, message = ibm_db.callproc(conn, "SYSPROC.ADMIN_INFO_SYSPARM", spParms)

# process the result set available
if (stmt1):
  print(ibm_db.fetch_assoc(stmt1))
  row = ibm_db.fetch_assoc(stmt1)
  while row:
    print(row["PARAMETER"])
    print(row["VALUE"])
    row = ibm_db.fetch_assoc(stmt1)
```

returning data back.  thanks again

**Comment by imavo** [comment]
pleased to read that it works. You can maybe close this ticket.
