### ISSUE TITLE
Need some post install instructions for configuring the db2cli utility that is installed as part of python-ibmdb

### ISSUE THREAD

**Issue by johnottogood** [ibmdb/python-ibmdb#855]
After a successful pip install of ibm_db, it is quite difficult to understand how to actually get the code to connect to a database.
The instructions need to describe, or at least point to reliable doc for how to configure the db2cli driver.

I had to do some digging to find a sample db2cli.ini.sample file in site-packages/clidriver/cfg and then do more digging to find what to put in it.

After that, the target database indicated it could not find the packages that the db2cli tool was using.  Knowing that one needs to bind the packages, I finally dug up the information for using db2cli to bind the packages against the remote Db2 (z/OS) database.

A python user that just wants to get at data is not likely to know that db2cli.ini exists, the concept of packages, or that they have to be bound against the target database.

Are there some references in the ibm_db project documentation that I missed that describes all of this?

**Comment by bimalkjha** [comment]
@johnottogood For connection, you need not to find the db2cli.ini file or db2dsdriver.cfg file, but you can directly pass the connection info using connection string as shown in the `quick example` doc of ibm_db: https://github.com/ibmdb/python-ibmdb#-quick-example

If you want to use db2cli.ini file or db2dsdriver.cfg file for connection and other configuration, you need to refer Db2 knowledgecenter about it.
db2cli.ini initialization file - https://www.ibm.com/docs/en/db2/11.5?topic=keywords-db2cliini-initialization-file
IBM data server driver configuration file - https://www.ibm.com/docs/en/db2/11.5?topic=drivers-data-server-driver-configuration-file

Regarding missing package error from z/OS server, you can bind packages using db2 or db2cli, but those instructions are too in db2 knowledge center doc only. We can see the db2cli bind command example here: https://www.ibm.com/docs/en/db2/11.5?topic=commands-db2cli-db2-interactive-cli

About location of `clidriver` post install of ibm_db, if you search ibm_db document for clidriver, you can find many instances with path of clidriver as `/usr/local/lib/python3.5/site-packages/clidriver/lib` i.e. it is under `site_packages` where `ibm_db` package get installed.

We have mentioned the `db2cli bind` command in the documentation of nodejs driver here: https://github.com/ibmdb/node-ibm_db#for-missing-packagebinding-issue
We'll update python driver doc too to include this info. Thanks.
