### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by srilakshmikancharla** [ibmdb/python-ibmdb#856]
My requirement is to connect the db2 database using python, so in python there we have ibm_db package, using that we can make connection to the db2 database.

i have installed the ibm_db package though pip command

 pip install ibm_d2

while making connection to db2 by using ibm_db.connect method. getting the below error.

 [IBM][CLI Driver] SQL1598N An attempt to connect to the database server failed because of a licensing problem. SQLSTATE=42968 SQLCODE=-1598

This error is causing due to missing of license files, what type of license files have to provide and  where to place. is it compulsory to have license file?

please help me, Thanks in advance.

**Comment by Earammak** [comment]
@srilakshmikancharla Can you please share other  etails[ like os name, version of ibm_db and python]  as well here.
This is due to missing of license file. You need to copy license file in license directory.

Thanks

**Comment by srilakshmikancharla** [comment]
Thanks for the reply @Earammak.

OS: windows
ibm_db version:  3.1.3
python : 3.8.13

can you please help me like what type of license file need to be copied in license directory and what is the license file format?

**Comment by bimalkjha** [comment]
@srilakshmikancharla Check this ibm_db documentation: https://github.com/ibmdb/python-ibmdb#-license-requirements-for-connecting-to-databases

**Comment by srilakshmikancharla** [comment]
Thanks for the reply @bimalkjha 

I have gone the documentations, still i was not clear about the client licenses, while downloading the ibm_db module , clidriver  got installed.

In documentation they mentioned like the client side license would need to be copied under license folder of your cidriver installation directory, My question is i don't have any license files to copy under license file where do i get the license files and what is license file extension?.

For server side license they mentioned we have to purchase the license, what about the client side license?

Thanks in advance

**Comment by bimalkjha** [comment]
@srilakshmikancharla Client side license also you need to purchase from IBM Support. 
Connectivity to Db2 for z/OS and Db2 for iSeries using ibm_db driver is not free from distributed platforms. You can connect to Db2 for LUW server, on-prem or in Cloud using ibm_db driver free of cost without any license. But for z/OS and iSeries servers, you need to purchase `db2connect v11.5` license from IBM Support: https://www.ibm.com/mysupport/s/createrecord/NewCase
Thanks.

**Comment by bimalkjha** [comment]
@srilakshmikancharla Please check your z/OS sysadmin about db2connect license. There is single license file comes with both client side and server side license. A license file with name `db2consv*.lic` is a client side license. You need to copy `db2consv_zs.lic` file under `clidriver\license` directory. 
You do not need client side license if z/OS server is db2connect activated for unlimited connection. So, check with your server admin first about db2connect license. They should have contact no of IBM Support too.

Your requirement is to connect to Db2 for z/OS or iSeries. You have not answered this question asked in the problem template. Without knowing server details, how we could help you? Could you please share the `db2level` output from your Db2 server to which you are trying to connect using `ibm_db` driver?

If you are working for IBM or its partner and you have slack access, then let us know. We can connect you to the right person to procure db2connect license. Thanks.
