### ISSUE TITLE
ProgrammingError: The last call to execute did not produce any result set

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb#857]
- Operating System Name: ubuntu 20.04
- db2level output from clidriver if in use:  11.5.0.8
- Target Db2 Server Version: 11.5.8.0
- Python Version: 3.9.5
- ibm_db version: 3.1.4
- For non-Windows, output of below commands:
  uname Linux
  uname -m x86_64
- Value of below environment variables if set:
  IBM_DB_HOME:  n/a
  PATH: n/a
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: n/a

- Bug description.

When pandas runs `read_sql_query()` to invoke a stored-procedure and put its result-set into a dataframe, the ibm_db_dbi.py throws an exception as follows:

```
Traceback (most recent call last):
  File "/home/user1/pvenv39/lib/python3.9/site-packages/sqlalchemy/engine/cursor.py", line 991, in fetchall
    rows = dbapi_cursor.fetchall()
  File "/home/user1/pvenv39/lib/python3.9/site-packages/ibm_db-3.1.4-py3.9-linux-x86_64.egg/ibm_db_dbi.py", line 1541, in fetchall
    return self._fetch_helper()
  File "/home/user1/pvenv39/lib/python3.9/site-packages/ibm_db-3.1.4-py3.9-linux-x86_64.egg/ibm_db_dbi.py", line 1482, in _fetch_helper
    raise  self.messages[len(self.messages) - 1]
ibm_db_dbi.ProgrammingError: ibm_db_dbi::ProgrammingError: The last call to execute did not produce any result set.
```

The cause appears to be broken logic for handling `_result_set_produced` in class Cursor of `ibm_db_dbi.py`.

This symptom was noted in previously closed issue #272  although the reason for closure is not mentioned there.

Recreate with Db2-LUW with the testcase below, after you create the relevant stored-procedure in your database and adjust for your environment.

In my case the versions of python (3.9.5) packages in the venv are as follows (although only a few are necessary), ibm_db , ibm_db_sa, pandas and sqlalchemy and their dependencies:

```
$ pip freeze
config==0.5.1
contourpy==1.0.7
cycler==0.11.0
fonttools==4.39.3
greenlet==1.1.2
ibm-db==3.1.4
ibm-db-sa==0.3.8
importlib-resources==5.12.0
kiwisolver==1.4.4
matplotlib==3.7.1
numpy==1.24.2
packaging==23.0
pandas==2.0.2
Pillow==9.5.0
pkg_resources==0.0.0
pyodbc==4.0.39
pyparsing==3.0.9
pypyodbc==1.3.6
python-dateutil==2.8.2
pytz==2022.7.1
six==1.16.0
SQLAlchemy==1.4.47
typing_extensions==4.5.0
tzdata==2023.3
zipp==3.15.0
```

- Test script to reproduce the problem.

```
!/usr/bin/python
#
# Use pandas read_sql_query() to call a stored procedure that returns a result-set into a dataframe.
#
# Before running this program, run the following ddl to create the stored-procedure
# in the same schema as the authid you use in the credentials below.
#    --#SET TERMINATOR @
#    create or replace procedure sp_result_2col ( )
#    language sql
#    specific sp_result_2col
#    dynamic result sets 1
#    begin
#        declare c1 cursor with return to client for
#        select tabschema,tabname 
#        from syscat.tables
#        where type='T'
#        order by 1, 2
#        with ur;
#        open c1;
#    end@
#    

import ibm_db
import pandas as pd
from sqlalchemy import create_engine


# CHANGEME - adjust for your environment
dsn_database = '.......'
dsn_uid='.......'
dsn_pwd='....'
dsn_hostname='....'
dsn_port=....


engine = create_engine(f'ibm_db_sa://{dsn_uid}:{dsn_pwd}@{dsn_hostname}:{dsn_port}/{dsn_database}')

my_query="call sp_result_2col()"

df=pd.read_sql_query(my_query, engine)

print(df)
```

Steps to Reproduce:

1. Create the stored-procedure in your database as per the ddl in the python script above, adjust the python script with your environment details and credentials for the dsn
2. Run the python script , no arguments required

**Comment by Earammak** [comment]
@imavo, The issue has been fixed as part of PR #863.
