### ISSUE TITLE
Cannot install ibm_db

### ISSUE THREAD

**Issue by jamesgeevarghese** [ibmdb/python-ibmdb#858]
<img width="953" alt="image" src="https://github.com/ibmdb/python-ibmdb/assets/135851100/68bd6fd5-1350-4ebb-986a-35e6cea28513">
 I am unable to download ibm_db and I have been trying to figure it out for sometime. In the error it is saying to install the intel-only x64 version of python but I don't know how to do that. Any help would be appreciated

**Comment by bimalkjha** [comment]
@jamesgeevarghese You have not answered the info asked in the bug report template. While opening any issue, please provide requested info.

Now, If you search ibm_db doc (https://github.com/ibmdb/python-ibmdb) about arm64, you'll find all info and link. You can download and install this x64 python: https://www.python.org/ftp/python/3.9.11/python-3.9.11-macosx10.9.pkg

You have not searched about this issue under closed issue too. There are lot of closed issues with solution. Please follow instructions as documented here: https://github.com/ibmdb/python-ibmdb/issues/835#issuecomment-1503772903

Thanks.
