### ISSUE TITLE
ImportError: dlopen(/Users/gurvindersingh/anaconda3/lib/python3.10/site-packages/ibm_db.cpython-310-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length

### ISSUE THREAD

**Issue by gurvinderguru007** [ibmdb/python-ibmdb#861]
ImportError: dlopen(/Users/gurvindersingh/anaconda3/lib/python3.10/site-packages/ibm_db.cpython-310-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: <855AE640-1BCF-3A61-A65E-58F5490BFF43> /Users/gurvindersingh/anaconda3/lib/python3.10/site-packages/clidriver/lib/libdb2.dylib
  Expected in:     <47CF44A7-69F5-3878-AD7F-9C572B4E4F8B> /usr/lib/libstdc++.6.dylib

**Comment by bimalkjha** [comment]
@gurvinderguru007 Please provide answer of the questions asked in [issue_template](https://github.com/ibmdb/python-ibmdb/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). For your current problem, check solution in [this comment](https://github.com/ibmdb/python-ibmdb/issues/835#issuecomment-1503772903) and apply it. Thanks.
