### ISSUE TITLE
Cannot connect to db2 instance using API key based authentication

### ISSUE THREAD

**Issue by Patrick-Harned** [ibmdb/python-ibmdb#866]
- Operating System Name:
- db2level output from clidriver if in use:
- Target Db2 Server Version: 11.5.8
- Python Version: 3.8
- ibm_db version: 3.1.0
- For non-Windows, output of below commands:
  uname
  uname -m
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

1. Attempt to connect to db2 using apikey

1. I can connect to the server using apikey based authentication from the server itself:

![image](https://github.com/ibmdb/python-ibmdb/assets/73145124/e1b9a4be-83bb-4c4e-b67c-31c99cccf1b4)

However i cannot using ibm_db

![image](https://github.com/ibmdb/python-ibmdb/assets/73145124/7dd57213-336c-4b08-b762-f74d04da6470)

1. Do I HAVE to use SSL if I am trying to use APIKEY based authentication?

**Comment by bimalkjha** [comment]
@Patrick-Harned Yes, APIKey based authentication is supported over SSL only. Since, you are connecting to bigsql db, I hope you are using SSL port in connection string and you have downloaded the SSL Certificate from server too. In this case, your connection string for ibm_db should be as: 
```
url = "Database=bigsql;Hostname=c-db2u-dv-db2u-engn-svc;Port=50001;Security=SSL;Authentication=GSSPLUGIN;APIKEY=JnZ-Y0cvHrBDZbOMuw_v_lULymLVq9RCFhy9YX7goQbU;SSLServerCertificate=full_path_of_certificate_file;"
```
I think 50000 is the TCPIP port and 50001 should be the SSL port. Thanks.

**Comment by Patrick-Harned** [comment]
@bimalkjha  Is it necessary to include the path of the certificate if the cert is already in the os certificate store?

**Comment by Patrick-Harned** [comment]
![image](https://github.com/ibmdb/python-ibmdb/assets/73145124/230dad09-ec4d-4cb4-ae86-05769bc8bc17)
![image](https://github.com/ibmdb/python-ibmdb/assets/73145124/623837a6-dbf9-4548-8ea1-55273bd651a9)

**Comment by Patrick-Harned** [comment]
1. Not necessary to include cert if the client and server already have the server certificate in the os store. 
2. it is NECESSARY to prepend the username to the api key in my case ( I am using an on-prem CPD installation)
![image](https://github.com/ibmdb/python-ibmdb/assets/73145124/f02f9b2a-b426-45fb-b0e4-fff027c4633c)

**Comment by Patrick-Harned** [comment]
I am not sure why, but 1 hour later when i came back to my computer, the above code stopped working suddenly. Will the SSL connection work if the certificate is self signed?


![image](https://github.com/ibmdb/python-ibmdb/assets/73145124/f266b676-043e-42f1-bf14-0a7cec90f974)

**Comment by bimalkjha** [comment]
@Patrick-Harned The error code 414 means GSK_ERROR_BAD_CERT which tells that your certificate file is wrong. More details about 414 error can be found here: https://www.ibm.com/docs/en/db2/11.5?topic=troubleshooting-common-gskit-errors
```
GSKit: 414

This return code indicates that an incorrectly formatted certificate was received from the partner in an TLS relationship.
This error can be returned in these scenarios:

    You are using self-signed certificates and the certificate is missing.
    The certificate that is being used is from a local certificate authority that does not have the Basic Constraints extension active. 
```
The SSL certificate on Db2 server get created using GSKit command and it get stored into KeyStoreDB on server. So, I am not sure how the certificate will move from keystoredb to os store on server. Yes, certificate can be self-signed or signed by some certificate authority. Both type of certificate works fine.
If client is on windows, ibm_db can read certificate from OS store but for that we need to indicate in connection string that certificate is in OS store using keyword. So, I think you need to get client certificate from Server, store in a file on client system and use its full path in connection string as a value of SSLServerCertificate keyword.
Yes, certificate can be self-signed.

As I shared before, I have used this connection string in past and it worked for me using ibm_db: `url = "Database=bigsql;Hostname=c-db2u-dv-db2u-engn-svc;Port=50001;Security=SSL;Authentication=GSSPLUGIN;APIKEY=JnZ-Y0cvHrBDZbOMuw_v_lULymLVq9RCFhy9YX7goQbU;SSLServerCertificate=full_path_of_certificate_file;"`
Thanks.

**Comment by Patrick-Harned** [comment]
@bimalkjha  Thanks for the help. I realized that the error is caused by using the server certificate rather than the intermediate certificate.
