### ISSUE TITLE
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ibm_db.cpython-311-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length

### ISSUE THREAD

**Issue by santoshnandi** [ibmdb/python-ibmdb#867]
- Operating System Name: MacOS Ventura 13.3.1
- db2level output from clidriver if in use:
- Target Db2 Server Version:
- Python Version: 3.11.4
- ibm_db version: 3.1..4
- For non-Windows, output of below commands:
  uname: Darwin
  uname -m: x86_64
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

1. At the time of creating the connection to db2, ' create_engine' is failing.
2. ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ibm_db.cpython-311-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: <855AE640-1BCF-3A61-A65E-58F5490BFF43> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/clidriver/lib/libdb2.dylib
  Expected in:     <C473C61C-2FFF-3171-BD7A-1C0A3B03B3B6> /usr/lib/libstdc++.6.dylib

**Comment by Earammak** [comment]
@santoshnandi , As discussed in slack, thank you for confirming that it is working after referring the solution given by #831.
