### ISSUE TITLE
ImportError: DLL load failed while importing ibm_db: The specified module could not be found

### ISSUE THREAD

**Issue by LokeshViswa** [ibmdb/python-ibmdb#872]
Hi,
I'm using
Python version: 3.11.0
Ibm_db-3.1.4

I am getting error like ImportError: DLL load failed while importing ibm_db: The specified module could not be found

I am trying in windows PC

Attaching the error image
![IMG_20230719_225547](https://github.com/ibmdb/python-ibmdb/assets/122007613/19f9d4ae-2ace-40fc-872c-d63e9d5f2636)

I installed ibm_db package

Please suggest any solution As soon as possible
@bimalkjha 

It's little bit urgent

**Comment by bimalkjha** [comment]
@LokeshViswa I think your system already has a windows client installed which is causing it. Please run `db2level` command and note down the install directory path from the output of `db2level` command. For example, if db2level shows - `Product is installed at "C:\Program Files\SQLLIB"`, you need to set a system level environment variable `IBM_DB_HOME="C:\Program Files\SQLLIB"` and then install `ibm_db`. It should fix the problem. Thanks.

**Comment by bimalkjha** [comment]
@LokeshViswa Are you able to resolve it? Please update about the issue and let us know to close it. Thanks.

**Comment by LokeshViswa** [comment]
Hi @bimalkjha,

My Issue was solved after setting up the System Level Environmental Variables.

Thanks.
