### ISSUE TITLE
[IBM][CLI Driver] SQL1013N  The database alias name or database name "" could not be found.  SQLSTATE=42705 SQLCODE=-1013

### ISSUE THREAD

**Issue by yvounet14** [ibmdb/python-ibmdb#873]
Already an existing issue, but no answer in it and closed.

- Operating System Name: RHEL 8.4
- db2level output from clidriver if in use: 
DB21085I  This instance or install (instance name, where applicable: "*") uses 
"64" bits and DB2 code release "SQL11058" with level identifier "0609010F".
Informational tokens are "DB2 v11.5.8.0", "special_26260", 
"DYN2301190517AMD64_26260", and Fix Pack "0".

- Target Db2 Server Version: unknown (maybe 10.0)
- Python Version: 3.9
- ibm_db version: 3.1.4
- For non-Windows, output of below commands:
  uname : Linux
  uname -m : X86_64
- Value of below environment variables if set: (
  IBM_DB_HOME:/opt/informix/clidriver
 PATH:/user/MYUSERNAME/public_html/api_rest/env/bin:.:/bin:/usr/bin:/usr/X11R6/bin:/user/MYUSERNAME/bin:/usr/local/bin:/usr/vue/bin:/usr/bin/X11:/opt/ibm/platform_mpi//bin
  LD_LIBRARY_PATH:/opt/informix/clidriver/lib

- Test script to reproduce the problem.
import ibm_db
conn_str = 'hostname=MYHOST;service=4010;database=MYDB;server=MYSERVER;protocol=onsoctcp;EnableScrollableCursors=1;uid=MYUID;pwd=MYPASSWD' ;
ibm_db_conn = ibm_db.connect(conn_str,'','')

- Traceback :
	Exception Value:	[IBM][CLI Driver] SQL1013N  The database alias name or database name "" could not be found.  SQLSTATE=42705 SQLCODE=-1013

- more info :
I tried with clidriver automatically installed when "pip install ibm_db"
I also tried with clidriver downloaded here : https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/
--> same issue for both situation

I am able to connect to this database in php, but with an IBM Informix ODBC Driver Version 4.10.FC5, which is older (2015), on CentOS 6.1
I am able to connect to this database with DbVisualize 14.0, on windows.

Thank you,
Yves

**Comment by imavo** [comment]
If you want to use cldriver then it needs to connect to the informix DRDA port, i.e. Your IDS must have drsoctcp configured correctly to allow this, and your connection string should include the drda alias as configured on the IDS.

Your connection string may need AUTHENTICATION=SERVER;
For clidriver to IDS, use PROTOCOL=TCPIP; 

DbVisualiser is jdbc, i.e it is not using clidriver. Python ibm_db can use clidriver (OR a functional equivalent, but ibm_db does not use jdbc).
