### ISSUE TITLE
SQL30061N The database alias or database name "FILESAP          " was not found at the remote node. when connecting to a remote database server.

### ISSUE THREAD

**Issue by Fertex** [ibmdb/python-ibmdb#874]
- Operating System Name: docker container Linux (FROM python:3.9-slim)
- db2level output from clidriver if in use: Default
- Target Db2 Server Version: unknown 
- Python Version: 3.9
- ibm_db version: 3.1.4
- For non-Windows, output of below commands:
  uname: Linux
  uname -m: X86_64
- Value of below environment variables if set:
  not set

- Test script to reproduce the problem.

               connection_str = "database=FILESAP;hostname={};port={};protocol=tcpip;uid={};pwd={}".format(
                    getenv('AS4_HOST').strip(), 446, getenv('AS4_USER').strip(), getenv('AS4_PASSWORD').strip())

                ibm_con = ibm_db.connect(connection_str, '', '')
                conn = ibm_db_dbi.Connection(ibm_con)

This is the full error printed by ibm_db.connect:
![image](https://github.com/ibmdb/python-ibmdb/assets/48325126/cf0efdba-f6c2-43a5-88aa-cae0603b78c9)

As you could see, the error seems to be the database name; the connection string format its correct but them, when connecting, the library adds some free spaces to the database name string. We test connection to host and port using telnet and it connects successfully.

**Comment by Earammak** [comment]
@Fertex, Please check the databases in that server is there or not. I think you are not using correct database.
Thanks
