### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by louisgrg** [ibmdb/python-ibmdb#882]
- Operating System Name:
> ProductName:		macOS
> ProductVersion:		13.5
> BuildVersion:		22G74

- db2level output from clidriver if in use:

> Traceback (most recent call last):
>   File "/Users/lois/.pyenv/versions/3.8.17_x86_64/bin/detect-secrets", line 8, in <module>
>     sys.exit(main())
>   File "/Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/detect_secrets/main.py", line 41, in main
>     plugins = initialize.from_parser_builder(
>   File "/Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/detect_secrets/plugins/common/initialize.py", line 38, in from_parser_builder
>     from_plugin_classname(
>   File "/Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/detect_secrets/plugins/common/initialize.py", line 181, in from_plugin_classname
>     klass = import_plugins(plugin_filenames)[plugin_classname]
>   File "/Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/detect_secrets/plugins/common/util.py", line 46, in import_plugins
>     module = import_module('detect_secrets.plugins.{}'.format(module_name))
>   File "/Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/detect_secrets/plugins/db2.py", line 17, in <module>
>     raise ie
>   File "/Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/detect_secrets/plugins/db2.py", line 7, in <module>
>     import ibm_db
> ImportError: dlopen(/Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/ibm_db.cpython-38-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
>   Referenced from: <855AE640-1BCF-3A61-A65E-58F5490BFF43> /Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/clidriver/lib/libdb2.dylib
>   Expected in:     <3F5CB4D5-26D1-3E43-B241-2688FF0A67BD> /usr/lib/libstdc++.6.dylib

- Target Db2 Server Version:
command detect-secrets with --db2-scan option (which uses ibm_db python package)
> detect-secrets --version
> 0.13.1+ibm.61.dss

- Python Version:
> python3 --version
> Python 3.8.17

> pip3 --version
> pip 23.2.1 from /Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/pip (python 3.8)

- ibm_db version:
> pip3 show ibm_db
> Name: ibm-db
> Version: 3.1.4
> Summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS
> Home-page: http://pypi.python.org/pypi/ibm_db/
> Author: IBM Application Development Team
> Author-email: praveen.narayanappa1@ibm.com
> License: Apache License 2.0
> Location: /Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages
> Requires:
> Required-by:

- For non-Windows, output of below commands:

uname
> uname
> Darwin

uname -m
> uname -m
> x86_64

- Value of below environment variables if set:

IBM_DB_HOME:
> echo $IBM_DB_HOME
> /Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/clidriver

PATH:
> echo $PATH
> /Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/clidriver/lib:/Users/lois/.pyenv/shims:/Users/lois/.nvm/versions/node/v16.20.2/bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/mqm/bin:/opt/mqm/samp/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/opt/openjdk/bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/mqm/bin:/opt/mqm/samp/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/apache-maven/bin:/opt/SAClientUtil/bin:/opt/rclone

LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:
> echo $LD_LIBRARY_PATH
> /Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/clidriver/lib

> echo $DYLD_LIBRARY_PATH
> /Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/clidriver/lib

- Test script to reproduce the problem.
1 Command executed using `--db2-scan` parameter which is the one that calls `ibm_db` python package:
> detect-secrets scan * --update .secrets.baseline --all-files --use-all-plugins --db2-scan

- For installation related issue, complete output of `pip install ibm_db` command.
No issues have been occurred during `ibm_db` installation on MacOS Rosetta (x86) terminal. My macbook has M1 processor, that is why the need to run a Rosetta (x86 - Intel) terminal. The installation command used was:
>pip3 install ibm_db --no-cache-dir 

Steps to Reproduce:
1.Tried to run the command described above in `Test script to reproduce the problem` section
2.Got the error related with `/usr/lib/libstdc++.6.dylib` described above at `db2level output from clidriver if in use` section

**Comment by bimalkjha** [comment]
@louisgrg Perhaps you have not searched for this problem in closed issue. It is similar to the closed issue #831 . Please check it for solution. You can also refer [this doc](https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#getting-error-and-unable-to-run-test-file) to fix it.
If still unable to resolve it, please share output of `gcc --version` and path of your gcc install directory/lib that contains libstdc++.6.dylib library. Thanks.

**Comment by louisgrg** [comment]
> /usr/local/Cellar/gcc@8/8.5.0/lib/gcc/8

**Comment by louisgrg** [comment]
Hi @bimalkjha , I have searched it first, tried to change the gcc to previous release gcc@12.

Got it working now only with gcc@8 in a Rosetta terminal (x86 - Intel emulation)
Question: Is there a way to fix this issue for new gcc versions like 12 and 14?
Is there any plan to let ibm-db to work with arm64 architecture (Macbook with M1 processor)?

**Comment by bimalkjha** [comment]
@louisgrg Yes, it can work with any version of gcc > 8.3. Currently default path for gcc in libdb2.dylib is of gcc8. You can change it based on the version of gcc installed in the system. Suppose, you have installed gcc v13.1.0 and libstdc++ is available under `/usr/local/Homebrew/Cellar/gcc/13.1.0/lib/gcc/13`, then you need to run below two commands from terminal to fix this issue:
```
cd  /Users/lois/.pyenv/versions/3.8.17_x86_64/lib/python3.8/site-packages/clidriver/lib
install_name_tool -change /usr/local/lib/gcc/8/libstdc++.6.dylib /usr/local/Homebrew/Cellar/gcc/13.1.0/lib/gcc/13/libstdc++.6.dylib libdb2.dylib
```
And run your test program. It should work fine. Thanks.

**Comment by louisgrg** [comment]
Got it, so there is a way to run ibm-db by following this work around you explained. This is great news.
So, I am going to close this issue.
Thank you @bimalkjha!

**Comment by louisgrg** [comment]
I have found a work around to let ibm-db work on a Macbook with M1 processor by using a Rosetta Terminal and gcc@8. There is also a work around to let gcc > 8.3 work with ibm-db python package by running the commands explained above by @bimalkjha.
I am closing this issue.

**Comment by louisgrg** [comment]
I have found a work around to let ibm-db work on a Macbook with M1 processor by using a Rosetta Terminal and gcc@8. There is also a work around to let gcc > 8.3 work with ibm-db python package by running the commands explained above by @bimalkjha.
I am closing this issue.
