### ISSUE TITLE
ImportError: DLL load failed while importing ibm_db: The specified module could not be found

### ISSUE THREAD

**Issue by bobgeorge1st** [ibmdb/python-ibmdb#885]
- Operating System Name: Win10
- db2level output from clidriver if in use: DB2 v11.5.6000.1809
- Target Db2 Server Version: 12
- Python Version: 3.11.4
- ibm_db version: 3.2.0
- Value of below environment variables if set:
  IBM_DB_HOME: `C:\PROGRA~1\IBM\SQLLIB\`
  PATH: `C:\Python3114-64\Scripts\;C:\Python3114-64\;C:\PROGRA~1\IBM\SQLLIB\BIN;C:\PROGRA~1\IBM\SQLLIB\FUNCTION`
  LIB: `C:\PROGRA~1\IBM\SQLLIB\LIB`

I upgraded from 3.1.4 to 3.2.0 and the ibm_db.dll has disappeared from `C:\Python3114-64\Lib\site-packages`

**Comment by bobgeorge1st** [comment]
That didn't work. Here is a code example:

```
import sqlalchemy.exc
import pandas as pd
import os
os.add_dll_directory('C:\\Program Files\\IBM\\SQLLIB\\clidriver')
import ibm_db
import ibm_db_sa

connection_string = f'db2://<user>:<pw>@<connection string>>;PROTOCOL=TCPIP'
engine = sqlalchemy.create_engine(connection_string)
connection = engine.connect()
transaction = connection.begin()

stmnt = 'select * from table fetch first 100 row only'

data = pd.read_sql(stmnt, connection)

print(data)

exit()
```

**Comment by bobgeorge1st** [comment]
Ok, that works, thank you. Is this the only possible solution?

**Comment by Earammak** [comment]
Yes, this is the solution given here.

**Comment by oneroadtotheend** [comment]
Do I definitely need to install the db2 client on this machine?
 I originally wanted to access the db2 database on the remote server. 
Does this path ('C:\Program Files\IBM\SQLLIB\bin') mean that the db2 client should be installed on my computer?

**Comment by bobgeorge1st** [comment]
@oneroadtotheend: Yes, you have to install the db2 client.

**Comment by bobgeorge1st** [comment]
Thank you for the assistance.

**Comment by bimalkjha** [comment]
@bobgeorge1st Installation of db2 client on machine is optional. Since, you already have `C:\Program Files\IBM\SQLLIB\bin` in your system, ibm_db uses it and hence you need to add it using `os.add_dll_directory`. If there is db2 client in the system and db2level do not work i.e. PATH and LIB do not have path of installed client, then ibm_db downloads clidriver automatically under `site_packages`. In that case  you need to add `...\site_packages\clidriver\lib` using os.add_dll_directory. Thanks.

**Comment by bobgeorge1st** [comment]
> @bobgeorge1st Installation of db2 client on machine is optional. Since, you already have `C:\Program Files\IBM\SQLLIB\bin` in your system, ibm_db uses it and hence you need to add it using `os.add_dll_directory`. If there is no db2 client in the system and db2level do not work i.e. PATH and LIB do not have path of installed client, then ibm_db downloads clidriver automatically under `site_packages`. In that case you need to add `...\site_packages\clidriver\lib` using os.add_dll_directory. Thanks.

@bimalkjha : Thanks, again something learnt

**Comment by adeepmalmotra** [comment]
@bimalkjha I have used the below code but I am still getting 

> ImportError: DLL load failed while importing ibm_db: The specified module could not be found.

```
import os
os.add_dll_directory(r'....\Python\Python310\Lib\site-packages\clidriver\lib')
import ibm_db
```

**Comment by bchoudhary6415** [comment]
@adeepmalmotra Please check the path, you need to give bin path not lib path.

Thank you

**Comment by Mavericks334** [comment]
My DLL path based on IBM Client that is installed.


```
importError                               Traceback (most recent call last)
Cell In[6], line 3
      1 import os
      2 os.add_dll_directory (r'C:\Program Files\IBM\SQLLIB\clidriver\bin')
----> 3 import ibm_db

ImportError: DLL load failed while importing ibm_db: The specified module could not be found.

```

IBM_DB. version that i have 3.2.3

**Comment by ksaket1998** [comment]
> You need to add as: os.add_dll_directory('C:\Program Files\IBM\SQLLIB\bin')

This works fine with python code. But does not works when that script gets converted to exe. Can you help how to resolve this
