### ISSUE TITLE
ibm_db_dbi::Error: SystemError(' returned NULL without setting an exception')

### ISSUE THREAD

**Issue by bobgeorge1st** [ibmdb/python-ibmdb#886]
- Operating System Name: Win10
- db2level output from clidriver if in use: DB2 v11.5.6000.1809
- Target Db2 Server Version: 12
- Python Version: 3.11.4
- ibm_db version: 3.1.4
- Value of below environment variables if set:
  IBM_DB_HOME: `C:\PROGRA~1\IBM\SQLLIB\`
  PATH: `C:\Python3114-64\Scripts\;C:\Python3114-64\;C:\PROGRA~1\IBM\SQLLIB\BIN;C:\PROGRA~1\IBM\SQLLIB\FUNCTION`
  LIB: `C:\PROGRA~1\IBM\SQLLIB\LIB`

I tried to bundle the following code with pyinstaller:

```
import sqlalchemy.exc
import pandas as pd
import ibm_db
import ibm_db_sa

connection_string = f'db2://<user>:<pw>>@<connection string>;PROTOCOL=TCPIP'
engine = sqlalchemy.create_engine(connection_string)
connection = engine.connect()
transaction = connection.begin()

stmnt = 'select * from table fetch first 100 row only'

data = pd.read_sql(stmnt, connection)

print(data)

exit()
```

and used the following lines in the pyinstaller .spec-file:

```
    binaries=[(r'C:\\Python3114-64\\Lib\\site-packages\\ibm_db_dlls\\ibm_db.dll', '.\\ibm_db_dlls')],
    datas=[],
    hiddenimports=['ibm_db_sa', 'ibm_db', 'sqlalchemy.sql.default_comparator'],
```

When I start the exe, I get the following error-message:

`sqlalchemy.exc.DBAPIError: (ibm_db_dbi.Error) ibm_db_dbi::Error: SystemError('<built-in function connect> returned NULL without setting an exception')`

It works when i start the py-file.

**Comment by la2yyu** [comment]
same isssu,is there some way to save the problem

**Comment by Earammak** [comment]
@bobgeorge1st I tried your sample example and not able to see the problem. Can you please share here that how to run with exe and Py file.
You can also refer the similar issues which are closed already for this system error.

**Comment by Earammak** [comment]
Hello @bobgeorge1st, 

Please try with the latest version of clidriver https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/v11.5.9/ and python ibm_db of version 3.2.3.


Thanks

**Comment by geekbadm** [comment]
me too, 
When I start the exe, I get the following error-message:

sqlalchemy.exc.DBAPIError: (ibm_db_dbi.Error) ibm_db_dbi::Error: SystemError('<built-in function connect> returned NULL without setting an exception')

It works when i start the py-file.

**Comment by Earammak** [comment]
@geekbadm, 
Can you please share how and where you run this. 
And also share python version, ibm_db version and other details here.

Thanks

**Comment by Earammak** [comment]
Can you please share the update for this ?

**Comment by Earammak** [comment]
@bobgeorge1st, Closing the issue. Let me know if you are facing this issue again. Thanks
