### ISSUE TITLE
DB2 z/OS - ibm-db 3.2.0 connection from Linux Client fails beacuse of a licensing problem

### ISSUE THREAD

**Issue by dverweij-dev** [ibmdb/python-ibmdb#888]
- Environment
Operating System Name: Red Hat Enterprise Linux 8.8 (4.18.0-477.21.1.el8_8.x86_64)
db2level output from clidriver if in use: DB21085I, DB2 v11.5.8.0
Target Db2 Server Version: DB2 12 for z/OS, DSN12015
Python Version: 3.11.2
ibm_db version: 3.2.0
For non-Windows, output of below commands:
  uname: Linux
  uname -m: x86_64
Value of below environment variables if set:
  export PATH=$PATH:$HOME/clidriver/bin
  export IBM_DB_HOME=$HOME/clidriver
  export LD_LIBRARY_PATH=$HOME/clidriver/lib

- Issue 
Upgraded from ibm-db 3.1.4 to 3.2.0 and this results in a connection failure with DB2 on z/OS. Licence key is in the correct location (clidriver/license/db2consv_zs.lic) and the directory and files have the correct permissions. After some fiddling around I noticed that the problem does not occur when I install the package from source an thus forcing a build on my system. The client system I'm using is RHEL 8.8, but I also noticed that the same happens on Ubuntu (20.04.5 LTS).

> Note that connection with DB2 LUW is succesfull in both (a) and (b) install scenario's,

- Test script (db2-ZOS-select.py) to reproduce the problem.
```
import ibm_db
import sys
import os

def getEnvironmentVariable(name):
    value = os.getenv(name)
    if value == None:
        print('Environmentvariable [{}] is not set.'.format(name))
        sys.exit(1)
    else:
        return value

userid = getEnvironmentVariable('DB2_USER')
password = getEnvironmentVariable('DB2_PWD')

conn = ibm_db.connect("DATABASE=DBNNXYZ;HOSTNAME=dbnn.mycompany.nl;PORT=1234;PROTOCOL=TCPIP;UID={};PWD{};".format(userid, password), "", "")

....
....
```
- For installation related issue, complete output of `pip install ibm_db` command.

(a) After installing/upgrading via "pip install --upgrade --no-cache-dir ibm-db" the connection to z/OS fails
```
pip install --upgrade --no-cache-dir ibm-db

Looking in indexes: https://nexus.mycompany.nl/nexus/repository/pypi-group/simple/
Collecting ibm-db
  Downloading https://nexus.mycompany.nl/nexus/repository/pypi-group/packages/ibm-db/3.2.0/ibm_db-3.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 MB 290.4 MB/s eta 0:00:00
Installing collected packages: ibm-db
Successfully installed ibm-db-3.2.0

python ~/db2-ZOS-select.py
Traceback (most recent call last):
  File "/home/testuser/db2-ZOS-select.py", line 16, in <module>
    conn = ibm_db.connect("DATABASE=DBNNXYZ;HOSTNAME=dbnn.mycompany.nl;PORT=1234;PROTOCOL=TCPIP;UID={};PWD={};".format(userid, password), "", "")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968 SQLCODE=-1598
```
(b) When installing the package from source "pip install --no-cache-dir ibm-db --no-binary :all:" and forcing a build on my system, I'm able to succesfully connect to z/OS again

```
pip install --no-cache-dir ibm-db --no-binary :all:

Looking in indexes: https://nexus.mycompany.nl/nexus/repository/pypi-group/simple/
Collecting ibm-db
  Downloading https://nexus.mycompany.nl/nexus/repository/pypi-group/packages/ibm-db/3.2.0/ibm_db-3.2.0.tar.gz (206 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.8/206.8 kB 27.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: ibm-db
  Building wheel for ibm-db (pyproject.toml) ... done
  Created wheel for ibm-db: filename=ibm_db-3.2.0-cp311-cp311-linux_x86_64.whl size=427355 sha256=5e1349a4a3bcf4d259e881bc542d3769c525b92faacad3f59235ba83148fdf40
  Stored in directory: /tmp/pip-ephem-wheel-cache-2x9aytzp/wheels/cb/7f/f3/7b84a29552f41e0c5ff970a78fcbe2ae02cca1c7d66ae58d4b
Successfully built ibm-db
Installing collected packages: ibm-db
Successfully installed ibm-db-3.2.0

python ~/db2-ZOS-select.py
COUSR01,T01 ë € £ $ ¢ ₡ ₢ ₣ ₤ ₥ ₦ ₧ ₨ ₩ ₪ ₫ ₭ ₮ ₯ ₹
COUSR02,Test UTF-8 encoding-€-€-€-€-€-€-€-₫-₭-₮-₯-₹-abcdefghij-Z
...
```
- Steps to Reproduce the problem:

1. install clidriver in $HOME and place z/OS license key (db2consv_zs.lic) in subdirectory clidriver/license 
2. create venv: python3.11 -m venv venv-py311
3. source venv-py311/bin/activate
4. pip install --upgrade --no-cache-dir pip wheel setuptools
5. export PATH=$PATH:$HOME/clidriver/bin
6. export IBM_DB_HOME=$HOME/clidriver
7. export LD_LIBRARY_PATH=$HOME/clidriver/lib
8. pip install --upgrade --no-cache-dir ibm-db
9. python db2-ZOS-select.py

**Comment by bimalkjha** [comment]
@dverweij-dev ibm_db==3.2.0 added wheel support for Linux, MacOS and Windows platforms. When ibm_db get installed from wheel, the *.whl file comes with its own clidriver and precompiled ibm_db.so is linked with this clidriver. So, when not installed from source, you can find clidriver under site_packages. Copy license file under `site_packages\clidiver\license` directory and then run test file. Thanks.

**Comment by dverweij-dev** [comment]
@bimalkjha Thanks for your explanation! I placed the license file in the site_packages\clidiver\license directory and things are working fine now.
