### ISSUE TITLE
unable to download driver

### ISSUE THREAD

**Issue by Gurjit86** [ibmdb/python-ibmdb#891]
It seems that https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz is returning a 500 error. Can team restore the links for linux drivers ?

**Comment by jammurp** [comment]
Also hitting the same error as of a couple hours ago.

**Comment by bimalkjha** [comment]
@Gurjit86 @jammurp Informed the concerned person to check and fix the link. It should get restored soon.
I think you are still using older version of ibm_db so hitting this issue. Newer version has logic to download it from https://github.com/ibmdb/db2drivers/tree/main/clidriver if public.dhe.ibm.com link is down for maintenance or broken. Thanks.

**Comment by jammurp** [comment]
@bimalkjha thanks, I can see the links have been restored here: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/
