### ISSUE TITLE
Fetch multiple records from result set

### ISSUE THREAD

**Issue by surya18091997** [ibmdb/python-ibmdb#895]
**Is your feature request related to a problem? Please describe.**
I see that the fetchall method and even fetchmany , is getting data one by one records from result set . Why so when i see sqlalchemy and all can fetch all records at once.

**Describe the solution you'd like**
Fetch all the records at once or fetch only the chunk size.

**Comment by bimalkjha** [comment]
@surya18091997 Where you see fetchall method do not return all rows at once? Could you please share test program to show that? Thanks.
