### ISSUE TITLE
Windows PC - Python - ibm-db 3.20 - sqlachemy: connection fails because a licensing problem

### ISSUE THREAD

**Issue by SandorSzalma1** [ibmdb/python-ibmdb#897]
I have seen a similar issue with Linux but it did not help to resolve my problem.

- Operating System Name: Windows 10
- db2level output from clidriver if in use: 11.5.40000
- Target Db2 Server Version: 11.5.x
- Python Version: 3.11.5
- ibm_db version: 3.2.0

- Test script to reproduce the problem.
I have installed the license file here:
`C:\Users\Cxxx\.conda\envs\db2\Lib\site-packages\clidriver\license\db2consv_zs.lic`

```
import os
if os.name == 'nt':
    os.add_dll_directory('C:\Program Files\IBM\SQLLIB\\BIN')

from urllib.parse import quote
from sqlalchemy import create_engine

connect_str = f"db2+ibm_db://{username}:{quote(password)}@{hostname}:{port}/{database};"

db_engine = create_engine(connect_str, echo=True)
db_engine.connect()
```

Error message:
```
  File "C:\Users\Cxxx\.conda\envs\db2\Lib\site-packages\ibm_db_dbi.py", line 634, in connect 
    raise _get_exception(inst)
sqlalchemy.exc.ProgrammingError: (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968  SQLCODE=-1598
```

- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

1.  create, activate conda environment, install ibm_db package, add license file
2.  execute python code
3.

**Comment by bimalkjha** [comment]
@SandorSzalma1 Since you added dll directory as `C:\Program Files\IBM\SQLLIB\BIN`, you need to copy license file under `'C:\Program Files\IBM\SQLLIB\license` directory. Thanks.

**Comment by SandorSzalma1** [comment]
@bimalkjha Thank you for your quick reply! 
I cannot add files to this folder on my company managed PC. 
Is there an other way?

**Comment by bimalkjha** [comment]
@SandorSzalma1 Then update your code to add clidriver dll directory as:
os.add_dll_directory('C:\\Users\\Cxxx\\.conda\\envs\\db2\\Lib\\site-packages\\clidriver\\bin'). Thanks.

**Comment by SandorSzalma1** [comment]
@bimalkjha thank you, it is working now!
