### ISSUE TITLE
ibm_db_dbi::DatabaseError: Failed to LOB Data: Error occurred in SQL Call Level Interface SQLSTATE=HY021 SQLCODE=-999

### ISSUE THREAD

**Issue by sgonchigar** [ibmdb/python-ibmdb#900]
- Operating System Name: IBMi V7R4
- db2level output from clidriver if in use:
- Target Db2 Server Version: DB2400
- Python Version: 3.6
- ibm_db version:  2.0.5.12 
- For non-Windows, output of below commands:
  uname: OS400
  uname -m   0078000508B1
- Value of below environment variables if set:
  IBM_DB_HOME: not set
  PATH: /QOpenSys/pkgs/bin:/QOpenSys/pkgs/bin:/usr/bin:.:/QOpenSys/usr/bin
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: 

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:

1. RPGLE pgm ---> write to input Data Q  ---> py script reading from input Data Q and writing to output Data Q ---> RPGLE (read output Data Q) 
2. RPGLE pgm ---> 15,336 writes ---->  py script reading from Data Q and 15, 336 writes,  py script errored with this message
ibm_db_dbi::DatabaseError: Failed to LOB Data: Error occurred in SQL Call Level Interface SQLSTATE=HY021 SQLCODE=-999 

```
import ibm_db_dbi as db2
 options = {
        db2.SQL_ATTR_TXN_ISOLATION: db2.SQL_TXN_NO_COMMIT,
        db2.SQL_ATTR_DBC_SYS_NAMING: db2.SQL_TRUE
    }

    conn = db2.connect("DATABASE=*LOCAL")
    conn.set_option(options)

    cur = conn.cursor()
    receive_data_queue = """ 
        select MESSAGE_DATA
        from TABLE(QSYS2.RECEIVE_DATA_QUEUE(
                        DATA_QUEUE => '{inputKeyedDqName}', 
                        DATA_QUEUE_LIBRARY => '{keyedDqLib}',
                        WAIT_TIME => -1,
                        KEY_ORDER => 'EQ',
                        KEY_DATA => cast('{dQKey}' as char({dQKeyLen}))
                        )) limit 1
        """.format(inputKeyedDqName = inputKeyedDqName
                    ,keyedDqLib=keyedDqLib
                    ,dQKey=dQKey
                    ,dQKeyLen=dQKeyLen)
   
 
    print("waiting for first entry...")

    while True:
          try:
                 cur.execute(receive_data_queue)
                 row = cur.fetchone()
                 ....... process the input
                 
                 cur = conn.cursor()
                send_data_queue = """ 
                         CALL QSYS2.SEND_DATA_QUEUE(MESSAGE_DATA => '{outputStr}',
                                    DATA_QUEUE => '{outputKeyedDqName}', 
                                    DATA_QUEUE_LIBRARY => '{keyedDqLib}',
                                    KEY_DATA => cast('{dQKey}' as char({dQKeyLen}))
                                )
               """.format(outputKeyedDqName =outputKeyedDqName
                    ,keyedDqLib=keyedDqLib
                    ,dQKey=dQKey
                    ,dQKeyLen=dQKeyLen
                    ,outputStr=outputStr)

              cur.execute(send_data_queue)

          except Exception as err:
            print("Error on Fetch", err)
            #..close the cursor and connection.
            cur.close()
            conn.close()
            break
          
         print("waiting for next entry...") 
    
Appreciate any help. Thank you!

**Comment by imavo** [comment]
Does this symptom recreate on demand? 
If it does, please can you take a CLI trace , and append relevant section here?
Use the clidriver tool called `db2trc` as follows in a shell:


db2trc on -cli -f hy021.dmp

now run your python script until it fails with the symptom you reported, then:

db2trc off

db2 fmt -cli hy021.dmp  hy021.txt


The resulting file (e.g. hy021.txt) is plain text, and will show the SQLGetData() that is returning the SQL_ERROR that triggers your symptom - but it will hopefully also show the types of the arguments, which will be needed to find root cause, along with other useful information.

**Comment by bimalkjha** [comment]
@sgonchigar Could you please collect the traces as mentioned by imavo and share here? Thanks.

**Comment by sgonchigar** [comment]
This is now resolved. sorry didn't close this.  you can see the updates here
https://github.com/kadler/python-ibmdb/issues/12
