### ISSUE TITLE
Error when installing ibm_db 

### ISSUE THREAD

**Issue by varunkumarmnnit** [ibmdb/python-ibmdb#901]
i am using below python version 3.10.4 and pip version is below 22.0.4 my requirements file is 
ibm-db==3.1.1
redshift-connector==2.0.905
pymongo==4.0.2
pandas~=1.4.1
requests==2.27.1
mysql-connector-python==8.0.28
confluent_kafka==1.8.2
SQLAlchemy==1.4.34

But I am getting below error while installing IBM db 

creating build/lib.linux-x86_64-3.10/confluent_kafka/avro/serializer
      copying src/confluent_kafka/avro/serializer/__init__.py -> build/lib.linux-x86_64-3.10/confluent_kafka/avro/serializer
      copying src/confluent_kafka/avro/serializer/message_serializer.py -> build/lib.linux-x86_64-3.10/confluent_kafka/avro/serializer
      running build_ext
      building 'confluent_kafka.cimpl' extension
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/tmp
      creating build/temp.linux-x86_64-3.10/tmp/pip-install-xss16iwg
      creating build/temp.linux-x86_64-3.10/tmp/pip-install-xss16iwg/confluent-kafka_69965faf08b343a6a6672cdb4ed8a36c
      creating build/temp.linux-x86_64-3.10/tmp/pip-install-xss16iwg/confluent-kafka_69965faf08b343a6a6672cdb4ed8a36c/src
      creating build/temp.linux-x86_64-3.10/tmp/pip-install-xss16iwg/confluent-kafka_69965faf08b[343](https://gitlab.frg.tech/brands-services/wms-gridiron/-/jobs/8436841#L343)a6a6672cdb4ed8a36c/src/confluent_kafka
      creating build/temp.linux-x86_64-3.10/tmp/pip-install-xss16iwg/confluent-kafka_69965faf08b343a6a6672cdb4ed8a36c/src/confluent_kafka/src
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.10 -c /tmp/pip-install-xss16iwg/confluent-kafka_69965faf08b343a6a6672cdb4ed8a36c/src/confluent_kafka/src/Admin.c -o build/temp.linux-x86_64-3.10/tmp/pip-install-xss16iwg/confluent-kafka_69965faf08b343a6a6672cdb4ed8a36c/src/confluent_kafka/src/Admin.o
      In file included from /tmp/pip-install-xss16iwg/confluent-kafka_69965faf08b343a6a6672cdb4ed8a36c/src/confluent_kafka/src/Admin.c:17:
      /tmp/pip-install-xss16iwg/confluent-kafka_69965faf08b343a6a6672cdb4ed8a36c/src/confluent_kafka/src/confluent_kafka.h:23:10: fatal error: librdkafka/rdkafka.h: No such file or directory
         23 | #include <librdkafka/rdkafka.h>
            |          ^~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> confluent_kafka
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: You are using pip version 22.0.4; however, version 23.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

**Comment by bimalkjha** [comment]
@varunkumarmnnit Please provide below information:
1. In your pasted error, we do not see `ibm_db` anywhere. How you concluded that it is issue with ibm_db?
2. You have not shared complete output of `pip install ibm_db` command. Partial output gives partial info only and without complete info, it is difficult to provide any suggestion.
3. ibm_db v3.1.1 is old and use `ibm-db==3.2.1` which may solve your issue. Share result here.
Thanks.
