### ISSUE TITLE
DLL Import Setup Issue

### ISSUE THREAD

**Issue by byegates** [ibmdb/python-ibmdb#903]
- Operating System Name: Windows 10 Enterprise
- db2level output from clidriver if in use: 
- Target Db2 Server Version:
- Python Version: 3.11.7
- ibm_db version: 3.2.1

I was wondering why do we have to hard code DLL lib in python code? We used to be able to use clidriver without the need to explicitly hardcode/import DLL lib.
I am building python scripts for users without programming knowledge to use, their python are installed in different ways, therefore their clidriver location are different, I had to ask them to manually check clidriver location and update python code before using it, which adds lots of overhead, any suggestions?

**Comment by bimalkjha** [comment]
The **os.add_dll_directory()** function is part of the `os` module in Python (introduced in **Python 3.8**), and it is used to add a directory to the DLL (Dynamic Link Library) search path. This function is particularly useful when working with third-party DLLs or shared libraries that your Python application depends on.

Before Python 3.8, the DLL search path was influenced by the **PATH** environment variable. However, this could lead to issues, especially when Python was embedded in larger applications. The **os.add_dll_directory()** function was introduced to provide a more controlled and isolated way of managing the DLL search path.

Here's a basic example of how to use `os.add_dll_directory()`:

```python
import os

# Add a directory to the DLL search path
dll_directory = r'C:\Path\To\Your\DLLs'
os.add_dll_directory(dll_directory)

# Now, when loading a DLL or using ctypes, the specified directory is considered in the search path
```
This function is particularly useful when dealing with scenarios where the DLLs needed by your Python application are not in the system's default search paths. By using **os.add_dll_directory()**, you can ensure that the specified directory is considered when resolving DLL dependencies.

It's important to note that this function is available only in **Python 3.8** and later versions. If you're working with an earlier version of Python, you might need to consider alternative approaches or upgrade to a newer Python version.

Thanks.
