### ISSUE TITLE
Testing fetch functions listed in Python documentation results in CEE3204S error.

### ISSUE THREAD

**Issue by vganich** [ibmdb/python-ibmdb#909]
- Operating System Name: z/OS
- db2level output from clidriver if in use: N/A
- Target Db2 Server Version: N/A
- Python Version:  v3.11.2
- ibm_db version: v3.1.4
- For non-Windows, output of below commands:
  uname        N/A
  uname -m  N/A
- Value of below environment variables if set:
  IBM_DB_HOME: N/A
  PATH: N/A
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: N/A

Trying to test examples from:

https://www.ibm.com/docs/en/ias?topic=SSHRBY/com.ibm.swg.im.dbclient.python.doc/doc/t0054388.htm

The only example which is working is "fetch_tuple.py". 

All other examples issue the errors such as:

% fetch_assoc.py ND0
CEE3204S The system detected a protection exception (System Completion Code=0C4).
From entry point PyDict_SetItem at compile unit offset +0000000027561B64 at entry offset +0000000000000044 at address 0000000027561B64.
[1] + Done(139) fetch_assoc.py ND0
50793680 Segmentation violation ./fetch_assoc.py

**Comment by bchoudhary6415** [comment]
Hello @vganich 
Please share the output of 
chtag -p fetch_assoc.py and also similar to your all python examples.

Also I created below sample program for the four functions you asked for and it's working for me.
Can you please try running below example in your system and share the output?

example -:
```
import ibm_db

def connect_to_database():
    conn = ibm_db.connect('', '','')
    return conn

def create_table(conn):
    sql = "CREATE TABLE EMPLOYEE (id INT, name VARCHAR(255))"
    stmt = ibm_db.exec_immediate(conn, sql)
    ibm_db.free_result(stmt)
    print("\nTable EMPLOYEE created successfully!")

def insert_record(conn, id, name):
    sql = f"INSERT INTO EMPLOYEE (id, name) VALUES ({id}, '{name}')"
    stmt = ibm_db.exec_immediate(conn, sql)
    ibm_db.free_result(stmt)

def drop_table(conn, table_name):
    sql = f"DROP TABLE {table_name}"
    stmt = ibm_db.exec_immediate(conn, sql)
    ibm_db.free_result(stmt)
    print("\nTable " + table_name + " dropped successfully!")

def fetch_bothFun(conn):
    print("\nPrint data using ibm_db.fetch_both:- ")
    sql = "SELECT * FROM EMPLOYEE"
    stmt = ibm_db.exec_immediate(conn, sql)
    dictionary = ibm_db.fetch_both(stmt)
    while dictionary:
        print("The ID is : ", dictionary[0])
        print("The Name is : ", dictionary[1])
        dictionary = ibm_db.fetch_both(stmt)

def fetch_tupleFun(conn):
    print("\nPrint data using ibm_db.fetch_tuple:- ")
    sql = "SELECT * FROM EMPLOYEE"
    stmt = ibm_db.exec_immediate(conn, sql)
    tuple = ibm_db.fetch_tuple(stmt)
    while tuple != False:
        print("The ID is : ", tuple[0])
        print("The name is : ", tuple[1])
        tuple = ibm_db.fetch_tuple(stmt)

def fetch_assocFun(conn):
    print("\nPrint data using ibm_db.fetch_assoc:- ")
    sql = "SELECT * FROM EMPLOYEE"
    stmt = ibm_db.exec_immediate(conn, sql)
    dictionary = ibm_db.fetch_assoc(stmt)
    while dictionary:
        print("The ID is : ", dictionary['ID'])
        print("The name is : ", dictionary['NAME'])
        dictionary = ibm_db.fetch_assoc(stmt)

def result_Set(conn):
    print("\nFetch columns from a result set:- ")
    sql = "SELECT * FROM EMPLOYEE"
    stmt = ibm_db.exec_immediate(conn, sql)
    while ibm_db.fetch_row(stmt):
        print("The Employee number is : ", ibm_db.result(stmt, 0))
        print("The name is : ", ibm_db.result(stmt, 1))


def main():
    conn = connect_to_database()

    create_table(conn)
    insert_record(conn, 1, "Alice")
    insert_record(conn, 2, "Bob")
    insert_record(conn, 3, "Jane")
    fetch_bothFun(conn)
    fetch_tupleFun(conn)
    fetch_assocFun(conn)
    result_Set(conn)
    drop_table(conn, "EMPLOYEE")
    ibm_db.close(conn)

if __name__ == "__main__":
    main()
```
Thank you

**Comment by bchoudhary6415** [comment]
@vganich 
Please update on this issue?

Thanks

**Comment by bchoudhary6415** [comment]
Hello @vganich
Have you tried running above sample program?
If yes, than did you see any error in running the program?
Can you please update, if you don't see any issue
will go for closing this issue?

Thanks

**Comment by bchoudhary6415** [comment]
@vganich As we discussed on mail, so closing this issue for now.
Thanks

**Comment by bimalkjha** [comment]
Closing the issue as per email discussion with Balram.
 Thanks
