### ISSUE TITLE
Support updating database attributes and configuration

### ISSUE THREAD

**Issue by kuwv** [ibmdb/python-ibmdb#910]
### Is your feature request related to a problem? Please describe.

DB2 does not have any remote management capabilities as you would typically find in other databases. Installing the `db2` command requires a complete database installation. For example, PostGRES can be easily managed remotely with just the `psql` command.

There is no corresponding methodology that can automate without local access to the database:

```shell
db2 update db cfg for sample using maxappls 50
```

This deficiency makes it difficult to automate DB2 at scale.

### Describe the solution you'd like

Provide the database update capabilities available to the `db2` CLI.

### Describe alternatives you've considered

- installation the `db2` CLI commands requires a full database installation
- no DB2 (community) CLI container exists within ICR.
- IBM ODBC driver does not establish non-database specific connections (meaning a default database must exit and ODBC must connect to it).
- `idm-db` create create databases but cannot update `maxappls` or any other attributes

### Additional context

Apologies if I am incorrect in my assessment. Please outline an alternative if possible.

https://www.ibm.com/docs/en/db2/11.5?topic=commands-update-database-configuration

**Comment by bimalkjha** [comment]
@kuwv The capability you are looking for comes with only Db2 Server or Client installations, not with driver installation. clidrivrer and dsdriver are drivers which is used to send SQL on server and return the response received from Db2 server to applicaiton.

You can see the different types of Db2 Installers here: https://www.ibm.com/support/pages/node/7071342
![image](https://github.com/ibmdb/python-ibmdb/assets/11818648/9d2a06a8-1246-4640-8f03-64b3ab665939)

You can download and install any installer from "Client" or "Server".  "db2" command line utility comes with Client and Server installers only. Only "db2" command line utility can be used to update database and configuration attributes as these commands requires db2 instance.

You can check details about which db2 client and driver types comes with what capabilities here: https://www.ibm.com/docs/en/db2/11.5?topic=overviews-data-server-clients
Only "IBM Data Server Runtime Client" and "IBM Data Server Client" installations has the feature that you are looking for.

After installation of Db2 Client, you can set system level environment variable `IBM_DB_HOME=full path of db2 install directory` and then install python driver using `pip install ibm_db --no-binary :all: --no-cache-dir` command. It will use the installed client and you can use db2 commands from db2cmd command prompt too.

Hence, this request does not apply for python driver. I am closing this request. Thanks.

**Comment by bimalkjha** [comment]
@kuwv If you are not satisfied with my reply and still want such features in IBM Data Server Driver Package, you can open an idea here: https://ibm-data-and-ai.ideas.ibm.com/?project=INFX to get detailed info from IBM. But, my gut feeling is IBM will also suggest to use Runtime Client for such features as Drivers is not meant for database administration. python ibm_db uses `IBM Data Server Driver`/ `IBM ODBC Driver` internally and can not provide a feature which is not supported by IBM Data Server Driver or clidriver. Thanks.
