### ISSUE TITLE
Unable to execute a command

### ISSUE THREAD

**Issue by rachelshirin007** [ibmdb/python-ibmdb#912]
- Operating System Name: Windows
- db2level output from clidriver if in use:
- Target Db2 Server Version: DB2 on cloud
- Python Version: Python 3.10.11
- ibm_db version: 3.2.1

- Value of below environment variables if set:
IBM_DB_HOME: C:\Users\kotav\Downloads\v11.5.4_ntx64_odbc_cli\clidriver\bin
PATH:
LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: C:\Users\kotav\Downloads\v11.5.4_ntx64_odbc_cli\clidriver\lib

- Test script to reproduce the problem.
- For installation related issue, complete output of `pip install ibm_db` command.

Steps to Reproduce:
"select * from impacted_tools" works fine but 

            cur2.execute("select * from impacted_servers where tools_id in %s ", [tools_id])

gives an error

> ibm_db_dbi::ProgrammingError: Statement Execute Failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0104N  An unexpected token "from impacted_servers where tools_id" was found following "select * ".  Expected tokens may include:  "<space>".  SQLSTATE=42601  SQLCODE=-104

Please help me on this

**Comment by bchoudhary6415** [comment]
Hello @rachelshirin007 
Your IBM_DB_HOME path is up to clidriver, don't include bin folder
It should be - C:\Users\kotav\Downloads\v11.5.4_ntx64_odbc_cli\clidriver.

Please run and check "select * from impacted_servers" is working or not.

Also I'm not getting what [tools_id] represents here, is it list like
"select * from impacted_servers where tools_id in [100,120, 135, 160,....]"

Also %s is not sql syntax, it's python syntax.
try giving correct sql, I don't have any idea what columns does impacted_servers have and what is [tools_id] here

Please refer the example for ibm_db.execute() API from - https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbexecute


Thanks
