### ISSUE TITLE
IBMDB apache 2.0 licence for other systems

### ISSUE THREAD

**Issue by TailorSoftHungary** [ibmdb/python-ibmdb#914]
Hello,

Is IBM not planning to make the IBMDB library available to other systems? It would make the work of freelance developers much easier.

**Comment by bimalkjha** [comment]
@TailorSoftHungary What do you mean by other systems? Could you please share name of some of such other systems?
ibm_db is available on pypi.org as a python package and it can be installed on any x64 system using `pip install ibm_db` command. ibm_db do not work on arm64 architecture. To support arm64 architecture, work is in progress. Thanks.

**Comment by TailorSoftHungary** [comment]
I have read readme page and i found this:
Connection to Db2 for z/OS or Db2 for i(AS400) Server using ibm_db driver from distributed platforms (Linux, Unix, Windows and MacOS) is not free. It requires either client side or server side license.

**Comment by TailorSoftHungary** [comment]
This is not open source pakage...

**Comment by bimalkjha** [comment]
@TailorSoftHungary This license is required by IBM ODBC/CLI Driver. ibm_db uses IBM ODBC driver for connectivity.
If you have a working odbc driver that connects to your server, you can set IBM_DB_HOME env var to this driver install directory and then install ibm_db.
IBM ODBC/CLI driver is not open source and hence they need license. ibm_db driver do not need. If odbc driver fails to connect to server, ibm_db too will fail. ibm_db has not implemented DRDA protocol but calls ODBC APIs from the ODBC driver for connectivity.
Apache 2.0 is for the code which is part of ibm_db not for the third party libraries used by ibm_db. Thanks.
