### ISSUE TITLE
ibm_db_dbi::DatabaseError: Binding Error:

### ISSUE THREAD

**Issue by sleakehe** [ibmdb/python-ibmdb#916]
Hello,

I'm trying to use SQLAlchemy & ibm_db to execute a stored procedure in a DB2 LUW database and then capture the output parameter values. I can't figure out the correct syntax to do this and I would be grateful if someone could point me in the right direction.

From what I've read, creating a few bindparam(isoutparam=True) should allow me to capture the output, but when I run the code below, it raises `sqlalchemy.exc.DatabaseError: (ibm_db_db.DatabaseError) ibm:db_dbi::DatabaseError: Binding Error:`
```import sqlalchemy

engine = sqlalchemy.create_engine("db2+ibm_db://userName:password@host:portNumber/database;")
stmt = sqlalchemy.text("CALL schema.MY_PROC('input1',1,CURRENT_TIMESTAMP,NULL,:out1,:out2,:out3,:out4)")

# raises ibm_db_dbi::DatabaseError: Binding Error
with engine.connect() as conn:
    out1 = sqlalchemy.sql.expression.bindparam(key='out1', value=0, type=sqlalchemy.Integer(), isoutparam=True)
    out2 = sqlalchemy.sql.expression.bindparam(key='out2', value='', type=sqlalchemy.String(), isoutparam=True)
    out3 = sqlalchemy.sql.expression.bindparam(key='out3', value=0, type=sqlalchemy.Integer(), isoutparam=True)
    out4 = sqlalchemy.sql.expression.bindparam(key='out4', value='', type=sqlalchemy.String(), isoutparam=True)

    result = conn.execute(stmt, parameters={'out1': out1, 'out2': out2, 'out3': out3, 'out4': out4}).fetchall()
```

If I run it like this instead, the stored proc will actually execute but I can't capture the output when I try any of the fetch methods. They all raise `ResourceClosedError: This result object does not return rows. It has been closed automatically.`
```
import sqlalchemy

engine = sqlalchemy.create_engine("db2+ibm_db://userName:password@host:portNumber/database;")
stmt = sqlalchemy.text("CALL schema.MY_PROC('input1',1,CURRENT_TIMESTAMP,NULL,:out1,:out2,:out3,:out4)")

#rasises sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.

with engine.connect() as conn:
    result = conn.execute(stmt, parameters={'out1': 0, 'out2': '', 'out3': 0, 'out4': ''}).fetchall()
```

**Versions:**
**Python packages** 
- SQLAlchemy==2.02
- ibm-db==3.2.0
- ibm-db-sa==0.4.0

**DB2** - v11.5.6.0

**Comment by bchoudhary6415** [comment]
Hello @sleakehe 
You need to import ibm_db,
Also ibm_db does not have fetchall() API, you should try using another APIs such as
[ibm_db.fetch_tuple](https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbfetch_tuple)
[ibm_db.fetch_assoc](https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbfetch_assoc)
[ibm_db.fetch_both](https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbfetch_both)
[ibm_db.fetch_row](https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbfetch_row)

Also you can refer this link - https://github.com/ibmdb/python-ibmdb/wiki/APIs for the ibm_db APIs.

Thank you

**Comment by sleakehe** [comment]
@bchoudhary6415 Thanks for taking a look. Can this not be done through SQLAlchemy alone? I'm trying to stick with SQLAlchemy because, as far as I understand, the ibm_db connections are not thread safe. I'm trying to execute a bunch of stored procs in a multi-threaded fashion and I know checking a connection out of the pool from a SqlAlchemy engine is thread-safe.
