### ISSUE TITLE
CI version mismatches causing 3.12 wheels to not be uploaded

### ISSUE THREAD

**Issue by shenanigansd** [ibmdb/python-ibmdb#918]
Hi! Congratulations on your release!
Unfortunately, there are two bugs with the release CI causing only a single Python 3.12 wheel to actually be uploaded.

### Artifacts v4

[GitHub has released v4](https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/) of `actions/{up,down}load-artifact`.
This new version is _not_ compatible with the old version, artifacts created with v4 can _not_ be downloaded by v3.
#913 bumped _only_ the 64-bit Windows job to v4: https://github.com/ibmdb/python-ibmdb/pull/913/files#diff-1b7eb3935d8d296cce84d4f92938e799bc698588bbbf7e624f2fbda0ef4e041fR28
All other instances, including the one that actually downloads the artifacts and uploads them to PyPI, is still on v3, so it wasn't able to see the artifact that v4 uploaded, resulting in the 64-bit Windows wheels being missed entirely.

### cibuildwheel v2.15.0

cibuildwheel enabled building wheels for Python 3.12 by default in v2.15.0.
The 32-bit and 64-bit Windows jobs were bumped to v2.16.5, which is currently the latest version, but the job for Mac OS and Linux was left at v2.12.2, which does _not_ build 3.12 wheels by default, causing the 3.12 wheels for Mac OS and Linux to not even be built.

**Comment by shenanigansd** [comment]
Thanks for the quick merges @bimalkjha!
This is holding up an upgrade at work, are you able to create a new release now so the wheels can get generated?

**Comment by bimalkjha** [comment]
@shenanigansd Released ibm_db==3.2.3. Please try it. Thanks.
