### ISSUE TITLE
Connection timeout property at client side

### ISSUE THREAD

**Issue by akashbogam** [ibmdb/python-ibmdb#923]
I'm connecting my db2 server using ibm_db python client, but after 60 sec of idle connection, connection is closed.

Can we have a connection timeout property in ibm_db python client

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by bimalkjha** [comment]
From Akash Bogam on Slack:
Hi Bimal,
my issue was related to haproxy configuration
it got resolved by setting out connect timeout parameters for client and server in haproxy.cfg file
thanks for your time and support 🙂 
haproxy : https://futuretechnoindia.medium.com/what-is-haproxy-and-how-to-install-and-configure-in-linux-526621e02aa8#:~:text=HAProxy%20(High%20Availability%20Proxy)%20is,capability%20of%20a%20single%20server.
