### ISSUE TITLE
ibm_db.callproc should return the stored procedures return value

### ISSUE THREAD

**Issue by sleakehe** [ibmdb/python-ibmdb#925]
**Is your feature request related to a problem? Please describe.**
ibm_db.callproc() currently returns a statement object that can be used to access result sets, and the in/out arguments. However, if the stored procedure returns some custom value via a RETURN statement, there is no way to capture that value.

Example proc:
```
CREATE OR REPLACE PROCEDURE check_odd_day ()
LANGUAGE SQL
BEGIN
    DECLARE current_day INT;
    DECLARE result INT;
    
    -- Get the current day
    SET current_day = DAY(CURRENT DATE);
    
    -- Check if the current day is odd
    IF MOD(current_day, 2) <> 0 THEN
        SET result = 1000;
    ELSE
        SET result = 2000; 
    END IF;
    
    RETURN result;
END
```
**Describe the solution you'd like**
I'd like ibm_db.callproc() to return the stored procedures return value.

**Comment by bchoudhary6415** [comment]
Hello @sleakehe 
Please check the examples of ibm_db.callproc: https://github.com/ibmdb/python-ibmdb/wiki/APIs#ibm_dbcallproc.
As you are suggesting that ibm_db.callproc() return the stored procedure return value,
Can you please share a sample script for how ibm_db.callproc() can return the stored procedure return value and be able to display the output?

Please try to give sample output also, so that we can make progress on this enhancement part if required.

Thanks

**Comment by Earammak** [comment]
@sleakehe, Can you please share the update for this?
Thanks

**Comment by Earammak** [comment]
@sleakehe, As we already shared a example link with you that giving output value of stored procedure return value.
 Please refer the below example:
`
import ibm_db
crsp = '''CREATE OR REPLACE PROCEDURE check_odd_day (OUT result INT)
LANGUAGE SQL
BEGIN
    DECLARE current_day INT;
    
    -- Get the current day
    SET current_day = DAY(CURRENT DATE);
    
    -- Check if the current day is odd
    --IF MOD(current_day, 2) <> 0 THEN
        SET result = 55000;
    ELSE
        SET result = 2000; 
    END IF;
    RETURN result;
END
'''
conn=ibm_db.connect(conn_str,'','')
sp_create = ibm_db.exec_immediate(conn, crsp)
out = 0
stmt, out=ibm_db.callproc(conn,'check_odd_day',(out,))
print(out)`


As of now we are closing this issue, if you face any issue feel free to reopen the issue.
Thanks
