### ISSUE TITLE
How to connect to DB2 using .JKS file as I connect from DB manager

### ISSUE THREAD

**Issue by shubsi33** [ibmdb/python-ibmdb#926]
I have driver installed here where .jar files are there as below:
Path where I have drivers: C:\Users\Myuser\Downloads\db2java\db2java
db2jcc_license_cisuz.jar
db2jcc_license_cu.jar
db2jcc.jar
db2jcc4.jar

I have .JKS file in this path: C:\Users\Myuser\Downloads\DEV.jks

with this .JKS file I can connect to DB from DB manager with  below url.
jdbc:db2://<hostname>:<port>/<dbname>:sslConnection=true;sslTrustStoreLocation=C:\Users\Myuser\Downloads\DEV.jks;

I dont have any other JKS file(like Key JKS) only with above mentioned driver and this JKS file I can connect from DBVis.

Can Anyone help me how to connect to Db2 using ibm_db with above information and exact steps to set any path or installation.
Installed Python is Python 3.11.4
OS : Windows 11

Thanks in Advance.

**Comment by bimalkjha** [comment]
@shubsi33 .JKS format certificates are for Java applications and do not work with non-Java applications like Python ibm_db. It is wrong format certificate for ibm_db. You need to use a certificate generated using GSKit. Read details here: https://github.com/ibmdb/node-ibm_db/blob/master/APIDocumentation.md#SSLConnection Thanks.

**Comment by bimalkjha** [comment]
@shubsi33 You need to extract client certificate file from your JKS file using command `keytool -exportcert -alias your_certificate_alias -file client_certificate.crt -DEV.jks` and then use below connection string in python program:
```
connStr = "DATABASE=database;HOSTNAME=hostname;PORT=port;PROTOCOL=TCPIP;UID=username;PWD=passwd;" +
          "Security=SSL;SSLServerCertificate=C:/Users/Myuser/Downloads/client_certificate.crt";
```

Note that all the *.jar files under directory C:\Users\Myuser\Downloads\db2java\db2java are useless for ibm_db driver. ibm_db do not read any *.jar or *.jks file.
If using client_certificate.crt file in connection string, you are unable to connect and get communication error, then you need to ask for correct client certificate file to the same source from where you got DEV.jks file. 
`Secure Connection Certificates.zip` is available on IBM site for cloud database along with `IBMCertTrustStore` files. But, it seems you are not using that. SSL Certificates are server specific and different for different db2 database.

Where is your Db2 server? In cloud or in premise? What is the name of database if it is in cloud? What is the version of your db2server? From where you got DEV.jks file? Please provide all these info if issue still exist. Thanks.
