### ISSUE TITLE
import ibm_db giving error

### ISSUE THREAD

**Issue by hancockki** [ibmdb/python-ibmdb#929]
- Operating System Name: MacOS sonoma 14.4.1
- db2level output from clidriver if in use: dont know
- Target Db2 Server Version: 
- Python Version: 3.7.0
- ibm_db version: 3.2.3
- For non-Windows, output of below commands:
  uname
Darwin
  uname -m
x86_64
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
PATH=/usr/local/opt/postgresql@15/bin:/usr/local/opt/postgresql@15/bin:/Users/kimberlyhancock/go/bin:/usr/local/go/bin:/Users/kimberlyhancock/go/bin:/usr/local/go/bin:/Users/kimberlyhancock/go/bin:/usr/local/go/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/PostgreSQL/15/bin:/Library/PostgreSQL/16/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Users/kimberlyhancock/.local/bin:/Users/kimberlyhancock/.axiom/interact:/Users/kimberlyhancock/.local/bin:/Users/kimberlyhancock/.axiom/interact:/Users/kimberlyhancock/.local/bin:/Users/kimberlyhancock/.axiom/interact
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:
DYLD_LIBRARY_PATH='/Users/kimberlyhancock/Desktop/IBM-Cloud-ECIRT-Cloud-Inventory/Project-Snowglobe/.venv/lib/python3.7/site-packages/clidriver/lib/'

- Test script to reproduce the problem.
rm -r /Users/kimberlyhancock/Desktop/IBM-Cloud-ECIRT-Cloud-Inventory/Project-Snowglobe/.venv/lib/python3.7/site-packages/clidriver
pip3 uninstall ibm_db
pip3 install ibm_db

then running import ibm_db gives:
ImportError: dlopen(/Users/kimberlyhancock/Desktop/IBM-Cloud-ECIRT-Cloud-Inventory/Project-Snowglobe/.venv/lib/python3.7/site-packages/ibm_db.cpython-37m-darwin.so, 0x0002): Symbol not found: __ZNKSt8__detail20_Prime_rehash_policy14_M_need_rehashEmmm
  Referenced from: <803DFCA0-2956-3B4C-B633-4BCFBAA8B43A> /Users/kimberlyhancock/Desktop/IBM-Cloud-ECIRT-Cloud-Inventory/Project-Snowglobe/.venv/lib/python3.7/site-packages/clidriver/lib/libdb2.dylib
  Expected in:     <8D23CC51-7D92-32C9-8416-8D06AE3BA034> /usr/lib/libstdc++.6.dylib

- For installation related issue, complete output of `pip install ibm_db` command.
installation works fine
Steps to Reproduce:

1. 
2.

**Comment by bchoudhary6415** [comment]
Hello @hancockki 
Please try to follow the doc - https://github.com/ibmdb/python-ibmdb/blob/master/INSTALL.md#-3-ibm_db-installation-on-macos-m1m2-chip-system-arm64-architecture
to install ibm_db on macOS.
You are getting Symbol not found error.
Please check the section 4 - https://github.com/ibmdb/python-ibmdb/blob/master/INSTALL.md#-4-troubleshooting-post-install-errors, the point number 4.2

Please try to execute all the steps of point number 4.2.

Thanks

**Comment by bchoudhary6415** [comment]
Hello @hancockki 
Any update?
Please refer similar issue - https://github.com/ibmdb/python-ibmdb/issues/930

Thanks

**Comment by hancockki** [comment]
> no I am still getting the ssame issue after following steps of 4.2 above

**Comment by bchoudhary6415** [comment]
Hello @hancockki 
Please try to follow all the installation steps from starting once again: https://github.com/ibmdb/python-ibmdb/blob/master/INSTALL.md#-3-ibm_db-installation-on-macos-m1m2-chip-system-arm64-architecture
It may be something you missed.
And please share your tried steps for point number 4.2.

Thanks

**Comment by Earammak** [comment]
Hello @hancockki, since no update from your end we are closing this issue for now. 
If you still faced this issue, please feel free to open it again.

Thanks

**Comment by bimalkjha** [comment]
@hancockki We have released `ibm_db v3.2.5` with native installation support for MacOS Silicon Chip system and no need to use the emulated environment with x86_64 python on M1 chip system. Please install latest version of ibm_db and verify. Thanks.
