### ISSUE TITLE
Question: how do I set ibm_db.SQL_ATTR_TXN_ISOLATION with ibm_db_dbi?

### ISSUE THREAD

**Issue by j-bennet** [ibmdb/python-ibmdb#931]
In IBM org, I see examples like this one:

```
conn = dbi.connect()
conn.set_option({ dbi.SQL_ATTR_TXN_ISOLATION: dbi.SQL_TXN_NO_COMMIT })
```

https://github.com/IBM/ibmi-oss-examples/blob/37f17dc6527e1f28314e055c050bb426f5cfe0f1/machinelearning/dbconn/runsql.py#L24-L25

But the current `ibm_db_dbi` does not have `SQL_TXN_NO_COMMIT` or any other isolation level constants defined.

What's the right way to do that?

**Comment by Earammak** [comment]
@j-bennet, Support for the isolation level attributes has been added. Please verify through the latest pull request #932. 

Thanks

**Comment by j-bennet** [comment]
Thanks @Earammak!
