### ISSUE TITLE
Update trusted-context testscripts for current cldriver messages and also allow running from remote

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb#945]
- Operating System Name: linux x64
- db2level output from clidriver if in use: 11.5.0.9
- Target Db2 Server Version: Db2-LUW 11.5.8
- Python Version: 3.9.5, 3.10.2
- ibm_db version: 3.2.3
- For non-Windows, output of below commands:
  uname linux
  uname -m x86_64
- Value of below environment variables if set:
  IBM_DB_HOME: n/a
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH: (../clidriver/lib) (.../clidriver/bin)

- Test script to reproduce the problem. existing testscripts test_trusted_context_connect.py, test_trusted_context_pconnect.py

- For installation related issue, complete output of `pip install ibm_db` command. (not installation related)

Steps to Reproduce:

1. Run the existing testcases `test_trusted_context_connect.py` and `test_trusted_context_pconnect.py` against a Db2-LUW server, using a current version of clidriver (e.g. 11.5.9)
2. Expect both testscripts to PASS but instead they FAIL for two reasons (a) the messages output for some SQLCODEs are changed in cldriver for example with SQL0551N meaning that the expected-output does not match the actual-output,  and secondly (b) the testscripts only put the ADDRESS of the Db2-server into the trusted-context which in turn will cause failures if run on an hostname that is different from the Db2-server.

Narrative

Recent versions of clidriver changed the text of some messages and as a result the existing testscripts named `test_trusted_context_connect.py`  and `test_trusted_context_pconnect.py`
will always fail (when previously they would have passed). 

The failures happen because the expected output messages from CLI differ slightly for actual messages for SQL0551N, so the regular expressions (comparing expected-output to actual-output) will not match.

In addition, both of these testscripts create the trusted-context with the assumption that the testscripts will run on the same hostname as the Db2-server (only a single ADDRESS is specified).  As a consequence , when the trusted-context testscripts run on a different computer than the Db2-server, they will fail, because the trusted-context they create omits the local hostname, and only adds the hostname of the config.hostname (which __must__ be the Db2-server in order to connect successfully). 

Changing the testscript code so that the local hostname gets added as the ADDRESS when creating the trusted context will allow the testscripts to run remotely from the Db2-server, as well as locally on the Db2-server (where that is supported/workable).

I have made the code changes locally, and both testscripts now "PASS" when run from remote.

Should I create a PR for this? 

Or should I just attach the modified test-scripts here?
Or do you prefer to work out the testscript changes by yourselves?
Note: no code changes are needed in ibm_db.c itself, only to the two testscripts.

**Comment by Earammak** [comment]
@imavo, Please raise a pull request. Thanks

**Comment by imavo** [comment]
@Earammak P.R created
