### ISSUE TITLE
`Overflow occurred during numeric data type conversion` previously `Numeric value out of range` error

### ISSUE THREAD

**Issue by mattixpet** [ibmdb/python-ibmdb#949]
There seems to be an issue with the driver with the `DECIMAL(X,Y)` column types in DB2.

The issue is as follows:

Say I have a `DECIMAL(4,2)` which should allow 4 digits in the number, with up to 2 of them used after the decimal point. E.g. 100.9, 10.22, 1.3 etc.

However, it gives an error for any number over a 100 (4-2). So inputting 100.0 into `DECIMAL(4,2)` doesn't work. Doing it through SQL without the DB2 IBM driver is confirmed to work. It seems the driver automatically changes it into 100.00 which is too large for the column type.

- Operating System Name: Windows WSL Debian Bookworm
- Target Db2 Server Version: DB2 v11.5.7.0
- Python Version: 3.10.0
- ibm_db version: 
```
greenlet==3.0.3
ibm-db-sa==0.4.0
ibm_db==3.2.3
SQLAlchemy==2.0.31
typing_extensions==4.12.2
```
- For non-Windows, output of below commands:
  uname: Linux
  uname -m: x86_64

- Test script to reproduce the problem.
Python script:
```python
import os
from sqlalchemy import (
    create_engine,
    text,
)

def main():
    DATABASE_LOCATION = "db2+ibm_db://{user}:{password}@{host}:{port}/{database}".format(
        user="user",
        password=os.environ.get("MY_PASSWORD", None),
        host="db.domain.com",
        port="50020",
        database="db2db",
    )
    engine = create_engine(DATABASE_LOCATION)

    with engine.begin() as conn:
        conn.execute(text(
            "INSERT INTO DATA (TEMP) VALUES (200.0)"
        ))

if __name__ == "__main__":
    main()
```
Db2 table definition:
```
CREATE TABLE 
    DATA 
    (
        TEMP        DECIMAL(4,2)
    );
```

Steps to Reproduce:

1. Have any table with DECIMAL column type, see above.
2. Run python script, witness the error

**Comment by imavo** [comment]
I think that this is working as designed, in the sense that the SQL0413N is the expected result, when supplied literal values differ in format from the underlying column datatype.

You can observe this same result if you submit the SQL via either the Db2 command line processor, Db2 CLP, or from any jdbc app.  In other words, this is not specific to ibm_db module, but the same symptom happens for all interfaces.

**Comment by mattixpet** [comment]
It seems you are correct, I thought my colleague had inserted through DbVisualizer, but that turned out to be wrong.

It was a misunderstanding of the datatype. I thought for example DECIMAL(6,4) would mean it could have *UP TO* 4 digits after the decimal point, but seems it *ALWAYS* has 4. In which case indeed this is working as intended.
