### ISSUE TITLE
Documentation update for ibm_db.bind_param  data-type parameter

### ISSUE THREAD

**Issue by imavo** [ibmdb/python-ibmdb#958]
WIKI / Documentation update. Please fix the broken 'data-type' descriptive-text in the API specification for `ibm_db.bind_param` .

Currently the ibm_db.bind_parameter for `data-type` parameter reads as follows:
`
data-type - A constant specifying the SQL data type that the Python variable should be bound as:

    SQL_BINARY
    DB2_CHAR
    DB2_DOUBLE
    DB2_LONG
`

But this documentation is incorrect/incomplete in two ways, firstly three of those constants are misspelled ( they should be SQL_CHAR, SQL_DOUBLE, SQL_LONG ), and secondly the acceptable data-types are much more than the 4 listed in the API-specification, so that list needs expanding to include the types mentioned in the source-code. Those additionally supported are currently SQL_VARCHAR, SQL_LONGVARCHAR, SQL_WCHAR, SQL_WVARCHAR, SQL_GRAPHIC, SQL_VARGRAPHIC, SQL_LONGVARGRAPHIC, SQL_LONGVARBINARY, SQL_VARBINARY, SQL_BIGINT, SQL_DECFLOAT, SQL_TYPE_DATE, SQL_TYPE_TIME, SQL_TYPE_TIMESTAMP, SQL_SMALLINT, SQL_BOOLEAN, SQL_INTEGER, SQL_BIT, SQL_REAL, SQL_FLOAT, SQL_DECIMAL, SQL_NUMERIC, SQL_BLOB, SQL_CLOB, SQL_DBCLOB, SQL_XML.

Furthermore it would be helpful to mention the need to qualify these types with the ibm_db prefix, e.g. `ibm_db.SQL_VARCHAR` etc., and the need to match the chosen type to the target column-datatype or routine-parameter-datatype, in the database, to avoid possible conversion errors.

**Comment by Earammak** [comment]
@imavo, Thank you for mentioning that it needs to be corrected, and I have added other date types in documentation.

**Comment by imavo** [comment]
@Earammak that's good. For other doc updates to the wiki, is it best to open a ticket like this one, or is there a separate process (e.g. P.R) to get updates to the wiki (for example, spelling mistakes, typos, grammar , or other clarification etc.) ?

**Comment by imavo** [comment]
OK, understood, I should raise Issues for documentation problems, not a P.R.  You Can close this issue now.
