### ISSUE TITLE
Not able to run ibm db2 from AWS lambda using runtime python 3.8 or greater

### ISSUE THREAD

**Issue by isadoralmeida** [ibmdb/python-ibmdb#959]
I have some lambdas to trigger DB2 database, I have a Docker file to build this function lambda dependencies, but for some reason ibm_db does not working when updating lambda runtime from 3.7 (works fine) to >=3.8 with base image: lambci/lambda:build-python3.8

- Operating System Name: MacOS M3 Chip
- db2level output from clidriver if in use:
- Target Db2 Server Version:
- Python Version: 3.8 
- ibm_db version: 3.0.2
- For non-Windows, output of below commands:
  uname -> Darwin
  uname -m -> arm64
- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

- Test script to reproduce the problem:

import json
import os
import base64
import pytz
from datetime import datetime, timezone
import boto3
from botocore.exceptions import ClientError
import logging
import ibm_db
import shutil
from connector import Db2Conn

logger = logging.getLogger()
logger.setLevel(logging.INFO)

[...]

Error: {
  "errorMessage": "Unable to import module 'lambda_function': libpam.so.0: cannot open shared object file: No such file or directory",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}

- For installation related issue, complete output of `pip install ibm_db` command.

Collecting ibm_db
  Downloading ibm_db-3.2.3.tar.gz (210 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.2/210.2 kB 598.1 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      Detected 64-bit Python
      Arm64 architecture is not supported. Please install intel-only (x64) version of python and then install ibm_db.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: pip install --upgrade pip

**Comment by Earammak** [comment]
@isadoralmeida ,
From the above error it says that you are trying on amr64 version of python. 
ibm_db do not work with ARM64 version of python[https://github.com/ibmdb/python-ibmdb/tree/master?tab=readme-ov-file#known-limitations-for-the-python-driver].
To install ibm_db, please refer to: [https://github.com/ibmdb/python-ibmdb/blob/master/INSTALL.md#-3-ibm_db-installation-on-macos-m1m2-chip-system-arm64-architecture](url).


Thanks

**Comment by isadoralmeida** [comment]
Hi 
thanks for your response, do you know why for [lambci/lambda 3.7](https://hub.docker.com/r/lambci/lambda/)
works since I'm using amd64? But not for >= 3.8?

**Comment by bimalkjha** [comment]
@isadoralmeida I think your AWS lambda has Linux OS, right?
On Linux, arm64 architecture is not supported and ibm_db do not work. Yes, your python 3.7 is on amd64, so it is working.
I think you are installing ibm_db on aws lambda and not on your local macbook which has Apple Silicon chip, right? Thanks.

**Comment by isadoralmeida** [comment]
Hi 

Yes, correct, I'm installing ibm_db on aws lambda.  Using this dockerfile:


FROM lambci/lambda:build-python3.8

ARG filename

COPY requirements.txt /var/task/

RUN --mount=type=ssh pip install -r /var/task/requirements.txt -t /var/task/

COPY *.py *.crt /var/task/
COPY *.lic nodelock* /var/task/clidriver/license/

RUN cd /var/task && \
  rm -rf boto* && \
  rm -rf certifi* && \
  zip -X -q -r9 ${filename}.zip . && \
  rm -rf `find -type d -name __pycache__` && \
  find . -exec touch -t 201905211337.00 {} + && \
  hash=($(find . ! -path "*${filename}.zip" -type f -exec sha256sum {} \; | sort -k 1 | sha256sum)) && \
  echo $hash > ${filename}.sha256

**Comment by isadoralmeida** [comment]
Hi, I was able to use the package by passing these required dependencies for DB2:

# Install required dependencies for DB2
RUN yum install -y gcc-c++ make python3-devel 
RUN yum install -y pam.i686
RUN yum install -y audit-libs libcap-ng libcap-ng-devel
RUN yum install -y pam pam-devel
